SIBR: sibr::RGBInputTextureArray Class Reference
sibr::RGBInputTextureArray Class Reference
sibr_scene
#include <RenderTargetTextures.hpp>
Public Member Functions
virtual void initRGBTextureArrays (IInputImages::Ptr imgs, int flags=0)
const Texture2DArrayRGB::Ptr & getInputRGBTextureArrayPtr () const
Public Member Functions inherited from sibr::RTTextureSize
RTTextureSize (uint w=0)
void initSize (uint w, uint h)
bool isInit () const
Protected Attributes
Texture2DArrayRGB::Ptr _inputRGBArrayPtr
Protected Attributes inherited from sibr::RTTextureSize
uint _width = 0
uint _height = 0
bool _isInit = false
int _initActiveCam = 0
Detailed Description
Definition at line 70 of file RenderTargetTextures.hpp.
Member Function Documentation
getInputRGBTextureArrayPtr()
const Texture2DArrayRGB::Ptr & sibr::RGBInputTextureArray::getInputRGBTextureArrayPtr () const
Definition at line 191 of file RenderTargetTextures.cpp.
References _inputRGBArrayPtr.
initRGBTextureArrays()
void sibr::RGBInputTextureArray::initRGBTextureArrays (IInputImages::Ptr imgs, int flags = 0) virtual
Definition at line 182 of file RenderTargetTextures.cpp.
References sibr::RTTextureSize::_height, sibr::RTTextureSize::_initActiveCam, _inputRGBArrayPtr, sibr::RTTextureSize::_width, sibr::RTTextureSize::initSize(), and sibr::RTTextureSize::isInit().
Referenced by sibr::RenderTargetTextures::initRGBandDepthTextureArrays().
Member Data Documentation
_inputRGBArrayPtr
Texture2DArrayRGB::Ptr sibr::RGBInputTextureArray::_inputRGBArrayPtr protected
Definition at line 79 of file RenderTargetTextures.hpp.
Referenced by getInputRGBTextureArrayPtr(), and initRGBTextureArrays().
The documentation for this class was generated from the following files:
src/core/scene/RenderTargetTextures.hpp
src/core/scene/RenderTargetTextures.cpp