SIBR: sibr::ImagesGrid Class Reference
sibr::ImagesGrid Class Reference
#include <ImagesGrid.hpp>
Public Types
enum SelectionMode { NO_SELECTION, IMAGE_SELECTION, PIXEL_SELECTION }
Public Types inherited from sibr::ViewBase
typedef std::shared_ptr< ViewBase > Ptr
Public Member Functions
virtual void onUpdate (Input &input, const Viewport &vp) override
Update state based on user input.
virtual void onRender (const Viewport &viewport) override
Render content in the currently bound RT, using a specific viewport.
virtual void onRender (IRenderTarget &dst)
virtual void onGUI () override
Display GUI.
void addImagesToHighlight (const std::string &name, const std::vector< int > &imgs, const Vector3f &col, float alpha_fill=0)
void addPixelsToHighlight (const std::string &name, const std::vector< MVpixel > &pixs, const Vector3f &col, float alpha_fill=0)
const MVpixel & getCurrentPixel ()
template<typename T , uint N>
void addImageLayer (const std::string &layer_name, const std::vector< Image< T, N > > &images, uint flags=0)
template<typename T , uint N>
void addImageLayer (const std::string &layer_name, const std::vector< ImagePtr< T, N >> &images, uint flags=0)
template<typename T , uint N>
void addImageLayer (const std::string &layer_name, const std::shared_ptr< Texture2DArray< T, N >> &images)
template<typename T , uint N>
void addImageLayer (const std::string &layer_name, const std::vector< cv::Mat > &images, uint flags=0)
Public Member Functions inherited from sibr::ViewBase
ViewBase (const unsigned int w=720, const unsigned int h=480)
Constructor.
virtual ~ViewBase ()=default
Destructor.
virtual void onUpdate (Input &input)
virtual void onRender (Window &win)
Render content in a window.
virtual void onRenderIBR (IRenderTarget &dst, const Camera &eye)
Render content in a given rendertarget.
virtual void preRender (RenderTargetRGB &prev)
Legacy: Used to mix with previous pass.
virtual void whichRT (uint i)
Legacy: Set the internal RT to use.
virtual uint whichRT (void)
Legacy:
void setResolution (const Vector2i &size)
Set the view resolution.
const Vector2i & getResolution (void) const
void active (bool act)
Toggle view status.
bool active ()
void setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
bool isFocused (void) const
void setName (const std::string &name)
Define the name of the view (used for disambiguation of GUI, etc.).
const std::string & name () const
Protected Member Functions
void listImagesLayerGUI ()
void optionsGUI ()
bool name_collision (const std::string &name) const
void setupFirstLayer ()
Protected Attributes
std::list< ImageGridLayer > images_layers
std::list< ImageGridLayer >::iterator current_layer
ITexture2DArray::Ptr current_level_tex
int current_lod = 0
bool integer_pixel_values = true
std::map< std::string, HighlightData< MVpixel > > pixels_to_highlight
std::map< std::string, HighlightData< int > > images_to_highlight
MVpixel currentActivePix
SelectionMode selectionMode = IMAGE_SELECTION
Protected Attributes inherited from sibr::ViewBase
uint _whichRT
Selected RT id.
std::vector< RenderTargetLum::Ptr > _masks
Rendering masks that can beused by some views/renderers.
bool _active = true
Is the view active.
Vector2i _resolution
View resolution.
bool _focus = false
Is the view focused.
std::string _name = ""
View name.
Private Member Functions
SIBR_CLASS_PTR (ImagesGrid)
Private Member Functions inherited from sibr::GridMapping
MVpixel pixFromScreenPos (const Vector2i &pos, const Vector2f &size)
Vector2f uvFromMVpixel (const MVpixel &pix, bool use_center=false)
void updateZoomBox (const Input &input, const sibr::Viewport &vp)
void updateZoomScroll (const Input &input)
void updateCenter (const Input &input, const Vector2f &size)
void updateDrag (const Input &input, const Vector2f &size)
void displayZoom (const sibr::Viewport &viewport, DrawUtilities &utils)
void highlightPixel (const MVpixel &pix, const sibr::Viewport &viewport, const sibr::Vector3f &color={ 0, 1, 0 }, const sibr::Vector2f &minPixSize={ 10.0f, 10.0f })
void highlightImage (int im, const sibr::Viewport &viewport, const sibr::Vector3f &color={ 0, 1, 0 }, float alpha=0)
void setupGrid (const Viewport &vp)
Additional Inherited Members
Private Attributes inherited from sibr::GridMapping
DrawUtilities draw_utils
Viewport _vp
QuadData viewRectangle
QuadSelectionData zoomSelection
DragClickData drag
int num_per_row = 4
Vector2f grid_adjusted
Vector2f imSizePixels
int num_imgs
Detailed Description
Definition at line 162 of file ImagesGrid.hpp.
Member Enumeration Documentation
SelectionMode
enum sibr::ImagesGrid::SelectionMode
Enumerator
NO_SELECTION
IMAGE_SELECTION
PIXEL_SELECTION
Definition at line 168 of file ImagesGrid.hpp.
Member Function Documentation
addImageLayer() [1/4]
template<typename T , uint N> void sibr::ImagesGrid::addImageLayer (const std::string & layer_name, const std::shared_ptr< Texture2DArray< T, N >> & images) inline
Definition at line 230 of file ImagesGrid.hpp.
References sibr::ImageGridLayer::imgs_texture_array, and sibr::ImageGridLayer::name.
addImageLayer() [2/4]
template<typename T , uint N> void sibr::ImagesGrid::addImageLayer (const std::string & layer_name, const std::vector< cv::Mat > & images, uint flags = 0) inline
Definition at line 248 of file ImagesGrid.hpp.
References sibr::ImageGridLayer::imgs_texture_array, sibr::ImageGridLayer::name, and SIBR_GPU_AUTOGEN_MIPMAP.
addImageLayer() [3/4]
template<typename T , uint N> void sibr::ImagesGrid::addImageLayer (const std::string & layer_name, const std::vector< Image< T, N > > & images, uint flags = 0) inline
Definition at line 204 of file ImagesGrid.hpp.
addImageLayer() [4/4]
template<typename T , uint N> void sibr::ImagesGrid::addImageLayer (const std::string & layer_name, const std::vector< ImagePtr< T, N >> & images, uint flags = 0) inline
Definition at line 217 of file ImagesGrid.hpp.
addImagesToHighlight()
void sibr::ImagesGrid::addImagesToHighlight (const std::string & name, const std::vector< int > & imgs, const Vector3f & col, float alpha_fill = 0)
Definition at line 128 of file ImagesGrid.cpp.
References images_to_highlight, and sibr::ViewBase::name().
Referenced by onUpdate().
addPixelsToHighlight()
void sibr::ImagesGrid::addPixelsToHighlight (const std::string & name, const std::vector< MVpixel > & pixs, const Vector3f & col, float alpha_fill = 0)
Definition at line 133 of file ImagesGrid.cpp.
References sibr::ViewBase::name(), and pixels_to_highlight.
Referenced by onUpdate().
getCurrentPixel()
const MVpixel & sibr::ImagesGrid::getCurrentPixel ()
Definition at line 138 of file ImagesGrid.cpp.
References currentActivePix.
listImagesLayerGUI()
void sibr::ImagesGrid::listImagesLayerGUI () protected
Definition at line 143 of file ImagesGrid.cpp.
References current_layer, current_level_tex, GUI_TEXT, and images_layers.
Referenced by onGUI().
name_collision()
bool sibr::ImagesGrid::name_collision (const std::string & name) const protected
Definition at line 215 of file ImagesGrid.cpp.
References images_layers, and sibr::ViewBase::name().
onGUI()
void sibr::ImagesGrid::onGUI () override virtual
Display GUI.
Reimplemented from sibr::ViewBase.
Definition at line 94 of file ImagesGrid.cpp.
References current_layer, current_lod, currentActivePix, sibr::Key::End, GUI_TEXT, sibr::MVpixel::im, integer_pixel_values, listImagesLayerGUI(), optionsGUI(), and sibr::MVpixel::pos.
onRender() [1/2]
void sibr::ImagesGrid::onRender (const Viewport & vpRender) override virtual
Render content in the currently bound RT, using a specific viewport.
Parameters
vpRender destination viewport
Note
Used when the view is in a multi-view system.
Reimplemented from sibr::ViewBase.
Definition at line 55 of file ImagesGrid.cpp.
References sibr::Viewport::bind(), sibr::QuadData::br(), sibr::Viewport::clear(), current_layer, current_level_tex, current_lod, sibr::GridMapping::displayZoom(), sibr::GridMapping::draw_utils, sibr::GridMapping::grid_adjusted, sibr::GridMapping::highlightImage(), sibr::GridMapping::highlightPixel(), sibr::DrawUtilities::image_grid(), images_to_highlight, sibr::GridMapping::num_imgs, pixels_to_highlight, sibr::QuadData::tl(), and sibr::GridMapping::viewRectangle.
Referenced by onRender().
onRender() [2/2]
void sibr::ImagesGrid::onRender (IRenderTarget & dst) virtual
Definition at line 84 of file ImagesGrid.cpp.
References ibr_preprocess_rc_to_sibr::dst, and onRender().
onUpdate()
void sibr::ImagesGrid::onUpdate (Input & input, const Viewport & vp) override virtual
Update state based on user input.
Parameters
input user input
vp input viewport
Note
Used when the view is in a multi-view system.
Reimplemented from sibr::ViewBase.
Definition at line 9 of file ImagesGrid.cpp.
References sibr::GridMapping::_vp, addImagesToHighlight(), addPixelsToHighlight(), current_layer, current_level_tex, current_lod, currentActivePix, sibr::Viewport::finalSize(), sibr::MVpixel::im, IMAGE_SELECTION, sibr::GridMapping::imSizePixels, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Input::key(), sibr::Key::Left, sibr::Key::LeftControl, sibr::Input::mouseButton(), sibr::Input::mousePosition(), sibr::GridMapping::num_imgs, PIXEL_SELECTION, sibr::GridMapping::pixFromScreenPos(), selectionMode, sibr::GridMapping::setupGrid(), sibr::GridMapping::updateDrag(), sibr::GridMapping::updateZoomBox(), and sibr::GridMapping::updateZoomScroll().
optionsGUI()
void sibr::ImagesGrid::optionsGUI () protected
Definition at line 188 of file ImagesGrid.cpp.
References sibr::QuadData::center, current_lod, currentActivePix, sibr::QuadData::diagonal, integer_pixel_values, sibr::MVpixel::isDefined, sibr::GridMapping::num_imgs, sibr::GridMapping::num_per_row, selectionMode, and sibr::GridMapping::viewRectangle.
Referenced by onGUI().
setupFirstLayer()
void sibr::ImagesGrid::setupFirstLayer () protected
Definition at line 225 of file ImagesGrid.cpp.
References current_layer, current_level_tex, and images_layers.
SIBR_CLASS_PTR()
sibr::ImagesGrid::SIBR_CLASS_PTR (ImagesGrid) private
Member Data Documentation
current_layer
std::list<ImageGridLayer>::iterator sibr::ImagesGrid::current_layer protected
Definition at line 191 of file ImagesGrid.hpp.
Referenced by listImagesLayerGUI(), onGUI(), onRender(), onUpdate(), and setupFirstLayer().
current_level_tex
ITexture2DArray::Ptr sibr::ImagesGrid::current_level_tex protected
Definition at line 192 of file ImagesGrid.hpp.
Referenced by listImagesLayerGUI(), onRender(), onUpdate(), and setupFirstLayer().
current_lod
int sibr::ImagesGrid::current_lod = 0 protected
Definition at line 193 of file ImagesGrid.hpp.
Referenced by onGUI(), onRender(), onUpdate(), and optionsGUI().
currentActivePix
MVpixel sibr::ImagesGrid::currentActivePix protected
Definition at line 199 of file ImagesGrid.hpp.
Referenced by getCurrentPixel(), onGUI(), onUpdate(), and optionsGUI().
images_layers
std::list<ImageGridLayer> sibr::ImagesGrid::images_layers protected
Definition at line 190 of file ImagesGrid.hpp.
Referenced by listImagesLayerGUI(), name_collision(), and setupFirstLayer().
images_to_highlight
std::map<std::string, HighlightData<int> > sibr::ImagesGrid::images_to_highlight protected
Definition at line 197 of file ImagesGrid.hpp.
Referenced by addImagesToHighlight(), and onRender().
integer_pixel_values
bool sibr::ImagesGrid::integer_pixel_values = true protected
Definition at line 194 of file ImagesGrid.hpp.
Referenced by onGUI(), and optionsGUI().
pixels_to_highlight
std::map< std::string, HighlightData<MVpixel> > sibr::ImagesGrid::pixels_to_highlight protected
Definition at line 196 of file ImagesGrid.hpp.
Referenced by addPixelsToHighlight(), and onRender().
selectionMode
SelectionMode sibr::ImagesGrid::selectionMode = IMAGE_SELECTION protected
Definition at line 200 of file ImagesGrid.hpp.
Referenced by onUpdate(), and optionsGUI().
The documentation for this class was generated from the following files:
src/core/view/ImagesGrid.hpp
src/core/view/ImagesGrid.cpp