SIBR: sibr::RequiredArgBase< T > Class Template Reference
sibr::RequiredArgBase< T > Class Template Reference
sibr_system
Represent a mandatory argument.
#include <CommandLineArgs.hpp>
Public Member Functions
RequiredArgBase (const std::string &_key, const std::string &description="")
Constructor.
operator const T & () const
const T & get () const
T & operator= (const T &t)
Copy operator.
const bool & isInit () const
Protected Member Functions
void checkInit () const
Check if the argument was init.If not, as it is a required argument we display the help message and raise an error.
Protected Attributes
std::string key
Argument key.
T value
Argument value.
bool wasInit = false
Was the argument initialized.
Detailed Description
template<typename T>
class sibr::RequiredArgBase< T >
Represent a mandatory argument.
Definition at line 255 of file CommandLineArgs.hpp.
Constructor & Destructor Documentation
RequiredArgBase()
template<typename T > sibr::RequiredArgBase< T >::RequiredArgBase (const std::string & _key, const std::string & description = "") inline
Constructor.
Parameters
_key the command argument
description help message description
Definition at line 261 of file CommandLineArgs.hpp.
Member Function Documentation
checkInit()
template<typename T > void sibr::RequiredArgBase< T >::checkInit () const inline protected
Check if the argument was init.If not, as it is a required argument we display the help message and raise an error.
Definition at line 287 of file CommandLineArgs.hpp.
Referenced by sibr::RequiredArgBase< std::string >::get(), sibr::RequiredArg< std::string >::operator const char *(), and sibr::RequiredArgBase< T >::operator const T &().
get()
template<typename T > const T& sibr::RequiredArgBase< T >::get () const inline
Returns
a reference to the argument value
Definition at line 273 of file CommandLineArgs.hpp.
Referenced by sibr::ParseData::getParsedData(), main(), and sibr::SceneDebugView::SceneDebugView().
isInit()
template<typename T > const bool& sibr::RequiredArgBase< T >::isInit () const inline
Returns
true if the argument was given
Definition at line 282 of file CommandLineArgs.hpp.
Referenced by main().
operator const T &()
template<typename T > sibr::RequiredArgBase< T >::operator const T & () const inline
Returns
a reference to the argument value
Definition at line 270 of file CommandLineArgs.hpp.
References sibr::RequiredArgBase< T >::checkInit(), and sibr::RequiredArgBase< T >::value.
operator=()
template<typename T > T& sibr::RequiredArgBase< T >::operator= (const T & t) inline
Copy operator.
Parameters
t the value to copy
Returns
a reference to the argument value
Definition at line 279 of file CommandLineArgs.hpp.
Member Data Documentation
key
template<typename T > std::string sibr::RequiredArgBase< T >::key protected
Argument key.
Definition at line 294 of file CommandLineArgs.hpp.
Referenced by sibr::RequiredArgBase< std::string >::checkInit(), and sibr::RequiredArgBase< std::string >::RequiredArgBase().
value
template<typename T > T sibr::RequiredArgBase< T >::value protected
Argument value.
Definition at line 295 of file CommandLineArgs.hpp.
Referenced by sibr::RequiredArgBase< std::string >::get(), sibr::RequiredArg< std::string >::operator const char *(), sibr::RequiredArgBase< T >::operator const T &(), sibr::RequiredArgBase< std::string >::operator=(), sibr::RequiredArg< std::string >::operator=(), and sibr::RequiredArgBase< std::string >::RequiredArgBase().
wasInit
template<typename T > bool sibr::RequiredArgBase< T >::wasInit = false protected
Was the argument initialized.
Definition at line 296 of file CommandLineArgs.hpp.
Referenced by sibr::RequiredArgBase< std::string >::checkInit(), sibr::RequiredArgBase< std::string >::isInit(), sibr::RequiredArgBase< std::string >::operator=(), sibr::RequiredArg< std::string >::operator=(), and sibr::RequiredArgBase< std::string >::RequiredArgBase().
The documentation for this class was generated from the following file:
src/core/system/CommandLineArgs.hpp