SIBR: sibr::ULRView Class Reference
sibr::ULRView Class Reference
View associated to ULRRenderer v1, providing interface and options.
#include <ULRView.hpp>
Public Member Functions
ULRView (const sibr::BasicIBRScene::Ptr &ibrScene, uint render_w, uint render_h)
Constructor.
~ULRView ()
Destructor.
virtual void onRenderIBR (sibr::IRenderTarget &dst, const sibr::Camera &eye)
Render using the ULR algorithm.
virtual std::vector< uint > chosen_cameras (const sibr::Camera &eye)
Select input cameras to use for rendering.
void altMesh (std::shared_ptr< sibr::Mesh > m)
Set the altMesh and use instead of scene proxy.
void doOccl (bool val)
Toggle occlusion testing.
std::shared_ptr< sibr::Mesh > altMesh ()
void setNumBlend (short int dist, short int angle)
Set the number of cmaeras to select for blending.
void inputRTs (const std::vector< std::shared_ptr< RenderTargetRGBA32F > > &iRTs)
Set the input RGBD textures.
void setMasks (const std::vector< RenderTargetLum::Ptr > &masks)
Set the masks for ignoring some regions of the input images.
Public Member Functions inherited from sibr::ViewBase
ViewBase (const unsigned int w=720, const unsigned int h=480)
Constructor.
virtual ~ViewBase ()=default
Destructor.
virtual void onUpdate (Input &input)
virtual void onRender (Window &win)
Render content in a window.
virtual void onGUI ()
Display GUI.
virtual void onRender (const Viewport &vpRender)
Render content in the currently bound RT, using a specific viewport.
virtual void onUpdate (Input &input, const Viewport &vp)
Update state based on user input.
virtual void preRender (RenderTargetRGB &prev)
Legacy: Used to mix with previous pass.
virtual void whichRT (uint i)
Legacy: Set the internal RT to use.
virtual uint whichRT (void)
Legacy:
void setResolution (const Vector2i &size)
Set the view resolution.
const Vector2i & getResolution (void) const
void active (bool act)
Toggle view status.
bool active ()
void setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
bool isFocused (void) const
void setName (const std::string &name)
Define the name of the view (used for disambiguation of GUI, etc.).
const std::string & name () const
Protected Attributes
ULRRenderer::Ptr _ulr
Renderer.
std::shared_ptr< sibr::BasicIBRScene > _scene
Scene.
std::shared_ptr< sibr::Mesh > _altMesh
For the cases when using a different mesh than the scene.
short int _numDistUlr
short int _numAnglUlr
max number of selected cameras for each criterion.
std::vector< std::shared_ptr< RenderTargetRGBA32F > > _inputRTs
input RTs – usually RGB but can be alpha or other
Protected Attributes inherited from sibr::ViewBase
uint _whichRT
Selected RT id.
std::vector< RenderTargetLum::Ptr > _masks
Rendering masks that can beused by some views/renderers.
bool _active = true
Is the view active.
Vector2i _resolution
View resolution.
bool _focus = false
Is the view focused.
std::string _name = ""
View name.
Private Member Functions
SIBR_CLASS_PTR (ULRView)
Additional Inherited Members
Public Types inherited from sibr::ViewBase
typedef std::shared_ptr< ViewBase > Ptr
Detailed Description
View associated to ULRRenderer v1, providing interface and options.
Definition at line 14 of file ULRView.hpp.
Constructor & Destructor Documentation
ULRView()
sibr::ULRView::ULRView (const sibr::BasicIBRScene::Ptr & ibrScene, uint render_w, uint render_h)
Constructor.
Parameters
ibrScene the scene
render_w rendering width
render_h rendering height
Definition at line 17 of file ULRView.cpp.
References _altMesh, _inputRTs, _numAnglUlr, _numDistUlr, and _ulr.
~ULRView()
sibr::ULRView::~ULRView ()
Destructor.
Definition at line 12 of file ULRView.cpp.
References _altMesh.
Member Function Documentation
altMesh() [1/2]
std::shared_ptr<sibr::Mesh> sibr::ULRView::altMesh () inline
Returns
a pointer to the alt mesh if it exists
Definition at line 53 of file ULRView.hpp.
altMesh() [2/2]
void sibr::ULRView::altMesh (std::shared_ptr< sibr::Mesh > m) inline
Set the altMesh and use instead of scene proxy.
Parameters
m mesh to use
Definition at line 45 of file ULRView.hpp.
chosen_cameras()
std::vector< uint > sibr::ULRView::chosen_cameras (const sibr::Camera & eye) virtual
Select input cameras to use for rendering.
Parameters
eye the current viewpoint
Returns
a list of camera indices.
Todo:
Select a subset from imput images speed up URL
Todo:
TODO: This function needs serious cleanup
Definition at line 48 of file ULRView.cpp.
References _numAnglUlr, _numDistUlr, _scene, sibr::Camera::dir(), sibr::distance(), sibr::dot(), sibr::InputCamera::isActive(), sibr::Camera::position(), and SIBR_ASSERT.
Referenced by onRenderIBR().
doOccl()
void sibr::ULRView::doOccl (bool val) inline
Toggle occlusion testing.
Parameters
val should occlusion testing be performed
Definition at line 50 of file ULRView.hpp.
inputRTs()
void sibr::ULRView::inputRTs (const std::vector< std::shared_ptr< RenderTargetRGBA32F > > & iRTs) inline
Set the input RGBD textures.
Parameters
iRTs the new textures to use.
Definition at line 64 of file ULRView.hpp.
onRenderIBR()
void sibr::ULRView::onRenderIBR (sibr::IRenderTarget & dst, const sibr::Camera & eye) virtual
Render using the ULR algorithm.
Parameters
dst destination target
eye novel viewpoint
Reimplemented from sibr::ViewBase.
Definition at line 31 of file ULRView.cpp.
References _altMesh, _inputRTs, _scene, _ulr, chosen_cameras(), and ibr_preprocess_rc_to_sibr::dst.
setMasks()
void sibr::ULRView::setMasks (const std::vector< RenderTargetLum::Ptr > & masks)
Set the masks for ignoring some regions of the input images.
Parameters
masks the new masks
Definition at line 95 of file ULRView.cpp.
References _ulr.
setNumBlend()
void sibr::ULRView::setNumBlend (short int dist, short int angle) inline
Set the number of cmaeras to select for blending.
Parameters
dist number of cameras for the distance criterion
angle number of cameras for the angle criterion
Definition at line 59 of file ULRView.hpp.
SIBR_CLASS_PTR()
sibr::ULRView::SIBR_CLASS_PTR (ULRView) private
Member Data Documentation
_altMesh
std::shared_ptr<sibr::Mesh> sibr::ULRView::_altMesh protected
For the cases when using a different mesh than the scene.
Definition at line 75 of file ULRView.hpp.
Referenced by onRenderIBR(), ULRView(), and ~ULRView().
_inputRTs
std::vector<std::shared_ptr<RenderTargetRGBA32F> > sibr::ULRView::_inputRTs protected
input RTs – usually RGB but can be alpha or other
Definition at line 77 of file ULRView.hpp.
Referenced by onRenderIBR(), and ULRView().
_numAnglUlr
short int sibr::ULRView::_numAnglUlr protected
max number of selected cameras for each criterion.
Definition at line 76 of file ULRView.hpp.
Referenced by chosen_cameras(), and ULRView().
_numDistUlr
short int sibr::ULRView::_numDistUlr protected
Definition at line 76 of file ULRView.hpp.
Referenced by chosen_cameras(), and ULRView().
_scene
std::shared_ptr<sibr::BasicIBRScene> sibr::ULRView::_scene protected
Scene.
Definition at line 74 of file ULRView.hpp.
Referenced by chosen_cameras(), and onRenderIBR().
_ulr
ULRRenderer::Ptr sibr::ULRView::_ulr protected
Renderer.
Definition at line 73 of file ULRView.hpp.
Referenced by onRenderIBR(), setMasks(), and ULRView().
The documentation for this class was generated from the following files:
src/projects/ulr/renderer/ULRView.hpp
src/projects/ulr/renderer/ULRView.cpp