SIBR: sibr::PoissonReconstruction Class Reference
sibr::PoissonReconstruction Class Reference
sibr_imgproc
Performs gradient integration for tasks such as Poisson-based inpainting, smooth filling, ...
#include <PoissonReconstruction.hpp>
Public Member Functions
PoissonReconstruction (const cv::Mat3f &gradientsX, const cv::Mat3f &gradientsY, const cv::Mat1f &mask, const cv::Mat3f &img_target)
Initialize reconstructor for a given problem.
void solve (void)
Solve the reconstruction problem.
cv::Mat result () const
Static Public Member Functions
static std::vector< sibr::Vector2i > getNeighbors (sibr::Vector2i pos, int width, int height)
helper to get the pixel coordinates of valid pixels for agiven pixel and image size.
static void computeGradients (const cv::Mat3f &src, cv::Mat3f &gradX, cv::Mat3f &gradY)
Compute the gradients of an RGB32F matrix using forward finite differences.
Private Member Functions
void parseMask (void)
Parse the mask and the additional label condition into a list of pixels to modified and boundaries conditions.
void checkConnectivity (void)
Make sure that every modified pixel is connected to some boundary condition, all non connected pixels are discarded.
void postProcessing (void)
Heuristic to fill isolated black pixels.
bool isInMask (sibr::Vector2i &pos)
Are we in the mask (ie mask==0).
bool isIgnored (sibr::Vector2i &pos)
Private Attributes
cv::Mat _img_target
Main image.
cv::Mat _gradientsX
Gradients.
cv::Mat _gradientsY
Gradients.
cv::Mat _mask
Mask guide.
std::vector< sibr::Vector2i > _pixels
list of valid pixels.
std::vector< sibr::Vector2i > _boundaryPixels
List of boundary pixels.
std::vector< int > _pixelsId
Pixel IDs list.
std::vector< std::vector< int > > _neighborMap
Each pixel valid neighbors.
Detailed Description
Performs gradient integration for tasks such as Poisson-based inpainting, smooth filling, ...
See the constructor for additional details.
Definition at line 13 of file PoissonReconstruction.hpp.
Constructor & Destructor Documentation
PoissonReconstruction()
sibr::PoissonReconstruction::PoissonReconstruction (const cv::Mat3f & gradientsX, const cv::Mat3f & gradientsY, const cv::Mat1f & mask, const cv::Mat3f & img_target)
Initialize reconstructor for a given problem.
Gradients and target are expected to be RGB32F, mask is L32F. In the mask, pixels with value = 0 are to be inpainted, value > 0.5 are pixels to be used as source/constraint, value < -0.5 are pixels to be left unchanged and unused. To compute the gradients from an image, prefer using PoissonReconstruction::computeGradients (weird results have been observed when using cv::Sobel and similar).
Parameters
gradientsX the RGB32F horizontal color gradients to integrate along
gradientsY the RGB32F vertical color gradients to integrate along
mask the L32F mask denoting how each pixel should be treated.
img_target the RGB32 image to use as a source constraint (will be copied internally)
Definition at line 10 of file PoissonReconstruction.cpp.
References _gradientsX, _gradientsY, _img_target, and _mask.
Member Function Documentation
checkConnectivity()
void sibr::PoissonReconstruction::checkConnectivity (void) private
Make sure that every modified pixel is connected to some boundary condition, all non connected pixels are discarded.
Definition at line 204 of file PoissonReconstruction.cpp.
References _boundaryPixels, _img_target, _mask, _pixelsId, getNeighbors(), isIgnored(), and isInMask().
Referenced by parseMask().
computeGradients()
void sibr::PoissonReconstruction::computeGradients (const cv::Mat3f & src, cv::Mat3f & gradX, cv::Mat3f & gradY) static
Compute the gradients of an RGB32F matrix using forward finite differences.
Parameters
src the matrix to compute the gradients of
gradX will contain the horizontal gradients
gradY will contain the vertical gradients
Definition at line 184 of file PoissonReconstruction.cpp.
References ibr_preprocess_rc_to_sibr::src.
getNeighbors()
std::vector< sibr::Vector2i > sibr::PoissonReconstruction::getNeighbors (sibr::Vector2i pos, int width, int height) static
helper to get the pixel coordinates of valid pixels for agiven pixel and image size.
Parameters
pos the central pixel position
width number of columns/width
height number of rows/height
Returns
a vector containing neighboring pixels coordinates.
Definition at line 168 of file PoissonReconstruction.cpp.
Referenced by checkConnectivity(), parseMask(), postProcessing(), and solve().
isIgnored()
bool sibr::PoissonReconstruction::isIgnored (sibr::Vector2i & pos) private
Definition at line 298 of file PoissonReconstruction.cpp.
References _mask.
Referenced by checkConnectivity(), parseMask(), and solve().
isInMask()
bool sibr::PoissonReconstruction::isInMask (sibr::Vector2i & pos) private
Are we in the mask (ie mask==0).
Parameters
pos the pixel to test for
Returns
true if mask(pix) == 0
Definition at line 292 of file PoissonReconstruction.cpp.
References _mask.
Referenced by checkConnectivity(), parseMask(), and solve().
parseMask()
void sibr::PoissonReconstruction::parseMask (void) private
Parse the mask and the additional label condition into a list of pixels to modified and boundaries conditions.
Definition at line 117 of file PoissonReconstruction.cpp.
References _boundaryPixels, _img_target, _mask, _pixels, _pixelsId, checkConnectivity(), getNeighbors(), isIgnored(), and isInMask().
Referenced by solve().
postProcessing()
void sibr::PoissonReconstruction::postProcessing (void) private
Heuristic to fill isolated black pixels.
Definition at line 250 of file PoissonReconstruction.cpp.
References _img_target, _mask, sibr::Key::count, and getNeighbors().
Referenced by solve().
result()
cv::Mat sibr::PoissonReconstruction::result () const inline
Returns
the result of the reconstruction
Definition at line 36 of file PoissonReconstruction.hpp.
Referenced by sibr::MeshTexturing::poissonFill().
solve()
void sibr::PoissonReconstruction::solve (void)
Solve the reconstruction problem.
Definition at line 24 of file PoissonReconstruction.cpp.
References _gradientsX, _gradientsY, _img_target, _mask, _pixels, _pixelsId, sibr::Key::A, getNeighbors(), isIgnored(), isInMask(), parseMask(), and postProcessing().
Referenced by sibr::MeshTexturing::poissonFill().
Member Data Documentation
_boundaryPixels
std::vector<sibr::Vector2i> sibr::PoissonReconstruction::_boundaryPixels private
List of boundary pixels.
Definition at line 60 of file PoissonReconstruction.hpp.
Referenced by checkConnectivity(), and parseMask().
_gradientsX
cv::Mat sibr::PoissonReconstruction::_gradientsX private
Gradients.
Definition at line 55 of file PoissonReconstruction.hpp.
Referenced by PoissonReconstruction(), and solve().
_gradientsY
cv::Mat sibr::PoissonReconstruction::_gradientsY private
Gradients.
Definition at line 56 of file PoissonReconstruction.hpp.
Referenced by PoissonReconstruction(), and solve().
_img_target
cv::Mat sibr::PoissonReconstruction::_img_target private
Main image.
Definition at line 54 of file PoissonReconstruction.hpp.
Referenced by checkConnectivity(), parseMask(), PoissonReconstruction(), postProcessing(), and solve().
_mask
cv::Mat sibr::PoissonReconstruction::_mask private
Mask guide.
Definition at line 57 of file PoissonReconstruction.hpp.
Referenced by checkConnectivity(), isIgnored(), isInMask(), parseMask(), PoissonReconstruction(), postProcessing(), and solve().
_neighborMap
std::vector<std::vector<int> > sibr::PoissonReconstruction::_neighborMap private
Each pixel valid neighbors.
Definition at line 62 of file PoissonReconstruction.hpp.
_pixels
std::vector<sibr::Vector2i> sibr::PoissonReconstruction::_pixels private
list of valid pixels.
Definition at line 59 of file PoissonReconstruction.hpp.
Referenced by parseMask(), and solve().
_pixelsId
std::vector<int > sibr::PoissonReconstruction::_pixelsId private
Pixel IDs list.
Definition at line 61 of file PoissonReconstruction.hpp.
Referenced by checkConnectivity(), parseMask(), and solve().
The documentation for this class was generated from the following files:
src/core/imgproc/PoissonReconstruction.hpp
src/core/imgproc/PoissonReconstruction.cpp