SIBR: sibr::MRFSolver Class Reference
sibr::MRFSolver Class Reference
sibr_imgproc
Object wrapper around Kolmogorov & Boykov MRF solver.
#include <MRFSolver.h>
Public Types
typedef std::shared_ptr< std::function< double(int, int)> > UnaryFuncPtr
Unary cost function that depend on node attributes and its label.
typedef std::shared_ptr< std::function< double(int, int, int, int)> > PairwiseFuncPtr
Pairwise cost function that depend on node attributes and their labels.
typedef std::shared_ptr< std::function< double(int)> > UnaryLabelOnlyFuncPtr
Unary cost function that only depend on the label.
typedef std::shared_ptr< std::function< double(int, int)> > PairwiseLabelOnlyFuncPtr
Pairwise cost function that only depend on the labels.
Public Member Functions
MRFSolver (void)
Default constructor.
MRFSolver (std::vector< int > labels, std::vector< std::vector< int > > *neighborMap, int numIterations, UnaryLabelOnlyFuncPtr unaryLabelOnly, UnaryFuncPtr unaryFull, PairwiseLabelOnlyFuncPtr pairwiseLabelsOnly, PairwiseFuncPtr pairwiseFull)
Initialize from a set of labels, connections and node/edge weights.
void solveLabels (void)
Solve using alpha expansion. When you have only two labels, use solveBinaryLabels instead.
void solveBinaryLabels (void)
Solve for binary labels: if you only more than two labels, call solveLabels instead.
std::vector< int > getLabels (void)
For each pixel, get the estimated label (call either solveLabels or solveBinaryLabels before).
double getTotalEnergy (void)
double computeEnergyU (void)
double computeEnergyW (void)
std::vector< double > getUnariesEnergies (void)
~MRFSolver (void)
Destructor.
Private Types
typedef Graph< double, double, double > GraphType
Private Member Functions
void buildGraphAlphaExp (int label_iteration_id)
Build graph for the general case.
void buildGraphBinaryLabels (void)
Build graph for the binary labeling case.
double unaryTotal (int p, int lp_id)
Compute the unary cost of a node.
double pairwiseTotal (int p, int q, int lp_id, int lq_id)
Compute the pairwise cost of a pair of nodes.
Private Attributes
std::vector< int > _labList
Map the label_id to the actual labels.
std::vector< int > _labels
Assign each node its current best label_id.
std::vector< std::vector< int > > * _neighborMap
For each variable, gives the list of its neighbor variables.
int _numIterations
Number of iterations in alpha expansion.
std::vector< double > _UnaryLabelOnly
Unaries only requiring label.
std::shared_ptr< std::function< double(int, int)> > _unaryFull
Unaries requiring label and variable.
std::vector< std::vector< double > > _PairwiseLabelsOnly
Pairwises only requiring labels.
std::shared_ptr< std::function< double(int, int, int, int)> > _pairwiseFull
Pairwises requiring labels and variables.
double _energy
Total energy.
GraphType * _graph
Graph.
bool ignoreIsolatedNode
Ignore nodes with no connections.
Detailed Description
Object wrapper around Kolmogorov & Boykov MRF solver.
Solve labelling problems on regular grids using alpha expension.
Definition at line 17 of file MRFSolver.h.
Member Typedef Documentation
GraphType
typedef Graph<double, double, double> sibr::MRFSolver::GraphType private
Definition at line 109 of file MRFSolver.h.
PairwiseFuncPtr
typedef std::shared_ptr<std::function<double(int, int, int, int)> > sibr::MRFSolver::PairwiseFuncPtr
Pairwise cost function that depend on node attributes and their labels.
Definition at line 23 of file MRFSolver.h.
PairwiseLabelOnlyFuncPtr
typedef std::shared_ptr<std::function<double(int, int)> > sibr::MRFSolver::PairwiseLabelOnlyFuncPtr
Pairwise cost function that only depend on the labels.
Definition at line 26 of file MRFSolver.h.
UnaryFuncPtr
typedef std::shared_ptr<std::function<double(int, int)> > sibr::MRFSolver::UnaryFuncPtr
Unary cost function that depend on node attributes and its label.
Definition at line 22 of file MRFSolver.h.
UnaryLabelOnlyFuncPtr
typedef std::shared_ptr<std::function<double(int)> > sibr::MRFSolver::UnaryLabelOnlyFuncPtr
Unary cost function that only depend on the label.
Definition at line 25 of file MRFSolver.h.
Constructor & Destructor Documentation
MRFSolver() [1/2]
sibr::MRFSolver::MRFSolver (void)
Default constructor.
Definition at line 6 of file MRFSolver.cpp.
MRFSolver() [2/2]
sibr::MRFSolver::MRFSolver (std::vector< int > labels, std::vector< std::vector< int > > * neighborMap, int numIterations, UnaryLabelOnlyFuncPtr unaryLabelOnly, UnaryFuncPtr unaryFull, PairwiseLabelOnlyFuncPtr pairwiseLabelsOnly, PairwiseFuncPtr pairwiseFull)
Initialize from a set of labels, connections and node/edge weights.
Parameters
labels list of available labels
neighborMap connectivity map, for each node, list of neighboring nodes linear indices
numIterations number of expansion iterations to perform
unaryLabelOnly optional unary cost that only depends on the label: f(lab0), else provide nullptr
unaryFull unary (per node) cost function evaluator, receiving the node linear index and label: f(ind0, lab0)
pairwiseLabelsOnly optional pairwise cost that only depends on the labels: f(lab0, lab1), else provide nullptr
pairwiseFull pairwise (per pair of nodes) cost function evaluator, receiving the nodes linear indices and their labels: f(ind0, ind1, lab0, lab1)
Note
the "*LabelsOnly" functions are optional and are precomputed and cached for optimized resolution.
Definition at line 10 of file MRFSolver.cpp.
References _labList, _neighborMap, _numIterations, _pairwiseFull, _PairwiseLabelsOnly, _unaryFull, _UnaryLabelOnly, and SIBR_LOG.
~MRFSolver()
sibr::MRFSolver::~MRFSolver (void)
Destructor.
Definition at line 322 of file MRFSolver.cpp.
Member Function Documentation
buildGraphAlphaExp()
void sibr::MRFSolver::buildGraphAlphaExp (int label_iteration_id) private
Build graph for the general case.
Parameters
label_iteration_id
Definition at line 128 of file MRFSolver.cpp.
References _graph, _labels, _neighborMap, pairwiseTotal(), and unaryTotal().
Referenced by solveLabels().
buildGraphBinaryLabels()
void sibr::MRFSolver::buildGraphBinaryLabels (void) private
Build graph for the binary labeling case.
Definition at line 217 of file MRFSolver.cpp.
References _graph, _neighborMap, pairwiseTotal(), unaryTotal(), and weight().
Referenced by solveBinaryLabels().
computeEnergyU()
double sibr::MRFSolver::computeEnergyU (void)
Returns
the unary energy of the current labeling.
Definition at line 295 of file MRFSolver.cpp.
References _labels, and unaryTotal().
Referenced by solveLabels().
computeEnergyW()
double sibr::MRFSolver::computeEnergyW (void)
Returns
the pairwise energy of the current labeling.
Definition at line 304 of file MRFSolver.cpp.
References _labels, _neighborMap, and pairwiseTotal().
Referenced by solveLabels().
getLabels()
std::vector< int > sibr::MRFSolver::getLabels (void)
For each pixel, get the estimated label (call either solveLabels or solveBinaryLabels before).
Returns
a list of labels, one per pixel
Definition at line 272 of file MRFSolver.cpp.
References _labels, and _labList.
getTotalEnergy()
double sibr::MRFSolver::getTotalEnergy (void)
Returns
the total energy of the current labeling.
Definition at line 317 of file MRFSolver.cpp.
References _energy.
getUnariesEnergies()
std::vector< double > sibr::MRFSolver::getUnariesEnergies (void)
Returns
per label unary energy.
Definition at line 283 of file MRFSolver.cpp.
References _labels, and unaryTotal().
pairwiseTotal()
double sibr::MRFSolver::pairwiseTotal (int p, int q, int lp_id, int lq_id) private
Compute the pairwise cost of a pair of nodes.
Parameters
p the first node linear index
q the second node linear index
lp_id the first node label to consider
lq_id the scond node label to consider
Returns
the total pairwise cost
Definition at line 258 of file MRFSolver.cpp.
References _labList, _pairwiseFull, and _PairwiseLabelsOnly.
Referenced by buildGraphAlphaExp(), buildGraphBinaryLabels(), and computeEnergyW().
solveBinaryLabels()
void sibr::MRFSolver::solveBinaryLabels (void)
Solve for binary labels: if you only more than two labels, call solveLabels instead.
Definition at line 185 of file MRFSolver.cpp.
References _graph, _labels, _labList, _neighborMap, buildGraphBinaryLabels(), SIBR_ERR, and SIBR_WRG.
solveLabels()
void sibr::MRFSolver::solveLabels (void)
Solve using alpha expansion. When you have only two labels, use solveBinaryLabels instead.
Definition at line 63 of file MRFSolver.cpp.
References _energy, _graph, _labels, _labList, _neighborMap, _numIterations, buildGraphAlphaExp(), computeEnergyU(), computeEnergyW(), SIBR_LOG, and unaryTotal().
unaryTotal()
double sibr::MRFSolver::unaryTotal (int p, int lp_id) private
Compute the unary cost of a node.
Parameters
p the node linear index
lp_id the node label to consider
Returns
the total unary cost
Definition at line 245 of file MRFSolver.cpp.
References _labList, _unaryFull, and _UnaryLabelOnly.
Referenced by buildGraphAlphaExp(), buildGraphBinaryLabels(), computeEnergyU(), getUnariesEnergies(), and solveLabels().
Member Data Documentation
_energy
double sibr::MRFSolver::_energy private
Total energy.
Definition at line 110 of file MRFSolver.h.
Referenced by getTotalEnergy(), and solveLabels().
_graph
GraphType* sibr::MRFSolver::_graph private
Graph.
Definition at line 111 of file MRFSolver.h.
Referenced by buildGraphAlphaExp(), buildGraphBinaryLabels(), solveBinaryLabels(), and solveLabels().
_labels
std::vector<int> sibr::MRFSolver::_labels private
Assign each node its current best label_id.
Definition at line 100 of file MRFSolver.h.
Referenced by buildGraphAlphaExp(), computeEnergyU(), computeEnergyW(), getLabels(), getUnariesEnergies(), solveBinaryLabels(), and solveLabels().
_labList
std::vector<int> sibr::MRFSolver::_labList private
Map the label_id to the actual labels.
Definition at line 99 of file MRFSolver.h.
Referenced by getLabels(), MRFSolver(), pairwiseTotal(), solveBinaryLabels(), solveLabels(), and unaryTotal().
_neighborMap
std::vector<std::vector<int> >* sibr::MRFSolver::_neighborMap private
For each variable, gives the list of its neighbor variables.
Definition at line 101 of file MRFSolver.h.
Referenced by buildGraphAlphaExp(), buildGraphBinaryLabels(), computeEnergyW(), MRFSolver(), solveBinaryLabels(), and solveLabels().
_numIterations
int sibr::MRFSolver::_numIterations private
Number of iterations in alpha expansion.
Definition at line 102 of file MRFSolver.h.
Referenced by MRFSolver(), and solveLabels().
_pairwiseFull
std::shared_ptr<std::function<double(int, int, int, int)> > sibr::MRFSolver::_pairwiseFull private
Pairwises requiring labels and variables.
Definition at line 107 of file MRFSolver.h.
Referenced by MRFSolver(), and pairwiseTotal().
_PairwiseLabelsOnly
std::vector<std::vector< double > > sibr::MRFSolver::_PairwiseLabelsOnly private
Pairwises only requiring labels.
Definition at line 106 of file MRFSolver.h.
Referenced by MRFSolver(), and pairwiseTotal().
_unaryFull
std::shared_ptr<std::function<double(int, int)> > sibr::MRFSolver::_unaryFull private
Unaries requiring label and variable.
Definition at line 105 of file MRFSolver.h.
Referenced by MRFSolver(), and unaryTotal().
_UnaryLabelOnly
std::vector<double> sibr::MRFSolver::_UnaryLabelOnly private
Unaries only requiring label.
Definition at line 104 of file MRFSolver.h.
Referenced by MRFSolver(), and unaryTotal().
ignoreIsolatedNode
bool sibr::MRFSolver::ignoreIsolatedNode private
Ignore nodes with no connections.
Definition at line 112 of file MRFSolver.h.
The documentation for this class was generated from the following files:
src/core/imgproc/MRFSolver.h
src/core/imgproc/MRFSolver.cpp