SIBR: sibr::MultiMeshManager Class Reference
sibr::MultiMeshManager Class Reference
sibr_view
Provide a view to render and interact with several meshes, useful for debugging purposes for instance.
#include <MultiMeshManager.hpp>
Public Member Functions
MultiMeshManager (const std::string &_name="MultiMeshManager")
Constructor.
MeshData & addMesh (const std::string &name, Mesh::Ptr mesh, bool use_raycaster=true)
Add a mesh to the visualization.
MeshData & addMesh (const std::string &name, Mesh::Ptr mesh, Raycaster::Ptr raycaster, bool create_raycaster=false)
Add a mesh to the visualization.
MeshData & addMeshAsLines (const std::string &name, Mesh::Ptr mesh)
Add lines to the visualization, using the mesh vertices as line endpoints.
MeshData & addLines (const std::string &name, const std::vector< Vector3f > &endPoints, const Vector3f &color={ 0, 1, 0 })
Add lines to the visualization, defined by their endpoints.
MeshData & addPoints (const std::string &name, const std::vector< Vector3f > &points, const Vector3f &color={ 1, 0, 0 })
Add points to the visualization.
MeshData & getMeshData (const std::string &name)
Accessor to the options of a visualized object.
void removeMesh (const std::string &name)
Remove a object from the viewer.
void setIntialView (const std::string &dataset_path)
virtual void onUpdate (Input &input, const Viewport &vp) override
Update state based on user input.
virtual void onRender (const Viewport &viewport) override
Render content in the currently bound RT, using a specific viewport.
virtual void onRender (IRenderTarget &dst)
Render content in a RT, using the RT viewport.
virtual void onGUI () override
Display GUI.
InteractiveCameraHandler & getCameraHandler ()
MeshShadingShader & getMeshShadingShader ()
Public Member Functions inherited from sibr::ViewBase
ViewBase (const unsigned int w=720, const unsigned int h=480)
Constructor.
virtual ~ViewBase ()=default
Destructor.
virtual void onUpdate (Input &input)
virtual void onRender (Window &win)
Render content in a window.
virtual void onRenderIBR (IRenderTarget &dst, const Camera &eye)
Render content in a given rendertarget.
virtual void preRender (RenderTargetRGB &prev)
Legacy: Used to mix with previous pass.
virtual void whichRT (uint i)
Legacy: Set the internal RT to use.
virtual uint whichRT (void)
Legacy:
void setResolution (const Vector2i &size)
Set the view resolution.
const Vector2i & getResolution (void) const
void active (bool act)
Toggle view status.
bool active ()
void setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
bool isFocused (void) const
void setName (const std::string &name)
Define the name of the view (used for disambiguation of GUI, etc.).
const std::string & name () const
Protected Types
using ListMesh = std::list< MeshData >
using Iterator = ListMesh::iterator
Protected Member Functions
MeshData & addMeshData (MeshData &data, bool update_raycaster=false)
Helper to add some geometry to the view.
void initShaders ()
Create the shaders.
void renderMeshes ()
Render all the registered meshes.
void list_mesh_onGUI ()
Generate the list of objects in the GUI panel of the view.
Protected Attributes
std::string name
View name.
ListMesh list_meshes
Meshes to display.
Iterator selected_mesh_it
Currently selected mesh.
bool selected_mesh_it_is_valid = false
Is there a valid currently selected mesh.
InteractiveCameraHandler camera_handler
View camera handler.
PointShader points_shader
Shader for points.
MeshShadingShader colored_mesh_shader
Shader for meshes.
NormalRenderingShader per_vertex_normals_shader
NormalRenderingShader per_triangle_normals_shader
Shaders for visualizing an object normals.
Vector3f backgroundColor = { 0.7f, 0.7f, 0.7f }
Background clear color.
Protected Attributes inherited from sibr::ViewBase
uint _whichRT
Selected RT id.
std::vector< RenderTargetLum::Ptr > _masks
Rendering masks that can beused by some views/renderers.
bool _active = true
Is the view active.
Vector2i _resolution
View resolution.
bool _focus = false
Is the view focused.
std::string _name = ""
View name.
Private Member Functions
SIBR_CLASS_PTR (MultiMeshManager)
Additional Inherited Members
Public Types inherited from sibr::ViewBase
typedef std::shared_ptr< ViewBase > Ptr
Detailed Description
Provide a view to render and interact with several meshes, useful for debugging purposes for instance.
The API supports chaining when setting mesh display options. You can for instance do: manager.addMesh("my mesh", mesh).setDepthtest(true).setAlpha(0.5f);
Definition at line 286 of file MultiMeshManager.hpp.
Member Typedef Documentation
Iterator
using sibr::MultiMeshManager::Iterator = ListMesh::iterator protected
Definition at line 398 of file MultiMeshManager.hpp.
ListMesh
using sibr::MultiMeshManager::ListMesh = std::list<MeshData> protected
Definition at line 397 of file MultiMeshManager.hpp.
Constructor & Destructor Documentation
MultiMeshManager()
sibr::MultiMeshManager::MultiMeshManager (const std::string & _name = "MultiMeshManager")
Constructor.
Parameters
_name Name used for GUI panels as a prefix to avoid collision.
Note
Requires an OpenGL context setup
Definition at line 297 of file MultiMeshManager.cpp.
References camera_handler, sibr::InteractiveCameraHandler::fromCamera(), sibr::TrackBall::fromMesh(), sibr::TrackBall::getCamera(), sibr::Mesh::getTestCube(), initShaders(), and sibr::InteractiveCameraHandler::switchMode().
Member Function Documentation
addLines()
MeshData & sibr::MultiMeshManager::addLines (const std::string & name, const std::vector< Vector3f > & endPoints, const Vector3f & color = { 0,1,0 })
Add lines to the visualization, defined by their endpoints.
Parameters
name name used for the object, if it already exist it will update the geometry and preserve display options
endPoints the line endpoints
color the display color to use
Returns
a reference to the object display options (for chained modifications).
Definition at line 653 of file MultiMeshManager.cpp.
References addMeshData(), sibr::MeshData::depthTest, sibr::Mesh::LineRenderMode, sibr::MeshData::LINES, name, sibr::MeshData::setColorMode(), sibr::MeshData::USER_DEFINED, and sibr::MeshData::userColor.
addMesh() [1/2]
MeshData & sibr::MultiMeshManager::addMesh (const std::string & name, Mesh::Ptr mesh, bool use_raycaster = true)
Add a mesh to the visualization.
Parameters
name name used for the object, if it already exist it will update the geometry and preserve display options
mesh the mesh
use_raycaster should a raycaster be setup, for trackball centering for instance
Returns
a reference to the object display options (for chained modifications).
Definition at line 616 of file MultiMeshManager.cpp.
References sibr::MeshData::dummy, name, and SIBR_WRG.
Referenced by list_mesh_onGUI(), and sibr::SceneDebugView::setupMeshes().
addMesh() [2/2]
MeshData & sibr::MultiMeshManager::addMesh (const std::string & name, Mesh::Ptr mesh, Raycaster::Ptr raycaster, bool create_raycaster = false)
Add a mesh to the visualization.
Parameters
name name used for the object, if it already exist it will update the geometry and preserve display options
mesh the mesh
raycaster existing raycaster, for trackball centering for instance
create_raycaster should a raycaster be setup if the passed raycaster is null
Returns
a reference to the object display options (for chained modifications).
Definition at line 626 of file MultiMeshManager.cpp.
References addMeshData(), sibr::MeshData::colorMode, sibr::MeshData::dummy, sibr::Mesh::FillRenderMode, name, sibr::MeshData::normalMode, sibr::MeshData::PER_TRIANGLE, sibr::MeshData::PER_VERTEX, sibr::MeshData::phongShading, sibr::MeshData::raycaster, sibr::MeshData::setColorRandom(), SIBR_WRG, and sibr::MeshData::TRIANGLES.
addMeshAsLines()
MeshData & sibr::MultiMeshManager::addMeshAsLines (const std::string & name, Mesh::Ptr mesh)
Add lines to the visualization, using the mesh vertices as line endpoints.
Parameters
name name used for the object, if it already exist it will update the geometry and preserve display options
mesh the mesh
Returns
a reference to the object display options (for chained modifications).
Definition at line 642 of file MultiMeshManager.cpp.
References addMeshData(), sibr::MeshData::dummy, sibr::Mesh::LineRenderMode, sibr::MeshData::LINES, name, sibr::MeshData::setColorRandom(), sibr::MeshData::setDepthTest(), and SIBR_WRG.
Referenced by sibr::SceneDebugView::onRender(), and sibr::SceneDebugView::setupMeshes().
addMeshData()
MeshData & sibr::MultiMeshManager::addMeshData (MeshData & data, bool update_raycaster = false) protected
Helper to add some geometry to the view.
Parameters
data the object to add
update_raycaster should the associated raycaster be updated with the new geometry
Returns
the update object options
Definition at line 695 of file MultiMeshManager.cpp.
References camera_handler, sibr::MeshData::dummy, sibr::InteractiveCameraHandler::fromCamera(), sibr::InteractiveCameraHandler::getCamera(), list_meshes, sibr::MeshData::meshPtr, sibr::MeshData::name, sibr::MeshData::raycaster, and sibr::Camera::zfar().
Referenced by addLines(), addMesh(), addMeshAsLines(), and addPoints().
addPoints()
MeshData & sibr::MultiMeshManager::addPoints (const std::string & name, const std::vector< Vector3f > & points, const Vector3f & color = { 1,0,0 })
Add points to the visualization.
Parameters
name name used for the mesh, if it already exist it will update the geometry and preserve display options
points the points
color the display color to use
Returns
a reference to the display options (for chained modifications).
Definition at line 671 of file MultiMeshManager.cpp.
References addMeshData(), sibr::MeshData::depthTest, name, sibr::Mesh::PointRenderMode, sibr::MeshData::POINTS, and sibr::MeshData::userColor.
getCameraHandler()
InteractiveCameraHandler& sibr::MultiMeshManager::getCameraHandler () inline
Returns
the view camera handler
Definition at line 374 of file MultiMeshManager.hpp.
getMeshData()
MeshData & sibr::MultiMeshManager::getMeshData (const std::string & name)
Accessor to the options of a visualized object.
Parameters
name the object name to look for
Returns
a reference to the object options if it exists, or to MeshData::dummy if no match was found.
Definition at line 685 of file MultiMeshManager.cpp.
References sibr::MeshData::dummy, list_meshes, and name.
Referenced by sibr::SceneDebugView::onUpdate().
getMeshShadingShader()
MeshShadingShader& sibr::MultiMeshManager::getMeshShadingShader () inline
Returns
the colored mesh shader
Definition at line 377 of file MultiMeshManager.hpp.
initShaders()
void sibr::MultiMeshManager::initShaders () protected
Create the shaders.
Definition at line 405 of file MultiMeshManager.cpp.
References colored_mesh_shader, sibr::getShadersDirectory(), sibr::PointShader::initShader(), sibr::MeshShadingShader::initShader(), sibr::NormalRenderingShader::initShader(), sibr::loadFile(), per_triangle_normals_shader, per_vertex_normals_shader, and points_shader.
Referenced by MultiMeshManager().
list_mesh_onGUI()
void sibr::MultiMeshManager::list_mesh_onGUI () protected
Generate the list of objects in the GUI panel of the view.
Definition at line 459 of file MultiMeshManager.cpp.
References addMesh(), backgroundColor, camera_handler, sibr::Default, sibr::InteractiveCameraHandler::fromCamera(), sibr::InteractiveCameraHandler::getCamera(), list_meshes, name, removeMesh(), selected_mesh_it, selected_mesh_it_is_valid, sibr::Camera::setLookAt(), and sibr::showFilePicker().
Referenced by sibr::SceneDebugView::onGUI(), and sibr::SceneDebugView::onRender().
onGUI()
void sibr::MultiMeshManager::onGUI () override virtual
Display GUI.
Reimplemented from sibr::ViewBase.
Reimplemented in sibr::SceneDebugView.
Definition at line 367 of file MultiMeshManager.cpp.
onRender() [1/2]
void sibr::MultiMeshManager::onRender (const Viewport & viewport) override virtual
Render content in the currently bound RT, using a specific viewport.
Parameters
viewport destination viewport
Note
Used when the view is in a multi-view system.
Reimplemented from sibr::ViewBase.
Reimplemented in sibr::SceneDebugView.
Definition at line 345 of file MultiMeshManager.cpp.
References backgroundColor, sibr::Viewport::bind(), camera_handler, sibr::Viewport::clear(), sibr::InteractiveCameraHandler::onRender(), and renderMeshes().
Referenced by onRender().
onRender() [2/2]
void sibr::MultiMeshManager::onRender (IRenderTarget & dst) virtual
Render content in a RT, using the RT viewport.
Parameters
dst destination RT
Definition at line 357 of file MultiMeshManager.cpp.
References ibr_preprocess_rc_to_sibr::dst, and onRender().
onUpdate()
void sibr::MultiMeshManager::onUpdate (Input & input, const Viewport & vp) override virtual
Update state based on user input.
Parameters
input user input
vp input viewport
Note
Used when the view is in a multi-view system.
Reimplemented from sibr::ViewBase.
Reimplemented in sibr::SceneDebugView.
Definition at line 309 of file MultiMeshManager.cpp.
References camera_handler, sibr::TrackBall::fromBoundingBox(), sibr::InteractiveCameraHandler::fromCamera(), sibr::TrackBall::getCamera(), sibr::InteractiveCameraHandler::getRaycaster(), sibr::InteractiveCameraHandler::isSetup(), list_meshes, selected_mesh_it, selected_mesh_it_is_valid, and sibr::InteractiveCameraHandler::update().
Referenced by sibr::SceneDebugView::onUpdate().
removeMesh()
void sibr::MultiMeshManager::removeMesh (const std::string & name)
Remove a object from the viewer.
Parameters
name the name of the object to remove
Definition at line 378 of file MultiMeshManager.cpp.
References list_meshes, and name.
Referenced by list_mesh_onGUI().
renderMeshes()
void sibr::MultiMeshManager::renderMeshes () protected
Render all the registered meshes.
Definition at line 429 of file MultiMeshManager.cpp.
References camera_handler, colored_mesh_shader, sibr::InteractiveCameraHandler::getCamera(), list_meshes, per_triangle_normals_shader, sibr::MeshData::PER_VERTEX, per_vertex_normals_shader, sibr::Mesh::PointRenderMode, points_shader, sibr::ShaderAlphaMVP::render(), and sibr::PointShader::render().
Referenced by onRender(), and sibr::SceneDebugView::onRender().
setIntialView()
void sibr::MultiMeshManager::setIntialView (const std::string & dataset_path)
Definition at line 388 of file MultiMeshManager.cpp.
References camera_handler, sibr::InteractiveCameraHandler::fromTransform(), sibr::InteractiveCameraHandler::getCamera(), sibr::InputCamera::readFromFile(), SIBR_LOG, and sibr::Camera::transform().
SIBR_CLASS_PTR()
sibr::MultiMeshManager::SIBR_CLASS_PTR (MultiMeshManager) private
Member Data Documentation
backgroundColor
Vector3f sibr::MultiMeshManager::backgroundColor = { 0.7f, 0.7f, 0.7f } protected
Background clear color.
Definition at line 411 of file MultiMeshManager.hpp.
Referenced by list_mesh_onGUI(), onRender(), and sibr::SceneDebugView::onRender().
camera_handler
InteractiveCameraHandler sibr::MultiMeshManager::camera_handler protected
View camera handler.
Definition at line 405 of file MultiMeshManager.hpp.
Referenced by addMeshData(), sibr::SceneDebugView::gui_cameras(), sibr::SceneDebugView::gui_options(), list_mesh_onGUI(), MultiMeshManager(), onRender(), sibr::SceneDebugView::onRender(), onUpdate(), renderMeshes(), sibr::SceneDebugView::save(), setIntialView(), sibr::SceneDebugView::setScene(), and sibr::SceneDebugView::setup().
colored_mesh_shader
MeshShadingShader sibr::MultiMeshManager::colored_mesh_shader protected
Shader for meshes.
Definition at line 408 of file MultiMeshManager.hpp.
Referenced by initShaders(), and renderMeshes().
list_meshes
ListMesh sibr::MultiMeshManager::list_meshes protected
Meshes to display.
Definition at line 401 of file MultiMeshManager.hpp.
Referenced by addMeshData(), getMeshData(), list_mesh_onGUI(), onUpdate(), removeMesh(), and renderMeshes().
name
std::string sibr::MultiMeshManager::name protected
View name.
Definition at line 400 of file MultiMeshManager.hpp.
Referenced by addLines(), addMesh(), addMeshAsLines(), addPoints(), getMeshData(), sibr::SceneDebugView::gui_cameras(), list_mesh_onGUI(), sibr::SceneDebugView::onRender(), and removeMesh().
per_triangle_normals_shader
NormalRenderingShader sibr::MultiMeshManager::per_triangle_normals_shader protected
Shaders for visualizing an object normals.
Definition at line 409 of file MultiMeshManager.hpp.
Referenced by initShaders(), and renderMeshes().
per_vertex_normals_shader
NormalRenderingShader sibr::MultiMeshManager::per_vertex_normals_shader protected
Definition at line 409 of file MultiMeshManager.hpp.
Referenced by initShaders(), and renderMeshes().
points_shader
PointShader sibr::MultiMeshManager::points_shader protected
Shader for points.
Definition at line 407 of file MultiMeshManager.hpp.
Referenced by initShaders(), and renderMeshes().
selected_mesh_it
Iterator sibr::MultiMeshManager::selected_mesh_it protected
Currently selected mesh.
Definition at line 402 of file MultiMeshManager.hpp.
Referenced by list_mesh_onGUI(), and onUpdate().
selected_mesh_it_is_valid
bool sibr::MultiMeshManager::selected_mesh_it_is_valid = false protected
Is there a valid currently selected mesh.
Definition at line 403 of file MultiMeshManager.hpp.
Referenced by list_mesh_onGUI(), and onUpdate().
The documentation for this class was generated from the following files:
src/core/view/MultiMeshManager.hpp
src/core/view/MultiMeshManager.cpp