SIBR: sibr::FPSCamera Class Reference
sibr::FPSCamera Class Reference
sibr_view
Interactive camera that can be moved using WASD keys.
#include <FPSCamera.hpp>
Public Member Functions
FPSCamera (void)
Default constructor.
void fromCamera (const sibr::InputCamera &cam)
void update (const sibr::Input &input, float deltaTime)
void snap (const std::vector< InputCamera::Ptr > &cams)
Move to a camera position/orientation that is a distance-wieghted combination of the given cameras.
virtual void update (const sibr::Input &input, const float deltaTime, const Viewport &viewport) override
Update the FPS camera based on the user input.
virtual const sibr::InputCamera & getCamera (void) const override
void setSpeed (const float speed, const float angular=0.0)
Set the camera speed.
virtual void onGUI (const std::string &suffix) override
Dispaly GUI.
Public Member Functions inherited from sibr::ICameraHandler
virtual void onRender (const sibr::Viewport &viewport)
Render on top of the associated view(s).
Private Member Functions
void moveUsingWASD (const sibr::Input &input, float deltaTime)
Update camera pose based on keys.
void moveUsingMousePan (const sibr::Input &input, float deltaTime)
Update camera pose based on mouse.
Private Attributes
float _speedFpsCam
float _speedRotFpsCam
Camera speeds.
bool _hasBeenInitialized
Has the camera been initialized.
sibr::InputCamera _currentCamera
Current camera.
bool _useAcceleration
Should the camera accelerate the longer keys are pressed.
Detailed Description
Interactive camera that can be moved using WASD keys.
Definition at line 21 of file FPSCamera.hpp.
Constructor & Destructor Documentation
FPSCamera()
sibr::FPSCamera::FPSCamera (void)
Default constructor.
Definition at line 14 of file FPSCamera.cpp.
References _speedFpsCam, _speedRotFpsCam, _useAcceleration, sibr::UIShortcuts::add(), and sibr::UIShortcuts::global().
Member Function Documentation
fromCamera()
void sibr::FPSCamera::fromCamera (const sibr::InputCamera & cam)
Setup the FPS camera so that it has the same pose as the argument camera.
Parameters
cam the reference camera
Definition at line 37 of file FPSCamera.cpp.
References _currentCamera, and _hasBeenInitialized.
Referenced by sibr::InteractiveCameraHandler::fromCamera().
getCamera()
const sibr::InputCamera & sibr::FPSCamera::getCamera (void) const override virtual
Returns
the current camera
Implements sibr::ICameraHandler.
Definition at line 69 of file FPSCamera.cpp.
References _currentCamera, _hasBeenInitialized, and SIBR_ERR.
Referenced by sibr::InteractiveCameraHandler::update().
moveUsingMousePan()
void sibr::FPSCamera::moveUsingMousePan (const sibr::Input & input, float deltaTime) private
Update camera pose based on mouse.
Parameters
input user input
deltaTime elapsed time
Definition at line 160 of file FPSCamera.cpp.
References _currentCamera, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Mouse::Left, sibr::Mouse::Middle, sibr::Input::mouseButton(), sibr::Input::mouseDeltaPosition(), sibr::Mouse::Right, sibr::Camera::transform(), and sibr::Camera::translate().
Referenced by update().
moveUsingWASD()
void sibr::FPSCamera::moveUsingWASD (const sibr::Input & input, float deltaTime) private
Update camera pose based on keys.
Parameters
input user input
deltaTime elapsed time
Definition at line 101 of file FPSCamera.cpp.
References _currentCamera, _speedFpsCam, _speedRotFpsCam, _useAcceleration, sibr::Key::A, sibr::Key::D, sibr::Key::E, sibr::Key::I, IBRVIEW_CAMSPEED, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Key::J, sibr::Key::K, sibr::Input::key(), sibr::Key::L, sibr::Key::LeftControl, sibr::Key::O, sibr::Camera::ortho(), sibr::Camera::orthoRight(), sibr::Camera::orthoTop(), sibr::Key::Q, sibr::Camera::rotate(), sibr::Key::S, sibr::Camera::transform(), sibr::Camera::translate(), sibr::Key::U, sibr::Key::W, sibr::Key::X, and sibr::Key::Z.
Referenced by update().
onGUI()
void sibr::FPSCamera::onGUI (const std::string & suffix) override virtual
Dispaly GUI.
Parameters
suffix Panel title suffix
Reimplemented from sibr::ICameraHandler.
Definition at line 85 of file FPSCamera.cpp.
References _speedFpsCam, _speedRotFpsCam, _useAcceleration, sibr::Key::End, and ImGui::PushScaledItemWidth().
Referenced by sibr::InteractiveCameraHandler::onGUI().
setSpeed()
void sibr::FPSCamera::setSpeed (const float speed, const float angular = 0.0)
Set the camera speed.
Parameters
speed translation speed
angular rotation speed
Definition at line 78 of file FPSCamera.cpp.
References _speedFpsCam, and _speedRotFpsCam.
Referenced by sibr::InteractiveCameraHandler::setFPSCameraSpeed().
snap()
void sibr::FPSCamera::snap (const std::vector< InputCamera::Ptr > & cams)
Move to a camera position/orientation that is a distance-wieghted combination of the given cameras.
Parameters
cams the cameras list.
Definition at line 51 of file FPSCamera.cpp.
References _currentCamera, sibr::distance(), sibr::lookAt(), sibr::Camera::position(), sibr::quatFromMatrix(), and sibr::Camera::rotation().
Referenced by sibr::InteractiveCameraHandler::update().
update() [1/2]
void sibr::FPSCamera::update (const sibr::Input & input, const float deltaTime, const Viewport & viewport) override virtual
Update the FPS camera based on the user input.
Parameters
input the user input
deltaTime time elapsed since last update
viewport the view viewport
Implements sibr::ICameraHandler.
Definition at line 64 of file FPSCamera.cpp.
References update().
update() [2/2]
void sibr::FPSCamera::update (const sibr::Input & input, float deltaTime)
Update the FPS camera based on the user input (keyboard).
Parameters
input the user input
deltaTime time elapsed since last update
Definition at line 43 of file FPSCamera.cpp.
References _hasBeenInitialized, moveUsingMousePan(), and moveUsingWASD().
Referenced by update(), and sibr::InteractiveCameraHandler::update().
Member Data Documentation
_currentCamera
sibr::InputCamera sibr::FPSCamera::_currentCamera private
Current camera.
Definition at line 76 of file FPSCamera.hpp.
Referenced by fromCamera(), getCamera(), moveUsingMousePan(), moveUsingWASD(), and snap().
_hasBeenInitialized
bool sibr::FPSCamera::_hasBeenInitialized private
Has the camera been initialized.
Definition at line 75 of file FPSCamera.hpp.
Referenced by fromCamera(), getCamera(), and update().
_speedFpsCam
float sibr::FPSCamera::_speedFpsCam private
Definition at line 74 of file FPSCamera.hpp.
Referenced by FPSCamera(), moveUsingWASD(), onGUI(), and setSpeed().
_speedRotFpsCam
float sibr::FPSCamera::_speedRotFpsCam private
Camera speeds.
Definition at line 74 of file FPSCamera.hpp.
Referenced by FPSCamera(), moveUsingWASD(), onGUI(), and setSpeed().
_useAcceleration
bool sibr::FPSCamera::_useAcceleration private
Should the camera accelerate the longer keys are pressed.
Definition at line 77 of file FPSCamera.hpp.
Referenced by FPSCamera(), moveUsingWASD(), and onGUI().
The documentation for this class was generated from the following files:
src/core/view/FPSCamera.hpp
src/core/view/FPSCamera.cpp