SIBR: sibr::MultiViewManager Class Reference
sibr::MultiViewManager Class Reference
sibr_view
A multiview manager is a multi-view system that displays its subviews in an OS window.
#include <MultiViewManager.hpp>
Public Member Functions
MultiViewManager (Window &window, bool resize=true)
void onUpdate (Input &input) override
Update subviews and the MultiViewManager.
void onRender (Window &win) override
Render the content of the MultiViewManager and its interface.
void onGui (Window &win) override
Render menus and additional gui.
Public Member Functions inherited from sibr::MultiViewBase
MultiViewBase (const Vector2i &defaultViewRes={ 800, 600 })
void addSubView (const std::string &title, ViewBase::Ptr view, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register a standard subview (for instance a SceneDebugView).
void addSubView (const std::string &title, ViewBase::Ptr view, const ViewUpdateFunc updateFunc, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register a standard subview (for instance a SceneDebugView).
void addIBRSubView (const std::string &title, ViewBase::Ptr view, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register an IBR subview (for instance an ULRView).
void addIBRSubView (const std::string &title, ViewBase::Ptr view, const IBRViewUpdateFunc updateFunc, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register an IBR subview (for instance an ULRView).
void addSubMultiView (const std::string &title, MultiViewBase::Ptr multiview)
Add another multi-view system as a subsystem of this one.
ViewBase::Ptr & getIBRSubView (const std::string &title)
Viewport & getIBRSubViewport (const std::string &title)
ViewBase::Ptr removeSubView (const std::string &title)
Unregister a subview.
void renderingMode (const IRenderingMode::Ptr &mode)
Change the rendering mode.
void setDefaultViewResolution (const Vector2i &size)
Define the default rendering and display size for new subviews.
const Viewport getViewport (void) const
Returns the default viewport used for subviews rendering.
const float & deltaTime () const
Returns the last frame time.
void addCameraForView (const std::string &name, ICameraHandler::Ptr cameraHandler)
Add a camera handler that will automatically be updated and used by the MultiViewManager for the given subview.
void addAdditionalRenderingForView (const std::string &name, const AdditionalRenderFunc renderFunc)
Register a function performing additional rendering for a given subview, called by the MultiViewManager after calling onRender() on the subview.
int numSubViews () const
Count NOT recursively the number of subviews.
void mosaicLayout (const Viewport &vp)
Place all subviews on a regular grid in the given viewport.
void toggleSubViewsGUI ()
Toggle the display of sub-managers GUIs.
void setExportPath (const std::string &path)
Set the export path.
void captureView (const std::string &subviewName, const std::string &path="./screenshots", const std::string &filename="")
captures a View content into an image file.
Private Member Functions
void toggleGUI ()
Show/hide the GUI.
Private Attributes
Window & _window
The OS window.
FPSCounter _fpsCounter
A FPS counter.
bool _showGUI = true
Should the GUI be displayed.
Additional Inherited Members
Public Types inherited from sibr::MultiViewBase
typedef std::function< void(sibr::ViewBase::Ptr &, sibr::Input &, const sibr::Viewport &, const float)> ViewUpdateFunc
Update callback for a standard view. Passes the view pointer, the correct input state, and the correct viewport.
typedef std::function< sibr::InputCamera(sibr::ViewBase::Ptr &, sibr::Input &, const sibr::Viewport &, const float)> IBRViewUpdateFunc
Update callback for an IBR view, see main description for the return value.
typedef std::function< void(sibr::ViewBase::Ptr &, const sibr::Viewport &, const IRenderTarget::Ptr &)> AdditionalRenderFunc
Additional render callback for a subview.
Protected Member Functions inherited from sibr::MultiViewBase
void addIBRSubView (const std::string &title, ViewBase::Ptr view, const IBRViewUpdateFunc updateFunc, const Vector2u &res, const ImGuiWindowFlags flags, const bool defaultFuncUsed)
Helper to add an IBR subview.
void renderSubView (SubView &subview)
Perform rendering for a given subview.
Static Protected Member Functions inherited from sibr::MultiViewBase
static void captureView (const SubView &view, const std::string &path="./screenshots/", const std::string &filename="")
Capture a view as an image on disk.
Protected Attributes inherited from sibr::MultiViewBase
IRenderingMode::Ptr _renderingMode = nullptr
Rendering mode.
std::map< std::string, BasicSubView > _subViews
Regular subviews.
std::map< std::string, IBRSubView > _ibrSubViews
IBR subviews.
std::map< std::string, std::shared_ptr< MultiViewBase > > _subMultiViews
Nested multi-views.
Vector2i _defaultViewResolution
Default view resolution.
std::string _exportPath
Capture output path.
std::vector< cv::Mat > _videoFrames
Video frames.
std::chrono::time_point< std::chrono::steady_clock > _timeLastFrame
Last frame time point.
float _deltaTime
Elapsed time.
bool _showSubViewsGui = true
Show the GUI of the subviews.
bool _onPause = false
Paused interaction and update.
Detailed Description
A multiview manager is a multi-view system that displays its subviews in an OS window.
use it as a based for applications with multiple subviews.
Definition at line 379 of file MultiViewManager.hpp.
Constructor & Destructor Documentation
MultiViewManager()
sibr::MultiViewManager::MultiViewManager (Window & window, bool resize = true)
Definition at line 416 of file MultiViewManager.cpp.
References sibr::Window::desktopSize(), sibr::Window::position(), sibr::MultiViewBase::renderingMode(), sibr::MultiViewBase::setDefaultViewResolution(), and sibr::Window::size().
Member Function Documentation
onGui()
void sibr::MultiViewManager::onGui (Window & win) override virtual
Render menus and additional gui.
Parameters
win The OS window into which the rendering should be performed.
Reimplemented from sibr::MultiViewBase.
Definition at line 460 of file MultiViewManager.cpp.
References sibr::MultiViewBase::_exportPath, _fpsCounter, sibr::MultiViewBase::_ibrSubViews, sibr::MultiViewBase::_onPause, _showGUI, sibr::MultiViewBase::_subViews, sibr::MultiViewBase::_videoFrames, sibr::FPSCounter::active(), sibr::MultiViewBase::captureView(), sibr::Window::close(), sibr::Directory, ImGui::GetTitleBarHeight(), sibr::Window::isFullscreen(), sibr::Window::isVsynced(), sibr::MultiViewBase::mosaicLayout(), sibr::MultiViewBase::onGui(), sibr::round(), sibr::Save, sibr::Window::scaling(), sibr::Window::setFullscreen(), sibr::Window::setVsynced(), sibr::showFilePicker(), SIBR_LOG, SIBR_WRG, sibr::Window::size(), toggleGUI(), sibr::FPSCounter::toggleVisibility(), and sibr::Window::viewport().
Referenced by onRender().
onRender()
void sibr::MultiViewManager::onRender (Window & win) override virtual
Render the content of the MultiViewManager and its interface.
Parameters
win The OS window into which the rendering should be performed.
Reimplemented from sibr::MultiViewBase.
Definition at line 446 of file MultiViewManager.cpp.
References _fpsCounter, _showGUI, sibr::Viewport::bind(), onGui(), sibr::MultiViewBase::onRender(), sibr::FPSCounter::update(), and sibr::Window::viewport().
Referenced by legacyV1main(), legacyV2main(), and main().
onUpdate()
void sibr::MultiViewManager::onUpdate (Input & input) override virtual
Update subviews and the MultiViewManager.
Parameters
input The Input state to use.
Reimplemented from sibr::MultiViewBase.
Definition at line 437 of file MultiViewManager.cpp.
References sibr::Key::G, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Input::key(), sibr::Key::LeftAlt, sibr::Key::LeftControl, sibr::MultiViewBase::onUpdate(), and toggleGUI().
Referenced by legacyV1main(), legacyV2main(), and main().
toggleGUI()
void sibr::MultiViewManager::toggleGUI () private
Show/hide the GUI.
Definition at line 618 of file MultiViewManager.cpp.
References _showGUI, SIBR_LOG, and sibr::MultiViewBase::toggleSubViewsGUI().
Referenced by onGui(), and onUpdate().
Member Data Documentation
_fpsCounter
FPSCounter sibr::MultiViewManager::_fpsCounter private
A FPS counter.
Definition at line 413 of file MultiViewManager.hpp.
Referenced by onGui(), and onRender().
_showGUI
bool sibr::MultiViewManager::_showGUI = true private
Should the GUI be displayed.
Definition at line 414 of file MultiViewManager.hpp.
Referenced by onGui(), onRender(), and toggleGUI().
_window
Window& sibr::MultiViewManager::_window private
The OS window.
Definition at line 412 of file MultiViewManager.hpp.
The documentation for this class was generated from the following files:
src/core/view/MultiViewManager.hpp
src/core/view/MultiViewManager.cpp