SIBR: sibr::RenderUtility Class Reference
sibr::RenderUtility Class Reference
sibr_graphics
Helpers for rendering basic debug objects (cameras, simple meshes,...)
#include <RenderUtility.hpp>
Static Public Member Functions
static Mesh createCameraStub (float camStubSize=0.1f)
Create a basic cmaera stub.
static Mesh createScreenQuad ()
Create a screenquad.
static Mesh::Ptr createAxisGizmo ()
Create a gizmo with X,Y,Z axis and labels (using R,G,B respectively).
static void useDefaultVAO (void)
Bind a static VAO for which you can redefine vertices or do vertex pulling.
static void renderScreenQuad ()
Draw a screenquad.
static void renderScreenQuad (bool reverse, GLfloat texCoor[]=NULL)
Draw a screenquad.
Static Private Member Functions
static void sendVertsTexToGPU (GLuint vertTexVBO, GLfloat vert[], GLfloat tcoord[], int svert, int stcoord)
Send vertices to the GPU.
Detailed Description
Helpers for rendering basic debug objects (cameras, simple meshes,...)
Todo:
Clarify duplication with functionality in SceneDebugView.
Definition at line 16 of file RenderUtility.hpp.
Member Function Documentation
createAxisGizmo()
Mesh::Ptr sibr::RenderUtility::createAxisGizmo () static
Create a gizmo with X,Y,Z axis and labels (using R,G,B respectively).
Returns
the gizmo mesh
Definition at line 204 of file RenderUtility.cpp.
Referenced by sibr::SceneDebugView::setupMeshes().
createCameraStub()
Mesh sibr::RenderUtility::createCameraStub (float camStubSize = 0.1f) static
Create a basic cmaera stub.
Parameters
camStubSize the stub scale
Returns
the mesh
Definition at line 167 of file RenderUtility.cpp.
References sibr::getCameraStubIndices(), sibr::getCameraStubVertices(), sibr::Mesh::triangles(), and sibr::Mesh::vertices().
createScreenQuad()
Mesh sibr::RenderUtility::createScreenQuad (void) static
Create a screenquad.
Returns
the mesh
Definition at line 176 of file RenderUtility.cpp.
References sibr::Mesh::texCoords(), sibr::Mesh::triangles(), and sibr::Mesh::vertices().
renderScreenQuad() [1/2]
void sibr::RenderUtility::renderScreenQuad () static
Draw a screenquad.
Definition at line 116 of file RenderUtility.cpp.
References sibr::Window::contextId, and sendVertsTexToGPU().
Referenced by sibr::CopyRenderer::copyToWindow(), sibr::MultiViewInterface::displayImages(), sibr::DrawUtilities::image_grid(), sibr::RGBDInputTextures::initializeImageRenderTargets(), sibr::ImageView::onRender(), sibr::ULRV2Renderer::process(), sibr::ULRRenderer::process(), sibr::AddShadowRenderer::process(), sibr::BlurRenderer::process(), sibr::CopyRenderer::process(), sibr::PoissonRenderer::render(), sibr::MonoRdrMode::render(), sibr::StereoAnaglyphRdrMode::render(), sibr::ULRV3Renderer::renderBlending(), sibr::show(), and sibr::RenderMaskHolder::uploadMaskGPU().
renderScreenQuad() [2/2]
void sibr::RenderUtility::renderScreenQuad (bool reverse, GLfloat texCoor[] = NULL) static
Draw a screenquad.
Parameters
reverse should the triangles be flipped
texCoor custom texture coordinates to use.
Definition at line 55 of file RenderUtility.cpp.
References sendVertsTexToGPU().
sendVertsTexToGPU()
void sibr::RenderUtility::sendVertsTexToGPU (GLuint vertTexVBO, GLfloat vert[], GLfloat tcoord[], int svert, int stcoord) static private
Send vertices to the GPU.
Parameters
vertTexVBO the VBO id
vert the vertices data
tcoord the UV data
svert the vert size
stcoord the tcoord size
Definition at line 47 of file RenderUtility.cpp.
Referenced by renderScreenQuad().
useDefaultVAO()
void sibr::RenderUtility::useDefaultVAO (void) static
Bind a static VAO for which you can redefine vertices or do vertex pulling.
Definition at line 306 of file RenderUtility.cpp.
Referenced by sibr::Skybox::render(), and sibr::RenderTarget< T_Type, T_NumComp >::RenderTarget().
The documentation for this class was generated from the following files:
src/core/graphics/RenderUtility.hpp
src/core/graphics/RenderUtility.cpp