SIBR: sibr::Skybox Class Reference
sibr::Skybox Class Reference
sibr_view
A skybox object for rendering a cubemap texture.
#include <Skybox.hpp>
Public Member Functions
bool load (const std::string &skyFolder)
Load skybox faces from a directory.
void render (const Camera &eye, const sibr::Vector2u &imgSize)
Render in the current RT.
Private Member Functions
SIBR_CLASS_PTR (Skybox)
Private Attributes
GLShader _shader
Skybox shader.
GLParameter _paramView
VP parameter.
GLParameter _paramAspect
Aspect ratio parameter.
TextureCubeMapRGB::Ptr _cubemap = nullptr
Cubemap texture.
Detailed Description
A skybox object for rendering a cubemap texture.
Definition at line 13 of file Skybox.hpp.
Member Function Documentation
load()
bool sibr::Skybox::load (const std::string & skyFolder)
Load skybox faces from a directory.
The files should be named: {right, left, top, bottom, forward, back}.jpg
Parameters
skyFolder directory path
Returns
a success boolean
Definition at line 7 of file Skybox.cpp.
References _cubemap, _paramAspect, _paramView, _shader, sibr::directoryExists(), sibr::GLParameter::init(), sibr::GLShader::init(), sibr::Resources::Instance(), sibr::loadFile(), and SIBR_ERR.
render()
void sibr::Skybox::render (const Camera & eye, const sibr::Vector2u & imgSize)
Render in the current RT.
Parameters
eye current viewpoint
imgSize the destination RT size
Definition at line 43 of file Skybox.cpp.
References _cubemap, _paramAspect, _paramView, _shader, sibr::GLShader::begin(), CHECK_GL_ERROR, sibr::GLShader::end(), sibr::GLParameter::set(), sibr::RenderUtility::useDefaultVAO(), and sibr::Camera::view().
SIBR_CLASS_PTR()
sibr::Skybox::SIBR_CLASS_PTR (Skybox) private
Member Data Documentation
_cubemap
TextureCubeMapRGB::Ptr sibr::Skybox::_cubemap = nullptr private
Cubemap texture.
Definition at line 37 of file Skybox.hpp.
Referenced by load(), and render().
_paramAspect
GLParameter sibr::Skybox::_paramAspect private
Aspect ratio parameter.
Definition at line 35 of file Skybox.hpp.
Referenced by load(), and render().
_paramView
GLParameter sibr::Skybox::_paramView private
VP parameter.
Definition at line 34 of file Skybox.hpp.
Referenced by load(), and render().
_shader
GLShader sibr::Skybox::_shader private
Skybox shader.
Definition at line 33 of file Skybox.hpp.
Referenced by load(), and render().
The documentation for this class was generated from the following files:
src/core/view/Skybox.hpp
src/core/view/Skybox.cpp