SIBR: sibr::NormalRenderingShader Class Reference
sibr::NormalRenderingShader Class Reference
sibr_view
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
#include <MultiMeshManager.hpp>
Public Member Functions
void initShader (const std::string &name, const std::string &vert, const std::string &frag, const std::string &geom="") override
Initialize the shader.
virtual void setUniforms (const Camera &eye, const MeshData &data) override
Public Member Functions inherited from sibr::ShaderAlphaMVP
virtual void render (const Camera &eye, const MeshData &data)
Render using the passed information.
Protected Attributes
GLuniform< float > normals_size
Normal line length.
Protected Attributes inherited from sibr::ColorMeshShader
GLuniform< Vector3f > user_color
user-defined constant color.
Protected Attributes inherited from sibr::ShaderAlphaMVP
GLShader shader
Base shader object.
GLuniform< Matrix4f > mvp
MVP matrix.
GLuniform< float > alpha = 1.0
Opacity.
Detailed Description
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
Adds line length option.
See also
ShaderAlphaMVP
Definition at line 134 of file MultiMeshManager.hpp.
Member Function Documentation
initShader()
void sibr::NormalRenderingShader::initShader (const std::string & name, const std::string & vert, const std::string & frag, const std::string & geom = "") override virtual
Initialize the shader.
Parameters
name the shader name
vert the vertex shader content
frag the fragment shader ocntent
geom the geometry shader content
Reimplemented from sibr::ColorMeshShader.
Definition at line 269 of file MultiMeshManager.cpp.
References sibr::GLuniform< T >::init(), sibr::ColorMeshShader::initShader(), normals_size, and sibr::ShaderAlphaMVP::shader.
Referenced by sibr::MultiMeshManager::initShaders().
setUniforms()
void sibr::NormalRenderingShader::setUniforms (const Camera & eye, const MeshData & data) override virtual
Reimplemented from sibr::ColorMeshShader.
Definition at line 275 of file MultiMeshManager.cpp.
References normals_size, sibr::MeshData::normalsLength, sibr::GLuniform< T >::set(), and sibr::ColorMeshShader::setUniforms().
Member Data Documentation
normals_size
GLuniform<float> sibr::NormalRenderingShader::normals_size protected
Normal line length.
Definition at line 151 of file MultiMeshManager.hpp.
Referenced by initShader(), and setUniforms().
The documentation for this class was generated from the following files:
src/core/view/MultiMeshManager.hpp
src/core/view/MultiMeshManager.cpp