SIBR: sibr::InterfaceUtilities Class Reference
sibr::InterfaceUtilities Class Reference
sibr_view
#include <InterfaceUtils.h>
Classes
struct GLinitializer
Public Member Functions
InterfaceUtilities ()
void rectangle (const sibr::Vector3f &color, const UV11 &tl, const UV11 &br, bool fill, float alpha)
void rectanglePixels (const sibr::Vector3f &color, const sibr::Vector2f &center, const sibr::Vector2f &diagonal, bool fill, float alpha, const sibr::Vector2f &winSize)
void circle (const sibr::Vector3f &color, const UV11 &center, float radius, bool fill, float alpha, const sibr::Vector2f &scaling=sibr::Vector3f(1, 1), int precision=50)
void circlePixels (const sibr::Vector3f &color, const sibr::Vector2f &center, float radius, bool fill, float alpha, const sibr::Vector2f &winSize, int precision=50)
void linePixels (const sibr::Vector3f &color, const sibr::Vector2f &ptA, const sibr::Vector2f &ptB, const sibr::Vector2f &winSize)
void initAllShaders ()
void freeAllShaders ()
Public Attributes
sibr::GLShader baseShader
sibr::GLParameter colorGL
sibr::GLParameter alphaGL
sibr::GLParameter scalingGL
sibr::GLParameter translationGL
sibr::GLShader meshViewShader
sibr::GLParameter mvp
sibr::GLParameter colorMeshGL
sibr::GLParameter alphaMeshGL
sibr::GLShader multiViewShader
sibr::GLParameter numImgsGL
sibr::GLParameter gridGL
sibr::GLParameter multiViewTopLeftGL
sibr::GLParameter multiViewBottomRightGL
Static Public Attributes
static const std::string translationScalingVertexShader
static const std::string colorAlphaFragmentShader
static const std::string multiViewVertexShader
static const std::string multiViewFragmentShader
static const std::string meshVertexShader
static const std::string meshAlphaViewFragmentShader
Private Member Functions
void initBaseShader ()
void initMultiViewShader ()
void initMeshViewShader ()
Detailed Description
Definition at line 69 of file InterfaceUtils.h.
Constructor & Destructor Documentation
InterfaceUtilities()
sibr::InterfaceUtilities::InterfaceUtilities ()
Definition at line 84 of file InterfaceUtils.cpp.
Member Function Documentation
circle()
void sibr::InterfaceUtilities::circle (const sibr::Vector3f & color, const UV11 & center, float radius, bool fill, float alpha, const sibr::Vector2f & scaling = sibr::Vector3f(1,1), int precision = 50)
Definition at line 189 of file InterfaceUtils.cpp.
References alphaGL, baseShader, sibr::GLShader::begin(), colorGL, sibr::Window::contextId, sibr::GLShader::end(), sibr::Mesh::LineRenderMode, scalingGL, sibr::GLParameter::set(), and translationGL.
Referenced by circlePixels().
circlePixels()
void sibr::InterfaceUtilities::circlePixels (const sibr::Vector3f & color, const sibr::Vector2f & center, float radius, bool fill, float alpha, const sibr::Vector2f & winSize, int precision = 50)
Definition at line 251 of file InterfaceUtils.cpp.
References circle(), and sibr::UV< space >::from().
freeAllShaders()
void sibr::InterfaceUtilities::freeAllShaders ()
Definition at line 99 of file InterfaceUtils.cpp.
References baseShader, CHECK_GL_ERROR, multiViewShader, and sibr::GLShader::terminate().
initAllShaders()
void sibr::InterfaceUtilities::initAllShaders ()
Definition at line 89 of file InterfaceUtils.cpp.
References CHECK_GL_ERROR, initBaseShader(), initMeshViewShader(), and initMultiViewShader().
Referenced by sibr::MultiViewInterface::displayLoop(), and sibr::show().
initBaseShader()
void sibr::InterfaceUtilities::initBaseShader () private
Definition at line 108 of file InterfaceUtils.cpp.
References alphaGL, baseShader, colorAlphaFragmentShader, colorGL, sibr::GLParameter::init(), sibr::GLShader::init(), scalingGL, translationGL, and translationScalingVertexShader.
Referenced by initAllShaders().
initMeshViewShader()
void sibr::InterfaceUtilities::initMeshViewShader () private
Definition at line 126 of file InterfaceUtils.cpp.
References alphaMeshGL, colorAlphaFragmentShader, colorMeshGL, sibr::GLParameter::init(), sibr::GLShader::init(), meshVertexShader, meshViewShader, and mvp.
Referenced by initAllShaders().
initMultiViewShader()
void sibr::InterfaceUtilities::initMultiViewShader () private
Definition at line 117 of file InterfaceUtils.cpp.
References gridGL, sibr::GLParameter::init(), sibr::GLShader::init(), multiViewBottomRightGL, multiViewFragmentShader, multiViewShader, multiViewTopLeftGL, multiViewVertexShader, and numImgsGL.
Referenced by initAllShaders().
linePixels()
void sibr::InterfaceUtilities::linePixels (const sibr::Vector3f & color, const sibr::Vector2f & ptA, const sibr::Vector2f & ptB, const sibr::Vector2f & winSize)
Definition at line 259 of file InterfaceUtils.cpp.
References alphaGL, baseShader, sibr::GLShader::begin(), colorGL, sibr::GLShader::end(), sibr::UV< space >::from(), ibr_convert_old_to_new::line, sibr::Mesh::LineRenderMode, scalingGL, sibr::GLParameter::set(), and translationGL.
rectangle()
void sibr::InterfaceUtilities::rectangle (const sibr::Vector3f & color, const UV11 & tl, const UV11 & br, bool fill, float alpha)
Definition at line 134 of file InterfaceUtils.cpp.
References alphaGL, baseShader, sibr::GLShader::begin(), colorGL, sibr::Window::contextId, sibr::GLShader::end(), sibr::Mesh::LineRenderMode, scalingGL, sibr::GLParameter::set(), and translationGL.
Referenced by sibr::MultiViewInterface::displayImages(), sibr::MultiViewInterface::displayZoom(), sibr::MultiViewInterface::highlightPixel(), and rectanglePixels().
rectanglePixels()
void sibr::InterfaceUtilities::rectanglePixels (const sibr::Vector3f & color, const sibr::Vector2f & center, const sibr::Vector2f & diagonal, bool fill, float alpha, const sibr::Vector2f & winSize)
Definition at line 181 of file InterfaceUtils.cpp.
References sibr::UV< space >::from(), and rectangle().
Referenced by sibr::MultiViewInterface::highlightPixel().
Member Data Documentation
alphaGL
sibr::GLParameter sibr::InterfaceUtilities::alphaGL
Definition at line 80 of file InterfaceUtils.h.
Referenced by circle(), sibr::MultiViewInterface::displayHighlightedPixels(), initBaseShader(), linePixels(), and rectangle().
alphaMeshGL
sibr::GLParameter sibr::InterfaceUtilities::alphaMeshGL
Definition at line 92 of file InterfaceUtils.h.
Referenced by sibr::MultiViewInterface::displayImages(), and initMeshViewShader().
baseShader
sibr::GLShader sibr::InterfaceUtilities::baseShader
Definition at line 77 of file InterfaceUtils.h.
Referenced by circle(), sibr::MultiViewInterface::displayHighlightedPixels(), freeAllShaders(), initBaseShader(), linePixels(), and rectangle().
colorAlphaFragmentShader
const std::string sibr::InterfaceUtilities::colorAlphaFragmentShader static
Initial value:
=
        "#version 420                                                       \n"
        "uniform vec3 color;                                                \n"
        "uniform float alpha;                                               \n"
        "out vec4 out_color;                                                \n"
        "void main(void) {                                                  \n"
        "       out_color = vec4(color,alpha);                              \n"
        "}                                                                  \n"
Definition at line 75 of file InterfaceUtils.h.
Referenced by initBaseShader(), and initMeshViewShader().
colorGL
sibr::GLParameter sibr::InterfaceUtilities::colorGL
Definition at line 79 of file InterfaceUtils.h.
Referenced by circle(), sibr::MultiViewInterface::displayHighlightedPixels(), initBaseShader(), linePixels(), and rectangle().
colorMeshGL
sibr::GLParameter sibr::InterfaceUtilities::colorMeshGL
Definition at line 91 of file InterfaceUtils.h.
Referenced by sibr::MultiViewInterface::displayImages(), and initMeshViewShader().
gridGL
sibr::GLParameter sibr::InterfaceUtilities::gridGL
Definition at line 97 of file InterfaceUtils.h.
Referenced by sibr::MultiViewInterface::displayImages(), initMultiViewShader(), and sibr::show().
meshAlphaViewFragmentShader
const std::string sibr::InterfaceUtilities::meshAlphaViewFragmentShader static
Definition at line 88 of file InterfaceUtils.h.
meshVertexShader
const std::string sibr::InterfaceUtilities::meshVertexShader static
Initial value:
=
        "#version 420                                                           \n"
        "layout(location = 0) in vec3 in_vertex;                                \n"
        "uniform mat4 mvp;                                              \n"
        "void main(void) {                                                      \n"
        "   gl_Position = mvp*vec4(in_vertex, 1.0);                     \n"
        "}                                                                      \n"
Definition at line 87 of file InterfaceUtils.h.
Referenced by initMeshViewShader().
meshViewShader
sibr::GLShader sibr::InterfaceUtilities::meshViewShader
Definition at line 89 of file InterfaceUtils.h.
Referenced by sibr::MultiViewInterface::displayImages(), and initMeshViewShader().
multiViewBottomRightGL
sibr::GLParameter sibr::InterfaceUtilities::multiViewBottomRightGL
Definition at line 99 of file InterfaceUtils.h.
Referenced by sibr::MultiViewInterface::displayImages(), initMultiViewShader(), and sibr::show().
multiViewFragmentShader
const std::string sibr::InterfaceUtilities::multiViewFragmentShader static
Initial value:
=
        "#version 420                                                       \n"
        "layout(binding = 0) uniform sampler2DArray texArray;               \n"
        "uniform int numImgs;                                               \n"
        "uniform vec2 grid;                                                 \n"
        "in vec2 uv_coord;                                                  \n"
        "out vec4 out_color;                                                \n"
        "void main(void) {                                                  \n"
        "   vec2 uvs = uv_coord;                                            \n"
        "   uvs =  grid*uvs;                                                \n"
        "  if( uvs.x < 0 || uvs.y < 0 ) { discard; }                        \n"
        "   vec2 fracs = fract(uvs);                                        \n"
        "   vec2 mods = uvs - fracs;                                        \n"
        "   int n = int(mods.x + grid.x*mods.y);                            \n"
        " if ( n< 0 || n > numImgs || mods.x >= grid.x || mods.y >= (float(numImgs)/grid.x) + 1) { discard; } else { \n"
        "   out_color = texture(texArray,vec3(fracs.x,fracs.y,n));  }       \n"
        "   //out_color = vec4(n/64.0,0.0,0.0,1.0); }                       \n"
        "   //out_color = vec4(uv_coord.x,uv_coord.y,0.0,1.0);  }           \n"
        "}                                                                  \n"
Definition at line 85 of file InterfaceUtils.h.
Referenced by initMultiViewShader().
multiViewShader
sibr::GLShader sibr::InterfaceUtilities::multiViewShader
Definition at line 94 of file InterfaceUtils.h.
Referenced by sibr::MultiViewInterface::displayImages(), freeAllShaders(), initMultiViewShader(), and sibr::show().
multiViewTopLeftGL
sibr::GLParameter sibr::InterfaceUtilities::multiViewTopLeftGL
Definition at line 98 of file InterfaceUtils.h.
Referenced by sibr::MultiViewInterface::displayImages(), initMultiViewShader(), and sibr::show().
multiViewVertexShader
const std::string sibr::InterfaceUtilities::multiViewVertexShader static
Initial value:
=
        "#version 420                                       \n"
        "layout(location = 0) in vec3 in_vertex;            \n"
        "out vec2 uv_coord;                                 \n"
        "uniform vec2 zoomTL;                               \n"
        "uniform vec2 zoomBR;                               \n"
        "void main(void) {                                  \n"
        "   uv_coord = 0.5*in_vertex.xy + vec2(0.5);        \n"
        "   uv_coord = zoomTL + (zoomBR-zoomTL)*uv_coord;   \n"
        "   uv_coord.y = 1.0 - uv_coord.y;                  \n"
        "   gl_Position = vec4(in_vertex.xy,0.0, 1.0);      \n"
        "}                                                  \n"
Definition at line 84 of file InterfaceUtils.h.
Referenced by initMultiViewShader().
mvp
sibr::GLParameter sibr::InterfaceUtilities::mvp
Definition at line 90 of file InterfaceUtils.h.
Referenced by sibr::MultiViewInterface::displayImages(), and initMeshViewShader().
numImgsGL
sibr::GLParameter sibr::InterfaceUtilities::numImgsGL
Definition at line 96 of file InterfaceUtils.h.
Referenced by sibr::MultiViewInterface::displayImages(), initMultiViewShader(), and sibr::show().
scalingGL
sibr::GLParameter sibr::InterfaceUtilities::scalingGL
Definition at line 81 of file InterfaceUtils.h.
Referenced by circle(), sibr::MultiViewInterface::displayHighlightedPixels(), initBaseShader(), linePixels(), and rectangle().
translationGL
sibr::GLParameter sibr::InterfaceUtilities::translationGL
Definition at line 82 of file InterfaceUtils.h.
Referenced by circle(), sibr::MultiViewInterface::displayHighlightedPixels(), initBaseShader(), linePixels(), and rectangle().
translationScalingVertexShader
const std::string sibr::InterfaceUtilities::translationScalingVertexShader static
Initial value:
=
        "#version 420                                                           \n"
        "layout(location = 0) in vec3 in_vertex;                                \n"
        "uniform vec2 translation;                                              \n"
        "uniform vec2 scaling;                                                  \n"
        "void main(void) {                                                      \n"
        "   gl_Position = vec4(scaling*in_vertex.xy+translation,0.0, 1.0);      \n"
        "}                                                                      \n"
Definition at line 74 of file InterfaceUtils.h.
Referenced by initBaseShader().
The documentation for this class was generated from the following files:
src/core/view/interface/InterfaceUtils.h
src/core/view/interface/InterfaceUtils.cpp