SIBR: sibr::InteractiveCameraHandler Class Reference
sibr::InteractiveCameraHandler Class Reference
sibr_view
The InteractiveCameraHandler gathers various types of camera interactions and allows the user to switch between them, keeping them in sync.
#include <InteractiveCameraHandler.hpp>
Public Types
enum InteractionMode {
FPS = 0, ORBIT = 1, INTERPOLATION = 2, TRACKBALL = 3,
NONE =4
}
Current handler interaction mode.
Public Member Functions
SIBR_CLASS_PTR (InteractiveCameraHandler)
InteractiveCameraHandler (const bool supportRecording=true)
Constructor.
void setup (const std::vector< InputCamera::Ptr > &cams, const sibr::Vector2u &resolution, const sibr::Viewport &viewport, const std::shared_ptr< sibr::Raycaster > raycaster)
void setup (const sibr::InputCamera &cam, const sibr::Viewport &viewport, const std::shared_ptr< sibr::Raycaster > raycaster)
Setup an interactive camera handler from an existing camera.
void setup (const Eigen::AlignedBox< float, 3 > &areaOfInterest, const sibr::Viewport &viewport, const std::shared_ptr< sibr::Raycaster > raycaster)
Setup an interactive camera handler from an area of interest.
void setup (const std::vector< InputCamera::Ptr > &cams, const sibr::Viewport &viewport, std::shared_ptr< sibr::Raycaster > raycaster, const sibr::Vector2f &clippingPlanes={-1.0f,-1.0f})
Setup an interactive camera handler from a series of existing cameras and mesh.
void setup (std::shared_ptr< sibr::Mesh > mesh, const sibr::Viewport &viewport)
Setup an interactive camera handler from a mesh.
void setupInterpolationPath (const std::vector< InputCamera::Ptr > &cameras)
Setup a camera path for the interpolation mode.
void fromCamera (const sibr::InputCamera &cam, bool interpolate=true, bool updateResolution=true)
Move the interactive camera to a new position and change its internal parameters.
void fromTransform (const Transform3f &transform, bool interpolate=true, bool updateResolution=true)
Move the interactive camera to a new position.
void setClippingPlanes (float znear, float zfar)
Set the clipping planes.
int findNearestCamera (const std::vector< InputCamera::Ptr > &inputCameras) const
Find the camera in a list closest to the current interactive camera position.
void switchSmoothing ()
Toggle camera motion smoothing.
void switchSnapping ()
Toggle automatic snapping when getting close to a camera from the interpolation path.
void switchMode (const InteractionMode mode)
Switch the interaction mode (trackball, fps,...).
void saveDefaultCamera (const std::string &datasetPath)
Save the current camera as a binary file to a standard location.
void loadDefaultCamera (const sibr::InputCamera &cam, const std::string &datasetPath)
Load a camera parameters from a binary file at a standard location.
InteractionMode getMode () const
void setFPSCameraSpeed (const float speed)
Set the speed of the FPS camera.
virtual void update (const sibr::Input &input, float deltaTime, const sibr::Viewport &viewport=Viewport(0.0f, 0.0f, 0.0f, 0.0f)) override
ICameraHandler interface.
virtual const sibr::InputCamera & getCamera (void) const override
virtual void onRender (const sibr::Viewport &viewport) override
Render additional information on screen (trackball gizmo).
virtual void onGUI (const std::string &suffix) override
Show the GUI.
sibr::CameraRecorder & getCameraRecorder ()
sibr::TrackBall & getTrackball ()
void snapToCamera (int id=-1)
Snap the interactive camera to one of the interpolation path cameras.
std::shared_ptr< Raycaster > & getRaycaster ()
bool isSetup () const
const sibr::Viewport & getViewport () const
float & getRadius ()
Private Member Functions
void interpolate ()
Interpolate along the path.
Private Attributes
int _currentCamId
Current snapped camera ID.
bool _shouldSmooth
Motion smoothing.
bool _shouldSnap
Currently snapping.
sibr::FPSCamera _fpsCamera
FPS handler.
sibr::Orbit _orbit
Orbit handler.
sibr::TrackBall _trackball
Trackball handler.
InteractionMode _currentMode
Current handler mode.
float _radius
Trackball radius property (for GUI).
std::shared_ptr< sibr::Raycaster > _raycaster
Raycaster (for trackball).
sibr::Viewport _viewport
Current viewport.
sibr::InputCamera _previousCamera
Previous camera (for interpolation).
sibr::InputCamera _currentCamera
Current camera.
uint _startCam
Parameters for path interpolation.
uint _interpFactor
Current interpolation factor between cam _startCam and _startCam+1.
std::vector< InputCamera::Ptr > _interpPath
Cameras along the path.
sibr::CameraRecorder _cameraRecorder
Camera recorder.
bool _supportRecording
Does the camera support recording (uneeded).
std::vector< InputCamera::Ptr > _keyCameras
Key cameras saved punctually.
sibr::Vector2f _clippingPlanes
Clipping planes parameter (for GUI).
bool _saveFrame
Should the frame be saved as an image.
bool _saveFrameVideo
Should the frame be saved as part of a video.
bool _triggerCameraUpdate
Should the camera be updated (delayed if info is missing).
bool _isSetup
Is the handler setup.
float _cameraFovDeg = 0.0f
Camera field of view in degrees (for GUI).
bool _fribrExport = false
Switch to FRIBR compatible export mode for paths.
Detailed Description
The InteractiveCameraHandler gathers various types of camera interactions and allows the user to switch between them, keeping them in sync.
It can also perform camera interpolation along a path.
Definition at line 30 of file InteractiveCameraHandler.hpp.
Member Enumeration Documentation
InteractionMode
enum sibr::InteractiveCameraHandler::InteractionMode
Current handler interaction mode.
Enumerator
FPS
ORBIT
INTERPOLATION
TRACKBALL
NONE
Definition at line 38 of file InteractiveCameraHandler.hpp.
Constructor & Destructor Documentation
InteractiveCameraHandler()
sibr::InteractiveCameraHandler::InteractiveCameraHandler (const bool supportRecording = true)
Constructor.
Parameters
supportRecording can this handler record camera paths.
Todo:
Do we really need this option?
Definition at line 16 of file InteractiveCameraHandler.cpp.
References _currentCamId, _currentMode, _interpFactor, _isSetup, _radius, _saveFrame, _saveFrameVideo, _shouldSmooth, _shouldSnap, _startCam, _supportRecording, _triggerCameraUpdate, _viewport, sibr::UIShortcuts::add(), FPS, sibr::UIShortcuts::global(), and IBRVIEW_USESMOOTHCAM.
Member Function Documentation
findNearestCamera()
int sibr::InteractiveCameraHandler::findNearestCamera (const std::vector< InputCamera::Ptr > & inputCameras) const
Find the camera in a list closest to the current interactive camera position.
Parameters
inputCameras the list to search in
Returns
the index of the closest camera in the list, or -1
Note
This function ignores cameras that are not 'active' in the list.
Definition at line 218 of file InteractiveCameraHandler.cpp.
References _currentCamera, sibr::IBRBasicUtils::selectCamerasAngleWeight(), sibr::IBRBasicUtils::selectCamerasSimpleDist(), and weight().
Referenced by onGUI(), and snapToCamera().
fromCamera()
void sibr::InteractiveCameraHandler::fromCamera (const sibr::InputCamera & cam, bool interpolate = true, bool updateResolution = true)
Move the interactive camera to a new position and change its internal parameters.
Parameters
cam the cameras the parameters and pose should be copied from
interpolate smooth interpolation between the current pose and the new one
updateResolution should the resolution of the camera be updated or not. Can be disabled if the new cam has a size incompatible with the current viewport.
Definition at line 123 of file InteractiveCameraHandler.cpp.
References _cameraFovDeg, _clippingPlanes, _currentCamera, _fpsCamera, _isSetup, _orbit, _previousCamera, _radius, _raycaster, _trackball, _triggerCameraUpdate, _viewport, sibr::Camera::aspect(), sibr::Camera::dir(), sibr::RayHit::dist(), sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), sibr::Camera::fovy(), sibr::TrackBall::fromCamera(), sibr::FPSCamera::fromCamera(), sibr::Orbit::fromCamera(), sibr::RayHit::hitSomething(), interpolate(), sibr::Viewport::isEmpty(), sibr::Camera::position(), sibr::InputCamera::size(), sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::MultiMeshManager::addMeshData(), fromTransform(), sibr::SceneDebugView::gui_cameras(), sibr::MultiMeshManager::list_mesh_onGUI(), loadDefaultCamera(), sibr::MultiMeshManager::MultiMeshManager(), onGUI(), sibr::MultiMeshManager::onUpdate(), setClippingPlanes(), sibr::SceneDebugView::setScene(), setup(), snapToCamera(), switchMode(), and update().
fromTransform()
void sibr::InteractiveCameraHandler::fromTransform (const Transform3f & transform, bool interpolate = true, bool updateResolution = true)
Move the interactive camera to a new position.
Parameters
transform the transform the orientation and pose should be copied from
interpolate smooth interpolation between the current pose and the new one
updateResolution should the resolution of the camera be updated or not. Can be disabled if the new cam has a size incompatible with the current viewport.
Definition at line 165 of file InteractiveCameraHandler.cpp.
References fromCamera(), getCamera(), interpolate(), and sibr::Camera::transform().
Referenced by sibr::MultiMeshManager::setIntialView(), and sibr::SceneDebugView::setup().
getCamera()
const sibr::InputCamera & sibr::InteractiveCameraHandler::getCamera (void) const override virtual
Returns
the current camera.
Implements sibr::ICameraHandler.
Definition at line 477 of file InteractiveCameraHandler.cpp.
References _currentCamera.
Referenced by sibr::MultiMeshManager::addMeshData(), fromTransform(), sibr::MultiMeshManager::list_mesh_onGUI(), onGUI(), sibr::SceneDebugView::onRender(), sibr::MultiMeshManager::renderMeshes(), sibr::SceneDebugView::save(), sibr::MultiMeshManager::setIntialView(), sibr::SceneDebugView::setScene(), and sibr::SceneDebugView::setup().
getCameraRecorder()
sibr::CameraRecorder& sibr::InteractiveCameraHandler::getCameraRecorder () inline
Returns
the camera recorder
Definition at line 171 of file InteractiveCameraHandler.hpp.
getMode()
InteractionMode sibr::InteractiveCameraHandler::getMode () const inline
Returns
the current interaction mode.
Definition at line 142 of file InteractiveCameraHandler.hpp.
getRadius()
float& sibr::InteractiveCameraHandler::getRadius () inline
Returns
radius used for trackball
Definition at line 193 of file InteractiveCameraHandler.hpp.
getRaycaster()
std::shared_ptr<Raycaster>& sibr::InteractiveCameraHandler::getRaycaster () inline
Returns
the handler raycaster.
Warning
Can be nullptr
Definition at line 184 of file InteractiveCameraHandler.hpp.
Referenced by sibr::MultiMeshManager::onUpdate(), and sibr::SceneDebugView::setScene().
getTrackball()
sibr::TrackBall& sibr::InteractiveCameraHandler::getTrackball () inline
Returns
the camera trackball
Definition at line 174 of file InteractiveCameraHandler.hpp.
getViewport()
const sibr::Viewport& sibr::InteractiveCameraHandler::getViewport () const inline
Returns
the handler viewport
Definition at line 190 of file InteractiveCameraHandler.hpp.
Referenced by sibr::SceneDebugView::gui_cameras(), and sibr::SceneDebugView::setScene().
interpolate()
void sibr::InteractiveCameraHandler::interpolate () private
Interpolate along the path.
Definition at line 279 of file InteractiveCameraHandler.cpp.
References _currentCamera, _interpFactor, _interpPath, _startCam, _viewport, sibr::Camera::aspect(), sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), sibr::InputCamera::h(), sibr::Camera::interpolate(), SIBR_INTERPOLATE_FRAMES, and sibr::InputCamera::w().
Referenced by fromCamera(), fromTransform(), and update().
isSetup()
bool sibr::InteractiveCameraHandler::isSetup () const inline
Returns
true if the handler has been entirely setup
Definition at line 187 of file InteractiveCameraHandler.hpp.
Referenced by sibr::MultiMeshManager::onUpdate().
loadDefaultCamera()
void sibr::InteractiveCameraHandler::loadDefaultCamera (const sibr::InputCamera & cam, const std::string & datasetPath)
Load a camera parameters from a binary file at a standard location.
Parameters
cam the camera to use if loading fails
datasetPath source directory
Note
"default_camera.bin" will be appended to the path.
Definition at line 55 of file InteractiveCameraHandler.cpp.
References fromCamera(), sibr::InputCamera::loadFromBinary(), and SIBR_LOG.
onGUI()
void sibr::InteractiveCameraHandler::onGUI (const std::string & suffix) override virtual
Show the GUI.
Parameters
suffix additional GUI name suffix to avoid collisions when having multiple handlers.
Reimplemented from sibr::ICameraHandler.
Definition at line 487 of file InteractiveCameraHandler.cpp.
References _cameraFovDeg, _cameraRecorder, _clippingPlanes, _currentCamera, _currentCamId, _currentMode, _fpsCamera, _fribrExport, _interpPath, _keyCameras, _saveFrame, _saveFrameVideo, _shouldSmooth, _supportRecording, _trackball, sibr::Camera::aspect(), sibr::clamp(), sibr::Default, sibr::Directory, sibr::TrackBall::drawThis, sibr::Key::End, findNearestCamera(), sibr::Camera::fovy(), fromCamera(), getCamera(), sibr::InputCamera::h(), sibr::CameraRecorder::load(), sibr::CameraRecorder::loadBundle(), sibr::CameraRecorder::loadColmap(), sibr::InputCamera::loadFromBinary(), sibr::CameraRecorder::loadLookat(), sibr::FPSCamera::onGUI(), sibr::CameraRecorder::playback(), sibr::CameraRecorder::playNoInterpolation(), ImGui::PushScaledItemWidth(), sibr::CameraRecorder::record(), sibr::CameraRecorder::reset(), sibr::CameraRecorder::save(), sibr::Save, sibr::CameraRecorder::saveAsBundle(), sibr::CameraRecorder::saveAsFRIBRBundle(), sibr::CameraRecorder::saveAsLookAt(), sibr::InputCamera::saveAsLookat(), sibr::InputCamera::saveToBinary(), sibr::CameraRecorder::saving(), sibr::CameraRecorder::savingVideo(), sibr::showFilePicker(), SIBR_LOG, snapToCamera(), sibr::CameraRecorder::speed(), sibr::CameraRecorder::stop(), sibr::CameraRecorder::stopSaving(), switchMode(), TRACKBALL, sibr::InputCamera::w(), sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::SceneDebugView::gui_options().
onRender()
void sibr::InteractiveCameraHandler::onRender (const sibr::Viewport & viewport) override virtual
Render additional information on screen (trackball gizmo).
Parameters
viewport the window viewport
Reimplemented from sibr::ICameraHandler.
Definition at line 481 of file InteractiveCameraHandler.cpp.
References _currentMode, _trackball, sibr::TrackBall::onRender(), and TRACKBALL.
Referenced by sibr::MultiMeshManager::onRender(), and sibr::SceneDebugView::onRender().
saveDefaultCamera()
void sibr::InteractiveCameraHandler::saveDefaultCamera (const std::string & datasetPath)
Save the current camera as a binary file to a standard location.
Parameters
datasetPath destination directory
Note
"default_camera.bin" will be appended to the path.
Definition at line 46 of file InteractiveCameraHandler.cpp.
References _currentCamera, sibr::InputCamera::saveToBinary(), and SIBR_LOG.
setClippingPlanes()
void sibr::InteractiveCameraHandler::setClippingPlanes (float znear, float zfar)
Set the clipping planes.
Parameters
znear near plane
zfar far plane
Definition at line 172 of file InteractiveCameraHandler.cpp.
References _clippingPlanes, _currentCamera, fromCamera(), sibr::Camera::zfar(), and sibr::Camera::znear().
setFPSCameraSpeed()
void sibr::InteractiveCameraHandler::setFPSCameraSpeed (const float speed)
Set the speed of the FPS camera.
Parameters
speed the new speed
Definition at line 317 of file InteractiveCameraHandler.cpp.
References _fpsCamera, and sibr::FPSCamera::setSpeed().
setup() [1/5]
void sibr::InteractiveCameraHandler::setup (const Eigen::AlignedBox< float, 3 > & areaOfInterest, const sibr::Viewport & viewport, const std::shared_ptr< sibr::Raycaster > raycaster)
Setup an interactive camera handler from an area of interest.
The interactive camera will be initialized so that the area is completely visible.
Parameters
areaOfInterest the region of space to show
viewport the window viewport
raycaster raycaster containing the mesh displayed (used for the trackball centering), can be nullptr
Definition at line 79 of file InteractiveCameraHandler.cpp.
References _raycaster, _trackball, _viewport, sibr::TrackBall::fromBoundingBox(), fromCamera(), and sibr::TrackBall::getCamera().
setup() [2/5]
void sibr::InteractiveCameraHandler::setup (const sibr::InputCamera & cam, const sibr::Viewport & viewport, const std::shared_ptr< sibr::Raycaster > raycaster)
Setup an interactive camera handler from an existing camera.
The interactive camera will be initialized at the position of the argument camera.
Parameters
cam initialization camera
viewport the window viewport
raycaster raycaster containing the mesh displayed (used for the trackball centering), can be nullptr
Definition at line 73 of file InteractiveCameraHandler.cpp.
References _raycaster, _viewport, and fromCamera().
setup() [3/5]
void sibr::InteractiveCameraHandler::setup (const std::vector< InputCamera::Ptr > & cams, const sibr::Vector2u & resolution, const sibr::Viewport & viewport, const std::shared_ptr< sibr::Raycaster > raycaster)
Deprecated:
Resolution is deprecated and will be removed in the near future. See setup(const std::vector<InputCamera::Ptr>&, const sibr::Viewport&, std::shared_ptr<sibr::Raycaster>,...) instead.
Definition at line 67 of file InteractiveCameraHandler.cpp.
Referenced by sibr::SceneDebugView::setScene(), and setup().
setup() [4/5]
void sibr::InteractiveCameraHandler::setup (const std::vector< InputCamera::Ptr > & cams, const sibr::Viewport & viewport, std::shared_ptr< sibr::Raycaster > raycaster, const sibr::Vector2f & clippingPlanes = {-1.0f,-1.0f})
Setup an interactive camera handler from a series of existing cameras and mesh.
The interactive camera will be initialized at the position of the first camera from the list.
Parameters
cams a list of cameras (used for interpolation path)
viewport the window viewport
raycaster raycaster containing the mesh displayed (used for the trackball centering), can be nullptr
clippingPlanes optional clipping planes to enforce
Definition at line 88 of file InteractiveCameraHandler.cpp.
References _interpPath, setup(), setupInterpolationPath(), SIBR_LOG, sibr::Camera::zfar(), and sibr::Camera::znear().
setup() [5/5]
void sibr::InteractiveCameraHandler::setup (std::shared_ptr< sibr::Mesh > mesh, const sibr::Viewport & viewport)
Setup an interactive camera handler from a mesh.
The interactive camera will be initialized so that the mesh is completely visible.
Parameters
mesh the mesh to display
viewport the window viewport
Note
a raycaster will be set up internally
Definition at line 114 of file InteractiveCameraHandler.cpp.
References _radius, _raycaster, _trackball, _viewport, sibr::TrackBall::fromBoundingBox(), fromCamera(), sibr::Mesh::getBoundingBox(), and sibr::TrackBall::getCamera().
setupInterpolationPath()
void sibr::InteractiveCameraHandler::setupInterpolationPath (const std::vector< InputCamera::Ptr > & cameras)
Setup a camera path for the interpolation mode.
Parameters
cameras to interpolate along
Definition at line 249 of file InteractiveCameraHandler.cpp.
References _interpPath.
Referenced by sibr::SceneDebugView::setScene(), and setup().
SIBR_CLASS_PTR()
sibr::InteractiveCameraHandler::SIBR_CLASS_PTR (InteractiveCameraHandler)
snapToCamera()
void sibr::InteractiveCameraHandler::snapToCamera (int id = -1)
Snap the interactive camera to one of the interpolation path cameras.
Parameters
id the index of the camera to snap to. if -1, the closest camera.
Definition at line 309 of file InteractiveCameraHandler.cpp.
References _interpPath, sibr::clamp(), findNearestCamera(), and fromCamera().
Referenced by onGUI(), and update().
switchMode()
void sibr::InteractiveCameraHandler::switchMode (const InteractionMode mode)
Switch the interaction mode (trackball, fps,...).
Parameters
mode the new mode
Definition at line 184 of file InteractiveCameraHandler.cpp.
References _currentCamera, _currentMode, _interpFactor, _shouldSmooth, FPS, fromCamera(), INTERPOLATION, NONE, ORBIT, and TRACKBALL.
Referenced by sibr::MultiMeshManager::MultiMeshManager(), onGUI(), and update().
switchSmoothing()
void sibr::InteractiveCameraHandler::switchSmoothing () inline
Toggle camera motion smoothing.
Definition at line 118 of file InteractiveCameraHandler.hpp.
References SIBR_LOG.
switchSnapping()
void sibr::InteractiveCameraHandler::switchSnapping () inline
Toggle automatic snapping when getting close to a camera from the interpolation path.
Definition at line 121 of file InteractiveCameraHandler.hpp.
References SIBR_LOG.
Referenced by update().
update()
void sibr::InteractiveCameraHandler::update (const sibr::Input & input, float deltaTime, const sibr::Viewport & viewport = Viewport(0.0f, 0.0f, 0.0f, 0.0f)) override virtual
ICameraHandler interface.
Update function, call at every tick.
Parameters
input the input object for the current view.
deltaTime time elapsed since last frame
viewport optional window viewport (can be used by the trackball for instance)
Implements sibr::ICameraHandler.
Definition at line 321 of file InteractiveCameraHandler.cpp.
References _cameraRecorder, _clippingPlanes, _currentCamera, _currentMode, _fpsCamera, _fribrExport, _interpPath, _orbit, _previousCamera, _raycaster, _saveFrame, _shouldSmooth, _shouldSnap, _supportRecording, _trackball, _triggerCameraUpdate, _viewport, sibr::Camera::aspect(), sibr::Key::B, sibr::Key::C, sibr::TrackBall::drawThis, FPS, fromCamera(), sibr::FPSCamera::getCamera(), sibr::Orbit::getCamera(), sibr::TrackBall::getCamera(), sibr::InputCamera::h(), IBRVIEW_SMOOTHCAM_POWER, interpolate(), sibr::Camera::interpolate(), INTERPOLATION, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Viewport::isEmpty(), sibr::CameraRecorder::isPlaying(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Input::key(), sibr::Key::LeftAlt, sibr::Key::LeftControl, sibr::Key::LeftShift, sibr::CameraRecorder::load(), sibr::CameraRecorder::loadBundle(), NONE, ORBIT, sibr::Key::P, sibr::CameraRecorder::playback(), sibr::CameraRecorder::record(), sibr::CameraRecorder::reset(), sibr::Key::RightAlt, sibr::CameraRecorder::save(), sibr::CameraRecorder::saveAsBundle(), sibr::CameraRecorder::saveAsFRIBRBundle(), sibr::CameraRecorder::saveAsLookAt(), sibr::CameraRecorder::saving(), SIBR_LOG, sibr::FPSCamera::snap(), snapToCamera(), sibr::Key::Space, sibr::CameraRecorder::stop(), sibr::CameraRecorder::stopSaving(), switchMode(), switchSnapping(), TRACKBALL, sibr::TrackBall::update(), sibr::Orbit::update(), sibr::FPSCamera::update(), sibr::CameraRecorder::use(), sibr::Key::V, sibr::InputCamera::w(), sibr::Key::Y, sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::MultiMeshManager::onUpdate().
Member Data Documentation
_cameraFovDeg
float sibr::InteractiveCameraHandler::_cameraFovDeg = 0.0f private
Camera field of view in degrees (for GUI).
Definition at line 230 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), and onGUI().
_cameraRecorder
sibr::CameraRecorder sibr::InteractiveCameraHandler::_cameraRecorder private
Camera recorder.
Definition at line 221 of file InteractiveCameraHandler.hpp.
Referenced by onGUI(), and update().
_clippingPlanes
sibr::Vector2f sibr::InteractiveCameraHandler::_clippingPlanes private
Clipping planes parameter (for GUI).
Definition at line 225 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), onGUI(), setClippingPlanes(), and update().
_currentCamera
sibr::InputCamera sibr::InteractiveCameraHandler::_currentCamera private
Current camera.
Definition at line 214 of file InteractiveCameraHandler.hpp.
Referenced by findNearestCamera(), fromCamera(), getCamera(), interpolate(), onGUI(), saveDefaultCamera(), setClippingPlanes(), switchMode(), and update().
_currentCamId
int sibr::InteractiveCameraHandler::_currentCamId private
Current snapped camera ID.
Definition at line 197 of file InteractiveCameraHandler.hpp.
Referenced by InteractiveCameraHandler(), and onGUI().
_currentMode
InteractionMode sibr::InteractiveCameraHandler::_currentMode private
Current handler mode.
Definition at line 206 of file InteractiveCameraHandler.hpp.
Referenced by InteractiveCameraHandler(), onGUI(), onRender(), switchMode(), and update().
_fpsCamera
sibr::FPSCamera sibr::InteractiveCameraHandler::_fpsCamera private
FPS handler.
Definition at line 202 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), onGUI(), setFPSCameraSpeed(), and update().
_fribrExport
bool sibr::InteractiveCameraHandler::_fribrExport = false private
Switch to FRIBR compatible export mode for paths.
Definition at line 231 of file InteractiveCameraHandler.hpp.
Referenced by onGUI(), and update().
_interpFactor
uint sibr::InteractiveCameraHandler::_interpFactor private
Current interpolation factor between cam _startCam and _startCam+1.
Definition at line 218 of file InteractiveCameraHandler.hpp.
Referenced by InteractiveCameraHandler(), interpolate(), and switchMode().
_interpPath
std::vector<InputCamera::Ptr> sibr::InteractiveCameraHandler::_interpPath private
Cameras along the path.
Definition at line 219 of file InteractiveCameraHandler.hpp.
Referenced by interpolate(), onGUI(), setup(), setupInterpolationPath(), snapToCamera(), and update().
_isSetup
bool sibr::InteractiveCameraHandler::_isSetup private
Is the handler setup.
Definition at line 229 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), and InteractiveCameraHandler().
_keyCameras
std::vector<InputCamera::Ptr> sibr::InteractiveCameraHandler::_keyCameras private
Key cameras saved punctually.
Note
This could be merged with the camera recorder.
Definition at line 223 of file InteractiveCameraHandler.hpp.
Referenced by onGUI().
_orbit
sibr::Orbit sibr::InteractiveCameraHandler::_orbit private
Orbit handler.
Definition at line 203 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), and update().
_previousCamera
sibr::InputCamera sibr::InteractiveCameraHandler::_previousCamera private
Previous camera (for interpolation).
Definition at line 213 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), and update().
_radius
float sibr::InteractiveCameraHandler::_radius private
Trackball radius property (for GUI).
Definition at line 208 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), InteractiveCameraHandler(), and setup().
_raycaster
std::shared_ptr<sibr::Raycaster> sibr::InteractiveCameraHandler::_raycaster private
Raycaster (for trackball).
Definition at line 210 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), setup(), and update().
_saveFrame
bool sibr::InteractiveCameraHandler::_saveFrame private
Should the frame be saved as an image.
Definition at line 226 of file InteractiveCameraHandler.hpp.
Referenced by InteractiveCameraHandler(), onGUI(), and update().
_saveFrameVideo
bool sibr::InteractiveCameraHandler::_saveFrameVideo private
Should the frame be saved as part of a video.
Definition at line 227 of file InteractiveCameraHandler.hpp.
Referenced by InteractiveCameraHandler(), and onGUI().
_shouldSmooth
bool sibr::InteractiveCameraHandler::_shouldSmooth private
Motion smoothing.
Definition at line 199 of file InteractiveCameraHandler.hpp.
Referenced by InteractiveCameraHandler(), onGUI(), switchMode(), and update().
_shouldSnap
bool sibr::InteractiveCameraHandler::_shouldSnap private
Currently snapping.
Definition at line 200 of file InteractiveCameraHandler.hpp.
Referenced by InteractiveCameraHandler(), and update().
_startCam
uint sibr::InteractiveCameraHandler::_startCam private
Parameters for path interpolation.
Start camera index in the list.
Definition at line 217 of file InteractiveCameraHandler.hpp.
Referenced by InteractiveCameraHandler(), and interpolate().
_supportRecording
bool sibr::InteractiveCameraHandler::_supportRecording private
Does the camera support recording (uneeded).
Definition at line 222 of file InteractiveCameraHandler.hpp.
Referenced by InteractiveCameraHandler(), onGUI(), and update().
_trackball
sibr::TrackBall sibr::InteractiveCameraHandler::_trackball private
Trackball handler.
Definition at line 204 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), onGUI(), onRender(), setup(), and update().
_triggerCameraUpdate
bool sibr::InteractiveCameraHandler::_triggerCameraUpdate private
Should the camera be updated (delayed if info is missing).
Definition at line 228 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), InteractiveCameraHandler(), and update().
_viewport
sibr::Viewport sibr::InteractiveCameraHandler::_viewport private
Current viewport.
Definition at line 211 of file InteractiveCameraHandler.hpp.
Referenced by fromCamera(), InteractiveCameraHandler(), interpolate(), setup(), and update().
The documentation for this class was generated from the following files:
src/core/view/InteractiveCameraHandler.hpp
src/core/view/InteractiveCameraHandler.cpp