SIBR: PlaneEstimator Class Reference
PlaneEstimator Class Reference
sibr_raycaster
Fit a plane to a point cloud using an improved RANSAC approach.
#include <PlaneEstimator.hpp>
Public Member Functions
PlaneEstimator ()
Default constructor.
PlaneEstimator (const std::vector< sibr::Vector3f > &vertices, bool excludeBB=false)
Constructor.
void computePlanes (const int numPlane, const float delta, const int numTry)
Compute one or more planes fitting the data using RANSAC.
sibr::Vector4f estimatePlane (const float delta, const int numTry, Eigen::MatrixXi &bestMask, int &vote, std::pair< Eigen::MatrixXf, sibr::Vector3f > &bestCovMean)
Estimate the best plane in the remaining points set using RANSAC.
sibr::Vector4f plane3Pts ()
Choose randomly 3 points among the vertices and compute the corresponding plane.
std::pair< int, float > votePlane (const sibr::Vector4f plane, const float delta, Eigen::MatrixXi &mask, float normalDot=0.98)
Given a plane and a threshold, this function return the num of point that fit the plane in the remaining points and also the associated mask.
void displayPCAndPlane (sibr::Window::Ptr window)
For visualization, display the point cloud and fitted plane in a window.
sibr::Vector4f estimateGroundPlane (sibr::Vector3f roughUp)
Estimate a fitting plane that is as orthogonal to the given up vector as possible.
~PlaneEstimator (void)
Destructor.
Static Public Member Functions
static sibr::Vector3f estimateMedianVec (const std::vector< sibr::Vector3f > &ups)
Estimate the scene zenith from a set of camera up vectors (assuming photogrametric capture).
static sibr::Mesh getMeshPlane (sibr::Vector4f plane, sibr::Vector3f center, float radius)
Generate a mesh representing a plane.
Public Attributes
std::vector< sibr::Vector3f > _Points
All initial points.
int _numPoints3D
Number of initial points.
std::vector< sibr::Vector4f > _planes
Planes are represented as Vector4f(n.x,n.y,n.z,d)
std::vector< std::vector< sibr::Vector3f > > _points
For each plane, list of fitting points.
std::vector< sibr::Vector3f > _centers
Plane centers.
std::vector< int > _votes
Number of votes per plane.
std::vector< std::pair< Eigen::MatrixXf, sibr::Vector3f > > _covMeans
Unused.
Protected Attributes
Eigen::MatrixXf _remainPoints3D
Points to consider.
Eigen::MatrixXf _remainNormals3D
Associated normals to consider.
std::vector< sibr::Vector3u > _Triangles
Triangle list.
bool _planeComputed
Has the plane been computed.
Detailed Description
Fit a plane to a point cloud using an improved RANSAC approach.
Definition at line 17 of file PlaneEstimator.hpp.
Constructor & Destructor Documentation
PlaneEstimator() [1/2]
PlaneEstimator::PlaneEstimator ()
Default constructor.
Definition at line 6 of file PlaneEstimator.cpp.
PlaneEstimator() [2/2]
PlaneEstimator::PlaneEstimator (const std::vector< sibr::Vector3f > & vertices, bool excludeBB = false)
Constructor.
Parameters
vertices the point cloud
excludeBB if true, reject points that are close to the vertices bounding box
Definition at line 8 of file PlaneEstimator.cpp.
References _numPoints3D, _planeComputed, _Points, _remainNormals3D, and _remainPoints3D.
~PlaneEstimator()
PlaneEstimator::~PlaneEstimator (void)
Destructor.
Definition at line 348 of file PlaneEstimator.cpp.
Member Function Documentation
computePlanes()
void PlaneEstimator::computePlanes (const int numPlane, const float delta, const int numTry)
Compute one or more planes fitting the data using RANSAC.
Points that are well fitted by a plan will bre moved from the set.
Parameters
numPlane number of planes to fit
delta fit validity threshold
numTry number of attempts to perform for each plane
Definition at line 61 of file PlaneEstimator.cpp.
References _centers, _covMeans, _numPoints3D, _planeComputed, _planes, _points, _remainNormals3D, _remainPoints3D, _votes, and estimatePlane().
displayPCAndPlane()
void PlaneEstimator::displayPCAndPlane (sibr::Window::Ptr window)
For visualization, display the point cloud and fitted plane in a window.
Parameters
window the windo to use for display
Deprecated:
Empty, won't do anything.
Definition at line 344 of file PlaneEstimator.cpp.
estimateGroundPlane()
sibr::Vector4f PlaneEstimator::estimateGroundPlane (sibr::Vector3f roughUp)
Estimate a fitting plane that is as orthogonal to the given up vector as possible.
Parameters
roughUp an estimation of the scene up vector
Returns
the plane parameters.
Definition at line 263 of file PlaneEstimator.cpp.
References _planeComputed, _planes, _votes, sibr::dot(), SIBR_ERR, and xyz().
estimateMedianVec()
sibr::Vector3f PlaneEstimator::estimateMedianVec (const std::vector< sibr::Vector3f > & ups) static
Estimate the scene zenith from a set of camera up vectors (assuming photogrametric capture).
Parameters
ups a set of up vector
Returns
the estimated median zenith vector
Definition at line 289 of file PlaneEstimator.cpp.
estimatePlane()
sibr::Vector4f PlaneEstimator::estimatePlane (const float delta, const int numTry, Eigen::MatrixXi & bestMask, int & vote, std::pair< Eigen::MatrixXf, sibr::Vector3f > & bestCovMean)
Estimate the best plane in the remaining points set using RANSAC.
Parameters
delta fit validity threshold
numTry number of attempts to perform for each plane
bestMask for each point, will be set to 1 if the plane explains the point well
vote will contain the number of points that fit
bestCovMean unused
Returns
the plane parameters
Definition at line 131 of file PlaneEstimator.cpp.
References plane3Pts(), and votePlane().
Referenced by computePlanes().
getMeshPlane()
sibr::Mesh PlaneEstimator::getMeshPlane (sibr::Vector4f plane, sibr::Vector3f center, float radius) static
Generate a mesh representing a plane.
Parameters
plane the parameters of the plane to represent
center center of the plane mesh
radius extent of the plane mesh
Returns
the generated plane mesh
Definition at line 315 of file PlaneEstimator.cpp.
References sibr::dot(), sibr::Mesh::normals(), sibr::Mesh::triangles(), and sibr::Mesh::vertices().
plane3Pts()
sibr::Vector4f PlaneEstimator::plane3Pts ()
Choose randomly 3 points among the vertices and compute the corresponding plane.
Returns
the plane parameters
Definition at line 211 of file PlaneEstimator.cpp.
References _remainPoints3D, and sibr::cross().
Referenced by estimatePlane().
votePlane()
std::pair< int, float > PlaneEstimator::votePlane (const sibr::Vector4f plane, const float delta, Eigen::MatrixXi & mask, float normalDot = 0.98)
Given a plane and a threshold, this function return the num of point that fit the plane in the remaining points and also the associated mask.
Parameters
plane the plane parameters
delta validity threshold
mask for each point, will be set to 1 if the plane explains the point well
normalDot normal validity threshold
Returns
number of points that fit and overall weighted score (based on normal similarity)
Definition at line 230 of file PlaneEstimator.cpp.
References _remainNormals3D, and _remainPoints3D.
Referenced by estimatePlane().
Member Data Documentation
_centers
std::vector<sibr::Vector3f> PlaneEstimator::_centers
Plane centers.
Definition at line 92 of file PlaneEstimator.hpp.
Referenced by computePlanes().
_covMeans
std::vector<std::pair<Eigen::MatrixXf,sibr::Vector3f> > PlaneEstimator::_covMeans
Unused.
Definition at line 94 of file PlaneEstimator.hpp.
Referenced by computePlanes().
_numPoints3D
int PlaneEstimator::_numPoints3D
Number of initial points.
Definition at line 88 of file PlaneEstimator.hpp.
Referenced by computePlanes(), and PlaneEstimator().
_planeComputed
bool PlaneEstimator::_planeComputed protected
Has the plane been computed.
Definition at line 104 of file PlaneEstimator.hpp.
Referenced by computePlanes(), estimateGroundPlane(), and PlaneEstimator().
_planes
std::vector<sibr::Vector4f> PlaneEstimator::_planes
Planes are represented as Vector4f(n.x,n.y,n.z,d)
Definition at line 90 of file PlaneEstimator.hpp.
Referenced by computePlanes(), and estimateGroundPlane().
_Points
std::vector<sibr::Vector3f> PlaneEstimator::_Points
All initial points.
Definition at line 87 of file PlaneEstimator.hpp.
Referenced by PlaneEstimator().
_points
std::vector<std::vector<sibr::Vector3f> > PlaneEstimator::_points
For each plane, list of fitting points.
Definition at line 91 of file PlaneEstimator.hpp.
Referenced by computePlanes().
_remainNormals3D
Eigen::MatrixXf PlaneEstimator::_remainNormals3D protected
Associated normals to consider.
Definition at line 102 of file PlaneEstimator.hpp.
Referenced by computePlanes(), PlaneEstimator(), and votePlane().
_remainPoints3D
Eigen::MatrixXf PlaneEstimator::_remainPoints3D protected
Points to consider.
Definition at line 101 of file PlaneEstimator.hpp.
Referenced by computePlanes(), plane3Pts(), PlaneEstimator(), and votePlane().
_Triangles
std::vector<sibr::Vector3u> PlaneEstimator::_Triangles protected
Triangle list.
Definition at line 103 of file PlaneEstimator.hpp.
_votes
std::vector<int> PlaneEstimator::_votes
Number of votes per plane.
Definition at line 93 of file PlaneEstimator.hpp.
Referenced by computePlanes(), and estimateGroundPlane().
The documentation for this class was generated from the following files:
src/core/raycaster/PlaneEstimator.hpp
src/core/raycaster/PlaneEstimator.cpp