SIBR: sibr::PositionRenderer Class Reference
sibr::PositionRenderer Class Reference
sibr_renderer
Render the world space positions of a mesh surface.
#include <PositionRender.hpp>
Public Member Functions
PositionRenderer (int w, int h)
Constructor with a target size.
void render (const sibr::Camera &cam, const Mesh &mesh, bool backFaceCulling=false, bool frontFaceCulling=false)
Render the mesh world positions.
const sibr::RenderTargetRGB32F::Ptr & getPositionsRT ()
Private Member Functions
SIBR_CLASS_PTR (PositionRenderer)
Private Attributes
sibr::GLShader _shader
The positions shader.
sibr::GLuniform< sibr::Matrix4f > _MVP
MVP uniform.
sibr::RenderTargetRGB32F::Ptr _RT
Destination render target.
Detailed Description
Render the world space positions of a mesh surface.
Definition at line 18 of file PositionRender.hpp.
Constructor & Destructor Documentation
PositionRenderer()
sibr::PositionRenderer::PositionRenderer (int w, int h)
Constructor with a target size.
Parameters
w the target width
h the target height
Definition at line 7 of file PositionRender.cpp.
References _MVP, _RT, _shader, sibr::GLuniform< T >::init(), sibr::GLShader::init(), sibr::Resources::Instance(), and sibr::loadFile().
Member Function Documentation
getPositionsRT()
const sibr::RenderTargetRGB32F::Ptr& sibr::PositionRenderer::getPositionsRT () inline
Returns
the result rendertarget containing world space positions.
Definition at line 39 of file PositionRender.hpp.
render()
void sibr::PositionRenderer::render (const sibr::Camera & cam, const Mesh & mesh, bool backFaceCulling = false, bool frontFaceCulling = false)
Render the mesh world positions.
Parameters
cam the viewpoint to use
mesh the mesh to render
backFaceCulling should backface culling be performed
frontFaceCulling flip the culling test orientation
Definition at line 17 of file PositionRender.cpp.
References _MVP, _RT, _shader, sibr::GLShader::begin(), sibr::GLShader::end(), sibr::Mesh::FillRenderMode, sibr::Mesh::render(), sibr::GLuniform< T >::set(), and sibr::Camera::viewproj().
SIBR_CLASS_PTR()
sibr::PositionRenderer::SIBR_CLASS_PTR (PositionRenderer) private
Member Data Documentation
_MVP
sibr::GLuniform<sibr::Matrix4f> sibr::PositionRenderer::_MVP private
MVP uniform.
Definition at line 44 of file PositionRender.hpp.
Referenced by PositionRenderer(), and render().
_RT
sibr::RenderTargetRGB32F::Ptr sibr::PositionRenderer::_RT private
Destination render target.
Definition at line 45 of file PositionRender.hpp.
Referenced by PositionRenderer(), and render().
_shader
sibr::GLShader sibr::PositionRenderer::_shader private
The positions shader.
Definition at line 43 of file PositionRender.hpp.
Referenced by PositionRenderer(), and render().
The documentation for this class was generated from the following files:
src/core/renderer/PositionRender.hpp
src/core/renderer/PositionRender.cpp