SIBR: sibr::NormalRenderer Class Reference
sibr::NormalRenderer Class Reference
sibr_renderer
Render the world or view space normals of a mesh.
#include <NormalRenderer.hpp>
Public Member Functions
NormalRenderer (int w, int h, bool generate=true, bool useFloats=false, bool imSpace=false)
Constructor.
~NormalRenderer ()
Destructor.
void render (const sibr::InputCamera &cam, const Mesh &mesh, const Matrix4f &modelMat=Matrix4f::Identity(), bool clear=true)
Render the mesh normals in the internal render target.
void setWH (int w, int h)
Resize the internal rendertarget.
Public Attributes
std::shared_ptr< sibr::RenderTargetRGB > _normal_RT
The low-precision normal result rendertarget (used if useFloats is false).
std::shared_ptr< sibr::RenderTargetRGBA32F > _normal_RT_32F
The high-precision normal result rendertarget (used if useFloats is true).
Private Attributes
sibr::GLShader _normalShader
Normal shader.
sibr::GLParameter _normalShader_proj
Projection matrix uniform.
sibr::GLParameter _normalShader_view
View matrix uniform.
sibr::GLParameter _normalShader_model
Model matrix uniform.
sibr::GLParameter _normalShader_projInv
Inverse projection matrix uniform.
sibr::GLParameter _normalShader_imSpace
View space toggle uniform.
bool _generate
Should normals be generated on the fly.
bool _useFloats
Should the normals be rendered to a 32F precision target.
Detailed Description
Render the world or view space normals of a mesh.
Definition at line 20 of file NormalRenderer.hpp.
Constructor & Destructor Documentation
NormalRenderer()
sibr::NormalRenderer::NormalRenderer (int w, int h, bool generate = true, bool useFloats = false, bool imSpace = false)
Constructor.
Parameters
w target width
h target height
generate if true, use a geoemtry shader to compute normals on the fly, else use vertex normals
useFloats if true, render in a 32F rendertarget, else use 8U
imSpace if true, render view space normals, else render world space normals
Definition at line 11 of file NormalRenderer.cpp.
References _generate, _normal_RT, _normal_RT_32F, _normalShader, _normalShader_imSpace, _normalShader_model, _normalShader_proj, _normalShader_projInv, _normalShader_view, _useFloats, sibr::GLShader::begin(), sibr::GLShader::end(), sibr::GLParameter::init(), sibr::GLShader::init(), sibr::Resources::Instance(), sibr::loadFile(), and sibr::GLParameter::set().
~NormalRenderer()
sibr::NormalRenderer::~NormalRenderer ()
Destructor.
Definition at line 9 of file NormalRenderer.cpp.
Member Function Documentation
render()
void sibr::NormalRenderer::render (const sibr::InputCamera & cam, const Mesh & mesh, const Matrix4f & modelMat = Matrix4f::Identity(), bool clear = true)
Render the mesh normals in the internal render target.
Parameters
cam the viewpoint to use
mesh the mesh to render
modelMat additional model matrix
clear clear the rendertarget before rendering
Definition at line 58 of file NormalRenderer.cpp.
References _generate, _normal_RT, _normal_RT_32F, _normalShader, _normalShader_model, _normalShader_proj, _normalShader_projInv, _normalShader_view, _useFloats, sibr::GLShader::begin(), sibr::GLShader::end(), sibr::Mesh::FillRenderMode, sibr::Mesh::render(), sibr::GLParameter::set(), sibr::Camera::view(), and sibr::Camera::viewproj().
setWH()
void sibr::NormalRenderer::setWH (int w, int h)
Resize the internal rendertarget.
Parameters
w the new width
h the new height
Definition at line 49 of file NormalRenderer.cpp.
References _normal_RT, _normal_RT_32F, and _useFloats.
Member Data Documentation
_generate
bool sibr::NormalRenderer::_generate private
Should normals be generated on the fly.
Definition at line 62 of file NormalRenderer.hpp.
Referenced by NormalRenderer(), and render().
_normal_RT
std::shared_ptr<sibr::RenderTargetRGB> sibr::NormalRenderer::_normal_RT
The low-precision normal result rendertarget (used if useFloats is false).
Definition at line 51 of file NormalRenderer.hpp.
Referenced by NormalRenderer(), render(), and setWH().
_normal_RT_32F
std::shared_ptr<sibr::RenderTargetRGBA32F> sibr::NormalRenderer::_normal_RT_32F
The high-precision normal result rendertarget (used if useFloats is true).
Definition at line 52 of file NormalRenderer.hpp.
Referenced by NormalRenderer(), render(), and setWH().
_normalShader
sibr::GLShader sibr::NormalRenderer::_normalShader private
Normal shader.
Definition at line 56 of file NormalRenderer.hpp.
Referenced by NormalRenderer(), and render().
_normalShader_imSpace
sibr::GLParameter sibr::NormalRenderer::_normalShader_imSpace private
View space toggle uniform.
Definition at line 61 of file NormalRenderer.hpp.
Referenced by NormalRenderer().
_normalShader_model
sibr::GLParameter sibr::NormalRenderer::_normalShader_model private
Model matrix uniform.
Definition at line 59 of file NormalRenderer.hpp.
Referenced by NormalRenderer(), and render().
_normalShader_proj
sibr::GLParameter sibr::NormalRenderer::_normalShader_proj private
Projection matrix uniform.
Definition at line 57 of file NormalRenderer.hpp.
Referenced by NormalRenderer(), and render().
_normalShader_projInv
sibr::GLParameter sibr::NormalRenderer::_normalShader_projInv private
Inverse projection matrix uniform.
Definition at line 60 of file NormalRenderer.hpp.
Referenced by NormalRenderer(), and render().
_normalShader_view
sibr::GLParameter sibr::NormalRenderer::_normalShader_view private
View matrix uniform.
Definition at line 58 of file NormalRenderer.hpp.
Referenced by NormalRenderer(), and render().
_useFloats
bool sibr::NormalRenderer::_useFloats private
Should the normals be rendered to a 32F precision target.
Definition at line 63 of file NormalRenderer.hpp.
Referenced by NormalRenderer(), render(), and setWH().
The documentation for this class was generated from the following files:
src/core/renderer/NormalRenderer.hpp
src/core/renderer/NormalRenderer.cpp