SIBR: sibr::Transform3< T > Class Template Reference
sibr::Transform3< T > Class Template Reference
sibr_system
Represent a 3D transformation composed of a rotation and translation.
#include <Transform3.hpp>
Public Types
typedef Eigen::Matrix< T, 3, 1, Eigen::DontAlign > Vector3
typedef Eigen::Quaternion< T > Quaternion
Public Member Functions
Transform3 (void)
Constructor: identity transform.
void set (const Vector3 &translation, const Quaternion &rotation)
Set the transformation parameters.
void translate (float x, float y, float z)
Apply a translation.
void translate (float x, float y, float z, const Transform3 &ref)
Apply a translation that is itself rotated by another transformation.
void translate (const Vector3 &v)
Apply a translation.
void translate (const Vector3 &v, const Transform3 &ref)
Apply a translation that is itself rotated by another transformation.
void position (float x, float y, float z)
Set the position.
void position (const Vector3 &v)
Set the position.
const Vector3 & position (void) const
void rotate (const Quaternion &rotation)
Apply a rotation.
void rotate (float x, float y, float z)
Apply a rotation using Euler angles.
void rotate (float x, float y, float z, const Transform3 &ref)
Apply a rotation using Euler angles and composite with an additional transformation.
void rotate (const Vector3 &v)
Apply a rotation using Euler angles.
void rotate (const Vector3 &v, const Transform3 &ref)
Apply a rotation using Euler angles and composite with an additional transformation.
void rotation (float x, float y, float z)
Set the rotation from Euler angles.
void rotation (const Vector3 &v)
Set the rotation from Euler angles.
void rotation (const Quaternion &q)
Set the rotation.
const Quaternion & rotation (void) const
Matrix4f matrix (void) const
Matrix4f invMatrix (void) const
bool operator== (const Transform3 &other) const
Equality operator with a 1e-3 tolerance.
bool operator!= (const Transform3 &other) const
Difference operator.
Static Public Member Functions
static Transform3< T > interpolate (const Transform3< T > &from, const Transform3< T > &to, float dist01)
Interpolate between two transformations.
static Transform3< T > extrapolate (const Transform3< T > &previous, const Transform3< T > &current, float dist01)
Linearly extrapolate based on two transformations, by reapplying the delta between the two transformations to the current one and interpolating between the current and the new estimate.
static Transform3< T > computeFinal (const Transform3< T > &parentTr, const Transform3< T > &childTr)
Compute a trnasformation made by compsoiting a parent and child transformations.
Private Attributes
Vector3 _position
Quaternion _rotation
Detailed Description
template<typename T>
class sibr::Transform3< T >
Represent a 3D transformation composed of a rotation and translation.
Definition at line 17 of file Transform3.hpp.
Member Typedef Documentation
Quaternion
template<typename T > typedef Eigen::Quaternion<T> sibr::Transform3< T >::Quaternion
Definition at line 21 of file Transform3.hpp.
Vector3
template<typename T > typedef Eigen::Matrix<T,3, 1, Eigen::DontAlign> sibr::Transform3< T >::Vector3
Definition at line 20 of file Transform3.hpp.
Constructor & Destructor Documentation
Transform3()
template<typename T > sibr::Transform3< T >::Transform3 (void) inline
Constructor: identity transform.
Definition at line 26 of file Transform3.hpp.
Member Function Documentation
computeFinal()
template<typename T > static Transform3<T> sibr::Transform3< T >::computeFinal (const Transform3< T > & parentTr, const Transform3< T > & childTr) inline static
Compute a trnasformation made by compsoiting a parent and child transformations.
Parameters
parentTr the parent
childTr the child
Returns
the composite transformation
Definition at line 189 of file Transform3.hpp.
extrapolate()
template<typename T > static Transform3<T> sibr::Transform3< T >::extrapolate (const Transform3< T > & previous, const Transform3< T > & current, float dist01) inline static
Linearly extrapolate based on two transformations, by reapplying the delta between the two transformations to the current one and interpolating between the current and the new estimate.
Parameters
previous source transformation
current current transformation
dist01 extrapolation factor
Returns
the extrapolated transformation
Note
dist01 should still be in 0,1
Definition at line 173 of file Transform3.hpp.
interpolate()
template<typename T > static Transform3<T> sibr::Transform3< T >::interpolate (const Transform3< T > & from, const Transform3< T > & to, float dist01) inline static
Interpolate between two transformations.
Parameters
from source transformation
to destination transformation
dist01 interpolation factor
Returns
the interpolated transformation
Definition at line 156 of file Transform3.hpp.
Referenced by sibr::Transform3< float >::extrapolate().
invMatrix()
template<typename T > Matrix4f sibr::Transform3< T >::invMatrix (void) const
Returns
the inverse of the transformation matrix
Definition at line 347 of file Transform3.hpp.
matrix()
template<typename T > Matrix4f sibr::Transform3< T >::matrix (void) const
Returns
the transformation matrix
Definition at line 340 of file Transform3.hpp.
References sibr::matFromQuat(), and sibr::matFromTranslation().
operator!=()
template<typename T > bool sibr::Transform3< T >::operator!= (const Transform3< T > & other) const inline
Difference operator.
Parameters
other transformation to test difference with
Returns
true if other is different
Definition at line 209 of file Transform3.hpp.
operator==()
template<typename T > bool sibr::Transform3< T >::operator== (const Transform3< T > & other) const inline
Equality operator with a 1e-3 tolerance.
Parameters
other transformation to test equality with
Returns
true if other is equal
Definition at line 200 of file Transform3.hpp.
position() [1/3]
template<typename T > void sibr::Transform3< T >::position (const Vector3 & v)
Set the position.
Parameters
v position
Definition at line 286 of file Transform3.hpp.
position() [2/3]
template<typename T > void sibr::Transform3< T >::position (float x, float y, float z)
Set the position.
Parameters
x x position
y y position
z z position
Definition at line 281 of file Transform3.hpp.
Referenced by sibr::Transform3< float >::computeFinal(), sibr::Transform3< float >::extrapolate(), sibr::Transform3< float >::interpolate(), sibr::operator<<(), sibr::operator>>(), sibr::Camera::position(), and sibr::InputCamera::writeToFile().
position() [3/3]
template<typename T > const Transform3< T >::Vector3 & sibr::Transform3< T >::position (void) const
Returns
the position
Definition at line 291 of file Transform3.hpp.
rotate() [1/5]
template<typename T > void sibr::Transform3< T >::rotate (const Quaternion & rotation)
Apply a rotation.
Parameters
rotation quaternion rotation
Definition at line 297 of file Transform3.hpp.
Referenced by sibr::Transform3< float >::extrapolate(), sibr::MaterialMesh::loadMtsXML(), and sibr::Camera::rotate().
rotate() [2/5]
template<typename T > void sibr::Transform3< T >::rotate (const Vector3 & v)
Apply a rotation using Euler angles.
Parameters
v angles
Todo:
Clarify the angles order.
See also
quatFromEulerAngles
Definition at line 310 of file Transform3.hpp.
rotate() [3/5]
template<typename T > void sibr::Transform3< T >::rotate (const Vector3 & v, const Transform3< T > & ref)
Apply a rotation using Euler angles and composite with an additional transformation.
Parameters
v angles
ref additional rotation
Todo:
Clarify the angles order.
See also
quatFromEulerAngles
Definition at line 315 of file Transform3.hpp.
rotate() [4/5]
template<typename T > void sibr::Transform3< T >::rotate (float x, float y, float z)
Apply a rotation using Euler angles.
Parameters
x yaw
y pitch
z roll
Todo:
Clarify the angles order.
See also
quatFromEulerAngles
Definition at line 303 of file Transform3.hpp.
References sibr::quatFromEulerAngles().
rotate() [5/5]
template<typename T > void sibr::Transform3< T >::rotate (float x, float y, float z, const Transform3< T > & ref)
Apply a rotation using Euler angles and composite with an additional transformation.
Parameters
x yaw
y pitch
z roll
ref additional rotation
Todo:
Clarify the angles order.
See also
quatFromEulerAngles
Definition at line 354 of file Transform3.hpp.
References sibr::quatFromEulerAngles(), and sibr::Transform3< T >::rotation().
rotation() [1/4]
template<typename T > void sibr::Transform3< T >::rotation (const Quaternion & q)
Set the rotation.
Parameters
q quaternion rotation
Definition at line 330 of file Transform3.hpp.
rotation() [2/4]
template<typename T > void sibr::Transform3< T >::rotation (const Vector3 & v)
Set the rotation from Euler angles.
Parameters
v angles
Todo:
Clarify the angles order.
See also
quatFromEulerAngles
Definition at line 325 of file Transform3.hpp.
rotation() [3/4]
template<typename T > void sibr::Transform3< T >::rotation (float x, float y, float z)
Set the rotation from Euler angles.
Parameters
x yaw
y pitch
z roll
Todo:
Clarify the angles order.
See also
quatFromEulerAngles
Definition at line 320 of file Transform3.hpp.
References sibr::quatFromEulerAngles().
Referenced by sibr::Transform3< float >::computeFinal(), sibr::Transform3< float >::extrapolate(), sibr::Transform3< float >::interpolate(), sibr::operator<<(), sibr::operator>>(), sibr::Transform3< T >::rotate(), sibr::Camera::rotation(), sibr::InputCamera::toBundleString(), sibr::Transform3< T >::translate(), and sibr::InputCamera::writeToFile().
rotation() [4/4]
template<typename T > const Transform3< T >::Quaternion & sibr::Transform3< T >::rotation (void) const
Returns
the rotation
Definition at line 335 of file Transform3.hpp.
Referenced by sibr::Transform3< float >::set().
set()
template<typename T > void sibr::Transform3< T >::set (const Vector3 & translation, const Quaternion & rotation) inline
Set the transformation parameters.
Parameters
translation the translation vector
rotation the rotation quaternion
Definition at line 34 of file Transform3.hpp.
Referenced by sibr::Camera::set(), and sibr::Camera::setLookAt().
translate() [1/4]
template<typename T > void sibr::Transform3< T >::translate (const Vector3 & v)
Apply a translation.
Parameters
v translation vector
Definition at line 271 of file Transform3.hpp.
translate() [2/4]
template<typename T > void sibr::Transform3< T >::translate (const Vector3 & v, const Transform3< T > & ref)
Apply a translation that is itself rotated by another transformation.
Parameters
v translation vector
ref additional rotation trnasofrmation to apply to the translation vector.
Definition at line 276 of file Transform3.hpp.
References sibr::Transform3< T >::rotation().
translate() [3/4]
template<typename T > void sibr::Transform3< T >::translate (float x, float y, float z)
Apply a translation.
Parameters
x x shift
y y shift
z z shift
Definition at line 260 of file Transform3.hpp.
Referenced by sibr::Transform3< float >::extrapolate(), and sibr::Camera::translate().
translate() [4/4]
template<typename T > void sibr::Transform3< T >::translate (float x, float y, float z, const Transform3< T > & ref)
Apply a translation that is itself rotated by another transformation.
Parameters
x x shift
y y shift
z z shift
ref additional rotation trnasofrmation to apply to the translation vector.
Definition at line 265 of file Transform3.hpp.
Member Data Documentation
_position
template<typename T > Vector3 sibr::Transform3< T >::_position private
Definition at line 214 of file Transform3.hpp.
Referenced by sibr::Transform3< float >::operator==(), and sibr::Transform3< float >::set().
_rotation
template<typename T > Quaternion sibr::Transform3< T >::_rotation private
Definition at line 215 of file Transform3.hpp.
Referenced by sibr::Transform3< float >::operator==(), sibr::Transform3< float >::set(), and sibr::Transform3< float >::Transform3().
The documentation for this class was generated from the following file:
src/core/system/Transform3.hpp