SIBR: sibr::MeshShadingShader Class Reference
sibr::MeshShadingShader Class Reference
sibr_view
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
#include <MultiMeshManager.hpp>
Public Member Functions
void initShader (const std::string &name, const std::string &vert, const std::string &frag, const std::string &geom="") override
Initialize the shader.
virtual void setUniforms (const Camera &eye, const MeshData &data) override
Public Member Functions inherited from sibr::ShaderAlphaMVP
virtual void render (const Camera &eye, const MeshData &data)
Render using the passed information.
Protected Attributes
GLuniform< Vector3f > light_position
Light position for shading.
GLuniform< bool > phong_shading
GLuniform< bool > use_mesh_color
Should the mesh be shaded, which color should be used.
Protected Attributes inherited from sibr::ColorMeshShader
GLuniform< Vector3f > user_color
user-defined constant color.
Protected Attributes inherited from sibr::ShaderAlphaMVP
GLShader shader
Base shader object.
GLuniform< Matrix4f > mvp
MVP matrix.
GLuniform< float > alpha = 1.0
Opacity.
Detailed Description
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
Adds shading parameters.
See also
ShaderAlphaMVP
Definition at line 109 of file MultiMeshManager.hpp.
Member Function Documentation
initShader()
void sibr::MeshShadingShader::initShader (const std::string & name, const std::string & vert, const std::string & frag, const std::string & geom = "") override virtual
Initialize the shader.
Parameters
name the shader name
vert the vertex shader content
frag the fragment shader ocntent
geom the geometry shader content
Reimplemented from sibr::ColorMeshShader.
Definition at line 281 of file MultiMeshManager.cpp.
References sibr::GLuniform< T >::init(), sibr::ColorMeshShader::initShader(), light_position, phong_shading, sibr::ShaderAlphaMVP::shader, and use_mesh_color.
Referenced by sibr::MultiMeshManager::initShaders().
setUniforms()
void sibr::MeshShadingShader::setUniforms (const Camera & eye, const MeshData & data) override virtual
Reimplemented from sibr::ColorMeshShader.
Definition at line 289 of file MultiMeshManager.cpp.
References sibr::MeshData::colorMode, light_position, phong_shading, sibr::MeshData::phongShading, sibr::Camera::position(), sibr::GLuniform< T >::set(), sibr::ColorMeshShader::setUniforms(), and use_mesh_color.
Member Data Documentation
light_position
GLuniform<Vector3f> sibr::MeshShadingShader::light_position protected
Light position for shading.
Definition at line 126 of file MultiMeshManager.hpp.
Referenced by initShader(), and setUniforms().
phong_shading
GLuniform<bool> sibr::MeshShadingShader::phong_shading protected
Definition at line 127 of file MultiMeshManager.hpp.
Referenced by initShader(), and setUniforms().
use_mesh_color
GLuniform<bool> sibr::MeshShadingShader::use_mesh_color protected
Should the mesh be shaded, which color should be used.
Definition at line 127 of file MultiMeshManager.hpp.
Referenced by initShader(), and setUniforms().
The documentation for this class was generated from the following files:
src/core/view/MultiMeshManager.hpp
src/core/view/MultiMeshManager.cpp