SIBR: sibr::MeshViewer Class Reference
sibr::MeshViewer Class Reference
sibr_view
#include <MeshViewer.h>
Public Member Functions
MeshViewer ()
MeshViewer (const sibr::Vector2i &screenRes, const sibr::Mesh &mesh=sibr::Mesh(), bool launchRenderingLoop=false)
virtual void setMainMesh (const sibr::Mesh &mesh, sibr::Mesh::RenderMode mode=sibr::Mesh::FillRenderMode, bool updateCam=true, bool setupRaycaster=true)
virtual void setMainMesh (sibr::Window &win, const sibr::Mesh &mesh, sibr::Mesh::RenderMode mode=sibr::Mesh::FillRenderMode, bool updateCam=true, bool setupRaycaster=true)
virtual void render (const sibr::Viewport &viewport, const sibr::Camera &eye)
virtual void render (const sibr::Viewport &viewport)
virtual void render (const sibr::Camera &eye)
virtual void render ()
virtual void renderLoop (sibr::Window &window)
void renderLoop (std::shared_ptr< sibr::Window > window)
void renderLoop (const std::function< void(MeshViewer *)> &f=[](MeshViewer *m){}, bool customRendering=false, bool doReset=true)
virtual void reset ()
Static Public Member Functions
static void demo ()
Public Attributes
sibr::Input input
sibr::FPSCounter fpsCounter
std::shared_ptr< sibr::Window > window
std::shared_ptr< MeshRenderer > renderer
std::shared_ptr< sibr::InteractiveCameraHandler > interactCam
std::shared_ptr< sibr::Raycaster > raycaster
bool inChargeOfWindow
Private Member Functions
SIBR_CLASS_PTR (MeshViewer)
Detailed Description
Definition at line 101 of file MeshViewer.h.
Constructor & Destructor Documentation
MeshViewer() [1/2]
sibr::MeshViewer::MeshViewer ()
Definition at line 274 of file MeshViewer.cpp.
MeshViewer() [2/2]
sibr::MeshViewer::MeshViewer (const sibr::Vector2i & screenRes, const sibr::Mesh & mesh = sibr::Mesh(), bool launchRenderingLoop = false)
Definition at line 284 of file MeshViewer.cpp.
Member Function Documentation
demo()
void sibr::MeshViewer::demo () static
Definition at line 450 of file MeshViewer.cpp.
References sibr::Mesh::getTestCube(), renderer, and renderLoop().
render() [1/4]
void sibr::MeshViewer::render () virtual
Definition at line 335 of file MeshViewer.cpp.
render() [2/4]
void sibr::MeshViewer::render (const sibr::Camera & eye) virtual
Definition at line 381 of file MeshViewer.cpp.
render() [3/4]
void sibr::MeshViewer::render (const sibr::Viewport & viewport) virtual
Definition at line 376 of file MeshViewer.cpp.
render() [4/4]
void sibr::MeshViewer::render (const sibr::Viewport & viewport, const sibr::Camera & eye) virtual
Definition at line 367 of file MeshViewer.cpp.
References sibr::Viewport::bind(), and sibr::Viewport::clear().
Referenced by sibr::MultiViewInterface::displayMesh().
renderLoop() [1/3]
void sibr::MeshViewer::renderLoop (const std::function< void(MeshViewer *)> & f = [](MeshViewer* m){}, bool customRendering = false, bool doReset = true)
Definition at line 413 of file MeshViewer.cpp.
References sibr::Key::Escape, sibr::Input::global(), and sibr::Input::poll().
renderLoop() [2/3]
void sibr::MeshViewer::renderLoop (sibr::Window & window) virtual
Definition at line 343 of file MeshViewer.cpp.
References sibr::Viewport::bind(), sibr::Viewport::clear(), sibr::Key::Escape, sibr::Input::global(), sibr::Window::isOpened(), sibr::Input::poll(), sibr::Window::swapBuffer(), and sibr::Window::viewport().
Referenced by demo().
renderLoop() [3/3]
void sibr::MeshViewer::renderLoop (std::shared_ptr< sibr::Window > window)
Definition at line 389 of file MeshViewer.cpp.
References sibr::Key::Escape, sibr::Input::global(), sibr::Window::isOpened(), and sibr::Input::poll().
reset()
void sibr::MeshViewer::reset (void) virtual
Definition at line 439 of file MeshViewer.cpp.
setMainMesh() [1/2]
void sibr::MeshViewer::setMainMesh (const sibr::Mesh & mesh, sibr::Mesh::RenderMode mode = sibr::Mesh::FillRenderMode, bool updateCam = true, bool setupRaycaster = true) virtual
Definition at line 300 of file MeshViewer.cpp.
Referenced by sibr::MultiViewInterface::displayLoop(), and sibr::MultiViewInterface::updateMeshView().
setMainMesh() [2/2]
void sibr::MeshViewer::setMainMesh (sibr::Window & win, const sibr::Mesh & mesh, sibr::Mesh::RenderMode mode = sibr::Mesh::FillRenderMode, bool updateCam = true, bool setupRaycaster = true) virtual
Definition at line 305 of file MeshViewer.cpp.
References sibr::Mesh::hasNormals(), sibr::Mesh::normals(), sibr::Mesh::triangles(), sibr::Mesh::vertices(), and sibr::Window::viewport().
SIBR_CLASS_PTR()
sibr::MeshViewer::SIBR_CLASS_PTR (MeshViewer) private
Member Data Documentation
fpsCounter
sibr::FPSCounter sibr::MeshViewer::fpsCounter
Definition at line 146 of file MeshViewer.h.
inChargeOfWindow
bool sibr::MeshViewer::inChargeOfWindow
Definition at line 152 of file MeshViewer.h.
input
sibr::Input sibr::MeshViewer::input
Definition at line 145 of file MeshViewer.h.
interactCam
std::shared_ptr<sibr::InteractiveCameraHandler> sibr::MeshViewer::interactCam
Definition at line 149 of file MeshViewer.h.
Referenced by sibr::MultiViewInterface::updateMeshView().
raycaster
std::shared_ptr<sibr::Raycaster> sibr::MeshViewer::raycaster
Definition at line 150 of file MeshViewer.h.
renderer
std::shared_ptr<MeshRenderer> sibr::MeshViewer::renderer
Definition at line 148 of file MeshViewer.h.
Referenced by demo().
window
std::shared_ptr<sibr::Window> sibr::MeshViewer::window
Definition at line 147 of file MeshViewer.h.
The documentation for this class was generated from the following files:
src/core/view/interface/MeshViewer.h
src/core/view/interface/MeshViewer.cpp