SIBR: sibr::ULRV3Renderer Class Reference
sibr::ULRV3Renderer Class Reference
Perform per-pixel Unstructured Lumigraph Rendering (Buehler et al., 2001).
#include <ULRV3Renderer.hpp>
Classes
struct CameraUBOInfos
Camera infos data structure shared between the CPU and GPU.
Public Member Functions
ULRV3Renderer (const std::vector< InputCamera::Ptr > &cameras, const uint w, const uint h, const std::string &fShader="ulr/ulr_v3", const std::string &vShader="ulr/ulr_v3", const bool facecull=true)
Constructor.
virtual void setupShaders (const std::string &fShader="ulr/ulr_v3", const std::string &vShader="ulr/ulr_v3")
Change the shaders used by the ULR renderer.
virtual void process (const sibr::Mesh &mesh, const sibr::Camera &eye, IRenderTarget &dst, const sibr::Texture2DArrayRGB::Ptr &inputRGBs, const sibr::Texture2DArrayLum32F::Ptr &inputDepths, bool passthroughDepth=false)
Performs ULR rendering to a given destination rendertarget.
virtual void process (const sibr::Mesh &mesh, const sibr::Camera &eye, IRenderTarget &dst, uint inputRGBHandle, const sibr::Texture2DArrayLum32F::Ptr &inputDepths, bool passthroughDepth=false)
Performs ULR rendering to a given destination rendertarget.
void updateCameras (const std::vector< uint > &camIds)
Update which cameras should be used for rendering, based on the indices passed.
float & epsilonOcclusion ()
Set the epsilon occlusion threshold.
bool & useMasks ()
Enable or disable the masks.
bool & flipRGBs ()
Flip the RGB images before using them.
bool & occTest ()
Enable or diable occlusion testing.
bool & showWeights ()
Show debug weights.
bool & winnerTakesAll ()
Set winner takes all weights strategy.
bool & gammaCorrection ()
Apply gamma correction to the output.
bool & backfaceCull ()
Apply backface culling to the mesh.
void resize (const unsigned int w, const unsigned int h)
Resize the internal rendertargets.
bool & clearDst ()
Should the final RT be cleared or not.
uint depthHandle () const
virtual void renderProxyDepth (const sibr::Mesh &mesh, const sibr::Camera &eye)
Render the world positions of the proxy points in an intermediate rendertarget.
virtual void renderBlending (const sibr::Camera &eye, IRenderTarget &dst, uint inputRGBHandle, const sibr::Texture2DArrayLum32F::Ptr &inputDepths, bool passthroughDepth)
Perform ULR blending.
Public Member Functions inherited from sibr::RenderMaskHolderArray
void setMasks (const MaskArrayPtr &masks)
Update the masks.
const MaskArrayPtr & getMasks (void) const
void loadMasks (const sibr::BasicIBRScene::Ptr &ibrScene, const std::string &maskDir="", const std::string &preFileName="masks", const std::string &postFileName="", int w=-1, int h=-1)
Load masks from black and white images on disk.
Protected Attributes
std::string fragString
Shader names.
std::string vertexString
sibr::GLShader _ulrShader
sibr::GLShader _depthShader
sibr::RenderTargetRGBA32F::Ptr _depthRT
GLuniform< Matrix4f > _nCamProj
GLuniform< Vector3f > _nCamPos
GLuniform< bool > _occTest = true
GLuniform< bool > _useMasks = false
GLuniform< bool > _discardBlackPixels = true
GLuniform< bool > _areMasksBinary = true
GLuniform< bool > _invertMasks = false
GLuniform< bool > _flipRGBs = false
GLuniform< bool > _showWeights = false
GLuniform< bool > _winnerTakesAll = false
GLuniform< bool > _gammaCorrection = false
size_t _maxNumCams = 0
GLuniform< int > _camsCount = 0
GLuniform< float > _epsilonOcclusion = 0.01f
bool _backFaceCulling = true
bool _clearDst = true
std::vector< CameraUBOInfos > _cameraInfos
GLuint _uboIndex
Protected Attributes inherited from sibr::RenderMaskHolderArray
MaskArrayPtr _masks
The masks texture array.
Private Member Functions
SIBR_CLASS_PTR (ULRV3Renderer)
Detailed Description
Perform per-pixel Unstructured Lumigraph Rendering (Buehler et al., 2001).
No selection is done on the CPU side. Relies on texture arrays and uniform buffer objects to support a high number of cameras.
Definition at line 18 of file ULRV3Renderer.hpp.
Constructor & Destructor Documentation
ULRV3Renderer()
sibr::ULRV3Renderer::ULRV3Renderer (const std::vector< InputCamera::Ptr > & cameras, const uint w, const uint h, const std::string & fShader = "ulr/ulr_v3", const std::string & vShader = "ulr/ulr_v3", const bool facecull = true)
Constructor.
Parameters
cameras The input cameras to use.
w The width of the internal rendertargets.
h The height of the internal rendertargets.
fShader An optional name of the fragment shader to use (default to ulr_v3).
vShader An optional name of the vertex shader to use (default to ulr_v3).
facecull Should the mesh be renderer with backface culling.
Definition at line 5 of file ULRV3Renderer.cpp.
References _backFaceCulling, _cameraInfos, _camsCount, _depthRT, _maxNumCams, _uboIndex, CHECK_GL_ERROR, fragString, setupShaders(), and vertexString.
Member Function Documentation
backfaceCull()
bool& sibr::ULRV3Renderer::backfaceCull () inline
Apply backface culling to the mesh.
Definition at line 114 of file ULRV3Renderer.hpp.
clearDst()
bool& sibr::ULRV3Renderer::clearDst () inline
Should the final RT be cleared or not.
Definition at line 123 of file ULRV3Renderer.hpp.
depthHandle()
uint sibr::ULRV3Renderer::depthHandle () const inline
Returns
The ID of the first pass position map texture.
Definition at line 126 of file ULRV3Renderer.hpp.
epsilonOcclusion()
float& sibr::ULRV3Renderer::epsilonOcclusion () inline
Set the epsilon occlusion threshold.
Definition at line 93 of file ULRV3Renderer.hpp.
flipRGBs()
bool& sibr::ULRV3Renderer::flipRGBs () inline
Flip the RGB images before using them.
Definition at line 99 of file ULRV3Renderer.hpp.
gammaCorrection()
bool& sibr::ULRV3Renderer::gammaCorrection () inline
Apply gamma correction to the output.
Definition at line 111 of file ULRV3Renderer.hpp.
occTest()
bool& sibr::ULRV3Renderer::occTest () inline
Enable or diable occlusion testing.
Definition at line 102 of file ULRV3Renderer.hpp.
process() [1/2]
void sibr::ULRV3Renderer::process (const sibr::Mesh & mesh, const sibr::Camera & eye, IRenderTarget & dst, const sibr::Texture2DArrayRGB::Ptr & inputRGBs, const sibr::Texture2DArrayLum32F::Ptr & inputDepths, bool passthroughDepth = false) virtual
Performs ULR rendering to a given destination rendertarget.
Parameters
mesh The mesh to use as geometric proxy.
eye The novel viewpoint.
dst The destination rendertarget.
inputRGBs A texture array containing the input RGB images.
inputDepths A texture array containing the input depth maps.
passthroughDepth If true, depth from the position map will be output to the depth buffer for ulterior passes.
Definition at line 83 of file ULRV3Renderer.cpp.
References ibr_preprocess_rc_to_sibr::dst.
process() [2/2]
void sibr::ULRV3Renderer::process (const sibr::Mesh & mesh, const sibr::Camera & eye, IRenderTarget & dst, uint inputRGBHandle, const sibr::Texture2DArrayLum32F::Ptr & inputDepths, bool passthroughDepth = false) virtual
Performs ULR rendering to a given destination rendertarget.
Parameters
mesh The mesh to use as geometric proxy.
eye The novel viewpoint.
dst The destination rendertarget.
inputRGBHandle The handle of a texture array containing the input RGB images.
inputDepths A texture array containing the input depth maps.
passthroughDepth If true, depth from the position map will be output to the depth buffer for ulterior passes.
Definition at line 95 of file ULRV3Renderer.cpp.
References ibr_preprocess_rc_to_sibr::dst.
renderBlending()
void sibr::ULRV3Renderer::renderBlending (const sibr::Camera & eye, IRenderTarget & dst, uint inputRGBHandle, const sibr::Texture2DArrayLum32F::Ptr & inputDepths, bool passthroughDepth) virtual
Perform ULR blending.
Parameters
eye The novel viewpoint.
dst The destination rendertarget.
inputRGBHandle The handle to a texture array containing the input RGB images.
inputDepths A texture array containing the input depth maps.
passthroughDepth If true, depth from the position map will be output to the depth buffer for ulterior passes.
Definition at line 144 of file ULRV3Renderer.cpp.
References ibr_preprocess_rc_to_sibr::dst, sibr::Camera::position(), and sibr::RenderUtility::renderScreenQuad().
renderProxyDepth()
void sibr::ULRV3Renderer::renderProxyDepth (const sibr::Mesh & mesh, const sibr::Camera & eye) virtual
Render the world positions of the proxy points in an intermediate rendertarget.
Parameters
mesh the proxy mesh.
eye The novel viewpoint.
Definition at line 125 of file ULRV3Renderer.cpp.
References sibr::Mesh::render(), and sibr::Camera::viewproj().
resize()
void sibr::ULRV3Renderer::resize (const unsigned int w, const unsigned int h)
Resize the internal rendertargets.
Parameters
w the new width
h the new height
Definition at line 209 of file ULRV3Renderer.cpp.
setupShaders()
void sibr::ULRV3Renderer::setupShaders (const std::string & fShader = "ulr/ulr_v3", const std::string & vShader = "ulr/ulr_v3") virtual
Change the shaders used by the ULR renderer.
Parameters
fShader The name of the fragment shader to use.
vShader The name of the vertex shader to use.
Definition at line 50 of file ULRV3Renderer.cpp.
References CHECK_GL_ERROR, sibr::getShadersDirectory(), and sibr::loadFile().
Referenced by ULRV3Renderer().
showWeights()
bool& sibr::ULRV3Renderer::showWeights () inline
Show debug weights.
Definition at line 105 of file ULRV3Renderer.hpp.
SIBR_CLASS_PTR()
sibr::ULRV3Renderer::SIBR_CLASS_PTR (ULRV3Renderer) private
updateCameras()
void sibr::ULRV3Renderer::updateCameras (const std::vector< uint > & camIds)
Update which cameras should be used for rendering, based on the indices passed.
Parameters
camIds The indices to enable.
Definition at line 109 of file ULRV3Renderer.cpp.
useMasks()
bool& sibr::ULRV3Renderer::useMasks (void) inline
Enable or disable the masks.
Definition at line 96 of file ULRV3Renderer.hpp.
winnerTakesAll()
bool& sibr::ULRV3Renderer::winnerTakesAll () inline
Set winner takes all weights strategy.
Definition at line 108 of file ULRV3Renderer.hpp.
Member Data Documentation
_areMasksBinary
GLuniform<bool> sibr::ULRV3Renderer::_areMasksBinary = true protected
Definition at line 167 of file ULRV3Renderer.hpp.
_backFaceCulling
bool sibr::ULRV3Renderer::_backFaceCulling = true protected
Definition at line 178 of file ULRV3Renderer.hpp.
Referenced by ULRV3Renderer().
_cameraInfos
std::vector<CameraUBOInfos> sibr::ULRV3Renderer::_cameraInfos protected
Definition at line 191 of file ULRV3Renderer.hpp.
Referenced by ULRV3Renderer().
_camsCount
GLuniform<int> sibr::ULRV3Renderer::_camsCount = 0 protected
Definition at line 175 of file ULRV3Renderer.hpp.
Referenced by ULRV3Renderer().
_clearDst
bool sibr::ULRV3Renderer::_clearDst = true protected
Definition at line 179 of file ULRV3Renderer.hpp.
_depthRT
sibr::RenderTargetRGBA32F::Ptr sibr::ULRV3Renderer::_depthRT protected
Definition at line 159 of file ULRV3Renderer.hpp.
Referenced by ULRV3Renderer().
_depthShader
sibr::GLShader sibr::ULRV3Renderer::_depthShader protected
Definition at line 157 of file ULRV3Renderer.hpp.
_discardBlackPixels
GLuniform<bool> sibr::ULRV3Renderer::_discardBlackPixels = true protected
Definition at line 166 of file ULRV3Renderer.hpp.
_epsilonOcclusion
GLuniform<float> sibr::ULRV3Renderer::_epsilonOcclusion = 0.01f protected
Definition at line 177 of file ULRV3Renderer.hpp.
_flipRGBs
GLuniform<bool> sibr::ULRV3Renderer::_flipRGBs = false protected
Definition at line 169 of file ULRV3Renderer.hpp.
_gammaCorrection
GLuniform<bool> sibr::ULRV3Renderer::_gammaCorrection = false protected
Definition at line 172 of file ULRV3Renderer.hpp.
_invertMasks
GLuniform<bool> sibr::ULRV3Renderer::_invertMasks = false protected
Definition at line 168 of file ULRV3Renderer.hpp.
_maxNumCams
size_t sibr::ULRV3Renderer::_maxNumCams = 0 protected
Definition at line 174 of file ULRV3Renderer.hpp.
Referenced by ULRV3Renderer().
_nCamPos
GLuniform<Vector3f> sibr::ULRV3Renderer::_nCamPos protected
Definition at line 161 of file ULRV3Renderer.hpp.
_nCamProj
GLuniform<Matrix4f> sibr::ULRV3Renderer::_nCamProj protected
Definition at line 160 of file ULRV3Renderer.hpp.
_occTest
GLuniform<bool> sibr::ULRV3Renderer::_occTest = true protected
Definition at line 164 of file ULRV3Renderer.hpp.
_showWeights
GLuniform<bool> sibr::ULRV3Renderer::_showWeights = false protected
Definition at line 170 of file ULRV3Renderer.hpp.
_uboIndex
GLuint sibr::ULRV3Renderer::_uboIndex protected
Definition at line 192 of file ULRV3Renderer.hpp.
Referenced by ULRV3Renderer().
_ulrShader
sibr::GLShader sibr::ULRV3Renderer::_ulrShader protected
Definition at line 156 of file ULRV3Renderer.hpp.
_useMasks
GLuniform<bool> sibr::ULRV3Renderer::_useMasks = false protected
Definition at line 165 of file ULRV3Renderer.hpp.
_winnerTakesAll
GLuniform<bool> sibr::ULRV3Renderer::_winnerTakesAll = false protected
Definition at line 171 of file ULRV3Renderer.hpp.
fragString
std::string sibr::ULRV3Renderer::fragString protected
Shader names.
Definition at line 154 of file ULRV3Renderer.hpp.
Referenced by ULRV3Renderer().
vertexString
std::string sibr::ULRV3Renderer::vertexString protected
Definition at line 154 of file ULRV3Renderer.hpp.
Referenced by ULRV3Renderer().
The documentation for this class was generated from the following files:
src/projects/ulr/renderer/ULRV3Renderer.hpp
src/projects/ulr/renderer/ULRV3Renderer.cpp