SIBR: sibr::Array2d< T > Class Template Reference
sibr::Array2d< T > Class Template Reference
sibr_system
Used to store custom data on a map using pixel position (2d unsigned pos).
#include <Array2d.hpp>
Public Types
typedef std::vector< T >::const_reference const_reference
typedef std::vector< T >::reference reference
Public Member Functions
Array2d (uint width=0, uint height=0)
Build from the given size.
Array2d (uint width, uint height, const_reference defaultValue)
Build from the given size and using the given default value.
~Array2d ()
Destructor.
uint width (void) const
Return the width of this Array2d.
uint height (void) const
Return the height of this Array2d.
uint w (void) const
Return the width of this Array2d.
uint h (void) const
Return the height of this Array2d.
bool empty (void) const
Return TRUE if is empty.
const_reference operator() (uint x, uint y) const
Return data about a pixel at given coordinates.
reference operator() (uint x, uint y)
Access data about a pixel at given coordinates.
const_reference operator() (const sibr::Vector2i &coords) const
Return data about a pixel at given coordinates.
reference operator() (const sibr::Vector2i &coords)
Access data about a pixel at given coordinates.
const_reference operator[] (size_t i) const
Return data about a pixel at given index.
reference operator[] (size_t i)
Access data about a pixel at given index.
size_t size (void) const
Return the total size of the one dimensional array.
const std::vector< T > & operator() (void) const
Return data accessible in a one array form.
std::vector< T > & operator() (void)
const std::vector< T > & vector (void) const
Return the internally used std::vector (so you can use STL algos).
std::vector< T > & vector (void)
void * data (void) const
Return a pointer to the first byte a stored data.
void * data (void)
uint index (uint x, uint y) const
Return the element index for the given coordinates.
bool inRange (uint x, uint y) const
Return FALSE if x,y are out of range. (DON'T print error)
bool isInRange (uint x, uint y) const
Protected Member Functions
bool checkSizeFor (uint x, uint y) const
Return FALSE if x,y are out of range. (print error)
Protected Attributes
uint _width
Width of the pixel map.
uint _height
Height of the pixel map.
std::vector< T > _data
data of the pixel map
Detailed Description
template<typename T>
class sibr::Array2d< T >
Used to store custom data on a map using pixel position (2d unsigned pos).
Internally, this simply use a one dimensional std::vector. This class abstract convert operation from 2d to 1d for making code easy to read.
Definition at line 20 of file Array2d.hpp.
Member Typedef Documentation
const_reference
template<typename T > typedef std::vector<T>::const_reference sibr::Array2d< T >::const_reference
Definition at line 27 of file Array2d.hpp.
reference
template<typename T > typedef std::vector<T>::reference sibr::Array2d< T >::reference
Definition at line 28 of file Array2d.hpp.
Constructor & Destructor Documentation
Array2d() [1/2]
template<typename T > sibr::Array2d< T >::Array2d (uint width = 0, uint height = 0)
Build from the given size.
Note you can't resize your Array2d (just create a new one if you need).
Definition at line 110 of file Array2d.hpp.
Array2d() [2/2]
template<typename T > sibr::Array2d< T >::Array2d (uint width, uint height, const_reference defaultValue)
Build from the given size and using the given default value.
Note you can't resize your Array2d (just create a new one if you need).
Definition at line 115 of file Array2d.hpp.
~Array2d()
template<typename T > sibr::Array2d< T >::~Array2d
Destructor.
Definition at line 120 of file Array2d.hpp.
Member Function Documentation
checkSizeFor()
template<typename T > bool sibr::Array2d< T >::checkSizeFor (uint x, uint y) const protected
Return FALSE if x,y are out of range. (print error)
Definition at line 232 of file Array2d.hpp.
References SIBR_ERR.
data() [1/2]
template<typename T > void * sibr::Array2d< T >::data (void)
Definition at line 190 of file Array2d.hpp.
data() [2/2]
template<typename T > void * sibr::Array2d< T >::data (void) const
Return a pointer to the first byte a stored data.
Definition at line 186 of file Array2d.hpp.
empty()
template<typename T > bool sibr::Array2d< T >::empty (void) const
Return TRUE if is empty.
Definition at line 195 of file Array2d.hpp.
h()
template<typename T > uint sibr::Array2d< T >::h (void) const
Return the height of this Array2d.
Definition at line 141 of file Array2d.hpp.
height()
template<typename T > uint sibr::Array2d< T >::height (void) const
Return the height of this Array2d.
Definition at line 131 of file Array2d.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
index()
template<typename T > uint sibr::Array2d< T >::index (uint x, uint y) const inline
Return the element index for the given coordinates.
Definition at line 217 of file Array2d.hpp.
inRange()
template<typename T > bool sibr::Array2d< T >::inRange (uint x, uint y) const inline
Return FALSE if x,y are out of range. (DON'T print error)
Definition at line 222 of file Array2d.hpp.
isInRange()
template<typename T > bool sibr::Array2d< T >::isInRange (uint x, uint y) const inline
Definition at line 227 of file Array2d.hpp.
operator()() [1/6]
template<typename T > Array2d< T >::reference sibr::Array2d< T >::operator() (const sibr::Vector2i & coords)
Access data about a pixel at given coordinates.
Definition at line 162 of file Array2d.hpp.
operator()() [2/6]
template<typename T > Array2d< T >::const_reference sibr::Array2d< T >::operator() (const sibr::Vector2i & coords) const
Return data about a pixel at given coordinates.
Definition at line 158 of file Array2d.hpp.
operator()() [3/6]
template<typename T > Array2d< T >::reference sibr::Array2d< T >::operator() (uint x, uint y)
Access data about a pixel at given coordinates.
Definition at line 152 of file Array2d.hpp.
operator()() [4/6]
template<typename T > Array2d< T >::const_reference sibr::Array2d< T >::operator() (uint x, uint y) const
Return data about a pixel at given coordinates.
Definition at line 147 of file Array2d.hpp.
operator()() [5/6]
template<typename T > std::vector< T > & sibr::Array2d< T >::operator() (void)
Definition at line 171 of file Array2d.hpp.
operator()() [6/6]
template<typename T > const std::vector< T > & sibr::Array2d< T >::operator() (void) const
Return data accessible in a one array form.
Deprecated:
Use Array2d<T>::vector(void) instead.
Definition at line 167 of file Array2d.hpp.
operator[]() [1/2]
template<typename T > Array2d< T >::reference sibr::Array2d< T >::operator[] (size_t i)
Access data about a pixel at given index.
Definition at line 206 of file Array2d.hpp.
operator[]() [2/2]
template<typename T > Array2d< T >::const_reference sibr::Array2d< T >::operator[] (size_t i) const
Return data about a pixel at given index.
Definition at line 201 of file Array2d.hpp.
size()
template<typename T > size_t sibr::Array2d< T >::size (void) const
Return the total size of the one dimensional array.
Definition at line 211 of file Array2d.hpp.
vector() [1/2]
template<typename T > std::vector< T > & sibr::Array2d< T >::vector (void)
Definition at line 181 of file Array2d.hpp.
vector() [2/2]
template<typename T > const std::vector< T > & sibr::Array2d< T >::vector (void) const
Return the internally used std::vector (so you can use STL algos).
Definition at line 177 of file Array2d.hpp.
w()
template<typename T > uint sibr::Array2d< T >::w (void) const
Return the width of this Array2d.
Definition at line 136 of file Array2d.hpp.
width()
template<typename T > uint sibr::Array2d< T >::width (void) const
Return the width of this Array2d.
Definition at line 126 of file Array2d.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
Member Data Documentation
_data
template<typename T > std::vector<T> sibr::Array2d< T >::_data protected
data of the pixel map
Definition at line 103 of file Array2d.hpp.
_height
template<typename T > uint sibr::Array2d< T >::_height protected
Height of the pixel map.
Definition at line 102 of file Array2d.hpp.
_width
template<typename T > uint sibr::Array2d< T >::_width protected
Width of the pixel map.
Definition at line 101 of file Array2d.hpp.
The documentation for this class was generated from the following file:
src/core/system/Array2d.hpp