SIBR: sibr::BlurRenderer Class Reference
sibr::BlurRenderer Class Reference
sibr_renderer
Blur on color edges present in a texture.
#include <BlurRenderer.hpp>
Public Types
typedef std::shared_ptr< BlurRenderer > Ptr
Public Member Functions
BlurRenderer (void)
Constructor.
void process (uint textureID, const Vector2f &textureSize, IRenderTarget &dst)
Process the texture.
Private Attributes
GLShader _shader
Blur shader.
GLParameter _paramImgSize
Texture size uniform.
Detailed Description
Blur on color edges present in a texture.
Definition at line 13 of file BlurRenderer.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<BlurRenderer> sibr::BlurRenderer::Ptr
Definition at line 16 of file BlurRenderer.hpp.
Constructor & Destructor Documentation
BlurRenderer()
sibr::BlurRenderer::BlurRenderer (void)
Constructor.
Definition at line 5 of file BlurRenderer.cpp.
References _paramImgSize, _shader, sibr::getShadersDirectory(), sibr::GLParameter::init(), sibr::GLShader::init(), and sibr::loadFile().
Member Function Documentation
process()
void sibr::BlurRenderer::process (uint textureID, const Vector2f & textureSize, IRenderTarget & dst)
Process the texture.
Parameters
textureID the texture to blur
textureSize the texture dimensions
dst the destination rendertarget
Definition at line 13 of file BlurRenderer.cpp.
References _paramImgSize, _shader, sibr::GLShader::begin(), ibr_preprocess_rc_to_sibr::dst, sibr::GLShader::end(), sibr::RenderUtility::renderScreenQuad(), and sibr::GLParameter::set().
Member Data Documentation
_paramImgSize
GLParameter sibr::BlurRenderer::_paramImgSize private
Texture size uniform.
Definition at line 36 of file BlurRenderer.hpp.
Referenced by BlurRenderer(), and process().
_shader
GLShader sibr::BlurRenderer::_shader private
Blur shader.
Definition at line 35 of file BlurRenderer.hpp.
Referenced by BlurRenderer(), and process().
The documentation for this class was generated from the following files:
src/core/renderer/BlurRenderer.hpp
src/core/renderer/BlurRenderer.cpp