SIBR: sibr::GridMapping Class Reference
sibr::GridMapping Class Reference
#include <ImagesGrid.hpp>
Protected Member Functions
MVpixel pixFromScreenPos (const Vector2i &pos, const Vector2f &size)
Vector2f uvFromMVpixel (const MVpixel &pix, bool use_center=false)
void updateZoomBox (const Input &input, const sibr::Viewport &vp)
void updateZoomScroll (const Input &input)
void updateCenter (const Input &input, const Vector2f &size)
void updateDrag (const Input &input, const Vector2f &size)
void displayZoom (const sibr::Viewport &viewport, DrawUtilities &utils)
void highlightPixel (const MVpixel &pix, const sibr::Viewport &viewport, const sibr::Vector3f &color={ 0, 1, 0 }, const sibr::Vector2f &minPixSize={ 10.0f, 10.0f })
void highlightImage (int im, const sibr::Viewport &viewport, const sibr::Vector3f &color={ 0, 1, 0 }, float alpha=0)
void setupGrid (const Viewport &vp)
Protected Attributes
DrawUtilities draw_utils
Viewport _vp
QuadData viewRectangle
QuadSelectionData zoomSelection
DragClickData drag
int num_per_row = 4
Vector2f grid_adjusted
Vector2f imSizePixels
int num_imgs
Detailed Description
Definition at line 89 of file ImagesGrid.hpp.
Member Function Documentation
displayZoom()
void sibr::GridMapping::displayZoom (const sibr::Viewport & viewport, DrawUtilities & utils) protected
Definition at line 582 of file ImagesGrid.cpp.
References _vp, sibr::Viewport::finalSize(), sibr::QuadSelectionData::first, sibr::DrawUtilities::rectangle(), sibr::QuadSelectionData::second, and zoomSelection.
Referenced by sibr::ImagesGrid::onRender().
highlightImage()
void sibr::GridMapping::highlightImage (int im, const sibr::Viewport & viewport, const sibr::Vector3f & color = { 0, 1, 0 }, float alpha = 0) protected
Definition at line 609 of file ImagesGrid.cpp.
References draw_utils, imSizePixels, sibr::DrawUtilities::rectangle(), and uvFromMVpixel().
Referenced by sibr::ImagesGrid::onRender().
highlightPixel()
void sibr::GridMapping::highlightPixel (const MVpixel & pix, const sibr::Viewport & viewport, const sibr::Vector3f & color = { 0, 1, 0 }, const sibr::Vector2f & minPixSize = { 10.0f, 10.0f }) protected
Definition at line 593 of file ImagesGrid.cpp.
References sibr::Viewport::bind(), draw_utils, sibr::Viewport::finalSize(), sibr::MVpixel::im, sibr::MVpixel::pos, sibr::DrawUtilities::rectangle(), sibr::DrawUtilities::rectanglePixels(), and uvFromMVpixel().
Referenced by sibr::ImagesGrid::onRender().
pixFromScreenPos()
MVpixel sibr::GridMapping::pixFromScreenPos (const Vector2i & pos, const Vector2f & size) protected
Definition at line 461 of file ImagesGrid.cpp.
References sibr::QuadData::diagonal, sibr::frac(), grid_adjusted, imSizePixels, num_imgs, num_per_row, sibr::QuadData::tl(), and viewRectangle.
Referenced by sibr::ImagesGrid::onUpdate().
setupGrid()
void sibr::GridMapping::setupGrid (const Viewport & vp) protected
Definition at line 617 of file ImagesGrid.cpp.
References sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), grid_adjusted, imSizePixels, and num_per_row.
Referenced by sibr::ImagesGrid::onUpdate().
updateCenter()
void sibr::GridMapping::updateCenter (const Input & input, const Vector2f & size) protected
Definition at line 563 of file ImagesGrid.cpp.
updateDrag()
void sibr::GridMapping::updateDrag (const Input & input, const Vector2f & size) protected
Definition at line 567 of file ImagesGrid.cpp.
References sibr::QuadData::center, sibr::DragClickData::center, sibr::QuadData::diagonal, drag, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::DragClickData::isActive, sibr::InputState< TNbState, TEnum >::isPressed(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Mouse::Left, sibr::Input::mouseButton(), sibr::Input::mousePosition(), sibr::DragClickData::position, and viewRectangle.
Referenced by sibr::ImagesGrid::onUpdate().
updateZoomBox()
void sibr::GridMapping::updateZoomBox (const Input & input, const sibr::Viewport & vp) protected
Definition at line 497 of file ImagesGrid.cpp.
References sibr::QuadData::br(), sibr::QuadData::center, sibr::clamp(), sibr::QuadData::diagonal, sibr::Viewport::finalBottom(), sibr::Viewport::finalHeight(), sibr::Viewport::finalRight(), sibr::Viewport::finalSize(), sibr::Viewport::finalWidth(), sibr::QuadSelectionData::first, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::QuadSelectionData::isActive, sibr::Input::isInsideViewport(), sibr::InputState< TNbState, TEnum >::isPressed(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Input::key(), sibr::Key::LeftControl, sibr::Input::mouseButton(), sibr::Input::mousePosition(), sibr::Key::Q, sibr::Key::Right, sibr::QuadSelectionData::second, sibr::QuadData::tl(), viewRectangle, and zoomSelection.
Referenced by sibr::ImagesGrid::onUpdate().
updateZoomScroll()
void sibr::GridMapping::updateZoomScroll (const Input & input) protected
Definition at line 551 of file ImagesGrid.cpp.
References sibr::QuadData::diagonal, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Input::key(), sibr::Key::LeftControl, sibr::Input::mouseScroll(), and viewRectangle.
Referenced by sibr::ImagesGrid::onUpdate().
uvFromMVpixel()
Vector2f sibr::GridMapping::uvFromMVpixel (const MVpixel & pix, bool use_center = false) protected
Definition at line 488 of file ImagesGrid.cpp.
References sibr::QuadData::diagonal, grid_adjusted, sibr::MVpixel::im, imSizePixels, num_per_row, sibr::MVpixel::pos, sibr::QuadData::tl(), and viewRectangle.
Referenced by highlightImage(), and highlightPixel().
Member Data Documentation
_vp
Viewport sibr::GridMapping::_vp protected
Definition at line 109 of file ImagesGrid.hpp.
Referenced by displayZoom(), and sibr::ImagesGrid::onUpdate().
drag
DragClickData sibr::GridMapping::drag protected
Definition at line 112 of file ImagesGrid.hpp.
Referenced by updateDrag().
draw_utils
DrawUtilities sibr::GridMapping::draw_utils protected
Definition at line 108 of file ImagesGrid.hpp.
Referenced by highlightImage(), highlightPixel(), and sibr::ImagesGrid::onRender().
grid_adjusted
Vector2f sibr::GridMapping::grid_adjusted protected
Definition at line 115 of file ImagesGrid.hpp.
Referenced by sibr::ImagesGrid::onRender(), pixFromScreenPos(), setupGrid(), and uvFromMVpixel().
imSizePixels
Vector2f sibr::GridMapping::imSizePixels protected
Definition at line 117 of file ImagesGrid.hpp.
Referenced by highlightImage(), sibr::ImagesGrid::onUpdate(), pixFromScreenPos(), setupGrid(), and uvFromMVpixel().
num_imgs
int sibr::GridMapping::num_imgs protected
Definition at line 118 of file ImagesGrid.hpp.
Referenced by sibr::ImagesGrid::onRender(), sibr::ImagesGrid::onUpdate(), sibr::ImagesGrid::optionsGUI(), and pixFromScreenPos().
num_per_row
int sibr::GridMapping::num_per_row = 4 protected
Definition at line 114 of file ImagesGrid.hpp.
Referenced by sibr::ImagesGrid::optionsGUI(), pixFromScreenPos(), setupGrid(), and uvFromMVpixel().
viewRectangle
QuadData sibr::GridMapping::viewRectangle protected
Definition at line 110 of file ImagesGrid.hpp.
Referenced by sibr::ImagesGrid::onRender(), sibr::ImagesGrid::optionsGUI(), pixFromScreenPos(), updateDrag(), updateZoomBox(), updateZoomScroll(), and uvFromMVpixel().
zoomSelection
QuadSelectionData sibr::GridMapping::zoomSelection protected
Definition at line 111 of file ImagesGrid.hpp.
Referenced by displayZoom(), and updateZoomBox().
The documentation for this class was generated from the following files:
src/core/view/ImagesGrid.hpp
src/core/view/ImagesGrid.cpp