SIBR: sibr::Intersector2D Class Reference
sibr::Intersector2D Class Reference
sibr_raycaster
This class provides utilities to compute point/line/triangle/quad intersections.
#include <Intersector2D.h>
Public Member Functions
Intersector2D (void)=delete
Constructor.
~Intersector2D (void)=delete
Destructor.
Static Public Member Functions
static float sign (sibr::Vector2f p1, sibr::Vector2f p2, sibr::Vector2f p3)
Having defined a straight line in the 2D plane, this method can be used to know in which half-space (defined by the line) a point lies.
static bool PointInTriangle (sibr::Vector2f pt, sibr::Vector2f v1, sibr::Vector2f v2, sibr::Vector2f v3)
Tests if a point falls inside a triangle, in 2D space.
static bool LineLineIntersect (sibr::Vector2f a, sibr::Vector2f b, sibr::Vector2f c, sibr::Vector2f d)
Tests if a line intersects another line, in 2D space.
static bool TriTriIntersect (sibr::Vector2f t0_0, sibr::Vector2f t0_1, sibr::Vector2f t0_2, sibr::Vector2f t1_0, sibr::Vector2f t1_1, sibr::Vector2f t1_2)
Tests if two triangles overlap, in 2D space.
static bool QuadQuadIntersect (sibr::Vector2f q0_0, sibr::Vector2f q0_1, sibr::Vector2f q0_2, sibr::Vector2f q0_3, sibr::Vector2f q1_0, sibr::Vector2f q1_1, sibr::Vector2f q1_2, sibr::Vector2f q1_3)
Tests if two quads overlap, in 2D space.
static std::vector< std::vector< bool > > frustrumQuadsIntersect (std::vector< quad > &quads, const std::vector< InputCamera::Ptr > &cams)
Perform multiple quads/camera frusta intersections at once.
Detailed Description
This class provides utilities to compute point/line/triangle/quad intersections.
Definition at line 53 of file Intersector2D.h.
Constructor & Destructor Documentation
Intersector2D()
sibr::Intersector2D::Intersector2D (void) delete
Constructor.
~Intersector2D()
sibr::Intersector2D::~Intersector2D (void) delete
Destructor.
Member Function Documentation
frustrumQuadsIntersect()
std::vector< std::vector< bool > > sibr::Intersector2D::frustrumQuadsIntersect (std::vector< quad > & quads, const std::vector< InputCamera::Ptr > & cams) static
Perform multiple quads/camera frusta intersections at once.
Warning
Requires an existing and current OpenGL context.
Parameters
quads an array of quads to test against each camera frustum.
cams an array of cameras against which frusta the intersections tests should be performed.
Returns
a double-array of booleans denoting, for each camera, for each quad, if the quad intersects the frustum volume.
Definition at line 103 of file Intersector2D.cpp.
References sibr::GLShader::begin(), sibr::RenderTarget< T_Type, T_NumComp >::bind(), sibr::GLShader::end(), sibr::InputCamera::h(), sibr::RenderTarget< T_Type, T_NumComp >::h(), sibr::GLParameter::init(), sibr::GLShader::init(), quad::q1, quad::q2, quad::q3, quad::q4, sibr::RenderTarget< T_Type, T_NumComp >::readBack(), sibr::Mesh::render(), sibr::GLParameter::set(), sibr::Mesh::triangles(), sibr::Mesh::vertices(), sibr::Camera::viewproj(), sibr::InputCamera::w(), and sibr::RenderTarget< T_Type, T_NumComp >::w().
LineLineIntersect()
bool sibr::Intersector2D::LineLineIntersect (sibr::Vector2f a, sibr::Vector2f b, sibr::Vector2f c, sibr::Vector2f d) static
Tests if a line intersects another line, in 2D space.
Parameters
a first point on the first line.
b second point on the first line.
c first point on the second line.
d second point on the second line.
Returns
a boolean denoting if the lines intersects.
Definition at line 26 of file Intersector2D.cpp.
Referenced by TriTriIntersect().
PointInTriangle()
bool sibr::Intersector2D::PointInTriangle (sibr::Vector2f pt, sibr::Vector2f v1, sibr::Vector2f v2, sibr::Vector2f v3) static
Tests if a point falls inside a triangle, in 2D space.
Parameters
pt the point to test.
v1 first triangle vertex.
v2 second triangle vertex.
v3 third triangle vertex.
Returns
a boolean denoting if the point belong to the triangle or not.
Definition at line 14 of file Intersector2D.cpp.
References sign().
Referenced by TriTriIntersect().
QuadQuadIntersect()
bool sibr::Intersector2D::QuadQuadIntersect (sibr::Vector2f q0_0, sibr::Vector2f q0_1, sibr::Vector2f q0_2, sibr::Vector2f q0_3, sibr::Vector2f q1_0, sibr::Vector2f q1_1, sibr::Vector2f q1_2, sibr::Vector2f q1_3) static
Tests if two quads overlap, in 2D space.
Parameters
q0_0 first vertex of the first quad.
q0_1 second vertex of the first quad.
q0_2 third vertex of the first quad.
q0_3 fourth vertex of the first quad.
q1_0 first vertex of the second quad.
q1_1 second vertex of the second quad.
q1_2 third vertex of the second quad.
q1_3 fourth vertex of the second quad.
Returns
a boolean denoting if the quads overlap.
Definition at line 76 of file Intersector2D.cpp.
References TriTriIntersect().
sign()
float sibr::Intersector2D::sign (sibr::Vector2f p1, sibr::Vector2f p2, sibr::Vector2f p3) static
Having defined a straight line in the 2D plane, this method can be used to know in which half-space (defined by the line) a point lies.
Parameters
p1 the 2D point to locate wrt to the line.
p2 a 2D point on the line.
p3 another 2D point on the line.
Returns
a signed value indicating on which side of the line the point is.
Definition at line 9 of file Intersector2D.cpp.
Referenced by PointInTriangle().
TriTriIntersect()
bool sibr::Intersector2D::TriTriIntersect (sibr::Vector2f t0_0, sibr::Vector2f t0_1, sibr::Vector2f t0_2, sibr::Vector2f t1_0, sibr::Vector2f t1_1, sibr::Vector2f t1_2) static
Tests if two triangles overlap, in 2D space.
Parameters
t0_0 first vertex of the first triangle.
t0_1 second vertex of the first triangle.
t0_2 third vertex of the first triangle.
t1_0 first vertex of the second triangle.
t1_1 second vertex of the second triangle.
t1_2 third vertex of the second triangle.
Returns
a boolean denoting if the triangles overlap.
Definition at line 47 of file Intersector2D.cpp.
References LineLineIntersect(), and PointInTriangle().
Referenced by QuadQuadIntersect().
The documentation for this class was generated from the following files:
src/core/raycaster/Intersector2D.h
src/core/raycaster/Intersector2D.cpp