SIBR: sibr::BinaryMeshRenderer Class Reference
sibr::BinaryMeshRenderer Class Reference
sibr_renderer
Render a binary mask of a mesh, with options to limit Z-fighting.
#include <BinaryMeshRenderer.hpp>
Public Member Functions
BinaryMeshRenderer ()
Constructor.
void process (const Mesh &mesh, const Camera &eye, IRenderTarget &dst)
Render the mesh mask.
float & getEpsilon ()
Shift that can be used to modify the depth written, to avoid Z-fighting when rendering multiple masks of the same mesh or combining masks.
Private Member Functions
SIBR_CLASS_PTR (BinaryMeshRenderer)
Private Attributes
GLShader _shader
Mask shader.
GLuniform< sibr::Matrix4f > _paramMVP
MVP uniform.
GLuniform< float > epsilon = 0
Epsilon uniform.
Detailed Description
Render a binary mask of a mesh, with options to limit Z-fighting.
Definition at line 15 of file BinaryMeshRenderer.hpp.
Constructor & Destructor Documentation
BinaryMeshRenderer()
sibr::BinaryMeshRenderer::BinaryMeshRenderer ()
Constructor.
Definition at line 5 of file BinaryMeshRenderer.cpp.
References _paramMVP, _shader, epsilon, sibr::GLuniform< T >::init(), sibr::GLShader::init(), main(), and SIBR_SHADER.
Member Function Documentation
getEpsilon()
float& sibr::BinaryMeshRenderer::getEpsilon () inline
Shift that can be used to modify the depth written, to avoid Z-fighting when rendering multiple masks of the same mesh or combining masks.
If set to 0.0: no shift, if set to 1.0: all vertices sent to depth 0.0.
Returns
a reference to the shift
Definition at line 38 of file BinaryMeshRenderer.hpp.
process()
void sibr::BinaryMeshRenderer::process (const Mesh & mesh, const Camera & eye, IRenderTarget & dst)
Render the mesh mask.
Regions covered by the mesh will be filled with (1,1,1,1).
Parameters
mesh the mesh to render
eye the viewpoint to use
dst the destination rendertarget
Definition at line 30 of file BinaryMeshRenderer.cpp.
References _paramMVP, _shader, sibr::GLShader::begin(), ibr_preprocess_rc_to_sibr::dst, sibr::GLShader::end(), epsilon, sibr::Mesh::render(), sibr::GLuniform< T >::send(), sibr::GLuniform< T >::set(), and sibr::Camera::viewproj().
SIBR_CLASS_PTR()
sibr::BinaryMeshRenderer::SIBR_CLASS_PTR (BinaryMeshRenderer) private
Member Data Documentation
_paramMVP
GLuniform<sibr::Matrix4f> sibr::BinaryMeshRenderer::_paramMVP private
MVP uniform.
Definition at line 45 of file BinaryMeshRenderer.hpp.
Referenced by BinaryMeshRenderer(), and process().
_shader
GLShader sibr::BinaryMeshRenderer::_shader private
Mask shader.
Definition at line 44 of file BinaryMeshRenderer.hpp.
Referenced by BinaryMeshRenderer(), and process().
epsilon
GLuniform<float> sibr::BinaryMeshRenderer::epsilon = 0 private
Epsilon uniform.
Definition at line 46 of file BinaryMeshRenderer.hpp.
Referenced by BinaryMeshRenderer(), and process().
The documentation for this class was generated from the following files:
src/core/renderer/BinaryMeshRenderer.hpp
src/core/renderer/BinaryMeshRenderer.cpp