SIBR: sibr::TextureCubeMap< T_Type, T_NumComp > Class Template Reference
sibr::TextureCubeMap< T_Type, T_NumComp > Class Template Reference
sibr_graphics
Represent a cubemap composed of 6 2D faces on the GPU, with custom format and type.
#include <Texture.hpp>
Public Types
typedef Image< T_Type, T_NumComp > PixelImage
typedef PixelImage::Pixel PixelFormat
typedef RenderTarget< T_Type, T_NumComp > PixelRT
typedef std::shared_ptr< TextureCubeMap< T_Type, T_NumComp > > Ptr
typedef std::unique_ptr< TextureCubeMap< T_Type, T_NumComp > > UPtr
Public Types inherited from sibr::ITextureCubeMap
typedef std::shared_ptr< ITextureCubeMap > Ptr
typedef std::unique_ptr< ITextureCubeMap > UPtr
Public Member Functions
TextureCubeMap (void)
Constructor.
TextureCubeMap (const uint w, const uint h, uint flags=0)
Constructor.
TextureCubeMap (const PixelImage &xpos, const PixelImage &xneg, const PixelImage &ypos, const PixelImage &yneg, const PixelImage &zpos, const PixelImage &zneg, uint flags=0)
Create a cubemap from 6 images.
void createFromImages (const PixelImage &xpos, const PixelImage &xneg, const PixelImage &ypos, const PixelImage &yneg, const PixelImage &zpos, const PixelImage &zneg, uint flags=0)
Create the texture from 6 images.
~TextureCubeMap (void)
Destructor.
GLuint handle (void) const
uint w (void) const
uint h (void) const
Public Member Functions inherited from sibr::ITextureCubeMap
virtual ~ITextureCubeMap (void)
Destructor.
Private Member Functions
SIBR_DISALLOW_COPY (TextureCubeMap)
void createCubeMap ()
Create the cubemap texture object.
void sendCubeMap (const PixelImage &xpos, const PixelImage &xneg, const PixelImage &ypos, const PixelImage &yneg, const PixelImage &zpos, const PixelImage &zneg)
Upload cubemap data.
Private Attributes
GLuint m_Handle = 0
Texture handle.
uint m_W = 0
Texture width.
uint m_H = 0
Texture height.
uint m_Flags = 0
Options.
Detailed Description
template<typename T_Type, unsigned int T_NumComp>
class sibr::TextureCubeMap< T_Type, T_NumComp >
Represent a cubemap composed of 6 2D faces on the GPU, with custom format and type.
See also
ITextureCubeMap
Definition at line 435 of file Texture.hpp.
Member Typedef Documentation
PixelFormat
template<typename T_Type , unsigned int T_NumComp> typedef PixelImage::Pixel sibr::TextureCubeMap< T_Type, T_NumComp >::PixelFormat
Definition at line 440 of file Texture.hpp.
PixelImage
template<typename T_Type , unsigned int T_NumComp> typedef Image<T_Type, T_NumComp> sibr::TextureCubeMap< T_Type, T_NumComp >::PixelImage
Definition at line 439 of file Texture.hpp.
PixelRT
template<typename T_Type , unsigned int T_NumComp> typedef RenderTarget<T_Type, T_NumComp> sibr::TextureCubeMap< T_Type, T_NumComp >::PixelRT
Definition at line 441 of file Texture.hpp.
Ptr
template<typename T_Type , unsigned int T_NumComp> typedef std::shared_ptr<TextureCubeMap<T_Type, T_NumComp> > sibr::TextureCubeMap< T_Type, T_NumComp >::Ptr
Definition at line 442 of file Texture.hpp.
UPtr
template<typename T_Type , unsigned int T_NumComp> typedef std::unique_ptr<TextureCubeMap<T_Type, T_NumComp> > sibr::TextureCubeMap< T_Type, T_NumComp >::UPtr
Definition at line 443 of file Texture.hpp.
Constructor & Destructor Documentation
TextureCubeMap() [1/3]
template<typename T_Type , unsigned int T_NumComp> sibr::TextureCubeMap< T_Type, T_NumComp >::TextureCubeMap (void)
Constructor.
Definition at line 1340 of file Texture.hpp.
TextureCubeMap() [2/3]
template<typename T_Type , unsigned int T_NumComp> sibr::TextureCubeMap< T_Type, T_NumComp >::TextureCubeMap (const uint w, const uint h, uint flags = 0)
Constructor.
Parameters
w width
h height
flags options
Definition at line 1343 of file Texture.hpp.
TextureCubeMap() [3/3]
template<typename T_Type , unsigned int T_NumComp> sibr::TextureCubeMap< T_Type, T_NumComp >::TextureCubeMap (const PixelImage & xpos, const PixelImage & xneg, const PixelImage & ypos, const PixelImage & yneg, const PixelImage & zpos, const PixelImage & zneg, uint flags = 0)
Create a cubemap from 6 images.
Parameters
xpos positive X face
xneg negative X face
ypos positive Y face
yneg negative Y face
zpos positive Z face
zneg negative Z face
flags options
Definition at line 1351 of file Texture.hpp.
~TextureCubeMap()
template<typename T_Type , unsigned int T_NumComp> sibr::TextureCubeMap< T_Type, T_NumComp >::~TextureCubeMap (void)
Destructor.
Definition at line 1488 of file Texture.hpp.
References CHECK_GL_ERROR.
Member Function Documentation
createCubeMap()
template<typename T_Type , unsigned int T_NumComp> void sibr::TextureCubeMap< T_Type, T_NumComp >::createCubeMap private
Create the cubemap texture object.
Definition at line 1360 of file Texture.hpp.
References CHECK_GL_ERROR, and SIBR_GPU_LINEAR_SAMPLING.
createFromImages()
template<typename T_Type , unsigned int T_NumComp> void sibr::TextureCubeMap< T_Type, T_NumComp >::createFromImages (const PixelImage & xpos, const PixelImage & xneg, const PixelImage & ypos, const PixelImage & yneg, const PixelImage & zpos, const PixelImage & zneg, uint flags = 0)
Create the texture from 6 images.
Parameters
xpos positive X face
xneg negative X face
ypos positive Y face
yneg negative Y face
zpos positive Z face
zneg negative Z face
flags options
Definition at line 1473 of file Texture.hpp.
References sibr::Image< T_Type, T_NumComp >::h(), and sibr::Image< T_Type, T_NumComp >::w().
h()
template<typename T_Type , unsigned int T_NumComp> uint sibr::TextureCubeMap< T_Type, T_NumComp >::h (void) const virtual
Returns
the texture height.
Implements sibr::ITextureCubeMap.
Definition at line 1501 of file Texture.hpp.
handle()
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::TextureCubeMap< T_Type, T_NumComp >::handle (void) const virtual
Returns
the texture handle.
Implements sibr::ITextureCubeMap.
Definition at line 1495 of file Texture.hpp.
sendCubeMap()
template<typename T_Type , unsigned int T_NumComp> void sibr::TextureCubeMap< T_Type, T_NumComp >::sendCubeMap (const PixelImage & xpos, const PixelImage & xneg, const PixelImage & ypos, const PixelImage & yneg, const PixelImage & zpos, const PixelImage & zneg) private
Upload cubemap data.
Parameters
xpos positive X face
xneg negative X face
ypos positive Y face
yneg negative Y face
zpos positive Z face
zneg negative Z face
Definition at line 1393 of file Texture.hpp.
References CHECK_GL_ERROR, sibr::Image< T_Type, T_NumComp >::clone(), sibr::Image< T_Type, T_NumComp >::data(), sibr::Image< T_Type, T_NumComp >::flipH(), sibr::Image< T_Type, T_NumComp >::h(), SIBR_FLIP_TEXTURE, SIBR_GPU_AUTOGEN_MIPMAP, SIBR_GPU_INTEGER, and sibr::Image< T_Type, T_NumComp >::w().
SIBR_DISALLOW_COPY()
template<typename T_Type , unsigned int T_NumComp> sibr::TextureCubeMap< T_Type, T_NumComp >::SIBR_DISALLOW_COPY (TextureCubeMap< T_Type, T_NumComp >) private
w()
template<typename T_Type , unsigned int T_NumComp> uint sibr::TextureCubeMap< T_Type, T_NumComp >::w (void) const virtual
Returns
the texture width.
Implements sibr::ITextureCubeMap.
Definition at line 1498 of file Texture.hpp.
Member Data Documentation
m_Flags
template<typename T_Type , unsigned int T_NumComp> uint sibr::TextureCubeMap< T_Type, T_NumComp >::m_Flags = 0 private
Options.
Definition at line 515 of file Texture.hpp.
m_H
template<typename T_Type , unsigned int T_NumComp> uint sibr::TextureCubeMap< T_Type, T_NumComp >::m_H = 0 private
Texture height.
Definition at line 514 of file Texture.hpp.
m_Handle
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::TextureCubeMap< T_Type, T_NumComp >::m_Handle = 0 private
Texture handle.
Definition at line 512 of file Texture.hpp.
m_W
template<typename T_Type , unsigned int T_NumComp> uint sibr::TextureCubeMap< T_Type, T_NumComp >::m_W = 0 private
Texture width.
Definition at line 513 of file Texture.hpp.
The documentation for this class was generated from the following file:
src/core/graphics/Texture.hpp