SIBR: sibr::RaycastingCamera Class Reference
sibr::RaycastingCamera Class Reference
sibr_raycaster
A raycasting camera is an input camera augmented with additional casting and frustum helpers.
#include <CameraRaycaster.hpp>
Public Types
using HPlane = Eigen::Hyperplane< float, 3 >
using Line3 = Eigen::ParametrizedLine< float, 3 >
Public Types inherited from sibr::InputCamera
typedef std::shared_ptr< InputCamera > Ptr
Public Types inherited from sibr::Camera
typedef Transform3< float > Transform3f
Public Member Functions
RaycastingCamera (const sibr::InputCamera &cam)
Constructor from an InputCamera.
sibr::Vector3f rayDirNotNormalized (const sibr::Vector2f &pixel) const
Compute the unormalized ray direction from the camera position to a given pixel.
sibr::Vector3f rayDir (const sibr::Vector2f &pixel) const
Compute the normalized ray direction from the camera position to a given pixel.
Ray getRay (const sibr::Vector2f &pixel) const
Generate the ray going from the camera position to a given pixel.
sibr::Vector2f rayProjection (const Line3 &line) const
Compute the (up to) two intersections of a oriented line with the camera frustum.
bool isInsideFrustum (const sibr::Vector3f &pt, float eps=0.0001) const
Check if a point is in the camera frustum.
sibr::Vector2f projectImg_outside_frustum_correction (const Vector3f &pt3d) const
Project a 3D point on the image plane, including points behind the camera (horizontal flip).
Public Member Functions inherited from sibr::InputCamera
InputCamera ()
Default constructor.
InputCamera (float f, float k1, float k2, int w, int h, int id)
Partial constructor.
InputCamera (float fy, float fx, float k1, float k2, int w, int h, int id)
InputCamera (int id, int w, int h, sibr::Vector3f &position, sibr::Matrix3f &rotation, float focal, float k1, float k2, bool active)
Constructor, initialize the input camera.
InputCamera (int id, int w, int h, sibr::Matrix4f m, bool active)
Constructor, initialize the input camera.
InputCamera (const Camera &c, int w, int h)
Constructor from a basic Camera.
InputCamera (const InputCamera &)=default
Copy constructor.
InputCamera (InputCamera &&)=default
Move constructor.
InputCamera & operator= (const InputCamera &)=default
Copy operator.
InputCamera & operator= (InputCamera &&)=default
Move operator.
uint w (void) const
Input image width.
uint h (void) const
Input image height.
bool isActive (void) const
Check if the input camera active or inactive, camera is completely ignored if set to inactive.
void setActive (bool active)
Set camera active status.
const std::string & name (void) const
void name (const std::string &s)
Set camera name.
void size (uint w, uint h)
Update image dimensions.
uint id () const
Vector3f projectScreen (const Vector3f &pt) const
Project a world space point into screen space.
float focal () const
void setFocal (float focal)
set the focal length ; to be used with caution; focal is usually inferred from the fov
float k1 () const
float k2 () const
Vector3f unprojectImgSpaceInvertY (const sibr::Vector2i &pixelPos, const float &depth) const
Back-project pixel coordinates and depth.
Vector3f projectImgSpaceInvertY (const Vector3f &point3d) const
Project 3D point using perspective projection.
bool loadFromBinary (const std::string &filename)
Load from internal binary representation.
void saveToBinary (const std::string &filename) const
Save to disk using internal binary representation.
void writeToFile (std::ostream &outfile) const
Save a file in the IBR TopView format.
void readFromFile (std::istream &infile)
Load a file in the IBR TopView format.
std::string toBundleString (bool negativeZ=false, bool recomputeFocal=true) const
Conver to Bundle string.
std::vector< sibr::Vector2i > getImageCorners () const
sibr::InputCamera resizedH (int h) const
Return a new camera resized to the specified height.
sibr::InputCamera resizedW (int w) const
Return a new camera resized to the specified height.
std::string lookatString () const
Return the lookat string of the camera.
Public Member Functions inherited from sibr::Camera
SIBR_CLASS_PTR (Camera)
Camera (void)
Default constructor.
void set (const Vector3f &translation, const Quaternionf &rotation)
Set the camera pose.
void setLookAt (const Vector3f &eye, const Vector3f &center, const Vector3f &up)
Set the camera pose based on two points and a up vector.
void translate (const Vector3f &v)
Translate the camera.
void translate (const Vector3f &v, const Transform3f &ref)
Translate the camera with respect to a reference frame.
void position (const Vector3f &v)
Set the camera position.
const Vector3f & position (void) const
void rotate (const Quaternionf &rotation)
Rotate the camera.
void rotate (const Vector3f &v)
Rotate the camera.
void rotate (const Vector3f &v, const Transform3f &ref)
Rotate the camera with respect to a reference frame.
void rotation (const Vector3f &v)
Set the camera rotation.
void rotation (const Quaternionf &q)
Set the camera rotation.
const Quaternionf & rotation (void) const
void transform (const Transform3f &t)
Set the camera transform.
const Transform3f & transform (void) const
void fovy (float value)
Set the vertical field of view (in radians).
float fovy (void) const
void aspect (float value)
Set the aspect ratio.
float aspect (void) const
void znear (float value)
Set the near plane.
float znear (void) const
void zfar (float value)
Set the far plane.
float zfar (void) const
void orthoRight (float value)
Set the right frustum extent.
float orthoRight (void) const
void orthoTop (float value)
Set the top frustum extent.
float orthoTop (void) const
bool ortho (void) const
Vector3f dir (void) const
Vector3f up (void) const
Vector3f right (void) const
Vector3f project (const Vector3f &point3d) const
Project 3D point using perspective projection.
Vector3f unproject (const Vector3f &pixel2d) const
Back-project pixel coordinates and depth.
void perspective (float fovRad, float ratio, float znear, float zfar)
Update the projection parameters of the camera.
bool frustumTest (const Vector3f &position3d) const
Check if a point falls inside the camera frustum.
bool frustumTest (const Vector3f &position3d, const Vector2f &pixel2d) const
Check if a point falls inside the camera frustum.
Matrix4f model (void) const
Matrix4f view (void) const
virtual Matrix4f proj (void) const
const Matrix4f & viewproj (void) const
const Matrix4f & invViewproj (void) const
void principalPoint (const sibr::Vector2f &p)
Set the camera principal point.
void setStereoCam (bool isLeft, float focal, float iod)
Set stereo camera projection parameters.
void setOrthoCam (float right, float top)
Set orthographic camera projection parameters.
bool needSave () const
bool needVideoSave () const
std::string savePath () const
void setSavePath (std::string savePath)
Set the save destination path for renderings.
void setDebugVideo (const bool debug)
Toggle video saving.
Public Attributes
sibr::Vector3f dx
sibr::Vector3f dy
sibr::Vector3f upLeftOffsetMinusPos
Camera raycasting parameters.
std::vector< HPlane > frustum_planes
Frustum planes: near, far, top, bottom, left, right.
Private Member Functions
SIBR_CLASS_PTR (RaycastingCamera)
Additional Inherited Members
Static Public Member Functions inherited from sibr::InputCamera
static void saveAsLookat (const std::vector< InputCamera::Ptr > &cams, const std::string &fileName)
save a vector of cameras as lookat
static void saveImageSizes (const std::vector< InputCamera::Ptr > &cams, const std::string &fileName)
save a vector of cameras sizes to a file to be read by mitsuba rendering script
static void saveAsBundle (const std::vector< InputCamera::Ptr > &cams, const std::string &fileName, bool negativeZ=false, bool exportImages=false, bool recomputeFocal=true)
Save a vector of cameras as a bundle file.
static void saveAsLookat (const std::vector< sibr::Camera > &cams, const std::string &fileName)
Save a vector of cameras as a lookat file.
static std::vector< InputCamera::Ptr > load (const std::string &datasetPath, float zNear=0.01f, float zFar=1000.0f, const std::string &bundleName="bundle.out", const std::string &listName="list_images.txt")
Load cameras from a bundler file.
static std::vector< InputCamera::Ptr > loadNVM (const std::string &nvmPath, float zNear=0.01f, float zFar=1000.0f, std::vector< sibr::Vector2u > wh=std::vector< sibr::Vector2u >())
Load cameras from a NVM file.
static std::vector< InputCamera::Ptr > loadLookat (const std::string &lookatPath, const std::vector< sibr::Vector2u > &wh=std::vector< sibr::Vector2u >(), float zNear=-1, float zFar=-1)
Load cameras from a .lookat file generated by our Blender plugin.
static std::vector< InputCamera::Ptr > loadColmap (const std::string &colmapSparsePath, const float zNear=0.01f, const float zFar=1000.0f, const int fovXfovYFlag=0)
Load cameras from a Colmap txt file.
static std::vector< InputCamera::Ptr > loadBundle (const std::string &bundlerPath, float zNear=0.01f, float zFar=1000.0f, const std::string &listImagePath="", bool path=false)
Load cameras from a bundle file.
static std::vector< InputCamera::Ptr > loadBundleFRIBR (const std::string &bundlerPath, float zNear=0.01f, float zFar=1000.0f, const std::string &listImagePath="")
Load cameras from a bundle file.
static std::vector< InputCamera::Ptr > loadMeshroom (const std::string &meshroomSFMPath, const float zNear=0.01f, const float zFar=1000.0f)
Load cameras from a Meshrrom SFM cameras.sfm txt file.
Static Public Member Functions inherited from sibr::Camera
static Camera interpolate (const Camera &from, const Camera &to, float dist01)
Interpolate between two cameras.
Protected Member Functions inherited from sibr::Camera
void forceUpdateViewProj (void) const
Trigger a viewproj matrix udpate.
Protected Attributes inherited from sibr::InputCamera
float _focal
focal length
float _k1
K1 bundler distorsion parameter.
float _k2
K2 bundler dist parameter.
uint _w
Image width.
uint _h
Image height.
uint _id
Input camera id.
std::string _name
Input image name.
bool _active
is the camera currently in use.
Protected Attributes inherited from sibr::Camera
std::string _savePath
Save destination path when reocrding images.
bool _debugVideoFrames
Is video saving enabled or not.
Matrix4f _matViewProj
View projection matrix.
Matrix4f _invMatViewProj
Inverse projection matrix.
bool _dirtyViewProj
Does the camera matrix need an update.
Transform3f _transform
The camera pose.
float _fov
The vertical field of view (radians)
float _aspect
Aspect ratio.
float _znear
Near plane.
float _zfar
Far plane.
float _right
Frustum half width.
float _top
Frustum half height.
sibr::Vector2f _p = {0.5f, 0.5}
Principal point.
bool _isOrtho
Is the camera orthographic.
Detailed Description
A raycasting camera is an input camera augmented with additional casting and frustum helpers.
Definition at line 100 of file CameraRaycaster.hpp.
Member Typedef Documentation
HPlane
using sibr::RaycastingCamera::HPlane = Eigen::Hyperplane<float, 3>
Definition at line 103 of file CameraRaycaster.hpp.
Line3
using sibr::RaycastingCamera::Line3 = Eigen::ParametrizedLine<float, 3>
Definition at line 104 of file CameraRaycaster.hpp.
Constructor & Destructor Documentation
RaycastingCamera()
sibr::RaycastingCamera::RaycastingCamera (const sibr::InputCamera & cam)
Constructor from an InputCamera.
Parameters
cam the camera
Definition at line 151 of file CameraRaycaster.cpp.
References sibr::CameraRaycaster::computePixelDerivatives(), dx, dy, frustum_planes, sibr::Camera::position(), sibr::Camera::unproject(), and upLeftOffsetMinusPos.
Member Function Documentation
getRay()
Ray sibr::RaycastingCamera::getRay (const sibr::Vector2f & pixel) const
Generate the ray going from the camera position to a given pixel.
Parameters
pixel the pixel in [0,w-1]x[0,h-1]
Returns
the ray from the camera position to the center of the input pixel.
Definition at line 192 of file CameraRaycaster.cpp.
References sibr::Camera::position(), and rayDir().
Referenced by sibr::DatasetView::onUpdate().
isInsideFrustum()
bool sibr::RaycastingCamera::isInsideFrustum (const sibr::Vector3f & pt, float eps = 0.0001) const
Check if a point is in the camera frustum.
Parameters
pt the 3D point to test
eps the tolerance threshold
Returns
true if the point is inside
Definition at line 230 of file CameraRaycaster.cpp.
References sibr::dot(), and frustum_planes.
Referenced by rayProjection().
projectImg_outside_frustum_correction()
sibr::Vector2f sibr::RaycastingCamera::projectImg_outside_frustum_correction (const Vector3f & pt3d) const
Project a 3D point on the image plane, including points behind the camera (horizontal flip).
Parameters
pt3d the 3d point
Returns
the pixel coordinates in [0,w]x(0,h]
Definition at line 240 of file CameraRaycaster.cpp.
References sibr::Camera::dir(), sibr::dot(), sibr::InputCamera::h(), sibr::Camera::position(), sibr::Camera::project(), and sibr::InputCamera::w().
rayDir()
sibr::Vector3f sibr::RaycastingCamera::rayDir (const sibr::Vector2f & pixel) const
Compute the normalized ray direction from the camera position to a given pixel.
Parameters
pixel the pixel in [0,w-1]x[0,h-1]
Returns
the ray direction from the camera position to the center of the input pixel.
Definition at line 187 of file CameraRaycaster.cpp.
References rayDirNotNormalized().
Referenced by getRay().
rayDirNotNormalized()
sibr::Vector3f sibr::RaycastingCamera::rayDirNotNormalized (const sibr::Vector2f & pixel) const
Compute the unormalized ray direction from the camera position to a given pixel.
Parameters
pixel the pixel in [0,w-1]x[0,h-1]
Returns
the ray direction from the camera position to the center of the input pixel.
Definition at line 182 of file CameraRaycaster.cpp.
References dx, dy, and upLeftOffsetMinusPos.
Referenced by rayDir().
rayProjection()
sibr::Vector2f sibr::RaycastingCamera::rayProjection (const Line3 & line) const
Compute the (up to) two intersections of a oriented line with the camera frustum.
Parameters
line the parametrized oriented line to test
Returns
the intersection parameters of the two intersection points with the frustum.
Definition at line 197 of file CameraRaycaster.cpp.
References frustum_planes, sibr::InputCamera::id(), isInsideFrustum(), and ibr_convert_old_to_new::line.
SIBR_CLASS_PTR()
sibr::RaycastingCamera::SIBR_CLASS_PTR (RaycastingCamera) private
Member Data Documentation
dx
sibr::Vector3f sibr::RaycastingCamera::dx
Definition at line 148 of file CameraRaycaster.hpp.
Referenced by RaycastingCamera(), and rayDirNotNormalized().
dy
sibr::Vector3f sibr::RaycastingCamera::dy
Definition at line 148 of file CameraRaycaster.hpp.
Referenced by RaycastingCamera(), and rayDirNotNormalized().
frustum_planes
std::vector<HPlane> sibr::RaycastingCamera::frustum_planes
Frustum planes: near, far, top, bottom, left, right.
Definition at line 150 of file CameraRaycaster.hpp.
Referenced by isInsideFrustum(), RaycastingCamera(), and rayProjection().
upLeftOffsetMinusPos
sibr::Vector3f sibr::RaycastingCamera::upLeftOffsetMinusPos
Camera raycasting parameters.
Definition at line 148 of file CameraRaycaster.hpp.
Referenced by RaycastingCamera(), and rayDirNotNormalized().
The documentation for this class was generated from the following files:
src/core/raycaster/CameraRaycaster.hpp
src/core/raycaster/CameraRaycaster.cpp