SIBR: sibr::InputCamera Class Reference
sibr::InputCamera Class Reference
sibr_assets
Input camera parameters.
#include <InputCamera.hpp>
Classes
struct Z
Near/far plane representation.
Public Types
typedef std::shared_ptr< InputCamera > Ptr
Public Types inherited from sibr::Camera
typedef Transform3< float > Transform3f
Public Member Functions
InputCamera ()
Default constructor.
InputCamera (float f, float k1, float k2, int w, int h, int id)
Partial constructor.
InputCamera (float fy, float fx, float k1, float k2, int w, int h, int id)
InputCamera (int id, int w, int h, sibr::Vector3f &position, sibr::Matrix3f &rotation, float focal, float k1, float k2, bool active)
Constructor, initialize the input camera.
InputCamera (int id, int w, int h, sibr::Matrix4f m, bool active)
Constructor, initialize the input camera.
InputCamera (const Camera &c, int w, int h)
Constructor from a basic Camera.
InputCamera (const InputCamera &)=default
Copy constructor.
InputCamera (InputCamera &&)=default
Move constructor.
InputCamera & operator= (const InputCamera &)=default
Copy operator.
InputCamera & operator= (InputCamera &&)=default
Move operator.
uint w (void) const
Input image width.
uint h (void) const
Input image height.
bool isActive (void) const
Check if the input camera active or inactive, camera is completely ignored if set to inactive.
void setActive (bool active)
Set camera active status.
const std::string & name (void) const
void name (const std::string &s)
Set camera name.
void size (uint w, uint h)
Update image dimensions.
uint id () const
Vector3f projectScreen (const Vector3f &pt) const
Project a world space point into screen space.
float focal () const
void setFocal (float focal)
set the focal length ; to be used with caution; focal is usually inferred from the fov
float k1 () const
float k2 () const
Vector3f unprojectImgSpaceInvertY (const sibr::Vector2i &pixelPos, const float &depth) const
Back-project pixel coordinates and depth.
Vector3f projectImgSpaceInvertY (const Vector3f &point3d) const
Project 3D point using perspective projection.
bool loadFromBinary (const std::string &filename)
Load from internal binary representation.
void saveToBinary (const std::string &filename) const
Save to disk using internal binary representation.
void writeToFile (std::ostream &outfile) const
Save a file in the IBR TopView format.
void readFromFile (std::istream &infile)
Load a file in the IBR TopView format.
std::string toBundleString (bool negativeZ=false, bool recomputeFocal=true) const
Conver to Bundle string.
std::vector< sibr::Vector2i > getImageCorners () const
sibr::InputCamera resizedH (int h) const
Return a new camera resized to the specified height.
sibr::InputCamera resizedW (int w) const
Return a new camera resized to the specified height.
std::string lookatString () const
Return the lookat string of the camera.
Public Member Functions inherited from sibr::Camera
SIBR_CLASS_PTR (Camera)
Camera (void)
Default constructor.
void set (const Vector3f &translation, const Quaternionf &rotation)
Set the camera pose.
void setLookAt (const Vector3f &eye, const Vector3f &center, const Vector3f &up)
Set the camera pose based on two points and a up vector.
void translate (const Vector3f &v)
Translate the camera.
void translate (const Vector3f &v, const Transform3f &ref)
Translate the camera with respect to a reference frame.
void position (const Vector3f &v)
Set the camera position.
const Vector3f & position (void) const
void rotate (const Quaternionf &rotation)
Rotate the camera.
void rotate (const Vector3f &v)
Rotate the camera.
void rotate (const Vector3f &v, const Transform3f &ref)
Rotate the camera with respect to a reference frame.
void rotation (const Vector3f &v)
Set the camera rotation.
void rotation (const Quaternionf &q)
Set the camera rotation.
const Quaternionf & rotation (void) const
void transform (const Transform3f &t)
Set the camera transform.
const Transform3f & transform (void) const
void fovy (float value)
Set the vertical field of view (in radians).
float fovy (void) const
void aspect (float value)
Set the aspect ratio.
float aspect (void) const
void znear (float value)
Set the near plane.
float znear (void) const
void zfar (float value)
Set the far plane.
float zfar (void) const
void orthoRight (float value)
Set the right frustum extent.
float orthoRight (void) const
void orthoTop (float value)
Set the top frustum extent.
float orthoTop (void) const
bool ortho (void) const
Vector3f dir (void) const
Vector3f up (void) const
Vector3f right (void) const
Vector3f project (const Vector3f &point3d) const
Project 3D point using perspective projection.
Vector3f unproject (const Vector3f &pixel2d) const
Back-project pixel coordinates and depth.
void perspective (float fovRad, float ratio, float znear, float zfar)
Update the projection parameters of the camera.
bool frustumTest (const Vector3f &position3d) const
Check if a point falls inside the camera frustum.
bool frustumTest (const Vector3f &position3d, const Vector2f &pixel2d) const
Check if a point falls inside the camera frustum.
Matrix4f model (void) const
Matrix4f view (void) const
virtual Matrix4f proj (void) const
const Matrix4f & viewproj (void) const
const Matrix4f & invViewproj (void) const
void principalPoint (const sibr::Vector2f &p)
Set the camera principal point.
void setStereoCam (bool isLeft, float focal, float iod)
Set stereo camera projection parameters.
void setOrthoCam (float right, float top)
Set orthographic camera projection parameters.
bool needSave () const
bool needVideoSave () const
std::string savePath () const
void setSavePath (std::string savePath)
Set the save destination path for renderings.
void setDebugVideo (const bool debug)
Toggle video saving.
Static Public Member Functions
static void saveAsLookat (const std::vector< InputCamera::Ptr > &cams, const std::string &fileName)
save a vector of cameras as lookat
static void saveImageSizes (const std::vector< InputCamera::Ptr > &cams, const std::string &fileName)
save a vector of cameras sizes to a file to be read by mitsuba rendering script
static void saveAsBundle (const std::vector< InputCamera::Ptr > &cams, const std::string &fileName, bool negativeZ=false, bool exportImages=false, bool recomputeFocal=true)
Save a vector of cameras as a bundle file.
static void saveAsLookat (const std::vector< sibr::Camera > &cams, const std::string &fileName)
Save a vector of cameras as a lookat file.
static std::vector< InputCamera::Ptr > load (const std::string &datasetPath, float zNear=0.01f, float zFar=1000.0f, const std::string &bundleName="bundle.out", const std::string &listName="list_images.txt")
Load cameras from a bundler file.
static std::vector< InputCamera::Ptr > loadNVM (const std::string &nvmPath, float zNear=0.01f, float zFar=1000.0f, std::vector< sibr::Vector2u > wh=std::vector< sibr::Vector2u >())
Load cameras from a NVM file.
static std::vector< InputCamera::Ptr > loadLookat (const std::string &lookatPath, const std::vector< sibr::Vector2u > &wh=std::vector< sibr::Vector2u >(), float zNear=-1, float zFar=-1)
Load cameras from a .lookat file generated by our Blender plugin.
static std::vector< InputCamera::Ptr > loadColmap (const std::string &colmapSparsePath, const float zNear=0.01f, const float zFar=1000.0f, const int fovXfovYFlag=0)
Load cameras from a Colmap txt file.
static std::vector< InputCamera::Ptr > loadBundle (const std::string &bundlerPath, float zNear=0.01f, float zFar=1000.0f, const std::string &listImagePath="", bool path=false)
Load cameras from a bundle file.
static std::vector< InputCamera::Ptr > loadBundleFRIBR (const std::string &bundlerPath, float zNear=0.01f, float zFar=1000.0f, const std::string &listImagePath="")
Load cameras from a bundle file.
static std::vector< InputCamera::Ptr > loadMeshroom (const std::string &meshroomSFMPath, const float zNear=0.01f, const float zFar=1000.0f)
Load cameras from a Meshrrom SFM cameras.sfm txt file.
Static Public Member Functions inherited from sibr::Camera
static Camera interpolate (const Camera &from, const Camera &to, float dist01)
Interpolate between two cameras.
Protected Attributes
float _focal
focal length
float _k1
K1 bundler distorsion parameter.
float _k2
K2 bundler dist parameter.
uint _w
Image width.
uint _h
Image height.
uint _id
Input camera id.
std::string _name
Input image name.
bool _active
is the camera currently in use.
Protected Attributes inherited from sibr::Camera
std::string _savePath
Save destination path when reocrding images.
bool _debugVideoFrames
Is video saving enabled or not.
Matrix4f _matViewProj
View projection matrix.
Matrix4f _invMatViewProj
Inverse projection matrix.
bool _dirtyViewProj
Does the camera matrix need an update.
Transform3f _transform
The camera pose.
float _fov
The vertical field of view (radians)
float _aspect
Aspect ratio.
float _znear
Near plane.
float _zfar
Far plane.
float _right
Frustum half width.
float _top
Frustum half height.
sibr::Vector2f _p = {0.5f, 0.5}
Principal point.
bool _isOrtho
Is the camera orthographic.
Additional Inherited Members
Protected Member Functions inherited from sibr::Camera
void forceUpdateViewProj (void) const
Trigger a viewproj matrix udpate.
Detailed Description
Input camera parameters.
Inherits all basic camera functionality from Camera and adds functions for depth samples from multi-view stereo.
See also
Camera, NovelCamera
Definition at line 15 of file InputCamera.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<InputCamera> sibr::InputCamera::Ptr
Definition at line 18 of file InputCamera.hpp.
Constructor & Destructor Documentation
InputCamera() [1/8]
sibr::InputCamera::InputCamera () inline
Default constructor.
Definition at line 38 of file InputCamera.hpp.
Referenced by loadBundle(), loadBundleFRIBR(), loadColmap(), loadLookat(), and loadNVM().
InputCamera() [2/8]
sibr::InputCamera::InputCamera (float f, float k1, float k2, int w, int h, int id)
Partial constructor.
Parameters
f focal length in mm
k1 first distortion parameter
k2 second distortion parameter
w width of input image
h height of input image
id ID of input image
Definition at line 15 of file InputCamera.cpp.
References _id, sibr::Camera::aspect(), sibr::Camera::fovy(), h(), id(), and w().
InputCamera() [3/8]
sibr::InputCamera::InputCamera (float fy, float fx, float k1, float k2, int w, int h, int id)
Definition at line 28 of file InputCamera.cpp.
References _id, sibr::Camera::aspect(), sibr::Camera::fovy(), h(), id(), and w().
InputCamera() [4/8]
sibr::InputCamera::InputCamera (int id, int w, int h, sibr::Vector3f & position, sibr::Matrix3f & rotation, float focal, float k1, float k2, bool active)
Constructor, initialize the input camera.
Parameters
id ID of input image
w width of input image
h height of input image
position camera position
rotation camera rotation
focal focal length in mm
k1 first distortion parameter
k2 second distortion parameter
active input image active or not
Definition at line 88 of file InputCamera.cpp.
References _focal, _h, _id, _k1, _k2, _name, _w, sibr::Camera::aspect(), focal(), sibr::Camera::fovy(), h(), id(), k1(), k2(), sibr::Camera::position(), sibr::Camera::rotation(), and w().
InputCamera() [5/8]
sibr::InputCamera::InputCamera (int id, int w, int h, sibr::Matrix4f m, bool active)
Constructor, initialize the input camera.
Parameters
id ID of input image
w width of input image
h height of input image
m camera parameters resad from Bundler output file
active input image active or not
fovFromFocal if true, compute fov from focal else use "standard sibr" convention
See also
Bundler: http://phototour.cs.washington.edu/bundler/
Deprecated:
Avoid using this legacy constructor.
Definition at line 42 of file InputCamera.cpp.
References _focal, _h, _id, _k1, _k2, _name, _w, sibr::Camera::aspect(), sibr::Camera::fovy(), h(), id(), sibr::Camera::position(), sibr::Camera::principalPoint(), sibr::Camera::rotation(), and w().
InputCamera() [6/8]
sibr::InputCamera::InputCamera (const Camera & c, int w, int h)
Constructor from a basic Camera.
Parameters
c camera
w image width
h image height
Definition at line 118 of file InputCamera.cpp.
References _active, _focal, _h, _id, _k1, _k2, _name, _w, sibr::Camera::aspect(), sibr::Camera::fovy(), h(), and w().
InputCamera() [7/8]
sibr::InputCamera::InputCamera (const InputCamera &) default
Copy constructor.
InputCamera() [8/8]
sibr::InputCamera::InputCamera (InputCamera &&) default
Move constructor.
Member Function Documentation
focal()
float sibr::InputCamera::focal () const
Returns
the focal length
Definition at line 146 of file InputCamera.cpp.
References _focal.
Referenced by InputCamera(), loadFromBinary(), rot90CC(), saveToBinary(), and toBundleString().
getImageCorners()
std::vector< sibr::Vector2i > sibr::InputCamera::getImageCorners () const
Returns
A vector of four Vector2i corresponding to the pixels at the camera corners
Definition at line 1204 of file InputCamera.cpp.
References _h, and _w.
Referenced by sibr::generateCamFrustum(), and sibr::generateCamQuadWithUvs().
h()
uint sibr::InputCamera::h (void) const
Input image height.
Returns
height of input image
Definition at line 133 of file InputCamera.cpp.
References _h.
Referenced by sibr::CameraRaycaster::castForEachPixel(), sibr::CameraRaycaster::computeClippingPlanes(), sibr::CameraRaycaster::computePixelDerivatives(), sibr::Intersector2D::frustrumQuadsIntersect(), InputCamera(), sibr::InteractiveCameraHandler::interpolate(), sibr::Orbit::interpolateOrbit(), legacyV2main(), loadBundle(), loadFromBinary(), loadLookat(), main(), sibr::TrackBall::mapTo3Dplane(), sibr::InteractiveCameraHandler::onGUI(), sibr::RaycastingCamera::projectImg_outside_frustum_correction(), projectImgSpaceInvertY(), resizedH(), resizedW(), rot90CC(), saveToBinary(), size(), toBundleString(), unprojectImgSpaceInvertY(), sibr::InteractiveCameraHandler::update(), sibr::TrackBall::updateBallCenter(), and sibr::TrackBall::updateTranslationPlane().
id()
uint sibr::InputCamera::id () const inline
Returns
the camera id
Definition at line 133 of file InputCamera.hpp.
Referenced by InputCamera(), loadBundle(), loadColmap(), main(), sibr::RaycastingCamera::rayProjection(), and saveAsLookat().
isActive()
bool sibr::InputCamera::isActive (void) const
Check if the input camera active or inactive, camera is completely ignored if set to inactive.
Returns
true if active, false otherwise
Definition at line 134 of file InputCamera.cpp.
References _active.
Referenced by sibr::ULRV2View::chosen_cameras(), sibr::ULRView::chosen_cameras(), and loadLookat().
k1()
float sibr::InputCamera::k1 () const
Returns
the k1 distorsion parameter
Definition at line 147 of file InputCamera.cpp.
References _k1.
Referenced by InputCamera(), loadBundleFRIBR(), loadFromBinary(), resizedH(), resizedW(), saveToBinary(), and toBundleString().
k2()
float sibr::InputCamera::k2 () const
Returns
the k2 distorsion parameter
Definition at line 148 of file InputCamera.cpp.
References _k2.
Referenced by InputCamera(), loadBundleFRIBR(), loadFromBinary(), resizedH(), resizedW(), saveToBinary(), and toBundleString().
load()
std::vector< InputCamera::Ptr > sibr::InputCamera::load (const std::string & datasetPath, float zNear = 0.01f, float zFar = 1000.0f, const std::string & bundleName = "bundle.out", const std::string & listName = "list_images.txt") static
Load cameras from a bundler file.
Parameters
datasetPath path to the root of the dataset, should contain bundle.out, list_images.txt and optionally clipping_planes.txt
zNear default near-plane value to use if the clipping_planes.txt file doesn't exist
zFar default far-plane value to use if the clipping_planes.txt file doesn't exist
bundleName name of the bundle file
listName name of the list images file
Returns
the loaded cameras
Definition at line 198 of file InputCamera.cpp.
References sibr::ActiveImageFile::active(), sibr::InputCamera::Z::far, sibr::ActiveImageFile::load(), loadBundle(), sibr::InputCamera::Z::near, setActive(), sibr::ActiveImageFile::setNumImages(), SIBR_LOG, SIBR_WRG, sibr::InputCamera::Z::Z(), and sibr::Key::Z.
Referenced by main().
loadBundle()
std::vector< InputCamera::Ptr > sibr::InputCamera::loadBundle (const std::string & bundlerPath, float zNear = 0.01f, float zFar = 1000.0f, const std::string & listImagePath = "", bool path = false) static
Load cameras from a bundle file.
Parameters
bundlerPath path to the bundle file.
zNear default near-plane value to use
zFar default far-plane value to use.
listImagePath path to the list_images.txt file. Will default to a file in the same directory as the bundle.out file.
path if this is a path, then you can load more images that those defined in the list_images file of the datset; TODO: possibly should require a list_images.txt for the path
Returns
the loaded cameras
Definition at line 736 of file InputCamera.cpp.
References h(), id(), InputCamera(), ibr_convert_old_to_new::line, ibr_convert_old_to_new::list_images, name(), SIBR_ERR, SIBR_LOG, and w().
Referenced by load(), loadRawRC(), and main().
loadBundleFRIBR()
std::vector< InputCamera::Ptr > sibr::InputCamera::loadBundleFRIBR (const std::string & bundlerPath, float zNear = 0.01f, float zFar = 1000.0f, const std::string & listImagePath = "") static
Load cameras from a bundle file.
Parameters
bundlerPath path to the bundle file.
zNear default near-plane value to use
zFar default far-plane value to use.
listImagePath path to the list_images.txt file. Will default to a file in the same directory as the bundle.out file.
Returns
the loaded cameras
Definition at line 834 of file InputCamera.cpp.
References InputCamera(), k1(), k2(), ibr_convert_old_to_new::line, sibr::Image< T_Type, T_NumComp >::load(), sibr::parentDirectory(), sibr::Camera::position(), sibr::Camera::rotation(), SIBR_ERR, SIBR_LOG, and sibr::Image< T_Type, T_NumComp >::size().
loadColmap()
std::vector< InputCamera::Ptr > sibr::InputCamera::loadColmap (const std::string & colmapSparsePath, const float zNear = 0.01f, const float zFar = 1000.0f, const int fovXfovYFlag = 0) static
Load cameras from a Colmap txt file.
Parameters
colmapSparsePath path to the Colmap sparse directory, should contains cameras.txt and images.txt
zNear default near-plane value to use
zFar default far-plane value to use.
fovXfovYFlag should we use two dimensional fov.
Returns
the loaded cameras
Note
the camera frame is internally transformed to be consistent with fribr and RC.
Definition at line 611 of file InputCamera.cpp.
References id(), InputCamera(), ibr_convert_old_to_new::line, sibr::Camera::position(), SIBR_ERR, SIBR_WRG, sibr::split(), and ibr_preprocess_rc_to_sibr::tokens.
Referenced by sibr::ParseData::getParsedColmapData(), sibr::CameraRecorder::loadColmap(), and main().
loadFromBinary()
bool sibr::InputCamera::loadFromBinary (const std::string & filename)
Load from internal binary representation.
Parameters
filename file path
Returns
success boolean
Definition at line 1061 of file InputCamera.cpp.
References _focal, _h, _k1, _k2, _w, sibr::Camera::aspect(), focal(), sibr::Camera::fovy(), h(), k1(), k2(), sibr::ByteStream::load(), sibr::Camera::position(), sibr::Camera::rotation(), SIBR_ERR, SIBR_INPUTCAMERA_BINARYFILE_VERSION, SIBR_WRG, w(), sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::InteractiveCameraHandler::loadDefaultCamera(), and sibr::InteractiveCameraHandler::onGUI().
loadLookat()
std::vector< InputCamera::Ptr > sibr::InputCamera::loadLookat (const std::string & lookatPath, const std::vector< sibr::Vector2u > & wh = std::vector<sibr::Vector2u>(), float zNear = -1, float zFar = -1) static
Load cameras from a .lookat file generated by our Blender plugin.
Parameters
lookatPath path to the lookAt file
wh indicative size of each camera image
zNear default near-plane value to use
zFar default far-plane value to use.
Returns
the loaded cameras
Definition at line 429 of file InputCamera.cpp.
References h(), InputCamera(), isActive(), ibr_convert_old_to_new::line, sibr::Camera::rotation(), SIBR_WRG, sibr::split(), sibr::Key::Up, w(), sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::CameraRecorder::loadLookat(), and main().
loadMeshroom()
std::vector< InputCamera::Ptr > sibr::InputCamera::loadMeshroom (const std::string & meshroomSFMPath, const float zNear = 0.01f, const float zFar = 1000.0f) static
Load cameras from a Meshrrom SFM cameras.sfm txt file.
Parameters
meshroomSFMPath path to the Meshroom StructureFromMotion/{dd63cea98bda0e3b53ec76f17b0753b3e4dde589}/ directory, should contains cameras.sfm
zNear default near-plane value to use
zFar default far-plane value to use.
Returns
the loaded cameras
Note
the camera frame is internally transformed to be consistent with fribr and RC.
Definition at line 929 of file InputCamera.cpp.
References sibr::Camera::position(), and sibr::Camera::rotation().
Referenced by sibr::ParseData::getParsedMeshroomData().
loadNVM()
std::vector< InputCamera::Ptr > sibr::InputCamera::loadNVM (const std::string & nvmPath, float zNear = 0.01f, float zFar = 1000.0f, std::vector< sibr::Vector2u > wh = std::vector<sibr::Vector2u>()) static
Load cameras from a NVM file.
Parameters
nvmPath path to the NVM file
zNear default near-plane value to use
zFar default far-plane value to use.
wh will contain the sizes of each camera image
Returns
the loaded cameras
Definition at line 289 of file InputCamera.cpp.
References sibr::Camera::aspect(), sibr::IImage::imageResolution(), InputCamera(), sibr::parentDirectory(), and SIBR_WRG.
Referenced by sibr::ParseData::getParsedNVMData(), and main().
lookatString()
std::string sibr::InputCamera::lookatString () const
Return the lookat string of the camera.
Definition at line 554 of file InputCamera.cpp.
References sibr::Camera::dir(), sibr::Camera::fovy(), sibr::Camera::position(), sibr::Camera::up(), sibr::Camera::zfar(), and sibr::Camera::znear().
name() [1/2]
void sibr::InputCamera::name (const std::string & s) inline
Set camera name.
Parameters
s the new name
Definition at line 124 of file InputCamera.hpp.
name() [2/2]
const std::string& sibr::InputCamera::name (void) const inline
Returns
the image name
Definition at line 119 of file InputCamera.hpp.
Referenced by loadBundle(), main(), resizedH(), and resizedW().
operator=() [1/2]
InputCamera& sibr::InputCamera::operator= (const InputCamera &) default
Copy operator.
operator=() [2/2]
InputCamera& sibr::InputCamera::operator= (InputCamera &&) default
Move operator.
projectImgSpaceInvertY()
Vector3f sibr::InputCamera::projectImgSpaceInvertY (const Vector3f & point3d) const
Project 3D point using perspective projection.
Parameters
point3d 3D point
Returns
pixel coordinates in [0,w-1]x[0,h-1] and depth d in [-1,1]
Definition at line 1053 of file InputCamera.cpp.
References h(), sibr::Camera::project(), and w().
projectScreen()
Vector3f sibr::InputCamera::projectScreen (const Vector3f & pt) const
Project a world space point into screen space.
Parameters
pt 3d world point
Returns
screen space position and depth, in (0,w)x(0,h)x(0,1)
Definition at line 139 of file InputCamera.cpp.
References _h, _w, and sibr::Camera::project().
readFromFile()
void sibr::InputCamera::readFromFile (std::istream & infile)
Load a file in the IBR TopView format.
Parameters
infile the input file
Definition at line 1147 of file InputCamera.cpp.
References IBRVIEW_TOPVIEW_SAVEVERSION, sibr::Camera::set(), and SIBR_WRG.
Referenced by sibr::MultiMeshManager::setIntialView(), and sibr::SceneDebugView::setup().
resizedH()
InputCamera sibr::InputCamera::resizedH (int h) const
Return a new camera resized to the specified height.
Definition at line 150 of file InputCamera.cpp.
References sibr::Camera::_aspect, _focal, _h, _id, _k1, _k2, h(), k1(), k2(), name(), sibr::Camera::position(), sibr::Camera::rotation(), w(), sibr::Camera::zfar(), and sibr::Camera::znear().
resizedW()
InputCamera sibr::InputCamera::resizedW (int w) const
Return a new camera resized to the specified height.
Definition at line 173 of file InputCamera.cpp.
References sibr::Camera::_aspect, _focal, _h, _id, _k1, _k2, h(), k1(), k2(), name(), sibr::Camera::position(), sibr::Camera::rotation(), w(), sibr::Camera::zfar(), and sibr::Camera::znear().
saveAsBundle()
void sibr::InputCamera::saveAsBundle (const std::vector< InputCamera::Ptr > & cams, const std::string & fileName, bool negativeZ = false, bool exportImages = false, bool recomputeFocal = true) static
Save a vector of cameras as a bundle file.
Parameters
cams the cameras
fileName output bundle file path
negativeZ should the Z axis be flipped
exportImages should empty images with the proper dimensions be saved in a visualize subdirectory
oldFocal recompute focal, else assign that of camera TODO: fix this
Definition at line 1209 of file InputCamera.cpp.
References sibr::makeDirectory(), and SIBR_WRG.
Referenced by main().
saveAsLookat() [1/2]
void sibr::InputCamera::saveAsLookat (const std::vector< InputCamera::Ptr > & cams, const std::string & fileName) static
save a vector of cameras as lookat
Definition at line 586 of file InputCamera.cpp.
Referenced by main(), sibr::InteractiveCameraHandler::onGUI(), and sibr::CameraRecorder::saveAsLookAt().
saveAsLookat() [2/2]
void sibr::InputCamera::saveAsLookat (const std::vector< sibr::Camera > & cams, const std::string & fileName) static
Save a vector of cameras as a lookat file.
Parameters
cams the cameras
fileName output lookat file path
Definition at line 1247 of file InputCamera.cpp.
References id(), SIBR_WRG, size(), and sibr::Camera::up().
saveImageSizes()
void sibr::InputCamera::saveImageSizes (const std::vector< InputCamera::Ptr > & cams, const std::string & fileName) static
save a vector of cameras sizes to a file to be read by mitsuba rendering script
Definition at line 597 of file InputCamera.cpp.
saveToBinary()
void sibr::InputCamera::saveToBinary (const std::string & filename) const
Save to disk using internal binary representation.
Parameters
filename file path
Definition at line 1119 of file InputCamera.cpp.
References sibr::Camera::_aspect, _focal, sibr::Camera::_fov, _h, _k1, _k2, _w, sibr::Camera::_zfar, sibr::Camera::_znear, sibr::Camera::aspect(), focal(), h(), k1(), k2(), sibr::Camera::position(), sibr::Camera::rotation(), sibr::ByteStream::saveToFile(), SIBR_INPUTCAMERA_BINARYFILE_VERSION, w(), sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::saveDefaultCamera().
setActive()
void sibr::InputCamera::setActive (bool active) inline
Set camera active status.
Parameters
active if true, camera is in use
Definition at line 116 of file InputCamera.hpp.
Referenced by load().
setFocal()
void sibr::InputCamera::setFocal (float focal) inline
set the focal length ; to be used with caution; focal is usually inferred from the fov
Definition at line 145 of file InputCamera.hpp.
size()
void sibr::InputCamera::size (uint w, uint h)
Update image dimensions.
Calls update() after changing image width and height
Parameters
w image width
h image height
Definition at line 131 of file InputCamera.cpp.
References _h, _w, h(), and w().
Referenced by sibr::InteractiveCameraHandler::fromCamera(), sibr::StereoAnaglyphRdrMode::render(), rot90CC(), saveAsLookat(), sibr::TrackBall::setCameraAttributes(), sibr::TrackBall::updateAspectWithViewport(), and sibr::TrackBall::updateTrackBallCameraSize().
toBundleString()
std::string sibr::InputCamera::toBundleString (bool negativeZ = false, bool recomputeFocal = true) const
Conver to Bundle string.
Parameters
negativeZ should the Z axis be flipped \recomputeFocal recompute the focal or just set
Returns
a string that can be used to create a bundle file from this camera
Definition at line 1174 of file InputCamera.cpp.
References _focal, focal(), sibr::Camera::fovy(), h(), k1(), k2(), sibr::Camera::position(), sibr::Transform3< T >::rotation(), and sibr::Camera::transform().
Referenced by main().
unprojectImgSpaceInvertY()
Vector3f sibr::InputCamera::unprojectImgSpaceInvertY (const sibr::Vector2i & pixelPos, const float & depth) const
Back-project pixel coordinates and depth.
Parameters
pixelPos pixel coordinates p[0],p[1] in [0,w-1]x[0,h-1]
depth d in [-1,1]
Returns
3D world point
Definition at line 1046 of file InputCamera.cpp.
References h(), sibr::Camera::unproject(), and w().
Referenced by legacyV2main().
w()
uint sibr::InputCamera::w (void) const
Input image width.
Returns
width of input image
Definition at line 132 of file InputCamera.cpp.
References _w.
Referenced by sibr::CameraRaycaster::castForEachPixel(), sibr::CameraRaycaster::computeClippingPlanes(), sibr::CameraRaycaster::computePixelDerivatives(), sibr::Intersector2D::frustrumQuadsIntersect(), InputCamera(), sibr::InteractiveCameraHandler::interpolate(), sibr::Orbit::interpolateOrbit(), legacyV2main(), loadBundle(), loadFromBinary(), loadLookat(), main(), sibr::TrackBall::mapTo3Dplane(), sibr::InteractiveCameraHandler::onGUI(), sibr::RaycastingCamera::projectImg_outside_frustum_correction(), projectImgSpaceInvertY(), resizedH(), resizedW(), rot90CC(), saveToBinary(), size(), unprojectImgSpaceInvertY(), sibr::InteractiveCameraHandler::update(), sibr::TrackBall::updateBallCenter(), and sibr::TrackBall::updateTranslationPlane().
writeToFile()
void sibr::InputCamera::writeToFile (std::ostream & outfile) const
Save a file in the IBR TopView format.
Parameters
outfile the destination file
Definition at line 1165 of file InputCamera.cpp.
References IBRVIEW_TOPVIEW_SAVEVERSION, sibr::Transform3< T >::position(), sibr::Transform3< T >::rotation(), and sibr::Camera::transform().
Referenced by sibr::SceneDebugView::save().
Member Data Documentation
_active
bool sibr::InputCamera::_active protected
is the camera currently in use.
Definition at line 308 of file InputCamera.hpp.
Referenced by InputCamera(), and isActive().
_focal
float sibr::InputCamera::_focal protected
focal length
Definition at line 301 of file InputCamera.hpp.
Referenced by focal(), InputCamera(), loadFromBinary(), resizedH(), resizedW(), saveToBinary(), and toBundleString().
_h
uint sibr::InputCamera::_h protected
Image height.
Definition at line 305 of file InputCamera.hpp.
Referenced by getImageCorners(), h(), InputCamera(), loadFromBinary(), projectScreen(), resizedH(), resizedW(), saveToBinary(), and size().
_id
uint sibr::InputCamera::_id protected
Input camera id.
Definition at line 306 of file InputCamera.hpp.
Referenced by InputCamera(), resizedH(), and resizedW().
_k1
float sibr::InputCamera::_k1 protected
K1 bundler distorsion parameter.
Definition at line 302 of file InputCamera.hpp.
Referenced by InputCamera(), k1(), loadFromBinary(), resizedH(), resizedW(), and saveToBinary().
_k2
float sibr::InputCamera::_k2 protected
K2 bundler dist parameter.
Definition at line 303 of file InputCamera.hpp.
Referenced by InputCamera(), k2(), loadFromBinary(), resizedH(), resizedW(), and saveToBinary().
_name
std::string sibr::InputCamera::_name protected
Input image name.
Definition at line 307 of file InputCamera.hpp.
Referenced by InputCamera().
_w
uint sibr::InputCamera::_w protected
Image width.
Definition at line 304 of file InputCamera.hpp.
Referenced by getImageCorners(), InputCamera(), loadFromBinary(), projectScreen(), saveToBinary(), size(), and w().
The documentation for this class was generated from the following files:
src/core/assets/InputCamera.hpp
src/core/assets/InputCamera.cpp