SIBR: sibr::ULRRenderer Class Reference
sibr::ULRRenderer Class Reference
Legacy ULR renderer.
#include <ULRRenderer.hpp>
Private Member Functions
SIBR_CLASS_PTR (ULRRenderer)
ULRRenderer (const uint w, const uint h)
Constructor.
void process (std::vector< uint > &imgs_ulr, const sibr::Camera &eye, const sibr::BasicIBRScene::Ptr scene, std::shared_ptr< sibr::Mesh > &altMesh, const std::vector< std::shared_ptr< RenderTargetRGBA32F > > &inputRTs, IRenderTarget &output)
Render.
void doOccl (bool val)
Toggle occlusion testing.
Private Attributes
sibr::RenderTargetRGBA32F::Ptr _ulr0_RT
sibr::RenderTargetRGBA32F::Ptr _ulr1_RT
sibr::RenderTargetRGBA32F::Ptr _depth_RT
sibr::GLShader _ulrShaderPass1
sibr::GLShader _ulrShaderPass2
sibr::GLShader _depthShader
sibr::GLParameter _ulrShaderPass1_nCamPos
sibr::GLParameter _ulrShaderPass1_iCamPos
sibr::GLParameter _ulrShaderPass1_iCamDir
sibr::GLParameter _ulrShaderPass1_iCamProj
sibr::GLParameter _ulrShaderPass1_occlTest
sibr::GLParameter _ulrShaderPass1_masking
sibr::GLParameter _depthShader_proj
bool _doOccl
Additional Inherited Members
Public Member Functions inherited from sibr::RenderMaskHolder
void setMasks (const std::vector< MaskPtr > &masks)
Update the masks.
const std::vector< MaskPtr > & getMasks (void) const
bool useMasks (void) const
void loadMasks (const sibr::BasicIBRScene::Ptr &ibrScene, const std::string &maskDir, const std::string &preFileName, const std::string &postFileName, int w, int h)
Load masks from black and white images on disk.
void uploadMaskGPU (sibr::ImageL8 &img, int i, std::vector< RenderTargetLum::Ptr > &masks, bool invert)
Upload a mask image to the GPU.
Detailed Description
Legacy ULR renderer.
Process each input image separately and accumulate them.
Definition at line 15 of file ULRRenderer.hpp.
Constructor & Destructor Documentation
ULRRenderer()
sibr::ULRRenderer::ULRRenderer (const uint w, const uint h) private
Constructor.
Parameters
w rendering width
h rendering height
Definition at line 6 of file ULRRenderer.cpp.
References _depth_RT, _depthShader, _depthShader_proj, _doOccl, _ulr0_RT, _ulr1_RT, _ulrShaderPass1, _ulrShaderPass1_iCamDir, _ulrShaderPass1_iCamPos, _ulrShaderPass1_iCamProj, _ulrShaderPass1_masking, _ulrShaderPass1_nCamPos, _ulrShaderPass1_occlTest, _ulrShaderPass2, sibr::getShadersDirectory(), sibr::GLParameter::init(), sibr::GLShader::init(), and sibr::loadFile().
Member Function Documentation
doOccl()
void sibr::ULRRenderer::doOccl (bool val) inline private
Toggle occlusion testing.
Parameters
val should occlusion testing be performed
Definition at line 42 of file ULRRenderer.hpp.
process()
void sibr::ULRRenderer::process (std::vector< uint > & imgs_ulr, const sibr::Camera & eye, const sibr::BasicIBRScene::Ptr scene, std::shared_ptr< sibr::Mesh > & altMesh, const std::vector< std::shared_ptr< RenderTargetRGBA32F > > & inputRTs, IRenderTarget & output) private
Render.
Parameters
imgs_ulr vector of selected image IDs
eye novel viewpoint
scene the scene to render
altMesh optional alternative mesh
inputRTs the RGBD input images
output destination target
Definition at line 39 of file ULRRenderer.cpp.
References _depth_RT, _depthShader, _depthShader_proj, _doOccl, _ulr0_RT, _ulr1_RT, _ulrShaderPass1, _ulrShaderPass1_iCamDir, _ulrShaderPass1_iCamPos, _ulrShaderPass1_iCamProj, _ulrShaderPass1_masking, _ulrShaderPass1_nCamPos, _ulrShaderPass1_occlTest, _ulrShaderPass2, sibr::GLShader::begin(), sibr::Camera::dir(), ibr_preprocess_rc_to_sibr::dst, sibr::GLShader::end(), sibr::RenderMaskHolder::getMasks(), sibr::Camera::position(), sibr::Mesh::render(), sibr::RenderUtility::renderScreenQuad(), sibr::GLParameter::set(), sibr::show(), sibr::RenderMaskHolder::useMasks(), sibr::Camera::viewproj(), and sibr::Camera::znear().
SIBR_CLASS_PTR()
sibr::ULRRenderer::SIBR_CLASS_PTR (ULRRenderer) private
Member Data Documentation
_depth_RT
sibr::RenderTargetRGBA32F::Ptr sibr::ULRRenderer::_depth_RT private
Definition at line 47 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_depthShader
sibr::GLShader sibr::ULRRenderer::_depthShader private
Definition at line 51 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_depthShader_proj
sibr::GLParameter sibr::ULRRenderer::_depthShader_proj private
Definition at line 59 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_doOccl
bool sibr::ULRRenderer::_doOccl private
Definition at line 61 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulr0_RT
sibr::RenderTargetRGBA32F::Ptr sibr::ULRRenderer::_ulr0_RT private
Definition at line 45 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulr1_RT
sibr::RenderTargetRGBA32F::Ptr sibr::ULRRenderer::_ulr1_RT private
Definition at line 46 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulrShaderPass1
sibr::GLShader sibr::ULRRenderer::_ulrShaderPass1 private
Definition at line 49 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulrShaderPass1_iCamDir
sibr::GLParameter sibr::ULRRenderer::_ulrShaderPass1_iCamDir private
Definition at line 55 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulrShaderPass1_iCamPos
sibr::GLParameter sibr::ULRRenderer::_ulrShaderPass1_iCamPos private
Definition at line 54 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulrShaderPass1_iCamProj
sibr::GLParameter sibr::ULRRenderer::_ulrShaderPass1_iCamProj private
Definition at line 56 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulrShaderPass1_masking
sibr::GLParameter sibr::ULRRenderer::_ulrShaderPass1_masking private
Definition at line 58 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulrShaderPass1_nCamPos
sibr::GLParameter sibr::ULRRenderer::_ulrShaderPass1_nCamPos private
Definition at line 53 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulrShaderPass1_occlTest
sibr::GLParameter sibr::ULRRenderer::_ulrShaderPass1_occlTest private
Definition at line 57 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
_ulrShaderPass2
sibr::GLShader sibr::ULRRenderer::_ulrShaderPass2 private
Definition at line 50 of file ULRRenderer.hpp.
Referenced by process(), and ULRRenderer().
The documentation for this class was generated from the following files:
src/projects/ulr/renderer/ULRRenderer.hpp
src/projects/ulr/renderer/ULRRenderer.cpp