SIBR: sibr::Window Class Reference
sibr::Window Class Reference
sibr_graphics
System window backed by an internal framebuffer.
#include <Window.hpp>
Classes
struct AutoInitializer
Helper to handle window creation/destruction.
Public Types
typedef std::shared_ptr< Window > Ptr
Public Types inherited from sibr::IRenderTarget
typedef std::shared_ptr< IRenderTarget > Ptr
typedef std::unique_ptr< IRenderTarget > UPtr
Public Member Functions
Window (const std::string &title, const WindowArgs &args={}, const std::string &defaultSettingsFilename="")
Constructor.
Window (uint w, uint h, const std::string &title, const WindowArgs &args={}, const std::string &defaultSettingsFilename="")
Constructor, overriding the window size.
Window (const std::string &title, const sibr::Vector2i &margins, const WindowArgs &args={}, const std::string &defaultSettingsFilename="")
Constructor, adjust the size to fill the screen except for the margins.
GLFWwindow * GLFW (void)
void makeContextCurrent (void)
Activate the associated graphics context.
GLFWwindow * getContextCurrent (void)
void makeContextNull (void)
Deactivate the associated graphics context.
void swapBuffer (void)
Flush the graphics pipeline and perform rendering, displaying the result in the abck buffer.
void size (int w, int h)
Set the window size.
Vector2i size (void) const
void position (const unsigned int x, const unsigned int y)
Set the window position.
Vector2i position () const
void setFrameRate (int fps)
Set the framerate.
void enableCursor (bool enable)
Display the cursor in the window.
bool isOpened (void) const
void close (void)
Mark the window as closed.
bool isFullscreen (void) const
void setFullscreen (const bool fullscreen)
Toggle fullscreen.
bool isVsynced (void) const
void setVsynced (const bool vsync)
Toggle V-sync.
const Viewport & viewport (void) const
void viewport (const Viewport &view)
Set the window viewport.
GLuint texture (uint t=0) const
Get the backbuffer texture ID.
GLuint handle (uint t=0) const
Get the backbuffer texture ID.
GLuint fbo (void) const
void bind (void)
Bind the window buffer.
void unbind (void)
Unind the window buffer.
void clear (void)
Clear the window buffer.
uint w (void) const
uint h (void) const
float scaling () const
Public Member Functions inherited from sibr::IRenderTarget
virtual ~IRenderTarget (void)
Destructor.
Static Public Member Functions
static Vector2i desktopSize (void)
static bool contextIsRunning (void)
Static Public Attributes
static int contextId = -1
Last created window context ID (-1 initially).
Private Types
typedef std::unique_ptr< GLFWwindow, std::function< void(GLFWwindow *)> > GLFWwindowptr
Window pointer for callbacks.
Private Member Functions
void setup (int width, int height, const std::string &title, const WindowArgs &args, const std::string &defaultSettingsFilename="")
Setup the window.
Private Attributes
bool _shouldClose
Is the window marked as closed.
GLFWwindowptr _glfwWin
Undelrying GLF window.
Vector2i _size
Window size.
const bool _useGUI
Should ImGui windows be displayed.
bool _useVSync
is the window using vsync.
Vector2i _oldPosition
Backup for handling fullscreen/windowed mode restoration.
Vector2i _oldSize
Backup for handling fullscreen/windowed mode restoration.
Viewport _viewport
Current viewport.
float _scaling = 1.0f
Internal scaling for HiDPI screens.
AutoInitializer _hiddenInit
nifty counter used to auto-init window system
std::string _defaultImguiSettingsFilename = "imgui_default.ini"
string of default Imgui settings filename
Detailed Description
System window backed by an internal framebuffer.
Definition at line 15 of file Window.hpp.
Member Typedef Documentation
GLFWwindowptr
typedef std::unique_ptr<GLFWwindow, std::function<void(GLFWwindow*)> > sibr::Window::GLFWwindowptr private
Window pointer for callbacks.
Definition at line 166 of file Window.hpp.
Ptr
typedef std::shared_ptr<Window> sibr::Window::Ptr
Definition at line 18 of file Window.hpp.
Constructor & Destructor Documentation
Window() [1/3]
sibr::Window::Window (const std::string & title, const WindowArgs & args = {}, const std::string & defaultSettingsFilename = "")
Constructor.
Parameters
title window title
args window setup arguments
See also
WindowArgs
Parameters
defaultSettingsFilename default settings file for this specific window
Definition at line 163 of file Window.cpp.
Window() [2/3]
sibr::Window::Window (uint w, uint h, const std::string & title, const WindowArgs & args = {}, const std::string & defaultSettingsFilename = "")
Constructor, overriding the window size.
Parameters
w window width
h window height
title window title
args window setup arguments
See also
WindowArgs
Parameters
defaultSettingsFilename default settings file for this specific window
Definition at line 152 of file Window.cpp.
References _glfwWin, sibr::WindowArgs::fullscreen, h(), setup(), and w().
Window() [3/3]
sibr::Window::Window (const std::string & title, const sibr::Vector2i & margins, const WindowArgs & args = {}, const std::string & defaultSettingsFilename = "")
Constructor, adjust the size to fill the screen except for the margins.
Parameters
title window title
margins horizontal and vertical margins to preserve on each side of the window
args window setup arguments
See also
WindowArgs
Parameters
defaultSettingsFilename default settings file for this specific window
Definition at line 168 of file Window.cpp.
References _glfwWin, desktopSize(), sibr::WindowArgs::fullscreen, and setup().
Member Function Documentation
bind()
void sibr::Window::bind (void) inline virtual
Bind the window buffer.
Implements sibr::IRenderTarget.
Definition at line 214 of file Window.hpp.
clear()
void sibr::Window::clear (void) inline virtual
Clear the window buffer.
Implements sibr::IRenderTarget.
Definition at line 224 of file Window.hpp.
close()
void sibr::Window::close (void)
Mark the window as closed.
Definition at line 350 of file Window.cpp.
References _glfwWin, and _shouldClose.
Referenced by legacyV1main(), legacyV2main(), main(), sibr::MultiViewManager::onGui(), and sibr::show().
contextIsRunning()
bool sibr::Window::contextIsRunning (void) static
Returns
true if an openGL context is active.
Definition at line 119 of file Window.cpp.
References sibr::windowCounter.
desktopSize()
Vector2i sibr::Window::desktopSize (void) static
Returns
the screen size.
Definition at line 321 of file Window.cpp.
Referenced by sibr::MultiViewManager::MultiViewManager(), setup(), and Window().
enableCursor()
void sibr::Window::enableCursor (bool enable)
Display the cursor in the window.
Parameters
enable boolean flag
Definition at line 417 of file Window.cpp.
References _glfwWin.
fbo()
GLuint sibr::Window::fbo (void) const inline virtual
Returns
the window buffer ID (0)
Implements sibr::IRenderTarget.
Definition at line 210 of file Window.hpp.
getContextCurrent()
GLFWwindow * sibr::Window::getContextCurrent (void) inline
Returns
the context currently in use (represented by a GLFW window)
Definition at line 198 of file Window.hpp.
GLFW()
GLFWwindow * sibr::Window::GLFW (void)
Returns
a pointer to the underlying GLFW window
Definition at line 422 of file Window.cpp.
References _glfwWin.
h()
uint sibr::Window::h (void) const inline virtual
Returns
the window buffer height
Implements sibr::IRenderTarget.
Definition at line 232 of file Window.hpp.
References size().
Referenced by size(), and Window().
handle()
GLuint sibr::Window::handle (uint t = 0) const inline virtual
Get the backbuffer texture ID.
unsuported.
Implements sibr::IRenderTarget.
Definition at line 206 of file Window.hpp.
References SIBR_ERR.
isFullscreen()
bool sibr::Window::isFullscreen (void) const
Returns
true if the window is fullscreen.
Definition at line 356 of file Window.cpp.
References _glfwWin.
Referenced by sibr::MultiViewManager::onGui(), and setFullscreen().
isOpened()
bool sibr::Window::isOpened (void) const
Returns
if the window is currently opened
Definition at line 345 of file Window.cpp.
References _glfwWin, and _shouldClose.
Referenced by sibr::MultiViewInterface::displayLoop(), legacyV1main(), legacyV2main(), main(), and sibr::MeshViewer::renderLoop().
isVsynced()
bool sibr::Window::isVsynced (void) const
Returns
true if the window is using V-sync.
Definition at line 407 of file Window.cpp.
References _useVSync.
Referenced by sibr::MultiViewManager::onGui().
makeContextCurrent()
void sibr::Window::makeContextCurrent (void) inline
Activate the associated graphics context.
Definition at line 190 of file Window.hpp.
References _glfwWin.
Referenced by sibr::MultiViewInterface::displayLoop(), legacyV1main(), legacyV2main(), main(), setup(), and sibr::show().
makeContextNull()
void sibr::Window::makeContextNull (void) inline
Deactivate the associated graphics context.
Definition at line 194 of file Window.hpp.
position() [1/2]
Vector2i sibr::Window::position (void) const
Returns
the window position on screen
Definition at line 339 of file Window.cpp.
References _glfwWin.
Referenced by setFullscreen(), and setup().
position() [2/2]
void sibr::Window::position (const unsigned int x, const unsigned int y)
Set the window position.
Parameters
x horizontal location
y vertical location
Definition at line 334 of file Window.cpp.
References _glfwWin.
Referenced by sibr::MultiViewManager::MultiViewManager().
scaling()
float sibr::Window::scaling () const inline
Returns
the screens caling factor.
Definition at line 236 of file Window.hpp.
References _scaling.
Referenced by sibr::MultiViewManager::onGui(), and setup().
setFrameRate()
void sibr::Window::setFrameRate (int fps)
Set the framerate.
Parameters
fps one of 60, 30, 15
Definition at line 396 of file Window.cpp.
setFullscreen()
void sibr::Window::setFullscreen (const bool fullscreen)
Toggle fullscreen.
Parameters
fullscreen if true the window will be resized to occupy the whole screen, without visible borders.
Definition at line 361 of file Window.cpp.
References _glfwWin, _oldPosition, _oldSize, _useVSync, isFullscreen(), position(), and size().
Referenced by sibr::MultiViewManager::onGui().
setup()
void sibr::Window::setup (int width, int height, const std::string & title, const WindowArgs & args, const std::string & defaultSettingsFilename = "") private
Setup the window.
Parameters
width window width on screen
height window height on screen
title window title
args window setup arguments
defaultSettingsFilename default settings file for this specific window
See also
WindowArgs
Definition at line 194 of file Window.cpp.
References _defaultImguiSettingsFilename, _glfwWin, _oldPosition, _oldSize, _scaling, _useVSync, sibr::clamp(), contextId, desktopSize(), sibr::fileExists(), sibr::WindowArgs::fullscreen, sibr::getAppDataDirectory(), sibr::getResourcesDirectory(), sibr::WindowArgs::gl_debug, sibr::glErrorCallback(), sibr::glfwCursorPosCallback(), sibr::glfwKeyboardCallback(), sibr::glfwMouseButtonCallback(), sibr::glfwMouseScrollCallback(), sibr::glfwResizeCallback(), sibr::WindowArgs::hdpi, makeContextCurrent(), sibr::WindowArgs::offscreen, position(), sibr::round(), scaling(), SIBR_ERR, SIBR_LOG, size(), viewport(), and sibr::WindowArgs::vsync.
Referenced by Window().
setVsynced()
void sibr::Window::setVsynced (const bool vsync)
Toggle V-sync.
Parameters
vsync if true, framerate will be limited to 60 FPS
Note
When set to false, tearing might be visible.
Definition at line 412 of file Window.cpp.
References _useVSync.
Referenced by sibr::MultiViewManager::onGui().
size() [1/2]
void sibr::Window::size (int w, int h)
Set the window size.
Parameters
w width
h height
Definition at line 381 of file Window.cpp.
References _glfwWin, h(), SIBR_WRG, size(), viewport(), and w().
Referenced by sibr::MultiViewInterface::displayLoop(), sibr::MultiViewManager::MultiViewManager(), sibr::MultiViewManager::onGui(), sibr::show(), and sibr::MultiViewInterface::updateMeshView().
size() [2/2]
Vector2i sibr::Window::size (void) const
Returns
the window size
Definition at line 327 of file Window.cpp.
References _glfwWin.
Referenced by h(), setFullscreen(), setup(), size(), and w().
swapBuffer()
void sibr::Window::swapBuffer (void) inline
Flush the graphics pipeline and perform rendering, displaying the result in the abck buffer.
Definition at line 181 of file Window.cpp.
References _glfwWin, and _useGUI.
Referenced by sibr::MultiViewInterface::displayLoop(), legacyV1main(), legacyV2main(), main(), sibr::MeshViewer::renderLoop(), and sibr::show().
texture()
GLuint sibr::Window::texture (uint t = 0) const inline virtual
Get the backbuffer texture ID.
unsuported.
Implements sibr::IRenderTarget.
Definition at line 202 of file Window.hpp.
References SIBR_ERR.
unbind()
void sibr::Window::unbind (void) inline virtual
Unind the window buffer.
Implements sibr::IRenderTarget.
Definition at line 220 of file Window.hpp.
viewport() [1/2]
void sibr::Window::viewport (const Viewport & view) inline
Set the window viewport.
Parameters
view the new viewport
Definition at line 245 of file Window.hpp.
References _viewport.
viewport() [2/2]
const Viewport & sibr::Window::viewport (void) const inline
Returns
the window viewport
Definition at line 241 of file Window.hpp.
References _viewport.
Referenced by sibr::MultiViewInterface::displayLoop(), sibr::glfwResizeCallback(), sibr::MultiViewManager::onGui(), sibr::MultiViewManager::onRender(), sibr::SceneDebugView::onRender(), sibr::MeshViewer::renderLoop(), sibr::MeshViewer::setMainMesh(), setup(), sibr::show(), size(), and sibr::MultiViewInterface::updateMeshView().
w()
uint sibr::Window::w (void) const inline virtual
Returns
the window buffer width
Implements sibr::IRenderTarget.
Definition at line 228 of file Window.hpp.
References size().
Referenced by size(), and Window().
Member Data Documentation
_defaultImguiSettingsFilename
std::string sibr::Window::_defaultImguiSettingsFilename = "imgui_default.ini" private
string of default Imgui settings filename
Definition at line 186 of file Window.hpp.
Referenced by setup().
_glfwWin
GLFWwindowptr sibr::Window::_glfwWin private
Undelrying GLF window.
Definition at line 176 of file Window.hpp.
Referenced by close(), enableCursor(), GLFW(), isFullscreen(), isOpened(), makeContextCurrent(), position(), setFullscreen(), setup(), size(), swapBuffer(), and Window().
_hiddenInit
AutoInitializer sibr::Window::_hiddenInit private
nifty counter used to auto-init window system
Definition at line 185 of file Window.hpp.
_oldPosition
Vector2i sibr::Window::_oldPosition private
Backup for handling fullscreen/windowed mode restoration.
Definition at line 180 of file Window.hpp.
Referenced by setFullscreen(), and setup().
_oldSize
Vector2i sibr::Window::_oldSize private
Backup for handling fullscreen/windowed mode restoration.
Definition at line 181 of file Window.hpp.
Referenced by setFullscreen(), and setup().
_scaling
float sibr::Window::_scaling = 1.0f private
Internal scaling for HiDPI screens.
Definition at line 183 of file Window.hpp.
Referenced by scaling(), and setup().
_shouldClose
bool sibr::Window::_shouldClose private
Is the window marked as closed.
Definition at line 175 of file Window.hpp.
Referenced by close(), and isOpened().
_size
Vector2i sibr::Window::_size private
Window size.
Definition at line 177 of file Window.hpp.
_useGUI
const bool sibr::Window::_useGUI private
Should ImGui windows be displayed.
Definition at line 178 of file Window.hpp.
Referenced by swapBuffer().
_useVSync
bool sibr::Window::_useVSync private
is the window using vsync.
Definition at line 179 of file Window.hpp.
Referenced by isVsynced(), setFullscreen(), setup(), and setVsynced().
_viewport
Viewport sibr::Window::_viewport private
Current viewport.
Definition at line 182 of file Window.hpp.
Referenced by viewport().
contextId
int sibr::Window::contextId = -1 static
Last created window context ID (-1 initially).
Definition at line 151 of file Window.hpp.
Referenced by sibr::InterfaceUtilities::circle(), sibr::InterfaceUtilities::rectangle(), sibr::RenderUtility::renderScreenQuad(), and setup().
The documentation for this class was generated from the following files:
src/core/graphics/Window.hpp
src/core/graphics/Window.cpp