SIBR: sibr::DistordCropUtility Class Reference
sibr::DistordCropUtility Class Reference
sibr_imgproc
Helpers for cropping undistorted dataset images so that margins are removed, while keeping the dataset consistent.
#include <DistordCropUtility.hpp>
Classes
struct Bounds
Image crop boundaries .
Public Member Functions
bool isBlack (const sibr::Vector3ub &pixelColor, Vector3i backgroundColor, int threshold_black_color)
Check if a pixel color is close to a reference color.
bool is_number (const std::string &s)
void addPixelToQueue (const sibr::Vector2i &pixel, const sibr::ImageRGB &img, std::priority_queue< sibr::Vector2i > &queue, sibr::Array2d< bool > &arrayVisited, Vector3i backgroundColor, int threshold_black_color)
void findBounds (sibr::Array2d< bool > &isBlack, Bounds &bounds, int thinest_bounding_box_size)
Estimate a region that won't contain any black pixels.
Bounds getBounds (const sibr::ImageRGB &img, Vector3i backgroundColor, int threshold_black_color, int thinest_bounding_box_size, float toleranceFactor)
Estimate a region of an image so that no pixels of a reference color are contained in it.
sibr::Vector2i calculateAvgResolution (const std::vector< Path > &imagePaths, std::vector< sibr::Vector2i > &resolutions, const int batch_size=150)
Estimate the average resolution of a set of images quickly using multithread to speed up the required loading.
sibr::Vector2i findBiggestImageCenteredBox (const Path &root, const std::vector< Path > &imagePaths, std::vector< sibr::Vector2i > &resolutions, int avgWidth=0, int avgHeight=0, const int batch_size=150, float resolutionThreshold=0.15f, float threshold_ratio_bounding_box_size=0.2f, Vector3i backgroundColor=Vector3i(0, 0, 0), int threshold_black_color=10, int thinest_bounding_box_size=5, float toleranceFactor=0.0f)
Find a common crop region for a set of images so that all pixels of a reference color are excluded from all images, while minimizing information loss.
sibr::Vector2i findMinImageSize (const Path &root, const std::vector< Path > &imagePaths)
Find the resolution of the smallest image in a set.
Detailed Description
Helpers for cropping undistorted dataset images so that margins are removed, while keeping the dataset consistent.
Definition at line 20 of file DistordCropUtility.hpp.
Member Function Documentation
addPixelToQueue()
void sibr::DistordCropUtility::addPixelToQueue (const sibr::Vector2i & pixel, const sibr::ImageRGB & img, std::priority_queue< sibr::Vector2i > & queue, sibr::Array2d< bool > & arrayVisited, Vector3i backgroundColor, int threshold_black_color)
Definition at line 18 of file DistordCropUtility.cpp.
References backgroundColor, isBlack(), and threshold_black_color.
Referenced by getBounds().
calculateAvgResolution()
sibr::Vector2i sibr::DistordCropUtility::calculateAvgResolution (const std::vector< Path > & imagePaths, std::vector< sibr::Vector2i > & resolutions, const int batch_size = 150)
Estimate the average resolution of a set of images quickly using multithread to speed up the required loading.
Parameters
imagePaths list of paths to the images
resolutions will contain each image resolution
batch_size number of images loaded per thread internally
Returns
the average resolution
Definition at line 112 of file DistordCropUtility.cpp.
Referenced by findBiggestImageCenteredBox().
findBiggestImageCenteredBox()
sibr::Vector2i sibr::DistordCropUtility::findBiggestImageCenteredBox (const Path & root, const std::vector< Path > & imagePaths, std::vector< sibr::Vector2i > & resolutions, int avgWidth = 0, int avgHeight = 0, const int batch_size = 150, float resolutionThreshold = 0.15f, float threshold_ratio_bounding_box_size = 0.2f, Vector3i backgroundColor = Vector3i(0, 0, 0), int threshold_black_color = 10, int thinest_bounding_box_size = 5, float toleranceFactor = 0.0f)
Find a common crop region for a set of images so that all pixels of a reference color are excluded from all images, while minimizing information loss.
Parameters
root the dataset root path (for writing list files)
imagePaths list of image paths
resolutions will contain the image resolutions
avgWidth average image width, if 0 will be recomputed (slow for large datasets)
avgHeight average image height, if 0 will be recomputed (slow for large datasets)
batch_size batch size for multithreaded image loading
resolutionThreshold ratio of the minimum allowed dimensions over the average image dimensions
threshold_ratio_bounding_box_size maximum change in aspect ratio
backgroundColor the reference background color
threshold_black_color the color tolerance threshold
thinest_bounding_box_size minimum size of the bounds along any dimension
toleranceFactor Additional tolerance factor: if set to 0 the bounds will be tight, if set to 1 it will cover the full image.
Returns
Definition at line 157 of file DistordCropUtility.cpp.
References backgroundColor, calculateAvgResolution(), getBounds(), resolutionThreshold, thinest_bounding_box_size, threshold_black_color, threshold_ratio_bounding_box_size, toleranceFactor, sibr::DistordCropUtility::Bounds::xRatio, and sibr::DistordCropUtility::Bounds::yRatio.
Referenced by main().
findBounds()
void sibr::DistordCropUtility::findBounds (sibr::Array2d< bool > & isBlack, DistordCropUtility::Bounds & bounds, int thinest_bounding_box_size)
Estimate a region that won't contain any black pixels.
Parameters
isBlack 2D array listing which pixels should be excluded
bounds will contain the region boundaries
thinest_bounding_box_size minimum size of the bounds along any dimension
Definition at line 25 of file DistordCropUtility.cpp.
References isBlack(), thinest_bounding_box_size, sibr::DistordCropUtility::Bounds::xMax, sibr::DistordCropUtility::Bounds::xMin, sibr::DistordCropUtility::Bounds::yMax, and sibr::DistordCropUtility::Bounds::yMin.
Referenced by getBounds().
findMinImageSize()
sibr::Vector2i sibr::DistordCropUtility::findMinImageSize (const Path & root, const std::vector< Path > & imagePaths)
Find the resolution of the smallest image in a set.
Note
In the past, this function was also supposed to exclude images based on a certain criterion and write them to a file.
Parameters
root dataset root path (for writing an exclude list file, see note)
imagePaths list of paths to the images
Returns
the minimum resolution
Definition at line 264 of file DistordCropUtility.cpp.
Referenced by main().
getBounds()
DistordCropUtility::Bounds sibr::DistordCropUtility::getBounds (const sibr::ImageRGB & img, Vector3i backgroundColor, int threshold_black_color, int thinest_bounding_box_size, float toleranceFactor)
Estimate a region of an image so that no pixels of a reference color are contained in it.
Parameters
img the image to crop
backgroundColor the reference color
threshold_black_color the color tolerance threshold
thinest_bounding_box_size minimum size of the bounds along any dimension
toleranceFactor Additional tolerance factor: if set to 0 the bounds will be tight, if set to 1 it will cover the full image.
Returns
the estimated region boundaries
Definition at line 54 of file DistordCropUtility.cpp.
References addPixelToQueue(), backgroundColor, findBounds(), sibr::Image< T_Type, T_NumComp >::h(), sibr::DistordCropUtility::Bounds::height, isBlack(), sibr::Image< T_Type, T_NumComp >::isInRange(), thinest_bounding_box_size, threshold_black_color, toleranceFactor, sibr::Image< T_Type, T_NumComp >::w(), sibr::DistordCropUtility::Bounds::width, sibr::DistordCropUtility::Bounds::xMax, sibr::DistordCropUtility::Bounds::xMin, sibr::DistordCropUtility::Bounds::xRatio, sibr::DistordCropUtility::Bounds::yMax, sibr::DistordCropUtility::Bounds::yMin, and sibr::DistordCropUtility::Bounds::yRatio.
Referenced by findBiggestImageCenteredBox().
is_number()
bool sibr::DistordCropUtility::is_number (const std::string & s)
Definition at line 12 of file DistordCropUtility.cpp.
Referenced by main().
isBlack()
bool sibr::DistordCropUtility::isBlack (const sibr::Vector3ub & pixelColor, Vector3i backgroundColor, int threshold_black_color)
Check if a pixel color is close to a reference color.
Parameters
pixelColor the color to test
backgroundColor the reference color
threshold_black_color the tolerance threshold
Returns
true if ||pixel - background||^2 < threshold
Definition at line 6 of file DistordCropUtility.cpp.
References backgroundColor, and threshold_black_color.
Referenced by addPixelToQueue(), findBounds(), and getBounds().
The documentation for this class was generated from the following files:
src/core/imgproc/DistordCropUtility.hpp
src/core/imgproc/DistordCropUtility.cpp