SIBR: sibr::CalibratedCameras Class Reference
sibr::CalibratedCameras Class Reference
sibr_scene
#include <CalibratedCameras.hpp>
Public Types
typedef std::shared_ptr< CalibratedCameras > Ptr
Pointer to the instance of class sibr::CalibratedCameras.
Public Types inherited from sibr::ICalibratedCameras
typedef std::shared_ptr< ICalibratedCameras > Ptr
Pointer to the instance of class sibr::CalibratedCameras.
Public Member Functions
void setupFromData (const IParseData::Ptr &data) override
Creates the calibrated cameras for a scene given data parsed from dataset path.
void setupCamerasFromExisting (const std::vector< InputCamera::Ptr > &cams) override
Assigns the calibrated cameras for a scene to a list of cameras passed as parameter.
void activateCamera (uint camId) override
Function to set a camera as active.
void deactivateCamera (uint camId) override
Function to set a camera as inactive.
void debugFlagCameraAsUsed (const std::vector< uint > &selectedCameras) override
Function to mark the cameras used for rendering.
bool isCameraUsedForRendering (size_t camId) const override
Function to check if the camera is used for rendering.
void usedCameraForRendering (const std::vector< bool > usedCamera) override
Function to set the cameras used for rendering.
const std::vector< InputCamera::Ptr > & inputCameras (void) const override
Getter to the vector of input cameras used to create the scene.
const void updateNearsFars (std::vector< sibr::Vector2f > &nearsFars) override
Protected Attributes
std::vector< InputCamera::Ptr > _inputCameras
std::vector< bool > _usedCameraFlag
Detailed Description
Definition at line 10 of file CalibratedCameras.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<CalibratedCameras> sibr::CalibratedCameras::Ptr
Pointer to the instance of class sibr::CalibratedCameras.
Definition at line 16 of file CalibratedCameras.hpp.
Member Function Documentation
activateCamera()
void sibr::CalibratedCameras::activateCamera (uint camId) inline override virtual
Function to set a camera as active.
Parameters
camId Integer ID of the camera to be set active
Implements sibr::ICalibratedCameras.
Definition at line 95 of file CalibratedCameras.hpp.
References _inputCameras.
deactivateCamera()
void sibr::CalibratedCameras::deactivateCamera (uint camId) inline override virtual
Function to set a camera as inactive.
Parameters
camId Integer ID of the camera to be set inactive
Implements sibr::ICalibratedCameras.
Definition at line 100 of file CalibratedCameras.hpp.
References _inputCameras.
debugFlagCameraAsUsed()
void sibr::CalibratedCameras::debugFlagCameraAsUsed (const std::vector< uint > & selectedCameras) override virtual
Function to mark the cameras used for rendering.
Generally used for debugging purposes
Parameters
selectedCameras list of camera IDs that are used for rendering
Implements sibr::ICalibratedCameras.
Definition at line 13 of file CalibratedCameras.cpp.
References inputCameras(), and usedCameraForRendering().
inputCameras()
const std::vector< InputCamera::Ptr > & sibr::CalibratedCameras::inputCameras (void) const inline override virtual
Getter to the vector of input cameras used to create the scene.
Implements sibr::ICalibratedCameras.
Definition at line 91 of file CalibratedCameras.hpp.
References _inputCameras.
Referenced by debugFlagCameraAsUsed().
isCameraUsedForRendering()
bool sibr::CalibratedCameras::isCameraUsedForRendering (size_t camId) const inline override virtual
Function to check if the camera is used for rendering.
Parameters
camId Integer ID of the cameras to be checked if it is being used for rendering
Returns
true if used for rendering
Implements sibr::ICalibratedCameras.
Definition at line 105 of file CalibratedCameras.hpp.
References _usedCameraFlag.
setupCamerasFromExisting()
void sibr::CalibratedCameras::setupCamerasFromExisting (const std::vector< InputCamera::Ptr > & cams) inline override virtual
Assigns the calibrated cameras for a scene to a list of cameras passed as parameter.
Parameters
cams Vector of type sibr::InputCamera to which the scene inputCameras will be set
Implements sibr::ICalibratedCameras.
Definition at line 86 of file CalibratedCameras.hpp.
References _inputCameras.
setupFromData()
void sibr::CalibratedCameras::setupFromData (const IParseData::Ptr & data) override virtual
Creates the calibrated cameras for a scene given data parsed from dataset path.
Parameters
data Holds all information required to created a set of calibrated cameras
Implements sibr::ICalibratedCameras.
Definition at line 4 of file CalibratedCameras.cpp.
References _inputCameras.
updateNearsFars()
const void sibr::CalibratedCameras::updateNearsFars (std::vector< sibr::Vector2f > & nearsFars) override virtual
Implements sibr::ICalibratedCameras.
Definition at line 23 of file CalibratedCameras.cpp.
References _inputCameras, and SIBR_ERR.
usedCameraForRendering()
void sibr::CalibratedCameras::usedCameraForRendering (const std::vector< bool > usedCamera) inline override virtual
Function to set the cameras used for rendering.
Parameters
usedCamera Vector to specify which cameras are used for rendering
Implements sibr::ICalibratedCameras.
Definition at line 110 of file CalibratedCameras.hpp.
References _usedCameraFlag.
Referenced by debugFlagCameraAsUsed().
Member Data Documentation
_inputCameras
std::vector<InputCamera::Ptr> sibr::CalibratedCameras::_inputCameras protected
Definition at line 79 of file CalibratedCameras.hpp.
Referenced by activateCamera(), deactivateCamera(), inputCameras(), setupCamerasFromExisting(), setupFromData(), and updateNearsFars().
_usedCameraFlag
std::vector<bool> sibr::CalibratedCameras::_usedCameraFlag protected
Definition at line 80 of file CalibratedCameras.hpp.
Referenced by isCameraUsedForRendering(), and usedCameraForRendering().
The documentation for this class was generated from the following files:
src/core/scene/CalibratedCameras.hpp
src/core/scene/CalibratedCameras.cpp