SIBR: sibr::MultiViewInterfaceView Class Reference
sibr::MultiViewInterfaceView Class Reference
#include <Interface.h>
Public Types
enum ViewType { ViewType::IMAGES, ViewType::MESH }
Public Types inherited from sibr::ViewBase
typedef std::shared_ptr< ViewBase > Ptr
Public Member Functions
SIBR_CLASS_PTR (MultiViewInterfaceView)
MultiViewInterfaceView ()
MultiViewInterfaceView (MultiViewInterface *interfacePtr, ViewType type)
virtual void onRenderIBR (IRenderTarget &, const sibr::Camera &)
Render content in a given rendertarget.
virtual void onUpdate (Input &, const sibr::Viewport &viewport)
Update state based on user input.
virtual void onRender (const sibr::Viewport &viewport)
Render content in the currently bound RT, using a specific viewport.
Public Member Functions inherited from sibr::ViewBase
ViewBase (const unsigned int w=720, const unsigned int h=480)
Constructor.
virtual ~ViewBase ()=default
Destructor.
virtual void onUpdate (Input &input)
virtual void onRender (Window &win)
Render content in a window.
virtual void onGUI ()
Display GUI.
virtual void preRender (RenderTargetRGB &prev)
Legacy: Used to mix with previous pass.
virtual void whichRT (uint i)
Legacy: Set the internal RT to use.
virtual uint whichRT (void)
Legacy:
void setResolution (const Vector2i &size)
Set the view resolution.
const Vector2i & getResolution (void) const
void active (bool act)
Toggle view status.
bool active ()
void setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
bool isFocused (void) const
void setName (const std::string &name)
Define the name of the view (used for disambiguation of GUI, etc.).
const std::string & name () const
Public Attributes
PixPos currentActivePos
Protected Attributes
MultiViewInterface * interfacePtr
ViewType viewType
Protected Attributes inherited from sibr::ViewBase
uint _whichRT
Selected RT id.
std::vector< RenderTargetLum::Ptr > _masks
Rendering masks that can beused by some views/renderers.
bool _active = true
Is the view active.
Vector2i _resolution
View resolution.
bool _focus = false
Is the view focused.
std::string _name = ""
View name.
Detailed Description
Definition at line 57 of file Interface.h.
Member Enumeration Documentation
ViewType
enum sibr::MultiViewInterfaceView::ViewType strong
Enumerator
IMAGES
MESH
Definition at line 60 of file Interface.h.
Constructor & Destructor Documentation
MultiViewInterfaceView() [1/2]
sibr::MultiViewInterfaceView::MultiViewInterfaceView () inline
Definition at line 64 of file Interface.h.
MultiViewInterfaceView() [2/2]
sibr::MultiViewInterfaceView::MultiViewInterfaceView (MultiViewInterface * interfacePtr, ViewType type) inline
Definition at line 65 of file Interface.h.
Member Function Documentation
onRender()
void sibr::MultiViewInterfaceView::onRender (const sibr::Viewport & vpRender) virtual
Render content in the currently bound RT, using a specific viewport.
Parameters
vpRender destination viewport
Note
Used when the view is in a multi-view system.
Reimplemented from sibr::ViewBase.
Definition at line 621 of file Interface.cpp.
References sibr::MultiViewInterface::displayMesh(), IMAGES, interfacePtr, MESH, sibr::MultiViewInterface::onGui(), sibr::MultiViewInterface::renderImageView(), and viewType.
onRenderIBR()
virtual void sibr::MultiViewInterfaceView::onRenderIBR (IRenderTarget & dst, const sibr::Camera & eye) inline virtual
Render content in a given rendertarget.
Parameters
dst destination RT
eye current viewpoint
See also
IRenderingMode
Reimplemented from sibr::ViewBase.
Definition at line 67 of file Interface.h.
onUpdate()
void sibr::MultiViewInterfaceView::onUpdate (Input & input, const sibr::Viewport & vp) virtual
Update state based on user input.
Parameters
input user input
vp input viewport
Note
Used when the view is in a multi-view system.
Reimplemented from sibr::ViewBase.
Definition at line 610 of file Interface.cpp.
References IMAGES, interfacePtr, MESH, sibr::MultiViewInterface::updateImageView(), sibr::MultiViewInterface::updateMeshView(), and viewType.
SIBR_CLASS_PTR()
sibr::MultiViewInterfaceView::SIBR_CLASS_PTR (MultiViewInterfaceView)
Member Data Documentation
currentActivePos
PixPos sibr::MultiViewInterfaceView::currentActivePos
Definition at line 72 of file Interface.h.
interfacePtr
MultiViewInterface* sibr::MultiViewInterfaceView::interfacePtr protected
Definition at line 75 of file Interface.h.
Referenced by onRender(), and onUpdate().
viewType
ViewType sibr::MultiViewInterfaceView::viewType protected
Definition at line 76 of file Interface.h.
Referenced by onRender(), and onUpdate().
The documentation for this class was generated from the following files:
src/core/view/interface/Interface.h
src/core/view/interface/Interface.cpp