SIBR: sibr::Ray Class Reference
sibr::Ray Class Reference
sibr_raycaster
Represents a simple ray.
#include <Ray.hpp>
Public Member Functions
Ray (const sibr::Vector3f &orig=sibr::Vector3f(0.f, 0.f, 0.f), const sibr::Vector3f &dir=sibr::Vector3f(0.f, 0.f, -1.f))
Construct a ray from parameters.
void orig (const sibr::Vector3f &o)
Set the position from where the ray starts.
const sibr::Vector3f & orig (void) const
void dir (const sibr::Vector3f &d, bool normalizeIt=true)
Set the direction of the ray.
const sibr::Vector3f & dir (void) const
Vector3f at (float t) const
Return the 3D point such that p = orig + t * dir;.
Private Attributes
sibr::Vector3f _orig
Position from where the ray starts.
sibr::Vector3f _dir
Direction where the ray goes.
Detailed Description
Represents a simple ray.
Definition at line 15 of file Ray.hpp.
Constructor & Destructor Documentation
Ray()
sibr::Ray::Ray (const sibr::Vector3f & orig = sibr::Vector3f(0.f, 0.f, 0.f), const sibr::Vector3f & dir = sibr::Vector3f(0.f, 0.f, -1.f))
Construct a ray from parameters.
Parameters
orig ray origin
dir ray direction
Note
The direction will be normalized.
Definition at line 8 of file Ray.cpp.
References _dir.
Member Function Documentation
at()
Vector3f sibr::Ray::at (float t) const inline
Return the 3D point such that p = orig + t * dir;.
Parameters
t the distance along the ray
Returns
the 3D point
Definition at line 144 of file Ray.hpp.
References dir(), and orig().
Referenced by sibr::DatasetView::onUpdate().
dir() [1/2]
void sibr::Ray::dir (const sibr::Vector3f & d, bool normalizeIt = true) inline
Set the direction of the ray.
Additionally, you can precise if you want this direction to be automatically normalized or not.
Parameters
d the new direction
normalizeIt should normalization be applied
Definition at line 137 of file Ray.hpp.
References _dir.
Referenced by sibr::Raycaster::hitSomething(), sibr::Raycaster::intersect(), sibr::VoxelGridBase::intersectionWithBox(), and sibr::VoxelGridBase::rayMarch().
dir() [2/2]
const sibr::Vector3f & sibr::Ray::dir (void) const inline
Returns
the direction of the ray.
Definition at line 140 of file Ray.hpp.
References _dir.
Referenced by at().
orig() [1/2]
void sibr::Ray::orig (const sibr::Vector3f & o) inline
Set the position from where the ray starts.
Parameters
o the new origin
Definition at line 130 of file Ray.hpp.
References _orig.
Referenced by sibr::Raycaster::hitSomething(), sibr::Raycaster::intersect(), sibr::VoxelGridBase::intersectionWithBox(), and sibr::VoxelGridBase::rayMarch().
orig() [2/2]
const sibr::Vector3f & sibr::Ray::orig (void) const inline
Returns
the ray origin
Definition at line 133 of file Ray.hpp.
References _orig.
Referenced by at().
Member Data Documentation
_dir
sibr::Vector3f sibr::Ray::_dir private
Direction where the ray goes.
Definition at line 53 of file Ray.hpp.
Referenced by dir(), and Ray().
_orig
sibr::Vector3f sibr::Ray::_orig private
Position from where the ray starts.
Definition at line 52 of file Ray.hpp.
Referenced by orig().
The documentation for this class was generated from the following files:
src/core/raycaster/Ray.hpp
src/core/raycaster/Ray.cpp