SIBR: sibr::MeshRenderer Class Reference
sibr::MeshRenderer Class Reference
sibr_view
#include <MeshViewer.h>
Classes
struct MeshData
struct MeshParams
Public Member Functions
MeshRenderer ()
void render (const sibr::Camera &viewproj)
void addMesh (std::shared_ptr< sibr::Mesh > meshPtr, sibr::Mesh::RenderMode mode=sibr::Mesh::FillRenderMode)
void addLines (const std::vector< sibr::Vector3f > &listPoints, const sibr::Vector3f &color)
void addPoint (const sibr::Vector3f &point, const sibr::Vector3f &color)
void addPoints (const std::vector< sibr::Vector3f > &listPoints, const sibr::Vector3f &color)
void cleanPoints ()
void cleanLines ()
void resetLinesAndPoints ()
void resetMeshes ()
std::vector< MeshParams > & getMeshesParams ()
Public Attributes
std::vector< MeshParams > listMeshes
MeshData lines
MeshData points
sibr::Mesh::Ptr specialPoints
sibr::GLShader shaderLines
Static Public Attributes
static const std::string meshVertexShader
static const std::string meshFragmentShader
Private Member Functions
SIBR_CLASS_PTR (MeshRenderer)
void initShaders ()
void updateMeshPoints (void)
void updateMeshLines (void)
Private Attributes
sibr::GLShader shaderMesh
sibr::GLShader shaderPoints
sibr::GLParameter mvpLines
sibr::GLuniform< sibr::Vector3f > lineColor = sibr::Vector3f(1,0,0)
sibr::GLParameter mvpPoints
sibr::GLParameter mvpMesh
sibr::GLParameter forcedColor
sibr::GLParameter light_pos
sibr::GLParameter radiusScreen
Detailed Description
Definition at line 23 of file MeshViewer.h.
Constructor & Destructor Documentation
MeshRenderer()
sibr::MeshRenderer::MeshRenderer ()
Definition at line 45 of file MeshViewer.cpp.
References initShaders(), and resetLinesAndPoints().
Member Function Documentation
addLines()
void sibr::MeshRenderer::addLines (const std::vector< sibr::Vector3f > & listPoints, const sibr::Vector3f & color)
Definition at line 115 of file MeshViewer.cpp.
addMesh()
void sibr::MeshRenderer::addMesh (std::shared_ptr< sibr::Mesh > meshPtr, sibr::Mesh::RenderMode mode = sibr::Mesh::FillRenderMode)
Definition at line 107 of file MeshViewer.cpp.
References sibr::MeshRenderer::MeshParams::mesh, and sibr::MeshRenderer::MeshParams::mode.
addPoint()
void sibr::MeshRenderer::addPoint (const sibr::Vector3f & point, const sibr::Vector3f & color)
Definition at line 127 of file MeshViewer.cpp.
addPoints()
void sibr::MeshRenderer::addPoints (const std::vector< sibr::Vector3f > & listPoints, const sibr::Vector3f & color)
Definition at line 134 of file MeshViewer.cpp.
cleanLines()
void sibr::MeshRenderer::cleanLines ()
Definition at line 153 of file MeshViewer.cpp.
cleanPoints()
void sibr::MeshRenderer::cleanPoints ()
Definition at line 146 of file MeshViewer.cpp.
getMeshesParams()
std::vector<MeshParams>& sibr::MeshRenderer::getMeshesParams () inline
Definition at line 62 of file MeshViewer.h.
initShaders()
void sibr::MeshRenderer::initShaders () private
Definition at line 173 of file MeshViewer.cpp.
Referenced by MeshRenderer().
render()
void sibr::MeshRenderer::render (const sibr::Camera & viewproj)
Definition at line 53 of file MeshViewer.cpp.
References sibr::Mesh::LineRenderMode, sibr::Mesh::PointRenderMode, sibr::Camera::position(), and sibr::Camera::viewproj().
resetLinesAndPoints()
void sibr::MeshRenderer::resetLinesAndPoints ()
Definition at line 160 of file MeshViewer.cpp.
Referenced by MeshRenderer().
resetMeshes()
void sibr::MeshRenderer::resetMeshes ()
Definition at line 168 of file MeshViewer.cpp.
SIBR_CLASS_PTR()
sibr::MeshRenderer::SIBR_CLASS_PTR (MeshRenderer) private
updateMeshLines()
void sibr::MeshRenderer::updateMeshLines (void) private
Definition at line 246 of file MeshViewer.cpp.
updateMeshPoints()
void sibr::MeshRenderer::updateMeshPoints (void) private
Definition at line 231 of file MeshViewer.cpp.
Member Data Documentation
forcedColor
sibr::GLParameter sibr::MeshRenderer::forcedColor private
Definition at line 85 of file MeshViewer.h.
light_pos
sibr::GLParameter sibr::MeshRenderer::light_pos private
Definition at line 87 of file MeshViewer.h.
lineColor
sibr::GLuniform<sibr::Vector3f> sibr::MeshRenderer::lineColor = sibr::Vector3f(1,0,0) private
Definition at line 82 of file MeshViewer.h.
lines
MeshData sibr::MeshRenderer::lines
Definition at line 67 of file MeshViewer.h.
listMeshes
std::vector<MeshParams> sibr::MeshRenderer::listMeshes
Definition at line 65 of file MeshViewer.h.
meshFragmentShader
const std::string sibr::MeshRenderer::meshFragmentShader static
Initial value:
=
"#version 420                                       \n"
"uniform vec3 light_pos;                            \n"
"uniform vec3 forcedColor = vec3(0.7f,0.7f,0.7f);   \n"
"in vec3 color;                                     \n"
"in vec3 normal;                                    \n"
"in vec3 vertex;                                    \n"
"out vec4 out_color;                                \n"
"void main(void) {                                  \n"
"   float kd = 0.3;                                 \n"
"   float ks = 0.2;                                 \n"
"   vec3 L = normalize(light_pos - vertex);                                 \n"
"   vec3 N = normalize(normal);                                     \n"
"   vec3 R = 2.0*dot(L,N)*N - N;                                    \n"
"   vec3 V = L;     //light pos = eye                               \n"
"   vec3 diffuse = max(0.0, dot(L,N))*vec3(1, 1, 1);                \n"
"   vec3 specular = max(0.0, dot(R,V))*vec3(1, 1, 1);               \n"
"   out_color = vec4((1.0 - kd -ks)*forcedColor + kd*diffuse + ks*specular , 1.0);      \n"
"}                                                                                  \n"
Definition at line 72 of file MeshViewer.h.
meshVertexShader
const std::string sibr::MeshRenderer::meshVertexShader static
Initial value:
=
"#version 420                                       \n"
"uniform mat4 MVP;                                  \n"
"layout(location = 0) in vec3 in_vertex;            \n"
"layout(location = 1) in vec3 in_color;             \n"
"layout(location = 3) in vec3 in_normal;            \n"
"out vec3 color;                                    \n"
"out vec3 normal;                                   \n"
"out vec3 vertex;                                   \n"
"void main(void) {                                  \n"
"   color = in_color;                               \n"
"   normal = in_normal;                             \n"
"   vertex = in_vertex;                             \n"
"   gl_Position = MVP * vec4(in_vertex,1.0);        \n"
"}                                                  \n"
Definition at line 71 of file MeshViewer.h.
mvpLines
sibr::GLParameter sibr::MeshRenderer::mvpLines private
Definition at line 81 of file MeshViewer.h.
mvpMesh
sibr::GLParameter sibr::MeshRenderer::mvpMesh private
Definition at line 84 of file MeshViewer.h.
mvpPoints
sibr::GLParameter sibr::MeshRenderer::mvpPoints private
Definition at line 83 of file MeshViewer.h.
points
MeshData sibr::MeshRenderer::points
Definition at line 68 of file MeshViewer.h.
radiusScreen
sibr::GLParameter sibr::MeshRenderer::radiusScreen private
Definition at line 88 of file MeshViewer.h.
shaderLines
sibr::GLShader sibr::MeshRenderer::shaderLines
Definition at line 74 of file MeshViewer.h.
shaderMesh
sibr::GLShader sibr::MeshRenderer::shaderMesh private
Definition at line 78 of file MeshViewer.h.
shaderPoints
sibr::GLShader sibr::MeshRenderer::shaderPoints private
Definition at line 79 of file MeshViewer.h.
specialPoints
sibr::Mesh::Ptr sibr::MeshRenderer::specialPoints
Definition at line 69 of file MeshViewer.h.
The documentation for this class was generated from the following files:
src/core/view/interface/MeshViewer.h
src/core/view/interface/MeshViewer.cpp