SIBR: sibr::RGBDInputTextures Class Reference
sibr::RGBDInputTextures Class Reference
sibr_scene
#include <RenderTargetTextures.hpp>
Public Member Functions
const std::vector< RenderTargetRGBA32F::Ptr > & inputImagesRT () const
virtual void initializeImageRenderTargets (ICalibratedCameras::Ptr cams, IInputImages::Ptr imgs)
virtual void initializeDepthRenderTargets (ICalibratedCameras::Ptr cams, IProxyMesh::Ptr proxies, bool facecull)
Public Member Functions inherited from sibr::RTTextureSize
RTTextureSize (uint w=0)
void initSize (uint w, uint h)
bool isInit () const
Protected Attributes
std::vector< RenderTargetRGBA32F::Ptr > _inputRGBARenderTextures
Protected Attributes inherited from sibr::RTTextureSize
uint _width = 0
uint _height = 0
bool _isInit = false
int _initActiveCam = 0
Detailed Description
Definition at line 41 of file RenderTargetTextures.hpp.
Member Function Documentation
initializeDepthRenderTargets()
void sibr::RGBDInputTextures::initializeDepthRenderTargets (ICalibratedCameras::Ptr cams, IProxyMesh::Ptr proxies, bool facecull) virtual
Definition at line 79 of file RenderTargetTextures.cpp.
References sibr::RTTextureSize::_initActiveCam, _inputRGBARenderTextures, sibr::GLShader::begin(), sibr::GLShader::end(), sibr::GLParameter::init(), sibr::GLShader::init(), sibr::RTTextureSize::initSize(), sibr::Resources::Instance(), sibr::RTTextureSize::isInit(), sibr::loadFile(), and sibr::GLParameter::set().
Referenced by sibr::RenderTargetTextures::initializeDefaultRenderTargets().
initializeImageRenderTargets()
void sibr::RGBDInputTextures::initializeImageRenderTargets (ICalibratedCameras::Ptr cams, IInputImages::Ptr imgs) virtual
Definition at line 39 of file RenderTargetTextures.cpp.
References sibr::RTTextureSize::_height, sibr::RTTextureSize::_initActiveCam, _inputRGBARenderTextures, sibr::RTTextureSize::_width, sibr::GLShader::begin(), sibr::GLShader::end(), sibr::Image< T_Type, T_NumComp >::flipH(), sibr::GLShader::init(), sibr::RTTextureSize::initSize(), sibr::Resources::Instance(), sibr::RTTextureSize::isInit(), sibr::loadFile(), sibr::RenderUtility::renderScreenQuad(), SIBR_GPU_LINEAR_SAMPLING, SIBR_LOG, and SIBR_SCENE_LINEAR_SAMPLING.
Referenced by sibr::RenderTargetTextures::initializeDefaultRenderTargets().
inputImagesRT()
const std::vector< RenderTargetRGBA32F::Ptr > & sibr::RGBDInputTextures::inputImagesRT () const
Definition at line 34 of file RenderTargetTextures.cpp.
References _inputRGBARenderTextures.
Member Data Documentation
_inputRGBARenderTextures
std::vector<RenderTargetRGBA32F::Ptr> sibr::RGBDInputTextures::_inputRGBARenderTextures protected
Definition at line 50 of file RenderTargetTextures.hpp.
Referenced by initializeDepthRenderTargets(), initializeImageRenderTargets(), and inputImagesRT().
The documentation for this class was generated from the following files:
src/core/scene/RenderTargetTextures.hpp
src/core/scene/RenderTargetTextures.cpp