SIBR: sibr::ColorMeshShader Class Reference
sibr::ColorMeshShader Class Reference
sibr_view
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
#include <MultiMeshManager.hpp>
Public Member Functions
virtual void initShader (const std::string &name, const std::string &vert, const std::string &frag, const std::string &geom="")
Initialize the shader.
virtual void setUniforms (const Camera &eye, const MeshData &data)
Public Member Functions inherited from sibr::ShaderAlphaMVP
virtual void render (const Camera &eye, const MeshData &data)
Render using the passed information.
Protected Attributes
GLuniform< Vector3f > user_color
user-defined constant color.
Protected Attributes inherited from sibr::ShaderAlphaMVP
GLShader shader
Base shader object.
GLuniform< Matrix4f > mvp
MVP matrix.
GLuniform< float > alpha = 1.0
Opacity.
Detailed Description
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
Adds a user-defined color.
See also
ShaderAlphaMVP
Definition at line 55 of file MultiMeshManager.hpp.
Member Function Documentation
initShader()
void sibr::ColorMeshShader::initShader (const std::string & name, const std::string & vert, const std::string & frag, const std::string & geom = "") virtual
Initialize the shader.
Parameters
name the shader name
vert the vertex shader content
frag the fragment shader ocntent
geom the geometry shader content
Reimplemented from sibr::ShaderAlphaMVP.
Reimplemented in sibr::NormalRenderingShader, sibr::MeshShadingShader, and sibr::PointShader.
Definition at line 238 of file MultiMeshManager.cpp.
References sibr::GLuniform< T >::init(), sibr::ShaderAlphaMVP::initShader(), sibr::ShaderAlphaMVP::shader, and user_color.
Referenced by sibr::PointShader::initShader(), sibr::MeshShadingShader::initShader(), and sibr::NormalRenderingShader::initShader().
setUniforms()
void sibr::ColorMeshShader::setUniforms (const Camera & eye, const MeshData & data) virtual
Reimplemented from sibr::ShaderAlphaMVP.
Reimplemented in sibr::NormalRenderingShader, sibr::MeshShadingShader, and sibr::PointShader.
Definition at line 244 of file MultiMeshManager.cpp.
References sibr::GLuniform< T >::set(), sibr::ShaderAlphaMVP::setUniforms(), user_color, and sibr::MeshData::userColor.
Referenced by sibr::PointShader::setUniforms(), sibr::MeshShadingShader::setUniforms(), and sibr::NormalRenderingShader::setUniforms().
Member Data Documentation
user_color
GLuniform<Vector3f> sibr::ColorMeshShader::user_color protected
user-defined constant color.
Definition at line 72 of file MultiMeshManager.hpp.
Referenced by initShader(), and setUniforms().
The documentation for this class was generated from the following files:
src/core/view/MultiMeshManager.hpp
src/core/view/MultiMeshManager.cpp