SIBR: sibr::TrackBall Class Reference
sibr::TrackBall Class Reference
sibr_view
Provide a handler to interact using a trackball (based on mouse motions).
#include <TrackBall.h>
Public Member Functions
TrackBall (bool verbose=false)
Constructor.
bool load (std::string &filePath, const Viewport &viewport)
Load a trackball settings from a file on disk.
void save (std::string &filePath) const
Save trackball settings to a file on disk.
void fromCamera (const InputCamera &cam, const Viewport &viewport, const float &radius=100.0f)
Update the trackball pose from a reference camera.
bool fromMesh (const Mesh &mesh, const Viewport &viewport)
Setup the trackball so that a mesh if visible and centered.
bool fromBoundingBox (const Eigen::AlignedBox< float, 3 > &box, const Viewport &viewport)
Setup the trackball so that a region of space if visible and centered.
void update (const Input &input, const Viewport &viewport, std::shared_ptr< Raycaster > raycaster=std::shared_ptr< Raycaster >())
Update the trackball handler state.
void updateAspectWithViewport (const Viewport &viewport)
update the internal aspect ratio.
bool initialized () const
virtual void update (const sibr::Input &input, const float deltaTime, const Viewport &viewport) override
ICameraHandler interface.
virtual const InputCamera & getCamera (void) const override
virtual void onRender (const sibr::Viewport &viewport) override
Render on top of the associated view(s).
Public Member Functions inherited from sibr::ICameraHandler
virtual void onGUI (const std::string &windowName)
Display GUI options and infos.
Public Attributes
bool drawThis
Should the trackball overlay be displayed.
Private Types
enum TrackBallState {
TrackBallState::IDLE, TrackBallState::TRANSLATION_PLANE, TrackBallState::TRANSLATION_Z, TrackBallState::ROTATION_SPHERE,
TrackBallState::ROTATION_ROLL
}
Trackball interaction status.
Private Member Functions
Vector3f mapToSphere (const Vector2i &pos2D, const Viewport &viewport) const
Map a pixel to a point on the sphere.
Vector3f mapTo3Dplane (const Vector2i &pos2D) const
Map a pixel to a point on the plane.
void updateZnearZFar (const Input &input)
update near and far planes.
void updateBallCenter (const Input &input, std::shared_ptr< Raycaster > raycaster)
update the trackball pivot center.
void updateRadius (const Input &input)
Update the trackball radius.
void updateRotationSphere (const Input &input, const Viewport &viewport)
Update the rotation parameters.
void updateRotationRoll (const Input &input, const Viewport &viewport)
Update the rotation parameters.
void updateTranslationPlane (const Input &input, const Viewport &viewport, std::shared_ptr< Raycaster > raycaster=std::shared_ptr< Raycaster >())
Update the translation parameters.
void updateTranslationZ (const Input &input, const Viewport &viewport)
Update the translation parameters.
void updateFromKeyboard (const Input &input)
Update based on keys input.
bool isInTrackBall2dRegion (const Vector2i &pos2D, const Viewport &viewport) const
Check if a point is in the central trackball region.
bool areClockWise (const Vector2f &a, const Vector2f &b, const Vector2f &c) const
Check if three points are in clockwise order.
void printMessage (const std::string &msg) const
Log a message.
void saveVectorInFile (std::ofstream &s, const Vector3f &v) const
Save vector to output stream.
void initTrackBallShader (void)
Setup trackball shader.
void setCameraAttributes (const Viewport &viewport)
Set camera attributes.
void updateTrackBallCameraSize (const Viewport &viewport)
Update camera size.
void updateTrackBallStatus (const Input &input, const Viewport &viewport)
Update trackball interaction status.
void updateTrackBallCamera (const Input &input, const Viewport &viewport, std::shared_ptr< Raycaster > raycaster=std::shared_ptr< Raycaster >())
Main update function.
Private Attributes
InputCamera fixedCamera
Reference camera.
InputCamera tempCamera
Temp camera.
Vector3f fixedCenter
Current center.
Vector3f tempCenter
Temp center.
Vector2i lastPoint2D
Last clicked 2D point.
Vector2i currentPoint2D
Current clicked point.
Eigen::Hyperplane< float, 3 > trackballPlane
Trackball translation plane.
TrackBallState state
Current status.
bool hasBeenInitialized
Initialized or not.
bool verbose
verbose or not.
float zoom =1.0f
std::shared_ptr< Mesh > quadMesh
Supporting mesh for the overlay.
GLShader trackBallShader
Overlay shader.
GLParameter ratioTrackBall2Dgpu
Aspect ratio.
GLParameter trackBallStateGPU
Trackball state uniform.
bool shadersCompiled
Are the sahders ready.
Static Private Attributes
static float ratioTrackBall2D = 0.75f
2D ratio parameter.
Detailed Description
Provide a handler to interact using a trackball (based on mouse motions).
Definition at line 22 of file TrackBall.h.
Member Enumeration Documentation
TrackBallState
enum sibr::TrackBall::TrackBallState strong private
Trackball interaction status.
Enumerator
IDLE
TRANSLATION_PLANE
TRANSLATION_Z
ROTATION_SPHERE
ROTATION_ROLL
Definition at line 98 of file TrackBall.h.
Constructor & Destructor Documentation
TrackBall()
sibr::TrackBall::TrackBall (bool verbose = false)
Constructor.
Parameters
verbose log updates and infos.
Definition at line 13 of file TrackBall.cpp.
References drawThis.
Member Function Documentation
areClockWise()
bool sibr::TrackBall::areClockWise (const Vector2f & a, const Vector2f & b, const Vector2f & c) const private
Check if three points are in clockwise order.
Parameters
a first point
b second point
c third point
Returns
true if their order is clockwise.
Definition at line 545 of file TrackBall.cpp.
Referenced by updateRotationRoll().
fromBoundingBox()
bool sibr::TrackBall::fromBoundingBox (const Eigen::AlignedBox< float, 3 > & box, const Viewport & viewport)
Setup the trackball so that a region of space if visible and centered.
Parameters
box the region of space to cover
viewport the view viewport
Definition at line 166 of file TrackBall.cpp.
References fixedCamera, fixedCenter, hasBeenInitialized, printMessage(), setCameraAttributes(), sibr::Camera::setLookAt(), SIBR_LOG, tempCamera, tempCenter, and sibr::Camera::zfar().
Referenced by fromMesh(), sibr::MultiMeshManager::onUpdate(), and sibr::InteractiveCameraHandler::setup().
fromCamera()
void sibr::TrackBall::fromCamera (const InputCamera & cam, const Viewport & viewport, const float & radius = 100.0f)
Update the trackball pose from a reference camera.
Parameters
cam the reference camera
viewport the viewport to use
radius the default trackball radius to use
Definition at line 144 of file TrackBall.cpp.
References sibr::Camera::dir(), fixedCamera, fixedCenter, hasBeenInitialized, sibr::Camera::position(), setCameraAttributes(), tempCamera, tempCenter, sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::InteractiveCameraHandler::fromCamera().
fromMesh()
bool sibr::TrackBall::fromMesh (const Mesh & mesh, const Viewport & viewport)
Setup the trackball so that a mesh if visible and centered.
Parameters
mesh the mesh to show
viewport the view viewport
Definition at line 161 of file TrackBall.cpp.
References fromBoundingBox(), and sibr::Mesh::getBoundingBox().
Referenced by sibr::MultiMeshManager::MultiMeshManager().
getCamera()
const InputCamera & sibr::TrackBall::getCamera (void) const override virtual
Returns
the current camera.
Implements sibr::ICameraHandler.
Definition at line 23 of file TrackBall.cpp.
References fixedCamera, hasBeenInitialized, IDLE, SIBR_ERR, state, and tempCamera.
Referenced by sibr::MultiMeshManager::MultiMeshManager(), sibr::MultiMeshManager::onUpdate(), sibr::InteractiveCameraHandler::setup(), and sibr::InteractiveCameraHandler::update().
initialized()
bool sibr::TrackBall::initialized () const inline
Returns
true if the trackball has been initialized
Definition at line 77 of file TrackBall.h.
initTrackBallShader()
void sibr::TrackBall::initTrackBallShader (void) private
Setup trackball shader.
Definition at line 554 of file TrackBall.cpp.
References sibr::GLParameter::init(), sibr::GLShader::init(), quadMesh, ratioTrackBall2Dgpu, shadersCompiled, trackBallShader, and trackBallStateGPU.
Referenced by onRender().
isInTrackBall2dRegion()
bool sibr::TrackBall::isInTrackBall2dRegion (const Vector2i & pos2D, const Viewport & viewport) const private
Check if a point is in the central trackball region.
Parameters
pos2D position in the view
viewport view viewport
Returns
true if it falls inside
Definition at line 496 of file TrackBall.cpp.
References sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), lastPoint2D, and ratioTrackBall2D.
Referenced by updateRotationRoll(), updateRotationSphere(), updateTrackBallStatus(), updateTranslationPlane(), and updateTranslationZ().
load()
bool sibr::TrackBall::load (std::string & filePath, const Viewport & viewport)
Load a trackball settings from a file on disk.
Parameters
filePath path to the file
viewport current viewport
Returns
a success boolean
Note
The viewport is needed to fill-in missing info.
Definition at line 88 of file TrackBall.cpp.
References fixedCamera, fixedCenter, sibr::Camera::fovy(), hasBeenInitialized, printMessage(), setCameraAttributes(), sibr::Camera::setLookAt(), tempCamera, tempCenter, sibr::Camera::zfar(), and sibr::Camera::znear().
mapTo3Dplane()
Vector3f sibr::TrackBall::mapTo3Dplane (const Vector2i & pos2D) const private
Map a pixel to a point on the plane.
Parameters
pos2D pixel position
Returns
a 3D point on the plane
Definition at line 525 of file TrackBall.cpp.
References sibr::CameraRaycaster::computeRayDir(), sibr::Camera::dir(), fixedCamera, sibr::InputCamera::h(), ibr_convert_old_to_new::line, sibr::Camera::ortho(), sibr::Camera::orthoRight(), sibr::Camera::orthoTop(), sibr::Camera::position(), sibr::Camera::right(), trackballPlane, sibr::Camera::up(), and sibr::InputCamera::w().
Referenced by updateTranslationPlane().
mapToSphere()
Vector3f sibr::TrackBall::mapToSphere (const Vector2i & pos2D, const Viewport & viewport) const private
Map a pixel to a point on the sphere.
Parameters
pos2D pixel position
viewport view viewport
Returns
a 3D point on the sphere
Definition at line 505 of file TrackBall.cpp.
References sibr::Viewport::finalBottom(), sibr::Viewport::finalHeight(), sibr::Viewport::finalLeft(), sibr::Viewport::finalRight(), sibr::Viewport::finalTop(), and sibr::Viewport::finalWidth().
Referenced by updateRotationSphere().
onRender()
void sibr::TrackBall::onRender (const sibr::Viewport & viewport) override virtual
Render on top of the associated view(s).
Parameters
viewport the rendering region
Reimplemented from sibr::ICameraHandler.
Definition at line 37 of file TrackBall.cpp.
References sibr::GLShader::begin(), sibr::Viewport::bind(), drawThis, sibr::GLShader::end(), IDLE, initTrackBallShader(), quadMesh, ratioTrackBall2D, ratioTrackBall2Dgpu, sibr::GLParameter::set(), shadersCompiled, state, trackBallShader, and trackBallStateGPU.
Referenced by sibr::InteractiveCameraHandler::onRender().
printMessage()
void sibr::TrackBall::printMessage (const std::string & msg) const private
Log a message.
Parameters
msg essage string
Definition at line 623 of file TrackBall.cpp.
References verbose.
Referenced by fromBoundingBox(), load(), updateBallCenter(), updateTrackBallStatus(), and updateZnearZFar().
save()
void sibr::TrackBall::save (std::string & filePath) const
Save trackball settings to a file on disk.
Parameters
filePath file path
Definition at line 120 of file TrackBall.cpp.
References fixedCamera, fixedCenter, sibr::Camera::fovy(), sibr::Camera::position(), saveVectorInFile(), SIBR_LOG, sibr::Camera::up(), sibr::Camera::zfar(), and sibr::Camera::znear().
saveVectorInFile()
void sibr::TrackBall::saveVectorInFile (std::ofstream & s, const Vector3f & v) const private
Save vector to output stream.
Parameters
s stream
v vector
Definition at line 72 of file TrackBall.cpp.
Referenced by save().
setCameraAttributes()
void sibr::TrackBall::setCameraAttributes (const Viewport & viewport) private
Set camera attributes.
Parameters
viewport the viewport to use
Definition at line 76 of file TrackBall.cpp.
References sibr::Camera::aspect(), sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), fixedCamera, and sibr::InputCamera::size().
Referenced by fromBoundingBox(), fromCamera(), and load().
update() [1/2]
void sibr::TrackBall::update (const Input & input, const Viewport & viewport, std::shared_ptr< Raycaster > raycaster = std::shared_ptr<Raycaster>())
Update the trackball handler state.
the raycaster is used when the user is clicking to center the trackball or panning.
Parameters
input user input
viewport view viewport
raycaster an optional raycaster
Definition at line 189 of file TrackBall.cpp.
References sibr::Input::empty(), hasBeenInitialized, updateFromKeyboard(), updateTrackBallCamera(), updateTrackBallCameraSize(), and updateTrackBallStatus().
Referenced by update(), and sibr::InteractiveCameraHandler::update().
update() [2/2]
void sibr::TrackBall::update (const sibr::Input & input, const float deltaTime, const Viewport & viewport) override virtual
ICameraHandler interface.
Update the camera handler state.
Parameters
input user input
deltaTime time elapsed since last udpate
viewport view viewport
Implements sibr::ICameraHandler.
Definition at line 19 of file TrackBall.cpp.
References update().
updateAspectWithViewport()
void sibr::TrackBall::updateAspectWithViewport (const Viewport & viewport)
update the internal aspect ratio.
Parameters
viewport the new viewport
Definition at line 202 of file TrackBall.cpp.
References sibr::Camera::aspect(), sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), fixedCamera, and sibr::InputCamera::size().
updateBallCenter()
void sibr::TrackBall::updateBallCenter (const Input & input, std::shared_ptr< Raycaster > raycaster) private
update the trackball pivot center.
Parameters
input user input
raycaster the scene raycaster
Definition at line 280 of file TrackBall.cpp.
References sibr::CameraRaycaster::computeRayDir(), sibr::Camera::dir(), sibr::RayHit::dist(), fixedCamera, fixedCenter, sibr::InputCamera::h(), sibr::RayHit::hitSomething(), sibr::InputState< TNbState, TEnum >::isPressed(), sibr::Mouse::Left, sibr::Input::mouseButton(), sibr::Input::mousePosition(), sibr::Camera::ortho(), sibr::Camera::orthoRight(), sibr::Camera::orthoTop(), sibr::Camera::position(), printMessage(), sibr::Camera::right(), sibr::Camera::setLookAt(), tempCenter, sibr::Camera::up(), and sibr::InputCamera::w().
Referenced by updateTrackBallCamera().
updateFromKeyboard()
void sibr::TrackBall::updateFromKeyboard (const Input & input) private
Update based on keys input.
Parameters
input user input
Definition at line 408 of file TrackBall.cpp.
References sibr::Camera::dir(), fixedCamera, fixedCenter, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Input::key(), sibr::Key::KPNum2, sibr::Key::KPNum4, sibr::Key::KPNum6, sibr::Key::KPNum7, sibr::Key::KPNum8, sibr::Key::KPNum9, sibr::Camera::position(), sibr::Camera::right(), sibr::Camera::setLookAt(), sibr::Camera::up(), sibr::Key::X, sibr::Key::Y, and sibr::Key::Z.
Referenced by update().
updateRadius()
void sibr::TrackBall::updateRadius (const Input & input) private
Update the trackball radius.
Parameters
input user input
Definition at line 461 of file TrackBall.cpp.
References sibr::Camera::dir(), fixedCamera, fixedCenter, sibr::InputState< TNbState, TEnum >::getNumActivated(), sibr::Input::key(), sibr::Input::mouseScroll(), sibr::Camera::ortho(), sibr::Camera::orthoRight(), sibr::Camera::orthoTop(), sibr::Camera::position(), sibr::Camera::setLookAt(), sibr::Camera::up(), and zoom.
Referenced by updateTrackBallCamera().
updateRotationRoll()
void sibr::TrackBall::updateRotationRoll (const Input & input, const Viewport & viewport) private
Update the rotation parameters.
Parameters
input user input
viewport view viewport
Definition at line 338 of file TrackBall.cpp.
References areClockWise(), sibr::Camera::dir(), sibr::Viewport::finalBottom(), sibr::Viewport::finalHeight(), sibr::Viewport::finalLeft(), sibr::Viewport::finalRight(), sibr::Viewport::finalTop(), sibr::Viewport::finalWidth(), fixedCamera, fixedCenter, isInTrackBall2dRegion(), lastPoint2D, sibr::Input::mousePosition(), sibr::Camera::position(), sibr::Camera::setLookAt(), tempCamera, and sibr::Camera::up().
Referenced by updateTrackBallCamera().
updateRotationSphere()
void sibr::TrackBall::updateRotationSphere (const Input & input, const Viewport & viewport) private
Update the rotation parameters.
Parameters
input user input
viewport view viewport
Definition at line 315 of file TrackBall.cpp.
References sibr::Camera::dir(), fixedCamera, fixedCenter, isInTrackBall2dRegion(), lastPoint2D, mapToSphere(), sibr::Input::mousePosition(), sibr::Camera::position(), sibr::Camera::setLookAt(), tempCamera, sibr::Camera::up(), and sibr::Camera::view().
Referenced by updateTrackBallCamera().
updateTrackBallCamera()
void sibr::TrackBall::updateTrackBallCamera (const Input & input, const Viewport & viewport, std::shared_ptr< Raycaster > raycaster = std::shared_ptr<Raycaster>()) private
Main update function.
Parameters
input user input
viewport the viewport to use
raycaster optional scene raycaster
Definition at line 255 of file TrackBall.cpp.
References IDLE, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Input::key(), sibr::Key::LeftControl, sibr::Input::mouseScroll(), ROTATION_ROLL, ROTATION_SPHERE, state, TRANSLATION_PLANE, TRANSLATION_Z, updateBallCenter(), updateRadius(), updateRotationRoll(), updateRotationSphere(), updateTranslationPlane(), updateTranslationZ(), and updateZnearZFar().
Referenced by update().
updateTrackBallCameraSize()
void sibr::TrackBall::updateTrackBallCameraSize (const Viewport & viewport) private
Update camera size.
Parameters
viewport the viewport to use
Definition at line 82 of file TrackBall.cpp.
References sibr::Viewport::finalSize(), fixedCamera, and sibr::InputCamera::size().
Referenced by update().
updateTrackBallStatus()
void sibr::TrackBall::updateTrackBallStatus (const Input & input, const Viewport & viewport) private
Update trackball interaction status.
Parameters
input user input
viewport the viewport to use
Definition at line 208 of file TrackBall.cpp.
References currentPoint2D, fixedCamera, fixedCenter, IDLE, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::InputState< TNbState, TEnum >::isActivatedOnly(), isInTrackBall2dRegion(), sibr::InputState< TNbState, TEnum >::isPressed(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Input::key(), lastPoint2D, sibr::Mouse::Left, sibr::Key::LeftControl, sibr::Input::mouseButton(), sibr::Input::mousePosition(), printMessage(), sibr::Mouse::Right, ROTATION_ROLL, ROTATION_SPHERE, SIBR_LOG, state, sibr::Key::T, tempCamera, tempCenter, TRANSLATION_PLANE, TRANSLATION_Z, sibr::Key::V, and verbose.
Referenced by update().
updateTranslationPlane()
void sibr::TrackBall::updateTranslationPlane (const Input & input, const Viewport & viewport, std::shared_ptr< Raycaster > raycaster = std::shared_ptr<Raycaster>()) private
Update the translation parameters.
Parameters
input user input
viewport view viewport
raycaster optional scene raycaster
Definition at line 353 of file TrackBall.cpp.
References sibr::CameraRaycaster::computeRayDir(), sibr::Camera::dir(), sibr::RayHit::dist(), fixedCamera, fixedCenter, sibr::InputCamera::h(), sibr::RayHit::hitSomething(), isInTrackBall2dRegion(), sibr::InputState< TNbState, TEnum >::isPressed(), lastPoint2D, mapTo3Dplane(), sibr::Input::mouseButton(), sibr::Input::mousePosition(), sibr::Camera::ortho(), sibr::Camera::orthoRight(), sibr::Camera::orthoTop(), sibr::Camera::position(), sibr::Camera::right(), sibr::Mouse::Right, sibr::Camera::setLookAt(), tempCamera, tempCenter, trackballPlane, sibr::Camera::up(), sibr::InputCamera::w(), and zoom.
Referenced by updateTrackBallCamera().
updateTranslationZ()
void sibr::TrackBall::updateTranslationZ (const Input & input, const Viewport & viewport) private
Update the translation parameters.
Parameters
input user input
viewport view viewport
Definition at line 392 of file TrackBall.cpp.
References sibr::Camera::dir(), sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), fixedCamera, fixedCenter, isInTrackBall2dRegion(), lastPoint2D, sibr::Input::mousePosition(), sibr::Camera::position(), sibr::Camera::setLookAt(), tempCamera, tempCenter, sibr::Camera::up(), and zoom.
Referenced by updateTrackBallCamera().
updateZnearZFar()
void sibr::TrackBall::updateZnearZFar (const Input & input) private
update near and far planes.
Parameters
input user input
Definition at line 481 of file TrackBall.cpp.
References fixedCamera, sibr::InputState< TNbState, TEnum >::isActivatedOnly(), sibr::Input::key(), sibr::Key::LeftShift, sibr::Input::mouseScroll(), printMessage(), tempCamera, sibr::Key::Z, sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by updateTrackBallCamera().
Member Data Documentation
currentPoint2D
Vector2i sibr::TrackBall::currentPoint2D private
Current clicked point.
Definition at line 221 of file TrackBall.h.
Referenced by updateTrackBallStatus().
drawThis
bool sibr::TrackBall::drawThis
Should the trackball overlay be displayed.
Definition at line 74 of file TrackBall.h.
Referenced by sibr::InteractiveCameraHandler::onGUI(), onRender(), TrackBall(), and sibr::InteractiveCameraHandler::update().
fixedCamera
InputCamera sibr::TrackBall::fixedCamera private
Reference camera.
Definition at line 214 of file TrackBall.h.
Referenced by fromBoundingBox(), fromCamera(), getCamera(), load(), mapTo3Dplane(), save(), setCameraAttributes(), updateAspectWithViewport(), updateBallCenter(), updateFromKeyboard(), updateRadius(), updateRotationRoll(), updateRotationSphere(), updateTrackBallCameraSize(), updateTrackBallStatus(), updateTranslationPlane(), updateTranslationZ(), and updateZnearZFar().
fixedCenter
Vector3f sibr::TrackBall::fixedCenter private
Current center.
Definition at line 217 of file TrackBall.h.
Referenced by fromBoundingBox(), fromCamera(), load(), save(), updateBallCenter(), updateFromKeyboard(), updateRadius(), updateRotationRoll(), updateRotationSphere(), updateTrackBallStatus(), updateTranslationPlane(), and updateTranslationZ().
hasBeenInitialized
bool sibr::TrackBall::hasBeenInitialized private
Initialized or not.
Definition at line 227 of file TrackBall.h.
Referenced by fromBoundingBox(), fromCamera(), getCamera(), load(), and update().
lastPoint2D
Vector2i sibr::TrackBall::lastPoint2D private
Last clicked 2D point.
Definition at line 220 of file TrackBall.h.
Referenced by isInTrackBall2dRegion(), updateRotationRoll(), updateRotationSphere(), updateTrackBallStatus(), updateTranslationPlane(), and updateTranslationZ().
quadMesh
std::shared_ptr<Mesh> sibr::TrackBall::quadMesh private
Supporting mesh for the overlay.
Definition at line 232 of file TrackBall.h.
Referenced by initTrackBallShader(), and onRender().
ratioTrackBall2D
float sibr::TrackBall::ratioTrackBall2D = 0.75f static private
2D ratio parameter.
Definition at line 237 of file TrackBall.h.
Referenced by isInTrackBall2dRegion(), and onRender().
ratioTrackBall2Dgpu
GLParameter sibr::TrackBall::ratioTrackBall2Dgpu private
Aspect ratio.
Definition at line 234 of file TrackBall.h.
Referenced by initTrackBallShader(), and onRender().
shadersCompiled
bool sibr::TrackBall::shadersCompiled private
Are the sahders ready.
Definition at line 236 of file TrackBall.h.
Referenced by initTrackBallShader(), and onRender().
state
TrackBallState sibr::TrackBall::state private
Current status.
Definition at line 225 of file TrackBall.h.
Referenced by getCamera(), onRender(), updateTrackBallCamera(), and updateTrackBallStatus().
tempCamera
InputCamera sibr::TrackBall::tempCamera private
Temp camera.
Definition at line 215 of file TrackBall.h.
Referenced by fromBoundingBox(), fromCamera(), getCamera(), load(), updateRotationRoll(), updateRotationSphere(), updateTrackBallStatus(), updateTranslationPlane(), updateTranslationZ(), and updateZnearZFar().
tempCenter
Vector3f sibr::TrackBall::tempCenter private
Temp center.
Definition at line 218 of file TrackBall.h.
Referenced by fromBoundingBox(), fromCamera(), load(), updateBallCenter(), updateTrackBallStatus(), updateTranslationPlane(), and updateTranslationZ().
trackballPlane
Eigen::Hyperplane<float,3> sibr::TrackBall::trackballPlane private
Trackball translation plane.
Definition at line 223 of file TrackBall.h.
Referenced by mapTo3Dplane(), and updateTranslationPlane().
trackBallShader
GLShader sibr::TrackBall::trackBallShader private
Overlay shader.
Definition at line 233 of file TrackBall.h.
Referenced by initTrackBallShader(), and onRender().
trackBallStateGPU
GLParameter sibr::TrackBall::trackBallStateGPU private
Trackball state uniform.
Definition at line 235 of file TrackBall.h.
Referenced by initTrackBallShader(), and onRender().
verbose
bool sibr::TrackBall::verbose private
verbose or not.
Definition at line 228 of file TrackBall.h.
Referenced by printMessage(), and updateTrackBallStatus().
zoom
float sibr::TrackBall::zoom =1.0f private
Definition at line 230 of file TrackBall.h.
Referenced by updateRadius(), updateTranslationPlane(), and updateTranslationZ().
The documentation for this class was generated from the following files:
src/core/view/TrackBall.h
src/core/view/TrackBall.cpp