SIBR: sibr::ShadowMapRenderer Class Reference
sibr::ShadowMapRenderer Class Reference
sibr_renderer
Render high quality soft shadows, designed to mimick the sun shadowing.
#include <ShadowMapRenderer.hpp>
Public Member Functions
ShadowMapRenderer (const sibr::InputCamera &depthMapCam, std::shared_ptr< sibr::RenderTargetLum32F > depthMap_RT)
Constructor.
~ShadowMapRenderer ()
Destructor.
void render (int w, int h, const sibr::InputCamera &cam, const Mesh &mesh, float bias=0.0005f)
Render soft sun shadows on the mesh, using the precomputed depth map.
Public Attributes
std::shared_ptr< sibr::RenderTargetLum > _shadowMap_RT
Result containing the soft shadows.
std::shared_ptr< sibr::RenderTargetLum32F > _depthMap_RT
Depth map rendered from the light viewpoint.
Private Attributes
sibr::GLShader _shadowMapShader
Shadow rendering.
sibr::GLParameter _shadowMapShader_MVP
Final MVP uniform.
sibr::GLParameter _depthMap_MVP
Light MVP uniform.
sibr::GLParameter _depthMap_MVPinv
Light inverse MVP uniform.
sibr::GLParameter _depthMap_radius
Depth map radius.
sibr::GLParameter _lightDir
Light direction uniform.
sibr::GLParameter _bias_control
Bias uniform.
sibr::GLParameter _sun_app_radius
Sun radius (for soft shadows).
std::shared_ptr< sibr::Texture2DLum32F > _textureDepthMap
Shadow map target (unused).
Detailed Description
Render high quality soft shadows, designed to mimick the sun shadowing.
Note
Soft shadowing require a lot of texture fetches that can impact performances.
Definition at line 21 of file ShadowMapRenderer.hpp.
Constructor & Destructor Documentation
ShadowMapRenderer()
sibr::ShadowMapRenderer::ShadowMapRenderer (const sibr::InputCamera & depthMapCam, std::shared_ptr< sibr::RenderTargetLum32F > depthMap_RT)
Constructor.
Parameters
depthMapCam the light viewpoint
depthMap_RT depth map rendered from the light viewpoint
Definition at line 11 of file ShadowMapRenderer.cpp.
References _bias_control, _depthMap_MVP, _depthMap_MVPinv, _depthMap_radius, _lightDir, _shadowMapShader, _shadowMapShader_MVP, _sun_app_radius, sibr::GLShader::begin(), sibr::Camera::dir(), sibr::GLShader::end(), sibr::GLParameter::init(), sibr::GLShader::init(), sibr::Resources::Instance(), sibr::Camera::invViewproj(), sibr::loadFile(), sibr::Camera::orthoRight(), sibr::GLParameter::set(), SUN_APP_DIAM, and sibr::Camera::viewproj().
~ShadowMapRenderer()
sibr::ShadowMapRenderer::~ShadowMapRenderer ()
Destructor.
Definition at line 9 of file ShadowMapRenderer.cpp.
Member Function Documentation
render()
void sibr::ShadowMapRenderer::render (int w, int h, const sibr::InputCamera & cam, const Mesh & mesh, float bias = 0.0005f)
Render soft sun shadows on the mesh, using the precomputed depth map.
Parameters
w the target width
h the target height
cam the viewpoint to use
mesh the mesh to render
bias shadow acne bias
Definition at line 35 of file ShadowMapRenderer.cpp.
References _bias_control, _depthMap_RT, _shadowMap_RT, _shadowMapShader, _shadowMapShader_MVP, sibr::GLShader::begin(), sibr::GLShader::end(), sibr::Mesh::FillRenderMode, sibr::Mesh::render(), sibr::GLParameter::set(), and sibr::Camera::viewproj().
Member Data Documentation
_bias_control
sibr::GLParameter sibr::ShadowMapRenderer::_bias_control private
Bias uniform.
Definition at line 58 of file ShadowMapRenderer.hpp.
Referenced by render(), and ShadowMapRenderer().
_depthMap_MVP
sibr::GLParameter sibr::ShadowMapRenderer::_depthMap_MVP private
Light MVP uniform.
Definition at line 54 of file ShadowMapRenderer.hpp.
Referenced by ShadowMapRenderer().
_depthMap_MVPinv
sibr::GLParameter sibr::ShadowMapRenderer::_depthMap_MVPinv private
Light inverse MVP uniform.
Definition at line 55 of file ShadowMapRenderer.hpp.
Referenced by ShadowMapRenderer().
_depthMap_radius
sibr::GLParameter sibr::ShadowMapRenderer::_depthMap_radius private
Depth map radius.
Definition at line 56 of file ShadowMapRenderer.hpp.
Referenced by ShadowMapRenderer().
_depthMap_RT
std::shared_ptr<sibr::RenderTargetLum32F> sibr::ShadowMapRenderer::_depthMap_RT
Depth map rendered from the light viewpoint.
Definition at line 47 of file ShadowMapRenderer.hpp.
Referenced by render().
_lightDir
sibr::GLParameter sibr::ShadowMapRenderer::_lightDir private
Light direction uniform.
Definition at line 57 of file ShadowMapRenderer.hpp.
Referenced by ShadowMapRenderer().
_shadowMap_RT
std::shared_ptr<sibr::RenderTargetLum> sibr::ShadowMapRenderer::_shadowMap_RT
Result containing the soft shadows.
Definition at line 45 of file ShadowMapRenderer.hpp.
Referenced by render().
_shadowMapShader
sibr::GLShader sibr::ShadowMapRenderer::_shadowMapShader private
Shadow rendering.
Definition at line 52 of file ShadowMapRenderer.hpp.
Referenced by render(), and ShadowMapRenderer().
_shadowMapShader_MVP
sibr::GLParameter sibr::ShadowMapRenderer::_shadowMapShader_MVP private
Final MVP uniform.
Definition at line 53 of file ShadowMapRenderer.hpp.
Referenced by render(), and ShadowMapRenderer().
_sun_app_radius
sibr::GLParameter sibr::ShadowMapRenderer::_sun_app_radius private
Sun radius (for soft shadows).
Definition at line 59 of file ShadowMapRenderer.hpp.
Referenced by ShadowMapRenderer().
_textureDepthMap
std::shared_ptr<sibr::Texture2DLum32F> sibr::ShadowMapRenderer::_textureDepthMap private
Shadow map target (unused).
Definition at line 60 of file ShadowMapRenderer.hpp.
The documentation for this class was generated from the following files:
src/core/renderer/ShadowMapRenderer.hpp
src/core/renderer/ShadowMapRenderer.cpp