SIBR: sibr::DepthRenderer Class Reference
sibr::DepthRenderer Class Reference
sibr_renderer
Render a mesh to a depth rendertarget.
#include <DepthRenderer.hpp>
Public Types
using Ptr = std::shared_ptr< DepthRenderer >
Public Member Functions
DepthRenderer (int w, int h)
Constructor with a target size.
~DepthRenderer ()
Destructor.
void render (const sibr::InputCamera &cam, const Mesh &mesh, bool backFaceCulling=false, bool frontFaceCulling=false)
Render a mesh depth in the result rendertarget.
Public Attributes
std::shared_ptr< sibr::RenderTargetLum32F > _depth_RT
The result depth rendertarget.
Private Attributes
sibr::GLShader _depthShader
Depth shader.
sibr::GLParameter _depthShader_MVP
Shader MVP.
Detailed Description
Render a mesh to a depth rendertarget.
Definition at line 19 of file DepthRenderer.hpp.
Member Typedef Documentation
Ptr
using sibr::DepthRenderer::Ptr = std::shared_ptr<DepthRenderer>
Definition at line 24 of file DepthRenderer.hpp.
Constructor & Destructor Documentation
DepthRenderer()
sibr::DepthRenderer::DepthRenderer (int w, int h)
Constructor with a target size.
Parameters
w target width
h target height
Definition at line 10 of file DepthRenderer.cpp.
References _depth_RT, _depthShader, _depthShader_MVP, sibr::GLParameter::init(), sibr::GLShader::init(), sibr::Resources::Instance(), and sibr::loadFile().
~DepthRenderer()
sibr::DepthRenderer::~DepthRenderer ()
Destructor.
Definition at line 8 of file DepthRenderer.cpp.
Member Function Documentation
render()
void sibr::DepthRenderer::render (const sibr::InputCamera & cam, const Mesh & mesh, bool backFaceCulling = false, bool frontFaceCulling = false)
Render a mesh depth in the result rendertarget.
Parameters
cam the viewpoint to use
mesh the mesh to render
backFaceCulling should perform backface culling
frontFaceCulling flip culling test orientation
Definition at line 21 of file DepthRenderer.cpp.
References _depth_RT, _depthShader, _depthShader_MVP, sibr::GLShader::begin(), sibr::GLShader::end(), sibr::Mesh::FillRenderMode, sibr::Mesh::render(), sibr::GLParameter::set(), and sibr::Camera::viewproj().
Referenced by legacyV2main(), and main().
Member Data Documentation
_depth_RT
std::shared_ptr<sibr::RenderTargetLum32F> sibr::DepthRenderer::_depth_RT
The result depth rendertarget.
Definition at line 43 of file DepthRenderer.hpp.
Referenced by DepthRenderer(), legacyV2main(), main(), and render().
_depthShader
sibr::GLShader sibr::DepthRenderer::_depthShader private
Depth shader.
Definition at line 47 of file DepthRenderer.hpp.
Referenced by DepthRenderer(), and render().
_depthShader_MVP
sibr::GLParameter sibr::DepthRenderer::_depthShader_MVP private
Shader MVP.
Definition at line 48 of file DepthRenderer.hpp.
Referenced by DepthRenderer(), and render().
The documentation for this class was generated from the following files:
src/core/renderer/DepthRenderer.hpp
src/core/renderer/DepthRenderer.cpp