SIBR: sibr::Texture2D< T_Type, T_NumComp > Class Template Reference
sibr::Texture2D< T_Type, T_NumComp > Class Template Reference
sibr_graphics
Represent a 2D texture on the GPU, with custom format and type.
#include <Texture.hpp>
Public Types
typedef Image< T_Type, T_NumComp > PixelImage
typedef PixelImage::Pixel PixelFormat
typedef std::shared_ptr< Texture2D< T_Type, T_NumComp > > Ptr
typedef std::unique_ptr< Texture2D< T_Type, T_NumComp > > UPtr
Public Types inherited from sibr::ITexture2D
typedef std::shared_ptr< ITexture2D > Ptr
typedef std::unique_ptr< ITexture2D > UPtr
Public Member Functions
Texture2D (void)
Constructor.
template<typename ImageType >
Texture2D (const ImageType &img, uint flags=0)
Constructor from an image.
Texture2D (const std::vector< PixelImage > &miparray, uint flags=0)
Constructor from a list of images, one for each mip level.
~Texture2D (void)
Destructor.
GLuint handle (void) const
uint w (void) const
uint h (void) const
sibr::Image< T_Type, T_NumComp > readBack (void) const
template<typename ImageType >
void update (const ImageType &img)
Update the content of the txeture with a new image.
void mipmap (int maxLOD=-1)
Trigger an update of the mipmaps for level 0 to maxLOD.
Public Member Functions inherited from sibr::ITexture2D
virtual ~ITexture2D (void)
Destructor.
Private Member Functions
SIBR_DISALLOW_COPY (Texture2D)
Static Private Member Functions
template<typename ImageType >
static GLuint create2D (const ImageType &array, uint flags)
Create 2D texture from a generic image (sibr::image or cv::Mat).
static GLuint create2D (const std::vector< PixelImage > &miparray, uint flags)
Create 2D texture with custom mipmaps from a list of generic images (sibr::image or cv::Mat).
template<typename ImageType >
static void send2D (GLuint id, const ImageType &array, uint flags)
Send the CPU image data to the GPU.
static void send2Dmipmap (GLuint id, const std::vector< PixelImage > &miparray, uint flags)
Send the CPU images data for each mipmap to the GPU.
Private Attributes
GLuint m_Handle = 0
Texture handle.
uint m_W = 0
Texture width.
uint m_H = 0
Texture height.
uint m_Flags = 0
Options.
bool m_autoMIPMAP = false
Should the mipmaps be generated automatically.
Detailed Description
template<typename T_Type, unsigned int T_NumComp>
class sibr::Texture2D< T_Type, T_NumComp >
Represent a 2D texture on the GPU, with custom format and type.
See also
ITexture2D
Definition at line 43 of file Texture.hpp.
Member Typedef Documentation
PixelFormat
template<typename T_Type , unsigned int T_NumComp> typedef PixelImage::Pixel sibr::Texture2D< T_Type, T_NumComp >::PixelFormat
Definition at line 47 of file Texture.hpp.
PixelImage
template<typename T_Type , unsigned int T_NumComp> typedef Image<T_Type, T_NumComp> sibr::Texture2D< T_Type, T_NumComp >::PixelImage
Definition at line 46 of file Texture.hpp.
Ptr
template<typename T_Type , unsigned int T_NumComp> typedef std::shared_ptr<Texture2D<T_Type, T_NumComp> > sibr::Texture2D< T_Type, T_NumComp >::Ptr
Definition at line 48 of file Texture.hpp.
UPtr
template<typename T_Type , unsigned int T_NumComp> typedef std::unique_ptr<Texture2D<T_Type, T_NumComp> > sibr::Texture2D< T_Type, T_NumComp >::UPtr
Definition at line 49 of file Texture.hpp.
Constructor & Destructor Documentation
Texture2D() [1/3]
template<typename T_Type , unsigned int T_NumComp> sibr::Texture2D< T_Type, T_NumComp >::Texture2D (void)
Constructor.
Definition at line 814 of file Texture.hpp.
Texture2D() [2/3]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > sibr::Texture2D< T_Type, T_NumComp >::Texture2D (const ImageType & img, uint flags = 0)
Constructor from an image.
Parameters
img the image to upload to the GPU
flags options
Definition at line 823 of file Texture.hpp.
References SIBR_GPU_AUTOGEN_MIPMAP.
Texture2D() [3/3]
template<typename T_Type , unsigned int T_NumComp> sibr::Texture2D< T_Type, T_NumComp >::Texture2D (const std::vector< PixelImage > & miparray, uint flags = 0)
Constructor from a list of images, one for each mip level.
Parameters
miparray the images to upload to the GPU
flags options
Definition at line 833 of file Texture.hpp.
~Texture2D()
template<typename T_Type , unsigned int T_NumComp> sibr::Texture2D< T_Type, T_NumComp >::~Texture2D (void)
Destructor.
Definition at line 842 of file Texture.hpp.
References CHECK_GL_ERROR.
Member Function Documentation
create2D() [1/2]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > GLuint sibr::Texture2D< T_Type, T_NumComp >::create2D (const ImageType & array, uint flags) static private
Create 2D texture from a generic image (sibr::image or cv::Mat).
Parameters
array the image
flags options
Returns
the handle of the texture
Definition at line 678 of file Texture.hpp.
References CHECK_GL_ERROR, SIBR_CLAMP_TO_BORDER, SIBR_CLAMP_UVS, SIBR_GPU_AUTOGEN_MIPMAP, SIBR_GPU_INTEGER, and SIBR_GPU_LINEAR_SAMPLING.
create2D() [2/2]
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::Texture2D< T_Type, T_NumComp >::create2D (const std::vector< PixelImage > & miparray, uint flags) static private
Create 2D texture with custom mipmaps from a list of generic images (sibr::image or cv::Mat).
Parameters
miparray the images
flags options
Returns
the handle of the texture
Definition at line 719 of file Texture.hpp.
References CHECK_GL_ERROR, SIBR_CLAMP_TO_BORDER, and SIBR_CLAMP_UVS.
h()
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2D< T_Type, T_NumComp >::h (void) const virtual
Returns
the texture height.
Implements sibr::ITexture2D.
Definition at line 853 of file Texture.hpp.
Referenced by sibr::show().
handle()
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::Texture2D< T_Type, T_NumComp >::handle (void) const virtual
Returns
the texture handle.
Implements sibr::ITexture2D.
Definition at line 849 of file Texture.hpp.
Referenced by sibr::show(), and sibr::RenderMaskHolder::uploadMaskGPU().
mipmap()
template<typename T_Type , unsigned int T_NumComp> void sibr::Texture2D< T_Type, T_NumComp >::mipmap (int maxLOD = -1)
Trigger an update of the mipmaps for level 0 to maxLOD.
Parameters
maxLOD the maximum level of mipmap to generate. If -1, as many as possible based on the texture size.
Definition at line 917 of file Texture.hpp.
readBack()
template<typename T_Type , unsigned int T_NumComp> sibr::Image< T_Type, T_NumComp > sibr::Texture2D< T_Type, T_NumComp >::readBack (void) const
Returns
a CPU image containing the texture content.
Warning
Can cause a GPU flush/sync.
Definition at line 857 of file Texture.hpp.
References CHECK_GL_ERROR, sibr::Image< T_Type, T_NumComp >::data(), and sibr::Image< T_Type, T_NumComp >::flipH().
send2D()
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2D< T_Type, T_NumComp >::send2D (GLuint id, const ImageType & array, uint flags) static private
Send the CPU image data to the GPU.
Parameters
id the created texture
array the image data
flags options
Definition at line 741 of file Texture.hpp.
References CHECK_GL_ERROR, SIBR_FLIP_TEXTURE, SIBR_GPU_AUTOGEN_MIPMAP, and SIBR_GPU_INTEGER.
send2Dmipmap()
template<typename T_Type , unsigned int T_NumComp> void sibr::Texture2D< T_Type, T_NumComp >::send2Dmipmap (GLuint id, const std::vector< PixelImage > & miparray, uint flags) static private
Send the CPU images data for each mipmap to the GPU.
Parameters
id the created texture
miparray the image data
flags options
Definition at line 778 of file Texture.hpp.
References CHECK_GL_ERROR, SIBR_FLIP_TEXTURE, and SIBR_GPU_INTEGER.
SIBR_DISALLOW_COPY()
template<typename T_Type , unsigned int T_NumComp> sibr::Texture2D< T_Type, T_NumComp >::SIBR_DISALLOW_COPY (Texture2D< T_Type, T_NumComp >) private
update()
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2D< T_Type, T_NumComp >::update (const ImageType & img)
Update the content of the txeture with a new image.
Parameters
img the new content.
Definition at line 886 of file Texture.hpp.
References SIBR_FLIP_TEXTURE.
w()
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2D< T_Type, T_NumComp >::w (void) const virtual
Returns
the texture width.
Implements sibr::ITexture2D.
Definition at line 851 of file Texture.hpp.
Referenced by sibr::show().
Member Data Documentation
m_autoMIPMAP
template<typename T_Type , unsigned int T_NumComp> bool sibr::Texture2D< T_Type, T_NumComp >::m_autoMIPMAP = false private
Should the mipmaps be generated automatically.
Definition at line 100 of file Texture.hpp.
m_Flags
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2D< T_Type, T_NumComp >::m_Flags = 0 private
Options.
Definition at line 99 of file Texture.hpp.
m_H
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2D< T_Type, T_NumComp >::m_H = 0 private
Texture height.
Definition at line 98 of file Texture.hpp.
m_Handle
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::Texture2D< T_Type, T_NumComp >::m_Handle = 0 private
Texture handle.
Definition at line 96 of file Texture.hpp.
m_W
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2D< T_Type, T_NumComp >::m_W = 0 private
Texture width.
Definition at line 97 of file Texture.hpp.
The documentation for this class was generated from the following file:
src/core/graphics/Texture.hpp