SIBR: sibr::ByteStream Class Reference
sibr::ByteStream Class Reference
sibr_system
Be sure to use STL objects from client's dll version by exporting this declaration (see warning C4251)
#include <ByteStream.hpp>
Public Types
enum Endianness { BigEndian = 0, LittleEndian }
Stream endianness, always default to BigEndian.
typedef std::vector< uint8 > bytes
type used for storing bytes
Public Member Functions
ByteStream (void)
Constructor.
bool load (const std::string &filename)
Load all bytes from a file using the given filename.
void saveToFile (const std::string &filename)
Save all bytes to a file using the given filename.
void push (const void *data, uint size)
Append data to the current buffer.
operator bool (void) const
ByteStream & operator<< (bool b)
Write a bool to the stream.
ByteStream & operator<< (int8 i)
Write an 8bits-integer to the stream.
ByteStream & operator<< (int16 i)
Write a 16bits-integer to the stream.
ByteStream & operator<< (int32 i)
Write a 32bits-integer to the stream.
ByteStream & operator<< (int64 i)
Write a 64bits-integer to the stream.
ByteStream & operator<< (uint8 i)
Write an 8bits-unsigned-integer to the stream.
ByteStream & operator<< (uint16 i)
Write a 16bits-unsigned-integer to the stream.
ByteStream & operator<< (uint32 i)
Write a 32bits-unsigned-integer to the stream.
ByteStream & operator<< (uint64 i)
Write a 64bits-unsigned-integer to the stream.
ByteStream & operator<< (const std::string &str)
Write a string to the stream.
ByteStream & operator<< (float f)
Write a float to the stream.
ByteStream & operator<< (double d)
Write a double to the stream.
ByteStream & operator>> (bool &b)
Read a bool from the stream.
ByteStream & operator>> (int8 &i)
Read an 8bits-integer from the stream.
ByteStream & operator>> (int16 &i)
Read a 16bits-integer from the stream.
ByteStream & operator>> (int32 &i)
Read a 32bits-integer from the stream.
ByteStream & operator>> (int64 &i)
Read a 64bits-integer from the stream.
ByteStream & operator>> (uint8 &i)
Read an 8bits-unsigned-integer from the stream.
ByteStream & operator>> (uint16 &i)
Read a 16bits-unsigned-integer from the stream.
ByteStream & operator>> (uint32 &i)
Read a 32bits-unsigned-integer from the stream.
ByteStream & operator>> (uint64 &i)
Read a 64bits-unsigned-integer from the stream.
ByteStream & operator>> (std::string &str)
Read a string from the stream.
ByteStream & operator>> (float &f)
Read a float from the stream.
ByteStream & operator>> (double &d)
Read a double from the stream.
size_t readableSize (void) const
size_t bufferSize (void) const
const uint8 * buffer (void) const
void memoryDump (void) const
Dump the buffer contents to stdout.
Static Public Member Functions
static uint64 htonll (uint64 n)
Convert an uint32 from host to network byte order (which is big endian)
static uint32 htonl (uint32 n)
Convert an uint32 from host to network byte order (which is big endian)
static uint16 htons (uint16 n)
Convert an uint16 from host to network byte order (which is big endian)
static uint64 ntohll (uint64 n)
Convert an uint32 from network to host byte order.
static uint32 ntohl (uint32 n)
Convert an uint32 from network to host byte order.
static uint16 ntohs (uint16 n)
Convert an uint16 from network to host byte order.
static bool systemIsBigEndian (void)
Private Member Functions
bool testSize (uint n)
Test if we can read n bytes in the buffer.
Private Attributes
bytes _buffer
the whole stream
uint32 _readPos
Current position in the buffer when reading.
bool _valid
tells if no error occured when reading
Detailed Description
Be sure to use STL objects from client's dll version by exporting this declaration (see warning C4251)
Used to manipulate stream of bytes.
Note
This ByteStream stores integer using the network byte order (which is big endian).
Definition at line 18 of file ByteStream.hpp.
Member Typedef Documentation
bytes
typedef std::vector<uint8> sibr::ByteStream::bytes
type used for storing bytes
Definition at line 30 of file ByteStream.hpp.
Member Enumeration Documentation
Endianness
enum sibr::ByteStream::Endianness
Stream endianness, always default to BigEndian.
Enumerator
BigEndian
LittleEndian
Definition at line 23 of file ByteStream.hpp.
Constructor & Destructor Documentation
ByteStream()
sibr::ByteStream::ByteStream (void) inline
Constructor.
Definition at line 33 of file ByteStream.hpp.
Member Function Documentation
buffer()
const uint8* sibr::ByteStream::buffer (void) const inline
Returns
a pointer to the buffer
Definition at line 206 of file ByteStream.hpp.
Referenced by sibr::Mesh::saveToBinaryPLY().
bufferSize()
size_t sibr::ByteStream::bufferSize (void) const inline
Returns
the total number of bytes in the buffer used by the stream
Definition at line 275 of file ByteStream.hpp.
References _buffer.
Referenced by memoryDump(), readableSize(), sibr::Mesh::saveToBinaryPLY(), and saveToFile().
htonl()
uint32 sibr::ByteStream::htonl (uint32 n) static
Convert an uint32 from host to network byte order (which is big endian)
Parameters
n host order value
Returns
network order value
Definition at line 58 of file ByteStream.cpp.
References systemIsBigEndian().
Referenced by ntohl(), and operator<<().
htonll()
uint64 sibr::ByteStream::htonll (uint64 n) static
Convert an uint32 from host to network byte order (which is big endian)
Parameters
n host order value
Returns
network order value
Definition at line 41 of file ByteStream.cpp.
References systemIsBigEndian().
Referenced by ntohll(), and operator<<().
htons()
uint16 sibr::ByteStream::htons (uint16 n) static
Convert an uint16 from host to network byte order (which is big endian)
Parameters
n host order value
Returns
network order value
Definition at line 72 of file ByteStream.cpp.
References systemIsBigEndian().
Referenced by ntohs(), and operator<<().
load()
bool sibr::ByteStream::load (const std::string & filename)
Load all bytes from a file using the given filename.
Parameters
filename the filename
Returns
success boolean
Definition at line 98 of file ByteStream.cpp.
References _buffer, and SIBR_WRG.
Referenced by load(), sibr::CameraRecorder::load(), quad::load(), sibr::Image< T_Type, T_NumComp >::loadByteStream(), and sibr::InputCamera::loadFromBinary().
memoryDump()
void sibr::ByteStream::memoryDump (void) const
Dump the buffer contents to stdout.
(used for debugging purposes)
Definition at line 15 of file ByteStream.cpp.
References _buffer, bufferSize(), and readableSize().
ntohl()
uint32 sibr::ByteStream::ntohl (uint32 n) inline static
Convert an uint32 from network to host byte order.
Parameters
n network order value
Returns
host order value
Definition at line 282 of file ByteStream.hpp.
References htonl().
Referenced by sibr::IImage::imageResolution(), and operator>>().
ntohll()
uint64 sibr::ByteStream::ntohll (uint64 n) inline static
Convert an uint32 from network to host byte order.
Parameters
n network order value
Returns
host order value
Definition at line 279 of file ByteStream.hpp.
References htonll().
Referenced by operator>>().
ntohs()
uint16 sibr::ByteStream::ntohs (uint16 n) inline static
Convert an uint16 from network to host byte order.
Parameters
n network order value
Returns
host order value
Definition at line 285 of file ByteStream.hpp.
References htons().
Referenced by operator>>().
operator bool()
sibr::ByteStream::operator bool (void) const inline
Returns
true if the stream is opened and valid.
Definition at line 53 of file ByteStream.hpp.
operator<<() [1/12]
ByteStream & sibr::ByteStream::operator<< (bool b)
Write a bool to the stream.
Parameters
b input value
Returns
the stream (for chaining).
Definition at line 145 of file ByteStream.cpp.
Referenced by operator<<().
operator<<() [2/12]
ByteStream & sibr::ByteStream::operator<< (const std::string & str)
Write a string to the stream.
Parameters
str input value
Returns
the stream (for chaining).
Definition at line 204 of file ByteStream.cpp.
References operator<<(), and push().
operator<<() [3/12]
ByteStream & sibr::ByteStream::operator<< (double d)
Write a double to the stream.
Parameters
d input value
Returns
the stream (for chaining).
Definition at line 218 of file ByteStream.cpp.
References operator<<().
operator<<() [4/12]
ByteStream & sibr::ByteStream::operator<< (float f)
Write a float to the stream.
Parameters
f input value
Returns
the stream (for chaining).
Note
Use the same endianness as for integers (not specified in IEEE 754).
Definition at line 212 of file ByteStream.cpp.
References operator<<().
operator<<() [5/12]
ByteStream & sibr::ByteStream::operator<< (int16 i)
Write a 16bits-integer to the stream.
Parameters
i input value
Returns
the stream (for chaining).
Definition at line 156 of file ByteStream.cpp.
References htons(), and push().
operator<<() [6/12]
ByteStream & sibr::ByteStream::operator<< (int32 i)
Write a 32bits-integer to the stream.
Parameters
i input value
Returns
the stream (for chaining).
Definition at line 163 of file ByteStream.cpp.
References htonl(), and push().
operator<<() [7/12]
ByteStream & sibr::ByteStream::operator<< (int64 i)
Write a 64bits-integer to the stream.
Parameters
i input value
Returns
the stream (for chaining).
Definition at line 170 of file ByteStream.cpp.
References htonll(), and push().
operator<<() [8/12]
ByteStream & sibr::ByteStream::operator<< (int8 i)
Write an 8bits-integer to the stream.
Parameters
i input value
Returns
the stream (for chaining).
Definition at line 150 of file ByteStream.cpp.
References push().
operator<<() [9/12]
ByteStream & sibr::ByteStream::operator<< (uint16 i)
Write a 16bits-unsigned-integer to the stream.
Parameters
i input value
Returns
the stream (for chaining).
Definition at line 183 of file ByteStream.cpp.
References htons(), and push().
operator<<() [10/12]
ByteStream & sibr::ByteStream::operator<< (uint32 i)
Write a 32bits-unsigned-integer to the stream.
Parameters
i input value
Returns
the stream (for chaining).
Definition at line 190 of file ByteStream.cpp.
References htonl(), and push().
operator<<() [11/12]
ByteStream & sibr::ByteStream::operator<< (uint64 i)
Write a 64bits-unsigned-integer to the stream.
Parameters
i input value
Returns
the stream (for chaining).
Definition at line 197 of file ByteStream.cpp.
References htonll(), and push().
operator<<() [12/12]
ByteStream & sibr::ByteStream::operator<< (uint8 i)
Write an 8bits-unsigned-integer to the stream.
Parameters
i input value
Returns
the stream (for chaining).
Definition at line 177 of file ByteStream.cpp.
References push().
operator>>() [1/12]
ByteStream & sibr::ByteStream::operator>> (bool & b) inline
Read a bool from the stream.
Parameters
b output value
Returns
the stream (for chaining).
Definition at line 292 of file ByteStream.hpp.
Referenced by operator>>().
operator>>() [2/12]
ByteStream & sibr::ByteStream::operator>> (double & d) inline
Read a double from the stream.
Parameters
d output value
Returns
the stream (for chaining).
Definition at line 387 of file ByteStream.hpp.
References _valid, and operator>>().
operator>>() [3/12]
ByteStream & sibr::ByteStream::operator>> (float & f) inline
Read a float from the stream.
Parameters
f output value
Returns
the stream (for chaining).
Note
Use the same endianness as for integers (not specified in IEEE 754).
Definition at line 378 of file ByteStream.hpp.
References _valid, and operator>>().
operator>>() [4/12]
ByteStream & sibr::ByteStream::operator>> (int16 & i) inline
Read a 16bits-integer from the stream.
Parameters
i output value
Returns
the stream (for chaining).
Definition at line 306 of file ByteStream.hpp.
References _buffer, _readPos, ntohs(), and testSize().
operator>>() [5/12]
ByteStream & sibr::ByteStream::operator>> (int32 & i) inline
Read a 32bits-integer from the stream.
Parameters
i output value
Returns
the stream (for chaining).
Definition at line 315 of file ByteStream.hpp.
References _buffer, _readPos, ntohl(), and testSize().
operator>>() [6/12]
ByteStream & sibr::ByteStream::operator>> (int64 & i) inline
Read a 64bits-integer from the stream.
Parameters
i output value
Returns
the stream (for chaining).
Definition at line 323 of file ByteStream.hpp.
References _buffer, _readPos, ntohll(), and testSize().
operator>>() [7/12]
ByteStream & sibr::ByteStream::operator>> (int8 & i) inline
Read an 8bits-integer from the stream.
Parameters
i output value
Returns
the stream (for chaining).
Definition at line 298 of file ByteStream.hpp.
References _buffer, _readPos, and testSize().
operator>>() [8/12]
ByteStream & sibr::ByteStream::operator>> (std::string & str) inline
Read a string from the stream.
Parameters
str output value
Returns
the stream (for chaining).
Definition at line 364 of file ByteStream.hpp.
References _buffer, _readPos, operator>>(), and testSize().
operator>>() [9/12]
ByteStream & sibr::ByteStream::operator>> (uint16 & i) inline
Read a 16bits-unsigned-integer from the stream.
Parameters
i output value
Returns
the stream (for chaining).
Definition at line 340 of file ByteStream.hpp.
References _buffer, _readPos, ntohs(), and testSize().
operator>>() [10/12]
ByteStream & sibr::ByteStream::operator>> (uint32 & i) inline
Read a 32bits-unsigned-integer from the stream.
Parameters
i output value
Returns
the stream (for chaining).
Definition at line 348 of file ByteStream.hpp.
References _buffer, _readPos, ntohl(), and testSize().
operator>>() [11/12]
ByteStream & sibr::ByteStream::operator>> (uint64 & i) inline
Read a 64bits-unsigned-integer from the stream.
Parameters
i output value
Returns
the stream (for chaining).
Definition at line 356 of file ByteStream.hpp.
References _buffer, _readPos, ntohll(), and testSize().
operator>>() [12/12]
ByteStream & sibr::ByteStream::operator>> (uint8 & i) inline
Read an 8bits-unsigned-integer from the stream.
Parameters
i output value
Returns
the stream (for chaining).
Definition at line 332 of file ByteStream.hpp.
References _buffer, _readPos, and testSize().
push()
void sibr::ByteStream::push (const void * data, uint size)
Append data to the current buffer.
Parameters
data pointer to the data
size size in bytes
Definition at line 135 of file ByteStream.cpp.
References _buffer.
Referenced by operator<<().
readableSize()
size_t sibr::ByteStream::readableSize (void) const inline
Returns
the number of bytes that have not been read yet.
Definition at line 272 of file ByteStream.hpp.
References _readPos, and bufferSize().
Referenced by memoryDump(), and testSize().
saveToFile()
void sibr::ByteStream::saveToFile (const std::string & filename)
Save all bytes to a file using the given filename.
Parameters
filename file apth
Definition at line 119 of file ByteStream.cpp.
References _buffer, bufferSize(), and SIBR_LOG.
Referenced by save(), sibr::CameraRecorder::save(), quad::save(), sibr::Image< T_Type, T_NumComp >::saveByteStream(), and sibr::InputCamera::saveToBinary().
systemIsBigEndian()
bool sibr::ByteStream::systemIsBigEndian (void) static
Returns
true if the current system runs using Big Endian
Definition at line 84 of file ByteStream.cpp.
Referenced by htonl(), htonll(), and htons().
testSize()
bool sibr::ByteStream::testSize (uint n) inline private
Test if we can read n bytes in the buffer.
Parameters
n the number of bytes to check
Returns
false if it fails (and set valid flag to false).
Definition at line 288 of file ByteStream.hpp.
References _valid, and readableSize().
Referenced by operator>>().
Member Data Documentation
_buffer
bytes sibr::ByteStream::_buffer private
the whole stream
Definition at line 264 of file ByteStream.hpp.
Referenced by bufferSize(), load(), memoryDump(), operator>>(), push(), and saveToFile().
_readPos
uint32 sibr::ByteStream::_readPos private
Current position in the buffer when reading.
Definition at line 265 of file ByteStream.hpp.
Referenced by operator>>(), and readableSize().
_valid
bool sibr::ByteStream::_valid private
tells if no error occured when reading
Definition at line 266 of file ByteStream.hpp.
Referenced by operator>>(), and testSize().
The documentation for this class was generated from the following files:
src/core/system/ByteStream.hpp
src/core/system/ByteStream.cpp