SIBR: sibr::DepthInputTextureArray Class Reference
sibr::DepthInputTextureArray Class Reference
sibr_scene
#include <RenderTargetTextures.hpp>
Public Member Functions
virtual void initDepthTextureArrays (ICalibratedCameras::Ptr cams, IProxyMesh::Ptr proxies, bool facecull, int flags=SIBR_GPU_LINEAR_SAMPLING)
const Texture2DArrayLum32F::Ptr & getInputDepthMapArrayPtr () const
Public Member Functions inherited from sibr::RTTextureSize
RTTextureSize (uint w=0)
void initSize (uint w, uint h)
bool isInit () const
Protected Attributes
Texture2DArrayLum32F::Ptr _inputDepthMapArrayPtr
Protected Attributes inherited from sibr::RTTextureSize
uint _width = 0
uint _height = 0
bool _isInit = false
int _initActiveCam = 0
Detailed Description
Definition at line 57 of file RenderTargetTextures.hpp.
Member Function Documentation
getInputDepthMapArrayPtr()
const Texture2DArrayLum32F::Ptr & sibr::DepthInputTextureArray::getInputDepthMapArrayPtr () const
Definition at line 177 of file RenderTargetTextures.cpp.
References _inputDepthMapArrayPtr.
initDepthTextureArrays()
void sibr::DepthInputTextureArray::initDepthTextureArrays (ICalibratedCameras::Ptr cams, IProxyMesh::Ptr proxies, bool facecull, int flags = SIBR_GPU_LINEAR_SAMPLING) virtual
Definition at line 122 of file RenderTargetTextures.cpp.
References sibr::RTTextureSize::_height, sibr::RTTextureSize::_initActiveCam, _inputDepthMapArrayPtr, sibr::RTTextureSize::_width, sibr::GLShader::begin(), sibr::RenderTarget< T_Type, T_NumComp >::bind(), CHECK_GL_ERROR, sibr::GLShader::end(), sibr::Resources::getResourceFilePathName(), sibr::RenderTarget< T_Type, T_NumComp >::handle(), sibr::GLParameter::init(), sibr::GLShader::init(), sibr::RTTextureSize::initSize(), sibr::Resources::Instance(), sibr::RTTextureSize::isInit(), sibr::loadFile(), sibr::GLParameter::set(), SIBR_GPU_LINEAR_SAMPLING, SIBR_LOG, SIBR_SCENE_LINEAR_SAMPLING, SIBR_WRG, and sibr::RenderTarget< T_Type, T_NumComp >::unbind().
Referenced by sibr::RenderTargetTextures::initRGBandDepthTextureArrays().
Member Data Documentation
_inputDepthMapArrayPtr
Texture2DArrayLum32F::Ptr sibr::DepthInputTextureArray::_inputDepthMapArrayPtr protected
Definition at line 64 of file RenderTargetTextures.hpp.
Referenced by getInputDepthMapArrayPtr(), and initDepthTextureArrays().
The documentation for this class was generated from the following files:
src/core/scene/RenderTargetTextures.hpp
src/core/scene/RenderTargetTextures.cpp