SIBR: sibr::TexturedMeshRenderer Class Reference
sibr::TexturedMeshRenderer Class Reference
sibr_renderer
Render a textured mesh, using per-vertex texture coordinates.
#include <TexturedMeshRenderer.hpp>
Public Types
typedef std::shared_ptr< TexturedMeshRenderer > Ptr
Public Member Functions
TexturedMeshRenderer (bool flipY=false)
Constructor.
void process (const Mesh &mesh, const Camera &eye, uint textureID, IRenderTarget &dst, bool backfaceCull=true)
Render the textured mesh.
void process (const Mesh &mesh, const Camera &eye, const sibr::Matrix4f &model, uint textureID, IRenderTarget &dst, bool backfaceCull=true)
Render the textured mesh.
Protected Attributes
GLShader _shader
The texture mesh shader.
GLParameter _paramMVP
MVP uniform.
Detailed Description
Render a textured mesh, using per-vertex texture coordinates.
Definition at line 15 of file TexturedMeshRenderer.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<TexturedMeshRenderer> sibr::TexturedMeshRenderer::Ptr
Definition at line 18 of file TexturedMeshRenderer.hpp.
Constructor & Destructor Documentation
TexturedMeshRenderer()
sibr::TexturedMeshRenderer::TexturedMeshRenderer (bool flipY = false)
Constructor.
Parameters
flipY if set to true, UV coordinates will be flipped vertically.
Definition at line 5 of file TexturedMeshRenderer.cpp.
References _paramMVP, _shader, sibr::getShadersDirectory(), sibr::GLParameter::init(), sibr::GLShader::init(), and sibr::loadFile().
Member Function Documentation
process() [1/2]
void sibr::TexturedMeshRenderer::process (const Mesh & mesh, const Camera & eye, const sibr::Matrix4f & model, uint textureID, IRenderTarget & dst, bool backfaceCull = true)
Render the textured mesh.
Parameters
mesh the mesh to render (should have UV attribute)
eye the viewpoint to use
model additional transformation matrix
textureID handle of the texture to use
dst destination rendertarget
backfaceCull should backface culling be performed
Definition at line 30 of file TexturedMeshRenderer.cpp.
References _paramMVP, _shader, sibr::GLShader::begin(), ibr_preprocess_rc_to_sibr::dst, sibr::GLShader::end(), sibr::Mesh::render(), sibr::GLParameter::set(), and sibr::Camera::viewproj().
process() [2/2]
void sibr::TexturedMeshRenderer::process (const Mesh & mesh, const Camera & eye, uint textureID, IRenderTarget & dst, bool backfaceCull = true)
Render the textured mesh.
Parameters
mesh the mesh to render (should have UV attribute)
eye the viewpoint to use
textureID handle of the texture to use
dst destination rendertarget
backfaceCull should backface culling be performed
Definition at line 18 of file TexturedMeshRenderer.cpp.
References _paramMVP, _shader, sibr::GLShader::begin(), ibr_preprocess_rc_to_sibr::dst, sibr::GLShader::end(), sibr::Mesh::render(), sibr::GLParameter::set(), and sibr::Camera::viewproj().
Member Data Documentation
_paramMVP
GLParameter sibr::TexturedMeshRenderer::_paramMVP protected
MVP uniform.
Definition at line 49 of file TexturedMeshRenderer.hpp.
Referenced by process(), and TexturedMeshRenderer().
_shader
GLShader sibr::TexturedMeshRenderer::_shader protected
The texture mesh shader.
Definition at line 48 of file TexturedMeshRenderer.hpp.
Referenced by process(), and TexturedMeshRenderer().
The documentation for this class was generated from the following files:
src/core/renderer/TexturedMeshRenderer.hpp
src/core/renderer/TexturedMeshRenderer.cpp