SIBR: sibr::GLShader Class Reference
sibr::GLShader Class Reference
sibr_graphics
OpenGL shader wrapper.
#include <Shader.hpp>
Classes
struct Define
Macro-like substitution in shaders.
Public Member Functions
GLShader (void)
Constructor.
~GLShader (void)
Destructor.
bool init (std::string name, std::string vp_code, std::string fp_code, std::string gp_code=std::string(), bool exitOnError=true, std::string tcs_code=std::string(), std::string tes_code=std::string())
Create and compile a GPU program composed of a vertex/fragment shader (and optionally geometry/tesselation shaders).
bool reload (std::string vp_code, std::string fp_code, std::string gp_code=std::string())
Recompile a GPU program with updated shaders.
void getBinary (std::vector< char > &binary)
Query the dissassembly of the shader program.
SIBR_OPT_INLINE void begin (void)
Bind (activate) the sahder for rendering.
SIBR_OPT_INLINE void end (void)
Unbind the shader.
void init (GLuint s_handle)
Init from an existing GPU program.
void terminate (void)
Cleanup and delete the program.
void setStrict (bool s)
If set to true, uniforms that are linked but not referenced by the shader will cause an error to be raised.
GLuint shader (void) const
std::string name (void) const
bool isReady (void) const
bool isActive (void) const
bool isStrict (void) const
Private Member Functions
SIBR_DISALLOW_COPY (GLShader)
SIBR_CLASS_PTR (GLShader)
GLuint compileShader (const char *shader_code, GLuint type)
Compile a shader for a given stage.
SIBR_OPT_INLINE void authorize (void) const
Check if the shader is properly setup, or raise an error.
Private Attributes
GLuint m_Shader
Shader program handle.
std::string m_Name
Shader name.
bool m_Strict
Should uniforms be validated.
bool m_Active
Is the shader currently bound.
Detailed Description
OpenGL shader wrapper.
Definition at line 16 of file Shader.hpp.
Constructor & Destructor Documentation
GLShader()
sibr::GLShader::GLShader (void)
Constructor.
Definition at line 45 of file Shader.cpp.
~GLShader()
sibr::GLShader::~GLShader (void)
Destructor.
Definition at line 52 of file Shader.cpp.
References terminate().
Member Function Documentation
authorize()
SIBR_OPT_INLINE void sibr::GLShader::authorize (void) const private
Check if the shader is properly setup, or raise an error.
begin()
SIBR_OPT_INLINE void sibr::GLShader::begin (void)
Bind (activate) the sahder for rendering.
Referenced by sibr::DrawUtilities::baseRendering(), sibr::InterfaceUtilities::circle(), sibr::CopyRenderer::copyToWindow(), sibr::MultiViewInterface::displayHighlightedPixels(), sibr::MultiViewInterface::displayImages(), sibr::Intersector2D::frustrumQuadsIntersect(), sibr::DrawUtilities::image_grid(), sibr::DepthInputTextureArray::initDepthTextureArrays(), sibr::RGBDInputTextures::initializeDepthRenderTargets(), sibr::RGBDInputTextures::initializeImageRenderTargets(), sibr::InterfaceUtilities::linePixels(), sibr::NormalRenderer::NormalRenderer(), sibr::TrackBall::onRender(), sibr::ImageView::onRender(), sibr::BinaryMeshRenderer::process(), sibr::ColoredMeshRenderer::process(), sibr::TexturedMeshRenderer::process(), sibr::ULRV2Renderer::process(), sibr::ULRRenderer::process(), sibr::AddShadowRenderer::process(), sibr::BlurRenderer::process(), sibr::CopyRenderer::process(), sibr::InterfaceUtilities::rectangle(), sibr::ShaderAlphaMVP::render(), sibr::Skybox::render(), sibr::PositionRenderer::render(), sibr::DepthRenderer::render(), sibr::NormalRenderer::render(), sibr::ShadowMapRenderer::render(), sibr::PoissonRenderer::render(), sibr::MonoRdrMode::render(), sibr::StereoAnaglyphRdrMode::render(), sibr::LabelsManager::renderLabels(), sibr::ULRV2Renderer::setupULRshader(), sibr::ShadowMapRenderer::ShadowMapRenderer(), sibr::show(), and sibr::RenderMaskHolder::uploadMaskGPU().
compileShader()
GLuint sibr::GLShader::compileShader (const char * shader_code, GLuint type) private
Compile a shader for a given stage.
Parameters
shader_code the string containing the sahder code
type the stage to compile for
Returns
the compiled shader stage handle.
Definition at line 13 of file Shader.cpp.
References m_Name, and SIBR_WRG.
Referenced by init().
end()
SIBR_OPT_INLINE void sibr::GLShader::end (void)
Unbind the shader.
Referenced by sibr::DrawUtilities::baseRendering(), sibr::InterfaceUtilities::circle(), sibr::CopyRenderer::copyToWindow(), sibr::MultiViewInterface::displayHighlightedPixels(), sibr::MultiViewInterface::displayImages(), sibr::Intersector2D::frustrumQuadsIntersect(), sibr::DrawUtilities::image_grid(), sibr::DepthInputTextureArray::initDepthTextureArrays(), sibr::RGBDInputTextures::initializeDepthRenderTargets(), sibr::RGBDInputTextures::initializeImageRenderTargets(), sibr::InterfaceUtilities::linePixels(), sibr::NormalRenderer::NormalRenderer(), sibr::TrackBall::onRender(), sibr::ImageView::onRender(), sibr::BinaryMeshRenderer::process(), sibr::ColoredMeshRenderer::process(), sibr::TexturedMeshRenderer::process(), sibr::ULRV2Renderer::process(), sibr::ULRRenderer::process(), sibr::AddShadowRenderer::process(), sibr::BlurRenderer::process(), sibr::CopyRenderer::process(), sibr::InterfaceUtilities::rectangle(), sibr::ShaderAlphaMVP::render(), sibr::Skybox::render(), sibr::PositionRenderer::render(), sibr::DepthRenderer::render(), sibr::NormalRenderer::render(), sibr::ShadowMapRenderer::render(), sibr::PoissonRenderer::render(), sibr::MonoRdrMode::render(), sibr::StereoAnaglyphRdrMode::render(), sibr::LabelsManager::renderLabels(), sibr::ULRV2Renderer::setupULRshader(), sibr::ShadowMapRenderer::ShadowMapRenderer(), sibr::show(), and sibr::RenderMaskHolder::uploadMaskGPU().
getBinary()
void sibr::GLShader::getBinary (std::vector< char > & binary)
Query the dissassembly of the shader program.
Parameters
binary will contain the compiled shader code
Note
This is not supported on all GPUs.
Definition at line 191 of file Shader.cpp.
References sibr::Key::count, sibr::length(), m_Name, m_Shader, and SIBR_WRG.
init() [1/2]
void sibr::GLShader::init (GLuint s_handle)
Init from an existing GPU program.
Parameters
s_handle the existing program handle
Definition at line 56 of file Shader.cpp.
References m_Shader.
init() [2/2]
bool sibr::GLShader::init (std::string name, std::string vp_code, std::string fp_code, std::string gp_code = std::string(), bool exitOnError = true, std::string tcs_code = std::string(), std::string tes_code = std::string())
Create and compile a GPU program composed of a vertex/fragment shader (and optionally geometry/tesselation shaders).
Parameters
name the name of the shader (for logging)
vp_code vertex shader code string
fp_code fragment shader code string
gp_code geometry shader code string
exitOnError should the application exit on a shader compilation error
tcs_code tesselation control shader code string
tes_code tesselation evaluation shader code string
Returns
a success flag
Definition at line 91 of file Shader.cpp.
References CHECK_GL_ERROR, compileShader(), m_Name, m_Shader, name(), SIBR_ERR, SIBR_WRG, and terminate().
Referenced by sibr::AddShadowRenderer::AddShadowRenderer(), sibr::BinaryMeshRenderer::BinaryMeshRenderer(), sibr::BlurRenderer::BlurRenderer(), sibr::ColoredMeshRenderer::ColoredMeshRenderer(), sibr::CopyRenderer::CopyRenderer(), sibr::DepthRenderer::DepthRenderer(), sibr::Intersector2D::frustrumQuadsIntersect(), sibr::ImageView::ImageView(), sibr::DrawUtilities::initBaseShader(), sibr::InterfaceUtilities::initBaseShader(), sibr::DepthInputTextureArray::initDepthTextureArrays(), sibr::DrawUtilities::initGridShader(), sibr::RGBDInputTextures::initializeDepthRenderTargets(), sibr::RGBDInputTextures::initializeImageRenderTargets(), sibr::InterfaceUtilities::initMeshViewShader(), sibr::InterfaceUtilities::initMultiViewShader(), sibr::ShaderAlphaMVP::initShader(), sibr::TrackBall::initTrackBallShader(), sibr::Skybox::load(), sibr::MonoRdrMode::MonoRdrMode(), sibr::NormalRenderer::NormalRenderer(), sibr::PoissonRenderer::PoissonRenderer(), sibr::PositionRenderer::PositionRenderer(), reload(), sibr::LabelsManager::setupLabelsManagerShader(), sibr::ULRV2Renderer::setupULRshader(), sibr::ShadowMapRenderer::ShadowMapRenderer(), sibr::StereoAnaglyphRdrMode::StereoAnaglyphRdrMode(), sibr::TexturedMeshRenderer::TexturedMeshRenderer(), sibr::ULRRenderer::ULRRenderer(), and sibr::RenderMaskHolder::uploadMaskGPU().
isActive()
bool sibr::GLShader::isActive (void) const
Returns
true if the shader is currently bound for drawing.
Definition at line 81 of file Shader.cpp.
References m_Active.
isReady()
bool sibr::GLShader::isReady (void) const
Returns
true if the shader is properly setup.
Definition at line 76 of file Shader.cpp.
References m_Shader.
isStrict()
bool sibr::GLShader::isStrict (void) const
Returns
true if the shader will validate linked uniforms.
Definition at line 86 of file Shader.cpp.
References m_Strict.
Referenced by sibr::GLParameter::init().
name()
std::string sibr::GLShader::name (void) const
Returns
the shader name.
Definition at line 71 of file Shader.cpp.
References m_Name.
Referenced by sibr::GLParameter::init(), and init().
reload()
bool sibr::GLShader::reload (std::string vp_code, std::string fp_code, std::string gp_code = std::string())
Recompile a GPU program with updated shaders.
Parameters
vp_code vertex shader code string
fp_code fragment shader code string
gp_code geometry shader code string
Returns
a success flag
Definition at line 176 of file Shader.cpp.
References init(), m_Name, and SIBR_WRG.
setStrict()
void sibr::GLShader::setStrict (bool s)
If set to true, uniforms that are linked but not referenced by the shader will cause an error to be raised.
Parameters
s the validation level
Definition at line 61 of file Shader.cpp.
References m_Strict.
shader()
GLuint sibr::GLShader::shader (void) const
Returns
the program handle.
Definition at line 66 of file Shader.cpp.
References m_Shader.
Referenced by sibr::GLParameter::init().
SIBR_CLASS_PTR()
sibr::GLShader::SIBR_CLASS_PTR (GLShader) private
SIBR_DISALLOW_COPY()
sibr::GLShader::SIBR_DISALLOW_COPY (GLShader) private
terminate()
void sibr::GLShader::terminate (void)
Cleanup and delete the program.
Definition at line 212 of file Shader.cpp.
References CHECK_GL_ERROR, and m_Shader.
Referenced by sibr::InterfaceUtilities::freeAllShaders(), init(), and ~GLShader().
Member Data Documentation
m_Active
bool sibr::GLShader::m_Active private
Is the shader currently bound.
Definition at line 135 of file Shader.hpp.
Referenced by isActive().
m_Name
std::string sibr::GLShader::m_Name private
Shader name.
Definition at line 133 of file Shader.hpp.
Referenced by compileShader(), getBinary(), init(), name(), and reload().
m_Shader
GLuint sibr::GLShader::m_Shader private
Shader program handle.
Definition at line 132 of file Shader.hpp.
Referenced by getBinary(), init(), isReady(), shader(), and terminate().
m_Strict
bool sibr::GLShader::m_Strict private
Should uniforms be validated.
Definition at line 134 of file Shader.hpp.
Referenced by isStrict(), and setStrict().
The documentation for this class was generated from the following files:
src/core/graphics/Shader.hpp
src/core/graphics/Shader.cpp