SIBR: sibr::Mesh Class Reference
sibr::Mesh Class Reference
sibr_graphics
Store both CPU and GPU data for a geometric mesh.
#include <Mesh.hpp>
Classes
struct BufferGL
Wrapper around a MeshBuffer, used to prevent copying OpenGL object IDs.
struct RenderingOptions
Mesh rendering options.
struct SubMesh
Submesh structure.
Public Types
enum RenderMode { PointRenderMode, LineRenderMode, FillRenderMode }
Mesh rendering mode.
enum VERTEX_LIST_CHOICE { VERTEX_LIST_CHOICE::KEEP, VERTEX_LIST_CHOICE::REMOVE }
Submesh extraction options.
enum PartOfSphere { PartOfSphere::WHOLE, PartOfSphere::UP, PartOfSphere::BOTTOM }
Environment sphere generation options: top/bottom parts or both.
typedef std::vector< Vector3f > Vertices
typedef std::vector< Vector3f > Normals
typedef std::vector< Vector3u > Triangles
typedef std::vector< Vector3f > Colors
typedef std::vector< Vector2f > UVs
Public Member Functions
Mesh (bool withGraphics=true)
Constructor.
void vertices (const Vertices &vertices)
Set vertices.
void vertices (const std::vector< float > &vertices)
Set vertices from a vector of floats (linear).
const Vertices & vertices (void) const
void replaceVertice (int vertex_id, const sibr::Vector3f &v)
Update a specific vertex position.
Mesh::Ptr clone () const
const float * vertexArray (void) const
void triangles (const Triangles &triangles)
Set triangles.
void triangles (const std::vector< uint > &triangles)
Set triangles.
const Triangles & triangles (void) const
const uint * triangleArray (void) const
void colors (const Colors &colors)
Set vertex colors.
const Colors & colors (void) const
bool hasColors (void) const
const float * colorArray (void) const
void texCoords (const UVs &texcoords)
Set vertex texture coordinates.
void texCoords (const std::vector< float > &texcoords)
Set texture coordinates using a flat vector of floats.
const UVs & texCoords (void) const
bool hasTexCoords (void) const
const float * texCoordArray (void) const
std::string getTextureImageFileName () const
void normals (const Normals &normals)
Set vertex normals.
void normals (const std::vector< float > &normals)
Set normals using a flat vector of floats.
const Normals & normals (void) const
bool hasNormals (void) const
const float * normalArray (void) const
void makeWhole (void)
Make the mesh whole, ie it will have default values for all components (texture, materials, colors, etc) It is useful when merging two meshes.
void generateNormals (void)
Generate vertex normals by using the average of all triangle normals around a each vertex.
void generateSmoothNormals (int numIter)
Generate smooth vertex normals by using the average of all triangle normals around a each vertex and iterating this process.
void generateSmoothNormalsDisconnected (int numIter)
Generate smooth vertex normals by using the average of all triangle normals around a each vertex and iterating this process.
void laplacianSmoothing (int numIter, bool updateNormals)
Perform laplacian smoothing on the mesh vertices.
void adaptativeTaubinSmoothing (int numIter, bool updateNormals)
Perform adaptive Taubin smoothing on the mesh vertices.
Mesh generateSubMesh (std::function< bool(int)> func) const
Generate a new mesh given a boolean function that state if each vertex should be kept or not.
bool load (const std::string &filename)
Load a mesh from the disk.
bool loadMtsXML (const std::string &filename)
Load a scene from a set of mitsuba XML scene files (referencing multiple OBJs/PLYs).
void save (const std::string &filename, bool universal=false, const std::string &textureName="TEXTURE_NAME_TO_PUT_IN_THE_FILE") const
Save the mesh to the disk.
bool saveToBinaryPLY (const std::string &filename, bool universal=false, const std::string &textureName="TEXTURE_NAME_TO_PUT_IN_THE_FILE") const
Save the mesh to .ply file (using the binary version).
bool saveToASCIIPLY (const std::string &filename, bool universal=false, const std::string &textureName="TEXTURE_NAME_TO_PUT_IN_THE_FILE") const
Save the mesh to .ply file (using the ASCII version).
bool saveToObj (const std::string &filename) const
Save the mesh to .obj file.
std::stringstream getOffStream (bool verbose=false) const
void fromOffStream (std::stringstream &stream, bool generateNormals=true)
void render (bool depthTest=true, bool backFaceCulling=true, RenderMode mode=FillRenderMode, bool frontFaceCulling=false, bool invertDepthTest=false, bool tessellation=false, bool adjacency=false) const
Render the geometry using OpenGL.
void renderSubMesh (unsigned int begin, unsigned int end, bool depthTest=true, bool backFaceCulling=true, RenderMode mode=FillRenderMode, bool frontFaceCulling=false, bool invertDepthTest=false) const
Render a part of the geometry (taken either from the index buffer or directly in the vertex buffer) using OpenGL.
void forceBufferGLUpdate (bool adjacency=false) const
Force upload of data to the GPU.
void freeBufferGLUpdate (void) const
Delete GPU mesh data.
void render_points (bool depthTest) const
Render the mesh vertices as points.
void render_points (void) const
Render the mesh vertices as points.
void render_lines (void) const
Render the mesh vertices as successive lines.
void merge (const Mesh &other)
Merge another mesh into this one.
void eraseTriangles (const std::vector< uint > &faceIDList)
Erase some of the triangles.
SubMesh extractSubMesh (const std::vector< int > &vertices, VERTEX_LIST_CHOICE v_choice) const
Extract a submesh based on a list of vertices to keep/remove.
sibr::Mesh invertedFacesMesh () const
sibr::Mesh::Ptr invertedFacesMesh2 () const
const std::string getMeshFilePath (void) const
Eigen::AlignedBox< float, 3 > getBoundingBox (void) const
sibr::Vector3f centroid () const
void getBoundingSphere (Vector3f &outCenter, float &outRadius, bool referencedOnly=false, bool usePCcenter=false) const
Estimated the mesh bounding sphere.
sibr::Mesh::Ptr subDivide (float limitSize, size_t maxRecursion=std::numeric_limits< size_t >::max()) const
Subdivide a mesh triangles until an edge size threshold is reached.
float meanEdgeSize () const
std::vector< std::vector< int > > removeDisconnectedComponents ()
Split a mesh in its connected components.
Static Public Member Functions
static sibr::Mesh::Ptr getTestCube (bool withGraphics=true)
Generate a simple cube with normals.
static Mesh::Ptr getSphereMesh (const Vector3f &center, float radius, bool withGraphics=true, int precision=50)
Generate a sphere mesh.
static sibr::Mesh::Ptr getEnvSphere (sibr::Vector3f center, float radius, sibr::Vector3f zenith, sibr::Vector3f north, PartOfSphere part=PartOfSphere::WHOLE)
Public Attributes
BufferGL _gl
Internal OpenGL data.
Vertices _vertices
Vertex positions.
Triangles _triangles
Triangle indices.
Normals _normals
Vertex normals.
Colors _colors
Vertex colors.
UVs _texcoords
Vertex UVs.
Private Member Functions
SIBR_CLASS_PTR (Mesh)
Private Attributes
std::string _meshPath
Source path, can be used to reload the mesh with/without graphics option in constructor.
std::string _textureImageFileName
RenderingOptions _renderingOptions
Detailed Description
Store both CPU and GPU data for a geometric mesh.
Provide many processing and display methods.
Definition at line 22 of file Mesh.hpp.
Member Typedef Documentation
Colors
typedef std::vector<Vector3f> sibr::Mesh::Colors
Definition at line 31 of file Mesh.hpp.
Normals
typedef std::vector<Vector3f> sibr::Mesh::Normals
Definition at line 29 of file Mesh.hpp.
Triangles
typedef std::vector<Vector3u> sibr::Mesh::Triangles
Definition at line 30 of file Mesh.hpp.
UVs
typedef std::vector<Vector2f> sibr::Mesh::UVs
Definition at line 32 of file Mesh.hpp.
Vertices
typedef std::vector<Vector3f> sibr::Mesh::Vertices
Definition at line 28 of file Mesh.hpp.
Member Enumeration Documentation
PartOfSphere
enum sibr::Mesh::PartOfSphere strong
Environment sphere generation options: top/bottom parts or both.
Enumerator
WHOLE
UP
BOTTOM
Definition at line 417 of file Mesh.hpp.
RenderMode
enum sibr::Mesh::RenderMode
Mesh rendering mode.
Enumerator
PointRenderMode
LineRenderMode
FillRenderMode
Definition at line 35 of file Mesh.hpp.
VERTEX_LIST_CHOICE
enum sibr::Mesh::VERTEX_LIST_CHOICE strong
Submesh extraction options.
Enumerator
KEEP
REMOVE
Definition at line 347 of file Mesh.hpp.
Constructor & Destructor Documentation
Mesh()
sibr::Mesh::Mesh (bool withGraphics = true)
Constructor.
Parameters
withGraphics init associated OpenGL buffers object (requires an openGL context)
Definition at line 24 of file Mesh.cpp.
References _gl, and sibr::Mesh::BufferGL::bufferGL.
Referenced by getSphereMesh().
Member Function Documentation
adaptativeTaubinSmoothing()
void sibr::Mesh::adaptativeTaubinSmoothing (int numIter, bool updateNormals)
Perform adaptive Taubin smoothing on the mesh vertices.
Parameters
numIter smoothing iteration count
updateNormals should the normals be recomputed after smoothing
Definition at line 1039 of file Mesh.cpp.
References _colors, _triangles, _vertices, colors(), sibr::dot(), generateNormals(), and vertices().
centroid()
sibr::Vector3f sibr::Mesh::centroid () const
Returns
the mesh centroid.
Definition at line 1694 of file Mesh.cpp.
References _vertices.
clone()
Mesh::Ptr sibr::Mesh::clone (void) const
Returns
a deep copy of the mesh.
Definition at line 2033 of file Mesh.cpp.
References _gl, sibr::Mesh::BufferGL::bufferGL, colors(), hasColors(), hasNormals(), hasTexCoords(), normals(), texCoords(), triangles(), and vertices().
colorArray()
const float * sibr::Mesh::colorArray (void) const inline
Returns
colors in an array using the following format: {0r, 0g, 0b, 1r, 1g, 1b, 2r, 2g, 2b, ...}. Useful for rendering and converting to another mesh struct.
Definition at line 526 of file Mesh.hpp.
References _colors.
colors() [1/2]
void sibr::Mesh::colors (const Colors & colors) inline
Set vertex colors.
Parameters
colors the new vertex colors
Definition at line 500 of file Mesh.hpp.
References _colors, _gl, colors(), and sibr::Mesh::BufferGL::dirtyBufferGL.
Referenced by sibr::MeshBufferGL::build(), extractSubMesh(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), invertedFacesMesh(), invertedFacesMesh2(), merge(), sibr::Raycaster::smoothColor(), and sibr::UVUnwrapper::unwrap().
colors() [2/2]
const Mesh::Colors & sibr::Mesh::colors (void) const inline
Returns
a reference to the vertex color list.
Definition at line 503 of file Mesh.hpp.
References _colors.
Referenced by adaptativeTaubinSmoothing(), sibr::MaterialMesh::ambientOcclusion(), clone(), colors(), eraseTriangles(), extractSubMesh(), sibr::MaterialMesh::fillColorsWithIndexMaterials(), sibr::MaterialMesh::fillColorsWithMatIds(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), invertedFacesMesh(), invertedFacesMesh2(), merge(), sibr::MaterialMesh::subdivideMesh(), and sibr::MaterialMesh::subdivideMesh2().
eraseTriangles()
void sibr::Mesh::eraseTriangles (const std::vector< uint > & faceIDList)
Erase some of the triangles.
Parameters
faceIDList a list of triangle IDs to erase
Definition at line 2109 of file Mesh.cpp.
References colors(), hasColors(), hasNormals(), hasTexCoords(), normals(), texCoords(), triangles(), and vertices().
extractSubMesh()
Mesh::SubMesh sibr::Mesh::extractSubMesh (const std::vector< int > & vertices, VERTEX_LIST_CHOICE v_choice) const
Extract a submesh based on a list of vertices to keep/remove.
Parameters
vertices a list of vertex indices
v_choice should the listed vertices be removed or kept
Returns
the extracted submesh with additional information
Definition at line 1383 of file Mesh.cpp.
References _gl, sibr::Mesh::BufferGL::bufferGL, colors(), sibr::Mesh::SubMesh::complementaryVertices, hasColors(), hasNormals(), hasTexCoords(), KEEP, sibr::Mesh::SubMesh::meshPtr, normals(), texCoords(), triangles(), and vertices().
forceBufferGLUpdate()
void sibr::Mesh::forceBufferGLUpdate (bool adjacency = false) const
Force upload of data to the GPU.
Parameters
adjacency should we give adjacent triangles info in buffer
Definition at line 1205 of file Mesh.cpp.
References _gl, sibr::Mesh::BufferGL::bufferGL, sibr::Mesh::BufferGL::dirtyBufferGL, and SIBR_ERR.
Referenced by render(), render_lines(), render_points(), and renderSubMesh().
freeBufferGLUpdate()
void sibr::Mesh::freeBufferGLUpdate (void) const
Delete GPU mesh data.
Definition at line 1212 of file Mesh.cpp.
References _gl, sibr::Mesh::BufferGL::bufferGL, and sibr::Mesh::BufferGL::dirtyBufferGL.
fromOffStream()
void sibr::Mesh::fromOffStream (std::stringstream & stream, bool generateNormals = true)
Definition at line 1730 of file Mesh.cpp.
References _gl, _triangles, _vertices, sibr::Mesh::BufferGL::bufferGL, sibr::Mesh::BufferGL::dirtyBufferGL, generateNormals(), and ibr_convert_old_to_new::line.
generateNormals()
void sibr::Mesh::generateNormals (void)
Generate vertex normals by using the average of all triangle normals around a each vertex.
Definition at line 739 of file Mesh.cpp.
References _gl, _normals, _triangles, _vertices, sibr::Mesh::BufferGL::dirtyBufferGL, and SIBR_ERR.
Referenced by adaptativeTaubinSmoothing(), sibr::MaterialMesh::addEnvironmentMap(), fromOffStream(), and laplacianSmoothing().
generateSmoothNormals()
void sibr::Mesh::generateSmoothNormals (int numIter)
Generate smooth vertex normals by using the average of all triangle normals around a each vertex and iterating this process.
Takes also the area of triangles as a weight.
Parameters
numIter iteration count
Definition at line 784 of file Mesh.cpp.
References _gl, _normals, _triangles, _vertices, sibr::Mesh::BufferGL::dirtyBufferGL, SIBR_ERR, and SIBR_LOG.
generateSmoothNormalsDisconnected()
void sibr::Mesh::generateSmoothNormalsDisconnected (int numIter)
Generate smooth vertex normals by using the average of all triangle normals around a each vertex and iterating this process.
Takes also the area of triangles as a weight. This methods also consider the fact that because of texture coordinates we may have duplicates vertices
Parameters
numIter iteration count
Definition at line 875 of file Mesh.cpp.
References _gl, _normals, _triangles, _vertices, sibr::Mesh::BufferGL::dirtyBufferGL, SIBR_ERR, and SIBR_LOG.
generateSubMesh()
Mesh sibr::Mesh::generateSubMesh (std::function< bool(int)> func) const
Generate a new mesh given a boolean function that state if each vertex should be kept or not.
Parameters
func the function that, based on a vertex ID, tells if it should be kept or not
Returns
the submesh
Definition at line 1130 of file Mesh.cpp.
References colors(), hasColors(), hasNormals(), hasTexCoords(), normals(), texCoords(), triangles(), and vertices().
getBoundingBox()
Eigen::AlignedBox< float, 3 > sibr::Mesh::getBoundingBox (void) const
Returns
the mesh bouding box.
Definition at line 1630 of file Mesh.cpp.
References _vertices.
Referenced by sibr::TrackBall::fromMesh(), and sibr::InteractiveCameraHandler::setup().
getBoundingSphere()
void sibr::Mesh::getBoundingSphere (Vector3f & outCenter, float & outRadius, bool referencedOnly = false, bool usePCcenter = false) const
Estimated the mesh bounding sphere.
Parameters
outCenter will contain the sphere center
outRadius will contain the sphere radius
referencedOnly if true, only consider vertices that are part of at least one face
usePCcenter if true, only consider vertices for center computation. Intended to be true when using the function on point clouds.
Definition at line 1566 of file Mesh.cpp.
References _triangles, _vertices, sibr::cross(), sibr::distance(), and SIBR_WRG.
Referenced by sibr::MaterialMesh::addEnvironmentMap().
getEnvSphere()
sibr::Mesh::Ptr sibr::Mesh::getEnvSphere (sibr::Vector3f center, float radius, sibr::Vector3f zenith, sibr::Vector3f north, PartOfSphere part = PartOfSphere::WHOLE) static
Definition at line 1639 of file Mesh.cpp.
References UP.
Referenced by sibr::MaterialMesh::addEnvironmentMap().
getMeshFilePath()
const std::string sibr::Mesh::getMeshFilePath (void) const inline
Returns
the path the mesh was loaded from.
Definition at line 1561 of file Mesh.cpp.
References _meshPath.
getOffStream()
std::stringstream sibr::Mesh::getOffStream (bool verbose = false) const
Definition at line 1706 of file Mesh.cpp.
References triangles(), and vertices().
getSphereMesh()
Mesh::Ptr sibr::Mesh::getSphereMesh (const Vector3f & center, float radius, bool withGraphics = true, int precision = 50) static
Generate a sphere mesh.
Parameters
center the sphere center
radius the sphere radius
withGraphics should the mesh be on the GPU
precision number of subdivisions on each dimension
Returns
the sphere mesh
Definition at line 1808 of file Mesh.cpp.
References Mesh(), normals(), and vertices().
getTestCube()
sibr::Mesh::Ptr sibr::Mesh::getTestCube (bool withGraphics = true) static
Generate a simple cube with normals.
Parameters
withGraphics should the mesh be on the GPU
Returns
a cube mesh
Definition at line 1786 of file Mesh.cpp.
References vertices().
Referenced by sibr::MeshViewer::demo(), and sibr::MultiMeshManager::MultiMeshManager().
getTextureImageFileName()
std::string sibr::Mesh::getTextureImageFileName () const inline
Returns
texture image file name
Definition at line 152 of file Mesh.hpp.
hasColors()
bool sibr::Mesh::hasColors (void) const inline
Returns
true if each vertex has a color assigned.
Definition at line 506 of file Mesh.hpp.
References _colors, and _vertices.
Referenced by clone(), eraseTriangles(), extractSubMesh(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), invertedFacesMesh(), invertedFacesMesh2(), merge(), saveToASCIIPLY(), saveToBinaryPLY(), sibr::Raycaster::smoothColor(), sibr::MaterialMesh::subdivideMesh(), sibr::MaterialMesh::subdivideMesh2(), and sibr::UVUnwrapper::unwrap().
hasNormals()
bool sibr::Mesh::hasNormals (void) const inline
Returns
true if each vertex has a normal assigned.
Definition at line 516 of file Mesh.hpp.
References _normals, and _vertices.
Referenced by clone(), eraseTriangles(), extractSubMesh(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), invertedFacesMesh(), invertedFacesMesh2(), sibr::MaterialMesh::loadMtsXML(), merge(), saveToASCIIPLY(), saveToBinaryPLY(), saveToObj(), sibr::MeshViewer::setMainMesh(), sibr::Raycaster::smoothNormal(), subDivide(), sibr::MaterialMesh::subdivideMesh(), sibr::MaterialMesh::subdivideMesh2(), sibr::UVUnwrapper::unwrap(), and sibr::UVUnwrapper::UVUnwrapper().
hasTexCoords()
bool sibr::Mesh::hasTexCoords (void) const inline
Returns
true if each vertex has texture coordinates assigned.
Definition at line 541 of file Mesh.hpp.
References _texcoords, and _vertices.
Referenced by clone(), eraseTriangles(), extractSubMesh(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), invertedFacesMesh(), invertedFacesMesh2(), merge(), saveToASCIIPLY(), saveToBinaryPLY(), saveToObj(), sibr::Raycaster::smoothUV(), sibr::MaterialMesh::subdivideMesh(), sibr::MaterialMesh::subdivideMesh2(), and sibr::UVUnwrapper::UVUnwrapper().
invertedFacesMesh()
sibr::Mesh sibr::Mesh::invertedFacesMesh () const
Returns
a copy of the mesh with inverted faces (flipping IDs).
Definition at line 1479 of file Mesh.cpp.
References _gl, sibr::Mesh::BufferGL::bufferGL, colors(), hasColors(), hasNormals(), hasTexCoords(), normals(), texCoords(), triangles(), and vertices().
Referenced by sibr::MaterialMesh::invertedFacesMesh2(), and invertedFacesMesh2().
invertedFacesMesh2()
sibr::Mesh::Ptr sibr::Mesh::invertedFacesMesh2 () const
Returns
a copy of the mesh with "doubled" faces (obtained by merging the current mesh with a copy with inverted faces.
Definition at line 1502 of file Mesh.cpp.
References _gl, sibr::Mesh::BufferGL::bufferGL, colors(), hasColors(), hasNormals(), hasTexCoords(), invertedFacesMesh(), normals(), texCoords(), triangles(), and vertices().
Referenced by sibr::CameraRaycaster::computeClippingPlanes(), and sibr::MaterialMesh::invertedFacesMesh2().
laplacianSmoothing()
void sibr::Mesh::laplacianSmoothing (int numIter, bool updateNormals)
Perform laplacian smoothing on the mesh vertices.
Parameters
numIter smoothing iteration count
updateNormals should the normals be recomputed after smoothing
Definition at line 999 of file Mesh.cpp.
References _triangles, _vertices, generateNormals(), and vertices().
load()
bool sibr::Mesh::load (const std::string & filename)
Load a mesh from the disk.
Parameters
filename the file path
Returns
a success flag
Note
Supports OBJ and PLY for now.
Definition at line 353 of file Mesh.cpp.
References _colors, _gl, _meshPath, _normals, _texcoords, _textureImageFileName, _triangles, _vertices, sibr::Mesh::BufferGL::dirtyBufferGL, sibr::fileExists(), SIBR_LOG, and SIBR_WRG.
Referenced by isRawRC(), loadRawRC(), and main().
loadMtsXML()
bool sibr::Mesh::loadMtsXML (const std::string & filename)
Load a scene from a set of mitsuba XML scene files (referencing multiple OBJs/PLYs).
It handles instances (duplicating the geoemtry and applying the per-instance transformation).
Parameters
filename the file path
Returns
a success flag
Definition at line 482 of file Mesh.cpp.
References load(), vertices(), and xyz().
Referenced by main().
makeWhole()
void sibr::Mesh::makeWhole (void)
Make the mesh whole, ie it will have default values for all components (texture, materials, colors, etc) It is useful when merging two meshes.
If the second one is missing some attributes, the merging will break the mesh state if it isn't made whole.
Definition at line 2096 of file Mesh.cpp.
Referenced by sibr::MaterialMesh::makeWhole().
meanEdgeSize()
float sibr::Mesh::meanEdgeSize () const
Returns
the mean edge size computed over all triangles.
Definition at line 2020 of file Mesh.cpp.
References triangles(), and vertices().
merge()
void sibr::Mesh::merge (const Mesh & other)
Merge another mesh into this one.
Parameters
other the mesh to merge
See also
makeWhole
Definition at line 2054 of file Mesh.cpp.
References _colors, _gl, _normals, _texcoords, _triangles, _vertices, sibr::Mesh::BufferGL::bufferGL, colors(), hasColors(), hasNormals(), hasTexCoords(), normals(), texCoords(), triangles(), and vertices().
Referenced by sibr::MaterialMesh::merge().
normalArray()
const float * sibr::Mesh::normalArray (void) const inline
Returns
normals in an array using the following format: {0x, 0y, 0z, 1x, 1y, 1z, 2x, 2y, 2z, ...}. Useful for rendering and converting to another mesh struct.
Definition at line 529 of file Mesh.hpp.
References _normals.
Referenced by sibr::UVUnwrapper::UVUnwrapper().
normals() [1/3]
void sibr::Mesh::normals (const Normals & normals) inline
Set vertex normals.
Parameters
normals the new vertex normals
Definition at line 510 of file Mesh.hpp.
References _gl, _normals, sibr::Mesh::BufferGL::dirtyBufferGL, and normals().
Referenced by sibr::MeshBufferGL::build(), extractSubMesh(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), PlaneEstimator::getMeshPlane(), invertedFacesMesh(), invertedFacesMesh2(), sibr::MaterialMesh::loadMtsXML(), merge(), sibr::MeshViewer::setMainMesh(), sibr::Raycaster::smoothNormal(), and sibr::UVUnwrapper::unwrap().
normals() [2/3]
void sibr::Mesh::normals (const std::vector< float > & normals)
Set normals using a flat vector of floats.
Parameters
normals the new vertex normals
Definition at line 719 of file Mesh.cpp.
References _gl, _normals, sibr::Mesh::BufferGL::dirtyBufferGL, and normals().
normals() [3/3]
const Mesh::Normals & sibr::Mesh::normals (void) const inline
Returns
a reference to the vertex normals list.
Definition at line 513 of file Mesh.hpp.
References _normals.
Referenced by clone(), eraseTriangles(), extractSubMesh(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), getSphereMesh(), invertedFacesMesh(), invertedFacesMesh2(), sibr::MaterialMesh::loadMtsXML(), merge(), normals(), subDivide(), sibr::MaterialMesh::subdivideMesh(), and sibr::MaterialMesh::subdivideMesh2().
removeDisconnectedComponents()
std::vector< std::vector< int > > sibr::Mesh::removeDisconnectedComponents ()
Split a mesh in its connected components.
Returns
a list of list of vertex indices, each list defining a component
Definition at line 2180 of file Mesh.cpp.
References triangles(), and vertices().
render()
void sibr::Mesh::render (bool depthTest = true, bool backFaceCulling = true, RenderMode mode = FillRenderMode, bool frontFaceCulling = false, bool invertDepthTest = false, bool tessellation = false, bool adjacency = false) const
Render the geometry using OpenGL.
Parameters
depthTest should depth testing be performed
backFaceCulling should culling be performed
mode the primitives rendering mode
frontFaceCulling should the culling test be flipped
invertDepthTest should the depth test be flipped (GL_GREATER_THAN)
tessellation should the rendering call tesselation shaders
adjacency should we get adjacent triangles info in geometry shader
Definition at line 1218 of file Mesh.cpp.
References _gl, _renderingOptions, _triangles, _vertices, sibr::Mesh::RenderingOptions::adjacency, sibr::Mesh::RenderingOptions::backFaceCulling, sibr::Mesh::BufferGL::bufferGL, sibr::Mesh::RenderingOptions::depthTest, sibr::Mesh::BufferGL::dirtyBufferGL, FillRenderMode, forceBufferGLUpdate(), sibr::Mesh::RenderingOptions::frontFaceCulling, sibr::Mesh::RenderingOptions::invertDepthTest, LineRenderMode, sibr::Mesh::RenderingOptions::mode, PointRenderMode, SIBR_ERR, and sibr::Mesh::RenderingOptions::tessellation.
Referenced by sibr::DrawUtilities::baseRendering(), sibr::Intersector2D::frustrumQuadsIntersect(), sibr::BinaryMeshRenderer::process(), sibr::ColoredMeshRenderer::process(), sibr::TexturedMeshRenderer::process(), sibr::ULRV2Renderer::process(), sibr::ULRRenderer::process(), sibr::MaterialMesh::render(), sibr::PositionRenderer::render(), sibr::DepthRenderer::render(), sibr::NormalRenderer::render(), sibr::ShadowMapRenderer::render(), sibr::ULRV3Renderer::renderProxyDepth(), and sibr::MaterialMesh::renderThreeSixty().
render_lines()
void sibr::Mesh::render_lines (void) const
Render the mesh vertices as successive lines.
Note
The depth test state will be whatever it is currently set to.
Definition at line 1375 of file Mesh.cpp.
References _gl, sibr::Mesh::BufferGL::bufferGL, sibr::Mesh::BufferGL::dirtyBufferGL, forceBufferGLUpdate(), and SIBR_ERR.
render_points() [1/2]
void sibr::Mesh::render_points (bool depthTest) const
Render the mesh vertices as points.
Parameters
depthTest should depth testing be performed
Definition at line 1361 of file Mesh.cpp.
References render_points().
render_points() [2/2]
void sibr::Mesh::render_points (void) const
Render the mesh vertices as points.
Note
The depth test state will be whatever it is currently set to.
Definition at line 1353 of file Mesh.cpp.
References _gl, sibr::Mesh::BufferGL::bufferGL, and forceBufferGLUpdate().
Referenced by render_points().
renderSubMesh()
void sibr::Mesh::renderSubMesh (unsigned int begin, unsigned int end, bool depthTest = true, bool backFaceCulling = true, RenderMode mode = FillRenderMode, bool frontFaceCulling = false, bool invertDepthTest = false) const
Render a part of the geometry (taken either from the index buffer or directly in the vertex buffer) using OpenGL.
Parameters
begin first item to render index
end last item to render index
depthTest should depth testing be performed
backFaceCulling should culling be performed
mode the primitives rendering mode
frontFaceCulling should the culling test be flipped
invertDepthTest should the depth test be flipped (GL_GREATER_THAN)
Definition at line 1292 of file Mesh.cpp.
References _gl, _triangles, _vertices, sibr::Mesh::BufferGL::bufferGL, sibr::Mesh::BufferGL::dirtyBufferGL, FillRenderMode, forceBufferGLUpdate(), LineRenderMode, PointRenderMode, and SIBR_ERR.
replaceVertice()
void sibr::Mesh::replaceVertice (int vertex_id, const sibr::Vector3f & v) inline
Update a specific vertex position.
Parameters
vertex_id the vertex location in the list
v the new value
Note
If the mesh is used by the GPU, data will be udpated.
Definition at line 484 of file Mesh.hpp.
References _gl, _vertices, sibr::Mesh::BufferGL::dirtyBufferGL, and vertices().
save()
void sibr::Mesh::save (const std::string & filename, bool universal = false, const std::string & textureName = "TEXTURE_NAME_TO_PUT_IN_THE_FILE") const
Save the mesh to the disk.
When saving as a PLY, use the universal flag to indicate if you want this mesh to be readable by most 3d applications (e.g. MeshLab). In this other case, the mesh will be saved with higher-precision custom PLY attributes.
Parameters
filename the file path
universal if true, the mesh will be compatible with external 3D viewers
textureName name of a texture to reference in the file (Meshlab compatible)
Note
Supports OBJ (ignoring the universal flag) and PLY for now.
Definition at line 633 of file Mesh.cpp.
References sibr::getExtension(), saveToASCIIPLY(), saveToBinaryPLY(), saveToObj(), SIBR_ERR, and vertices().
Referenced by main().
saveToASCIIPLY()
bool sibr::Mesh::saveToASCIIPLY (const std::string & filename, bool universal = false, const std::string & textureName = "TEXTURE_NAME_TO_PUT_IN_THE_FILE") const
Save the mesh to .ply file (using the ASCII version).
Parameters
filename the file path
universal indicates if you want this mesh to be readable by most 3d viewer application (e.g. MeshLab).
textureName name of a texture to reference in the file (Meshlab compatible) In this other case, the mesh will be saved with higher-precision custom PLY attributes.
Definition at line 232 of file Mesh.cpp.
References _colors, _normals, _texcoords, _triangles, _vertices, hasColors(), hasNormals(), hasTexCoords(), and SIBR_LOG.
Referenced by save().
saveToBinaryPLY()
bool sibr::Mesh::saveToBinaryPLY (const std::string & filename, bool universal = false, const std::string & textureName = "TEXTURE_NAME_TO_PUT_IN_THE_FILE") const
Save the mesh to .ply file (using the binary version).
Parameters
filename the file path
universal indicates if you want this mesh to be readable by most 3d viewer application (e.g. MeshLab). In this other case, the mesh will be saved with higher-precision custom PLY attributes.
textureName name of a texture to reference in the file (Meshlab compatible)
Definition at line 115 of file Mesh.cpp.
References _colors, _normals, _texcoords, _triangles, _vertices, sibr::ByteStream::buffer(), sibr::ByteStream::bufferSize(), hasColors(), hasNormals(), hasTexCoords(), and SIBR_LOG.
Referenced by save().
saveToObj()
bool sibr::Mesh::saveToObj (const std::string & filename) const
Save the mesh to .obj file.
Parameters
filename the file path
Warning
the vertex colros won't be saved
Definition at line 33 of file Mesh.cpp.
References _normals, _texcoords, _triangles, _vertices, hasNormals(), hasTexCoords(), and SIBR_LOG.
Referenced by save().
SIBR_CLASS_PTR()
sibr::Mesh::SIBR_CLASS_PTR (Mesh) private
subDivide()
sibr::Mesh::Ptr sibr::Mesh::subDivide (float limitSize, size_t maxRecursion = std::numeric_limits<size_t>::max()) const
Subdivide a mesh triangles until an edge size threshold is reached.
Parameters
limitSize the maximum edge length allowed
maxRecursion maximum subdivision iteration count
Returns
the subdivided mesh
Bug:
SR: Can be stuck in a loop in some cases.
Definition at line 1853 of file Mesh.cpp.
References hasNormals(), sibr::length(), normals(), triangles(), and vertices().
texCoordArray()
const float * sibr::Mesh::texCoordArray (void) const inline
Returns
texture coordinate in an array using the following format: {0u, 0v, 1u, 1v, 2u, 2v, ...} Useful for rendering and converting to another mesh struct.
Definition at line 546 of file Mesh.hpp.
References _texcoords.
Referenced by sibr::UVUnwrapper::UVUnwrapper().
texCoords() [1/3]
void sibr::Mesh::texCoords (const std::vector< float > & texcoords)
Set texture coordinates using a flat vector of floats.
Parameters
texcoords the new vertex texture coordinates
Definition at line 699 of file Mesh.cpp.
References _gl, _texcoords, and sibr::Mesh::BufferGL::dirtyBufferGL.
texCoords() [2/3]
void sibr::Mesh::texCoords (const UVs & texcoords) inline
Set vertex texture coordinates.
Parameters
texcoords the new vertex texture coordinates
Definition at line 533 of file Mesh.hpp.
References _gl, _texcoords, and sibr::Mesh::BufferGL::dirtyBufferGL.
Referenced by sibr::MeshBufferGL::build(), sibr::RenderUtility::createScreenQuad(), extractSubMesh(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), invertedFacesMesh(), invertedFacesMesh2(), merge(), and sibr::Raycaster::smoothUV().
texCoords() [3/3]
const Mesh::UVs & sibr::Mesh::texCoords (void) const inline
Returns
a reference to the vertex texture coordinates list.
Definition at line 537 of file Mesh.hpp.
References _texcoords.
Referenced by clone(), eraseTriangles(), extractSubMesh(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), invertedFacesMesh(), invertedFacesMesh2(), sibr::MaterialMesh::subdivideMesh(), and sibr::MaterialMesh::subdivideMesh2().
triangleArray()
const uint * sibr::Mesh::triangleArray (void) const inline
Returns
triangles in an array using the following format: {0a, 0b, 0c, 1a, 1b, 1c, 2a, 2b, 2c, ...}. Useful for rendering and converting to another mesh struct.
Definition at line 523 of file Mesh.hpp.
References _triangles.
Referenced by sibr::MeshBufferGL::fetchIndices(), and sibr::UVUnwrapper::UVUnwrapper().
triangles() [1/3]
void sibr::Mesh::triangles (const std::vector< uint > & triangles)
Set triangles.
Using a flat vector of uints.
Parameters
triangles the new indices
Definition at line 679 of file Mesh.cpp.
References _gl, _triangles, sibr::Mesh::BufferGL::dirtyBufferGL, and triangles().
triangles() [2/3]
void sibr::Mesh::triangles (const Triangles & triangles) inline
Set triangles.
Each triangle contains 3 indices and each indice correspond to a vertex in the vertices list.
Parameters
triangles the list of indices to use
Definition at line 492 of file Mesh.hpp.
References _gl, _triangles, sibr::Mesh::BufferGL::dirtyBufferGL, and triangles().
Referenced by sibr::MaterialMesh::addEnvironmentMap(), sibr::Raycaster::addGenericMesh(), sibr::MultiViewInterface::addMesh(), sibr::RenderUtility::createCameraStub(), sibr::RenderUtility::createScreenQuad(), sibr::DatasetView::displayRepro(), extractSubMesh(), sibr::MeshBufferGL::fetchIndices(), sibr::Intersector2D::frustrumQuadsIntersect(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), PlaneEstimator::getMeshPlane(), invertedFacesMesh(), invertedFacesMesh2(), merge(), sibr::MeshViewer::setMainMesh(), sibr::MeshTexturing::setMesh(), sibr::Raycaster::smoothColor(), sibr::Raycaster::smoothNormal(), sibr::Raycaster::smoothUV(), and sibr::UVUnwrapper::UVUnwrapper().
triangles() [3/3]
const Mesh::Triangles & sibr::Mesh::triangles (void) const inline
Returns
a reference to the triangles list.
Definition at line 496 of file Mesh.hpp.
References _triangles.
Referenced by sibr::MaterialMesh::ambientOcclusion(), clone(), eraseTriangles(), extractSubMesh(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), getOffStream(), invertedFacesMesh(), sibr::MaterialMesh::invertedFacesMesh2(), invertedFacesMesh2(), sibr::MaterialMesh::makeWhole(), meanEdgeSize(), merge(), removeDisconnectedComponents(), subDivide(), sibr::MaterialMesh::subdivideMesh(), sibr::MaterialMesh::subdivideMesh2(), and triangles().
vertexArray()
const float * sibr::Mesh::vertexArray (void) const inline
Returns
vertices in an array using the following format: {0x, 0y, 0z, 1x, 1y, 1z, 2x, 2y, 2z, ...}. Useful for rendering and converting to another mesh struct.
Definition at line 520 of file Mesh.hpp.
References _vertices.
Referenced by sibr::UVUnwrapper::UVUnwrapper().
vertices() [1/3]
void sibr::Mesh::vertices (const std::vector< float > & vertices)
Set vertices from a vector of floats (linear).
Parameters
vertices the new vertices
Definition at line 659 of file Mesh.cpp.
References _gl, _vertices, sibr::Mesh::BufferGL::dirtyBufferGL, and vertices().
vertices() [2/3]
void sibr::Mesh::vertices (const Vertices & vertices) inline
Set vertices.
Parameters
vertices the new vertices
Definition at line 476 of file Mesh.hpp.
References _gl, _vertices, sibr::Mesh::BufferGL::dirtyBufferGL, and vertices().
Referenced by sibr::Raycaster::addGenericMesh(), sibr::MultiViewInterface::addMesh(), sibr::MeshBufferGL::build(), sibr::RenderUtility::createCameraStub(), sibr::RenderUtility::createScreenQuad(), sibr::DatasetView::displayRepro(), extractSubMesh(), sibr::Intersector2D::frustrumQuadsIntersect(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), PlaneEstimator::getMeshPlane(), invertedFacesMesh(), invertedFacesMesh2(), loadMtsXML(), sibr::MaterialMesh::loadMtsXML(), main(), sibr::MaterialMesh::merge(), merge(), sibr::MeshViewer::setMainMesh(), sibr::MeshTexturing::setMesh(), sibr::UVUnwrapper::unwrap(), sibr::UVUnwrapper::UVUnwrapper(), and sibr::Raycaster::xformRtcMeshOnly().
vertices() [3/3]
const Mesh::Vertices & sibr::Mesh::vertices (void) const inline
Returns
a reference to the vertices.
Definition at line 480 of file Mesh.hpp.
References _vertices.
Referenced by adaptativeTaubinSmoothing(), sibr::MaterialMesh::ambientOcclusion(), clone(), eraseTriangles(), extractSubMesh(), sibr::MaterialMesh::fillColorsWithIndexMaterials(), sibr::MaterialMesh::fillColorsWithMatIds(), sibr::MaterialMesh::generateSubMaterialMesh(), generateSubMesh(), getOffStream(), getSphereMesh(), getTestCube(), invertedFacesMesh(), sibr::MaterialMesh::invertedFacesMesh2(), invertedFacesMesh2(), laplacianSmoothing(), sibr::MaterialMesh::loadMtsXML(), sibr::MaterialMesh::makeWhole(), meanEdgeSize(), sibr::MaterialMesh::merge(), merge(), removeDisconnectedComponents(), replaceVertice(), save(), subDivide(), sibr::MaterialMesh::subdivideMesh(), sibr::MaterialMesh::subdivideMesh2(), and vertices().
Member Data Documentation
_colors
Colors sibr::Mesh::_colors
Vertex colors.
Definition at line 465 of file Mesh.hpp.
Referenced by adaptativeTaubinSmoothing(), colorArray(), colors(), hasColors(), sibr::MaterialMesh::load(), load(), merge(), saveToASCIIPLY(), and saveToBinaryPLY().
_gl
BufferGL sibr::Mesh::_gl mutable
Internal OpenGL data.
Definition at line 456 of file Mesh.hpp.
Referenced by clone(), colors(), extractSubMesh(), forceBufferGLUpdate(), sibr::MaterialMesh::forceBufferGLUpdate(), sibr::MaterialMesh::freeBufferGLUpdate(), freeBufferGLUpdate(), fromOffStream(), generateNormals(), generateSmoothNormals(), generateSmoothNormalsDisconnected(), invertedFacesMesh(), invertedFacesMesh2(), sibr::MaterialMesh::load(), load(), merge(), Mesh(), normals(), render(), render_lines(), render_points(), renderSubMesh(), replaceVertice(), texCoords(), triangles(), and vertices().
_meshPath
std::string sibr::Mesh::_meshPath private
Source path, can be used to reload the mesh with/without graphics option in constructor.
Definition at line 469 of file Mesh.hpp.
Referenced by getMeshFilePath(), and load().
_normals
Normals sibr::Mesh::_normals
Vertex normals.
Definition at line 464 of file Mesh.hpp.
Referenced by generateNormals(), generateSmoothNormals(), generateSmoothNormalsDisconnected(), hasNormals(), sibr::MaterialMesh::load(), load(), merge(), normalArray(), normals(), saveToASCIIPLY(), saveToBinaryPLY(), and saveToObj().
_renderingOptions
RenderingOptions sibr::Mesh::_renderingOptions mutable private
Definition at line 471 of file Mesh.hpp.
Referenced by render().
_texcoords
UVs sibr::Mesh::_texcoords
Vertex UVs.
Definition at line 466 of file Mesh.hpp.
Referenced by hasTexCoords(), sibr::MaterialMesh::load(), load(), merge(), saveToASCIIPLY(), saveToBinaryPLY(), saveToObj(), texCoordArray(), and texCoords().
_textureImageFileName
std::string sibr::Mesh::_textureImageFileName private
Definition at line 470 of file Mesh.hpp.
Referenced by load().
_triangles
Triangles sibr::Mesh::_triangles
Triangle indices.
Definition at line 463 of file Mesh.hpp.
Referenced by adaptativeTaubinSmoothing(), sibr::MaterialMesh::fillColorsWithIndexMaterials(), sibr::MaterialMesh::fillColorsWithMatIds(), fromOffStream(), generateNormals(), generateSmoothNormals(), generateSmoothNormalsDisconnected(), getBoundingSphere(), sibr::MaterialMesh::hasMatIds(), laplacianSmoothing(), sibr::MaterialMesh::load(), load(), merge(), render(), renderSubMesh(), saveToASCIIPLY(), saveToBinaryPLY(), saveToObj(), triangleArray(), and triangles().
_vertices
Vertices sibr::Mesh::_vertices
Vertex positions.
Definition at line 462 of file Mesh.hpp.
Referenced by adaptativeTaubinSmoothing(), centroid(), fromOffStream(), generateNormals(), generateSmoothNormals(), generateSmoothNormalsDisconnected(), getBoundingBox(), getBoundingSphere(), hasColors(), sibr::MaterialMesh::hasMeshIds(), hasNormals(), hasTexCoords(), laplacianSmoothing(), sibr::MaterialMesh::load(), load(), sibr::MaterialMesh::merge(), merge(), render(), renderSubMesh(), replaceVertice(), saveToASCIIPLY(), saveToBinaryPLY(), saveToObj(), vertexArray(), and vertices().
The documentation for this class was generated from the following files:
src/core/graphics/Mesh.hpp
src/core/graphics/Mesh.cpp