SIBR: sibr::MaterialMesh Class Reference
sibr::MaterialMesh Class Reference
sibr_graphics
Store both CPU and GPU data for a geometric mesh.
#include <MaterialMesh.hpp>
Classes
struct AmbientOcclusion
Ambient occlusion options.
Public Types
enum RenderCategory { RenderCategory::classic, RenderCategory::diffuseMaterials, RenderCategory::threesixtyMaterials, RenderCategory::threesixtyDepth }
Synthetic data rendering options.
typedef std::vector< int > MatIds
typedef std::vector< int > MeshIds
typedef std::vector< std::string > MatId2Name
typedef std::map< std::string, sibr::ImageRGB::Ptr > OpacityMaps
typedef std::map< std::string, sibr::ImageRGBA::Ptr > DiffuseMaps
typedef sibr::ImageRGB::Ptr TagsMap
typedef std::map< std::string, sibr::ImageRGB::Ptr > TagsCoveringMaps
typedef std::vector< Mesh > SubMeshes
typedef std::vector< sibr::ImageRGBA > AlbedoTextures
typedef std::map< std::string, bool > SwitchTagsProperty
typedef struct AmbientOcclusion AmbientOcclusion
Public Types inherited from sibr::Mesh
enum RenderMode { PointRenderMode, LineRenderMode, FillRenderMode }
Mesh rendering mode.
enum VERTEX_LIST_CHOICE { VERTEX_LIST_CHOICE::KEEP, VERTEX_LIST_CHOICE::REMOVE }
Submesh extraction options.
enum PartOfSphere { PartOfSphere::WHOLE, PartOfSphere::UP, PartOfSphere::BOTTOM }
Environment sphere generation options: top/bottom parts or both.
typedef std::vector< Vector3f > Vertices
typedef std::vector< Vector3f > Normals
typedef std::vector< Vector3u > Triangles
typedef std::vector< Vector3f > Colors
typedef std::vector< Vector2f > UVs
Public Member Functions
SIBR_CLASS_PTR (MaterialMesh)
MaterialMesh (bool withGraphics=true)
Constructor.
MaterialMesh (sibr::Mesh &mesh)
Constructor from a basic mesh.
void matIds (const MatIds &matIds)
Set material IDs (per triangle)
const MatIds & matIds (void) const
const MatIds & matIdsVertices (void) const
bool hasMatIds (void) const
const MatId2Name & matId2Name (void) const
void matId2Name (const MatId2Name &matId2Name)
Set the mapping between IDs and material names.
void meshIds (const MeshIds &meshIds)
Set the mesh ID of each vertex.
const MeshIds & meshIds (void) const
bool hasMeshIds (void) const
sibr::ImageRGB::Ptr opacityMap (const std::string &matName) const
Query a material opacity map.
void opacityMaps (const OpacityMaps &maps)
Set all material opacity maps.
const OpacityMaps & opacityMaps (void) const
void switchTag (const SwitchTagsProperty &switchTag)
Set the switchTag.
const SwitchTagsProperty & switchTag (void) const
get the switchTag
sibr::ImageRGBA::Ptr diffuseMap (const std::string &matName) const
Return the pointer to oppacity texture if it exist.
void diffuseMaps (const DiffuseMaps &maps)
Set all material diffuse maps.
const DiffuseMaps & diffuseMaps (void) const
void hasTagsFile (bool hasOrNot)
Indicate if the mesh has an associated tag file (for calibration).
const bool hasTagsFile (void) const
void tagsMap (const TagsMap &map)
Set the tag map.
const TagsMap & tagsMap (void) const
void hasTagsCoveringFile (bool hasOrNot)
Indicate if the mesh has an associated covering tag file (for calibration).
const bool hasTagsCoveringFile (void) const
void tagsCoveringMaps (const TagsCoveringMaps &map)
Set the covering tag map.
const TagsCoveringMaps & tagsCoveringMaps (void) const
sibr::ImageRGB::Ptr tagsCoveringMap (const std::string &matName) const
Return the pointer to oppacity texture if it exist.
void subMeshes (const SubMeshes &subMeshes)
Set the sub meshes.
const SubMeshes & subMeshes (void) const
void typeOfRender (const RenderCategory &type)
Set the synthetic rendering mode.
const RenderCategory & typeOfRender (void) const
void ambientOcclusion (const AmbientOcclusion &ao)
Set the ambient occlusion options and compute AO values, storing them in the vertex colors.
const AmbientOcclusion & ambientOcclusion (void)
void aoFunction (std::function< sibr::Mesh::Colors(sibr::MaterialMesh &, const int)> &aoFunction)
Set the function used to compute ambient occlusion at each vertex.
bool load (const std::string &filename)
Load a mesh from the disk.
bool loadMtsXML (const std::string &xmlFile, bool loadTextures=true)
Load a scene from a set of mitsuba XML scene files (referencing multiple OBJs/PLYs).
void loadCoveringTagsTexture (const std::vector< std::string > &listFilesTags)
void fillColorsWithIndexMaterials ()
Attribute a random color at each vertex based on the material IDs of the faces it belongs to.
void fillColorsWithMatIds ()
Store the material ID of each vertex in its color attribute (R: bits 0-7, G: 8-15, B: 16-23).
void merge (const MaterialMesh &other)
Merge another mesh into this one.
void makeWhole (void)
Make the mesh whole, ie it will have default values for all components (texture, materials, colors, etc) It is useful when merging two meshes.
void createSubMeshes (void)
Split the mesh geometry in multiple submeshes based on each vertex material ID.
sibr::MaterialMesh::Ptr invertedFacesMesh2 () const
void forceBufferGLUpdate (void) const
Force upload of data to the GPU.
void freeBufferGLUpdate (void) const
Delete GPU mesh data.
void subdivideMesh2 (float threshold)
Subdivide a mesh triangles until a triangle area threshold is reached.
void subdivideMesh (float threshold)
Subdivide a mesh triangles until an edge length threshold is reached.
void addEnvironmentMap (float *forcedCenterX=nullptr, float *forcedCenterY=nullptr, float *forcedCenterZ=nullptr, float *forcedRadius=nullptr)
Add an environment sphere to the mesh, surrounding the existing geometry.
void render (bool depthTest=true, bool backFaceCulling=true, RenderMode mode=FillRenderMode, bool frontFaceCulling=false, bool invertDepthTest=false, bool tessellation=false, bool adjacency=false) const
Render the geometry using OpenGL.
void renderAlbedo (bool depthTest=true, bool backFaceCulling=true, RenderMode mode=FillRenderMode, bool frontFaceCulling=false, bool invertDepthTest=false, bool specificMaterial=false, std::string nameOfSpecificMaterial="") const
Render the geometry with albedo and tag textures.
void renderThreeSixty (bool depthTest, bool backFaceCulling, RenderMode mode, bool frontFaceCulling, bool invertDepthTest) const
Render the geometry for 360 environment maps.
void initAlbedoTextures (void)
Upload the material textures to the GPU.
Mesh generateSubMaterialMesh (int material) const
Generate a mesh containing all triangles with a given material.
Public Member Functions inherited from sibr::Mesh
Mesh (bool withGraphics=true)
Constructor.
void vertices (const Vertices &vertices)
Set vertices.
void vertices (const std::vector< float > &vertices)
Set vertices from a vector of floats (linear).
const Vertices & vertices (void) const
void replaceVertice (int vertex_id, const sibr::Vector3f &v)
Update a specific vertex position.
Mesh::Ptr clone () const
const float * vertexArray (void) const
void triangles (const Triangles &triangles)
Set triangles.
void triangles (const std::vector< uint > &triangles)
Set triangles.
const Triangles & triangles (void) const
const uint * triangleArray (void) const
void colors (const Colors &colors)
Set vertex colors.
const Colors & colors (void) const
bool hasColors (void) const
const float * colorArray (void) const
void texCoords (const UVs &texcoords)
Set vertex texture coordinates.
void texCoords (const std::vector< float > &texcoords)
Set texture coordinates using a flat vector of floats.
const UVs & texCoords (void) const
bool hasTexCoords (void) const
const float * texCoordArray (void) const
std::string getTextureImageFileName () const
void normals (const Normals &normals)
Set vertex normals.
void normals (const std::vector< float > &normals)
Set normals using a flat vector of floats.
const Normals & normals (void) const
bool hasNormals (void) const
const float * normalArray (void) const
void makeWhole (void)
Make the mesh whole, ie it will have default values for all components (texture, materials, colors, etc) It is useful when merging two meshes.
void generateNormals (void)
Generate vertex normals by using the average of all triangle normals around a each vertex.
void generateSmoothNormals (int numIter)
Generate smooth vertex normals by using the average of all triangle normals around a each vertex and iterating this process.
void generateSmoothNormalsDisconnected (int numIter)
Generate smooth vertex normals by using the average of all triangle normals around a each vertex and iterating this process.
void laplacianSmoothing (int numIter, bool updateNormals)
Perform laplacian smoothing on the mesh vertices.
void adaptativeTaubinSmoothing (int numIter, bool updateNormals)
Perform adaptive Taubin smoothing on the mesh vertices.
Mesh generateSubMesh (std::function< bool(int)> func) const
Generate a new mesh given a boolean function that state if each vertex should be kept or not.
bool load (const std::string &filename)
Load a mesh from the disk.
bool loadMtsXML (const std::string &filename)
Load a scene from a set of mitsuba XML scene files (referencing multiple OBJs/PLYs).
void save (const std::string &filename, bool universal=false, const std::string &textureName="TEXTURE_NAME_TO_PUT_IN_THE_FILE") const
Save the mesh to the disk.
bool saveToBinaryPLY (const std::string &filename, bool universal=false, const std::string &textureName="TEXTURE_NAME_TO_PUT_IN_THE_FILE") const
Save the mesh to .ply file (using the binary version).
bool saveToASCIIPLY (const std::string &filename, bool universal=false, const std::string &textureName="TEXTURE_NAME_TO_PUT_IN_THE_FILE") const
Save the mesh to .ply file (using the ASCII version).
bool saveToObj (const std::string &filename) const
Save the mesh to .obj file.
std::stringstream getOffStream (bool verbose=false) const
void fromOffStream (std::stringstream &stream, bool generateNormals=true)
void render (bool depthTest=true, bool backFaceCulling=true, RenderMode mode=FillRenderMode, bool frontFaceCulling=false, bool invertDepthTest=false, bool tessellation=false, bool adjacency=false) const
Render the geometry using OpenGL.
void renderSubMesh (unsigned int begin, unsigned int end, bool depthTest=true, bool backFaceCulling=true, RenderMode mode=FillRenderMode, bool frontFaceCulling=false, bool invertDepthTest=false) const
Render a part of the geometry (taken either from the index buffer or directly in the vertex buffer) using OpenGL.
void forceBufferGLUpdate (bool adjacency=false) const
Force upload of data to the GPU.
void freeBufferGLUpdate (void) const
Delete GPU mesh data.
void render_points (bool depthTest) const
Render the mesh vertices as points.
void render_points (void) const
Render the mesh vertices as points.
void render_lines (void) const
Render the mesh vertices as successive lines.
void merge (const Mesh &other)
Merge another mesh into this one.
void eraseTriangles (const std::vector< uint > &faceIDList)
Erase some of the triangles.
SubMesh extractSubMesh (const std::vector< int > &vertices, VERTEX_LIST_CHOICE v_choice) const
Extract a submesh based on a list of vertices to keep/remove.
sibr::Mesh invertedFacesMesh () const
sibr::Mesh::Ptr invertedFacesMesh2 () const
const std::string getMeshFilePath (void) const
Eigen::AlignedBox< float, 3 > getBoundingBox (void) const
sibr::Vector3f centroid () const
void getBoundingSphere (Vector3f &outCenter, float &outRadius, bool referencedOnly=false, bool usePCcenter=false) const
Estimated the mesh bounding sphere.
sibr::Mesh::Ptr subDivide (float limitSize, size_t maxRecursion=std::numeric_limits< size_t >::max()) const
Subdivide a mesh triangles until an edge size threshold is reached.
float meanEdgeSize () const
std::vector< std::vector< int > > removeDisconnectedComponents ()
Split a mesh in its connected components.
Public Attributes
std::string vertexShaderAlbedo
std::string fragmentShaderAlbedo
std::string fragmentShaderAlbedoTag
Public Attributes inherited from sibr::Mesh
BufferGL _gl
Internal OpenGL data.
Vertices _vertices
Vertex positions.
Triangles _triangles
Triangle indices.
Normals _normals
Vertex normals.
Colors _colors
Vertex colors.
UVs _texcoords
Vertex UVs.
Private Attributes
MatIds _matIds
Per triangle material ID.
MatIds _matIdsVertices
Per vertex material ID.
MatId2Name _matId2Name
ID to name material mapping.
MeshIds _meshIds
Per-vertex submesh ID.
size_t _maxMeshId = 0
Maximum submesh ID encounter.
OpacityMaps _opacityMaps
Material opacity images.
DiffuseMaps _diffuseMaps
Material diffuse images.
TagsMap _tagsMap
Material tag images.
TagsCoveringMaps _tagsCoveringMaps
Material covering tag images.
std::vector< std::string > uniformColorMtlList
List of materials with a diffuse map.
SubMeshes _subMeshes
Submeshes, one per material, for rendering them separately.
RenderCategory _typeOfRender = RenderCategory::diffuseMaterials
Synthetic rendering mode.
bool _albedoTexturesInitialized = false
Are the texture initialized.
std::vector< sibr::Texture2DRGBA::Ptr > _albedoTextures
Albedo textures.
std::vector< GLuint > _idTextures
Texture handles.
std::vector< sibr::Texture2DRGB::Ptr > _opacityTextures
Opacity textures.
std::vector< GLuint > _idTexturesOpacity
Opacity texture handles.
bool _hasTagsFile = false
Is a tag file associated to the mesh.
sibr::Texture2DRGB::Ptr _tagTexture
Tag texture.
GLuint _idTagTexture = 0
Tag texture handle.
bool _hasTagsCoveringFile = false
Is a covering tag file associated to the mesh.
sibr::Texture2DRGB::Ptr _tagCoveringTexture
Convering tag texture.
GLuint _idTagCoveringTexture = 0
Covering tag texture handle.
std::vector< sibr::ImageRGB::Ptr > _listCoveringImagesTags
std::map< std::string, sibr::Texture2DRGB::Ptr > _tagsCoveringTexture
std::map< std::string, GLuint > _idTagsCoveringTexture
SwitchTagsProperty _switchTags
float _currentThreshold
AmbientOcclusion _ambientOcclusion
AO options.
std::function< sibr::Mesh::Colors(sibr::MaterialMesh &, const int)> _aoFunction
AO generation function.
bool _aoInitialized = false
Is AO data initialized.
float _averageSize = 0.0f
Average maximum edge length.
float _averageArea = 0.0f
Average triangle area.
Additional Inherited Members
Static Public Member Functions inherited from sibr::Mesh
static sibr::Mesh::Ptr getTestCube (bool withGraphics=true)
Generate a simple cube with normals.
static Mesh::Ptr getSphereMesh (const Vector3f &center, float radius, bool withGraphics=true, int precision=50)
Generate a sphere mesh.
static sibr::Mesh::Ptr getEnvSphere (sibr::Vector3f center, float radius, sibr::Vector3f zenith, sibr::Vector3f north, PartOfSphere part=PartOfSphere::WHOLE)
Detailed Description
Store both CPU and GPU data for a geometric mesh.
Specifically designed for synthetic scenes with material information. Provide many processing and display methods.
Definition at line 23 of file MaterialMesh.hpp.
Member Typedef Documentation
AlbedoTextures
typedef std::vector<sibr::ImageRGBA> sibr::MaterialMesh::AlbedoTextures
Definition at line 37 of file MaterialMesh.hpp.
AmbientOcclusion
typedef struct AmbientOcclusion sibr::MaterialMesh::AmbientOcclusion
Definition at line 41 of file MaterialMesh.hpp.
DiffuseMaps
typedef std::map<std::string, sibr::ImageRGBA::Ptr> sibr::MaterialMesh::DiffuseMaps
Definition at line 31 of file MaterialMesh.hpp.
MatId2Name
typedef std::vector<std::string> sibr::MaterialMesh::MatId2Name
Definition at line 28 of file MaterialMesh.hpp.
MatIds
typedef std::vector<int> sibr::MaterialMesh::MatIds
Definition at line 26 of file MaterialMesh.hpp.
MeshIds
typedef std::vector<int> sibr::MaterialMesh::MeshIds
Definition at line 27 of file MaterialMesh.hpp.
OpacityMaps
typedef std::map<std::string, sibr::ImageRGB::Ptr> sibr::MaterialMesh::OpacityMaps
Definition at line 30 of file MaterialMesh.hpp.
SubMeshes
typedef std::vector<Mesh> sibr::MaterialMesh::SubMeshes
Definition at line 36 of file MaterialMesh.hpp.
SwitchTagsProperty
typedef std::map<std::string, bool> sibr::MaterialMesh::SwitchTagsProperty
Definition at line 39 of file MaterialMesh.hpp.
TagsCoveringMaps
typedef std::map<std::string, sibr::ImageRGB::Ptr> sibr::MaterialMesh::TagsCoveringMaps
Definition at line 34 of file MaterialMesh.hpp.
TagsMap
typedef sibr::ImageRGB::Ptr sibr::MaterialMesh::TagsMap
Definition at line 33 of file MaterialMesh.hpp.
Member Enumeration Documentation
RenderCategory
enum sibr::MaterialMesh::RenderCategory strong
Synthetic data rendering options.
Enumerator
classic
diffuseMaterials
threesixtyMaterials
threesixtyDepth
Definition at line 44 of file MaterialMesh.hpp.
Constructor & Destructor Documentation
MaterialMesh() [1/2]
sibr::MaterialMesh::MaterialMesh (bool withGraphics = true) inline
Constructor.
Parameters
withGraphics init associated OpenGL buffers object (requires an openGL context)
Definition at line 186 of file MaterialMesh.hpp.
MaterialMesh() [2/2]
sibr::MaterialMesh::MaterialMesh (sibr::Mesh & mesh) inline
Constructor from a basic mesh.
Parameters
mesh the mesh to copy
Definition at line 192 of file MaterialMesh.hpp.
Member Function Documentation
addEnvironmentMap()
void sibr::MaterialMesh::addEnvironmentMap (float * forcedCenterX = nullptr, float * forcedCenterY = nullptr, float * forcedCenterZ = nullptr, float * forcedRadius = nullptr)
Add an environment sphere to the mesh, surrounding the existing geometry.
Parameters
forcedCenterX optional sphere center x coordinate
forcedCenterY optional sphere center y coordinate
forcedCenterZ optional sphere center z coordinate
forcedRadius optional sphere radius
Definition at line 1592 of file MaterialMesh.cpp.
References _diffuseMaps, _opacityMaps, sibr::Mesh::BOTTOM, sibr::Mesh::generateNormals(), sibr::Mesh::getBoundingSphere(), sibr::Mesh::getEnvSphere(), matId2Name(), matIds(), merge(), sibr::Mesh::triangles(), and sibr::Mesh::UP.
ambientOcclusion() [1/2]
void sibr::MaterialMesh::ambientOcclusion (const AmbientOcclusion & ao)
Set the ambient occlusion options and compute AO values, storing them in the vertex colors.
Parameters
ao the new options
Definition at line 1201 of file MaterialMesh.cpp.
References _ambientOcclusion, _aoFunction, _aoInitialized, _averageArea, _averageSize, sibr::Key::A, sibr::MaterialMesh::AmbientOcclusion::AttenuationDistance, sibr::Key::B, sibr::Key::C, sibr::Mesh::colors(), createSubMeshes(), sibr::distance(), subdivideMesh(), sibr::MaterialMesh::AmbientOcclusion::SubdivideThreshold, sibr::Mesh::triangles(), and sibr::Mesh::vertices().
ambientOcclusion() [2/2]
const MaterialMesh::AmbientOcclusion & sibr::MaterialMesh::ambientOcclusion (void) inline
Returns
the current ambient occlusion options.
Definition at line 659 of file MaterialMesh.hpp.
References _ambientOcclusion.
aoFunction()
void sibr::MaterialMesh::aoFunction (std::function< sibr::Mesh::Colors(sibr::MaterialMesh &, const int)> & aoFunction) inline
Set the function used to compute ambient occlusion at each vertex.
Parameters
aoFunction the new function to use
Definition at line 664 of file MaterialMesh.hpp.
References _aoFunction.
createSubMeshes()
void sibr::MaterialMesh::createSubMeshes (void)
Split the mesh geometry in multiple submeshes based on each vertex material ID.
Definition at line 1539 of file MaterialMesh.cpp.
References _matId2Name, _subMeshes, and generateSubMaterialMesh().
Referenced by ambientOcclusion(), and loadMtsXML().
diffuseMap()
ImageRGBA::Ptr sibr::MaterialMesh::diffuseMap (const std::string & matName) const inline
Return the pointer to oppacity texture if it exist.
Query a material diffuse map.
Parameters
matName the material name
Returns
the diffuse texture if it exist
Definition at line 616 of file MaterialMesh.hpp.
References _diffuseMaps.
Referenced by initAlbedoTextures().
diffuseMaps() [1/2]
void sibr::MaterialMesh::diffuseMaps (const DiffuseMaps & maps) inline
Set all material diffuse maps.
Parameters
maps the new maps
Definition at line 638 of file MaterialMesh.hpp.
References _diffuseMaps.
Referenced by merge().
diffuseMaps() [2/2]
const MaterialMesh::DiffuseMaps & sibr::MaterialMesh::diffuseMaps (void) const inline
Returns
all diffuse maps.
Definition at line 633 of file MaterialMesh.hpp.
References _diffuseMaps.
fillColorsWithIndexMaterials()
void sibr::MaterialMesh::fillColorsWithIndexMaterials (void)
Attribute a random color at each vertex based on the material IDs of the faces it belongs to.
Definition at line 753 of file MaterialMesh.cpp.
References _matId2Name, _matIds, sibr::Mesh::_triangles, sibr::Mesh::colors(), and sibr::Mesh::vertices().
fillColorsWithMatIds()
void sibr::MaterialMesh::fillColorsWithMatIds ()
Store the material ID of each vertex in its color attribute (R: bits 0-7, G: 8-15, B: 16-23).
Definition at line 782 of file MaterialMesh.cpp.
References _matIds, sibr::Mesh::_triangles, sibr::Mesh::colors(), and sibr::Mesh::vertices().
forceBufferGLUpdate()
void sibr::MaterialMesh::forceBufferGLUpdate (void) const
Force upload of data to the GPU.
Definition at line 901 of file MaterialMesh.cpp.
References sibr::Mesh::_gl, sibr::Mesh::BufferGL::bufferGL, sibr::Mesh::BufferGL::dirtyBufferGL, and SIBR_ERR.
freeBufferGLUpdate()
void sibr::MaterialMesh::freeBufferGLUpdate (void) const
Delete GPU mesh data.
Definition at line 908 of file MaterialMesh.cpp.
References sibr::Mesh::_gl, sibr::Mesh::BufferGL::bufferGL, and sibr::Mesh::BufferGL::dirtyBufferGL.
generateSubMaterialMesh()
Mesh sibr::MaterialMesh::generateSubMaterialMesh (int material) const
Generate a mesh containing all triangles with a given material.
Parameters
material the material ID
Returns
the submesh
Definition at line 799 of file MaterialMesh.cpp.
References sibr::Mesh::colors(), sibr::Mesh::hasColors(), sibr::Mesh::hasNormals(), sibr::Mesh::hasTexCoords(), matIds(), sibr::Mesh::normals(), sibr::Mesh::texCoords(), sibr::Mesh::triangles(), and sibr::Mesh::vertices().
Referenced by createSubMeshes().
hasMatIds()
bool sibr::MaterialMesh::hasMatIds (void) const inline
Returns
true if each triangle has a material ID assigned.
Definition at line 520 of file MaterialMesh.hpp.
References _matIds, and sibr::Mesh::_triangles.
Referenced by invertedFacesMesh2(), and makeWhole().
hasMeshIds()
bool sibr::MaterialMesh::hasMeshIds (void) const inline
Returns
true if source mesh information is available for each vertex.
Definition at line 540 of file MaterialMesh.hpp.
References _meshIds, and sibr::Mesh::_vertices.
Referenced by invertedFacesMesh2(), makeWhole(), merge(), subdivideMesh(), and subdivideMesh2().
hasTagsCoveringFile() [1/2]
void sibr::MaterialMesh::hasTagsCoveringFile (bool hasOrNot) inline
Indicate if the mesh has an associated covering tag file (for calibration).
Parameters
hasOrNot the flag
Definition at line 568 of file MaterialMesh.hpp.
References _hasTagsCoveringFile.
hasTagsCoveringFile() [2/2]
const bool sibr::MaterialMesh::hasTagsCoveringFile (void) const inline
Returns
true if the mesh has an associated covering tag file.
Definition at line 573 of file MaterialMesh.hpp.
References _hasTagsCoveringFile.
hasTagsFile() [1/2]
void sibr::MaterialMesh::hasTagsFile (bool hasOrNot) inline
Indicate if the mesh has an associated tag file (for calibration).
Parameters
hasOrNot the flag
Definition at line 558 of file MaterialMesh.hpp.
References _hasTagsFile.
hasTagsFile() [2/2]
const bool sibr::MaterialMesh::hasTagsFile (void) const inline
Returns
true if the mesh has an associated tag file.
Definition at line 563 of file MaterialMesh.hpp.
References _hasTagsFile.
initAlbedoTextures()
void sibr::MaterialMesh::initAlbedoTextures (void)
Upload the material textures to the GPU.
Definition at line 1270 of file MaterialMesh.cpp.
References _albedoTextures, _albedoTexturesInitialized, _hasTagsCoveringFile, _hasTagsFile, _idTagsCoveringTexture, _idTagTexture, _idTextures, _idTexturesOpacity, _opacityTextures, _switchTags, _tagsCoveringMaps, _tagsCoveringTexture, _tagsMap, _tagTexture, diffuseMap(), matId2Name(), opacityMap(), SIBR_GPU_LINEAR_SAMPLING, and tagsCoveringMap().
invertedFacesMesh2()
sibr::MaterialMesh::Ptr sibr::MaterialMesh::invertedFacesMesh2 () const
Returns
a copy of the mesh with "doubled" faces (obtained by merging the current mesh with a copy with inverted faces.
Definition at line 1549 of file MaterialMesh.cpp.
References _diffuseMaps, _matId2Name, _opacityMaps, hasMatIds(), hasMeshIds(), sibr::Mesh::invertedFacesMesh(), sibr::Mesh::invertedFacesMesh2(), matIds(), meshIds(), sibr::Mesh::triangles(), and sibr::Mesh::vertices().
load()
bool sibr::MaterialMesh::load (const std::string & filename)
Load a mesh from the disk.
Parameters
filename the file path
Returns
a success flag
Note
Supports OBJ and PLY for now.
Definition at line 23 of file MaterialMesh.cpp.
References sibr::Mesh::_colors, sibr::Mesh::_gl, _matId2Name, _matIds, _matIdsVertices, _maxMeshId, _meshIds, sibr::Mesh::_normals, sibr::Mesh::_texcoords, sibr::Mesh::_triangles, sibr::Mesh::_vertices, sibr::Mesh::BufferGL::dirtyBufferGL, SIBR_LOG, and SIBR_WRG.
Referenced by loadMtsXML().
loadCoveringTagsTexture()
void sibr::MaterialMesh::loadCoveringTagsTexture (const std::vector< std::string > & listFilesTags)
Definition at line 723 of file MaterialMesh.cpp.
References _hasTagsCoveringFile, _listCoveringImagesTags, _tagsCoveringMaps, matId2Name(), and SIBR_ERR.
loadMtsXML()
bool sibr::MaterialMesh::loadMtsXML (const std::string & xmlFile, bool loadTextures = true)
Load a scene from a set of mitsuba XML scene files (referencing multiple OBJs/PLYs).
It handles instances (duplicating the geometry and applying the per-instance transformation).
Parameters
xmlFile the file path
loadTextures should the material textures be loaded
Returns
a success flag
Definition at line 204 of file MaterialMesh.cpp.
References _diffuseMaps, _opacityMaps, _tagsCoveringMaps, createSubMeshes(), sibr::Mesh::hasNormals(), load(), sibr::lookAt(), matIds(), merge(), meshIds(), sibr::Mesh::normals(), sibr::Transform3< T >::rotate(), SIBR_ERR, SIBR_LOG, SIBR_WRG, sibr::split(), sibr::Mesh::vertices(), and xyz().
makeWhole()
void sibr::MaterialMesh::makeWhole (void)
Make the mesh whole, ie it will have default values for all components (texture, materials, colors, etc) It is useful when merging two meshes.
If the second one is missing some attributes, the merging will break the mesh state if it isn't made whole.
Definition at line 1525 of file MaterialMesh.cpp.
References _matId2Name, _matIds, _matIdsVertices, _maxMeshId, _meshIds, hasMatIds(), hasMeshIds(), sibr::Mesh::makeWhole(), sibr::Mesh::triangles(), and sibr::Mesh::vertices().
matId2Name() [1/2]
void sibr::MaterialMesh::matId2Name (const MatId2Name & matId2Name) inline
Set the mapping between IDs and material names.
Parameters
matId2Name the new mapping
Definition at line 529 of file MaterialMesh.hpp.
References _matId2Name, and matId2Name().
matId2Name() [2/2]
const MaterialMesh::MatId2Name & sibr::MaterialMesh::matId2Name (void) const inline
Returns
the mapping between IDs and material names.
Definition at line 526 of file MaterialMesh.hpp.
References _matId2Name.
Referenced by addEnvironmentMap(), initAlbedoTextures(), loadCoveringTagsTexture(), matId2Name(), merge(), and renderAlbedo().
matIds() [1/2]
void sibr::MaterialMesh::matIds (const MatIds & matIds) inline
Set material IDs (per triangle)
Parameters
matIds the new ids
Definition at line 514 of file MaterialMesh.hpp.
References _matIds, and matIds().
Referenced by addEnvironmentMap(), and merge().
matIds() [2/2]
const MaterialMesh::MatIds & sibr::MaterialMesh::matIds (void) const inline
Returns
a reference to the per-triangle material IDs.
Definition at line 517 of file MaterialMesh.hpp.
References _matIds.
Referenced by generateSubMaterialMesh(), invertedFacesMesh2(), loadMtsXML(), matIds(), merge(), subdivideMesh(), and subdivideMesh2().
matIdsVertices()
const MaterialMesh::MatIds & sibr::MaterialMesh::matIdsVertices (void) const inline
Returns
a reference to the per-vertex material IDs.
Definition at line 523 of file MaterialMesh.hpp.
References _matIdsVertices.
merge()
void sibr::MaterialMesh::merge (const MaterialMesh & other)
Merge another mesh into this one.
Parameters
other the mesh to merge
See also
makeWhole
Definition at line 1428 of file MaterialMesh.cpp.
References _diffuseMaps, _matId2Name, _matIds, _maxMeshId, _meshIds, _opacityMaps, sibr::Mesh::_vertices, diffuseMaps(), hasMeshIds(), matId2Name(), matIds(), sibr::Mesh::merge(), meshIds(), opacityMaps(), and sibr::Mesh::vertices().
Referenced by addEnvironmentMap(), and loadMtsXML().
meshIds() [1/2]
void sibr::MaterialMesh::meshIds (const MeshIds & meshIds) inline
Set the mesh ID of each vertex.
Parameters
meshIds the new ids
Definition at line 534 of file MaterialMesh.hpp.
References _meshIds, and meshIds().
Referenced by merge().
meshIds() [2/2]
const MaterialMesh::MeshIds & sibr::MaterialMesh::meshIds (void) const inline
Returns
a reference to the per-vertex mesh IDs.
Definition at line 537 of file MaterialMesh.hpp.
References _meshIds.
Referenced by invertedFacesMesh2(), loadMtsXML(), meshIds(), subdivideMesh(), and subdivideMesh2().
opacityMap()
ImageRGB::Ptr sibr::MaterialMesh::opacityMap (const std::string & matName) const inline
Query a material opacity map.
Parameters
matName the material name
Returns
the opacity texture if it exist
Definition at line 545 of file MaterialMesh.hpp.
References _opacityMaps.
Referenced by initAlbedoTextures().
opacityMaps() [1/2]
void sibr::MaterialMesh::opacityMaps (const OpacityMaps & maps) inline
Set all material opacity maps.
Parameters
maps the new maps
Definition at line 578 of file MaterialMesh.hpp.
References _opacityMaps.
Referenced by merge().
opacityMaps() [2/2]
const MaterialMesh::OpacityMaps & sibr::MaterialMesh::opacityMaps (void) const inline
Returns
all opacity maps.
Definition at line 553 of file MaterialMesh.hpp.
References _opacityMaps.
render()
void sibr::MaterialMesh::render (bool depthTest = true, bool backFaceCulling = true, RenderMode mode = FillRenderMode, bool frontFaceCulling = false, bool invertDepthTest = false, bool tessellation = false, bool adjacency = false) const
Render the geometry using OpenGL.
Parameters
depthTest should depth testing be performed
backFaceCulling should culling be performed
mode the primitives rendering mode
frontFaceCulling should the culling test be flipped
invertDepthTest should the depth test be flipped (GL_GREATER_THAN)
tessellation should the rendering call tesselation shaders
adjacency should we get adjacent triangles info in geometry shader
Definition at line 1406 of file MaterialMesh.cpp.
References _typeOfRender, classic, diffuseMaterials, sibr::Mesh::render(), renderAlbedo(), renderThreeSixty(), threesixtyDepth, and threesixtyMaterials.
renderAlbedo()
void sibr::MaterialMesh::renderAlbedo (bool depthTest = true, bool backFaceCulling = true, RenderMode mode = FillRenderMode, bool frontFaceCulling = false, bool invertDepthTest = false, bool specificMaterial = false, std::string nameOfSpecificMaterial = "") const
Render the geometry with albedo and tag textures.
Parameters
depthTest should depth testing be performed
backFaceCulling should culling be performed
mode the primitives rendering mode
frontFaceCulling should the culling test be flipped
invertDepthTest should the depth test be flipped (GL_GREATER_THAN)
specificMaterial should we use a specific material
nameOfSpecificMaterial name of the specific material
Definition at line 1332 of file MaterialMesh.cpp.
References _albedoTextures, _hasTagsCoveringFile, _hasTagsFile, _idTagsCoveringTexture, _idTagTexture, _idTextures, _idTexturesOpacity, _subMeshes, _switchTags, _tagTexture, matId2Name(), tagsCoveringMap(), and tagsCoveringMaps().
Referenced by render().
renderThreeSixty()
void sibr::MaterialMesh::renderThreeSixty (bool depthTest, bool backFaceCulling, RenderMode mode, bool frontFaceCulling, bool invertDepthTest) const
Render the geometry for 360 environment maps.
Parameters
depthTest should depth testing be performed
backFaceCulling should culling be performed
mode the primitives rendering mode
frontFaceCulling should the culling test be flipped
invertDepthTest should the depth test be flipped (GL_GREATER_THAN)
Definition at line 1398 of file MaterialMesh.cpp.
References sibr::Mesh::render().
Referenced by render().
SIBR_CLASS_PTR()
sibr::MaterialMesh::SIBR_CLASS_PTR (MaterialMesh)
subdivideMesh()
void sibr::MaterialMesh::subdivideMesh (float threshold)
Subdivide a mesh triangles until an edge length threshold is reached.
Parameters
threshold the maximum deviation from the average edge length allowed
Definition at line 1027 of file MaterialMesh.cpp.
References _averageSize, sibr::Mesh::colors(), sibr::distance(), sibr::Mesh::hasColors(), hasMeshIds(), sibr::Mesh::hasNormals(), sibr::Mesh::hasTexCoords(), matIds(), meshIds(), sibr::Mesh::normals(), sibr::Mesh::texCoords(), sibr::Mesh::triangles(), and sibr::Mesh::vertices().
Referenced by ambientOcclusion().
subdivideMesh2()
void sibr::MaterialMesh::subdivideMesh2 (float threshold)
Subdivide a mesh triangles until a triangle area threshold is reached.
Parameters
threshold the maximum deviation from the average triangle area allowed
Definition at line 914 of file MaterialMesh.cpp.
References _averageArea, sibr::Key::A, sibr::Key::B, sibr::Key::C, sibr::Mesh::colors(), sibr::distance(), sibr::Mesh::hasColors(), hasMeshIds(), sibr::Mesh::hasNormals(), sibr::Mesh::hasTexCoords(), matIds(), meshIds(), sibr::Mesh::normals(), sibr::Mesh::texCoords(), sibr::Mesh::triangles(), and sibr::Mesh::vertices().
subMeshes() [1/2]
void sibr::MaterialMesh::subMeshes (const SubMeshes & subMeshes) inline
Set the sub meshes.
Parameters
subMeshes a list of submeshes
Definition at line 649 of file MaterialMesh.hpp.
References _subMeshes, and subMeshes().
subMeshes() [2/2]
const MaterialMesh::SubMeshes & sibr::MaterialMesh::subMeshes (void) const inline
Returns
the list of submeshes.
Definition at line 643 of file MaterialMesh.hpp.
References _subMeshes.
Referenced by subMeshes().
switchTag() [1/2]
void sibr::MaterialMesh::switchTag (const SwitchTagsProperty & switchTag) inline
Set the switchTag.
Definition at line 608 of file MaterialMesh.hpp.
References _switchTags, and switchTag().
switchTag() [2/2]
const MaterialMesh::SwitchTagsProperty & sibr::MaterialMesh::switchTag (void) const inline
get the switchTag
Definition at line 612 of file MaterialMesh.hpp.
References _switchTags.
Referenced by switchTag().
tagsCoveringMap()
sibr::ImageRGB::Ptr sibr::MaterialMesh::tagsCoveringMap (const std::string & matName) const inline
Return the pointer to oppacity texture if it exist.
Definition at line 599 of file MaterialMesh.hpp.
References _tagsCoveringMaps.
Referenced by initAlbedoTextures(), and renderAlbedo().
tagsCoveringMaps() [1/2]
void sibr::MaterialMesh::tagsCoveringMaps (const TagsCoveringMaps & map) inline
Set the covering tag map.
Parameters
map the new map
Definition at line 591 of file MaterialMesh.hpp.
References _tagsCoveringMaps.
tagsCoveringMaps() [2/2]
const MaterialMesh::TagsCoveringMaps & sibr::MaterialMesh::tagsCoveringMaps (void) const inline
Returns
the current covering tag map.
Definition at line 595 of file MaterialMesh.hpp.
References _tagsCoveringMaps.
Referenced by renderAlbedo().
tagsMap() [1/2]
void sibr::MaterialMesh::tagsMap (const TagsMap & map) inline
Set the tag map.
Parameters
map the new map
Definition at line 583 of file MaterialMesh.hpp.
References _tagsMap.
tagsMap() [2/2]
const MaterialMesh::TagsMap & sibr::MaterialMesh::tagsMap (void) const inline
Returns
the current tag map.
Definition at line 587 of file MaterialMesh.hpp.
References _tagsMap.
typeOfRender() [1/2]
void sibr::MaterialMesh::typeOfRender (const RenderCategory & type) inline
Set the synthetic rendering mode.
Parameters
type the new mode
Definition at line 671 of file MaterialMesh.hpp.
References _typeOfRender.
typeOfRender() [2/2]
const MaterialMesh::RenderCategory & sibr::MaterialMesh::typeOfRender (void) const inline
Returns
the current synthetic rendering mode.
Definition at line 654 of file MaterialMesh.hpp.
References _typeOfRender.
Member Data Documentation
_albedoTextures
std::vector<sibr::Texture2DRGBA::Ptr> sibr::MaterialMesh::_albedoTextures private
Albedo textures.
Definition at line 481 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures(), and renderAlbedo().
_albedoTexturesInitialized
bool sibr::MaterialMesh::_albedoTexturesInitialized = false private
Are the texture initialized.
Definition at line 480 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures().
_ambientOcclusion
AmbientOcclusion sibr::MaterialMesh::_ambientOcclusion private
AO options.
Definition at line 502 of file MaterialMesh.hpp.
Referenced by ambientOcclusion().
_aoFunction
std::function<sibr::Mesh::Colors(sibr::MaterialMesh&, const int)> sibr::MaterialMesh::_aoFunction private
AO generation function.
Definition at line 503 of file MaterialMesh.hpp.
Referenced by ambientOcclusion(), and aoFunction().
_aoInitialized
bool sibr::MaterialMesh::_aoInitialized = false private
Is AO data initialized.
Definition at line 504 of file MaterialMesh.hpp.
Referenced by ambientOcclusion().
_averageArea
float sibr::MaterialMesh::_averageArea = 0.0f private
Average triangle area.
Definition at line 506 of file MaterialMesh.hpp.
Referenced by ambientOcclusion(), and subdivideMesh2().
_averageSize
float sibr::MaterialMesh::_averageSize = 0.0f private
Average maximum edge length.
Definition at line 505 of file MaterialMesh.hpp.
Referenced by ambientOcclusion(), and subdivideMesh().
_currentThreshold
float sibr::MaterialMesh::_currentThreshold private
Definition at line 501 of file MaterialMesh.hpp.
_diffuseMaps
DiffuseMaps sibr::MaterialMesh::_diffuseMaps private
Material diffuse images.
Definition at line 470 of file MaterialMesh.hpp.
Referenced by addEnvironmentMap(), diffuseMap(), diffuseMaps(), invertedFacesMesh2(), loadMtsXML(), and merge().
_hasTagsCoveringFile
bool sibr::MaterialMesh::_hasTagsCoveringFile = false private
Is a covering tag file associated to the mesh.
Definition at line 490 of file MaterialMesh.hpp.
Referenced by hasTagsCoveringFile(), initAlbedoTextures(), loadCoveringTagsTexture(), and renderAlbedo().
_hasTagsFile
bool sibr::MaterialMesh::_hasTagsFile = false private
Is a tag file associated to the mesh.
Definition at line 486 of file MaterialMesh.hpp.
Referenced by hasTagsFile(), initAlbedoTextures(), and renderAlbedo().
_idTagCoveringTexture
GLuint sibr::MaterialMesh::_idTagCoveringTexture = 0 private
Covering tag texture handle.
Definition at line 492 of file MaterialMesh.hpp.
_idTagsCoveringTexture
std::map<std::string,GLuint> sibr::MaterialMesh::_idTagsCoveringTexture private
Definition at line 496 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures(), and renderAlbedo().
_idTagTexture
GLuint sibr::MaterialMesh::_idTagTexture = 0 private
Tag texture handle.
Definition at line 488 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures(), and renderAlbedo().
_idTextures
std::vector<GLuint> sibr::MaterialMesh::_idTextures private
Texture handles.
Definition at line 482 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures(), and renderAlbedo().
_idTexturesOpacity
std::vector<GLuint> sibr::MaterialMesh::_idTexturesOpacity private
Opacity texture handles.
Definition at line 484 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures(), and renderAlbedo().
_listCoveringImagesTags
std::vector<sibr::ImageRGB::Ptr> sibr::MaterialMesh::_listCoveringImagesTags private
Definition at line 494 of file MaterialMesh.hpp.
Referenced by loadCoveringTagsTexture().
_matId2Name
MatId2Name sibr::MaterialMesh::_matId2Name private
ID to name material mapping.
Definition at line 464 of file MaterialMesh.hpp.
Referenced by createSubMeshes(), fillColorsWithIndexMaterials(), invertedFacesMesh2(), load(), makeWhole(), matId2Name(), and merge().
_matIds
MatIds sibr::MaterialMesh::_matIds private
Per triangle material ID.
Definition at line 462 of file MaterialMesh.hpp.
Referenced by fillColorsWithIndexMaterials(), fillColorsWithMatIds(), hasMatIds(), load(), makeWhole(), matIds(), and merge().
_matIdsVertices
MatIds sibr::MaterialMesh::_matIdsVertices private
Per vertex material ID.
Definition at line 463 of file MaterialMesh.hpp.
Referenced by load(), makeWhole(), and matIdsVertices().
_maxMeshId
size_t sibr::MaterialMesh::_maxMeshId = 0 private
Maximum submesh ID encounter.
Definition at line 467 of file MaterialMesh.hpp.
Referenced by load(), makeWhole(), and merge().
_meshIds
MeshIds sibr::MaterialMesh::_meshIds private
Per-vertex submesh ID.
Definition at line 466 of file MaterialMesh.hpp.
Referenced by hasMeshIds(), load(), makeWhole(), merge(), and meshIds().
_opacityMaps
OpacityMaps sibr::MaterialMesh::_opacityMaps private
Material opacity images.
Definition at line 469 of file MaterialMesh.hpp.
Referenced by addEnvironmentMap(), invertedFacesMesh2(), loadMtsXML(), merge(), opacityMap(), and opacityMaps().
_opacityTextures
std::vector<sibr::Texture2DRGB::Ptr> sibr::MaterialMesh::_opacityTextures private
Opacity textures.
Definition at line 483 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures().
_subMeshes
SubMeshes sibr::MaterialMesh::_subMeshes private
Submeshes, one per material, for rendering them separately.
Definition at line 477 of file MaterialMesh.hpp.
Referenced by createSubMeshes(), renderAlbedo(), and subMeshes().
_switchTags
SwitchTagsProperty sibr::MaterialMesh::_switchTags private
Definition at line 498 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures(), renderAlbedo(), and switchTag().
_tagCoveringTexture
sibr::Texture2DRGB::Ptr sibr::MaterialMesh::_tagCoveringTexture private
Convering tag texture.
Definition at line 491 of file MaterialMesh.hpp.
_tagsCoveringMaps
TagsCoveringMaps sibr::MaterialMesh::_tagsCoveringMaps private
Material covering tag images.
Definition at line 474 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures(), loadCoveringTagsTexture(), loadMtsXML(), tagsCoveringMap(), and tagsCoveringMaps().
_tagsCoveringTexture
std::map<std::string,sibr::Texture2DRGB::Ptr> sibr::MaterialMesh::_tagsCoveringTexture private
Definition at line 495 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures().
_tagsMap
TagsMap sibr::MaterialMesh::_tagsMap private
Material tag images.
Definition at line 473 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures(), and tagsMap().
_tagTexture
sibr::Texture2DRGB::Ptr sibr::MaterialMesh::_tagTexture private
Tag texture.
Definition at line 487 of file MaterialMesh.hpp.
Referenced by initAlbedoTextures(), and renderAlbedo().
_typeOfRender
RenderCategory sibr::MaterialMesh::_typeOfRender = RenderCategory::diffuseMaterials private
Synthetic rendering mode.
Definition at line 478 of file MaterialMesh.hpp.
Referenced by render(), and typeOfRender().
fragmentShaderAlbedo
std::string sibr::MaterialMesh::fragmentShaderAlbedo
Definition at line 88 of file MaterialMesh.hpp.
fragmentShaderAlbedoTag
std::string sibr::MaterialMesh::fragmentShaderAlbedoTag
Definition at line 124 of file MaterialMesh.hpp.
uniformColorMtlList
std::vector<std::string> sibr::MaterialMesh::uniformColorMtlList private
List of materials with a diffuse map.
Definition at line 475 of file MaterialMesh.hpp.
vertexShaderAlbedo
std::string sibr::MaterialMesh::vertexShaderAlbedo
Initial value:
=
            "#version 450                                       \n"
            "layout(location = 0) in vec3 in_vertex;            \n"
            "layout(location = 1) in vec3 in_colors;            \n"
            "layout(location = 2) in vec2 in_uvCoords;          \n"
            "layout(location = 3) in vec3 in_normal;            \n"
            "layout(location = 4) in float in_ao;           \n"
            "//layout(location = 4) in float in_material;           \n"
            "layout (location = 2) out vec2 uvCoords;           \n"
            "//out float material;          \n"
            "layout (location = 3) out vec3 normal;                                 \n"
            "out float ao ;                                 \n"
            "out vec3 pos_vertex;                                   \n"
            "layout (location = 1) out vec3 colors;                                 \n"
            "uniform mat4 MVP;                                  \n"
            "uniform bool lightIsPresent;                                   \n"
            "uniform vec3 lightPos;                                 \n"
            "void main(void) {                                  \n"
            "   normal = in_normal;     \n"
            "   ao = in_ao;     \n"
            "   uvCoords = in_uvCoords;     \n"
            "   colors= in_colors;      \n"
            "   pos_vertex= in_vertex;      \n"
            "   //material= float(in_material);     \n"
            "   gl_Position = MVP*vec4(in_vertex,1) ;       \n"
            "}                                                  \n"
Definition at line 61 of file MaterialMesh.hpp.
The documentation for this class was generated from the following files:
src/core/graphics/MaterialMesh.hpp
src/core/graphics/MaterialMesh.cpp