SIBR: sibr::Texture2DArray< T_Type, T_NumComp > Class Template Reference
sibr::Texture2DArray< T_Type, T_NumComp > Class Template Reference
sibr_graphics
Represent an array of 2D textures on the GPU, with custom format, type and slice count.
#include <Texture.hpp>
Public Types
typedef Image< T_Type, T_NumComp > PixelImage
typedef PixelImage::Pixel PixelFormat
typedef RenderTarget< T_Type, T_NumComp > PixelRT
typedef std::shared_ptr< Texture2DArray< T_Type, T_NumComp > > Ptr
typedef std::unique_ptr< Texture2DArray< T_Type, T_NumComp > > UPtr
Public Types inherited from sibr::ITexture2DArray
typedef std::shared_ptr< ITexture2DArray > Ptr
typedef std::unique_ptr< ITexture2DArray > UPtr
Public Member Functions
Texture2DArray (const uint d=0, uint flags=0)
Constructor.
Texture2DArray (const uint w, const uint h, const uint d, uint flags=0)
Constructor.
Texture2DArray (const std::vector< typename PixelRT::Ptr > &images, uint flags=0)
Constructor from a set of rendertargets.
template<typename ImageType >
Texture2DArray (const std::vector< ImageType > &images, uint flags=0)
Constructor from a set of CPU images.
template<typename ImageType >
Texture2DArray (const std::vector< ImageType > &images, uint w, uint h, uint flags=0)
Constructor from a set of CPU images that will be resized to a fix size.
template<typename ImageType >
Texture2DArray (const std::vector< std::vector< ImageType >> &images, uint flags=0)
Constructor from a set of CPU images, with custom mipmaps.
template<typename ImageType >
Texture2DArray (const std::vector< std::vector< ImageType >> &images, uint w, uint h, uint flags=0)
Constructor from a set of CPU images, with custom mipmaps.
template<typename ImageType >
void createFromImages (const std::vector< ImageType > &images, uint flags=0)
Create the texture from a set of images and send it to GPU.
template<typename ImageType >
void createFromImages (const std::vector< ImageType > &images, uint w, uint h, uint flags=0)
Create the texture from a set of images and send it to GPU.
template<typename ImageType >
void createCompressedFromImages (const std::vector< ImageType > &images, uint compression, uint flags=0)
Create the texture from a set of images and send it to GPU while compressing them.
template<typename ImageType >
void createCompressedFromImages (const std::vector< ImageType > &images, uint w, uint h, uint compression, uint flags=0)
Create the texture from a set of images and send it to GPU while compressing them.
template<typename ImageType >
void createFromImages (const std::vector< std::vector< ImageType >> &images, uint flags=0)
Create the texture from a set of images with custom mipmaps and send it to GPU.
template<typename ImageType >
void createFromImages (const std::vector< std::vector< ImageType >> &images, uint w, uint h, uint flags=0)
Create the texture from a set of images with custom mipmaps and send it to GPU.
template<typename ImageType >
void updateFromImages (const std::vector< ImageType > &images)
Update the content of all layers of the texture.
void createFromRTs (const std::vector< typename PixelRT::Ptr > &RTs, uint flags=0)
Create the texture from a set of rendertargets and send it to GPU.
template<typename ImageType >
void updateSlices (const std::vector< ImageType > &images, const std::vector< int > &slices)
Update the content of specific layers of the texture.
~Texture2DArray (void)
Destructor.
GLuint handle (void) const
uint w (void) const
uint h (void) const
uint depth (void) const
uint numLODs (void) const
Vector4f readBackPixel (int i, int x, int y, uint lod=0) const
Read back the value of a given pixel to the CPU.
Public Member Functions inherited from sibr::ITexture2DArray
virtual ~ITexture2DArray (void)
Destructor.
Private Member Functions
SIBR_DISALLOW_COPY (Texture2DArray)
void createArray (uint compression=0)
Create the texture array.
template<typename ImageType >
void sendArray (const std::vector< ImageType > &images)
Upload the images data to the GPU.
void sendRTarray (const std::vector< typename PixelRT::Ptr > &RTs)
Copy the rendertargets data to the texture.
template<typename ImageType >
void sendMipArray (const std::vector< std::vector< ImageType >> &images)
Upload the images data to the GPU.
template<typename ImageType >
std::vector< const ImageType * > applyFlipAndResize (const std::vector< ImageType > &images, std::vector< ImageType > &tmp, uint tw, uint th, const std::vector< int > &slices)
Flip and rescale a subset of images from a list.
template<typename ImageType >
std::vector< const ImageType * > applyFlipAndResize (const std::vector< ImageType > &images, std::vector< ImageType > &tmp, uint tw, uint th)
Flip and rescale a set of images.
Private Attributes
GLuint m_Handle = 0
Texture handle.
uint m_W = 0
Texture width.
uint m_H = 0
Texture height.
uint m_Flags = 0
Options.
uint m_Depth = 0
Layers count.
uint m_numLODs = 1
Mipmap level count.
Detailed Description
template<typename T_Type, unsigned int T_NumComp>
class sibr::Texture2DArray< T_Type, T_NumComp >
Represent an array of 2D textures on the GPU, with custom format, type and slice count.
See also
ITexture2DArray
Definition at line 178 of file Texture.hpp.
Member Typedef Documentation
PixelFormat
template<typename T_Type , unsigned int T_NumComp> typedef PixelImage::Pixel sibr::Texture2DArray< T_Type, T_NumComp >::PixelFormat
Definition at line 182 of file Texture.hpp.
PixelImage
template<typename T_Type , unsigned int T_NumComp> typedef Image<T_Type, T_NumComp> sibr::Texture2DArray< T_Type, T_NumComp >::PixelImage
Definition at line 181 of file Texture.hpp.
PixelRT
template<typename T_Type , unsigned int T_NumComp> typedef RenderTarget<T_Type, T_NumComp> sibr::Texture2DArray< T_Type, T_NumComp >::PixelRT
Definition at line 183 of file Texture.hpp.
Ptr
template<typename T_Type , unsigned int T_NumComp> typedef std::shared_ptr<Texture2DArray<T_Type, T_NumComp> > sibr::Texture2DArray< T_Type, T_NumComp >::Ptr
Definition at line 184 of file Texture.hpp.
UPtr
template<typename T_Type , unsigned int T_NumComp> typedef std::unique_ptr<Texture2DArray<T_Type, T_NumComp> > sibr::Texture2DArray< T_Type, T_NumComp >::UPtr
Definition at line 185 of file Texture.hpp.
Constructor & Destructor Documentation
Texture2DArray() [1/7]
template<typename T_Type , unsigned int T_NumComp> sibr::Texture2DArray< T_Type, T_NumComp >::Texture2DArray (const uint d = 0, uint flags = 0)
Constructor.
Parameters
d number of layers
flags options
Definition at line 931 of file Texture.hpp.
Texture2DArray() [2/7]
template<typename T_Type , unsigned int T_NumComp> sibr::Texture2DArray< T_Type, T_NumComp >::Texture2DArray (const uint w, const uint h, const uint d, uint flags = 0)
Constructor.
Parameters
w width
h height
d number of layers
flags options
Definition at line 937 of file Texture.hpp.
Texture2DArray() [3/7]
template<typename T_Type , unsigned int T_NumComp> sibr::Texture2DArray< T_Type, T_NumComp >::Texture2DArray (const std::vector< typename PixelRT::Ptr > & images, uint flags = 0)
Constructor from a set of rendertargets.
Parameters
images list of rendertargets, one for each layer
flags options
Warning
RTs should be of the same size.
Definition at line 970 of file Texture.hpp.
Texture2DArray() [4/7]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > sibr::Texture2DArray< T_Type, T_NumComp >::Texture2DArray (const std::vector< ImageType > & images, uint flags = 0)
Constructor from a set of CPU images.
Parameters
images list of images, one for each layer
flags options
Note
All images will be resized to the dimensions of the largest one.
Definition at line 946 of file Texture.hpp.
Texture2DArray() [5/7]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > sibr::Texture2DArray< T_Type, T_NumComp >::Texture2DArray (const std::vector< ImageType > & images, uint w, uint h, uint flags = 0)
Constructor from a set of CPU images that will be resized to a fix size.
Parameters
images list of images, one for each layer
w the target width
h the target height
flags options
Definition at line 952 of file Texture.hpp.
Texture2DArray() [6/7]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > sibr::Texture2DArray< T_Type, T_NumComp >::Texture2DArray (const std::vector< std::vector< ImageType >> & images, uint flags = 0)
Constructor from a set of CPU images, with custom mipmaps.
Parameters
images list of lists of images, one for each mip level, each containing an image for each layer
flags options
Note
All images will be resized to the dimensions of the largest one.
Definition at line 958 of file Texture.hpp.
Texture2DArray() [7/7]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > sibr::Texture2DArray< T_Type, T_NumComp >::Texture2DArray (const std::vector< std::vector< ImageType >> & images, uint w, uint h, uint flags = 0)
Constructor from a set of CPU images, with custom mipmaps.
Parameters
images list of lists of images, one for each mip level, each containing an image for each layer
w the target width
h the target height
flags options
Definition at line 964 of file Texture.hpp.
~Texture2DArray()
template<typename T_Type , unsigned int T_NumComp> sibr::Texture2DArray< T_Type, T_NumComp >::~Texture2DArray (void)
Destructor.
Definition at line 1301 of file Texture.hpp.
References CHECK_GL_ERROR.
Member Function Documentation
applyFlipAndResize() [1/2]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > std::vector< const ImageType * > sibr::Texture2DArray< T_Type, T_NumComp >::applyFlipAndResize (const std::vector< ImageType > & images, std::vector< ImageType > & tmp, uint tw, uint th) private
Flip and rescale a set of images.
Parameters
images the images to resize
tmp a temporary buffer
tw the target width
th the target height
Returns
a list of pointers to the transformed images
Definition at line 1130 of file Texture.hpp.
applyFlipAndResize() [2/2]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > std::vector< const ImageType * > sibr::Texture2DArray< T_Type, T_NumComp >::applyFlipAndResize (const std::vector< ImageType > & images, std::vector< ImageType > & tmp, uint tw, uint th, const std::vector< int > & slices) private
Flip and rescale a subset of images from a list.
Parameters
images the images to resize
tmp a temporary buffer
tw the target width
th the target height
slices the indices of the images to process in the list
Returns
a list of pointers to the transformed images
Definition at line 1095 of file Texture.hpp.
References SIBR_FLIP_TEXTURE.
createArray()
template<typename T_Type , unsigned int T_NumComp> void sibr::Texture2DArray< T_Type, T_NumComp >::createArray (uint compression = 0) private
Create the texture array.
Definition at line 976 of file Texture.hpp.
References CHECK_GL_ERROR, SIBR_GPU_AUTOGEN_MIPMAP, and SIBR_GPU_LINEAR_SAMPLING.
createCompressedFromImages() [1/2]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::createCompressedFromImages (const std::vector< ImageType > & images, uint compression, uint flags = 0)
Create the texture from a set of images and send it to GPU while compressing them.
Parameters
images list of images, one for each layer
compression the GL_COMPRESSED format. It must be choosen accordingly to the texture internal format.
flags options
Note
All images will be resized to the dimensions of the largest one.
Definition at line 1185 of file Texture.hpp.
createCompressedFromImages() [2/2]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::createCompressedFromImages (const std::vector< ImageType > & images, uint w, uint h, uint compression, uint flags = 0)
Create the texture from a set of images and send it to GPU while compressing them.
images will be resized to the target size.
Parameters
images list of images, one for each layer
w the target width
h the target height
compression the GL_COMPRESSED format. It must be choosen accordingly to the texture internal format.
flags options
Definition at line 1196 of file Texture.hpp.
createFromImages() [1/4]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::createFromImages (const std::vector< ImageType > & images, uint flags = 0)
Create the texture from a set of images and send it to GPU.
Parameters
images list of images, one for each layer
flags options
Note
All images will be resized to the dimensions of the largest one.
Definition at line 1164 of file Texture.hpp.
Referenced by sibr::MultiViewInterface::addImageLayer(), sibr::MultiViewInterface::addImageLayerWithLambda(), and legacyV2main().
createFromImages() [2/4]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::createFromImages (const std::vector< ImageType > & images, uint w, uint h, uint flags = 0)
Create the texture from a set of images and send it to GPU.
images will be resized to the target size.
Parameters
images list of images, one for each layer
w the target width
h the target height
flags options
Definition at line 1175 of file Texture.hpp.
createFromImages() [3/4]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::createFromImages (const std::vector< std::vector< ImageType >> & images, uint flags = 0)
Create the texture from a set of images with custom mipmaps and send it to GPU.
Parameters
images list of lists of images, one for each mip level, each containing an image for each layer
flags options
Note
All images will be resized to the dimensions of the largest one.
Definition at line 1206 of file Texture.hpp.
createFromImages() [4/4]
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::createFromImages (const std::vector< std::vector< ImageType >> & images, uint w, uint h, uint flags = 0)
Create the texture from a set of images with custom mipmaps and send it to GPU.
Parameters
images list of lists of images, one for each mip level, each containing an image for each layer
w the target width
h the target height
flags options
Definition at line 1217 of file Texture.hpp.
References SIBR_GPU_AUTOGEN_MIPMAP.
createFromRTs()
template<typename T_Type , unsigned int T_NumComp> void sibr::Texture2DArray< T_Type, T_NumComp >::createFromRTs (const std::vector< typename PixelRT::Ptr > & RTs, uint flags = 0)
Create the texture from a set of rendertargets and send it to GPU.
Parameters
RTs list of rendertargets, one for each layer
flags options
Warning
RTs should be of the same size.
Definition at line 1287 of file Texture.hpp.
depth()
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2DArray< T_Type, T_NumComp >::depth (void) const virtual
Returns
the texture layer count.
Implements sibr::ITexture2DArray.
Definition at line 1317 of file Texture.hpp.
Referenced by sibr::show().
h()
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2DArray< T_Type, T_NumComp >::h (void) const virtual
Returns
the texture height.
Implements sibr::ITexture2DArray.
Definition at line 1314 of file Texture.hpp.
handle()
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::Texture2DArray< T_Type, T_NumComp >::handle (void) const virtual
Returns
the texture handle.
Implements sibr::ITexture2DArray.
Definition at line 1308 of file Texture.hpp.
Referenced by sibr::ULRV2Renderer::process(), and sibr::show().
numLODs()
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2DArray< T_Type, T_NumComp >::numLODs (void) const virtual
Returns
the number of mipmap levels.
Implements sibr::ITexture2DArray.
Definition at line 1320 of file Texture.hpp.
readBackPixel()
template<typename T_Type , unsigned int T_NumComp> Vector4f sibr::Texture2DArray< T_Type, T_NumComp >::readBackPixel (int i, int x, int y, uint lod = 0) const virtual
Read back the value of a given pixel to the CPU.
Parameters
i layer
x x coordinate in [0,w-1]
y y coordinate in [0,h-1]
lod the mip level
Returns
a converted RGBA float color
Warning
Use only for debugging, can cause a GPU flush/sync.
Implements sibr::ITexture2DArray.
Definition at line 1323 of file Texture.hpp.
References CHECK_GL_ERROR.
sendArray()
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::sendArray (const std::vector< ImageType > & images) private
Upload the images data to the GPU.
Parameters
images the data to upload
Definition at line 1026 of file Texture.hpp.
References CHECK_GL_ERROR, and SIBR_GPU_AUTOGEN_MIPMAP.
sendMipArray()
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::sendMipArray (const std::vector< std::vector< ImageType >> & images) private
Upload the images data to the GPU.
Parameters
images the data to upload
Definition at line 1058 of file Texture.hpp.
References CHECK_GL_ERROR, and SIBR_GPU_AUTOGEN_MIPMAP.
sendRTarray()
template<typename T_Type , unsigned int T_NumComp> void sibr::Texture2DArray< T_Type, T_NumComp >::sendRTarray (const std::vector< typename PixelRT::Ptr > & RTs) private
Copy the rendertargets data to the texture.
Parameters
RTs the rendertargets to copy
Definition at line 1142 of file Texture.hpp.
References CHECK_GL_ERROR.
SIBR_DISALLOW_COPY()
template<typename T_Type , unsigned int T_NumComp> sibr::Texture2DArray< T_Type, T_NumComp >::SIBR_DISALLOW_COPY (Texture2DArray< T_Type, T_NumComp >) private
updateFromImages()
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::updateFromImages (const std::vector< ImageType > & images)
Update the content of all layers of the texture.
Parameters
images the new content to use
Note
All images will be resized to the size of the largest one.
Definition at line 1230 of file Texture.hpp.
updateSlices()
template<typename T_Type , unsigned int T_NumComp> template<typename ImageType > void sibr::Texture2DArray< T_Type, T_NumComp >::updateSlices (const std::vector< ImageType > & images, const std::vector< int > & slices)
Update the content of specific layers of the texture.
Parameters
images the new content to use
slices the indices of the slices to update
Note
All images will be resized to the size of the largest one.
Definition at line 1246 of file Texture.hpp.
References CHECK_GL_ERROR.
w()
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2DArray< T_Type, T_NumComp >::w (void) const virtual
Returns
the texture width.
Implements sibr::ITexture2DArray.
Definition at line 1311 of file Texture.hpp.
Member Data Documentation
m_Depth
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2DArray< T_Type, T_NumComp >::m_Depth = 0 private
Layers count.
Definition at line 401 of file Texture.hpp.
m_Flags
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2DArray< T_Type, T_NumComp >::m_Flags = 0 private
Options.
Definition at line 400 of file Texture.hpp.
m_H
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2DArray< T_Type, T_NumComp >::m_H = 0 private
Texture height.
Definition at line 399 of file Texture.hpp.
m_Handle
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::Texture2DArray< T_Type, T_NumComp >::m_Handle = 0 private
Texture handle.
Definition at line 397 of file Texture.hpp.
m_numLODs
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2DArray< T_Type, T_NumComp >::m_numLODs = 1 private
Mipmap level count.
Definition at line 402 of file Texture.hpp.
m_W
template<typename T_Type , unsigned int T_NumComp> uint sibr::Texture2DArray< T_Type, T_NumComp >::m_W = 0 private
Texture width.
Definition at line 398 of file Texture.hpp.
The documentation for this class was generated from the following file:
src/core/graphics/Texture.hpp