SIBR: sibr::Viewport Class Reference
sibr::Viewport Class Reference
sibr_graphics
Represent an on-screen viewport using normalized coordinates, which can be nested into another viewport.
#include <Viewport.hpp>
Public Member Functions
Viewport (void)
Default constructor: unit viewport.
Viewport (float left, float top, float right, float bottom)
Constructor from extents.
Viewport (const Viewport *parent_, float left, float top, float right, float bottom)
Constructor from a parent and relative extents.
Viewport (const Viewport &parent_, float left, float top, float right, float bottom)
Constructor from a parent and relative extents.
float left (void) const
float top (void) const
float right (void) const
float bottom (void) const
float width (void) const
float height (void) const
float finalLeft (void) const
float finalTop (void) const
float finalRight (void) const
float finalBottom (void) const
float finalWidth (void) const
float finalHeight (void) const
sibr::Vector2f finalSize () const
Vector2f finalTopLeft () const
Vector2f pixAt (const Vector2f &uv) const
Compute the absolute pixel coordinates based on relative normalized coordinates.
bool contains (float x, float y) const
Check if a point is inside the viewport.
bool contains (int x, int y) const
Check if a point is inside the viewport.
bool contains (const Vector2f &xy) const
Check if a point is inside the viewport.
void bind (uint screenWidth, uint screenHeight) const
Bind an OpenGL viewport whose values are determined based on the viewport final dimensions and the target size.
void bind (void) const
Bind an OpenGL viewport whose values are determined based on the viewport final dimensions.
void clear (const Vector3f &bgColor=Vector3f(0.f, 0.f, 0.f)) const
Perform a full OpenGL clear of the region defined by the viewport in the currently bound target.
void parent (const Viewport *view)
Set the viewport parent.
const Viewport * parent (void) const
bool isEmpty () const
Private Attributes
const Viewport * _parent
(optional)
float _left
Left extent.
float _top
Top extent.
float _right
Right extent.
float _bottom
Bottom extent.
Detailed Description
Represent an on-screen viewport using normalized coordinates, which can be nested into another viewport.
Definition at line 12 of file Viewport.hpp.
Constructor & Destructor Documentation
Viewport() [1/4]
sibr::Viewport::Viewport (void) inline
Default constructor: unit viewport.
Definition at line 17 of file Viewport.hpp.
Viewport() [2/4]
sibr::Viewport::Viewport (float left, float top, float right, float bottom) inline
Constructor from extents.
Parameters
left left extent
top top extent
right right extent
bottom bottom extent
Definition at line 27 of file Viewport.hpp.
Viewport() [3/4]
sibr::Viewport::Viewport (const Viewport * parent_, float left, float top, float right, float bottom) inline
Constructor from a parent and relative extents.
Parameters
parent_ the parent viewport
left left relative extent
top top relative extent
right right relative extent
bottom bottom relative extent
Definition at line 38 of file Viewport.hpp.
Viewport() [4/4]
sibr::Viewport::Viewport (const Viewport & parent_, float left, float top, float right, float bottom) inline
Constructor from a parent and relative extents.
Parameters
parent_ the parent viewport
left left relative extent
top top relative extent
right right relative extent
bottom bottom relative extent
Definition at line 48 of file Viewport.hpp.
Member Function Documentation
bind() [1/2]
void sibr::Viewport::bind (uint screenWidth, uint screenHeight) const
Bind an OpenGL viewport whose values are determined based on the viewport final dimensions and the target size.
Parameters
screenWidth the width of the rendertarget
screenHeight the height of the rendertarget
Definition at line 7 of file Viewport.cpp.
References height(), left(), top(), and width().
Referenced by sibr::DrawUtilities::baseRendering(), sibr::MultiViewInterface::displayImages(), sibr::MultiViewInterface::displayZoom(), sibr::GridMapping::highlightPixel(), sibr::MultiViewInterface::highlightPixel(), sibr::TrackBall::onRender(), sibr::ImagesGrid::onRender(), sibr::MultiMeshManager::onRender(), sibr::SceneDebugView::onRender(), sibr::ImageView::onRender(), sibr::MultiViewManager::onRender(), sibr::MultiViewBase::BasicSubView::render(), sibr::MeshViewer::render(), sibr::MonoRdrMode::render(), sibr::MeshViewer::renderLoop(), sibr::MultiViewBase::renderSubView(), and sibr::show().
bind() [2/2]
void sibr::Viewport::bind (void) const
Bind an OpenGL viewport whose values are determined based on the viewport final dimensions.
Definition at line 34 of file Viewport.cpp.
References finalHeight(), finalLeft(), finalTop(), and finalWidth().
bottom()
float sibr::Viewport::bottom (void) const inline
Returns
the relative bottom extent.
Definition at line 60 of file Viewport.hpp.
Referenced by finalBottom().
clear()
void sibr::Viewport::clear (const Vector3f & bgColor = Vector3f(0.f, 0.f, 0.f)) const
Perform a full OpenGL clear of the region defined by the viewport in the currently bound target.
Parameters
bgColor clear color
Definition at line 14 of file Viewport.cpp.
References finalHeight(), finalLeft(), finalTop(), and finalWidth().
Referenced by sibr::MultiViewInterface::displayImages(), sibr::ImagesGrid::onRender(), sibr::MultiMeshManager::onRender(), sibr::SceneDebugView::onRender(), sibr::ImageView::onRender(), sibr::MultiViewBase::BasicSubView::render(), sibr::MeshViewer::render(), sibr::MonoRdrMode::render(), sibr::StereoAnaglyphRdrMode::render(), and sibr::MeshViewer::renderLoop().
contains() [1/3]
bool sibr::Viewport::contains (const Vector2f & xy) const
Check if a point is inside the viewport.
Parameters
xy coordinates
Returns
true if the point is inside
Definition at line 54 of file Viewport.cpp.
References contains(), and xy().
contains() [2/3]
bool sibr::Viewport::contains (float x, float y) const
Check if a point is inside the viewport.
Parameters
x horizontal coordinate
y vertical coordinate
Returns
true if the point is inside
Definition at line 44 of file Viewport.cpp.
References finalBottom(), finalLeft(), finalRight(), and finalTop().
Referenced by contains().
contains() [3/3]
bool sibr::Viewport::contains (int x, int y) const
Check if a point is inside the viewport.
Parameters
x horizontal coordinate
y vertical coordinate
Returns
true if the point is inside
Definition at line 49 of file Viewport.cpp.
References finalBottom(), finalLeft(), finalRight(), and finalTop().
finalBottom()
float sibr::Viewport::finalBottom (void) const inline
Returns
the absolute bottom extent.
Definition at line 172 of file Viewport.hpp.
References _parent, bottom(), finalHeight(), and finalTop().
Referenced by contains(), sibr::Input::isInsideViewport(), sibr::TrackBall::mapToSphere(), sibr::MultiViewBase::mosaicLayout(), sibr::TrackBall::updateRotationRoll(), and sibr::GridMapping::updateZoomBox().
finalHeight()
float sibr::Viewport::finalHeight (void) const inline
Returns
the absolute viewport height.
Definition at line 180 of file Viewport.hpp.
References _parent, finalHeight(), and height().
Referenced by sibr::MultiViewBase::addIBRSubView(), sibr::MultiViewBase::addSubView(), bind(), clear(), sibr::MultiViewInterface::displayImages(), finalBottom(), finalHeight(), finalSize(), finalTop(), sibr::InteractiveCameraHandler::fromCamera(), sibr::InteractiveCameraHandler::interpolate(), sibr::TrackBall::isInTrackBall2dRegion(), sibr::TrackBall::mapToSphere(), sibr::MonoRdrMode::render(), sibr::StereoAnaglyphRdrMode::render(), sibr::LabelsManager::renderLabels(), sibr::TrackBall::setCameraAttributes(), sibr::GridMapping::setupGrid(), sibr::showImGuiWindow(), sibr::TrackBall::updateAspectWithViewport(), sibr::TrackBall::updateRotationRoll(), sibr::TrackBall::updateTranslationZ(), and sibr::GridMapping::updateZoomBox().
finalLeft()
float sibr::Viewport::finalLeft (void) const inline
Returns
the absolute left extent.
Definition at line 160 of file Viewport.hpp.
References _parent, finalLeft(), finalWidth(), and left().
Referenced by bind(), clear(), contains(), finalLeft(), finalRight(), finalTopLeft(), sibr::SubView::getViewportPosition(), sibr::Input::isInsideViewport(), sibr::TrackBall::mapToSphere(), sibr::MultiViewBase::mosaicLayout(), sibr::showImGuiWindow(), sibr::Input::subInput(), and sibr::TrackBall::updateRotationRoll().
finalRight()
float sibr::Viewport::finalRight (void) const inline
Returns
the absolute right extent.
Definition at line 168 of file Viewport.hpp.
References _parent, finalLeft(), finalWidth(), and right().
Referenced by contains(), sibr::Input::isInsideViewport(), sibr::TrackBall::mapToSphere(), sibr::MultiViewBase::mosaicLayout(), sibr::TrackBall::updateRotationRoll(), and sibr::GridMapping::updateZoomBox().
finalSize()
sibr::Vector2f sibr::Viewport::finalSize (void) const inline
Returns
the absolute viewport size.
Definition at line 184 of file Viewport.hpp.
References finalHeight(), and finalWidth().
Referenced by sibr::MultiViewInterface::displayZoom(), sibr::GridMapping::displayZoom(), sibr::SceneDebugView::gui_cameras(), sibr::GridMapping::highlightPixel(), sibr::MultiViewInterface::highlightPixel(), sibr::ImagesGrid::onUpdate(), sibr::ImageView::onUpdate(), pixAt(), sibr::DrawUtilities::rectanglePixels(), sibr::MultiViewInterface::renderImageView(), sibr::showImGuiWindow(), sibr::MultiViewInterface::updateImageView(), sibr::TrackBall::updateTrackBallCameraSize(), and sibr::GridMapping::updateZoomBox().
finalTop()
float sibr::Viewport::finalTop (void) const inline
Returns
the absolute top extent.
Definition at line 164 of file Viewport.hpp.
References _parent, finalHeight(), finalTop(), and top().
Referenced by bind(), clear(), contains(), finalBottom(), finalTop(), finalTopLeft(), sibr::SubView::getViewportPosition(), sibr::Input::isInsideViewport(), sibr::TrackBall::mapToSphere(), sibr::MultiViewBase::mosaicLayout(), sibr::showImGuiWindow(), sibr::Input::subInput(), and sibr::TrackBall::updateRotationRoll().
finalTopLeft()
Vector2f sibr::Viewport::finalTopLeft () const inline
Returns
the absolute cooridnates of the top left corner.
Definition at line 188 of file Viewport.hpp.
References finalLeft(), and finalTop().
Referenced by pixAt().
finalWidth()
float sibr::Viewport::finalWidth (void) const inline
Returns
the absolute viewport width.
Definition at line 176 of file Viewport.hpp.
References _parent, finalWidth(), and width().
Referenced by sibr::MultiViewBase::addIBRSubView(), sibr::MultiViewBase::addSubView(), bind(), clear(), sibr::MultiViewInterface::displayImages(), finalLeft(), finalRight(), finalSize(), finalWidth(), sibr::InteractiveCameraHandler::fromCamera(), sibr::InteractiveCameraHandler::interpolate(), sibr::TrackBall::isInTrackBall2dRegion(), sibr::TrackBall::mapToSphere(), sibr::MonoRdrMode::render(), sibr::StereoAnaglyphRdrMode::render(), sibr::LabelsManager::renderLabels(), sibr::TrackBall::setCameraAttributes(), sibr::GridMapping::setupGrid(), sibr::showImGuiWindow(), sibr::TrackBall::updateAspectWithViewport(), sibr::TrackBall::updateRotationRoll(), sibr::TrackBall::updateTranslationZ(), and sibr::GridMapping::updateZoomBox().
height()
float sibr::Viewport::height (void) const inline
Returns
the relative viewport height
Definition at line 65 of file Viewport.hpp.
Referenced by bind(), finalHeight(), isEmpty(), get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
isEmpty()
bool sibr::Viewport::isEmpty () const
Returns
true if the viewport is empty (0x0).
Definition at line 59 of file Viewport.cpp.
References height(), and width().
Referenced by sibr::InteractiveCameraHandler::fromCamera(), and sibr::InteractiveCameraHandler::update().
left()
float sibr::Viewport::left (void) const inline
Returns
the relative left extent.
Definition at line 54 of file Viewport.hpp.
Referenced by bind(), and finalLeft().
parent() [1/2]
void sibr::Viewport::parent (const Viewport * view) inline
Set the viewport parent.
Parameters
view the new parent
Definition at line 150 of file Viewport.hpp.
References _parent.
parent() [2/2]
const Viewport * sibr::Viewport::parent (void) const inline
Returns
the parent viewport if it exists or nullptr.
Definition at line 156 of file Viewport.hpp.
References _parent.
pixAt()
Vector2f sibr::Viewport::pixAt (const Vector2f & uv) const
Compute the absolute pixel coordinates based on relative normalized coordinates.
Parameters
uv the normalized UVs
Returns
the pixel coordinates
Definition at line 63 of file Viewport.cpp.
References finalSize(), and finalTopLeft().
right()
float sibr::Viewport::right (void) const inline
Returns
the relative right extent.
Definition at line 58 of file Viewport.hpp.
Referenced by finalRight().
top()
float sibr::Viewport::top (void) const inline
Returns
the relative top extent.
Definition at line 56 of file Viewport.hpp.
Referenced by bind(), and finalTop().
width()
float sibr::Viewport::width (void) const inline
Returns
the relative viewport width
Definition at line 63 of file Viewport.hpp.
Referenced by bind(), finalWidth(), isEmpty(), get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
Member Data Documentation
_bottom
float sibr::Viewport::_bottom private
Bottom extent.
Definition at line 144 of file Viewport.hpp.
_left
float sibr::Viewport::_left private
Left extent.
Definition at line 141 of file Viewport.hpp.
_parent
const Viewport* sibr::Viewport::_parent private
(optional)
Definition at line 139 of file Viewport.hpp.
Referenced by finalBottom(), finalHeight(), finalLeft(), finalRight(), finalTop(), finalWidth(), and parent().
_right
float sibr::Viewport::_right private
Right extent.
Definition at line 143 of file Viewport.hpp.
_top
float sibr::Viewport::_top private
Top extent.
Definition at line 142 of file Viewport.hpp.
The documentation for this class was generated from the following files:
src/core/graphics/Viewport.hpp
src/core/graphics/Viewport.cpp