SIBR: sibr::Timer Class Reference
sibr::Timer Class Reference
sibr_system
Timer to monitor performance of a section of code.
#include <SimpleTimer.hpp>
Public Types
typedef std::chrono::time_point< std::chrono::steady_clock > time_point
typedef std::chrono::nanoseconds nano
typedef std::chrono::microseconds micro
typedef std::chrono::milliseconds milli
typedef std::chrono::seconds s
Public Member Functions
Timer (bool start_now=false)
Constructor.
Timer (const Timer &timer)
Copy constructor.
void tic ()
Start measuring elapsed time.
void toc ()
Save currently elapsed time.
template<typename T = Timer::milli>
double deltaTimeFromLastTic () const
Get the time elapsed since the last tic, with a precisiond etemrined by the tempalte argument.
template<typename T = Timer::milli>
void display (bool toc_now=false)
Print a list of all the recorded tocs, with the precision specified as a template argument (by default in ms).
template<typename T = Timer::milli>
bool getDeltaTime (const time_point &tic, const time_point &toc, double &deltaTime) const
Get the time elapsed between two points in time, using the precision specified as a template argument (default to ms).
Public Attributes
const double timeResolution
Timer resolution.
Private Attributes
time_point current_tic
Initial tic.
std::vector< time_point > tocs
Recorded time points.
bool hasStarted
Is the timer currently running.
Detailed Description
Timer to monitor performance of a section of code.
Definition at line 13 of file SimpleTimer.hpp.
Member Typedef Documentation
micro
typedef std::chrono::microseconds sibr::Timer::micro
Definition at line 18 of file SimpleTimer.hpp.
milli
typedef std::chrono::milliseconds sibr::Timer::milli
Definition at line 19 of file SimpleTimer.hpp.
nano
typedef std::chrono::nanoseconds sibr::Timer::nano
Definition at line 17 of file SimpleTimer.hpp.
s
typedef std::chrono::seconds sibr::Timer::s
Definition at line 20 of file SimpleTimer.hpp.
time_point
typedef std::chrono::time_point<std::chrono::steady_clock> sibr::Timer::time_point
Definition at line 16 of file SimpleTimer.hpp.
Constructor & Destructor Documentation
Timer() [1/2]
sibr::Timer::Timer (bool start_now = false) inline
Constructor.
Create a timer.
Parameters
start_now start to measure time at creation
Definition at line 28 of file SimpleTimer.hpp.
References tic().
Timer() [2/2]
sibr::Timer::Timer (const Timer & timer) inline
Copy constructor.
Parameters
timer another timer
Definition at line 38 of file SimpleTimer.hpp.
References current_tic, and hasStarted.
Member Function Documentation
deltaTimeFromLastTic()
template<typename T = Timer::milli> double sibr::Timer::deltaTimeFromLastTic () const inline
Get the time elapsed since the last tic, with a precisiond etemrined by the tempalte argument.
Returns
the measured time (default: in ms)
Definition at line 66 of file SimpleTimer.hpp.
References current_tic, hasStarted, and toc().
Referenced by sibr::DoubleClick< sibr::Mouse::Left >::detected(), and sibr::UVUnwrapper::unwrap().
display()
template<typename T = Timer::milli> void sibr::Timer::display (bool toc_now = false) inline
Print a list of all the recorded tocs, with the precision specified as a template argument (by default in ms).
Parameters
toc_now should a toc be generated right now.
Definition at line 82 of file SimpleTimer.hpp.
References current_tic, hasStarted, toc(), and tocs.
getDeltaTime()
template<typename T = Timer::milli> bool sibr::Timer::getDeltaTime (const time_point & tic, const time_point & toc, double & deltaTime) const inline
Get the time elapsed between two points in time, using the precision specified as a template argument (default to ms).
Parameters
tic first time point
toc second time point
deltaTime will contain the computed duration
Returns
false if the elapsed time was below the timer precision.
Definition at line 111 of file SimpleTimer.hpp.
References tic(), timeResolution, and toc().
tic()
void sibr::Timer::tic () inline
Start measuring elapsed time.
Warning
This will clear existing recorded times.
Definition at line 46 of file SimpleTimer.hpp.
References current_tic, hasStarted, and tocs.
Referenced by sibr::DoubleClick< sibr::Mouse::Left >::detected(), getDeltaTime(), Timer(), and sibr::UVUnwrapper::unwrap().
toc()
void sibr::Timer::toc () inline
Save currently elapsed time.
Note
You can call toc multiple times in a row.
Definition at line 56 of file SimpleTimer.hpp.
References tocs.
Referenced by deltaTimeFromLastTic(), display(), and getDeltaTime().
Member Data Documentation
current_tic
time_point sibr::Timer::current_tic private
Initial tic.
Definition at line 123 of file SimpleTimer.hpp.
Referenced by deltaTimeFromLastTic(), display(), tic(), and Timer().
hasStarted
bool sibr::Timer::hasStarted private
Is the timer currently running.
Definition at line 125 of file SimpleTimer.hpp.
Referenced by deltaTimeFromLastTic(), display(), tic(), and Timer().
timeResolution
const double sibr::Timer::timeResolution
Initial value:
= (double)std::chrono::high_resolution_clock::period::num
            / std::chrono::high_resolution_clock::period::den
Timer resolution.
Definition at line 22 of file SimpleTimer.hpp.
Referenced by getDeltaTime().
tocs
std::vector<time_point> sibr::Timer::tocs private
Recorded time points.
Definition at line 124 of file SimpleTimer.hpp.
Referenced by display(), tic(), and toc().
The documentation for this class was generated from the following file:
src/core/system/SimpleTimer.hpp