SIBR: sibr::Video Class Reference
sibr::Video Class Reference
sibr_video
Video loaded from a file using OpenCV VideoCapture and FFMPEG.
#include <Video.hpp>
Public Member Functions
Video (const std::string &path="")
Constructor.
virtual bool load (const std::string &path)
Load from a given file on disk.
const sibr::Vector2i & getResolution ()
cv::Size getResolutionCV ()
int getCurrentFrameNumber ()
void setCurrentFrame (int i)
Seek a specific frame.
int getNumFrames ()
double getFrameRate ()
const Path & getFilepath () const
bool isLoaded ()
int getCodec ()
virtual void release ()
Stop reading from the file.
cv::Mat getVolume (float time_skiped_begin=0, float time_skiped_end=0)
Read a section of the video and store it in a cv::Mat, where each row contains a frame, stored as RGBRGBRGB...
cv::Mat getVolume (int starting_frame, int ending_frame)
Read a section of the video and store otin a cv::Mat, where each row contains a frame, stored as RGBRGBRGB...
cv::Mat next ()
cv::VideoCapture & getCVvideo ()
bool exists () const
Protected Member Functions
virtual void checkLoad ()
Check if the video is loaded.
Protected Attributes
cv::VideoCapture cap
Internal capture object.
Path filepath
The path to the video.
sibr::Vector2i resolution
Video resolution.
int nFrames = 0
Number of frames in the video.
double frameRate = 0.0
Video frame rate.
int codec = 0
Codec used to read the video.
bool loaded = false
Video loading status.
Private Member Functions
SIBR_CLASS_PTR (Video)
Detailed Description
Video loaded from a file using OpenCV VideoCapture and FFMPEG.
Definition at line 19 of file Video.hpp.
Constructor & Destructor Documentation
Video()
sibr::Video::Video (const std::string & path = "") inline
Constructor.
Parameters
path the path to the video file
Note
No loading will be performed at construction. Call load.
Definition at line 29 of file Video.hpp.
Member Function Documentation
checkLoad()
void sibr::Video::checkLoad () protected virtual
Check if the video is loaded.
Definition at line 119 of file Video.cpp.
References filepath, load(), loaded, and SIBR_ERR.
Referenced by getCodec(), getCurrentFrameNumber(), getCVvideo(), getFrameRate(), getNumFrames(), getResolution(), getResolutionCV(), getVolume(), next(), sibr::VideoPlayer::onGui(), setCurrentFrame(), sibr::VideoPlayer::update(), and sibr::VideoPlayer::updateCPU().
exists()
bool sibr::Video::exists () const
Returns
true if the video exists on disk.
Definition at line 114 of file Video.cpp.
References sibr::fileExists(), and getFilepath().
Referenced by sibr::loadVideoVolume().
getCodec()
int sibr::Video::getCodec ()
Returns
the ID of the codec used to decode the video.
Definition at line 60 of file Video.cpp.
References checkLoad(), and codec.
getCurrentFrameNumber()
int sibr::Video::getCurrentFrameNumber ()
Returns
the current frame ID.
Definition at line 32 of file Video.cpp.
References cap, and checkLoad().
Referenced by sibr::loadVideoVolume(), and sibr::VideoPlayer::onGui().
getCVvideo()
cv::VideoCapture & sibr::Video::getCVvideo ()
Returns
the underlying VideoCapture object.
Definition at line 108 of file Video.cpp.
References cap, and checkLoad().
Referenced by sibr::loadVideoVolume().
getFilepath()
const Path & sibr::Video::getFilepath () const
Returns
the path to the video file on disk.
Definition at line 52 of file Video.cpp.
References filepath.
Referenced by sibr::VideoUtils::computeSaveSimpleFlow(), sibr::VideoUtils::computeSaveVideoMaskBlur(), sibr::VideoUtils::computeSaveVideoMaskF(), and exists().
getFrameRate()
double sibr::Video::getFrameRate ()
Returns
the video framerate.
Definition at line 47 of file Video.cpp.
References checkLoad(), and frameRate.
Referenced by getVolume(), sibr::VideoPlayer::onGui(), sibr::VideoUtils::smallAlignmentVideo(), and sibr::VideoUtils::smallAlignmentVideo2().
getNumFrames()
int sibr::Video::getNumFrames ()
Returns
the total number of frames.
Definition at line 42 of file Video.cpp.
References checkLoad(), and nFrames.
Referenced by getVolume(), sibr::loadVideoVolume(), and sibr::VideoPlayer::onGui().
getResolution()
const sibr::Vector2i & sibr::Video::getResolution ()
Returns
the video resolution.
Definition at line 22 of file Video.cpp.
References checkLoad(), and resolution.
Referenced by sibr::buildVideoGaussianPyramid(), sibr::buildVideoLaplacianPyramid(), sibr::VideoUtils::getBackgroundImage(), sibr::VideoUtils::getBackGroundVideo(), sibr::VideoUtils::getTemporalSpatialRatio(), getVolume(), sibr::loadVideoVolume(), sibr::VideoUtils::smallAlignmentVideo(), and sibr::VideoUtils::smallAlignmentVideo2().
getResolutionCV()
cv::Size sibr::Video::getResolutionCV ()
Returns
the video resolution.
Definition at line 27 of file Video.cpp.
References checkLoad(), and resolution.
Referenced by sibr::VideoUtils::getMedian().
getVolume() [1/2]
cv::Mat sibr::Video::getVolume (float time_skiped_begin = 0, float time_skiped_end = 0)
Read a section of the video and store it in a cv::Mat, where each row contains a frame, stored as RGBRGBRGB...
linearly.
Parameters
time_skiped_begin time to skip at the beginning of the video, in seconds
time_skiped_end time to skip at the end of the video, in seconds
Returns
the frames data stored as described above.
Definition at line 71 of file Video.cpp.
References getFrameRate(), getNumFrames(), and getVolume().
Referenced by sibr::buildVideoGaussianPyramid(), sibr::buildVideoLaplacianPyramid(), sibr::VideoUtils::getBackgroundImage(), sibr::VideoUtils::getBackGroundVideo(), sibr::VideoUtils::getMedian(), sibr::VideoUtils::getTemporalSpatialRatio(), and getVolume().
getVolume() [2/2]
cv::Mat sibr::Video::getVolume (int starting_frame, int ending_frame)
Read a section of the video and store otin a cv::Mat, where each row contains a frame, stored as RGBRGBRGB...
linearly.
Parameters
starting_frame index of the first frame to extract
ending_frame index of the last frame to extract
Returns
the frames data stored as described above.
Definition at line 78 of file Video.cpp.
References cap, checkLoad(), getResolution(), sibr::Key::L, sibr::Key::N, and setCurrentFrame().
isLoaded()
bool sibr::Video::isLoaded ()
Returns
true if the video has been loaded.
Definition at line 56 of file Video.cpp.
References loaded.
load()
bool sibr::Video::load (const std::string & path) virtual
Load from a given file on disk.
Parameters
path path to the video
Returns
a success flag
Reimplemented in sibr::VideoPlayer.
Definition at line 6 of file Video.cpp.
References cap, codec, filepath, frameRate, loaded, nFrames, resolution, and SIBR_LOG.
Referenced by checkLoad().
next()
cv::Mat sibr::Video::next ()
Returns
the next frame.
Definition at line 100 of file Video.cpp.
References cap, and checkLoad().
Referenced by sibr::VideoUtils::smallAlignmentVideo(), sibr::VideoUtils::smallAlignmentVideo2(), and sibr::VideoPlayer::updateCPU().
release()
void sibr::Video::release () virtual
Stop reading from the file.
Definition at line 65 of file Video.cpp.
References cap, and loaded.
setCurrentFrame()
void sibr::Video::setCurrentFrame (int i)
Seek a specific frame.
Parameters
i the frame ID to seek
Definition at line 37 of file Video.cpp.
References cap, and checkLoad().
Referenced by getVolume(), sibr::loadVideoVolume(), sibr::VideoPlayer::onGui(), sibr::VideoUtils::smallAlignmentVideo(), sibr::VideoUtils::smallAlignmentVideo2(), and sibr::VideoPlayer::updateCPU().
SIBR_CLASS_PTR()
sibr::Video::SIBR_CLASS_PTR (Video) private
Member Data Documentation
cap
cv::VideoCapture sibr::Video::cap protected
Internal capture object.
Definition at line 99 of file Video.hpp.
Referenced by getCurrentFrameNumber(), getCVvideo(), getVolume(), load(), next(), release(), and setCurrentFrame().
codec
int sibr::Video::codec = 0 protected
Codec used to read the video.
Definition at line 105 of file Video.hpp.
Referenced by getCodec(), and load().
filepath
Path sibr::Video::filepath protected
The path to the video.
Definition at line 101 of file Video.hpp.
Referenced by checkLoad(), getFilepath(), and load().
frameRate
double sibr::Video::frameRate = 0.0 protected
Video frame rate.
Definition at line 104 of file Video.hpp.
Referenced by getFrameRate(), and load().
loaded
bool sibr::Video::loaded = false protected
Video loading status.
Definition at line 106 of file Video.hpp.
Referenced by checkLoad(), isLoaded(), load(), and release().
nFrames
int sibr::Video::nFrames = 0 protected
Number of frames in the video.
Definition at line 103 of file Video.hpp.
Referenced by getNumFrames(), and load().
resolution
sibr::Vector2i sibr::Video::resolution protected
Video resolution.
Definition at line 102 of file Video.hpp.
Referenced by bundle.InputImage::__str__(), getResolution(), getResolutionCV(), and load().
The documentation for this class was generated from the following files:
src/core/video/Video.hpp
src/core/video/Video.cpp