SIBR: sibr::InputState< TNbState, TEnum > Class Template Reference
sibr::InputState< TNbState, TEnum > Class Template Reference
Keep track of the pressed/active/released state of a set of keys/buttons.
#include <Input.hpp>
Public Member Functions
bool isActivated (TEnum code) const
Is an item currently active.
bool isReleased (TEnum code) const
Is an item released (lasts one frame).
bool isPressed (TEnum code) const
Is an item pressed at this frame (lasts one frame).
KeyCombination isPressedOnly (TEnum code) const
Is an item currently pressed and only this one (lasts one frame).
KeyCombination isActivatedOnly (TEnum code) const
Is an item currently active and only this one.
void press (TEnum code)
Declare an item as pressed at this frame.
void release (TEnum code)
Declare an item as released at this frame.
void silent (TEnum code)
Mute an item.
void clearStates (void)
Reset all items state.
void swapStates (void)
Update previous frame states with the current frame ones.
int getNumActivated (void) const
Private Attributes
std::array< bool, TNbState > _currentStates
Current frame state.
std::array< bool, TNbState > _lastStates
Last frame state.
Detailed Description
template<int TNbState, typename TEnum>
class sibr::InputState< TNbState, TEnum >
Keep track of the pressed/active/released state of a set of keys/buttons.
See also
Key::Code, Mouse::Code
Definition at line 202 of file Input.hpp.
Member Function Documentation
clearStates()
template<int TNbState, typename TEnum > void sibr::InputState< TNbState, TEnum >::clearStates (void) inline
Reset all items state.
Definition at line 275 of file Input.hpp.
Referenced by sibr::Window::AutoInitializer::AutoInitializer().
getNumActivated()
template<int TNbState, typename TEnum > int sibr::InputState< TNbState, TEnum >::getNumActivated (void) const inline
Returns
the number of keys currently activated.
Definition at line 286 of file Input.hpp.
Referenced by sibr::KeyCombination::operator bool(), and sibr::TrackBall::updateRadius().
isActivated()
template<int TNbState, typename TEnum > bool sibr::InputState< TNbState, TEnum >::isActivated (TEnum code) const inline
Is an item currently active.
Parameters
code the item code (key or mouse)
Returns
true if the item is active at this frame
Definition at line 210 of file Input.hpp.
Referenced by sibr::InputState< Mouse::count, Mouse::Code >::isActivatedOnly(), sibr::FPSCamera::moveUsingMousePan(), sibr::FPSCamera::moveUsingWASD(), sibr::MultiViewBase::onUpdate(), sibr::DatasetView::onUpdate(), sibr::MultiViewManager::onUpdate(), sibr::SceneDebugView::onUpdate(), sibr::ImagesGrid::onUpdate(), sibr::ImageView::onUpdate(), sibr::Orbit::update(), sibr::InteractiveCameraHandler::update(), sibr::GridMapping::updateDrag(), sibr::MultiViewInterface::updateDrag(), sibr::TrackBall::updateFromKeyboard(), sibr::MultiViewInterface::updateImageView(), sibr::TrackBall::updateTrackBallCamera(), sibr::TrackBall::updateTrackBallStatus(), sibr::GridMapping::updateZoomBox(), sibr::MultiViewInterface::updateZoomBox(), sibr::GridMapping::updateZoomScroll(), and sibr::MultiViewInterface::updateZoomScroll().
isActivatedOnly()
template<int TNbState, typename TEnum > KeyCombination sibr::InputState< TNbState, TEnum >::isActivatedOnly (TEnum code) const inline
Is an item currently active and only this one.
Parameters
code the item code (key or mouse)
Returns
true if the item is the only one active
Definition at line 246 of file Input.hpp.
Referenced by sibr::TrackBall::updateTrackBallStatus(), and sibr::TrackBall::updateZnearZFar().
isPressed()
template<int TNbState, typename TEnum > bool sibr::InputState< TNbState, TEnum >::isPressed (TEnum code) const inline
Is an item pressed at this frame (lasts one frame).
See also
isActivated
Parameters
code the item code (key or mouse)
Returns
true if the item is pressed at this frame
Definition at line 228 of file Input.hpp.
Referenced by sibr::DoubleClick< sibr::Mouse::Left >::detected(), sibr::InputState< Mouse::count, Mouse::Code >::isPressedOnly(), sibr::MultiViewBase::onUpdate(), sibr::show(), sibr::TrackBall::updateBallCenter(), sibr::MultiViewInterface::updateCurrentLayer(), sibr::GridMapping::updateDrag(), sibr::MultiViewInterface::updateDrag(), sibr::TrackBall::updateTrackBallStatus(), sibr::TrackBall::updateTranslationPlane(), sibr::GridMapping::updateZoomBox(), and sibr::MultiViewInterface::updateZoomBox().
isPressedOnly()
template<int TNbState, typename TEnum > KeyCombination sibr::InputState< TNbState, TEnum >::isPressedOnly (TEnum code) const inline
Is an item currently pressed and only this one (lasts one frame).
See also
isActivated
Parameters
code the item code (key or mouse)
Returns
true if the item is the only one pressed
Definition at line 238 of file Input.hpp.
isReleased()
template<int TNbState, typename TEnum > bool sibr::InputState< TNbState, TEnum >::isReleased (TEnum code) const inline
Is an item released (lasts one frame).
Parameters
code the item code (key or mouse)
Returns
true if the item is released at this frame
Definition at line 218 of file Input.hpp.
Referenced by sibr::ULRV2View::onUpdate(), sibr::MultiViewManager::onUpdate(), sibr::SceneDebugView::onUpdate(), sibr::ImagesGrid::onUpdate(), sibr::Orbit::update(), sibr::InteractiveCameraHandler::update(), sibr::GridMapping::updateDrag(), sibr::MultiViewInterface::updateDrag(), sibr::TrackBall::updateTrackBallStatus(), sibr::GridMapping::updateZoomBox(), and sibr::MultiViewInterface::updateZoomBox().
press()
template<int TNbState, typename TEnum > void sibr::InputState< TNbState, TEnum >::press (TEnum code) inline
Declare an item as pressed at this frame.
Parameters
code the item code (Key or Mouse).
Definition at line 253 of file Input.hpp.
Referenced by sibr::glfwKeyboardCallback(), and sibr::glfwMouseButtonCallback().
release()
template<int TNbState, typename TEnum > void sibr::InputState< TNbState, TEnum >::release (TEnum code) inline
Declare an item as released at this frame.
Parameters
code the item code (Key or Mouse).
Definition at line 260 of file Input.hpp.
Referenced by sibr::glfwKeyboardCallback(), and sibr::glfwMouseButtonCallback().
silent()
template<int TNbState, typename TEnum > void sibr::InputState< TNbState, TEnum >::silent (TEnum code) inline
Mute an item.
Parameters
code the item code (Key or Mouse).
Definition at line 268 of file Input.hpp.
swapStates()
template<int TNbState, typename TEnum > void sibr::InputState< TNbState, TEnum >::swapStates (void) inline
Update previous frame states with the current frame ones.
Definition at line 281 of file Input.hpp.
Member Data Documentation
_currentStates
template<int TNbState, typename TEnum > std::array<bool, TNbState> sibr::InputState< TNbState, TEnum >::_currentStates private
Current frame state.
Definition at line 295 of file Input.hpp.
Referenced by sibr::InputState< Mouse::count, Mouse::Code >::clearStates(), sibr::InputState< Mouse::count, Mouse::Code >::getNumActivated(), sibr::InputState< Mouse::count, Mouse::Code >::isActivated(), sibr::InputState< Mouse::count, Mouse::Code >::isPressed(), sibr::InputState< Mouse::count, Mouse::Code >::isReleased(), sibr::InputState< Mouse::count, Mouse::Code >::press(), sibr::InputState< Mouse::count, Mouse::Code >::release(), sibr::InputState< Mouse::count, Mouse::Code >::silent(), and sibr::InputState< Mouse::count, Mouse::Code >::swapStates().
_lastStates
template<int TNbState, typename TEnum > std::array<bool, TNbState> sibr::InputState< TNbState, TEnum >::_lastStates private
Last frame state.
Definition at line 296 of file Input.hpp.
Referenced by sibr::InputState< Mouse::count, Mouse::Code >::clearStates(), sibr::InputState< Mouse::count, Mouse::Code >::isPressed(), sibr::InputState< Mouse::count, Mouse::Code >::isReleased(), sibr::InputState< Mouse::count, Mouse::Code >::release(), sibr::InputState< Mouse::count, Mouse::Code >::silent(), and sibr::InputState< Mouse::count, Mouse::Code >::swapStates().
The documentation for this class was generated from the following file:
src/core/graphics/Input.hpp