SIBR: sibr::Frustum Class Reference
sibr::Frustum Class Reference
sibr_graphics
Represent a 3D frustum defined by 6 planes.
#include <Frustum.hpp>
Classes
struct Plane
Frustum plane representation.
Public Types
enum TestResult { OUTSIDE = 0, INTERSECT, INSIDE }
Result of intersection test.
Public Member Functions
Frustum (const Camera &cam)
Construct the furstum associated to a camera.
TestResult testSphere (const Vector3f &sphere, float radius)
Test if a sphere intersects the frustum or is contained in it.
Private Types
enum {
TOP = 0, BOTTOM, LEFT, RIGHT,
NEARP, FARP, COUNT
}
Location of each plane.
Private Attributes
std::array< Plane, COUNT > _planes
Frustum planes.
Detailed Description
Represent a 3D frustum defined by 6 planes.
Warning
This class has not been strongly tested!
Definition at line 15 of file Frustum.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Location of each plane.
Enumerator
TOP
BOTTOM
LEFT
RIGHT
NEARP
FARP
COUNT
Definition at line 65 of file Frustum.hpp.
TestResult
enum sibr::Frustum::TestResult
Result of intersection test.
Enumerator
OUTSIDE
INTERSECT
INSIDE
Definition at line 20 of file Frustum.hpp.
Constructor & Destructor Documentation
Frustum()
sibr::Frustum::Frustum (const Camera & cam)
Construct the furstum associated to a camera.
Parameters
cam the camera
Definition at line 9 of file Frustum.cpp.
References _planes, sibr::Camera::aspect(), BOTTOM, sibr::Camera::dir(), FARP, sibr::Camera::fovy(), LEFT, NEARP, sibr::Camera::position(), RIGHT, SIBR_DEGTORAD, TOP, sibr::Camera::up(), sibr::Key::X, sibr::Key::Y, sibr::Key::Z, sibr::Camera::zfar(), and sibr::Camera::znear().
Member Function Documentation
testSphere()
Frustum::TestResult sibr::Frustum::testSphere (const Vector3f & sphere, float radius)
Test if a sphere intersects the frustum or is contained in it.
Parameters
sphere sphere center
radius sphere radis
Returns
if the sphere is inside, intersecting or outside the frustum
Definition at line 68 of file Frustum.cpp.
References _planes, sibr::distance(), INSIDE, INTERSECT, and OUTSIDE.
Member Data Documentation
_planes
std::array<Plane, COUNT> sibr::Frustum::_planes private
Frustum planes.
Definition at line 78 of file Frustum.hpp.
Referenced by Frustum(), and testSphere().
The documentation for this class was generated from the following files:
src/core/graphics/Frustum.hpp
src/core/graphics/Frustum.cpp