SIBR: sibr::GLParameter Class Reference
sibr::GLParameter Class Reference
sibr_graphics
OpenGL shader uniform wrapper.
#include <Shader.hpp>
Public Member Functions
GLParameter (void)
Constructor.
void init (sibr::GLShader &shader, std::string name)
Link the uniform to a shader.
bool isInitialized (void) const
GLint handle (void) const
SIBR_OPT_INLINE void set (float f)
Set the uniform float value.
SIBR_OPT_INLINE void set (float a, float b)
Set the uniform vec2 value.
SIBR_OPT_INLINE void set (float a, float b, float c)
Set the uniform vec3 value.
SIBR_OPT_INLINE void set (float a, float b, float c, float d)
Set the uniform vec4 value.
SIBR_OPT_INLINE void set (const float *matrix)
Set the uniform mat4 value.
SIBR_OPT_INLINE void set (GLuint tex)
Set the uniform sampler value.
SIBR_OPT_INLINE void set (int v)
Set the uniform integer value.
SIBR_OPT_INLINE void set (bool b)
Set the uniform boolean value (converted to an int).
SIBR_OPT_INLINE void setArray (const float *pv, int size)
Set the uniform values defined as an array of floats.
SIBR_OPT_INLINE void setArray (const std::vector< int > &pv, int size)
Set the uniform values defined as an array of integers.
SIBR_OPT_INLINE void set (const Vector2i &v)
Set the uniform ivec2 value.
SIBR_OPT_INLINE void set (const Vector3i &v)
Set the uniform ivec3 value.
SIBR_OPT_INLINE void set (const Vector4i &v)
Set the uniform ivec4 value.
SIBR_OPT_INLINE void set (const Vector2f &v)
Set the uniform vec2 value.
SIBR_OPT_INLINE void set (const Vector3f &v)
Set the uniform vec3 value.
SIBR_OPT_INLINE void set (const Vector4f &v)
Set the uniform vec4 value.
SIBR_OPT_INLINE void set (const Matrix4f &m)
Set the uniform mat4 value.
SIBR_OPT_INLINE void setMatrixArray (const float *m, int num)
Set the uniform values defined as an array of mat4s (row major).
Private Member Functions
SIBR_OPT_INLINE void authorize (void) const
Check if the uniform/shader link is valid.
Private Attributes
sibr::GLShader * m_Shader
Linked shader.
GLint m_Handle
Uniform location.
std::string m_Name
Uniform name.
bool m_Strict
Should the program raise an error if the uniform is not found in the linked shader.
Detailed Description
OpenGL shader uniform wrapper.
Prefer using GLuniform instead.
See also
GLuniform
Definition at line 146 of file Shader.hpp.
Constructor & Destructor Documentation
GLParameter()
sibr::GLParameter::GLParameter (void)
Constructor.
Definition at line 222 of file Shader.cpp.
Member Function Documentation
authorize()
SIBR_OPT_INLINE void sibr::GLParameter::authorize (void) const private
Check if the uniform/shader link is valid.
handle()
GLint sibr::GLParameter::handle (void) const
Returns
the OpenGL uniform location handle.
Definition at line 234 of file Shader.cpp.
References m_Handle.
init()
void sibr::GLParameter::init (sibr::GLShader & shader, std::string name)
Link the uniform to a shader.
Parameters
shader the shader to link to
name the name of the uniform in the shader
Definition at line 239 of file Shader.cpp.
References sibr::GLShader::isStrict(), m_Handle, m_Name, m_Shader, m_Strict, sibr::GLShader::name(), and sibr::GLShader::shader().
Referenced by sibr::AddShadowRenderer::AddShadowRenderer(), sibr::BlurRenderer::BlurRenderer(), sibr::ColoredMeshRenderer::ColoredMeshRenderer(), sibr::DepthRenderer::DepthRenderer(), sibr::Intersector2D::frustrumQuadsIntersect(), sibr::GLuniform< sibr::Vector4f >::init(), sibr::InterfaceUtilities::initBaseShader(), sibr::DepthInputTextureArray::initDepthTextureArrays(), sibr::RGBDInputTextures::initializeDepthRenderTargets(), sibr::InterfaceUtilities::initMeshViewShader(), sibr::InterfaceUtilities::initMultiViewShader(), sibr::TrackBall::initTrackBallShader(), sibr::Skybox::load(), sibr::NormalRenderer::NormalRenderer(), sibr::PoissonRenderer::PoissonRenderer(), sibr::ULRV2Renderer::setupULRshader(), sibr::ShadowMapRenderer::ShadowMapRenderer(), sibr::TexturedMeshRenderer::TexturedMeshRenderer(), and sibr::ULRRenderer::ULRRenderer().
isInitialized()
bool sibr::GLParameter::isInitialized (void) const
Returns
true if the uniform was linked to a shader.
Definition at line 229 of file Shader.cpp.
References m_Handle, and m_Shader.
Referenced by sibr::GLuniform< sibr::Vector4f >::send(), and sibr::GLuniform< sibr::Vector4f >::setArray().
set() [1/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (bool b)
Set the uniform boolean value (converted to an int).
Parameters
b the new value
set() [2/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (const float * matrix)
Set the uniform mat4 value.
Parameters
matrix the 16 matrix components, in row order
set() [3/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (const Matrix4f & m)
Set the uniform mat4 value.
Parameters
m the new value
set() [4/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (const Vector2f & v)
Set the uniform vec2 value.
Parameters
v the new value
set() [5/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (const Vector2i & v)
Set the uniform ivec2 value.
Parameters
v the new value
set() [6/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (const Vector3f & v)
Set the uniform vec3 value.
Parameters
v the new value
set() [7/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (const Vector3i & v)
Set the uniform ivec3 value.
Parameters
v the new value
set() [8/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (const Vector4f & v)
Set the uniform vec4 value.
Parameters
v the new value
set() [9/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (const Vector4i & v)
Set the uniform ivec4 value.
Parameters
v the new value
set() [10/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (float a, float b)
Set the uniform vec2 value.
Parameters
a first component
b second component
set() [11/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (float a, float b, float c)
Set the uniform vec3 value.
Parameters
a first component
b second component
c third component
set() [12/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (float a, float b, float c, float d)
Set the uniform vec4 value.
Parameters
a first component
b second component
c third component
d fourth component
set() [13/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (float f)
Set the uniform float value.
Parameters
f the new value
Referenced by sibr::InterfaceUtilities::circle(), sibr::MultiViewInterface::displayHighlightedPixels(), sibr::MultiViewInterface::displayImages(), sibr::Intersector2D::frustrumQuadsIntersect(), sibr::DepthInputTextureArray::initDepthTextureArrays(), sibr::RGBDInputTextures::initializeDepthRenderTargets(), sibr::InterfaceUtilities::linePixels(), sibr::NormalRenderer::NormalRenderer(), sibr::TrackBall::onRender(), sibr::ColoredMeshRenderer::process(), sibr::TexturedMeshRenderer::process(), sibr::ULRV2Renderer::process(), sibr::ULRRenderer::process(), sibr::AddShadowRenderer::process(), sibr::BlurRenderer::process(), sibr::InterfaceUtilities::rectangle(), sibr::Skybox::render(), sibr::DepthRenderer::render(), sibr::NormalRenderer::render(), sibr::ShadowMapRenderer::render(), sibr::PoissonRenderer::render(), sibr::GLuniform< sibr::Vector4f >::send(), sibr::ShadowMapRenderer::ShadowMapRenderer(), and sibr::show().
set() [14/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (GLuint tex)
Set the uniform sampler value.
Parameters
tex the new value (ie the binding location of the texture)
set() [15/15]
SIBR_OPT_INLINE void sibr::GLParameter::set (int v)
Set the uniform integer value.
Parameters
v the new value
setArray() [1/2]
SIBR_OPT_INLINE void sibr::GLParameter::setArray (const float * pv, int size)
Set the uniform values defined as an array of floats.
Parameters
pv pointer to the float array
size number of elements
Referenced by sibr::GLuniform< sibr::Vector4f >::setArray().
setArray() [2/2]
SIBR_OPT_INLINE void sibr::GLParameter::setArray (const std::vector< int > & pv, int size)
Set the uniform values defined as an array of integers.
Parameters
pv pointer to the int array
size number of elements
setMatrixArray()
SIBR_OPT_INLINE void sibr::GLParameter::setMatrixArray (const float * m, int num)
Set the uniform values defined as an array of mat4s (row major).
Parameters
m pinter to the beginning of the matrix array
num number of matrices
Member Data Documentation
m_Handle
GLint sibr::GLParameter::m_Handle private
Uniform location.
Definition at line 267 of file Shader.hpp.
Referenced by handle(), init(), and isInitialized().
m_Name
std::string sibr::GLParameter::m_Name private
Uniform name.
Definition at line 268 of file Shader.hpp.
Referenced by init().
m_Shader
sibr::GLShader* sibr::GLParameter::m_Shader private
Linked shader.
Definition at line 266 of file Shader.hpp.
Referenced by init(), and isInitialized().
m_Strict
bool sibr::GLParameter::m_Strict private
Should the program raise an error if the uniform is not found in the linked shader.
Definition at line 269 of file Shader.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
src/core/graphics/Shader.hpp
src/core/graphics/Shader.cpp