SIBR: sibr::CropScaleImageUtility Class Reference
sibr::CropScaleImageUtility Class Reference
sibr_imgproc
Utility class to crop and rescale images, especially for uniformizing IBR datasets.
#include <CropScaleImageUtility.hpp>
Classes
struct Image
Image infos.
Public Member Functions
std::vector< std::string > getPathToImgs (const std::string &inputFileName)
Load a list_images.txt file and extract the image paths.
void logExecution (const sibr::Vector2i &resolution, unsigned nrImages, long long elapsedTime, bool wasTransformed, const char *log_file_name)
Log processing informations to a file.
void writeListImages (const std::string path_to_file, const std::vector< Image > &listOfImages)
Save a list of images to a list_images.txt file, where each image has a line "name w h".
void writeScaleFactor (const std::string path_to_file, float scaleFactor)
Write a scale float factor to a text file.
void writeTargetResolution (const std::string path_to_file, const sibr::Vector2i &targetResolution)
Write a resolution to a text file, as "w h".
sibr::Vector2i parseResolution (const std::string &param)
Extract an image resolution from a "wxh" string.
Detailed Description
Utility class to crop and rescale images, especially for uniformizing IBR datasets.
Definition at line 18 of file CropScaleImageUtility.hpp.
Member Function Documentation
getPathToImgs()
std::vector< std::string > sibr::CropScaleImageUtility::getPathToImgs (const std::string & inputFileName)
Load a list_images.txt file and extract the image paths.
Parameters
inputFileName path to the listing
Returns
a list of image paths
Definition at line 5 of file CropScaleImageUtility.cpp.
References ibr_convert_old_to_new::line.
Referenced by main().
logExecution()
void sibr::CropScaleImageUtility::logExecution (const sibr::Vector2i & resolution, unsigned nrImages, long long elapsedTime, bool wasTransformed, const char * log_file_name)
Log processing informations to a file.
Parameters
resolution the estimated resolution
nrImages the number of images
elapsedTime the time taken by the processing
wasTransformed was transforamtion applied
log_file_name the destination file path
Definition at line 21 of file CropScaleImageUtility.cpp.
References sibr::fileExists().
Referenced by main().
parseResolution()
sibr::Vector2i sibr::CropScaleImageUtility::parseResolution (const std::string & param)
Extract an image resolution from a "wxh" string.
Parameters
param the string to parse
Returns
the resolution
Definition at line 60 of file CropScaleImageUtility.cpp.
writeListImages()
void sibr::CropScaleImageUtility::writeListImages (const std::string path_to_file, const std::vector< Image > & listOfImages)
Save a list of images to a list_images.txt file, where each image has a line "name w h".
Parameters
path_to_file the destination file path
listOfImages the images to save to the list
Definition at line 49 of file CropScaleImageUtility.cpp.
Referenced by main().
writeScaleFactor()
void sibr::CropScaleImageUtility::writeScaleFactor (const std::string path_to_file, float scaleFactor)
Write a scale float factor to a text file.
Parameters
path_to_file the destination file path
scaleFactor the value to write
Definition at line 68 of file CropScaleImageUtility.cpp.
Referenced by main().
writeTargetResolution()
void sibr::CropScaleImageUtility::writeTargetResolution (const std::string path_to_file, const sibr::Vector2i & targetResolution)
Write a resolution to a text file, as "w h".
Parameters
path_to_file the destination file path
targetResolution the resolution to write
Definition at line 77 of file CropScaleImageUtility.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
src/core/imgproc/CropScaleImageUtility.hpp
src/core/imgproc/CropScaleImageUtility.cpp