SIBR: sibr::ITexture2D Class Reference
sibr::ITexture2D Class Reference abstract
sibr_graphics
Interface for a generic GPU 2D texture.
#include <Texture.hpp>
Public Types
typedef std::shared_ptr< ITexture2D > Ptr
typedef std::unique_ptr< ITexture2D > UPtr
Public Member Functions
virtual ~ITexture2D (void)
Destructor.
virtual GLuint handle (void) const =0
virtual uint w (void) const =0
virtual uint h (void) const =0
Detailed Description
Interface for a generic GPU 2D texture.
See also
Texture2D
Definition at line 18 of file Texture.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<ITexture2D> sibr::ITexture2D::Ptr
Definition at line 21 of file Texture.hpp.
UPtr
typedef std::unique_ptr<ITexture2D> sibr::ITexture2D::UPtr
Definition at line 22 of file Texture.hpp.
Constructor & Destructor Documentation
~ITexture2D()
virtual sibr::ITexture2D::~ITexture2D (void) inline virtual
Destructor.
Definition at line 26 of file Texture.hpp.
Member Function Documentation
h()
virtual uint sibr::ITexture2D::h (void) const pure virtual
Returns
the texture height.
Implemented in sibr::Texture2D< T_Type, T_NumComp >, and sibr::Texture2D< uchar, N >.
Referenced by sibr::ImageView::setTexture().
handle()
virtual GLuint sibr::ITexture2D::handle (void) const pure virtual
Returns
the texture handle.
Implemented in sibr::Texture2D< T_Type, T_NumComp >, and sibr::Texture2D< uchar, N >.
Referenced by sibr::ImageView::setTexture().
w()
virtual uint sibr::ITexture2D::w (void) const pure virtual
Returns
the texture width.
Implemented in sibr::Texture2D< T_Type, T_NumComp >, and sibr::Texture2D< uchar, N >.
Referenced by sibr::ImageView::setTexture().
The documentation for this class was generated from the following file:
src/core/graphics/Texture.hpp