SIBR: sibr::ImageView Class Reference
sibr::ImageView Class Reference
Basic view to display an image and inspect it.
#include <ImageView.hpp>
Public Member Functions
ImageView (bool interactiveMode=true)
Constructor.
void onRender (const Viewport &vpRender) override
Render the image in the currently bound rendertarget.
void onUpdate (Input &input, const Viewport &vp) override
Update user interactions.
void onGUI () override
Display GUI.
void setRenderTarget (const IRenderTarget &rt, uint handle=0)
Set an attachment of a rendertarget as the texture to display.
void setTexture (const ITexture2D &tex)
Set the texture to display.
template<typename T_Type , unsigned T_NumComp>
void setImage (const Image< T_Type, T_NumComp > &img)
Set an image as the texture to display.
void showGUI (bool opt)
Set if the GUI panel should be displayed or not.
void allowInteraction (bool opt)
Set if the user should be able to pan/zoom the image.
Public Member Functions inherited from sibr::ViewBase
ViewBase (const unsigned int w=720, const unsigned int h=480)
Constructor.
virtual ~ViewBase ()=default
Destructor.
virtual void onUpdate (Input &input)
virtual void onRender (Window &win)
Render content in a window.
virtual void onRenderIBR (IRenderTarget &dst, const Camera &eye)
Render content in a given rendertarget.
virtual void preRender (RenderTargetRGB &prev)
Legacy: Used to mix with previous pass.
virtual void whichRT (uint i)
Legacy: Set the internal RT to use.
virtual uint whichRT (void)
Legacy:
void setResolution (const Vector2i &size)
Set the view resolution.
const Vector2i & getResolution (void) const
void active (bool act)
Toggle view status.
bool active ()
void setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
bool isFocused (void) const
void setName (const std::string &name)
Define the name of the view (used for disambiguation of GUI, etc.).
const std::string & name () const
Protected Attributes
ITexture2D::Ptr _tex
Internal texture for the image input case.
GLuint _texHandle = 0
Texture to display.
GLShader _display
Shader.
GLuniform< sibr::Vector4f > _minVal
Normalization minimum.
GLuniform< sibr::Vector4f > _maxVal
Normalization maximum.
bool _lockChannels = true
Use the same normalization values for all channels.
std::array< bool, 4 > _showChannels
Display which channels.
GLuniform< sibr::Vector4f > _channels
Display which channels (shader).
GLuniform< sibr::Vector2f > _pos
Center position.
GLuniform< sibr::Vector2f > _size
Image size.
GLuniform< float > _scale
Image scale.
GLuniform< bool > _correctRatio
Use proper aspect ratio to display.
sibr::Vector3f _bgColor
Background color.
bool _showGUI = true
Show the GUI be displayed or not.
bool _allowInteraction = true
Should the user be able to pan/zoom into the image.
Protected Attributes inherited from sibr::ViewBase
uint _whichRT
Selected RT id.
std::vector< RenderTargetLum::Ptr > _masks
Rendering masks that can beused by some views/renderers.
bool _active = true
Is the view active.
Vector2i _resolution
View resolution.
bool _focus = false
Is the view focused.
std::string _name = ""
View name.
Private Member Functions
SIBR_CLASS_PTR (ImageView)
Additional Inherited Members
Public Types inherited from sibr::ViewBase
typedef std::shared_ptr< ViewBase > Ptr
Detailed Description
Basic view to display an image and inspect it.
Two modes are supported:
interactive, where the user can pan/zoom, rescale the values, display some channels, via the mouse and GUI.
fixed, where the image is displayed as is, without any modification possible.
Definition at line 16 of file ImageView.hpp.
Constructor & Destructor Documentation
ImageView()
sibr::ImageView::ImageView (bool interactiveMode = true)
Constructor.
Parameters
interactiveMode should the GUI panel be displayed and the user be able to pan/zoom into the image
Definition at line 8 of file ImageView.cpp.
References _allowInteraction, _bgColor, _channels, _correctRatio, _display, _maxVal, _minVal, _pos, _scale, _showChannels, _showGUI, _size, sibr::getShadersDirectory(), sibr::GLuniform< T >::init(), sibr::GLShader::init(), and sibr::loadFile().
Member Function Documentation
allowInteraction()
void sibr::ImageView::allowInteraction (bool opt) inline
Set if the user should be able to pan/zoom the image.
Parameters
opt interaction option
Definition at line 76 of file ImageView.hpp.
onGUI()
void sibr::ImageView::onGUI () override virtual
Display GUI.
Reimplemented from sibr::ViewBase.
Definition at line 46 of file ImageView.cpp.
References _bgColor, _correctRatio, _lockChannels, _maxVal, _minVal, _pos, _scale, _showChannels, _showGUI, _size, sibr::Key::End, sibr::GLuniform< T >::get(), and sibr::ViewBase::name().
onRender()
void sibr::ImageView::onRender (const Viewport & vpRender) override virtual
Render the image in the currently bound rendertarget.
Parameters
vpRender the region to render into
Reimplemented from sibr::ViewBase.
Definition at line 122 of file ImageView.cpp.
References _bgColor, _channels, _correctRatio, _display, _maxVal, _minVal, _pos, _scale, _showChannels, _size, _texHandle, sibr::GLShader::begin(), sibr::Viewport::bind(), CHECK_GL_ERROR, sibr::Viewport::clear(), sibr::GLShader::end(), sibr::GLuniform< T >::get(), sibr::RenderUtility::renderScreenQuad(), and sibr::GLuniform< T >::send().
onUpdate()
void sibr::ImageView::onUpdate (Input & input, const Viewport & vp) override virtual
Update user interactions.
Parameters
input the user input for the view
vp the view viewport
Reimplemented from sibr::ViewBase.
Definition at line 34 of file ImageView.cpp.
References _allowInteraction, _pos, _scale, sibr::Viewport::finalSize(), sibr::GLuniform< T >::get(), sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Mouse::Left, sibr::Input::mouseButton(), sibr::Input::mouseDeltaPosition(), and sibr::Input::mouseScroll().
setImage()
template<typename T_Type , unsigned T_NumComp> void sibr::ImageView::setImage (const Image< T_Type, T_NumComp > & img) inline
Set an image as the texture to display.
An internal copy of the image will be sent to the GPU.
Parameters
img the image
Definition at line 57 of file ImageView.hpp.
setRenderTarget()
void sibr::ImageView::setRenderTarget (const IRenderTarget & rt, uint handle = 0)
Set an attachment of a rendertarget as the texture to display.
Parameters
rt the rendertarget to display
handle the index of the attachment to display
Warning
Will only be valid until the RT is deleted.
Definition at line 108 of file ImageView.cpp.
References _size, _tex, _texHandle, sibr::GLuniform< T >::get(), sibr::IRenderTarget::h(), sibr::IRenderTarget::handle(), and sibr::IRenderTarget::w().
setTexture()
void sibr::ImageView::setTexture (const ITexture2D & tex)
Set the texture to display.
Parameters
tex the texture to display
Warning
Will only be valid until the texture is deleted.
Definition at line 114 of file ImageView.cpp.
References _size, _tex, _texHandle, sibr::GLuniform< T >::get(), sibr::ITexture2D::h(), sibr::ITexture2D::handle(), and sibr::ITexture2D::w().
showGUI()
void sibr::ImageView::showGUI (bool opt) inline
Set if the GUI panel should be displayed or not.
Parameters
opt display option
Definition at line 69 of file ImageView.hpp.
SIBR_CLASS_PTR()
sibr::ImageView::SIBR_CLASS_PTR (ImageView) private
Member Data Documentation
_allowInteraction
bool sibr::ImageView::_allowInteraction = true protected
Should the user be able to pan/zoom into the image.
Definition at line 101 of file ImageView.hpp.
Referenced by ImageView(), and onUpdate().
_bgColor
sibr::Vector3f sibr::ImageView::_bgColor protected
Background color.
Definition at line 99 of file ImageView.hpp.
Referenced by ImageView(), onGUI(), and onRender().
_channels
GLuniform<sibr::Vector4f> sibr::ImageView::_channels protected
Display which channels (shader).
Definition at line 92 of file ImageView.hpp.
Referenced by ImageView(), and onRender().
_correctRatio
GLuniform<bool> sibr::ImageView::_correctRatio protected
Use proper aspect ratio to display.
Definition at line 97 of file ImageView.hpp.
Referenced by ImageView(), onGUI(), and onRender().
_display
GLShader sibr::ImageView::_display protected
Shader.
Definition at line 85 of file ImageView.hpp.
Referenced by ImageView(), and onRender().
_lockChannels
bool sibr::ImageView::_lockChannels = true protected
Use the same normalization values for all channels.
Definition at line 89 of file ImageView.hpp.
Referenced by onGUI().
_maxVal
GLuniform<sibr::Vector4f> sibr::ImageView::_maxVal protected
Normalization maximum.
Definition at line 88 of file ImageView.hpp.
Referenced by ImageView(), onGUI(), and onRender().
_minVal
GLuniform<sibr::Vector4f> sibr::ImageView::_minVal protected
Normalization minimum.
Definition at line 87 of file ImageView.hpp.
Referenced by ImageView(), onGUI(), and onRender().
_pos
GLuniform<sibr::Vector2f> sibr::ImageView::_pos protected
Center position.
Definition at line 94 of file ImageView.hpp.
Referenced by ImageView(), onGUI(), onRender(), and onUpdate().
_scale
GLuniform<float> sibr::ImageView::_scale protected
Image scale.
Definition at line 96 of file ImageView.hpp.
Referenced by ImageView(), onGUI(), onRender(), and onUpdate().
_showChannels
std::array<bool, 4> sibr::ImageView::_showChannels protected
Display which channels.
Definition at line 91 of file ImageView.hpp.
Referenced by ImageView(), onGUI(), and onRender().
_showGUI
bool sibr::ImageView::_showGUI = true protected
Show the GUI be displayed or not.
Definition at line 100 of file ImageView.hpp.
Referenced by ImageView(), and onGUI().
_size
GLuniform<sibr::Vector2f> sibr::ImageView::_size protected
Image size.
Definition at line 95 of file ImageView.hpp.
Referenced by ImageView(), onGUI(), onRender(), setRenderTarget(), and setTexture().
_tex
ITexture2D::Ptr sibr::ImageView::_tex protected
Internal texture for the image input case.
Definition at line 82 of file ImageView.hpp.
Referenced by setRenderTarget(), and setTexture().
_texHandle
GLuint sibr::ImageView::_texHandle = 0 protected
Texture to display.
Definition at line 83 of file ImageView.hpp.
Referenced by onRender(), setRenderTarget(), and setTexture().
The documentation for this class was generated from the following files:
src/core/view/ImageView.hpp
src/core/view/ImageView.cpp