SIBR: sibr::LoadingProgress Class Reference
sibr::LoadingProgress Class Reference
sibr_system
Simple utility class for reporting on the standard output a loading progess.
#include <LoadingProgress.hpp>
Public Types
typedef std::chrono::steady_clock clock
typedef clock::time_point time_point
typedef std::function< void(float, const std::string &)> ExternalCallback
Public Member Functions
LoadingProgress (size_t maxIteration, const std::string &status="", float interval=1.f)
Create a progress bar.
void walk (size_t step=1)
Make the loading progress by the given number of steps.
float current (void) const
float interval (void) const
void interval (float interval)
Change the frequency of each report.
const std::string & status (void) const
void status (const std::string &message)
Insert a message in printed reports.
Private Member Functions
void report (void) const
Print a report.
Private Attributes
size_t _currentStep
current number of iterations
size_t _maxProgress
number of iterations before reaching 100%
std::string _status
inserted into a report (you can update it)
float _interval
time interval before next report (sec)
time_point _lastReport
time point saved during the last report
std::mutex _mutex
used ot thread-safe this class (not heavly tested!)
Detailed Description
Simple utility class for reporting on the standard output a loading progess.
(So users know your heavy computations didn't crash)
Instructions: 1) Instantiate just before a loop (for or while), providing the max number of iterations. 2) Call walk() once in a the loop.
Definition at line 22 of file LoadingProgress.hpp.
Member Typedef Documentation
clock
typedef std::chrono::steady_clock sibr::LoadingProgress::clock
Definition at line 25 of file LoadingProgress.hpp.
ExternalCallback
typedef std::function<void (float, const std::string&)> sibr::LoadingProgress::ExternalCallback
Definition at line 27 of file LoadingProgress.hpp.
time_point
typedef clock::time_point sibr::LoadingProgress::time_point
Definition at line 26 of file LoadingProgress.hpp.
Constructor & Destructor Documentation
LoadingProgress()
sibr::LoadingProgress::LoadingProgress (size_t maxIteration, const std::string & status = "", float interval = 1.f)
Create a progress bar.
Parameters
maxIteration total number of iterations
status a message that will be inserted in next reports
interval an interval of time between each report.
Definition at line 7 of file LoadingProgress.cpp.
References _lastReport.
Member Function Documentation
current()
float sibr::LoadingProgress::current (void) const
Returns
the current progress in a range [0.0, 1.0]
Definition at line 28 of file LoadingProgress.cpp.
References _currentStep, and _maxProgress.
Referenced by report().
interval() [1/2]
void sibr::LoadingProgress::interval (float interval) inline
Change the frequency of each report.
Parameters
interval the new step interval to use
Definition at line 72 of file LoadingProgress.hpp.
References _interval, and interval().
interval() [2/2]
float sibr::LoadingProgress::interval (void) const inline
Returns
the time interval used
Definition at line 69 of file LoadingProgress.hpp.
References _interval.
Referenced by interval().
report()
void sibr::LoadingProgress::report (void) const private
Print a report.
Definition at line 35 of file LoadingProgress.cpp.
References _status, current(), and SIBR_LOG.
Referenced by walk().
status() [1/2]
void sibr::LoadingProgress::status (const std::string & message) inline
Insert a message in printed reports.
Parameters
message the message to insert
Definition at line 80 of file LoadingProgress.hpp.
References _status.
status() [2/2]
const std::string & sibr::LoadingProgress::status (void) const inline
Returns
the status message used
Definition at line 77 of file LoadingProgress.hpp.
References _status.
walk()
void sibr::LoadingProgress::walk (size_t step = 1)
Make the loading progress by the given number of steps.
Parameters
step number of steps
Definition at line 14 of file LoadingProgress.cpp.
References _currentStep, _interval, _lastReport, _maxProgress, _mutex, sibr::Key::count, and report().
Referenced by sibr::MeshTexturing::reproject().
Member Data Documentation
_currentStep
size_t sibr::LoadingProgress::_currentStep private
current number of iterations
Definition at line 59 of file LoadingProgress.hpp.
Referenced by current(), and walk().
_interval
float sibr::LoadingProgress::_interval private
time interval before next report (sec)
Definition at line 62 of file LoadingProgress.hpp.
Referenced by interval(), and walk().
_lastReport
time_point sibr::LoadingProgress::_lastReport private
time point saved during the last report
Definition at line 63 of file LoadingProgress.hpp.
Referenced by LoadingProgress(), and walk().
_maxProgress
size_t sibr::LoadingProgress::_maxProgress private
number of iterations before reaching 100%
Definition at line 60 of file LoadingProgress.hpp.
Referenced by current(), and walk().
_mutex
std::mutex sibr::LoadingProgress::_mutex private
used ot thread-safe this class (not heavly tested!)
Definition at line 64 of file LoadingProgress.hpp.
Referenced by walk().
_status
std::string sibr::LoadingProgress::_status private
inserted into a report (you can update it)
Definition at line 61 of file LoadingProgress.hpp.
Referenced by report(), and status().
The documentation for this class was generated from the following files:
src/core/system/LoadingProgress.hpp
src/core/system/LoadingProgress.cpp