SIBR: sibr::ULRV3View Class Reference
sibr::ULRV3View Class Reference
Wrap a ULR renderer with additional parameters and information.
#include <ULRV3View.hpp>
Public Member Functions
ULRV3View (const sibr::BasicIBRScene::Ptr &ibrScene, uint render_w, uint render_h)
Constructor.
void setScene (const sibr::BasicIBRScene::Ptr &newScene)
Replace the current scene.
void onRenderIBR (sibr::IRenderTarget &dst, const sibr::Camera &eye) override
Perform rendering.
void onUpdate (Input &input) override
Update inputs (do nothing).
void onGUI () override
Update the GUI.
const ULRV3Renderer::Ptr & getULRrenderer () const
void setMode (const WeightsMode mode)
Set the renderer blending weights mode.
const std::shared_ptr< sibr::BasicIBRScene > & getScene () const
Public Member Functions inherited from sibr::ViewBase
ViewBase (const unsigned int w=720, const unsigned int h=480)
Constructor.
virtual ~ViewBase ()=default
Destructor.
virtual void onRender (Window &win)
Render content in a window.
virtual void onRender (const Viewport &vpRender)
Render content in the currently bound RT, using a specific viewport.
virtual void onUpdate (Input &input, const Viewport &vp)
Update state based on user input.
virtual void preRender (RenderTargetRGB &prev)
Legacy: Used to mix with previous pass.
virtual void whichRT (uint i)
Legacy: Set the internal RT to use.
virtual uint whichRT (void)
Legacy:
void setResolution (const Vector2i &size)
Set the view resolution.
const Vector2i & getResolution (void) const
void active (bool act)
Toggle view status.
bool active ()
void setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
bool isFocused (void) const
void setName (const std::string &name)
Define the name of the view (used for disambiguation of GUI, etc.).
const std::string & name () const
Protected Member Functions
void updateCameras (bool allowResetToDefault)
Update the camera informations in the ULR renderer based on the current rendering mode and selected index.
Protected Attributes
std::shared_ptr< sibr::BasicIBRScene > _scene
The current scene.
ULRV3Renderer::Ptr _ulrRenderer
The ULR renderer.
PoissonRenderer::Ptr _poissonRenderer
The poisson filling renderer.
RenderTargetRGBA::Ptr _blendRT
ULR destination RT.
RenderTargetRGBA::Ptr _poissonRT
Poisson filling destination RT.
bool _poissonBlend = false
Should Poisson filling be applied.
RenderMode _renderMode = ALL_CAMS
Current rendering mode.
WeightsMode _weightsMode = ULR_W
Current blend weights mode.
int _singleCamId = 0
Selected camera for the single view mode.
int _everyNCamStep = 1
Camera step size for the every other N mode.
Protected Attributes inherited from sibr::ViewBase
uint _whichRT
Selected RT id.
std::vector< RenderTargetLum::Ptr > _masks
Rendering masks that can beused by some views/renderers.
bool _active = true
Is the view active.
Vector2i _resolution
View resolution.
bool _focus = false
Is the view focused.
std::string _name = ""
View name.
Private Types
enum RenderMode { ALL_CAMS, ONE_CAM, LEAVE_ONE_OUT, EVERY_N_CAM }
Rendering mode: default, use only one camera, use all cameras but one.
enum WeightsMode { ULR_W, VARIANCE_BASED_W, ULR_FAST }
Blending mode: keep the four best values per pixel, or aggregate them all.
Private Member Functions
SIBR_CLASS_PTR (ULRV3View)
Additional Inherited Members
Public Types inherited from sibr::ViewBase
typedef std::shared_ptr< ViewBase > Ptr
Detailed Description
Wrap a ULR renderer with additional parameters and information.
Definition at line 17 of file ULRV3View.hpp.
Member Enumeration Documentation
RenderMode
enum sibr::ULRV3View::RenderMode private
Rendering mode: default, use only one camera, use all cameras but one.
Enumerator
ALL_CAMS
ONE_CAM
LEAVE_ONE_OUT
EVERY_N_CAM
Definition at line 22 of file ULRV3View.hpp.
WeightsMode
enum sibr::ULRV3View::WeightsMode private
Blending mode: keep the four best values per pixel, or aggregate them all.
Enumerator
ULR_W
VARIANCE_BASED_W
ULR_FAST
Definition at line 25 of file ULRV3View.hpp.
Constructor & Destructor Documentation
ULRV3View()
sibr::ULRV3View::ULRV3View (const sibr::BasicIBRScene::Ptr & ibrScene, uint render_w, uint render_h)
Constructor.
Parameters
ibrScene The scene to use for rendering.
render_w rendering width
render_h rendering height
Definition at line 4 of file ULRV3View.cpp.
References _blendRT, _poissonRenderer, _poissonRT, _scene, _ulrRenderer, and SIBR_CLAMP_UVS.
Member Function Documentation
getScene()
const std::shared_ptr<sibr::BasicIBRScene>& sibr::ULRV3View::getScene () const inline
Returns
a reference to the scene
Definition at line 69 of file ULRV3View.hpp.
getULRrenderer()
const ULRV3Renderer::Ptr& sibr::ULRV3View::getULRrenderer () const inline
Returns
a reference to the renderer.
Definition at line 60 of file ULRV3View.hpp.
onGUI()
void sibr::ULRV3View::onGUI () override virtual
Update the GUI.
Reimplemented from sibr::ViewBase.
Definition at line 93 of file ULRV3View.cpp.
References sibr::clamp(), sibr::Key::End, and ImGui::PushScaledItemWidth().
onRenderIBR()
void sibr::ULRV3View::onRenderIBR (sibr::IRenderTarget & dst, const sibr::Camera & eye) override virtual
Perform rendering.
Called by the view manager or rendering mode.
Parameters
dst The destination rendertarget.
eye The novel viewpoint.
Reimplemented from sibr::ViewBase.
Definition at line 70 of file ULRV3View.cpp.
References sibr::blit(), and ibr_preprocess_rc_to_sibr::dst.
onUpdate()
void sibr::ULRV3View::onUpdate (Input & input) override virtual
Update inputs (do nothing).
Parameters
input The inputs state.
Reimplemented from sibr::ViewBase.
Definition at line 89 of file ULRV3View.cpp.
setMode()
void sibr::ULRV3View::setMode (const WeightsMode mode)
Set the renderer blending weights mode.
Parameters
mode the new mode to use
See also
WeightsMode
Definition at line 57 of file ULRV3View.cpp.
setScene()
void sibr::ULRV3View::setScene (const sibr::BasicIBRScene::Ptr & newScene)
Replace the current scene.
Parameters
newScene the new scene to render
Definition at line 31 of file ULRV3View.cpp.
SIBR_CLASS_PTR()
sibr::ULRV3View::SIBR_CLASS_PTR (ULRV3View) private
updateCameras()
void sibr::ULRV3View::updateCameras (bool allowResetToDefault) protected
Update the camera informations in the ULR renderer based on the current rendering mode and selected index.
Parameters
allowResetToDefault If true, when the rendering mode is ALL_CAMS, the cameras information will be updated.
Definition at line 143 of file ULRV3View.cpp.
Member Data Documentation
_blendRT
RenderTargetRGBA::Ptr sibr::ULRV3View::_blendRT protected
ULR destination RT.
Definition at line 83 of file ULRV3View.hpp.
Referenced by ULRV3View().
_everyNCamStep
int sibr::ULRV3View::_everyNCamStep = 1 protected
Camera step size for the every other N mode.
Definition at line 91 of file ULRV3View.hpp.
_poissonBlend
bool sibr::ULRV3View::_poissonBlend = false protected
Should Poisson filling be applied.
Definition at line 86 of file ULRV3View.hpp.
_poissonRenderer
PoissonRenderer::Ptr sibr::ULRV3View::_poissonRenderer protected
The poisson filling renderer.
Definition at line 81 of file ULRV3View.hpp.
Referenced by ULRV3View().
_poissonRT
RenderTargetRGBA::Ptr sibr::ULRV3View::_poissonRT protected
Poisson filling destination RT.
Definition at line 84 of file ULRV3View.hpp.
Referenced by ULRV3View().
_renderMode
RenderMode sibr::ULRV3View::_renderMode = ALL_CAMS protected
Current rendering mode.
Definition at line 88 of file ULRV3View.hpp.
_scene
std::shared_ptr<sibr::BasicIBRScene> sibr::ULRV3View::_scene protected
The current scene.
Definition at line 79 of file ULRV3View.hpp.
Referenced by ULRV3View().
_singleCamId
int sibr::ULRV3View::_singleCamId = 0 protected
Selected camera for the single view mode.
Definition at line 90 of file ULRV3View.hpp.
_ulrRenderer
ULRV3Renderer::Ptr sibr::ULRV3View::_ulrRenderer protected
The ULR renderer.
Definition at line 80 of file ULRV3View.hpp.
Referenced by ULRV3View().
_weightsMode
WeightsMode sibr::ULRV3View::_weightsMode = ULR_W protected
Current blend weights mode.
Definition at line 89 of file ULRV3View.hpp.
The documentation for this class was generated from the following files:
src/projects/ulr/renderer/ULRV3View.hpp
src/projects/ulr/renderer/ULRV3View.cpp