SIBR: sibr::RayHit Class Reference
sibr::RayHit Class Reference
sibr_raycaster
Contains information about a ray hit.
#include <Ray.hpp>
Classes
struct BCCoord
Barycentric coordinates.
struct Primitive
Infos about the object that was hit.
Public Member Functions
RayHit (const Ray &r, float dist, const BCCoord &coord, const sibr::Vector3f &normal, const Primitive &prim)
Construct a hit record.
RayHit ()
Non-hit constructor.
const Ray & ray (void) const
float dist (void) const
const BCCoord & barycentricCoord (void) const
sibr::Vector3f interpolateUV (void) const
Return the proper barycentric factors for interpolating information stored at each vertex of a triangle.
const sibr::Vector3f & normal (void) const
const Primitive & primitive (void) const
bool hitSomething (void) const
Static Public Attributes
static const float InfinityDist = std::numeric_limits<float>::infinity()
Private Attributes
Ray _ray
casted ray
float _dist
distance from the ray's origin to the hit
BCCoord _coord
barycentric coordinate on the triangle that was hit
sibr::Vector3f _normal
normal of the triangle that was hit
Primitive _prim
infos about the primitive that was hit
Detailed Description
Contains information about a ray hit.
Definition at line 60 of file Ray.hpp.
Constructor & Destructor Documentation
RayHit() [1/2]
sibr::RayHit::RayHit (const Ray & r, float dist, const BCCoord & coord, const sibr::Vector3f & normal, const Primitive & prim)
Construct a hit record.
Parameters
r the ray
dist intersection distance
coord barycentric coordinates
normal surface normal
prim intersected primitive
Definition at line 15 of file Ray.cpp.
References _dist, _normal, dist(), and sibr::length().
RayHit() [2/2]
sibr::RayHit::RayHit () inline
Non-hit constructor.
Definition at line 91 of file Ray.hpp.
Member Function Documentation
barycentricCoord()
const RayHit::BCCoord & sibr::RayHit::barycentricCoord (void) const inline
Returns
the barycentric coordinates of the hit point on the triangle that was hit
Definition at line 157 of file Ray.hpp.
References _coord.
Referenced by sibr::MeshTexturing::interpolate(), interpolateUV(), sibr::Raycaster::smoothColor(), sibr::Raycaster::smoothNormal(), and sibr::Raycaster::smoothUV().
dist()
float sibr::RayHit::dist (void) const inline
Returns
the distance from the ray origin to the hit
Definition at line 154 of file Ray.hpp.
References _dist.
Referenced by sibr::CameraRaycaster::computeClippingPlanes(), sibr::InteractiveCameraHandler::fromCamera(), RayHit(), sibr::MeshTexturing::reproject(), sibr::TrackBall::updateBallCenter(), sibr::Orbit::updateOrbitParameters(), sibr::Orbit::updateOrbitParametersCentered(), and sibr::TrackBall::updateTranslationPlane().
hitSomething()
bool sibr::RayHit::hitSomething (void) const inline
Returns
true if an object was hit.
Definition at line 167 of file Ray.hpp.
References _dist, and InfinityDist.
Referenced by sibr::CameraRaycaster::computeClippingPlanes(), sibr::InteractiveCameraHandler::fromCamera(), sibr::MeshTexturing::hitTest(), sibr::MeshTexturing::reproject(), sibr::TrackBall::updateBallCenter(), sibr::Orbit::updateOrbitParameters(), sibr::Orbit::updateOrbitParametersCentered(), and sibr::TrackBall::updateTranslationPlane().
interpolateUV()
sibr::Vector3f sibr::RayHit::interpolateUV (void) const
Return the proper barycentric factors for interpolating information stored at each vertex of a triangle.
e.g: get fragment color using color = factor[0]*colorVert0 + factor[1]*colorVert1 + factor[2]*colorVert2 It consider the following triangle: https://embree.github.io/images/triangle_uv.png
Returns
the barycentric coordinates
Definition at line 28 of file Ray.cpp.
References barycentricCoord(), sibr::RayHit::BCCoord::u, and sibr::RayHit::BCCoord::v.
normal()
const sibr::Vector3f & sibr::RayHit::normal (void) const inline
Returns
the normal of the triangle that was hit.
Definition at line 160 of file Ray.hpp.
References _normal.
primitive()
const RayHit::Primitive & sibr::RayHit::primitive (void) const inline
Returns
information about the primitive that was hit.
Definition at line 163 of file Ray.hpp.
References _prim.
Referenced by sibr::MeshTexturing::interpolate(), sibr::Raycaster::smoothColor(), sibr::Raycaster::smoothNormal(), and sibr::Raycaster::smoothUV().
ray()
const Ray & sibr::RayHit::ray (void) const inline
Returns
the ray that was casted
Definition at line 151 of file Ray.hpp.
References _ray.
Member Data Documentation
_coord
BCCoord sibr::RayHit::_coord private
barycentric coordinate on the triangle that was hit
Definition at line 123 of file Ray.hpp.
Referenced by barycentricCoord().
_dist
float sibr::RayHit::_dist private
distance from the ray's origin to the hit
Definition at line 122 of file Ray.hpp.
Referenced by dist(), hitSomething(), and RayHit().
_normal
sibr::Vector3f sibr::RayHit::_normal private
normal of the triangle that was hit
Definition at line 124 of file Ray.hpp.
Referenced by normal(), and RayHit().
_prim
Primitive sibr::RayHit::_prim private
infos about the primitive that was hit
Definition at line 125 of file Ray.hpp.
Referenced by primitive().
_ray
Ray sibr::RayHit::_ray private
casted ray
Definition at line 121 of file Ray.hpp.
Referenced by ray().
InfinityDist
SIBR_RAYCASTER_EXPORT const float sibr::RayHit::InfinityDist = std::numeric_limits<float>::infinity() static
Definition at line 63 of file Ray.hpp.
Referenced by sibr::Raycaster::hitSomething(), hitSomething(), sibr::Raycaster::hitSomething8(), sibr::Raycaster::intersect(), and sibr::Raycaster::intersect8().
The documentation for this class was generated from the following files:
src/core/raycaster/Ray.hpp
src/core/raycaster/Ray.cpp