SIBR: sibr::ColoredMeshRenderer Class Reference
sibr::ColoredMeshRenderer Class Reference
sibr_renderer
Render a mesh colored using the per-vertex color attribute.
#include <ColoredMeshRenderer.hpp>
Public Types
typedef std::shared_ptr< ColoredMeshRenderer > Ptr
Public Member Functions
ColoredMeshRenderer (void)
Constructor.
void process (const Mesh &mesh, const Camera &eye, IRenderTarget &dst, sibr::Mesh::RenderMode mode=sibr::Mesh::FillRenderMode, bool backFaceCulling=true)
Render the mesh using its vertices colors, interpolated over triangles.
Private Attributes
GLShader _shader
Color shader.
GLParameter _paramMVP
MVP uniform.
Detailed Description
Render a mesh colored using the per-vertex color attribute.
Definition at line 15 of file ColoredMeshRenderer.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<ColoredMeshRenderer> sibr::ColoredMeshRenderer::Ptr
Definition at line 18 of file ColoredMeshRenderer.hpp.
Constructor & Destructor Documentation
ColoredMeshRenderer()
sibr::ColoredMeshRenderer::ColoredMeshRenderer (void)
Constructor.
Definition at line 6 of file ColoredMeshRenderer.cpp.
References _paramMVP, _shader, sibr::getShadersDirectory(), sibr::GLParameter::init(), sibr::GLShader::init(), and sibr::loadFile().
Member Function Documentation
process()
void sibr::ColoredMeshRenderer::process (const Mesh & mesh, const Camera & eye, IRenderTarget & dst, sibr::Mesh::RenderMode mode = sibr::Mesh::FillRenderMode, bool backFaceCulling = true)
Render the mesh using its vertices colors, interpolated over triangles.
Parameters
mesh the mesh to render
eye the viewpoint to use
dst the destination rendertarget
mode the rendering mode of the mesh
backFaceCulling should backface culling be performed
Definition at line 14 of file ColoredMeshRenderer.cpp.
References _paramMVP, _shader, sibr::GLShader::begin(), sibr::IRenderTarget::bind(), sibr::GLShader::end(), sibr::Mesh::render(), sibr::GLParameter::set(), sibr::IRenderTarget::unbind(), and sibr::Camera::viewproj().
Member Data Documentation
_paramMVP
GLParameter sibr::ColoredMeshRenderer::_paramMVP private
MVP uniform.
Definition at line 42 of file ColoredMeshRenderer.hpp.
Referenced by ColoredMeshRenderer(), and process().
_shader
GLShader sibr::ColoredMeshRenderer::_shader private
Color shader.
Definition at line 41 of file ColoredMeshRenderer.hpp.
Referenced by ColoredMeshRenderer(), and process().
The documentation for this class was generated from the following files:
src/core/renderer/ColoredMeshRenderer.hpp
src/core/renderer/ColoredMeshRenderer.cpp