SIBR: sibr::Raycaster Class Reference
sibr::Raycaster Class Reference
sibr_raycaster
This class can be used to cast rays against a scene containing triangular meshes.
#include <Raycaster.hpp>
Public Types
typedef std::shared_ptr< RTCDevice > RTCDevicePtr
typedef std::shared_ptr< RTCScene > RTCScenePtr
typedef std::shared_ptr< Raycaster > Ptr
typedef uint geomId
Public Member Functions
~Raycaster (void)
Destructor.
bool init (RTCSceneFlags sceneType=RTC_SCENE_FLAG_NONE)
Init the raycaster.
geomId addMesh (const sibr::Mesh &mesh)
Add a triangle mesh to the raycast scene, taht you won't modify frequently Return the id of the geometry added so you can track your mesh (and compare its id to the one stored in RayHits).
geomId addDynamicMesh (const sibr::Mesh &mesh)
Add a triangle mesh to the raycast scene, that you will frequently update.
geomId addGenericMesh (const sibr::Mesh &mesh, RTCBuildQuality type)
Add a triangle mesh to the raycast scene.
void xformRtcMeshOnly (sibr::Mesh &mesh, geomId mesh_id, sibr::Matrix4f &mat, sibr::Vector3f &centerPt, float &maxlen)
Transform the vertices of a mesh by applying a sibr::Matrix4f mat.
RayHit intersect (const Ray &ray, float minDist=0.f)
Launch a ray into the raycaster scene.
std::array< RayHit, 8 > intersect8 (const std::array< Ray, 8 > &inray, const std::vector< int > &valid8=std::vector< int >(8,-1), float minDist=0.f)
Launch 8 rays into the raycaster scene in an optimized fashion, reporting intersections infos.
bool hitSomething (const Ray &ray, float minDist=0.f)
Optimized ray-cast that only tells you if an intersection occured.
std::array< bool, 8 > hitSomething8 (const std::array< Ray, 8 > &inray, float minDist=0.f)
Launch 8 rays into the raycaster scene in an optimized fashion, reporting if intersections occured.
void disableGeom (geomId id)
Disable geometry to avoid raycasting against it (eg background when only intersecting a foreground object).
void enableGeom (geomId id)
Enable geometry to start raycasting it again.
void deleteGeom (geomId id)
Delete geometry.
void clearGeometry ()
Clears internal scene..
bool isInit ()
Static Public Member Functions
static sibr::Vector3f smoothNormal (const sibr::Mesh &mesh, const RayHit &hit)
Returns the normalized smooth normal (shading normal) from a hit, assuming the mesh has normals.
static sibr::Vector3f smoothColor (const sibr::Mesh &mesh, const RayHit &hit)
Interpolate color at a hit (barycentric interpolation), assuming the mesh has colors.
static sibr::Vector2f smoothUV (const sibr::Mesh &mesh, const RayHit &hit)
Interpolate texcoords from a hit (barycentric interpolation), assuming the mesh has UVs.
Static Public Attributes
static const geomId InvalidGeomId = RTC_INVALID_GEOMETRY_ID
Stores a number representing an invalid geom id.
Private Member Functions
RTCScenePtr scene ()
Static Private Member Functions
static void rtcErrorCallback (void *userPtr, RTCError code, const char *msg)
Will be called by embree whenever an error occurs.
Private Attributes
RTCScenePtr _scene
scene storing raycastable meshes
RTCDevicePtr _devicePtr
embree device (context for a raycaster)
Static Private Attributes
static bool g_initRegisterFlag = false
Used to initialize flag of registers used by SSE.
static RTCDevicePtr g_device = nullptr
embree device (context for a raycaster)
Detailed Description
This class can be used to cast rays against a scene containing triangular meshes.
You can check for intersections with the geometry and get information about the hit (such as coordinates, distance, triangle id).
You should have one or few instance of this class (for performance purposes). Each instance can run in parallel.
Note
This abstraction is built on top of Embree.
Warning
There is no backface culling applied.
Definition at line 29 of file Raycaster.hpp.
Member Typedef Documentation
geomId
typedef uint sibr::Raycaster::geomId
Definition at line 36 of file Raycaster.hpp.
Ptr
typedef std::shared_ptr<Raycaster> sibr::Raycaster::Ptr
Definition at line 34 of file Raycaster.hpp.
RTCDevicePtr
typedef std::shared_ptr<RTCDevice> sibr::Raycaster::RTCDevicePtr
Definition at line 32 of file Raycaster.hpp.
RTCScenePtr
typedef std::shared_ptr<RTCScene> sibr::Raycaster::RTCScenePtr
Definition at line 33 of file Raycaster.hpp.
Constructor & Destructor Documentation
~Raycaster()
sibr::Raycaster::~Raycaster (void)
Destructor.
Definition at line 29 of file Raycaster.cpp.
References _devicePtr, _scene, and g_device.
Member Function Documentation
addDynamicMesh()
Raycaster::geomId sibr::Raycaster::addDynamicMesh (const sibr::Mesh & mesh)
Add a triangle mesh to the raycast scene, that you will frequently update.
Parameters
mesh the mesh to add
Returns
the mesh ID or Raycaster::InvalidGeomId if it fails.
Definition at line 83 of file Raycaster.cpp.
References addGenericMesh().
addGenericMesh()
Raycaster::geomId sibr::Raycaster::addGenericMesh (const sibr::Mesh & mesh, RTCBuildQuality type)
Add a triangle mesh to the raycast scene.
Parameters
mesh the mesh to add
type the type of mesh
Returns
the mesh ID or Raycaster::InvalidGeomId if it fails.
Definition at line 88 of file Raycaster.cpp.
References _scene, g_device, init(), InvalidGeomId, sibr::Mesh::triangles(), and sibr::Mesh::vertices().
Referenced by addDynamicMesh(), and addMesh().
addMesh()
Raycaster::geomId sibr::Raycaster::addMesh (const sibr::Mesh & mesh)
Add a triangle mesh to the raycast scene, taht you won't modify frequently Return the id of the geometry added so you can track your mesh (and compare its id to the one stored in RayHits).
Parameters
mesh the mesh to add
Returns
the mesh ID or Raycaster::InvalidGeomId if it fails.
Definition at line 78 of file Raycaster.cpp.
References addGenericMesh().
Referenced by sibr::CameraRaycaster::addMesh(), sibr::CameraRaycaster::computeClippingPlanes(), legacyV1main(), legacyV2main(), main(), and sibr::MeshTexturing::setMesh().
clearGeometry()
void sibr::Raycaster::clearGeometry ()
Clears internal scene..
Definition at line 333 of file Raycaster.cpp.
References _scene.
deleteGeom()
void sibr::Raycaster::deleteGeom (geomId id) inline
Delete geometry.
Parameters
id the geometry to delete
Definition at line 120 of file Raycaster.hpp.
disableGeom()
void sibr::Raycaster::disableGeom (geomId id) inline
Disable geometry to avoid raycasting against it (eg background when only intersecting a foreground object).
Parameters
id the mesh to disable
Todo:
Untested.
Definition at line 111 of file Raycaster.hpp.
enableGeom()
void sibr::Raycaster::enableGeom (geomId id) inline
Enable geometry to start raycasting it again.
Parameters
id the geometry to enable
Todo:
Untested.
Definition at line 116 of file Raycaster.hpp.
hitSomething()
bool sibr::Raycaster::hitSomething (const Ray & ray, float minDist = 0.f)
Optimized ray-cast that only tells you if an intersection occured.
See also
intersect
Parameters
ray the ray to cast
minDist Any intersection closer than minDist from the ray origin will be ignored. Useful to avoid self intersections.
Returns
true if an intersection took place
Definition at line 179 of file Raycaster.cpp.
References _scene, sibr::Ray::dir(), sibr::RayHit::InfinityDist, init(), sibr::Ray::orig(), and SIBR_ERR.
hitSomething8()
std::array< bool, 8 > sibr::Raycaster::hitSomething8 (const std::array< Ray, 8 > & inray, float minDist = 0.f)
Launch 8 rays into the raycaster scene in an optimized fashion, reporting if intersections occured.
Parameters
inray the rays to cast
minDist Any intersection closer than minDist from the ray origin will be ignored. Useful to avoid self intersections.
Returns
a list of boolean denoting if intersections happened
Definition at line 206 of file Raycaster.cpp.
References _scene, sibr::RayHit::InfinityDist, init(), and SIBR_ERR.
init()
bool sibr::Raycaster::init (RTCSceneFlags sceneType = RTC_SCENE_FLAG_NONE)
Init the raycaster.
Called automatically whenever you call a member that need this instance to be init. However, you can call it manually to check error on init.
Parameters
sceneType the type of scene, see Embree doc.
Returns
a success flag
Definition at line 37 of file Raycaster.cpp.
References _devicePtr, _scene, g_device, rtcErrorCallback(), and SIBR_LOG.
Referenced by addGenericMesh(), sibr::CameraRaycaster::computeClippingPlanes(), hitSomething(), hitSomething8(), sibr::CameraRaycaster::init(), intersect(), intersect8(), legacyV1main(), legacyV2main(), and main().
intersect()
RayHit sibr::Raycaster::intersect (const Ray & ray, float minDist = 0.f)
Launch a ray into the raycaster scene.
Return information about this cast in RayHit. To simply know if something has been hit, use RayHit::hitSomething().
See also
hitSomething
Parameters
ray the ray to cast
minDist Any intersection closer than minDist from the ray origin will be ignored. Useful to avoid self intersections.
Returns
the (potential) intersection information
Definition at line 242 of file Raycaster.cpp.
References _scene, sibr::Ray::dir(), sibr::RayHit::Primitive::geomID, sibr::RayHit::InfinityDist, init(), sibr::RayHit::Primitive::instID, sibr::Ray::orig(), SIBR_ERR, sibr::RayHit::Primitive::triID, sibr::RayHit::BCCoord::u, and sibr::RayHit::BCCoord::v.
Referenced by sibr::CameraRaycaster::castForEachPixel(), sibr::CameraRaycaster::computeClippingPlanes(), sibr::MeshTexturing::hitTest(), sibr::MeshTexturing::reproject(), sibr::Orbit::updateOrbitParameters(), and sibr::Orbit::updateOrbitParametersCentered().
intersect8()
std::array< RayHit, 8 > sibr::Raycaster::intersect8 (const std::array< Ray, 8 > & inray, const std::vector< int > & valid8 = std::vector<int>(8,-1), float minDist = 0.f)
Launch 8 rays into the raycaster scene in an optimized fashion, reporting intersections infos.
Parameters
inray the rays to cast
valid8 an indication of which of the rays should be cast
minDist Any intersection closer than minDist from the ray origin will be ignored. Useful to avoid self intersections.
Returns
the list of (potential) intersection informations
Definition at line 288 of file Raycaster.cpp.
References _scene, sibr::RayHit::Primitive::geomID, sibr::RayHit::InfinityDist, init(), SIBR_ERR, and sibr::RayHit::BCCoord::u.
isInit()
bool sibr::Raycaster::isInit () inline
Returns
true if the raycaster is initialized.
Definition at line 144 of file Raycaster.hpp.
rtcErrorCallback()
void sibr::Raycaster::rtcErrorCallback (void * userPtr, RTCError code, const char * msg) static private
Will be called by embree whenever an error occurs.
Parameters
userPtr the user data pointer
code the error code
msg additional info message.
Definition at line 10 of file Raycaster.cpp.
References SIBR_ERR.
Referenced by init().
scene()
RTCScenePtr sibr::Raycaster::scene () inline private
Returns
the internal scene pointer
Definition at line 159 of file Raycaster.hpp.
smoothColor()
sibr::Vector3f sibr::Raycaster::smoothColor (const sibr::Mesh & mesh, const RayHit & hit) static
Interpolate color at a hit (barycentric interpolation), assuming the mesh has colors.
Parameters
mesh sibr::Mesh used by raycaster
hit intersection basic information
Returns
the interpolated color
Definition at line 354 of file Raycaster.cpp.
References sibr::RayHit::barycentricCoord(), sibr::Mesh::colors(), sibr::Mesh::hasColors(), sibr::RayHit::primitive(), SIBR_ERR, sibr::Mesh::triangles(), sibr::RayHit::Primitive::triID, sibr::RayHit::BCCoord::u, and sibr::RayHit::BCCoord::v.
smoothNormal()
sibr::Vector3f sibr::Raycaster::smoothNormal (const sibr::Mesh & mesh, const RayHit & hit) static
Returns the normalized smooth normal (shading normal) from a hit, assuming the mesh has normals.
Parameters
mesh sibr::Mesh used by raycaster
hit intersection basic information
Returns
the interpolated normalized normal
Definition at line 338 of file Raycaster.cpp.
References sibr::RayHit::barycentricCoord(), sibr::Mesh::hasNormals(), sibr::Mesh::normals(), sibr::RayHit::primitive(), SIBR_ERR, sibr::Mesh::triangles(), sibr::RayHit::Primitive::triID, sibr::RayHit::BCCoord::u, and sibr::RayHit::BCCoord::v.
smoothUV()
sibr::Vector2f sibr::Raycaster::smoothUV (const sibr::Mesh & mesh, const RayHit & hit) static
Interpolate texcoords from a hit (barycentric interpolation), assuming the mesh has UVs.
Parameters
mesh sibr::Mesh used by raycaster
hit intersection basic information \eturn the interpolated texture coordinates
Definition at line 370 of file Raycaster.cpp.
References sibr::RayHit::barycentricCoord(), sibr::Mesh::hasTexCoords(), sibr::RayHit::primitive(), SIBR_ERR, sibr::Mesh::texCoords(), sibr::Mesh::triangles(), sibr::RayHit::Primitive::triID, sibr::RayHit::BCCoord::u, and sibr::RayHit::BCCoord::v.
xformRtcMeshOnly()
void sibr::Raycaster::xformRtcMeshOnly (sibr::Mesh & mesh, geomId mesh_id, sibr::Matrix4f & mat, sibr::Vector3f & centerPt, float & maxlen)
Transform the vertices of a mesh by applying a sibr::Matrix4f mat.
Note
The original positions are always stored unchanged in mesh.vertices – we only xform the vertices in the embree buffer
Parameters
mesh the mesh to transform
mesh_id the corresponding raycaster mesh id
mat the transformation to apply
centerPt will contain the new centroid
maxlen will contain the maximum distance from a vertex to the centroid
Bug:
maxlen is computed incrementally and may be incorrect
Definition at line 143 of file Raycaster.cpp.
References _scene, sibr::Mesh::vertices(), and xyz().
Member Data Documentation
_devicePtr
RTCDevicePtr sibr::Raycaster::_devicePtr private
embree device (context for a raycaster)
Definition at line 162 of file Raycaster.hpp.
Referenced by init(), and ~Raycaster().
_scene
RTCScenePtr sibr::Raycaster::_scene private
scene storing raycastable meshes
Definition at line 161 of file Raycaster.hpp.
Referenced by addGenericMesh(), clearGeometry(), hitSomething(), hitSomething8(), init(), intersect(), intersect8(), xformRtcMeshOnly(), and ~Raycaster().
g_device
Raycaster::RTCDevicePtr sibr::Raycaster::g_device = nullptr static private
embree device (context for a raycaster)
Definition at line 156 of file Raycaster.hpp.
Referenced by addGenericMesh(), init(), and ~Raycaster().
g_initRegisterFlag
bool sibr::Raycaster::g_initRegisterFlag = false static private
Used to initialize flag of registers used by SSE.
Definition at line 155 of file Raycaster.hpp.
InvalidGeomId
SIBR_RAYCASTER_EXPORT const Raycaster::geomId sibr::Raycaster::InvalidGeomId = RTC_INVALID_GEOMETRY_ID static
Stores a number representing an invalid geom id.
Definition at line 38 of file Raycaster.hpp.
Referenced by addGenericMesh().
The documentation for this class was generated from the following files:
src/core/raycaster/Raycaster.hpp
src/core/raycaster/Raycaster.cpp