SIBR: sibr::StereoAnaglyphRdrMode Class Reference
sibr::StereoAnaglyphRdrMode Class Reference
sibr_view
Stereo rendering mode: two slightly shifted views are rendered and composited as anaglyphs.
#include <RenderingMode.hpp>
Public Member Functions
StereoAnaglyphRdrMode (void)
Constructor.
void render (ViewBase &view, const sibr::Camera &eye, const sibr::Viewport &viewport, IRenderTarget *optDest=nullptr)
Perform rendering of a view.
void setFocalDist (float focal)
Set the focal distance.
void setEyeDist (float iod)
Set the distance between the two eyes.
float focalDist ()
float eyeDist ()
void destRT2img (sibr::ImageRGB &current_img)
Get the current rendered image as a CPU image (empty).
virtual const std::unique_ptr< RenderTargetRGB > & lRT ()
virtual const std::unique_ptr< RenderTargetRGB > & rRT ()
Public Member Functions inherited from sibr::IRenderingMode
virtual ~IRenderingMode (void)
Destructor.
void setPrev (const std::unique_ptr< RenderTargetRGB > &p)
Set common previous step RT.
void setPrevLR (const std::unique_ptr< RenderTargetRGB > &pl, const std::unique_ptr< RenderTargetRGB > &pr)
Set left and right previous step RTs.
Private Attributes
sibr::GLShader _stereoShader
Anaglyph shader.
RenderTarget::UPtr _leftRT
RenderTarget::UPtr _rightRT
Each eye RT.
float _focalDist
float _eyeDist
Focal and inter-eyes distances.
Additional Inherited Members
Public Types inherited from sibr::IRenderingMode
typedef RenderTargetRGB RenderTarget
Public Attributes inherited from sibr::IRenderingMode
bool _clear
Should the dst RT be cleared before rendering.
Protected Attributes inherited from sibr::IRenderingMode
std::unique_ptr< RenderTargetRGB > _prevL
std::unique_ptr< RenderTargetRGB > _prevR
prev RT to link renderers across different views in multipass
Detailed Description
Stereo rendering mode: two slightly shifted views are rendered and composited as anaglyphs.
Definition at line 105 of file RenderingMode.hpp.
Constructor & Destructor Documentation
StereoAnaglyphRdrMode()
sibr::StereoAnaglyphRdrMode::StereoAnaglyphRdrMode (void)
Constructor.
Definition at line 101 of file RenderingMode.cpp.
References sibr::IRenderingMode::_clear, _eyeDist, _focalDist, _leftRT, _rightRT, _stereoShader, sibr::GLShader::init(), sibr::Resources::Instance(), and sibr::loadFile().
Member Function Documentation
destRT2img()
void sibr::StereoAnaglyphRdrMode::destRT2img (sibr::ImageRGB & current_img) inline virtual
Get the current rendered image as a CPU image (empty).
Parameters
current_img will contain the content of the RT
Implements sibr::IRenderingMode.
Definition at line 137 of file RenderingMode.hpp.
eyeDist()
float sibr::StereoAnaglyphRdrMode::eyeDist () inline
Returns
the intra-ocular distance
Definition at line 133 of file RenderingMode.hpp.
focalDist()
float sibr::StereoAnaglyphRdrMode::focalDist () inline
Returns
the focal distance
Definition at line 131 of file RenderingMode.hpp.
lRT()
virtual const std::unique_ptr<RenderTargetRGB>& sibr::StereoAnaglyphRdrMode::lRT () inline virtual
Returns
the left eye RT.
Implements sibr::IRenderingMode.
Definition at line 140 of file RenderingMode.hpp.
render()
void sibr::StereoAnaglyphRdrMode::render (ViewBase & view, const sibr::Camera & eye, const sibr::Viewport & viewport, IRenderTarget * optDest = nullptr) virtual
Perform rendering of a view.
Parameters
view the view to render
eye the current camera
viewport the current viewport
optDest an optional destination RT
Implements sibr::IRenderingMode.
Definition at line 114 of file RenderingMode.cpp.
References sibr::IRenderingMode::_clear, _eyeDist, _focalDist, _leftRT, sibr::IRenderingMode::_prevL, sibr::IRenderingMode::_prevR, _rightRT, _stereoShader, sibr::GLShader::begin(), sibr::IRenderTarget::bind(), sibr::Viewport::clear(), sibr::GLShader::end(), sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), sibr::IRenderTarget::h(), sibr::ViewBase::onRenderIBR(), sibr::Camera::position(), sibr::ViewBase::preRender(), sibr::RenderUtility::renderScreenQuad(), sibr::Camera::right(), sibr::Camera::setStereoCam(), sibr::InputCamera::size(), sibr::IRenderTarget::unbind(), and sibr::IRenderTarget::w().
rRT()
virtual const std::unique_ptr<RenderTargetRGB>& sibr::StereoAnaglyphRdrMode::rRT () inline virtual
Returns
the right eye RT.
Implements sibr::IRenderingMode.
Definition at line 142 of file RenderingMode.hpp.
setEyeDist()
void sibr::StereoAnaglyphRdrMode::setEyeDist (float iod) inline
Set the distance between the two eyes.
Parameters
iod intra-ocular distance
Definition at line 128 of file RenderingMode.hpp.
setFocalDist()
void sibr::StereoAnaglyphRdrMode::setFocalDist (float focal) inline
Set the focal distance.
Parameters
focal focal distance
Definition at line 123 of file RenderingMode.hpp.
Member Data Documentation
_eyeDist
float sibr::StereoAnaglyphRdrMode::_eyeDist private
Focal and inter-eyes distances.
Definition at line 147 of file RenderingMode.hpp.
Referenced by render(), and StereoAnaglyphRdrMode().
_focalDist
float sibr::StereoAnaglyphRdrMode::_focalDist private
Definition at line 147 of file RenderingMode.hpp.
Referenced by render(), and StereoAnaglyphRdrMode().
_leftRT
RenderTarget::UPtr sibr::StereoAnaglyphRdrMode::_leftRT private
Definition at line 146 of file RenderingMode.hpp.
Referenced by render(), and StereoAnaglyphRdrMode().
_rightRT
RenderTarget::UPtr sibr::StereoAnaglyphRdrMode::_rightRT private
Each eye RT.
Definition at line 146 of file RenderingMode.hpp.
Referenced by render(), and StereoAnaglyphRdrMode().
_stereoShader
sibr::GLShader sibr::StereoAnaglyphRdrMode::_stereoShader private
Anaglyph shader.
Definition at line 145 of file RenderingMode.hpp.
Referenced by render(), and StereoAnaglyphRdrMode().
The documentation for this class was generated from the following files:
src/core/view/RenderingMode.hpp
src/core/view/RenderingMode.cpp