SIBR: sibr::MultiViewInterface Class Reference
sibr::MultiViewInterface Class Reference
sibr_view
This class provides basic rendering utilities for a list of images + a mesh.
#include <Interface.h>
Public Member Functions
MultiViewInterface ()
void displayLoop (sibr::Window &window, std::function< void(MultiViewInterface *)>=[](MultiViewInterface *){})
Execute the main display loop, with an optional callback.
void addCameras (const std::vector< InputCamera::Ptr > &input_cams)
void addMesh (const sibr::Mesh::Ptr &mesh)
void addMesh (const sibr::Mesh &mesh)
virtual void update (sibr::Window &window, const sibr::Input &input)
virtual void updateImageView (const sibr::Viewport &viewport, const sibr::Input &input)
virtual void render ()
void renderImageView (const sibr::Viewport &viewport)
sibr::ViewBase::Ptr getViewBase (MultiViewInterfaceView::ViewType type=MultiViewInterfaceView::ViewType::IMAGES)
void onGui ()
PixPos pixFromScreenPos (const sibr::Vector2i &pos, const sibr::Vector2f &winSize)
UV01 screenPos (const PixPos &pix)
UV01 screenPosPixelCenter (const PixPos &pix)
sibr::Vector2i screenPosPixels (const PixPos &pix, const sibr::Vector2f &winSize)
sibr::Vector2f screenPosPixelsFloat (const PixPos &pix, const sibr::Vector2f &winSize)
void addHighlightPixel (const PixPos &pix, const sibr::Vector2f &winSize)
void renderHighlightPixels ()
void highlightPixel (const PixPos &pix, const sibr::Viewport &viewport, const sibr::Vector3f &color={ 0, 1, 0 }, const sibr::Vector2f &pixScreenSize={ 5.0f, 5.0f })
virtual void displayImages (const sibr::Viewport &viewport)
virtual void displayMesh (const sibr::Viewport &viewport)
void displayZoom (const sibr::Viewport &viewport)
void displayHighlightedPixels (const sibr::Vector3f &color, float alpha)
virtual void updateMeshView (const sibr::Input &input, sibr::Window &window)
virtual void updateMeshView (const sibr::Input &input, const sibr::Viewport &viewport)
void updateZoomBox (const sibr::Input &input, const sibr::Vector2f &winSize)
void updateCurrentLayer (const sibr::Input &input)
void updateZoomScroll (const sibr::Input &input)
void updateCenter (const sibr::Input &input, const sibr::Vector2f &winSize)
void updateDrag (const sibr::Input &input, const sibr::Vector2f &winSize)
template<typename T_Type , unsigned int T_NumComp>
bool checkNewLayer (const std::vector< sibr::Image< T_Type, T_NumComp > > &images)
template<typename T_Type , unsigned int T_NumComp>
void addImageLayer (const std::vector< sibr::ImagePtr< T_Type, T_NumComp > > &images, const std::string &name="")
template<typename T_Type , unsigned int T_NumComp>
void addImageLayer (const std::vector< sibr::Image< T_Type, T_NumComp > > &images, const std::string &name="")
template<typename T_Type , unsigned int T_NumComp, typename LambdaType >
void addImageLayerWithLambda (const std::vector< sibr::Image< T_Type, T_NumComp > > &images, LambdaType lambda, const std::string &name="")
Public Attributes
sibr::Mesh::Ptr cpuMesh
sibr::Mesh::Ptr reproMesh
sibr::Mesh::RenderMode reproMeshMode
bool reproMeshBackFace
sibr::Mesh::Ptr highlightedPixelsMesh
std::vector< sibr::PixPos > highlightedPixels
bool hightligthChanged
sibr::Vector2f imgPixelScreenSize
SubView imagesView
SubView meshView
sibr::Input imagesInput
sibr::Input meshInput
MultiViewInterfaceView::Ptr imagesViewBase
MultiViewInterfaceView::Ptr meshViewBase
InterfaceUtilities utils
ScalingOptions scalingOptions
std::map< std::string, int > name_to_layer_map
RectangleData viewRectangle
DragData drag
DoubleClick< sibr::Mouse::Left > dclick
SelectionData zoomSelection
sibr::MeshViewer meshViewer
std::vector< InputCamera::Ptr > cams
sibr::PixPos currentActivePos
sibr::Vector2i grid
sibr::Vector2f imSizeF
sibr::Vector2f winSize
float imRatio
int currentScale
int currentLayer
int numImgs
std::vector< std::vector< sibr::ITexture2DArray::Ptr > > imagesLayers
std::vector< std::vector< const sibr::IImage * > > imagesPtr
std::vector< std::vector< sibr::IImage::Ptr > > imagesFromLambdasPtr
std::vector< LayerData > layersData
std::vector< ScaleData > scalesData
Private Member Functions
SIBR_CLASS_PTR (MultiViewInterface)
Detailed Description
This class provides basic rendering utilities for a list of images + a mesh.
Definition at line 83 of file Interface.h.
Constructor & Destructor Documentation
MultiViewInterface()
sibr::MultiViewInterface::MultiViewInterface ()
Definition at line 10 of file Interface.cpp.
References currentLayer, currentScale, sibr::Mesh::FillRenderMode, grid, hightligthChanged, sibr::MultiViewInterfaceView::IMAGES, imagesViewBase, sibr::MultiViewInterfaceView::MESH, meshViewBase, numImgs, reproMeshBackFace, and reproMeshMode.
Member Function Documentation
addCameras()
void sibr::MultiViewInterface::addCameras (const std::vector< InputCamera::Ptr > & input_cams)
Definition at line 78 of file Interface.cpp.
References cams.
addHighlightPixel()
void sibr::MultiViewInterface::addHighlightPixel (const PixPos & pix, const sibr::Vector2f & winSize)
Definition at line 274 of file Interface.cpp.
References highlightedPixels.
addImageLayer() [1/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::MultiViewInterface::addImageLayer (const std::vector< sibr::Image< T_Type, T_NumComp > > & images, const std::string & name = "") inline
Definition at line 235 of file Interface.h.
References sibr::Texture2DArray< T_Type, T_NumComp >::createFromImages(), sibr::ScalingOptions::interpolation_method_cv, and sibr::ScalingOptions::numScale.
addImageLayer() [2/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::MultiViewInterface::addImageLayer (const std::vector< sibr::ImagePtr< T_Type, T_NumComp > > & images, const std::string & name = "") inline
Definition at line 226 of file Interface.h.
addImageLayerWithLambda()
template<typename T_Type , unsigned int T_NumComp, typename LambdaType > void sibr::MultiViewInterface::addImageLayerWithLambda (const std::vector< sibr::Image< T_Type, T_NumComp > > & images, LambdaType lambda, const std::string & name = "") inline
Definition at line 272 of file Interface.h.
References sibr::Texture2DArray< T_Type, T_NumComp >::createFromImages(), sibr::ScalingOptions::interpolation_method_cv, and sibr::ScalingOptions::numScale.
addMesh() [1/2]
void sibr::MultiViewInterface::addMesh (const sibr::Mesh & mesh)
Definition at line 89 of file Interface.cpp.
References cpuMesh, sibr::Mesh::triangles(), and sibr::Mesh::vertices().
addMesh() [2/2]
void sibr::MultiViewInterface::addMesh (const sibr::Mesh::Ptr & mesh)
Definition at line 83 of file Interface.cpp.
References cpuMesh.
checkNewLayer()
template<typename T_Type , unsigned int T_NumComp> bool sibr::MultiViewInterface::checkNewLayer (const std::vector< sibr::Image< T_Type, T_NumComp > > & images) inline
Definition at line 197 of file Interface.h.
References sibr::ScalingOptions::numScale, and SIBR_ERR.
displayHighlightedPixels()
void sibr::MultiViewInterface::displayHighlightedPixels (const sibr::Vector3f & color, float alpha)
Definition at line 438 of file Interface.cpp.
References sibr::InterfaceUtilities::alphaGL, sibr::InterfaceUtilities::baseShader, sibr::GLShader::begin(), sibr::InterfaceUtilities::colorGL, sibr::GLShader::end(), highlightedPixelsMesh, sibr::Mesh::LineRenderMode, sibr::InterfaceUtilities::scalingGL, sibr::GLParameter::set(), sibr::InterfaceUtilities::translationGL, and utils.
displayImages()
void sibr::MultiViewInterface::displayImages (const sibr::Viewport & viewport) virtual
Definition at line 338 of file Interface.cpp.
References sibr::InterfaceUtilities::alphaMeshGL, sibr::GLShader::begin(), sibr::Viewport::bind(), sibr::RectangleData::br(), cams, sibr::Viewport::clear(), sibr::InterfaceUtilities::colorMeshGL, currentLayer, currentScale, sibr::GLShader::end(), sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), grid, sibr::InterfaceUtilities::gridGL, imagesLayers, imagesView, sibr::InterfaceUtilities::meshViewShader, sibr::InterfaceUtilities::multiViewBottomRightGL, sibr::InterfaceUtilities::multiViewShader, sibr::InterfaceUtilities::multiViewTopLeftGL, sibr::InterfaceUtilities::mvp, sibr::InterfaceUtilities::numImgsGL, sibr::InterfaceUtilities::rectangle(), sibr::RenderUtility::renderScreenQuad(), reproMesh, reproMeshBackFace, reproMeshMode, scalesData, screenPos(), screenPosPixels(), sibr::GLParameter::set(), sibr::RectangleData::tl(), utils, sibr::SubView::viewport, and viewRectangle.
Referenced by renderImageView().
displayLoop()
void sibr::MultiViewInterface::displayLoop (sibr::Window & window, std::function< void(MultiViewInterface *)> f = [](MultiViewInterface*){})
Execute the main display loop, with an optional callback.
Parameters
window the sibr::Window displayed into
f an optional callback called at the end of each frame.
Definition at line 24 of file Interface.cpp.
References cpuMesh, sibr::Key::Escape, sibr::Mesh::FillRenderMode, sibr::Input::global(), imagesInput, imagesView, sibr::InterfaceUtilities::initAllShaders(), sibr::SubView::isActive, sibr::Window::isOpened(), layersData, sibr::Window::makeContextCurrent(), meshInput, meshView, meshViewer, onGui(), sibr::Input::poll(), render(), scalesData, sibr::MeshViewer::setMainMesh(), SIBR_ERR, sibr::Window::size(), sibr::Input::subInput(), sibr::Window::swapBuffer(), update(), utils, sibr::Window::viewport(), sibr::SubView::viewport, and winSize.
displayMesh()
void sibr::MultiViewInterface::displayMesh (const sibr::Viewport & viewport) virtual
Definition at line 421 of file Interface.cpp.
References sibr::SubView::isActive, meshView, meshViewer, and sibr::MeshViewer::render().
Referenced by sibr::MultiViewInterfaceView::onRender(), and render().
displayZoom()
void sibr::MultiViewInterface::displayZoom (const sibr::Viewport & viewport)
Definition at line 428 of file Interface.cpp.
References sibr::Viewport::bind(), sibr::Viewport::finalSize(), sibr::SelectionData::first, sibr::UV< space >::from(), sibr::SelectionData::isActive, sibr::InterfaceUtilities::rectangle(), sibr::SelectionData::second, utils, and zoomSelection.
Referenced by renderImageView().
getViewBase()
sibr::ViewBase::Ptr sibr::MultiViewInterface::getViewBase (MultiViewInterfaceView::ViewType type = MultiViewInterfaceView::ViewType::IMAGES)
Definition at line 157 of file Interface.cpp.
References sibr::MultiViewInterfaceView::IMAGES, imagesViewBase, and meshViewBase.
highlightPixel()
void sibr::MultiViewInterface::highlightPixel (const PixPos & pix, const sibr::Viewport & viewport, const sibr::Vector3f & color = { 0, 1, 0 }, const sibr::Vector2f & pixScreenSize = { 5.0f,5.0f })
Definition at line 320 of file Interface.cpp.
References sibr::Viewport::bind(), sibr::Viewport::finalSize(), sibr::PixPos::im, sibr::PixPos::pos, sibr::InterfaceUtilities::rectangle(), sibr::InterfaceUtilities::rectanglePixels(), screenPos(), and utils.
Referenced by renderImageView().
onGui()
void sibr::MultiViewInterface::onGui ()
Definition at line 167 of file Interface.cpp.
References currentActivePos, currentLayer, currentScale, sibr::PixPos::im, imagesLayers, sibr::PixPos::isDefined, layersData, and sibr::PixPos::pos.
Referenced by displayLoop(), and sibr::MultiViewInterfaceView::onRender().
pixFromScreenPos()
PixPos sibr::MultiViewInterface::pixFromScreenPos (const sibr::Vector2i & pos, const sibr::Vector2f & winSize)
Definition at line 209 of file Interface.cpp.
References sibr::RectangleData::br(), currentScale, sibr::frac(), sibr::UV< space >::from(), grid, numImgs, scalesData, sibr::RectangleData::tl(), viewRectangle, and winSize.
Referenced by updateImageView().
render()
void sibr::MultiViewInterface::render () virtual
Definition at line 123 of file Interface.cpp.
References displayMesh(), imagesView, meshView, renderImageView(), and sibr::SubView::viewport.
Referenced by displayLoop().
renderHighlightPixels()
void sibr::MultiViewInterface::renderHighlightPixels ()
Definition at line 280 of file Interface.cpp.
References highlightedPixels, highlightedPixelsMesh, and screenPos().
renderImageView()
void sibr::MultiViewInterface::renderImageView (const sibr::Viewport & viewport)
Definition at line 144 of file Interface.cpp.
References currentActivePos, displayImages(), displayZoom(), sibr::Viewport::finalSize(), highlightPixel(), and sibr::PixPos::isDefined.
Referenced by sibr::MultiViewInterfaceView::onRender(), and render().
screenPos()
UV01 sibr::MultiViewInterface::screenPos (const PixPos & pix)
Definition at line 241 of file Interface.cpp.
References sibr::RectangleData::br(), currentScale, sibr::UV< space >::from(), grid, sibr::PixPos::im, sibr::PixPos::pos, scalesData, sibr::RectangleData::tl(), and viewRectangle.
Referenced by displayImages(), highlightPixel(), renderHighlightPixels(), and screenPosPixels().
screenPosPixelCenter()
UV01 sibr::MultiViewInterface::screenPosPixelCenter (const PixPos & pix)
Definition at line 249 of file Interface.cpp.
References sibr::RectangleData::br(), currentScale, sibr::UV< space >::from(), grid, sibr::PixPos::im, sibr::PixPos::pos, scalesData, sibr::RectangleData::tl(), and viewRectangle.
Referenced by screenPosPixelsFloat().
screenPosPixels()
sibr::Vector2i sibr::MultiViewInterface::screenPosPixels (const PixPos & pix, const sibr::Vector2f & winSize)
Definition at line 257 of file Interface.cpp.
References screenPos(), and winSize.
Referenced by displayImages().
screenPosPixelsFloat()
sibr::Vector2f sibr::MultiViewInterface::screenPosPixelsFloat (const PixPos & pix, const sibr::Vector2f & winSize)
Definition at line 262 of file Interface.cpp.
References screenPosPixelCenter(), and winSize.
Referenced by updateImageView().
SIBR_CLASS_PTR()
sibr::MultiViewInterface::SIBR_CLASS_PTR (MultiViewInterface) private
update()
void sibr::MultiViewInterface::update (sibr::Window & window, const sibr::Input & input) virtual
Definition at line 97 of file Interface.cpp.
References imagesInput, imagesView, meshInput, updateImageView(), updateMeshView(), and sibr::SubView::viewport.
Referenced by displayLoop().
updateCenter()
void sibr::MultiViewInterface::updateCenter (const sibr::Input & input, const sibr::Vector2f & winSize)
Definition at line 583 of file Interface.cpp.
References sibr::RectangleData::br(), sibr::RectangleData::center, dclick, sibr::DoubleClick< mKey >::detected(), sibr::DoubleClick< mKey >::firstPosition, sibr::RectangleData::tl(), viewRectangle, and winSize.
updateCurrentLayer()
void sibr::MultiViewInterface::updateCurrentLayer (const sibr::Input & input)
Definition at line 549 of file Interface.cpp.
References currentLayer, imagesLayers, sibr::InputState< TNbState, TEnum >::isPressed(), sibr::Input::key(), sibr::Key::Num1, sibr::Key::Num2, sibr::Key::Num3, sibr::Key::Num4, sibr::Key::Num5, sibr::Key::Num6, sibr::Key::Num7, sibr::Key::Num8, and sibr::Key::Num9.
Referenced by updateImageView().
updateDrag()
void sibr::MultiViewInterface::updateDrag (const sibr::Input & input, const sibr::Vector2f & winSize)
Definition at line 593 of file Interface.cpp.
References sibr::RectangleData::br(), sibr::RectangleData::center, sibr::DragData::center, drag, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::DragData::isActive, sibr::InputState< TNbState, TEnum >::isPressed(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Mouse::Left, sibr::Input::mouseButton(), sibr::Input::mousePosition(), sibr::DragData::position, sibr::RectangleData::tl(), viewRectangle, and winSize.
Referenced by updateImageView().
updateImageView()
void sibr::MultiViewInterface::updateImageView (const sibr::Viewport & viewport, const sibr::Input & input) virtual
Definition at line 103 of file Interface.cpp.
References currentActivePos, sibr::Viewport::finalSize(), imagesViewBase, imgPixelScreenSize, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Input::key(), sibr::Key::LeftShift, sibr::Input::mousePosition(), pixFromScreenPos(), screenPosPixelsFloat(), updateCurrentLayer(), updateDrag(), updateZoomBox(), updateZoomScroll(), and winSize.
Referenced by sibr::MultiViewInterfaceView::onUpdate(), and update().
updateMeshView() [1/2]
void sibr::MultiViewInterface::updateMeshView (const sibr::Input & input, const sibr::Viewport & viewport) virtual
Definition at line 492 of file Interface.cpp.
References cpuMesh, sibr::Mesh::FillRenderMode, sibr::MeshViewer::interactCam, sibr::SubView::isActive, meshView, meshViewer, and sibr::MeshViewer::setMainMesh().
updateMeshView() [2/2]
void sibr::MultiViewInterface::updateMeshView (const sibr::Input & input, sibr::Window & window) virtual
Definition at line 465 of file Interface.cpp.
References cpuMesh, sibr::Input::global(), imagesView, sibr::MeshViewer::interactCam, sibr::SubView::isActive, sibr::Key::Left, meshView, meshViewer, sibr::Key::Right, sibr::Window::size(), sibr::Window::viewport(), and sibr::SubView::viewport.
Referenced by sibr::MultiViewInterfaceView::onUpdate(), and update().
updateZoomBox()
void sibr::MultiViewInterface::updateZoomBox (const sibr::Input & input, const sibr::Vector2f & winSize)
Definition at line 504 of file Interface.cpp.
References sibr::RectangleData::br(), sibr::RectangleData::center, currentScale, sibr::RectangleData::diagonal, sibr::SelectionData::first, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::SelectionData::isActive, sibr::InputState< TNbState, TEnum >::isPressed(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Input::key(), sibr::Input::mouseButton(), sibr::Input::mousePosition(), sibr::Key::Q, sibr::Key::Right, scalesData, sibr::SelectionData::second, sibr::RectangleData::tl(), viewRectangle, winSize, and zoomSelection.
Referenced by updateImageView().
updateZoomScroll()
void sibr::MultiViewInterface::updateZoomScroll (const sibr::Input & input)
Definition at line 570 of file Interface.cpp.
References sibr::RectangleData::diagonal, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Input::key(), sibr::Key::LeftControl, sibr::Input::mouseScroll(), and viewRectangle.
Referenced by updateImageView().
Member Data Documentation
cams
std::vector<InputCamera::Ptr> sibr::MultiViewInterface::cams
Definition at line 151 of file Interface.h.
Referenced by addCameras(), and displayImages().
cpuMesh
sibr::Mesh::Ptr sibr::MultiViewInterface::cpuMesh
Definition at line 116 of file Interface.h.
Referenced by addMesh(), displayLoop(), and updateMeshView().
currentActivePos
sibr::PixPos sibr::MultiViewInterface::currentActivePos
Definition at line 153 of file Interface.h.
Referenced by onGui(), renderImageView(), and updateImageView().
currentLayer
int sibr::MultiViewInterface::currentLayer
Definition at line 161 of file Interface.h.
Referenced by displayImages(), MultiViewInterface(), onGui(), and updateCurrentLayer().
currentScale
int sibr::MultiViewInterface::currentScale
Definition at line 160 of file Interface.h.
Referenced by displayImages(), MultiViewInterface(), onGui(), pixFromScreenPos(), screenPos(), screenPosPixelCenter(), and updateZoomBox().
dclick
DoubleClick<sibr::Mouse::Left> sibr::MultiViewInterface::dclick
Definition at line 147 of file Interface.h.
Referenced by updateCenter().
drag
DragData sibr::MultiViewInterface::drag
Definition at line 146 of file Interface.h.
Referenced by updateDrag().
grid
sibr::Vector2i sibr::MultiViewInterface::grid
Definition at line 155 of file Interface.h.
Referenced by displayImages(), MultiViewInterface(), pixFromScreenPos(), screenPos(), and screenPosPixelCenter().
highlightedPixels
std::vector<sibr::PixPos> sibr::MultiViewInterface::highlightedPixels
Definition at line 122 of file Interface.h.
Referenced by addHighlightPixel(), and renderHighlightPixels().
highlightedPixelsMesh
sibr::Mesh::Ptr sibr::MultiViewInterface::highlightedPixelsMesh
Definition at line 121 of file Interface.h.
Referenced by displayHighlightedPixels(), and renderHighlightPixels().
hightligthChanged
bool sibr::MultiViewInterface::hightligthChanged
Definition at line 123 of file Interface.h.
Referenced by MultiViewInterface().
imagesFromLambdasPtr
std::vector<std::vector<sibr::IImage::Ptr> > sibr::MultiViewInterface::imagesFromLambdasPtr
Definition at line 165 of file Interface.h.
imagesInput
sibr::Input sibr::MultiViewInterface::imagesInput
Definition at line 130 of file Interface.h.
Referenced by displayLoop(), and update().
imagesLayers
std::vector<std::vector<sibr::ITexture2DArray::Ptr> > sibr::MultiViewInterface::imagesLayers
Definition at line 163 of file Interface.h.
Referenced by displayImages(), onGui(), and updateCurrentLayer().
imagesPtr
std::vector<std::vector<const sibr::IImage*> > sibr::MultiViewInterface::imagesPtr
Definition at line 164 of file Interface.h.
imagesView
SubView sibr::MultiViewInterface::imagesView
Definition at line 127 of file Interface.h.
Referenced by displayImages(), displayLoop(), render(), update(), and updateMeshView().
imagesViewBase
MultiViewInterfaceView::Ptr sibr::MultiViewInterface::imagesViewBase
Definition at line 137 of file Interface.h.
Referenced by getViewBase(), MultiViewInterface(), and updateImageView().
imgPixelScreenSize
sibr::Vector2f sibr::MultiViewInterface::imgPixelScreenSize
Definition at line 125 of file Interface.h.
Referenced by updateImageView().
imRatio
float sibr::MultiViewInterface::imRatio
Definition at line 158 of file Interface.h.
imSizeF
sibr::Vector2f sibr::MultiViewInterface::imSizeF
Definition at line 156 of file Interface.h.
layersData
std::vector<LayerData> sibr::MultiViewInterface::layersData
Definition at line 166 of file Interface.h.
Referenced by displayLoop(), and onGui().
meshInput
sibr::Input sibr::MultiViewInterface::meshInput
Definition at line 131 of file Interface.h.
Referenced by displayLoop(), and update().
meshView
SubView sibr::MultiViewInterface::meshView
Definition at line 128 of file Interface.h.
Referenced by displayLoop(), displayMesh(), render(), and updateMeshView().
meshViewBase
MultiViewInterfaceView::Ptr sibr::MultiViewInterface::meshViewBase
Definition at line 138 of file Interface.h.
Referenced by getViewBase(), and MultiViewInterface().
meshViewer
sibr::MeshViewer sibr::MultiViewInterface::meshViewer
Definition at line 149 of file Interface.h.
Referenced by displayLoop(), displayMesh(), and updateMeshView().
name_to_layer_map
std::map<std::string, int> sibr::MultiViewInterface::name_to_layer_map
Definition at line 143 of file Interface.h.
numImgs
int sibr::MultiViewInterface::numImgs
Definition at line 162 of file Interface.h.
Referenced by MultiViewInterface(), and pixFromScreenPos().
reproMesh
sibr::Mesh::Ptr sibr::MultiViewInterface::reproMesh
Definition at line 117 of file Interface.h.
Referenced by displayImages().
reproMeshBackFace
bool sibr::MultiViewInterface::reproMeshBackFace
Definition at line 119 of file Interface.h.
Referenced by displayImages(), and MultiViewInterface().
reproMeshMode
sibr::Mesh::RenderMode sibr::MultiViewInterface::reproMeshMode
Definition at line 118 of file Interface.h.
Referenced by displayImages(), and MultiViewInterface().
scalesData
std::vector<ScaleData> sibr::MultiViewInterface::scalesData
Definition at line 167 of file Interface.h.
Referenced by displayImages(), displayLoop(), pixFromScreenPos(), screenPos(), screenPosPixelCenter(), and updateZoomBox().
scalingOptions
ScalingOptions sibr::MultiViewInterface::scalingOptions
Definition at line 142 of file Interface.h.
utils
InterfaceUtilities sibr::MultiViewInterface::utils
Definition at line 140 of file Interface.h.
Referenced by displayHighlightedPixels(), displayImages(), displayLoop(), displayZoom(), and highlightPixel().
viewRectangle
RectangleData sibr::MultiViewInterface::viewRectangle
Definition at line 145 of file Interface.h.
Referenced by displayImages(), pixFromScreenPos(), screenPos(), screenPosPixelCenter(), updateCenter(), updateDrag(), updateZoomBox(), and updateZoomScroll().
winSize
sibr::Vector2f sibr::MultiViewInterface::winSize
Definition at line 157 of file Interface.h.
Referenced by displayLoop(), pixFromScreenPos(), screenPosPixels(), screenPosPixelsFloat(), updateCenter(), updateDrag(), updateImageView(), and updateZoomBox().
zoomSelection
SelectionData sibr::MultiViewInterface::zoomSelection
Definition at line 148 of file Interface.h.
Referenced by displayZoom(), and updateZoomBox().
The documentation for this class was generated from the following files:
src/core/view/interface/Interface.h
src/core/view/interface/Interface.cpp