SIBR: sibr::RenderMaskHolder Class Reference
sibr::RenderMaskHolder Class Reference
sibr_renderer
Store a set of masks associated to a set of images (dataset input images for instance), on the GPU.
#include <RenderMaskHolder.hpp>
Public Member Functions
void setMasks (const std::vector< MaskPtr > &masks)
Update the masks.
const std::vector< MaskPtr > & getMasks (void) const
bool useMasks (void) const
void loadMasks (const sibr::BasicIBRScene::Ptr &ibrScene, const std::string &maskDir, const std::string &preFileName, const std::string &postFileName, int w, int h)
Load masks from black and white images on disk.
void uploadMaskGPU (sibr::ImageL8 &img, int i, std::vector< RenderTargetLum::Ptr > &masks, bool invert)
Upload a mask image to the GPU.
Private Types
typedef RenderTargetLum::Ptr MaskPtr
Private Attributes
std::vector< MaskPtr > _masks
List of masks on the GPU.
Detailed Description
Store a set of masks associated to a set of images (dataset input images for instance), on the GPU.
This version uses a list of R8 rendertargets.
Note
Might want to use textures instead of RTs here.
Definition at line 17 of file RenderMaskHolder.hpp.
Member Typedef Documentation
MaskPtr
typedef RenderTargetLum::Ptr sibr::RenderMaskHolder::MaskPtr private
Definition at line 19 of file RenderMaskHolder.hpp.
Member Function Documentation
getMasks()
const std::vector< RenderMaskHolder::MaskPtr > & sibr::RenderMaskHolder::getMasks (void) const
Returns
the masks rendertargets.
Definition at line 10 of file RenderMaskHolder.cpp.
References _masks.
Referenced by sibr::ULRV2Renderer::process(), and sibr::ULRRenderer::process().
loadMasks()
void sibr::RenderMaskHolder::loadMasks (const sibr::BasicIBRScene::Ptr & ibrScene, const std::string & maskDir, const std::string & preFileName, const std::string & postFileName, int w, int h)
Load masks from black and white images on disk.
Parameters
ibrScene the dataset scene associated to the masks
maskDir the masks directory
preFileName mask filename prefix
postFileName mask filename suffix and extension
w target width
h target height
Definition at line 55 of file RenderMaskHolder.cpp.
References _masks, sibr::Image< T_Type, T_NumComp >::fromOpenCV(), sibr::imageIdToString(), sibr::Image< T_Type, T_NumComp >::load(), SIBR_ERR, sibr::split(), sibr::Image< T_Type, T_NumComp >::toOpenCV(), and uploadMaskGPU().
setMasks()
void sibr::RenderMaskHolder::setMasks (const std::vector< MaskPtr > & masks)
Update the masks.
Parameters
masks the new masks to use
Definition at line 5 of file RenderMaskHolder.cpp.
References _masks.
uploadMaskGPU()
void sibr::RenderMaskHolder::uploadMaskGPU (sibr::ImageL8 & img, int i, std::vector< RenderTargetLum::Ptr > & masks, bool invert)
Upload a mask image to the GPU.
Parameters
img the mask image to upload
i the mask index in the list
masks the uploaded masks list (will be updated)
invert should the mask be inverted
Definition at line 20 of file RenderMaskHolder.cpp.
References sibr::GLShader::begin(), sibr::RenderTarget< T_Type, T_NumComp >::bind(), sibr::RenderTarget< T_Type, T_NumComp >::clear(), sibr::GLShader::end(), sibr::Image< T_Type, T_NumComp >::flipH(), sibr::getShadersDirectory(), sibr::Image< T_Type, T_NumComp >::h(), sibr::Texture2D< T_Type, T_NumComp >::handle(), sibr::GLShader::init(), sibr::Resources::Instance(), sibr::loadFile(), sibr::RenderUtility::renderScreenQuad(), sibr::RenderTarget< T_Type, T_NumComp >::unbind(), and sibr::Image< T_Type, T_NumComp >::w().
Referenced by loadMasks().
useMasks()
bool sibr::RenderMaskHolder::useMasks (void) const
Returns
true if masks are available (non empty list).
Definition at line 15 of file RenderMaskHolder.cpp.
References _masks.
Referenced by sibr::ULRV2Renderer::process(), and sibr::ULRRenderer::process().
Member Data Documentation
_masks
std::vector<MaskPtr> sibr::RenderMaskHolder::_masks private
List of masks on the GPU.
Definition at line 56 of file RenderMaskHolder.hpp.
Referenced by getMasks(), loadMasks(), setMasks(), and useMasks().
The documentation for this class was generated from the following files:
src/core/renderer/RenderMaskHolder.hpp
src/core/renderer/RenderMaskHolder.cpp