SIBR: sibr::AddShadowRenderer Class Reference
sibr::AddShadowRenderer Class Reference
sibr_renderer
Composite two rendered scenes while generating local cast shadows from the top one to the bottom one.
#include <AddShadowRenderer.hpp>
Public Types
typedef std::shared_ptr< AddShadowRenderer > Ptr
Public Member Functions
AddShadowRenderer (void)
Constructor.
void process (uint backgroundTextureID, uint foregroundTextureID, const Vector2f &textureSize, const Camera &camera, IRenderTarget &dst)
Composite the two textures, they sjould contain color+depth information in the alpha channel.
Private Attributes
GLShader _shader
Composite shader.
GLParameter _paramInvProj
Inverse proj matrix uniform.
GLParameter _paramImgSize
Image size uniform.
Detailed Description
Composite two rendered scenes while generating local cast shadows from the top one to the bottom one.
Definition at line 14 of file AddShadowRenderer.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<AddShadowRenderer> sibr::AddShadowRenderer::Ptr
Definition at line 17 of file AddShadowRenderer.hpp.
Constructor & Destructor Documentation
AddShadowRenderer()
sibr::AddShadowRenderer::AddShadowRenderer (void)
Constructor.
Definition at line 5 of file AddShadowRenderer.cpp.
References _paramImgSize, _paramInvProj, _shader, sibr::getShadersDirectory(), sibr::GLParameter::init(), sibr::GLShader::init(), and sibr::loadFile().
Member Function Documentation
process()
void sibr::AddShadowRenderer::process (uint backgroundTextureID, uint foregroundTextureID, const Vector2f & textureSize, const Camera & camera, IRenderTarget & dst)
Composite the two textures, they sjould contain color+depth information in the alpha channel.
Parameters
backgroundTextureID handle of the background image
foregroundTextureID handle of the foreground image
textureSize the texture size (should be the same)
camera the viewpoint used
dst the destination rendertarget
Definition at line 14 of file AddShadowRenderer.cpp.
References _paramImgSize, _paramInvProj, _shader, sibr::GLShader::begin(), ibr_preprocess_rc_to_sibr::dst, sibr::GLShader::end(), sibr::Camera::invViewproj(), sibr::RenderUtility::renderScreenQuad(), and sibr::GLParameter::set().
Member Data Documentation
_paramImgSize
GLParameter sibr::AddShadowRenderer::_paramImgSize private
Image size uniform.
Definition at line 42 of file AddShadowRenderer.hpp.
Referenced by AddShadowRenderer(), and process().
_paramInvProj
GLParameter sibr::AddShadowRenderer::_paramInvProj private
Inverse proj matrix uniform.
Definition at line 41 of file AddShadowRenderer.hpp.
Referenced by AddShadowRenderer(), and process().
_shader
GLShader sibr::AddShadowRenderer::_shader private
Composite shader.
Definition at line 40 of file AddShadowRenderer.hpp.
Referenced by AddShadowRenderer(), and process().
The documentation for this class was generated from the following files:
src/core/renderer/AddShadowRenderer.hpp
src/core/renderer/AddShadowRenderer.cpp