SIBR: sibr::Arg< Switch > Class Reference
sibr::Arg< Switch > Class Reference
sibr_system
Specialization of Arg for Switch, default value get flipped if arg is present.
#include <CommandLineArgs.hpp>
Public Member Functions
Arg (const std::string &key, const bool &default_value, const std::string &description="")
Constructor.
Public Member Functions inherited from sibr::ArgBase< bool >
operator const bool & () const
const bool & get () const
bool & operator= (const bool &t)
Copy operator.
Additional Inherited Members
Protected Attributes inherited from sibr::ArgBase< bool >
bool value
the argument value.
Detailed Description
Specialization of Arg for Switch, default value get flipped if arg is present.
Definition at line 211 of file CommandLineArgs.hpp.
Constructor & Destructor Documentation
Arg()
sibr::Arg< Switch >::Arg (const std::string & key, const bool & default_value, const std::string & description = "") inline
Constructor.
Parameters
key the command argument
default_value the default boolean value
description help message description
Definition at line 218 of file CommandLineArgs.hpp.
References sibr::CommandLineArgs::get(), sibr::CommandLineArgs::getGlobal(), sibr::CommandLineArgs::registerCommand(), and sibr::ArgBase< T >::value.
The documentation for this class was generated from the following file:
src/core/system/CommandLineArgs.hpp