SIBR: sibr::ImageListFile Class Reference
sibr::ImageListFile Class Reference
sibr_assets
Represents a list of input images.
#include <ImageListFile.hpp>
Classes
struct Infos
Image infos.
Public Member Functions
bool load (const std::string &filename, bool verbose=true)
Load the list file from disk.
const std::vector< Infos > & infos (void) const
Images information.
const std::string & basename (void) const
Image absename.
template<class TImage >
std::vector< TImage > loadImages (void) const
Load images.
template<class TImage >
std::vector< TImage > loadImages (const ActiveImageFile &ac) const
Load images, applying an active images file filter.
Public Member Functions inherited from sibr::IFileLoader
virtual ~IFileLoader (void)
Destructor.
Private Attributes
std::vector< Infos > _infos
Image infos.
std::string _basename
Root name.
Detailed Description
Represents a list of input images.
Definition at line 14 of file ImageListFile.hpp.
Member Function Documentation
basename()
const std::string& sibr::ImageListFile::basename (void) const inline
Image absename.
Returns
the basename
Definition at line 44 of file ImageListFile.hpp.
infos()
const std::vector<Infos>& sibr::ImageListFile::infos (void) const inline
Images information.
Returns
each image infos.
Definition at line 39 of file ImageListFile.hpp.
load()
bool sibr::ImageListFile::load (const std::string & filename, bool verbose = true) virtual
Load the list file from disk.
Parameters
filename path to the list file
verbose display information
Returns
a boolean denoting success
Implements sibr::IFileLoader.
Definition at line 8 of file ImageListFile.cpp.
References _basename, _infos, sibr::ImageListFile::Infos::filename, sibr::ImageListFile::Infos::height, SIBR_FLOG, SIBR_WRG, and sibr::ImageListFile::Infos::width.
Referenced by loadImages(), and main().
loadImages() [1/2]
template<class TImage > std::vector< TImage > sibr::ImageListFile::loadImages (const ActiveImageFile & ac) const
Load images, applying an active images file filter.
Parameters
ac the active list file
Returns
the loaded images
Note
Non-active images are present but empty.
Definition at line 71 of file ImageListFile.hpp.
References _basename, _infos, sibr::ActiveImageFile::active(), SIBR_LOG, and SIBR_WRG.
loadImages() [2/2]
template<class TImage > std::vector< TImage > sibr::ImageListFile::loadImages (void) const
Load images.
Returns
the loaded images
Definition at line 91 of file ImageListFile.hpp.
References _basename, _infos, load(), and SIBR_WRG.
Member Data Documentation
_basename
std::string sibr::ImageListFile::_basename private
Root name.
Definition at line 63 of file ImageListFile.hpp.
Referenced by load(), and loadImages().
_infos
std::vector<Infos> sibr::ImageListFile::_infos private
Image infos.
Definition at line 62 of file ImageListFile.hpp.
Referenced by load(), and loadImages().
The documentation for this class was generated from the following files:
src/core/assets/ImageListFile.hpp
src/core/assets/ImageListFile.cpp