SIBR: sibr::BasicIBRScene Class Reference
sibr::BasicIBRScene Class Reference
sibr_scene
Class used to define a basic IBR Scene containing multiple components required to define a scene.
#include <BasicIBRScene.hpp>
Public Member Functions
SIBR_CLASS_PTR (BasicIBRScene)
Pointer to the instance of class sibr::BasicIBRScene.
BasicIBRScene ()
Default constructor to create a BasicIBRScene.
BasicIBRScene (const BasicIBRAppArgs &myArgs, bool noRTs, bool noMesh=false)
Constructor to create a BasicIBRScene given command line arguments.
BasicIBRScene (const BasicIBRAppArgs &myArgs, SceneOptions myOpts=SceneOptions())
Constructor to create a BasicIBRScene given command line arguments.
~BasicIBRScene ()
Destructor.
void createFromCustomData (const IParseData::Ptr &data, const uint width=0, SceneOptions myOpts=SceneOptions()) override
Creates a BasicIBRScene given custom data argument.
void createFromDatasetPath ()
Function to create a scene directly using the dataset path specified in command-line.
void createRenderTargets () override
Function to generate render targets using the _data (regarding cameras, images, proxies) parsed from metadata file.
const IParseData::Ptr data (void) const override
Getter for the pointer holding the data related to the scene.
void data (const sibr::IParseData::Ptr &data) override
Setter for the pointer holding the data related to the scene for scene creation.
const ICalibratedCameras::Ptr cameras (void) const override
Getter for the pointer holding cameras related to each input iamge of the scene.
const IInputImages::Ptr images (void) const override
Getter for the pointer holding the input images to the scene.
const IProxyMesh::Ptr proxies (void) const override
Getter for the pointer holding the proxies required by the scene.
const RenderTargetTextures::Ptr & renderTargets (void) const override
Getter for the pointer holding the render targets textures related to the scene.
RenderTargetTextures::Ptr & renderTargets (void) override
Getter for the pointer holding the render targets textures related to the scene.
Texture2DRGB::Ptr & inputMeshTextures (void) override
Getter for the pointer holding the mesh textures related to the mesh loaded for the scene.
Public Member Functions inherited from sibr::IIBRScene
virtual void createFromCustomData (const IParseData::Ptr &data, const uint width=0, SceneOptions myOpts=SceneOptions())=0
Creates a BasicIBRScene given custom data argument.
Protected Member Functions
BasicIBRScene (BasicIBRScene &scene)
BasicIBRScene & operator= (const BasicIBRScene &)=delete
void createFromData (const uint width=0)
Creates a BasicIBRScene from the internal stored data component in the scene.
Protected Attributes
IParseData::Ptr _data
ICalibratedCameras::Ptr _cams
IInputImages::Ptr _imgs
IProxyMesh::Ptr _proxies
Texture2DRGB::Ptr _inputMeshTexture
RenderTargetTextures::Ptr _renderTargets
SceneOptions _currentOpts
Detailed Description
Class used to define a basic IBR Scene containing multiple components required to define a scene.
Definition at line 13 of file BasicIBRScene.hpp.
Constructor & Destructor Documentation
BasicIBRScene() [1/4]
sibr::BasicIBRScene::BasicIBRScene ()
Default constructor to create a BasicIBRScene.
Definition at line 13 of file BasicIBRScene.cpp.
References _cams, _data, _imgs, _proxies, and _renderTargets.
Referenced by BasicIBRScene().
BasicIBRScene() [2/4]
sibr::BasicIBRScene::BasicIBRScene (const BasicIBRAppArgs & myArgs, bool noRTs, bool noMesh = false)
Constructor to create a BasicIBRScene given command line arguments.
The scene may be created using either dataset path, or explicitly specifying individual componenets.
Parameters
myArgs to provide all command line arguments containing path to specific components.
noRTs to specify whether to initialize render target textures or not.
noMesh skip loading the mesh
Definition at line 21 of file BasicIBRScene.cpp.
References _currentOpts, _data, BasicIBRScene(), createFromData(), sibr::IParseData::EMPTY, sibr::IIBRScene::SceneOptions::mesh, sibr::IIBRScene::SceneOptions::renderTargets, SIBR_ERR, and sibr::RenderingArgs::texture_width.
BasicIBRScene() [3/4]
sibr::BasicIBRScene::BasicIBRScene (const BasicIBRAppArgs & myArgs, SceneOptions myOpts = SceneOptions())
Constructor to create a BasicIBRScene given command line arguments.
The scene may be created using either dataset path, or explicitly specifying individual componenets.
Parameters
myArgs to provide all command line arguments containing path to specific components.
myOpts to specify initialization paramters for the scene.
Definition at line 41 of file BasicIBRScene.cpp.
References _currentOpts, _data, BasicIBRScene(), createFromData(), sibr::IParseData::EMPTY, SIBR_ERR, and sibr::RenderingArgs::texture_width.
Referenced by BasicIBRScene().
~BasicIBRScene()
sibr::BasicIBRScene::~BasicIBRScene () inline
Destructor.
Definition at line 47 of file BasicIBRScene.hpp.
BasicIBRScene() [4/4]
sibr::BasicIBRScene::BasicIBRScene (BasicIBRScene & scene) protected
Definition at line 74 of file BasicIBRScene.cpp.
References _cams, _data, _imgs, _proxies, _renderTargets, cameras(), data(), images(), proxies(), and renderTargets().
Member Function Documentation
cameras()
const ICalibratedCameras::Ptr sibr::BasicIBRScene::cameras (void) const inline override virtual
Getter for the pointer holding cameras related to each input iamge of the scene.
Implements sibr::IIBRScene.
Definition at line 151 of file BasicIBRScene.hpp.
References _cams.
Referenced by BasicIBRScene(), sibr::DatasetView::DatasetView(), and main().
createFromCustomData()
void sibr::BasicIBRScene::createFromCustomData (const IParseData::Ptr & data, const uint width = 0, SceneOptions myOpts = SceneOptions()) override
Creates a BasicIBRScene given custom data argument.
The scene will be created using the custom data (cameras/images/proxies/textures etc.) provided.
Parameters
data to provide data instance holding customized components.
width the constrained width for GPU texture data.
myOpts to specify whether to initialize specific parts of the scene (RTs, geometry,...)
Definition at line 61 of file BasicIBRScene.cpp.
References _currentOpts, _data, createFromData(), and data().
createFromData()
void sibr::BasicIBRScene::createFromData (const uint width = 0) protected
Creates a BasicIBRScene from the internal stored data component in the scene.
The data could be populated either from dataset path or customized by the user externally.
Parameters
width the constrained width for GPU texture data.
Definition at line 83 of file BasicIBRScene.cpp.
References _cams, _currentOpts, _data, _imgs, _inputMeshTexture, _proxies, _renderTargets, sibr::IIBRScene::SceneOptions::cameras, sibr::CameraRaycaster::computeClippingPlanes(), createRenderTargets(), sibr::fileExists(), sibr::IIBRScene::SceneOptions::images, sibr::Image< T_Type, T_NumComp >::load(), sibr::IIBRScene::SceneOptions::mesh, sibr::parentDirectory(), sibr::IIBRScene::SceneOptions::renderTargets, SIBR_GPU_LINEAR_SAMPLING, and sibr::IIBRScene::SceneOptions::texture.
Referenced by BasicIBRScene(), and createFromCustomData().
createFromDatasetPath()
void sibr::BasicIBRScene::createFromDatasetPath () inline virtual
Function to create a scene directly using the dataset path specified in command-line.
Implements sibr::IIBRScene.
Definition at line 61 of file BasicIBRScene.hpp.
createRenderTargets()
void sibr::BasicIBRScene::createRenderTargets () override virtual
Function to generate render targets using the _data (regarding cameras, images, proxies) parsed from metadata file.
Implements sibr::IIBRScene.
Definition at line 69 of file BasicIBRScene.cpp.
References _cams, _imgs, _proxies, and _renderTargets.
Referenced by createFromData().
data() [1/2]
void sibr::BasicIBRScene::data (const sibr::IParseData::Ptr & data) inline override virtual
Setter for the pointer holding the data related to the scene for scene creation.
Parameters
data the setup data
Implements sibr::IIBRScene.
Definition at line 146 of file BasicIBRScene.hpp.
References _data, and data().
data() [2/2]
const IParseData::Ptr sibr::BasicIBRScene::data (void) const inline override virtual
Getter for the pointer holding the data related to the scene.
Implements sibr::IIBRScene.
Definition at line 141 of file BasicIBRScene.hpp.
References _data.
Referenced by BasicIBRScene(), createFromCustomData(), data(), and main().
images()
const IInputImages::Ptr sibr::BasicIBRScene::images (void) const inline override virtual
Getter for the pointer holding the input images to the scene.
Implements sibr::IIBRScene.
Definition at line 156 of file BasicIBRScene.hpp.
References _imgs.
Referenced by BasicIBRScene(), sibr::DatasetView::DatasetView(), and main().
inputMeshTextures()
Texture2DRGB::Ptr & sibr::BasicIBRScene::inputMeshTextures (void) inline override virtual
Getter for the pointer holding the mesh textures related to the mesh loaded for the scene.
Implements sibr::IIBRScene.
Definition at line 176 of file BasicIBRScene.hpp.
References _inputMeshTexture.
operator=()
BasicIBRScene& sibr::BasicIBRScene::operator= (const BasicIBRScene &) protected delete
proxies()
const IProxyMesh::Ptr sibr::BasicIBRScene::proxies (void) const inline override virtual
Getter for the pointer holding the proxies required by the scene.
Implements sibr::IIBRScene.
Definition at line 161 of file BasicIBRScene.hpp.
References _proxies.
Referenced by BasicIBRScene(), sibr::DatasetView::DatasetView(), and main().
renderTargets() [1/2]
const RenderTargetTextures::Ptr & sibr::BasicIBRScene::renderTargets (void) const inline override virtual
Getter for the pointer holding the render targets textures related to the scene.
Implements sibr::IIBRScene.
Definition at line 166 of file BasicIBRScene.hpp.
References _renderTargets.
Referenced by BasicIBRScene().
renderTargets() [2/2]
RenderTargetTextures::Ptr & sibr::BasicIBRScene::renderTargets (void) inline override virtual
Getter for the pointer holding the render targets textures related to the scene.
Implements sibr::IIBRScene.
Definition at line 171 of file BasicIBRScene.hpp.
References _renderTargets.
SIBR_CLASS_PTR()
sibr::BasicIBRScene::SIBR_CLASS_PTR (BasicIBRScene)
Pointer to the instance of class sibr::BasicIBRScene.
Member Data Documentation
_cams
ICalibratedCameras::Ptr sibr::BasicIBRScene::_cams protected
Definition at line 122 of file BasicIBRScene.hpp.
Referenced by BasicIBRScene(), cameras(), createFromData(), and createRenderTargets().
_currentOpts
SceneOptions sibr::BasicIBRScene::_currentOpts protected
Definition at line 127 of file BasicIBRScene.hpp.
Referenced by BasicIBRScene(), createFromCustomData(), and createFromData().
_data
IParseData::Ptr sibr::BasicIBRScene::_data protected
Definition at line 121 of file BasicIBRScene.hpp.
Referenced by BasicIBRScene(), createFromCustomData(), createFromData(), and data().
_imgs
IInputImages::Ptr sibr::BasicIBRScene::_imgs protected
Definition at line 123 of file BasicIBRScene.hpp.
Referenced by BasicIBRScene(), createFromData(), createRenderTargets(), and images().
_inputMeshTexture
Texture2DRGB::Ptr sibr::BasicIBRScene::_inputMeshTexture protected
Definition at line 125 of file BasicIBRScene.hpp.
Referenced by createFromData(), and inputMeshTextures().
_proxies
IProxyMesh::Ptr sibr::BasicIBRScene::_proxies protected
Definition at line 124 of file BasicIBRScene.hpp.
Referenced by BasicIBRScene(), createFromData(), createRenderTargets(), and proxies().
_renderTargets
RenderTargetTextures::Ptr sibr::BasicIBRScene::_renderTargets protected
Definition at line 126 of file BasicIBRScene.hpp.
Referenced by BasicIBRScene(), createFromData(), createRenderTargets(), and renderTargets().
The documentation for this class was generated from the following files:
src/core/scene/BasicIBRScene.hpp
src/core/scene/BasicIBRScene.cpp