SIBR: sibr::SceneDebugView Class Reference
sibr::SceneDebugView Class Reference
sibr_view
Scene viewer for IBR scenes with a proxy, cameras and input images.
#include <SceneDebugView.hpp>
Public Types
enum CameraInfoDisplay { SIZE, FOCAL, FOV_Y, ASPECT }
Which camera info should be displayed in the GUI.
Public Types inherited from sibr::ViewBase
typedef std::shared_ptr< ViewBase > Ptr
Public Member Functions
SceneDebugView (const IIBRScene::Ptr &scene, const InteractiveCameraHandler::Ptr &camHandler, const BasicDatasetArgs &myArgs)
Constructor.
SceneDebugView (const IIBRScene::Ptr &scene, const Viewport &viewport, const InteractiveCameraHandler::Ptr &camHandler, const BasicDatasetArgs &myArgs)
Constructor.
virtual void onUpdate (Input &input, const float deltaTime, const Viewport &viewport=Viewport(0.0f, 0.0f, 0.0f, 0.0f))
Update state based on user input.
virtual void onUpdate (Input &input, const Viewport &viewport) override
Update state based on user input.
virtual void onUpdate (Input &input) override
virtual void onRender (Window &win) override
Render content in a window.
virtual void onRender (const Viewport &viewport) override
Render content in the currently bound RT, using a specific viewport.
virtual void onGUI () override
Update and display GUI panels.
void save ()
Save the top view camera to scene/cameras/topview.txt.
const InteractiveCameraHandler & getCamera () const
InteractiveCameraHandler & getCamera ()
void setScene (const IIBRScene::Ptr &scene, bool preserveCamera=false)
Replace the scene.
void updateActiveCams (const std::vector< uint > &cams_id)
Update the active status of all cameras.
virtual void onRender (const Viewport &viewport) override
Render content in the currently bound RT, using a specific viewport.
virtual void onRender (IRenderTarget &dst)
Render content in a RT, using the RT viewport.
Public Member Functions inherited from sibr::MultiMeshManager
MultiMeshManager (const std::string &_name="MultiMeshManager")
Constructor.
MeshData & addMesh (const std::string &name, Mesh::Ptr mesh, bool use_raycaster=true)
Add a mesh to the visualization.
MeshData & addMesh (const std::string &name, Mesh::Ptr mesh, Raycaster::Ptr raycaster, bool create_raycaster=false)
Add a mesh to the visualization.
MeshData & addMeshAsLines (const std::string &name, Mesh::Ptr mesh)
Add lines to the visualization, using the mesh vertices as line endpoints.
MeshData & addLines (const std::string &name, const std::vector< Vector3f > &endPoints, const Vector3f &color={ 0, 1, 0 })
Add lines to the visualization, defined by their endpoints.
MeshData & addPoints (const std::string &name, const std::vector< Vector3f > &points, const Vector3f &color={ 1, 0, 0 })
Add points to the visualization.
MeshData & getMeshData (const std::string &name)
Accessor to the options of a visualized object.
void removeMesh (const std::string &name)
Remove a object from the viewer.
void setIntialView (const std::string &dataset_path)
virtual void onRender (IRenderTarget &dst)
Render content in a RT, using the RT viewport.
InteractiveCameraHandler & getCameraHandler ()
MeshShadingShader & getMeshShadingShader ()
Public Member Functions inherited from sibr::ViewBase
ViewBase (const unsigned int w=720, const unsigned int h=480)
Constructor.
virtual ~ViewBase ()=default
Destructor.
virtual void onRenderIBR (IRenderTarget &dst, const Camera &eye)
Render content in a given rendertarget.
virtual void preRender (RenderTargetRGB &prev)
Legacy: Used to mix with previous pass.
virtual void whichRT (uint i)
Legacy: Set the internal RT to use.
virtual uint whichRT (void)
Legacy:
void setResolution (const Vector2i &size)
Set the view resolution.
const Vector2i & getResolution (void) const
void active (bool act)
Toggle view status.
bool active ()
void setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
bool isFocused (void) const
void setName (const std::string &name)
Define the name of the view (used for disambiguation of GUI, etc.).
const std::string & name () const
Protected Member Functions
void gui_options ()
Generate the GUI for the display options.
void gui_cameras ()
generate the GUI with the camera infos.
void setup ()
Setup the view.
void setupMeshes ()
Setup the geometry.
Protected Member Functions inherited from sibr::MultiMeshManager
MeshData & addMeshData (MeshData &data, bool update_raycaster=false)
Helper to add some geometry to the view.
void initShaders ()
Create the shaders.
void renderMeshes ()
Render all the registered meshes.
void list_mesh_onGUI ()
Generate the list of objects in the GUI panel of the view.
Protected Member Functions inherited from sibr::ImageCamViewer
void initImageCamShaders ()
Initialize the shaders.
void renderImage (const Camera &eye, const InputCamera &cam, const std::vector< RenderTargetRGBA32F::Ptr > &rts, int cam_id)
Render one specific input image on a camera image plane.
void renderImage (const Camera &eye, const InputCamera &cam, uint tex2Darray_handle, int cam_id)
Render one specific input image on a camera image plane.
Protected Member Functions inherited from sibr::LabelsManager
void setupLabelsManagerShader ()
Initialize the shaders.
void setupLabelsManagerMeshes (const std::vector< InputCamera::Ptr > &cams)
Generate labels data based on input camera informations.
void renderLabels (const Camera &eye, const Viewport &vp, const std::vector< CameraInfos > &cams_info)
Render the camera labels.
Protected Attributes
InteractiveCameraHandler::Ptr _userCurrentCam
The "main view" camera handler (will be displayed as an extra camera).
IIBRScene::Ptr _scene
Current displayed scene.
std::vector< CameraInfos > _cameras
Additional scene cameras info.
CameraInfoDisplay _camInfoOption = SIZE
Camera info to display in the GUI.
std::string _topViewPath
Path to the topview saved file.
int _snapToImage = 0
ID of the camera to snap to.
int _cameraIdInfoGUI = 0
ID of the camera to display info about.
bool _showImages = true
Show the image planes.
bool _showLabels = false
Show camera labels.
Protected Attributes inherited from sibr::MultiMeshManager
std::string name
View name.
ListMesh list_meshes
Meshes to display.
Iterator selected_mesh_it
Currently selected mesh.
bool selected_mesh_it_is_valid = false
Is there a valid currently selected mesh.
InteractiveCameraHandler camera_handler
View camera handler.
PointShader points_shader
Shader for points.
MeshShadingShader colored_mesh_shader
Shader for meshes.
NormalRenderingShader per_vertex_normals_shader
NormalRenderingShader per_triangle_normals_shader
Shaders for visualizing an object normals.
Vector3f backgroundColor = { 0.7f, 0.7f, 0.7f }
Background clear color.
Protected Attributes inherited from sibr::ViewBase
uint _whichRT
Selected RT id.
std::vector< RenderTargetLum::Ptr > _masks
Rendering masks that can beused by some views/renderers.
bool _active = true
Is the view active.
Vector2i _resolution
View resolution.
bool _focus = false
Is the view focused.
std::string _name = ""
View name.
Protected Attributes inherited from sibr::ImageCamViewer
GLShader _shader2D
Shader for the 2D separate case.
GLShader _shaderArray
Shader for the texture array case.
GLuniform< sibr::Matrix4f > _mvp2D
GLuniform< sibr::Matrix4f > _mvpArray
MVP matrix.
GLuniform< float > _alpha2D = 1.0f
Opacity.
GLuniform< float > _alphaArray = 1.0f
Opacity.
GLuniform< int > _sliceArray = 1
Slice location (for the texture array case).
float _alphaImage = 0.5f
Opacity shared value.
float _cameraScaling = 0.8f
Camera scaling.
Protected Attributes inherited from sibr::LabelsManager
std::map< unsigned int, LabelMesh > _labelMeshes
Generated geometry for each label.
GLShader _labelShader
Shader.
GLuniform< Vector3f > _labelShaderPosition
Uniform for the label position.
GLuniform< float > _labelShaderScale = 1.0f
Uniform for the label scale (used twice per label, with different values derived from _labelScale).
GLuniform< Vector2f > _labelShaderViewport
The viewport of the view, for ratio adjustment.
float _labelScale = 1.0f
The label scale ons creen.
Private Member Functions
SIBR_CLASS_PTR (SceneDebugView)
Additional Inherited Members
Protected Types inherited from sibr::MultiMeshManager
using ListMesh = std::list< MeshData >
using Iterator = ListMesh::iterator
Detailed Description
Scene viewer for IBR scenes with a proxy, cameras and input images.
It adds camera visualization options (labels, frusta, image planes) on top of the MeshManager.
Definition at line 142 of file SceneDebugView.hpp.
Member Enumeration Documentation
CameraInfoDisplay
enum sibr::SceneDebugView::CameraInfoDisplay
Which camera info should be displayed in the GUI.
Enumerator
SIZE
FOCAL
FOV_Y
ASPECT
Definition at line 149 of file SceneDebugView.hpp.
Constructor & Destructor Documentation
SceneDebugView() [1/2]
sibr::SceneDebugView::SceneDebugView (const IIBRScene::Ptr & scene, const InteractiveCameraHandler::Ptr & camHandler, const BasicDatasetArgs & myArgs)
Constructor.
Parameters
scene the scene to display
camHandler a camera handler to display as a "user camera"
myArgs dataset arguments (needed to load/save the camera location)
Definition at line 180 of file SceneDebugView.cpp.
References sibr::BasicDatasetArgs::dataset_path, sibr::directoryExists(), sibr::RequiredArgBase< T >::get(), sibr::makeDirectory(), sibr::parentDirectory(), and sibr::LabelsManager::setupLabelsManagerShader().
SceneDebugView() [2/2]
sibr::SceneDebugView::SceneDebugView (const IIBRScene::Ptr & scene, const Viewport & viewport, const InteractiveCameraHandler::Ptr & camHandler, const BasicDatasetArgs & myArgs)
Constructor.
Parameters
scene the scene to display
viewport the view viewport
camHandler a camera handler to display as a "user camera"
myArgs dataset arguments (needed to load/save the camera location)
Warning
Deprecated, use the version without the viewport.
Definition at line 210 of file SceneDebugView.cpp.
References SIBR_WRG.
Member Function Documentation
getCamera() [1/2]
InteractiveCameraHandler& sibr::SceneDebugView::getCamera (void) inline
Returns
the camera handler for the view.
Definition at line 210 of file SceneDebugView.hpp.
getCamera() [2/2]
const InteractiveCameraHandler& sibr::SceneDebugView::getCamera (void) const inline
Returns
the camera handler for the view.
Definition at line 207 of file SceneDebugView.hpp.
gui_cameras()
void sibr::SceneDebugView::gui_cameras () protected
generate the GUI with the camera infos.
Definition at line 387 of file SceneDebugView.cpp.
References _cameraIdInfoGUI, _cameras, _camInfoOption, _scene, ASPECT, sibr::MultiMeshManager::camera_handler, sibr::Viewport::finalSize(), FOCAL, FOV_Y, sibr::InteractiveCameraHandler::fromCamera(), sibr::InteractiveCameraHandler::getViewport(), sibr::MultiMeshManager::name, and SIZE.
Referenced by onGUI().
gui_options()
void sibr::SceneDebugView::gui_options () protected
Generate the GUI for the display options.
Definition at line 356 of file SceneDebugView.cpp.
References sibr::ImageCamViewer::_alphaImage, sibr::ImageCamViewer::_cameraScaling, sibr::LabelsManager::_labelScale, _showImages, _showLabels, sibr::MultiMeshManager::camera_handler, sibr::InteractiveCameraHandler::onGUI(), ImGui::PushScaledItemWidth(), and save().
Referenced by onGUI().
onGUI()
void sibr::SceneDebugView::onGUI () override virtual
Update and display GUI panels.
Reimplemented from sibr::MultiMeshManager.
Definition at line 311 of file SceneDebugView.cpp.
References sibr::Key::End, gui_cameras(), gui_options(), and sibr::MultiMeshManager::list_mesh_onGUI().
onRender() [1/4]
void sibr::SceneDebugView::onRender (const Viewport & viewport) override virtual
Render content in the currently bound RT, using a specific viewport.
Parameters
viewport destination viewport
Note
Used when the view is in a multi-view system.
Reimplemented from sibr::MultiMeshManager.
Definition at line 259 of file SceneDebugView.cpp.
References _cameras, sibr::ImageCamViewer::_cameraScaling, _scene, _showImages, _showLabels, _userCurrentCam, sibr::MultiMeshManager::addMeshAsLines(), sibr::MultiMeshManager::backgroundColor, sibr::Viewport::bind(), sibr::MultiMeshManager::camera_handler, sibr::Viewport::clear(), sibr::generateCamFrustum(), sibr::InteractiveCameraHandler::getCamera(), sibr::InteractiveCameraHandler::onRender(), sibr::ImageCamViewer::renderImage(), sibr::LabelsManager::renderLabels(), sibr::MultiMeshManager::renderMeshes(), and sibr::MeshData::setColor().
onRender() [2/4]
void sibr::MultiMeshManager::onRender override
Render content in the currently bound RT, using a specific viewport.
Parameters
viewport destination viewport
Note
Used when the view is in a multi-view system.
Definition at line 363 of file MultiMeshManager.cpp.
Referenced by onRender().
onRender() [3/4]
void sibr::MultiMeshManager::onRender
Render content in a RT, using the RT viewport.
Parameters
dst destination RT
Definition at line 368 of file MultiMeshManager.cpp.
References sibr::Key::End, sibr::MultiMeshManager::list_mesh_onGUI(), and sibr::MultiMeshManager::name.
onRender() [4/4]
void sibr::SceneDebugView::onRender (Window & win) override virtual
Render content in a window.
Parameters
win destination window
Reimplemented from sibr::ViewBase.
Definition at line 253 of file SceneDebugView.cpp.
References onRender(), and sibr::Window::viewport().
onUpdate() [1/3]
void sibr::SceneDebugView::onUpdate (Input & input) override virtual
Reimplemented from sibr::ViewBase.
Definition at line 247 of file SceneDebugView.cpp.
References onUpdate().
onUpdate() [2/3]
void sibr::SceneDebugView::onUpdate (Input & input, const float deltaTime, const Viewport & viewport = Viewport(0.0f, 0.0f, 0.0f, 0.0f)) virtual
Update state based on user input.
Parameters
input user input
deltaTime the time elapsed since last update
viewport input viewport
Note
Used when the view is in a multi-view system.
Definition at line 215 of file SceneDebugView.cpp.
References sibr::ImageCamViewer::_cameraScaling, sibr::MeshData::active, sibr::MultiMeshManager::getMeshData(), sibr::InputState< TNbState, TEnum >::isActivated(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Input::key(), sibr::Key::LeftControl, sibr::Input::mouseScroll(), sibr::MultiMeshManager::onUpdate(), sibr::Key::P, sibr::MeshData::renderMode, save(), sibr::Key::T, and sibr::Key::Z.
Referenced by onUpdate().
onUpdate() [3/3]
void sibr::SceneDebugView::onUpdate (Input & input, const Viewport & viewport) override virtual
Update state based on user input.
Parameters
input user input
viewport input viewport
Note
Used when the view is in a multi-view system.
Reimplemented from sibr::MultiMeshManager.
Definition at line 242 of file SceneDebugView.cpp.
References onUpdate().
save()
void sibr::SceneDebugView::save ()
Save the top view camera to scene/cameras/topview.txt.
Definition at line 322 of file SceneDebugView.cpp.
References _topViewPath, sibr::MultiMeshManager::camera_handler, sibr::InteractiveCameraHandler::getCamera(), and sibr::InputCamera::writeToFile().
Referenced by gui_options(), and onUpdate().
setScene()
void sibr::SceneDebugView::setScene (const IIBRScene::Ptr & scene, bool preserveCamera = false)
Replace the scene.
Parameters
scene the new scene
preserveCamera should the current camera position be preserved
Definition at line 331 of file SceneDebugView.cpp.
References _scene, sibr::MultiMeshManager::camera_handler, sibr::InteractiveCameraHandler::fromCamera(), sibr::InteractiveCameraHandler::getCamera(), sibr::InteractiveCameraHandler::getRaycaster(), sibr::InteractiveCameraHandler::getViewport(), setup(), sibr::InteractiveCameraHandler::setup(), and sibr::InteractiveCameraHandler::setupInterpolationPath().
setup()
void sibr::SceneDebugView::setup () protected
Setup the view.
Definition at line 460 of file SceneDebugView.cpp.
References _cameras, _scene, _showLabels, _snapToImage, _topViewPath, sibr::MultiMeshManager::camera_handler, sibr::InteractiveCameraHandler::fromTransform(), sibr::InteractiveCameraHandler::getCamera(), sibr::InputCamera::readFromFile(), sibr::LabelsManager::setupLabelsManagerMeshes(), setupMeshes(), SIBR_LOG, and sibr::Camera::transform().
Referenced by setScene().
setupMeshes()
void sibr::SceneDebugView::setupMeshes () protected
Setup the geometry.
Definition at line 491 of file SceneDebugView.cpp.
References _scene, sibr::MultiMeshManager::addMesh(), sibr::MultiMeshManager::addMeshAsLines(), sibr::RenderUtility::createAxisGizmo(), sibr::MeshData::setColorMode(), and sibr::MeshData::setDepthTest().
Referenced by setup().
SIBR_CLASS_PTR()
sibr::SceneDebugView::SIBR_CLASS_PTR (SceneDebugView) private
updateActiveCams()
void sibr::SceneDebugView::updateActiveCams (const std::vector< uint > & cams_id)
Update the active status of all cameras.
Parameters
cams_id the active camera IDs.
Definition at line 344 of file SceneDebugView.cpp.
References _cameras.
Member Data Documentation
_cameraIdInfoGUI
int sibr::SceneDebugView::_cameraIdInfoGUI = 0 protected
ID of the camera to display info about.
Definition at line 243 of file SceneDebugView.hpp.
Referenced by gui_cameras().
_cameras
std::vector<CameraInfos> sibr::SceneDebugView::_cameras protected
Additional scene cameras info.
Definition at line 239 of file SceneDebugView.hpp.
Referenced by gui_cameras(), onRender(), setup(), and updateActiveCams().
_camInfoOption
CameraInfoDisplay sibr::SceneDebugView::_camInfoOption = SIZE protected
Camera info to display in the GUI.
Definition at line 240 of file SceneDebugView.hpp.
Referenced by gui_cameras().
_scene
IIBRScene::Ptr sibr::SceneDebugView::_scene protected
Current displayed scene.
Definition at line 238 of file SceneDebugView.hpp.
Referenced by gui_cameras(), onRender(), setScene(), setup(), and setupMeshes().
_showImages
bool sibr::SceneDebugView::_showImages = true protected
Show the image planes.
Definition at line 244 of file SceneDebugView.hpp.
Referenced by gui_options(), and onRender().
_showLabels
bool sibr::SceneDebugView::_showLabels = false protected
Show camera labels.
Definition at line 245 of file SceneDebugView.hpp.
Referenced by gui_options(), onRender(), and setup().
_snapToImage
int sibr::SceneDebugView::_snapToImage = 0 protected
ID of the camera to snap to.
Definition at line 242 of file SceneDebugView.hpp.
Referenced by setup().
_topViewPath
std::string sibr::SceneDebugView::_topViewPath protected
Path to the topview saved file.
Definition at line 241 of file SceneDebugView.hpp.
Referenced by save(), and setup().
_userCurrentCam
InteractiveCameraHandler::Ptr sibr::SceneDebugView::_userCurrentCam protected
The "main view" camera handler (will be displayed as an extra camera).
Definition at line 237 of file SceneDebugView.hpp.
Referenced by onRender().
The documentation for this class was generated from the following files:
src/core/view/SceneDebugView.hpp
src/core/view/SceneDebugView.cpp