SIBR: sibr::Input Class Reference
sibr::Input Class Reference
sibr_graphics
Maintain the complete state of user interactions (mouse, keyboard) for a given view or window.
#include <Input.hpp>
Public Types
typedef InputState< Key::count, Key::Code > Keyboard
typedef InputState< Mouse::count, Mouse::Code > MouseButton
Public Member Functions
bool isInsideViewport (const sibr::Viewport &viewport) const
Is the mouse inside a given viewport.
const Keyboard & key (void) const
Keyboard & key (void)
const MouseButton & mouseButton (void) const
MouseButton & mouseButton (void)
const Vector2i & mousePosition (void) const
void mousePosition (Vector2i mousePos)
Set the current mouse position.
Vector2i mouseDeltaPosition (void) const
int pressedNumber () const
If any number key is pressed, return the lowest one.
void swapStates (void)
Update last frame state with the current one.
double mouseScroll (void) const
void mouseScroll (double v)
Set the scroll amount.
bool empty () const
Static Public Member Functions
static Input & global (void)
static Input subInput (const sibr::Input &global, const sibr::Viewport &viewport, const bool mouseOutsideDisablesKeyboard=true)
Generate a new Input object based on a parent one and a viewport.
static void poll (void)
Update internal state based on GLFW, call once per frame.
Private Attributes
Keyboard _keyboard
Keyboard state.
MouseButton _mouseButton
Mouse state.
Vector2i _mousePos = {0, 0}
Current mouse position.
Vector2i _mousePrevPos = { 0, 0 }
Previous mouse position.
double _mouseScroll = 0.0
Current scroll amount.
bool _empty = true
Is the input associated to an empty view/window.
Detailed Description
Maintain the complete state of user interactions (mouse, keyboard) for a given view or window.
All coordinates are recaled with respect to the associated view. To check if the B key is currently held: input.key().isActivated(Key::B); To check if the right mouse was just released: input.mouseButton().isReleased(Mouse::Right);
Definition at line 308 of file Input.hpp.
Member Typedef Documentation
Keyboard
typedef InputState<Key::count, Key::Code> sibr::Input::Keyboard
Definition at line 311 of file Input.hpp.
MouseButton
typedef InputState<Mouse::count, Mouse::Code> sibr::Input::MouseButton
Definition at line 312 of file Input.hpp.
Member Function Documentation
empty()
bool sibr::Input::empty () const inline
Returns
true if the input is associated to an empty view/window.
Definition at line 412 of file Input.hpp.
Referenced by sibr::TrackBall::update().
global()
Input & sibr::Input::global (void) static
Returns
the global system input (all others are derived from this one)
Definition at line 7 of file Input.cpp.
References _empty.
Referenced by sibr::Window::AutoInitializer::AutoInitializer(), sibr::MultiViewInterface::displayLoop(), sibr::glfwCursorPosCallback(), sibr::glfwKeyboardCallback(), sibr::glfwMouseButtonCallback(), sibr::glfwMouseScrollCallback(), legacyV1main(), legacyV2main(), main(), sibr::KeyCombination::operator bool(), poll(), sibr::MeshViewer::renderLoop(), sibr::show(), subInput(), and sibr::MultiViewInterface::updateMeshView().
isInsideViewport()
bool sibr::Input::isInsideViewport (const sibr::Viewport & viewport) const
Is the mouse inside a given viewport.
Parameters
viewport the viewport to test against
Returns
true if the mouse is inside.
Definition at line 40 of file Input.cpp.
References sibr::Viewport::finalBottom(), sibr::Viewport::finalLeft(), sibr::Viewport::finalRight(), sibr::Viewport::finalTop(), and mousePosition().
Referenced by subInput(), and sibr::GridMapping::updateZoomBox().
key() [1/2]
Keyboard& sibr::Input::key (void) inline
Returns
the keyboard state.
Definition at line 343 of file Input.hpp.
key() [2/2]
const Keyboard& sibr::Input::key (void) const inline
Returns
the keyboard state.
Definition at line 338 of file Input.hpp.
Referenced by sibr::Window::AutoInitializer::AutoInitializer(), sibr::glfwKeyboardCallback(), sibr::FPSCamera::moveUsingWASD(), sibr::MultiViewBase::onUpdate(), sibr::ULRV2View::onUpdate(), sibr::DatasetView::onUpdate(), sibr::MultiViewManager::onUpdate(), sibr::SceneDebugView::onUpdate(), sibr::ImagesGrid::onUpdate(), sibr::KeyCombination::operator bool(), sibr::show(), sibr::Orbit::update(), sibr::InteractiveCameraHandler::update(), sibr::MultiViewInterface::updateCurrentLayer(), sibr::TrackBall::updateFromKeyboard(), sibr::MultiViewInterface::updateImageView(), sibr::TrackBall::updateRadius(), sibr::TrackBall::updateTrackBallCamera(), sibr::TrackBall::updateTrackBallStatus(), sibr::TrackBall::updateZnearZFar(), sibr::GridMapping::updateZoomBox(), sibr::MultiViewInterface::updateZoomBox(), sibr::GridMapping::updateZoomScroll(), and sibr::MultiViewInterface::updateZoomScroll().
mouseButton() [1/2]
MouseButton& sibr::Input::mouseButton (void) inline
Returns
the mouse buttons state.
Definition at line 353 of file Input.hpp.
mouseButton() [2/2]
const MouseButton& sibr::Input::mouseButton (void) const inline
Returns
the mouse buttons state.
Definition at line 348 of file Input.hpp.
Referenced by sibr::DoubleClick< sibr::Mouse::Left >::detected(), sibr::glfwMouseButtonCallback(), sibr::FPSCamera::moveUsingMousePan(), sibr::DatasetView::onUpdate(), sibr::ImagesGrid::onUpdate(), sibr::ImageView::onUpdate(), sibr::Orbit::update(), sibr::TrackBall::updateBallCenter(), sibr::GridMapping::updateDrag(), sibr::MultiViewInterface::updateDrag(), sibr::TrackBall::updateTrackBallStatus(), sibr::TrackBall::updateTranslationPlane(), sibr::GridMapping::updateZoomBox(), and sibr::MultiViewInterface::updateZoomBox().
mouseDeltaPosition()
Vector2i sibr::Input::mouseDeltaPosition (void) const inline
Returns
the change in mouse position since last frame.
Definition at line 370 of file Input.hpp.
Referenced by sibr::FPSCamera::moveUsingMousePan(), and sibr::ImageView::onUpdate().
mousePosition() [1/2]
void sibr::Input::mousePosition (Vector2i mousePos) inline
Set the current mouse position.
Parameters
mousePos the new position
Definition at line 365 of file Input.hpp.
mousePosition() [2/2]
const Vector2i& sibr::Input::mousePosition (void) const inline
Returns
the current mouse position
Definition at line 358 of file Input.hpp.
Referenced by sibr::DoubleClick< sibr::Mouse::Left >::detected(), sibr::glfwCursorPosCallback(), isInsideViewport(), sibr::DatasetView::onUpdate(), sibr::ImagesGrid::onUpdate(), sibr::TrackBall::updateBallCenter(), sibr::GridMapping::updateDrag(), sibr::MultiViewInterface::updateDrag(), sibr::MultiViewInterface::updateImageView(), sibr::Orbit::updateOrbitParameters(), sibr::TrackBall::updateRotationRoll(), sibr::TrackBall::updateRotationSphere(), sibr::TrackBall::updateTrackBallStatus(), sibr::TrackBall::updateTranslationPlane(), sibr::TrackBall::updateTranslationZ(), sibr::GridMapping::updateZoomBox(), and sibr::MultiViewInterface::updateZoomBox().
mouseScroll() [1/2]
void sibr::Input::mouseScroll (double v) inline
Set the scroll amount.
Parameters
v the scroll amount.
Definition at line 407 of file Input.hpp.
mouseScroll() [2/2]
double sibr::Input::mouseScroll (void) const inline
Returns
the scroll amount along the vertical axis.
Definition at line 400 of file Input.hpp.
Referenced by sibr::glfwMouseScrollCallback(), sibr::SceneDebugView::onUpdate(), sibr::ImageView::onUpdate(), sibr::TrackBall::updateRadius(), sibr::TrackBall::updateTrackBallCamera(), sibr::TrackBall::updateZnearZFar(), sibr::GridMapping::updateZoomScroll(), and sibr::MultiViewInterface::updateZoomScroll().
poll()
void sibr::Input::poll (void) static
Update internal state based on GLFW, call once per frame.
Definition at line 15 of file Input.cpp.
References global(), and swapStates().
Referenced by sibr::MultiViewInterface::displayLoop(), legacyV1main(), legacyV2main(), main(), sibr::MeshViewer::renderLoop(), and sibr::show().
pressedNumber()
int sibr::Input::pressedNumber () const inline
If any number key is pressed, return the lowest one.
Returns
the smallest pressed number, or -1 if none is pressed.
Definition at line 377 of file Input.hpp.
References sibr::Key::Num0, sibr::Key::Num1, sibr::Key::Num2, sibr::Key::Num3, sibr::Key::Num4, sibr::Key::Num5, sibr::Key::Num6, sibr::Key::Num7, sibr::Key::Num8, and sibr::Key::Num9.
subInput()
Input sibr::Input::subInput (const sibr::Input & global, const sibr::Viewport & viewport, const bool mouseOutsideDisablesKeyboard = true) static
Generate a new Input object based on a parent one and a viewport.
Events (clicks) happening outside the viewport will be ignored, mouse coordinates will be recentered with respect to the viewport.
Parameters
global the parent input
viewport the viewport to retrict the input to
mouseOutsideDisablesKeyboard if set to true, keyboard inputs are ignored when the mouse is outside the viewport
Returns
the new restricted input
Definition at line 21 of file Input.cpp.
References _keyboard, _mouseButton, _mousePos, _mousePrevPos, _mouseScroll, sibr::Viewport::finalLeft(), sibr::Viewport::finalTop(), global(), and isInsideViewport().
Referenced by sibr::MultiViewInterface::displayLoop(), sibr::MultiViewBase::onUpdate(), and sibr::DatasetView::onUpdate().
swapStates()
void sibr::Input::swapStates (void) inline
Update last frame state with the current one.
Call at the end of each frame.
Definition at line 392 of file Input.hpp.
Referenced by poll().
Member Data Documentation
_empty
bool sibr::Input::_empty = true private
Is the input associated to an empty view/window.
Definition at line 424 of file Input.hpp.
Referenced by global().
_keyboard
Keyboard sibr::Input::_keyboard private
Keyboard state.
Definition at line 418 of file Input.hpp.
Referenced by subInput().
_mouseButton
MouseButton sibr::Input::_mouseButton private
Mouse state.
Definition at line 419 of file Input.hpp.
Referenced by subInput().
_mousePos
Vector2i sibr::Input::_mousePos = {0, 0} private
Current mouse position.
Definition at line 421 of file Input.hpp.
Referenced by subInput().
_mousePrevPos
Vector2i sibr::Input::_mousePrevPos = { 0, 0 } private
Previous mouse position.
Definition at line 422 of file Input.hpp.
Referenced by subInput().
_mouseScroll
double sibr::Input::_mouseScroll = 0.0 private
Current scroll amount.
Definition at line 423 of file Input.hpp.
Referenced by subInput().
The documentation for this class was generated from the following files:
src/core/graphics/Input.hpp
src/core/graphics/Input.cpp