SIBR: sibr::ArgBase< T > Class Template Reference
sibr::ArgBase< T > Class Template Reference
sibr_system
Internal argument based interface.
#include <CommandLineArgs.hpp>
Public Member Functions
operator const T & () const
const T & get () const
T & operator= (const T &t)
Copy operator.
Protected Attributes
T value
the argument value.
Detailed Description
template<typename T>
class sibr::ArgBase< T >
Internal argument based interface.
Definition at line 166 of file CommandLineArgs.hpp.
Member Function Documentation
get()
template<typename T > const T& sibr::ArgBase< T >::get () const inline
Returns
a reference to the argument value
Definition at line 173 of file CommandLineArgs.hpp.
Referenced by sibr::AppArgs::displayHelpIfRequired(), getParamas(), sibr::ParseData::getParsedData(), legacyV1main(), legacyV2main(), and main().
operator const T &()
template<typename T > sibr::ArgBase< T >::operator const T & () const inline
Returns
a reference to the argument value
Definition at line 170 of file CommandLineArgs.hpp.
operator=()
template<typename T > T& sibr::ArgBase< T >::operator= (const T & t) inline
Copy operator.
Parameters
t the value to copy
Returns
a reference to the argument value
Definition at line 179 of file CommandLineArgs.hpp.
Member Data Documentation
value
template<typename T > T sibr::ArgBase< T >::value protected
the argument value.
Definition at line 183 of file CommandLineArgs.hpp.
Referenced by sibr::Arg< Switch >::Arg(), sibr::Arg< sibr::Switch >::Arg(), sibr::Arg< bool >::Arg(), sibr::ArgBase< bool >::get(), sibr::ArgBase< Vector2i >::operator const Vector2i &(), and sibr::ArgBase< bool >::operator=().
The documentation for this class was generated from the following file:
src/core/system/CommandLineArgs.hpp