SIBR: sibr::CommandLineArgs Class Reference
sibr::CommandLineArgs Class Reference
#include <CommandLineArgs.hpp>
Public Member Functions
template<typename T , uint N = 0>
T get (const std::string &key, const T &default_val) const
Get the Nth parsed element following -key or –key as a T If not available (key not found or not enough token), return default_val argument.
template<typename T , uint N = 0>
T getRequired (const std::string &key) const
Get the Nth parsed element following -key or –key as a T If not available (key not found or not enough token), an error is raised.
void registerCommand (const std::string &key, const std::string &description, const std::string &defaultValue)
Register a command for the help message.
void registerRequiredCommand (const std::string &key, const std::string &description)
Register a mandatory command for the help message.
bool contains (const std::string &key) const
Check if a given argument was specified by the user.
int numArguments (const std::string &key) const
Count how many parameters were specified by the suer for a given argument.
void displayHelp () const
Display an help message to stdout.
Static Public Member Functions
static void parseMainArgs (const int argc, const char *const *argv)
Populate arguments list, should be called once at launch.
static CommandLineArgs & getGlobal ()
Global instance getter.
Protected Member Functions
CommandLineArgs ()=default
Default constructor.
template<typename T , uint N = 0>
bool getInternal (const std::string &key, T &val) const
Get the Nth parsed element following -key or –key as a T If not available (key not found or not enough token), an error is raised.
Protected Attributes
std::map< std::string, std::vector< std::string > > args
List of arguments input by the user and their parameters.
std::map< std::string, std::string > commands
List of registered commands to display the help.
bool init = false
Have the arguments been parsed.
Static Protected Attributes
static CommandLineArgs global = CommandLineArgs()
Singleton (because there is only one command line).
Detailed Description
Definition at line 64 of file CommandLineArgs.hpp.
Constructor & Destructor Documentation
CommandLineArgs()
sibr::CommandLineArgs::CommandLineArgs () protected default
Default constructor.
Member Function Documentation
contains()
bool sibr::CommandLineArgs::contains (const std::string & key) const
Check if a given argument was specified by the user.
Parameters
key the argument to look for
Returns
whether the argument was specified
Definition at line 61 of file CommandLineArgs.cpp.
References args.
Referenced by numArguments().
displayHelp()
void sibr::CommandLineArgs::displayHelp () const
Display an help message to stdout.
Definition at line 76 of file CommandLineArgs.cpp.
References args, and SIBR_LOG.
Referenced by sibr::RequiredArgBase< std::string >::checkInit(), and sibr::AppArgs::displayHelpIfRequired().
get()
template<typename T , uint N = 0> T sibr::CommandLineArgs::get (const std::string & key, const T & default_val) const inline
Get the Nth parsed element following -key or –key as a T If not available (key not found or not enough token), return default_val argument.
Parameters
key the argument keyword
default_val the default value to use if not present
Definition at line 80 of file CommandLineArgs.hpp.
References sibr::Key::T.
Referenced by sibr::Arg< Switch >::Arg(), sibr::Arg< sibr::Switch >::Arg(), sibr::Arg< bool >::Arg(), and sibr::RequiredArgBase< std::string >::RequiredArgBase().
getGlobal()
CommandLineArgs & sibr::CommandLineArgs::getGlobal () static
Global instance getter.
Definition at line 15 of file CommandLineArgs.cpp.
References global, init, and SIBR_WRG.
Referenced by sibr::AppArgs::AppArgs(), sibr::Arg< Switch >::Arg(), sibr::Arg< sibr::Switch >::Arg(), sibr::Arg< bool >::Arg(), sibr::RequiredArgBase< std::string >::checkInit(), sibr::getCommandLineArgs(), and sibr::RequiredArgBase< std::string >::RequiredArgBase().
getInternal()
template<typename T , uint N = 0> bool sibr::CommandLineArgs::getInternal (const std::string & key, T & val) const inline protected
Get the Nth parsed element following -key or –key as a T If not available (key not found or not enough token), an error is raised.
Definition at line 142 of file CommandLineArgs.hpp.
References sibr::ValueGetter< T >::get(), and sibr::Key::N.
getRequired()
template<typename T , uint N = 0> T sibr::CommandLineArgs::getRequired (const std::string & key) const inline
Get the Nth parsed element following -key or –key as a T If not available (key not found or not enough token), an error is raised.
Parameters
key the argument keyword
Definition at line 94 of file CommandLineArgs.hpp.
References SIBR_ERR, and sibr::Key::T.
Referenced by sibr::AppArgs::AppArgs().
numArguments()
int sibr::CommandLineArgs::numArguments (const std::string & key) const
Count how many parameters were specified by the suer for a given argument.
Parameters
key the argument to look for
Returns
the number of parameters
Definition at line 66 of file CommandLineArgs.cpp.
References args, and contains().
parseMainArgs()
void sibr::CommandLineArgs::parseMainArgs (const int argc, const char *const * argv) static
Populate arguments list, should be called once at launch.
Parameters
argc argument count
argv argument list
Definition at line 25 of file CommandLineArgs.cpp.
References args, global, init, and SIBR_WRG.
Referenced by getParamas(), and main().
registerCommand()
void sibr::CommandLineArgs::registerCommand (const std::string & key, const std::string & description, const std::string & defaultValue)
Register a command for the help message.
Parameters
key the command
description a string describing the use of the command
defaultValue string representation of the default value
Definition at line 109 of file CommandLineArgs.cpp.
Referenced by sibr::Arg< Switch >::Arg(), sibr::Arg< sibr::Switch >::Arg(), and sibr::Arg< bool >::Arg().
registerRequiredCommand()
void sibr::CommandLineArgs::registerRequiredCommand (const std::string & key, const std::string & description)
Register a mandatory command for the help message.
Parameters
key the command
description a string describing the use of the command
Definition at line 116 of file CommandLineArgs.cpp.
Referenced by sibr::RequiredArgBase< std::string >::RequiredArgBase().
Member Data Documentation
args
std::map<std::string, std::vector<std::string> > sibr::CommandLineArgs::args protected
List of arguments input by the user and their parameters.
Definition at line 151 of file CommandLineArgs.hpp.
Referenced by contains(), displayHelp(), TaskPipeline.TaskPipeline::isExpressionValid(), numArguments(), parseMainArgs(), and TaskPipeline.TaskPipeline::runProcessSteps().
commands
std::map<std::string, std::string> sibr::CommandLineArgs::commands protected
List of registered commands to display the help.
Definition at line 152 of file CommandLineArgs.hpp.
global
CommandLineArgs sibr::CommandLineArgs::global = CommandLineArgs() static protected
Singleton (because there is only one command line).
Definition at line 155 of file CommandLineArgs.hpp.
Referenced by getGlobal(), and parseMainArgs().
init
bool sibr::CommandLineArgs::init = false protected
Have the arguments been parsed.
Definition at line 153 of file CommandLineArgs.hpp.
Referenced by getGlobal(), and parseMainArgs().
The documentation for this class was generated from the following files:
src/core/system/CommandLineArgs.hpp
src/core/system/CommandLineArgs.cpp