SIBR: sibr::MonoRdrMode Class Reference
sibr::MonoRdrMode Class Reference
sibr_view
Default rendering mode: monoview, passthrough.
#include <RenderingMode.hpp>
Public Member Functions
MonoRdrMode (void)
Constructor.
void render (ViewBase &view, const sibr::Camera &eye, const sibr::Viewport &viewport, IRenderTarget *optDest=nullptr)
Perform rendering of a view.
void destRT2img (sibr::ImageRGB &current_img)
Get the current rendered image as a CPU image.
virtual const std::unique_ptr< RenderTargetRGB > & lRT ()
virtual const std::unique_ptr< RenderTargetRGB > & rRT ()
Public Member Functions inherited from sibr::IRenderingMode
virtual ~IRenderingMode (void)
Destructor.
void setPrev (const std::unique_ptr< RenderTargetRGB > &p)
Set common previous step RT.
void setPrevLR (const std::unique_ptr< RenderTargetRGB > &pl, const std::unique_ptr< RenderTargetRGB > &pr)
Set left and right previous step RTs.
Private Attributes
sibr::GLShader _quadShader
Passthrough shader.
std::unique_ptr< RenderTarget > _destRT
Common destination RT.
Additional Inherited Members
Public Types inherited from sibr::IRenderingMode
typedef RenderTargetRGB RenderTarget
Public Attributes inherited from sibr::IRenderingMode
bool _clear
Should the dst RT be cleared before rendering.
Protected Attributes inherited from sibr::IRenderingMode
std::unique_ptr< RenderTargetRGB > _prevL
std::unique_ptr< RenderTargetRGB > _prevR
prev RT to link renderers across different views in multipass
Detailed Description
Default rendering mode: monoview, passthrough.
Definition at line 68 of file RenderingMode.hpp.
Constructor & Destructor Documentation
MonoRdrMode()
sibr::MonoRdrMode::MonoRdrMode (void)
Constructor.
Definition at line 9 of file RenderingMode.cpp.
References sibr::IRenderingMode::_clear, _quadShader, sibr::GLShader::init(), sibr::Resources::Instance(), and sibr::loadFile().
Member Function Documentation
destRT2img()
void sibr::MonoRdrMode::destRT2img (sibr::ImageRGB & current_img) inline virtual
Get the current rendered image as a CPU image.
Parameters
current_img will contain the content of the RT
Implements sibr::IRenderingMode.
Definition at line 85 of file RenderingMode.hpp.
lRT()
virtual const std::unique_ptr<RenderTargetRGB>& sibr::MonoRdrMode::lRT () inline virtual
Returns
the common RT.
Implements sibr::IRenderingMode.
Definition at line 92 of file RenderingMode.hpp.
render()
void sibr::MonoRdrMode::render (ViewBase & view, const sibr::Camera & eye, const sibr::Viewport & viewport, IRenderTarget * optDest = nullptr) virtual
Perform rendering of a view.
Parameters
view the view to render
eye the current camera
viewport the current viewport
optDest an optional destination RT
Implements sibr::IRenderingMode.
Definition at line 17 of file RenderingMode.cpp.
References sibr::IRenderingMode::_clear, _destRT, sibr::IRenderingMode::_prevR, _quadShader, sibr::GLShader::begin(), sibr::Viewport::bind(), sibr::IRenderTarget::bind(), sibr::Viewport::clear(), sibr::GLShader::end(), sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), sibr::IRenderTarget::h(), sibr::ViewBase::onRenderIBR(), sibr::ViewBase::preRender(), sibr::RenderUtility::renderScreenQuad(), sibr::show(), SIBR_GPU_LINEAR_SAMPLING, sibr::IRenderTarget::unbind(), and sibr::IRenderTarget::w().
rRT()
virtual const std::unique_ptr<RenderTargetRGB>& sibr::MonoRdrMode::rRT () inline virtual
Returns
the common RT.
Implements sibr::IRenderingMode.
Definition at line 94 of file RenderingMode.hpp.
Member Data Documentation
_destRT
std::unique_ptr<RenderTarget> sibr::MonoRdrMode::_destRT private
Common destination RT.
Definition at line 98 of file RenderingMode.hpp.
Referenced by render().
_quadShader
sibr::GLShader sibr::MonoRdrMode::_quadShader private
Passthrough shader.
Definition at line 97 of file RenderingMode.hpp.
Referenced by MonoRdrMode(), and render().
The documentation for this class was generated from the following files:
src/core/view/RenderingMode.hpp
src/core/view/RenderingMode.cpp