SIBR: sibr::ActiveImageFile Class Reference
sibr::ActiveImageFile Class Reference
sibr_assets
Represent a active_images.txt file use to select a subset of a scene images.
#include <ActiveImageFile.hpp>
Public Member Functions
void setNumImages (int n)
Set the number of images contained in the associated scene.
bool load (const std::string &filename, bool verbose=true) override
Load an active cameras listing from a file on disk.
bool load (const std::string &filename, int numImages, bool verbose=true)
Load an active cameras listing from a file on disk, expecting numImage images in total.
const std::vector< bool > & active (void) const
Return a reference to a boolean vector indicating, for each picture of the associated scene, if it is active or not.
Public Member Functions inherited from sibr::IFileLoader
virtual ~IFileLoader (void)
Destructor.
Private Attributes
std::vector< bool > _active
Flags denoting which images are active.
int _numImages = 0
Number of images.
Detailed Description
Represent a active_images.txt file use to select a subset of a scene images.
Definition at line 13 of file ActiveImageFile.hpp.
Member Function Documentation
active()
const std::vector<bool>& sibr::ActiveImageFile::active (void) const inline
Return a reference to a boolean vector indicating, for each picture of the associated scene, if it is active or not.
Returns
the boolean vector described above.
Definition at line 47 of file ActiveImageFile.hpp.
Referenced by sibr::InputCamera::load(), and sibr::ImageListFile::loadImages().
load() [1/2]
bool sibr::ActiveImageFile::load (const std::string & filename, bool verbose = true) override virtual
Load an active cameras listing from a file on disk.
Parameters
filename the path to the file.
verbose output additional informations to the standard output.
Returns
a boolean indicating if the loading was successful or not.
Implements sibr::IFileLoader.
Definition at line 7 of file ActiveImageFile.cpp.
References _active, _numImages, SIBR_FLOG, and SIBR_WRG.
Referenced by sibr::InputCamera::load(), and load().
load() [2/2]
bool sibr::ActiveImageFile::load (const std::string & filename, int numImages, bool verbose = true)
Load an active cameras listing from a file on disk, expecting numImage images in total.
The active images file does not indicate the total number of cameras in the scene, thus the additional parameter.
Parameters
filename the path to the file.
numImages the total number of images in the associated scene.
verbose output additional informations to the standard output.
Returns
a boolean indicating if the load was successful or not.
Definition at line 44 of file ActiveImageFile.cpp.
References _numImages, and load().
setNumImages()
void sibr::ActiveImageFile::setNumImages (int n) inline
Set the number of images contained in the associated scene.
Parameters
n the number of images.
Definition at line 22 of file ActiveImageFile.hpp.
Referenced by sibr::InputCamera::load().
Member Data Documentation
_active
std::vector<bool> sibr::ActiveImageFile::_active private
Flags denoting which images are active.
Definition at line 51 of file ActiveImageFile.hpp.
Referenced by load().
_numImages
int sibr::ActiveImageFile::_numImages = 0 private
Number of images.
Definition at line 52 of file ActiveImageFile.hpp.
Referenced by load().
The documentation for this class was generated from the following files:
src/core/assets/ActiveImageFile.hpp
src/core/assets/ActiveImageFile.cpp