SIBR: sibr::MultiViewBase Class Reference
sibr::MultiViewBase Class Reference
sibr_view
MultiViewBase is designed to provide more flexibility and with a multi-windows system in mind.
#include <MultiViewManager.hpp>
Classes
struct BasicSubView
Specialization of Subview for basic views.
struct IBRSubView
Specialization of Subview for views using a render mode (IBR views mainly).
struct SubView
Internal representation of a subview.
Public Types
typedef std::function< void(sibr::ViewBase::Ptr &, sibr::Input &, const sibr::Viewport &, const float)> ViewUpdateFunc
Update callback for a standard view. Passes the view pointer, the correct input state, and the correct viewport.
typedef std::function< sibr::InputCamera(sibr::ViewBase::Ptr &, sibr::Input &, const sibr::Viewport &, const float)> IBRViewUpdateFunc
Update callback for an IBR view, see main description for the return value.
typedef std::function< void(sibr::ViewBase::Ptr &, const sibr::Viewport &, const IRenderTarget::Ptr &)> AdditionalRenderFunc
Additional render callback for a subview.
Public Member Functions
MultiViewBase (const Vector2i &defaultViewRes={ 800, 600 })
virtual void onUpdate (Input &input)
Update subviews and the MultiViewBase.
virtual void onRender (Window &win)
Render the content of the MultiViewBase.
virtual void onGui (Window &win)
Render additional gui.
void addSubView (const std::string &title, ViewBase::Ptr view, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register a standard subview (for instance a SceneDebugView).
void addSubView (const std::string &title, ViewBase::Ptr view, const ViewUpdateFunc updateFunc, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register a standard subview (for instance a SceneDebugView).
void addIBRSubView (const std::string &title, ViewBase::Ptr view, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register an IBR subview (for instance an ULRView).
void addIBRSubView (const std::string &title, ViewBase::Ptr view, const IBRViewUpdateFunc updateFunc, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register an IBR subview (for instance an ULRView).
void addSubMultiView (const std::string &title, MultiViewBase::Ptr multiview)
Add another multi-view system as a subsystem of this one.
ViewBase::Ptr & getIBRSubView (const std::string &title)
Viewport & getIBRSubViewport (const std::string &title)
ViewBase::Ptr removeSubView (const std::string &title)
Unregister a subview.
void renderingMode (const IRenderingMode::Ptr &mode)
Change the rendering mode.
void setDefaultViewResolution (const Vector2i &size)
Define the default rendering and display size for new subviews.
const Viewport getViewport (void) const
Returns the default viewport used for subviews rendering.
const float & deltaTime () const
Returns the last frame time.
void addCameraForView (const std::string &name, ICameraHandler::Ptr cameraHandler)
Add a camera handler that will automatically be updated and used by the MultiViewManager for the given subview.
void addAdditionalRenderingForView (const std::string &name, const AdditionalRenderFunc renderFunc)
Register a function performing additional rendering for a given subview, called by the MultiViewManager after calling onRender() on the subview.
int numSubViews () const
Count NOT recursively the number of subviews.
void mosaicLayout (const Viewport &vp)
Place all subviews on a regular grid in the given viewport.
void toggleSubViewsGUI ()
Toggle the display of sub-managers GUIs.
void setExportPath (const std::string &path)
Set the export path.
void captureView (const std::string &subviewName, const std::string &path="./screenshots", const std::string &filename="")
captures a View content into an image file.
Protected Member Functions
void addIBRSubView (const std::string &title, ViewBase::Ptr view, const IBRViewUpdateFunc updateFunc, const Vector2u &res, const ImGuiWindowFlags flags, const bool defaultFuncUsed)
Helper to add an IBR subview.
void renderSubView (SubView &subview)
Perform rendering for a given subview.
Static Protected Member Functions
static void captureView (const SubView &view, const std::string &path="./screenshots/", const std::string &filename="")
Capture a view as an image on disk.
Protected Attributes
IRenderingMode::Ptr _renderingMode = nullptr
Rendering mode.
std::map< std::string, BasicSubView > _subViews
Regular subviews.
std::map< std::string, IBRSubView > _ibrSubViews
IBR subviews.
std::map< std::string, std::shared_ptr< MultiViewBase > > _subMultiViews
Nested multi-views.
Vector2i _defaultViewResolution
Default view resolution.
std::string _exportPath
Capture output path.
std::vector< cv::Mat > _videoFrames
Video frames.
std::chrono::time_point< std::chrono::steady_clock > _timeLastFrame
Last frame time point.
float _deltaTime
Elapsed time.
bool _showSubViewsGui = true
Show the GUI of the subviews.
bool _onPause = false
Paused interaction and update.
Private Member Functions
SIBR_CLASS_PTR (MultiViewBase)
Detailed Description
MultiViewBase is designed to provide more flexibility and with a multi-windows system in mind.
Once a MultiViewBase is created, you can register standard and IBR subviews, providing additional functions for update and rendering if needed, along with support for ImGui interfaces. MultiViewBase will wrap those views and manage them on screen. To support legacy rendering modes and views, we introduce a distinction between standard subviews, that will be rendered through a call to onRender(Viewport&), and IBR subviews rendered through a onRenderIBR(rt, eye) call. This also means that after updating (via onUpdate) an IBR subview, you have to return the camera that will be used for the onRenderIBR call. Note: new IBR views don't have to implement this distinction.
Definition at line 45 of file MultiViewManager.hpp.
Member Typedef Documentation
AdditionalRenderFunc
typedef std::function<void(sibr::ViewBase::Ptr &, const sibr::Viewport&, const IRenderTarget::Ptr&)> sibr::MultiViewBase::AdditionalRenderFunc
Additional render callback for a subview.
Definition at line 56 of file MultiViewManager.hpp.
IBRViewUpdateFunc
typedef std::function<sibr::InputCamera(sibr::ViewBase::Ptr &, sibr::Input&, const sibr::Viewport&, const float)> sibr::MultiViewBase::IBRViewUpdateFunc
Update callback for an IBR view, see main description for the return value.
Definition at line 54 of file MultiViewManager.hpp.
ViewUpdateFunc
typedef std::function<void(sibr::ViewBase::Ptr &, sibr::Input&, const sibr::Viewport&, const float)> sibr::MultiViewBase::ViewUpdateFunc
Update callback for a standard view. Passes the view pointer, the correct input state, and the correct viewport.
Definition at line 52 of file MultiViewManager.hpp.
Constructor & Destructor Documentation
MultiViewBase()
sibr::MultiViewBase::MultiViewBase (const Vector2i & defaultViewRes = { 800, 600 })
Definition at line 7 of file MultiViewManager.cpp.
References _deltaTime, _exportPath, _timeLastFrame, renderingMode(), and setDefaultViewResolution().
Member Function Documentation
addAdditionalRenderingForView()
void sibr::MultiViewBase::addAdditionalRenderingForView (const std::string & name, const AdditionalRenderFunc renderFunc)
Register a function performing additional rendering for a given subview, called by the MultiViewManager after calling onRender() on the subview.
Parameters
name the name of the subview to which the function should be associated.
renderFunc the function performing additional rendering..
Definition at line 281 of file MultiViewManager.cpp.
References _ibrSubViews, _subViews, and SIBR_WRG.
addCameraForView()
void sibr::MultiViewBase::addCameraForView (const std::string & name, ICameraHandler::Ptr cameraHandler)
Add a camera handler that will automatically be updated and used by the MultiViewManager for the given subview.
Parameters
name the name of the subview to which the camera should be associated.
cameraHandler a pointer to the camera handler to register.
Definition at line 265 of file MultiViewManager.cpp.
References _ibrSubViews, _subViews, and SIBR_WRG.
Referenced by legacyV1main(), legacyV2main(), and main().
addIBRSubView() [1/3]
void sibr::MultiViewBase::addIBRSubView (const std::string & title, ViewBase::Ptr view, const IBRViewUpdateFunc updateFunc, const Vector2u & res, const ImGuiWindowFlags flags, const bool defaultFuncUsed) protected
Helper to add an IBR subview.
Parameters
title the title of the view.
view a pointer to the view.
updateFunc the function that will be called to update your view. It will pass you the view, the correct Input (mouse position from 0,0 in the top left corner, key presses and mouse clicks only if the cursor is over the view), and the Viewport in the OS window. You should return the camera to use during rendering.
res a custom resolution used for the internal rendering. If null, the default value is used.
flags ImGui_WindowFlags to pass to the internal window manager.
defaultFuncUsed a flag denoting if the default function had to be used
Definition at line 133 of file MultiViewManager.cpp.
References _defaultViewResolution, _ibrSubViews, sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), ImGui::GetTitleBarHeight(), and SIBR_CLAMP_UVS.
addIBRSubView() [2/3]
void sibr::MultiViewBase::addIBRSubView (const std::string & title, ViewBase::Ptr view, const IBRViewUpdateFunc updateFunc, const Vector2u & res = Vector2u(0, 0), const ImGuiWindowFlags flags = 0)
Register an IBR subview (for instance an ULRView).
It will be rendered via a call to onRenderIBR(rt,cam,dst).
Parameters
title the title of the view.
view a pointer to the view.
updateFunc the function that will be called to update your view. It will pass you the view, the correct Input (mouse position from 0,0 in the top left corner, key presses and mouse clicks only if the cursor is over the view), and the Viewport in the OS window. You should return the camera to use during rendering.
res a custom resolution used for the internal rendering. If null, the default value is used.
flags ImGui_WindowFlags to pass to the internal window manager.
Definition at line 159 of file MultiViewManager.cpp.
References addIBRSubView().
addIBRSubView() [3/3]
void sibr::MultiViewBase::addIBRSubView (const std::string & title, ViewBase::Ptr view, const Vector2u & res = Vector2u(0, 0), const ImGuiWindowFlags flags = 0)
Register an IBR subview (for instance an ULRView).
It will be rendered via a call to onRenderIBR(rt,cam,dst).
Parameters
title the title of the view.
view a pointer to the view.
res a custom resolution used for the internal rendering. If null, the default value is used.
flags ImGui_WindowFlags to pass to the internal window manager.
Definition at line 150 of file MultiViewManager.cpp.
Referenced by addIBRSubView(), legacyV1main(), legacyV2main(), and main().
addSubMultiView()
void sibr::MultiViewBase::addSubMultiView (const std::string & title, MultiViewBase::Ptr multiview)
Add another multi-view system as a subsystem of this one.
Parameters
title a name for the multiview
multiview the multiview system to add as a subview
Definition at line 164 of file MultiViewManager.cpp.
References _subMultiViews.
addSubView() [1/2]
void sibr::MultiViewBase::addSubView (const std::string & title, ViewBase::Ptr view, const Vector2u & res = Vector2u(0,0), const ImGuiWindowFlags flags = 0)
Register a standard subview (for instance a SceneDebugView).
It will be rendered via a call to onRender(Viewport) in an implicit rendertarget managed by the MultiViewBase.
Parameters
title the title of the view.
view a pointer to the view.
res a custom resolution used for the internal rendering and display. If null, the default value is used.
flags ImGui_WindowFlags to pass to the internal window manager.
Definition at line 113 of file MultiViewManager.cpp.
Referenced by sibr::DatasetView::DatasetView(), legacyV1main(), legacyV2main(), and main().
addSubView() [2/2]
void sibr::MultiViewBase::addSubView (const std::string & title, ViewBase::Ptr view, const ViewUpdateFunc updateFunc, const Vector2u & res = Vector2u(0, 0), const ImGuiWindowFlags flags = 0)
Register a standard subview (for instance a SceneDebugView).
It will be rendered via a call to onRender(Viewport) in an implicit rendertarget managed by the MultiViewBase.
Parameters
title the title of the view.
view a pointer to the view.
updateFunc the function that will be called to update your view. It will pass you the view, the correct Input (mouse position from 0,0 in the top left corner, key presses and mouse clicks only if the cursor is over the view), and the Viewport in the OS window.
res a custom resolution used for the internal rendering and display. If null, the default value is used.
flags ImGui_WindowFlags to pass to the internal window manager.
Definition at line 122 of file MultiViewManager.cpp.
References _defaultViewResolution, _subViews, sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), ImGui::GetTitleBarHeight(), and SIBR_CLAMP_UVS.
captureView() [1/2]
void sibr::MultiViewBase::captureView (const std::string & subviewName, const std::string & path = "./screenshots", const std::string & filename = "")
captures a View content into an image file.
Parameters
subviewName a string with the name of the subview.
path the path to save the output.
filename the name of the output file, needs to have an OpenCV compatible file type.
Definition at line 299 of file MultiViewManager.cpp.
References _ibrSubViews, _subViews, and SIBR_WRG.
Referenced by sibr::MultiViewManager::onGui().
captureView() [2/2]
void sibr::MultiViewBase::captureView (const SubView & view, const std::string & path = "./screenshots/", const std::string & filename = "") static protected
Capture a view as an image on disk.
Parameters
view the view to capture
path the destination direcotry path
filename an optional filename, a timestamp will be appended
Note
if the filename is empty, the name of the view is used, with a timestamp appended.
Definition at line 312 of file MultiViewManager.cpp.
References sibr::makeDirectory(), sibr::MultiViewBase::SubView::rt, sibr::Image< T_Type, T_NumComp >::save(), sibr::timestamp(), and sibr::MultiViewBase::SubView::view.
deltaTime()
const float& sibr::MultiViewBase::deltaTime () const inline
Returns the last frame time.
Returns
the last frame time.
Definition at line 190 of file MultiViewManager.hpp.
getIBRSubView()
ViewBase::Ptr & sibr::MultiViewBase::getIBRSubView (const std::string & title)
Parameters
title
Returns
Return viewbase associated with title, will EXIT_ERROR if no view found
Note
This covers both basic and IBR subviews.
Todo:
Rename without the IBR prefix
Definition at line 169 of file MultiViewManager.cpp.
References _ibrSubViews, _subViews, and SIBR_ERR.
Referenced by legacyV1main(), legacyV2main(), and main().
getIBRSubViewport()
Viewport & sibr::MultiViewBase::getIBRSubViewport (const std::string & title)
Parameters
title
Returns
the Viewport associated with title, will EXIT_ERROR if no viewport found
Note
This covers both basic and IBR subviews.
Todo:
Rename without the IBR prefix
Definition at line 183 of file MultiViewManager.cpp.
References _ibrSubViews, _subViews, and SIBR_ERR.
getViewport()
const Viewport sibr::MultiViewBase::getViewport (void) const
Returns the default viewport used for subviews rendering.
Returns
the current default subview viewport
Definition at line 260 of file MultiViewManager.cpp.
References _defaultViewResolution.
mosaicLayout()
void sibr::MultiViewBase::mosaicLayout (const Viewport & vp)
Place all subviews on a regular grid in the given viewport.
Parameters
vp the region in which the views should be layed out.
Definition at line 334 of file MultiViewManager.cpp.
References _ibrSubViews, _subMultiViews, _subViews, sibr::Viewport::finalBottom(), sibr::Viewport::finalLeft(), sibr::Viewport::finalRight(), sibr::Viewport::finalTop(), ImGui::GetTitleBarHeight(), and numSubViews().
Referenced by sibr::MultiViewManager::onGui().
numSubViews()
int sibr::MultiViewBase::numSubViews () const
Count NOT recursively the number of subviews.
Definition at line 294 of file MultiViewManager.cpp.
References _ibrSubViews, _subMultiViews, and _subViews.
Referenced by mosaicLayout().
onGui()
void sibr::MultiViewBase::onGui (Window & win) virtual
Render additional gui.
Parameters
win The OS window into which the rendering should be performed.
Reimplemented in sibr::MultiViewManager, and sibr::DatasetView.
Definition at line 109 of file MultiViewManager.cpp.
Referenced by sibr::MultiViewManager::onGui().
onRender()
void sibr::MultiViewBase::onRender (Window & win) virtual
Render the content of the MultiViewBase.
Parameters
win The OS window into which the rendering should be performed.
Reimplemented in sibr::MultiViewManager, and sibr::DatasetView.
Definition at line 73 of file MultiViewManager.cpp.
References _ibrSubViews, _showSubViewsGui, _subMultiViews, _subViews, and renderSubView().
Referenced by sibr::DatasetView::onRender(), and sibr::MultiViewManager::onRender().
onUpdate()
void sibr::MultiViewBase::onUpdate (Input & input) virtual
Update subviews and the MultiViewBase.
Parameters
input The input state to use.
Reimplemented in sibr::MultiViewManager, and sibr::DatasetView.
Definition at line 20 of file MultiViewManager.cpp.
References _deltaTime, _ibrSubViews, _onPause, _subMultiViews, _subViews, _timeLastFrame, sibr::MultiViewBase::IBRSubView::cam, sibr::MultiViewBase::IBRSubView::defaultUpdateFunc, sibr::MultiViewBase::SubView::handler, sibr::InputState< TNbState, TEnum >::isActivated(), sibr::InputState< TNbState, TEnum >::isPressed(), sibr::Input::key(), sibr::Key::LeftAlt, sibr::Key::LeftControl, sibr::Key::P, sibr::Input::subInput(), sibr::MultiViewBase::IBRSubView::updateFunc, sibr::MultiViewBase::SubView::view, and sibr::MultiViewBase::SubView::viewport.
Referenced by sibr::DatasetView::onUpdate(), and sibr::MultiViewManager::onUpdate().
removeSubView()
ViewBase::Ptr sibr::MultiViewBase::removeSubView (const std::string & title)
Unregister a subview.
Parameters
title the title of the view to remove.
Returns
the view removed from the MultiViewManager.
Definition at line 238 of file MultiViewManager.cpp.
References _ibrSubViews, _subViews, and SIBR_WRG.
renderingMode()
void sibr::MultiViewBase::renderingMode (const IRenderingMode::Ptr & mode)
Change the rendering mode.
Parameters
mode The rendering mode to use.
Definition at line 255 of file MultiViewManager.cpp.
References _renderingMode.
Referenced by MultiViewBase(), and sibr::MultiViewManager::MultiViewManager().
renderSubView()
void sibr::MultiViewBase::renderSubView (SubView & subview) protected
Perform rendering for a given subview.
Parameters
subview the subview to render
Definition at line 197 of file MultiViewManager.cpp.
References _onPause, _renderingMode, _videoFrames, sibr::Viewport::bind(), sibr::MultiViewBase::SubView::flags, sibr::MultiViewBase::SubView::handler, sibr::MultiViewBase::SubView::render(), sibr::MultiViewBase::SubView::renderFunc, sibr::MultiViewBase::SubView::rt, sibr::Image< T_Type, T_NumComp >::save(), sibr::MultiViewBase::SubView::shouldUpdateLayout, sibr::showImGuiWindow(), sibr::Image< T_Type, T_NumComp >::toOpenCVBGR(), sibr::MultiViewBase::SubView::view, and sibr::MultiViewBase::SubView::viewport.
Referenced by onRender().
setDefaultViewResolution()
void sibr::MultiViewBase::setDefaultViewResolution (const Vector2i & size) inline
Define the default rendering and display size for new subviews.
Parameters
size the default size to use.
Definition at line 420 of file MultiViewManager.hpp.
References _defaultViewResolution.
Referenced by MultiViewBase(), and sibr::MultiViewManager::MultiViewManager().
setExportPath()
void sibr::MultiViewBase::setExportPath (const std::string & path)
Set the export path.
Parameters
path path to the directory to use.
Definition at line 382 of file MultiViewManager.cpp.
References _exportPath, and sibr::makeDirectory().
SIBR_CLASS_PTR()
sibr::MultiViewBase::SIBR_CLASS_PTR (MultiViewBase) private
toggleSubViewsGUI()
void sibr::MultiViewBase::toggleSubViewsGUI ()
Toggle the display of sub-managers GUIs.
Definition at line 373 of file MultiViewManager.cpp.
References _showSubViewsGui, and _subMultiViews.
Referenced by sibr::MultiViewManager::toggleGUI().
Member Data Documentation
_defaultViewResolution
Vector2i sibr::MultiViewBase::_defaultViewResolution protected
Default view resolution.
Definition at line 364 of file MultiViewManager.hpp.
Referenced by addIBRSubView(), addSubView(), getViewport(), and setDefaultViewResolution().
_deltaTime
float sibr::MultiViewBase::_deltaTime protected
Elapsed time.
Definition at line 370 of file MultiViewManager.hpp.
Referenced by MultiViewBase(), and onUpdate().
_exportPath
std::string sibr::MultiViewBase::_exportPath protected
Capture output path.
Definition at line 366 of file MultiViewManager.hpp.
Referenced by MultiViewBase(), sibr::MultiViewManager::onGui(), and setExportPath().
_ibrSubViews
std::map<std::string, IBRSubView> sibr::MultiViewBase::_ibrSubViews protected
IBR subviews.
Definition at line 361 of file MultiViewManager.hpp.
Referenced by addAdditionalRenderingForView(), addCameraForView(), addIBRSubView(), captureView(), getIBRSubView(), getIBRSubViewport(), mosaicLayout(), numSubViews(), sibr::MultiViewManager::onGui(), onRender(), onUpdate(), and removeSubView().
_onPause
bool sibr::MultiViewBase::_onPause = false protected
Paused interaction and update.
Definition at line 372 of file MultiViewManager.hpp.
Referenced by sibr::MultiViewManager::onGui(), onUpdate(), and renderSubView().
_renderingMode
IRenderingMode::Ptr sibr::MultiViewBase::_renderingMode = nullptr protected
Rendering mode.
Definition at line 359 of file MultiViewManager.hpp.
Referenced by renderingMode(), and renderSubView().
_showSubViewsGui
bool sibr::MultiViewBase::_showSubViewsGui = true protected
Show the GUI of the subviews.
Definition at line 371 of file MultiViewManager.hpp.
Referenced by onRender(), and toggleSubViewsGUI().
_subMultiViews
std::map<std::string, std::shared_ptr<MultiViewBase> > sibr::MultiViewBase::_subMultiViews protected
Nested multi-views.
Definition at line 362 of file MultiViewManager.hpp.
Referenced by addSubMultiView(), mosaicLayout(), numSubViews(), onRender(), onUpdate(), and toggleSubViewsGUI().
_subViews
std::map<std::string, BasicSubView> sibr::MultiViewBase::_subViews protected
Regular subviews.
Definition at line 360 of file MultiViewManager.hpp.
Referenced by addAdditionalRenderingForView(), addCameraForView(), addSubView(), captureView(), sibr::DatasetView::getGridView(), getIBRSubView(), getIBRSubViewport(), sibr::DatasetView::getMeshView(), mosaicLayout(), numSubViews(), sibr::MultiViewManager::onGui(), onRender(), onUpdate(), and removeSubView().
_timeLastFrame
std::chrono::time_point<std::chrono::steady_clock> sibr::MultiViewBase::_timeLastFrame protected
Last frame time point.
Definition at line 369 of file MultiViewManager.hpp.
Referenced by MultiViewBase(), and onUpdate().
_videoFrames
std::vector<cv::Mat> sibr::MultiViewBase::_videoFrames protected
Video frames.
Definition at line 367 of file MultiViewManager.hpp.
Referenced by sibr::MultiViewManager::onGui(), and renderSubView().
The documentation for this class was generated from the following files:
src/core/view/MultiViewManager.hpp
src/core/view/MultiViewManager.cpp