SIBR: sibr::PointShader Class Reference
sibr::PointShader Class Reference
sibr_view
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
#include <MultiMeshManager.hpp>
Public Member Functions
void initShader (const std::string &name, const std::string &vert, const std::string &frag, const std::string &geom="") override
Initialize the shader.
virtual void setUniforms (const Camera &eye, const MeshData &data) override
virtual void render (const Camera &eye, const MeshData &data) override
Render using the passed information.
Protected Attributes
GLuniform< int > radius
Point screenspace radius.
Protected Attributes inherited from sibr::ColorMeshShader
GLuniform< Vector3f > user_color
user-defined constant color.
Protected Attributes inherited from sibr::ShaderAlphaMVP
GLShader shader
Base shader object.
GLuniform< Matrix4f > mvp
MVP matrix.
GLuniform< float > alpha = 1.0
Opacity.
Detailed Description
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
Adds a point size.
See also
ShaderAlphaMVP
Definition at line 79 of file MultiMeshManager.hpp.
Member Function Documentation
initShader()
void sibr::PointShader::initShader (const std::string & name, const std::string & vert, const std::string & frag, const std::string & geom = "") override virtual
Initialize the shader.
Parameters
name the shader name
vert the vertex shader content
frag the fragment shader ocntent
geom the geometry shader content
Reimplemented from sibr::ColorMeshShader.
Definition at line 250 of file MultiMeshManager.cpp.
References sibr::GLuniform< T >::init(), sibr::ColorMeshShader::initShader(), radius, and sibr::ShaderAlphaMVP::shader.
Referenced by sibr::MultiMeshManager::initShaders().
render()
void sibr::PointShader::render (const Camera & eye, const MeshData & data) override virtual
Render using the passed information.
Parameters
eye the current viewpoint
data the mesh display options
Reimplemented from sibr::ShaderAlphaMVP.
Definition at line 262 of file MultiMeshManager.cpp.
References sibr::ShaderAlphaMVP::render().
Referenced by sibr::MultiMeshManager::renderMeshes().
setUniforms()
void sibr::PointShader::setUniforms (const Camera & eye, const MeshData & data) override virtual
Reimplemented from sibr::ColorMeshShader.
Definition at line 256 of file MultiMeshManager.cpp.
References radius, sibr::MeshData::radius, sibr::GLuniform< T >::set(), and sibr::ColorMeshShader::setUniforms().
Member Data Documentation
radius
GLuniform<int> sibr::PointShader::radius protected
Point screenspace radius.
Definition at line 102 of file MultiMeshManager.hpp.
Referenced by initShader(), and setUniforms().
The documentation for this class was generated from the following files:
src/core/view/MultiMeshManager.hpp
src/core/view/MultiMeshManager.cpp