SIBR: sibr::CopyRenderer Class Reference
sibr::CopyRenderer Class Reference
sibr_renderer
Copy the content of an input texture to another rendertarget or to the window.
#include <CopyRenderer.hpp>
Public Types
typedef std::shared_ptr< CopyRenderer > Ptr
Public Member Functions
CopyRenderer (const std::string &vertFile=sibr::getShadersDirectory("core")+"/noproj.vert", const std::string &fragFile=sibr::getShadersDirectory("core")+"/copy.frag")
Constructor.
void process (uint textureID, IRenderTarget &dst, bool disableTest=true)
Copy input texture to the output texture, copy also the input alpha into depth.
void copyToWindow (uint textureID, Window &dst)
Copy input texture to a window.
bool & flip ()
Private Attributes
GLShader _shader
Copy shader.
GLuniform< bool > _flip = false
Flip the texture when copying.
Detailed Description
Copy the content of an input texture to another rendertarget or to the window.
If you need a basic copy, prefer using blit.
See also
sibr::blit
Definition at line 16 of file CopyRenderer.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<CopyRenderer> sibr::CopyRenderer::Ptr
Definition at line 19 of file CopyRenderer.hpp.
Constructor & Destructor Documentation
CopyRenderer()
sibr::CopyRenderer::CopyRenderer (const std::string & vertFile = sibr::getShadersDirectory("core") + "/noproj.vert", const std::string & fragFile = sibr::getShadersDirectory("core") + "/copy.frag")
Constructor.
You can specify custom shaders, refer to noproj.vert and copy.frag for examples.
Parameters
vertFile pah to the vertex shader file
fragFile pah to the fragment shader file
Definition at line 5 of file CopyRenderer.cpp.
References _flip, _shader, sibr::GLuniform< T >::init(), sibr::GLShader::init(), and sibr::loadFile().
Member Function Documentation
copyToWindow()
void sibr::CopyRenderer::copyToWindow (uint textureID, Window & dst)
Copy input texture to a window.
Parameters
textureID the texture to copy
dst the destination window
Definition at line 34 of file CopyRenderer.cpp.
References _shader, sibr::GLShader::begin(), sibr::GLShader::end(), and sibr::RenderUtility::renderScreenQuad().
flip()
bool& sibr::CopyRenderer::flip () inline
Returns
option to flip the texture when copying.
Definition at line 47 of file CopyRenderer.hpp.
process()
void sibr::CopyRenderer::process (uint textureID, IRenderTarget & dst, bool disableTest = true)
Copy input texture to the output texture, copy also the input alpha into depth.
Parameters
textureID the texture to copy
dst the destination
disableTest disable depth testing (depth won't be written)
Definition at line 14 of file CopyRenderer.cpp.
References _flip, _shader, sibr::GLShader::begin(), ibr_preprocess_rc_to_sibr::dst, sibr::GLShader::end(), sibr::RenderUtility::renderScreenQuad(), and sibr::GLuniform< T >::send().
Member Data Documentation
_flip
GLuniform<bool> sibr::CopyRenderer::_flip = false private
Flip the texture when copying.
Definition at line 52 of file CopyRenderer.hpp.
Referenced by CopyRenderer(), and process().
_shader
GLShader sibr::CopyRenderer::_shader private
Copy shader.
Definition at line 51 of file CopyRenderer.hpp.
Referenced by CopyRenderer(), copyToWindow(), and process().
The documentation for this class was generated from the following files:
src/core/renderer/CopyRenderer.hpp
src/core/renderer/CopyRenderer.cpp