SIBR: sibr::UIShortcuts Class Reference
sibr::UIShortcuts Class Reference
sibr_view
Register and display keyboard shortcuts.
#include <UIShortcuts.hpp>
Public Member Functions
void list (void)
Print all registered shortcuts.
void add (const std::string &shortcut, const char *desc)
Register a shortcut.
Static Public Member Functions
static UIShortcuts & global (void)
Singleton.
Private Attributes
std::unordered_map< std::string, const char * > _shortcuts
List of shortcuts.
Detailed Description
Register and display keyboard shortcuts.
Todo:
The system should be more robust for collision detection.
Definition at line 12 of file UIShortcuts.hpp.
Member Function Documentation
add()
void sibr::UIShortcuts::add (const std::string & shortcut, const char * desc)
Register a shortcut.
Parameters
shortcut the shortcut keys
desc the description
Definition at line 27 of file UIShortcuts.cpp.
References _shortcuts, and SIBR_ERR.
Referenced by sibr::FPSCamera::FPSCamera(), sibr::InteractiveCameraHandler::InteractiveCameraHandler(), and sibr::Orbit::Orbit().
global()
UIShortcuts & sibr::UIShortcuts::global (void) static
Singleton.
Definition at line 9 of file UIShortcuts.cpp.
Referenced by sibr::FPSCamera::FPSCamera(), sibr::InteractiveCameraHandler::InteractiveCameraHandler(), and sibr::Orbit::Orbit().
list()
void sibr::UIShortcuts::list (void)
Print all registered shortcuts.
Definition at line 15 of file UIShortcuts.cpp.
References _shortcuts, and SIBR_LOG.
Member Data Documentation
_shortcuts
std::unordered_map<std::string, const char*> sibr::UIShortcuts::_shortcuts private
List of shortcuts.
Definition at line 30 of file UIShortcuts.hpp.
Referenced by add(), and list().
The documentation for this class was generated from the following files:
src/core/view/UIShortcuts.hpp
src/core/view/UIShortcuts.cpp