SIBR: sibr::ULRV2View Class Reference
sibr::ULRV2View Class Reference
View associated to ULRRenderer v2, providing interface and options.
#include <ULRV2View.hpp>
Public Member Functions
ULRV2View (const sibr::BasicIBRScene::Ptr &ibrScene, uint render_w, uint render_h)
Constructor.
~ULRV2View ()
Destructor.
virtual void onRenderIBR (sibr::IRenderTarget &dst, const sibr::Camera &eye)
Render using the ULR algorithm.
virtual void onUpdate (Input &input)
Update state absed on user inputs.
virtual void onGUI () override
Display GUI.
virtual std::vector< uint > chosen_cameras (const sibr::Camera &eye)
Select input cameras to use for rendering.
virtual std::vector< uint > chosen_camerasNew (const sibr::Camera &eye)
Select input cameras to use for rendering, based only on distance.
virtual std::vector< uint > chosen_cameras_angdist (const sibr::Camera &eye)
Select input cameras to use for rendering.
void altMesh (std::shared_ptr< sibr::Mesh > m)
Set the altMesh and use instead of scene proxy.
void doOccl (bool val)
Toggle occlusion testing.
std::shared_ptr< sibr::Mesh > altMesh ()
void setNumBlend (short int dist, short int angle)
Set the number of cmaeras to select for blending.
void inputRTs (const std::vector< std::shared_ptr< RenderTargetRGBA32F > > &iRTs)
Set the input RGBD textures.
void setMasks (const std::vector< RenderTargetLum::Ptr > &masks)
Set the masks for ignoring some regions of the input images.
void loadMasks (const sibr::BasicIBRScene::Ptr &ibrScene, int w, int h, const std::string &maskDir="", const std::string &preFileName="", const std::string &postFileName="")
Load masks from disk.
void setRenderMode (RenderMode mode)
Set the camera selection mode.
RenderMode getRenderMode () const
void setSingleViewId (int id)
Set the view ID when in single view mode.
int getSingleViewId (void) const
void noPoissonBlend (bool val)
Toggle poisson blending.
bool noPoissonBlend () const
void computeVisibilityMap (const sibr::ImageL32F &depthMap, sibr::ImageRGBA &out)
Compute soft visibility map.
const std::shared_ptr< sibr::BasicIBRScene > & getScene () const
Public Member Functions inherited from sibr::ViewBase
ViewBase (const unsigned int w=720, const unsigned int h=480)
Constructor.
virtual ~ViewBase ()=default
Destructor.
virtual void onRender (Window &win)
Render content in a window.
virtual void onRender (const Viewport &vpRender)
Render content in the currently bound RT, using a specific viewport.
virtual void onUpdate (Input &input, const Viewport &vp)
Update state based on user input.
virtual void preRender (RenderTargetRGB &prev)
Legacy: Used to mix with previous pass.
virtual void whichRT (uint i)
Legacy: Set the internal RT to use.
virtual uint whichRT (void)
Legacy:
void setResolution (const Vector2i &size)
Set the view resolution.
const Vector2i & getResolution (void) const
void active (bool act)
Toggle view status.
bool active ()
void setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
bool isFocused (void) const
void setName (const std::string &name)
Define the name of the view (used for disambiguation of GUI, etc.).
const std::string & name () const
Public Attributes
ULRV2Renderer::Ptr _ulr
ULRV2 renderer.
PoissonRenderer::Ptr _poisson
Poisson filling renderer.
Protected Attributes
std::shared_ptr< sibr::BasicIBRScene > _scene
the current scene.
std::shared_ptr< sibr::Mesh > _altMesh
For the cases when using a different mesh than the scene.
int _numDistUlr
int _numAnglUlr
Number of cameras to select for each criterion.
std::vector< std::shared_ptr< RenderTargetRGBA32F > > _inputRTs
input RTs – usually RGB but can be alpha or other
bool _noPoissonBlend = false
Runtime status of the poisson blend.
RenderTargetRGBA::Ptr _blendRT
ULR destination RT.
RenderTargetRGBA::Ptr _poissonRT
Poisson filling destination RT.
RenderMode _renderMode
Current camera selection mode.
int _singleCamId
Selected camera in single view mode.
bool testAltlULRShader
TT: to switch with alternate shader with tab.
Protected Attributes inherited from sibr::ViewBase
uint _whichRT
Selected RT id.
std::vector< RenderTargetLum::Ptr > _masks
Rendering masks that can beused by some views/renderers.
bool _active = true
Is the view active.
Vector2i _resolution
View resolution.
bool _focus = false
Is the view focused.
std::string _name = ""
View name.
Private Types
enum RenderMode { RenderMode::NORMAL = 0, RenderMode::ONLY_ONE_CAM = 1, RenderMode::LEAVE_ONE_OUT = 2 }
Camera selection mode.
Private Member Functions
SIBR_CLASS_PTR (ULRV2View)
Additional Inherited Members
Public Types inherited from sibr::ViewBase
typedef std::shared_ptr< ViewBase > Ptr
Detailed Description
View associated to ULRRenderer v2, providing interface and options.
Definition at line 15 of file ULRV2View.hpp.
Member Enumeration Documentation
RenderMode
enum sibr::ULRV2View::RenderMode strong private
Camera selection mode.
Enumerator
NORMAL
ONLY_ONE_CAM
LEAVE_ONE_OUT
Definition at line 20 of file ULRV2View.hpp.
Constructor & Destructor Documentation
ULRV2View()
sibr::ULRV2View::ULRV2View (const sibr::BasicIBRScene::Ptr & ibrScene, uint render_w, uint render_h)
Constructor.
Parameters
ibrScene the scene
render_w rendering width
render_h rendering height
Definition at line 16 of file ULRV2View.cpp.
References _altMesh, _blendRT, _inputRTs, _numAnglUlr, _numDistUlr, _poisson, _poissonRT, _ulr, SIBR_CLAMP_UVS, and testAltlULRShader.
~ULRV2View()
sibr::ULRV2View::~ULRV2View ()
Destructor.
Definition at line 11 of file ULRV2View.cpp.
References _altMesh.
Member Function Documentation
altMesh() [1/2]
std::shared_ptr<sibr::Mesh> sibr::ULRV2View::altMesh () inline
Returns
a pointer to the alt mesh if it exists
Definition at line 77 of file ULRV2View.hpp.
altMesh() [2/2]
void sibr::ULRV2View::altMesh (std::shared_ptr< sibr::Mesh > m) inline
Set the altMesh and use instead of scene proxy.
Parameters
m mesh to use
Definition at line 69 of file ULRV2View.hpp.
chosen_cameras()
std::vector< uint > sibr::ULRV2View::chosen_cameras (const sibr::Camera & eye) virtual
Select input cameras to use for rendering.
Parameters
eye the current viewpoint
Returns
a list of camera indices.
Definition at line 172 of file ULRV2View.cpp.
References _numAnglUlr, _numDistUlr, _scene, sibr::Camera::dir(), sibr::distance(), sibr::dot(), sibr::InputCamera::isActive(), sibr::Camera::position(), and SIBR_ASSERT.
chosen_cameras_angdist()
std::vector< uint > sibr::ULRV2View::chosen_cameras_angdist (const sibr::Camera & eye) virtual
Select input cameras to use for rendering.
Parameters
eye the current viewpoint
Returns
a list of camera indices.
Definition at line 211 of file ULRV2View.cpp.
References _numAnglUlr, _numDistUlr, _scene, sibr::Camera::dir(), sibr::dot(), and sibr::Camera::position().
Referenced by onRenderIBR().
chosen_camerasNew()
std::vector< uint > sibr::ULRV2View::chosen_camerasNew (const sibr::Camera & eye) virtual
Select input cameras to use for rendering, based only on distance.
Parameters
eye the current viewpoint
Returns
a list of camera indices.
Definition at line 256 of file ULRV2View.cpp.
References _numDistUlr, _scene, and sibr::Camera::position().
computeVisibilityMap()
void sibr::ULRV2View::computeVisibilityMap (const sibr::ImageL32F & depthMap, sibr::ImageRGBA & out)
Compute soft visibility map.
Parameters
depthMap view depth map
out will contain the soft visibility map
Definition at line 140 of file ULRV2View.cpp.
References sibr::convertL32FtoRGBA(), sibr::distance(), sibr::Image< T_Type, T_NumComp >::fromOpenCV(), sibr::Image< T_Type, T_NumComp >::h(), sibr::Image< T_Type, T_NumComp >::isInRange(), sibr::Image< T_Type, T_NumComp >::toOpenCVnonConst(), and sibr::Image< T_Type, T_NumComp >::w().
doOccl()
void sibr::ULRV2View::doOccl (bool val) inline
Toggle occlusion testing.
Parameters
val should occlusion testing be performed
Definition at line 74 of file ULRV2View.hpp.
getRenderMode()
RenderMode sibr::ULRV2View::getRenderMode () const inline
Returns
the camera selection mode.
Definition at line 115 of file ULRV2View.hpp.
getScene()
const std::shared_ptr<sibr::BasicIBRScene>& sibr::ULRV2View::getScene () const inline
Returns
a pointer to the scene
Definition at line 138 of file ULRV2View.hpp.
getSingleViewId()
int sibr::ULRV2View::getSingleViewId (void) const inline
Returns
the current selected camera ID in single view mode.
Definition at line 122 of file ULRV2View.hpp.
inputRTs()
void sibr::ULRV2View::inputRTs (const std::vector< std::shared_ptr< RenderTargetRGBA32F > > & iRTs) inline
Set the input RGBD textures.
Parameters
iRTs the new textures to use.
Definition at line 88 of file ULRV2View.hpp.
loadMasks()
void sibr::ULRV2View::loadMasks (const sibr::BasicIBRScene::Ptr & ibrScene, int w, int h, const std::string & maskDir = "", const std::string & preFileName = "", const std::string & postFileName = "")
Load masks from disk.
Parameters
ibrScene the scene
w resolution width
h resolution height
maskDir masks directory path
preFileName mask files prefix
postFileName mask files suffix and extension
Definition at line 294 of file ULRV2View.cpp.
References _ulr.
noPoissonBlend() [1/2]
bool sibr::ULRV2View::noPoissonBlend () const inline
Returns
true if pOisson blending is disabled.
Definition at line 129 of file ULRV2View.hpp.
noPoissonBlend() [2/2]
void sibr::ULRV2View::noPoissonBlend (bool val) inline
Toggle poisson blending.
Parameters
val if true, Poisson blending is disabled.
Definition at line 127 of file ULRV2View.hpp.
onGUI()
void sibr::ULRV2View::onGUI () override virtual
Display GUI.
Reimplemented from sibr::ViewBase.
Definition at line 107 of file ULRV2View.cpp.
References _noPoissonBlend, _numAnglUlr, _numDistUlr, _poisson, _renderMode, _scene, _singleCamId, _ulr, sibr::clamp(), sibr::Key::End, sibr::ViewBase::name(), ONLY_ONE_CAM, ImGui::PushScaledItemWidth(), and setNumBlend().
onRenderIBR()
void sibr::ULRV2View::onRenderIBR (sibr::IRenderTarget & dst, const sibr::Camera & eye) virtual
Render using the ULR algorithm.
Parameters
dst destination target
eye novel viewpoint
Reimplemented from sibr::ViewBase.
Definition at line 38 of file ULRV2View.cpp.
References _altMesh, _blendRT, _inputRTs, _noPoissonBlend, _poisson, _poissonRT, _renderMode, _scene, _singleCamId, _ulr, sibr::blit(), chosen_cameras_angdist(), ibr_preprocess_rc_to_sibr::dst, LEAVE_ONE_OUT, and ONLY_ONE_CAM.
onUpdate()
void sibr::ULRV2View::onUpdate (Input & input) virtual
Update state absed on user inputs.
Parameters
input the view input
Reimplemented from sibr::ViewBase.
Definition at line 94 of file ULRV2View.cpp.
References _ulr, sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Input::key(), sibr::Key::Tab, and testAltlULRShader.
setMasks()
void sibr::ULRV2View::setMasks (const std::vector< RenderTargetLum::Ptr > & masks)
Set the masks for ignoring some regions of the input images.
Parameters
masks the new masks
Definition at line 301 of file ULRV2View.cpp.
References _ulr.
setNumBlend()
void sibr::ULRV2View::setNumBlend (short int dist, short int angle)
Set the number of cmaeras to select for blending.
Parameters
dist number of cameras for the distance criterion
angle number of cameras for the angle criterion
Definition at line 282 of file ULRV2View.cpp.
References _numAnglUlr, _numDistUlr, _scene, and _ulr.
Referenced by onGUI().
setRenderMode()
void sibr::ULRV2View::setRenderMode (RenderMode mode) inline
Set the camera selection mode.
Parameters
mode the new mode.
Definition at line 113 of file ULRV2View.hpp.
setSingleViewId()
void sibr::ULRV2View::setSingleViewId (int id) inline
Set the view ID when in single view mode.
Parameters
id the camera id to use
Definition at line 120 of file ULRV2View.hpp.
SIBR_CLASS_PTR()
sibr::ULRV2View::SIBR_CLASS_PTR (ULRV2View) private
Member Data Documentation
_altMesh
std::shared_ptr<sibr::Mesh> sibr::ULRV2View::_altMesh protected
For the cases when using a different mesh than the scene.
Definition at line 147 of file ULRV2View.hpp.
Referenced by onRenderIBR(), ULRV2View(), and ~ULRV2View().
_blendRT
RenderTargetRGBA::Ptr sibr::ULRV2View::_blendRT protected
ULR destination RT.
Definition at line 154 of file ULRV2View.hpp.
Referenced by onRenderIBR(), and ULRV2View().
_inputRTs
std::vector<std::shared_ptr<RenderTargetRGBA32F> > sibr::ULRV2View::_inputRTs protected
input RTs – usually RGB but can be alpha or other
Definition at line 150 of file ULRV2View.hpp.
Referenced by onRenderIBR(), and ULRV2View().
_noPoissonBlend
bool sibr::ULRV2View::_noPoissonBlend = false protected
Runtime status of the poisson blend.
Definition at line 152 of file ULRV2View.hpp.
Referenced by onGUI(), and onRenderIBR().
_numAnglUlr
int sibr::ULRV2View::_numAnglUlr protected
Number of cameras to select for each criterion.
Definition at line 148 of file ULRV2View.hpp.
Referenced by chosen_cameras(), chosen_cameras_angdist(), onGUI(), setNumBlend(), and ULRV2View().
_numDistUlr
int sibr::ULRV2View::_numDistUlr protected
Definition at line 148 of file ULRV2View.hpp.
Referenced by chosen_cameras(), chosen_cameras_angdist(), chosen_camerasNew(), onGUI(), setNumBlend(), and ULRV2View().
_poisson
PoissonRenderer::Ptr sibr::ULRV2View::_poisson
Poisson filling renderer.
Definition at line 142 of file ULRV2View.hpp.
Referenced by onGUI(), onRenderIBR(), and ULRV2View().
_poissonRT
RenderTargetRGBA::Ptr sibr::ULRV2View::_poissonRT protected
Poisson filling destination RT.
Definition at line 155 of file ULRV2View.hpp.
Referenced by onRenderIBR(), and ULRV2View().
_renderMode
RenderMode sibr::ULRV2View::_renderMode protected
Current camera selection mode.
Definition at line 157 of file ULRV2View.hpp.
Referenced by onGUI(), and onRenderIBR().
_scene
std::shared_ptr<sibr::BasicIBRScene> sibr::ULRV2View::_scene protected
the current scene.
Definition at line 146 of file ULRV2View.hpp.
Referenced by chosen_cameras(), chosen_cameras_angdist(), chosen_camerasNew(), onGUI(), onRenderIBR(), and setNumBlend().
_singleCamId
int sibr::ULRV2View::_singleCamId protected
Selected camera in single view mode.
Definition at line 158 of file ULRV2View.hpp.
Referenced by onGUI(), and onRenderIBR().
_ulr
ULRV2Renderer::Ptr sibr::ULRV2View::_ulr
ULRV2 renderer.
Definition at line 141 of file ULRV2View.hpp.
Referenced by loadMasks(), onGUI(), onRenderIBR(), onUpdate(), setMasks(), setNumBlend(), and ULRV2View().
testAltlULRShader
bool sibr::ULRV2View::testAltlULRShader protected
TT: to switch with alternate shader with tab.
Definition at line 160 of file ULRV2View.hpp.
Referenced by onUpdate(), and ULRV2View().
The documentation for this class was generated from the following files:
src/projects/ulr/renderer/ULRV2View.hpp
src/projects/ulr/renderer/ULRV2View.cpp