SIBR: sibr::DrawUtilities Class Reference
sibr::DrawUtilities Class Reference
#include <ImagesGrid.hpp>
Public Member Functions
DrawUtilities ()
void baseRendering (const Mesh &mesh, Mesh::RenderMode mode, const Vector3f &color, const Vector2f &translation, const Vector2f &scaling, float alpha, const Viewport &vp)
void rectangle (const Vector3f &color, const Vector2f &tl, const Vector2f &br, bool fill, float alpha, const Viewport &vp)
void rectanglePixels (const Vector3f &color, const Vector2f &center, const Vector2f &diagonalPixs, bool fill, float alpha, const Viewport &vp)
void circle (const Vector3f &color, const Vector2f &center, float radius, bool fill, float alpha, const Vector2f &scaling=Vector3f(1, 1), int precision=50)
void circlePixels (const Vector3f &color, const Vector2f &center, float radius, bool fill, float alpha, const Vector2f &winSize, int precision=50)
void linePixels (const Vector3f &color, const Vector2f &ptA, const Vector2f &ptB, const Vector2f &winSize)
void image_grid (int num_imgs, uint texture, const Vector2f &grid, const Vector2f &tl, const Vector2f &br, int lod, bool flip_texture)
Public Attributes
GLShader baseShader
GLuniform< Vector3f > colorGL
GLuniform< float > alphaGL
GLuniform< Vector2f > scalingGL
GLuniform< Vector2f > translationGL
GLShader gridShader
GLuniform< Vector2f > gridGL
GLuniform< Vector2f > gridTopLeftGL
GLuniform< Vector2f > gridBottomRightGL
GLuniform< float > lodGL
GLuniform< int > numImgsGL
GLuniform< bool > flip_textureGL
Private Member Functions
void initBaseShader ()
void initGridShader ()
Detailed Description
Definition at line 12 of file ImagesGrid.hpp.
Constructor & Destructor Documentation
DrawUtilities()
sibr::DrawUtilities::DrawUtilities ()
Definition at line 233 of file ImagesGrid.cpp.
References initBaseShader(), and initGridShader().
Member Function Documentation
baseRendering()
void sibr::DrawUtilities::baseRendering (const Mesh & mesh, Mesh::RenderMode mode, const Vector3f & color, const Vector2f & translation, const Vector2f & scaling, float alpha, const Viewport & vp)
Definition at line 239 of file ImagesGrid.cpp.
References alphaGL, baseShader, sibr::GLShader::begin(), sibr::Viewport::bind(), colorGL, sibr::GLShader::end(), sibr::Mesh::render(), scalingGL, sibr::GLuniform< T >::set(), and translationGL.
Referenced by circle(), linePixels(), and rectangle().
circle()
void sibr::DrawUtilities::circle (const Vector3f & color, const Vector2f & center, float radius, bool fill, float alpha, const Vector2f & scaling = Vector3f(1, 1), int precision = 50)
Definition at line 296 of file ImagesGrid.cpp.
References baseRendering(), sibr::Mesh::FillRenderMode, and sibr::Mesh::LineRenderMode.
Referenced by circlePixels().
circlePixels()
void sibr::DrawUtilities::circlePixels (const Vector3f & color, const Vector2f & center, float radius, bool fill, float alpha, const Vector2f & winSize, int precision = 50)
Definition at line 338 of file ImagesGrid.cpp.
References circle().
image_grid()
void sibr::DrawUtilities::image_grid (int num_imgs, uint texture, const Vector2f & grid, const Vector2f & tl, const Vector2f & br, int lod, bool flip_texture)
Definition at line 364 of file ImagesGrid.cpp.
References sibr::GLShader::begin(), sibr::GLShader::end(), flip_textureGL, gridBottomRightGL, gridGL, gridShader, gridTopLeftGL, lodGL, numImgsGL, sibr::RenderUtility::renderScreenQuad(), and sibr::GLuniform< T >::set().
Referenced by sibr::ImagesGrid::onRender().
initBaseShader()
void sibr::DrawUtilities::initBaseShader () private
Definition at line 384 of file ImagesGrid.cpp.
References alphaGL, baseShader, colorGL, sibr::GLuniform< T >::init(), sibr::GLShader::init(), scalingGL, and translationGL.
Referenced by DrawUtilities().
initGridShader()
void sibr::DrawUtilities::initGridShader () private
Definition at line 411 of file ImagesGrid.cpp.
References flip_textureGL, gridBottomRightGL, gridGL, gridShader, gridTopLeftGL, sibr::GLuniform< T >::init(), sibr::GLShader::init(), lodGL, and numImgsGL.
Referenced by DrawUtilities().
linePixels()
void sibr::DrawUtilities::linePixels (const Vector3f & color, const Vector2f & ptA, const Vector2f & ptB, const Vector2f & winSize)
Definition at line 346 of file ImagesGrid.cpp.
References baseRendering(), ibr_convert_old_to_new::line, and sibr::Mesh::LineRenderMode.
rectangle()
void sibr::DrawUtilities::rectangle (const Vector3f & color, const Vector2f & tl, const Vector2f & br, bool fill, float alpha, const Viewport & vp)
Definition at line 261 of file ImagesGrid.cpp.
References baseRendering(), sibr::Mesh::FillRenderMode, and sibr::Mesh::LineRenderMode.
Referenced by sibr::GridMapping::displayZoom(), sibr::GridMapping::highlightImage(), sibr::GridMapping::highlightPixel(), and rectanglePixels().
rectanglePixels()
void sibr::DrawUtilities::rectanglePixels (const Vector3f & color, const Vector2f & center, const Vector2f & diagonalPixs, bool fill, float alpha, const Viewport & vp)
Definition at line 288 of file ImagesGrid.cpp.
References sibr::Viewport::finalSize(), and rectangle().
Referenced by sibr::GridMapping::highlightPixel().
Member Data Documentation
alphaGL
GLuniform<float> sibr::DrawUtilities::alphaGL
Definition at line 21 of file ImagesGrid.hpp.
Referenced by baseRendering(), and initBaseShader().
baseShader
GLShader sibr::DrawUtilities::baseShader
Definition at line 18 of file ImagesGrid.hpp.
Referenced by baseRendering(), and initBaseShader().
colorGL
GLuniform<Vector3f> sibr::DrawUtilities::colorGL
Definition at line 20 of file ImagesGrid.hpp.
Referenced by baseRendering(), and initBaseShader().
flip_textureGL
GLuniform<bool> sibr::DrawUtilities::flip_textureGL
Definition at line 33 of file ImagesGrid.hpp.
Referenced by image_grid(), and initGridShader().
gridBottomRightGL
GLuniform<Vector2f> sibr::DrawUtilities::gridBottomRightGL
Definition at line 30 of file ImagesGrid.hpp.
Referenced by image_grid(), and initGridShader().
gridGL
GLuniform<Vector2f> sibr::DrawUtilities::gridGL
Definition at line 28 of file ImagesGrid.hpp.
Referenced by image_grid(), and initGridShader().
gridShader
GLShader sibr::DrawUtilities::gridShader
Definition at line 25 of file ImagesGrid.hpp.
Referenced by image_grid(), and initGridShader().
gridTopLeftGL
GLuniform<Vector2f> sibr::DrawUtilities::gridTopLeftGL
Definition at line 29 of file ImagesGrid.hpp.
Referenced by image_grid(), and initGridShader().
lodGL
GLuniform<float> sibr::DrawUtilities::lodGL
Definition at line 31 of file ImagesGrid.hpp.
Referenced by image_grid(), and initGridShader().
numImgsGL
GLuniform<int> sibr::DrawUtilities::numImgsGL
Definition at line 32 of file ImagesGrid.hpp.
Referenced by image_grid(), and initGridShader().
scalingGL
GLuniform<Vector2f> sibr::DrawUtilities::scalingGL
Definition at line 22 of file ImagesGrid.hpp.
Referenced by baseRendering(), and initBaseShader().
translationGL
GLuniform<Vector2f> sibr::DrawUtilities::translationGL
Definition at line 23 of file ImagesGrid.hpp.
Referenced by baseRendering(), and initBaseShader().
The documentation for this class was generated from the following files:
src/core/view/ImagesGrid.hpp
src/core/view/ImagesGrid.cpp