SIBR: sibr::IRenderTarget Class Reference
sibr::IRenderTarget Class Reference abstract
sibr_graphics
Rendertarget interface.
#include <RenderTarget.hpp>
Public Types
typedef std::shared_ptr< IRenderTarget > Ptr
typedef std::unique_ptr< IRenderTarget > UPtr
Public Member Functions
virtual ~IRenderTarget (void)
Destructor.
virtual GLuint texture (uint t=0) const =0
Get the texture handle of the t-th color attachment.
virtual GLuint handle (uint t=0) const =0
Get the texture handle of the t-th color attachment.
virtual void bind (void)=0
Bind the rendertarget for drawing.
virtual void unbind (void)=0
Unbind the rendertarget.
virtual void clear (void)=0
Clear the content of the rendertarget.
virtual uint w (void) const =0
virtual uint h (void) const =0
virtual GLuint fbo (void) const =0
Detailed Description
Rendertarget interface.
A render target wraps an OpenGL framebuffer, that can have one depth buffer, one stencil buffer, and one or more color attachments. This generic interface is typeless,
See also
RenderTarget.
Definition at line 23 of file RenderTarget.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<IRenderTarget> sibr::IRenderTarget::Ptr
Definition at line 26 of file RenderTarget.hpp.
UPtr
typedef std::unique_ptr<IRenderTarget> sibr::IRenderTarget::UPtr
Definition at line 27 of file RenderTarget.hpp.
Constructor & Destructor Documentation
~IRenderTarget()
virtual sibr::IRenderTarget::~IRenderTarget (void) inline virtual
Destructor.
Definition at line 30 of file RenderTarget.hpp.
Member Function Documentation
bind()
virtual void sibr::IRenderTarget::bind (void) pure virtual
Bind the rendertarget for drawing.
All color buffers are bound, along with the depth and optional stencil buffers.
Implemented in sibr::Window, and sibr::RenderTarget< T_Type, T_NumComp >.
Referenced by sibr::ColoredMeshRenderer::process(), sibr::MonoRdrMode::render(), and sibr::StereoAnaglyphRdrMode::render().
clear()
virtual void sibr::IRenderTarget::clear (void) pure virtual
Clear the content of the rendertarget.
Implemented in sibr::Window, and sibr::RenderTarget< T_Type, T_NumComp >.
fbo()
virtual GLuint sibr::IRenderTarget::fbo (void) const pure virtual
Returns
the framebuffer handle.
Implemented in sibr::Window, and sibr::RenderTarget< T_Type, T_NumComp >.
h()
virtual uint sibr::IRenderTarget::h (void) const pure virtual
Returns
the rendertarget height.
Implemented in sibr::Window, and sibr::RenderTarget< T_Type, T_NumComp >.
Referenced by sibr::MonoRdrMode::render(), sibr::StereoAnaglyphRdrMode::render(), and sibr::ImageView::setRenderTarget().
handle()
virtual GLuint sibr::IRenderTarget::handle (uint t = 0) const pure virtual
Get the texture handle of the t-th color attachment.
Parameters
t the color attachment slot
Returns
the texture handle
Implemented in sibr::Window, and sibr::RenderTarget< T_Type, T_NumComp >.
Referenced by sibr::ImageView::setRenderTarget(), and sibr::showImGuiWindow().
texture()
virtual GLuint sibr::IRenderTarget::texture (uint t = 0) const pure virtual
Get the texture handle of the t-th color attachment.
Parameters
t the color attachment slot
Returns
the texture handle
Deprecated:
Use handle instead.
Implemented in sibr::Window, and sibr::RenderTarget< T_Type, T_NumComp >.
unbind()
virtual void sibr::IRenderTarget::unbind (void) pure virtual
Unbind the rendertarget.
Note
This will bind the window rendertarget.
Implemented in sibr::Window, and sibr::RenderTarget< T_Type, T_NumComp >.
Referenced by sibr::ColoredMeshRenderer::process(), sibr::MonoRdrMode::render(), and sibr::StereoAnaglyphRdrMode::render().
w()
virtual uint sibr::IRenderTarget::w (void) const pure virtual
Returns
the rendertarget width.
Implemented in sibr::Window, and sibr::RenderTarget< T_Type, T_NumComp >.
Referenced by sibr::MonoRdrMode::render(), sibr::StereoAnaglyphRdrMode::render(), and sibr::ImageView::setRenderTarget().
The documentation for this class was generated from the following file:
src/core/graphics/RenderTarget.hpp