SIBR: sibr::RenderTarget< T_Type, T_NumComp > Class Template Reference
sibr::RenderTarget< T_Type, T_NumComp > Class Template Reference
sibr_graphics
A render target wraps an OpenGL framebuffer, that can have one depth buffer, one stencil buffer, and one or more color attachments.
#include <RenderTarget.hpp>
Public Types
typedef Image< T_Type, T_NumComp > PixelImage
typedef PixelImage::Pixel PixelFormat
typedef std::shared_ptr< RenderTarget< T_Type, T_NumComp > > Ptr
typedef std::unique_ptr< RenderTarget< T_Type, T_NumComp > > UPtr
Public Types inherited from sibr::IRenderTarget
typedef std::shared_ptr< IRenderTarget > Ptr
typedef std::unique_ptr< IRenderTarget > UPtr
Public Member Functions
RenderTarget (void)
Constructor.
RenderTarget (uint w, uint h, uint flags=0, uint num=1)
Constructor and allocation.
~RenderTarget (void)
Destructor.
GLuint texture (uint t=0) const
Get the texture handle of the t-th color attachment.
GLuint handle (uint t=0) const
Get the texture handle of the t-th color attachment.
GLuint depthRB () const
void bind (void)
Bind the rendertarget for drawing.
void unbind (void)
Unbind the rendertarget.
void clear (void)
Clear the rendertarget buffers with default values.
void clear (const typename RenderTarget< T_Type, T_NumComp >::PixelFormat &v)
Clear the rendertarget buffers, using a custom clear color.
void clearStencil (void)
Clear the stencil buffer only.
void clearDepth (void)
Clear the depth buffer only.
template<typename TType , uint NNumComp>
void readBack (sibr::Image< TType, NNumComp > &image, uint target=0) const
Readback the content of a color attachment into an sibr::Image on the CPU.
template<typename TType , uint NNumComp>
void readBackToCVmat (cv::Mat &image, uint target=0) const
Readback the content of a color attachment into a cv::Mat on the CPU.
template<typename TType , uint NNumComp>
void readBackDepth (sibr::Image< TType, NNumComp > &image) const
Readback the content of the depth attachment into an sibr::Image on the CPU.
uint numTargets (void) const
uint w (void) const
uint h (void) const
GLuint fbo (void) const
template<typename T_IType , uint N_INumComp>
void readBack (sibr::Image< T_IType, N_INumComp > &img, uint target) const
template<typename T_IType , uint N_INumComp>
void readBackDepth (sibr::Image< T_IType, N_INumComp > &image) const
Public Member Functions inherited from sibr::IRenderTarget
virtual ~IRenderTarget (void)
Destructor.
Private Member Functions
SIBR_DISALLOW_COPY (RenderTarget)
Private Attributes
GLuint m_fbo = 0
Framebuffer handle.
GLuint m_depth_rb = 0
Depth renderbuffer handle.
GLuint m_stencil_rb = 0
Stencil renderbuffer handle.
GLuint m_textures [SIBR_MAX_SHADER_ATTACHMENTS]
Color texture handles.
uint m_numtargets = 0
Number of active color attachments.
bool m_autoMIPMAP = false
Generate mipmaps on the fly.
bool m_msaa = false
Use multisampled targets.
bool m_stencil = false
Has a stencil buffer.
uint m_W = 0
Width.
uint m_H = 0
Height.
Detailed Description
template<typename T_Type, unsigned int T_NumComp>
class sibr::RenderTarget< T_Type, T_NumComp >
A render target wraps an OpenGL framebuffer, that can have one depth buffer, one stencil buffer, and one or more color attachments.
See also
IRenderTarget.
Definition at line 73 of file RenderTarget.hpp.
Member Typedef Documentation
PixelFormat
template<typename T_Type , unsigned int T_NumComp> typedef PixelImage::Pixel sibr::RenderTarget< T_Type, T_NumComp >::PixelFormat
Definition at line 77 of file RenderTarget.hpp.
PixelImage
template<typename T_Type , unsigned int T_NumComp> typedef Image<T_Type, T_NumComp> sibr::RenderTarget< T_Type, T_NumComp >::PixelImage
Definition at line 76 of file RenderTarget.hpp.
Ptr
template<typename T_Type , unsigned int T_NumComp> typedef std::shared_ptr<RenderTarget<T_Type, T_NumComp> > sibr::RenderTarget< T_Type, T_NumComp >::Ptr
Definition at line 78 of file RenderTarget.hpp.
UPtr
template<typename T_Type , unsigned int T_NumComp> typedef std::unique_ptr<RenderTarget<T_Type, T_NumComp> > sibr::RenderTarget< T_Type, T_NumComp >::UPtr
Definition at line 79 of file RenderTarget.hpp.
Constructor & Destructor Documentation
RenderTarget() [1/2]
template<typename T_Type , unsigned int T_NumComp> sibr::RenderTarget< T_Type, T_NumComp >::RenderTarget (void)
Constructor.
Definition at line 288 of file RenderTarget.hpp.
RenderTarget() [2/2]
template<typename T_Type , unsigned int T_NumComp> sibr::RenderTarget< T_Type, T_NumComp >::RenderTarget (uint w, uint h, uint flags = 0, uint num = 1)
Constructor and allocation.
Parameters
w the target width
h the target height
flags options
num the number of color attachments.
Definition at line 297 of file RenderTarget.hpp.
References CHECK_GL_ERROR, SIBR_ASSERT, SIBR_CLAMP_UVS, SIBR_DEBUG, SIBR_GPU_AUTOGEN_MIPMAP, SIBR_GPU_INTEGER, SIBR_GPU_LINEAR_SAMPLING, SIBR_GPU_MULSTISAMPLE, SIBR_STENCIL_BUFFER, and sibr::RenderUtility::useDefaultVAO().
~RenderTarget()
template<typename T_Type , unsigned int T_NumComp> sibr::RenderTarget< T_Type, T_NumComp >::~RenderTarget (void)
Destructor.
Definition at line 462 of file RenderTarget.hpp.
References CHECK_GL_ERROR.
Member Function Documentation
bind()
template<typename T_Type , unsigned int T_NumComp> void sibr::RenderTarget< T_Type, T_NumComp >::bind (void) virtual
Bind the rendertarget for drawing.
All color buffers are bound, along with the depth and optional stencil buffers.
Implements sibr::IRenderTarget.
Definition at line 487 of file RenderTarget.hpp.
References SIBR_MAX_SHADER_ATTACHMENTS.
Referenced by sibr::Intersector2D::frustrumQuadsIntersect(), sibr::DepthInputTextureArray::initDepthTextureArrays(), and sibr::RenderMaskHolder::uploadMaskGPU().
clear() [1/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::RenderTarget< T_Type, T_NumComp >::clear (const typename RenderTarget< T_Type, T_NumComp >::PixelFormat & v)
Clear the rendertarget buffers, using a custom clear color.
Parameters
v the clear color
Warning
This function will unbind the render target after clearing.
Bug:
This function does not rescale values for uchar (so background is either 0 or 1)
Definition at line 520 of file RenderTarget.hpp.
References NumComp.
clear() [2/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::RenderTarget< T_Type, T_NumComp >::clear (void) virtual
Clear the rendertarget buffers with default values.
Warning
This function will unbind the render target after clearing.
Implements sibr::IRenderTarget.
Definition at line 515 of file RenderTarget.hpp.
Referenced by sibr::RenderMaskHolder::uploadMaskGPU().
clearDepth()
template<typename T_Type , unsigned int T_NumComp> void sibr::RenderTarget< T_Type, T_NumComp >::clearDepth (void)
Clear the depth buffer only.
Definition at line 544 of file RenderTarget.hpp.
clearStencil()
template<typename T_Type , unsigned int T_NumComp> void sibr::RenderTarget< T_Type, T_NumComp >::clearStencil (void)
Clear the stencil buffer only.
Definition at line 536 of file RenderTarget.hpp.
depthRB()
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::RenderTarget< T_Type, T_NumComp >::depthRB
Returns
the depth buffer handle.
Definition at line 471 of file RenderTarget.hpp.
fbo()
template<typename T_Type , unsigned int T_NumComp> uint sibr::RenderTarget< T_Type, T_NumComp >::fbo (void) const virtual
Returns
the framebuffer handle.
Implements sibr::IRenderTarget.
Definition at line 649 of file RenderTarget.hpp.
h()
template<typename T_Type , unsigned int T_NumComp> uint sibr::RenderTarget< T_Type, T_NumComp >::h (void) const virtual
Returns
the target height.
Implements sibr::IRenderTarget.
Definition at line 647 of file RenderTarget.hpp.
Referenced by sibr::Intersector2D::frustrumQuadsIntersect(), sibr::show(), sibr::showDepth(), and sibr::showDepthFromAlpha().
handle()
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::RenderTarget< T_Type, T_NumComp >::handle (uint t = 0) const virtual
Get the texture handle of the t-th color attachment.
Parameters
t the color attachment slot
Returns
the texture handle
Implements sibr::IRenderTarget.
Definition at line 481 of file RenderTarget.hpp.
References SIBR_ASSERT.
Referenced by sibr::DepthInputTextureArray::initDepthTextureArrays().
numTargets()
template<typename T_Type , unsigned int T_NumComp> uint sibr::RenderTarget< T_Type, T_NumComp >::numTargets (void) const
Returns
the number of active color targets.
Definition at line 643 of file RenderTarget.hpp.
readBack() [1/2]
template<typename T_Type , unsigned int T_NumComp> template<typename T_IType , uint N_INumComp> void sibr::RenderTarget< T_Type, T_NumComp >::readBack (sibr::Image< T_IType, N_INumComp > & img, uint target) const
Definition at line 552 of file RenderTarget.hpp.
References sibr::Image< T_Type, T_NumComp >::data(), sibr::Image< T_Type, T_NumComp >::flipH(), sibr::Image< T_Type, T_NumComp >::fromOpenCV(), SIBR_ERR, and sibr::Image< T_Type, T_NumComp >::toOpenCV().
readBack() [2/2]
template<typename T_Type , unsigned int T_NumComp> template<typename TType , uint NNumComp> void sibr::RenderTarget< T_Type, T_NumComp >::readBack (sibr::Image< TType, NNumComp > & image, uint target = 0) const
Readback the content of a color attachment into an sibr::Image on the CPU.
Parameters
image will contain the texture content
target the color attachment index to read
Warning
Might cause a GPU flush/sync.
Referenced by sibr::Intersector2D::frustrumQuadsIntersect(), sibr::show(), and sibr::showDepthFromAlpha().
readBackDepth() [1/2]
template<typename T_Type , unsigned int T_NumComp> template<typename T_IType , uint N_INumComp> void sibr::RenderTarget< T_Type, T_NumComp >::readBackDepth (sibr::Image< T_IType, N_INumComp > & image) const
Definition at line 621 of file RenderTarget.hpp.
References sibr::Image< T_Type, T_NumComp >::color(), sibr::Image< T_Type, T_NumComp >::data(), sibr::Image< T_Type, T_NumComp >::h(), and sibr::Image< T_Type, T_NumComp >::w().
readBackDepth() [2/2]
template<typename T_Type , unsigned int T_NumComp> template<typename TType , uint NNumComp> void sibr::RenderTarget< T_Type, T_NumComp >::readBackDepth (sibr::Image< TType, NNumComp > & image) const
Readback the content of the depth attachment into an sibr::Image on the CPU.
Parameters
image will contain the depth content
Warning
Might cause a GPU flush/sync.
Image orientation might be inconsistent with readBack (flip around horizontal axis).
Referenced by sibr::showDepth().
readBackToCVmat()
template<typename T_Type , unsigned int T_NumComp> template<typename T_IType , uint N_INumComp> void sibr::RenderTarget< T_Type, T_NumComp >::readBackToCVmat (cv::Mat & image, uint target = 0) const
Readback the content of a color attachment into a cv::Mat on the CPU.
Parameters
image will contain the texture content
target the color attachment index to read
Warning
Might cause a GPU flush/sync.
Definition at line 588 of file RenderTarget.hpp.
References SIBR_ERR.
SIBR_DISALLOW_COPY()
template<typename T_Type , unsigned int T_NumComp> sibr::RenderTarget< T_Type, T_NumComp >::SIBR_DISALLOW_COPY (RenderTarget< T_Type, T_NumComp >) private
texture()
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::RenderTarget< T_Type, T_NumComp >::texture (uint t = 0) const virtual
Get the texture handle of the t-th color attachment.
Parameters
t the color attachment slot
Returns
the texture handle
Deprecated:
Use handle instead.
Implements sibr::IRenderTarget.
Definition at line 476 of file RenderTarget.hpp.
References SIBR_ASSERT.
unbind()
template<typename T_Type , unsigned int T_NumComp> void sibr::RenderTarget< T_Type, T_NumComp >::unbind (void) virtual
Unbind the rendertarget.
Note
This will bind the window rendertarget.
Implements sibr::IRenderTarget.
Definition at line 504 of file RenderTarget.hpp.
Referenced by sibr::DepthInputTextureArray::initDepthTextureArrays(), and sibr::RenderMaskHolder::uploadMaskGPU().
w()
template<typename T_Type , unsigned int T_NumComp> uint sibr::RenderTarget< T_Type, T_NumComp >::w (void) const virtual
Returns
the target width.
Implements sibr::IRenderTarget.
Definition at line 645 of file RenderTarget.hpp.
Referenced by sibr::Intersector2D::frustrumQuadsIntersect(), sibr::show(), sibr::showDepth(), and sibr::showDepthFromAlpha().
Member Data Documentation
m_autoMIPMAP
template<typename T_Type , unsigned int T_NumComp> bool sibr::RenderTarget< T_Type, T_NumComp >::m_autoMIPMAP = false private
Generate mipmaps on the fly.
Definition at line 88 of file RenderTarget.hpp.
m_depth_rb
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::RenderTarget< T_Type, T_NumComp >::m_depth_rb = 0 private
Depth renderbuffer handle.
Definition at line 84 of file RenderTarget.hpp.
m_fbo
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::RenderTarget< T_Type, T_NumComp >::m_fbo = 0 private
Framebuffer handle.
Definition at line 83 of file RenderTarget.hpp.
m_H
template<typename T_Type , unsigned int T_NumComp> uint sibr::RenderTarget< T_Type, T_NumComp >::m_H = 0 private
Height.
Definition at line 92 of file RenderTarget.hpp.
m_msaa
template<typename T_Type , unsigned int T_NumComp> bool sibr::RenderTarget< T_Type, T_NumComp >::m_msaa = false private
Use multisampled targets.
Definition at line 89 of file RenderTarget.hpp.
m_numtargets
template<typename T_Type , unsigned int T_NumComp> uint sibr::RenderTarget< T_Type, T_NumComp >::m_numtargets = 0 private
Number of active color attachments.
Definition at line 87 of file RenderTarget.hpp.
m_stencil
template<typename T_Type , unsigned int T_NumComp> bool sibr::RenderTarget< T_Type, T_NumComp >::m_stencil = false private
Has a stencil buffer.
Definition at line 90 of file RenderTarget.hpp.
m_stencil_rb
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::RenderTarget< T_Type, T_NumComp >::m_stencil_rb = 0 private
Stencil renderbuffer handle.
Definition at line 85 of file RenderTarget.hpp.
m_textures
template<typename T_Type , unsigned int T_NumComp> GLuint sibr::RenderTarget< T_Type, T_NumComp >::m_textures[SIBR_MAX_SHADER_ATTACHMENTS] private
Color texture handles.
Definition at line 86 of file RenderTarget.hpp.
m_W
template<typename T_Type , unsigned int T_NumComp> uint sibr::RenderTarget< T_Type, T_NumComp >::m_W = 0 private
Width.
Definition at line 91 of file RenderTarget.hpp.
The documentation for this class was generated from the following file:
src/core/graphics/RenderTarget.hpp