SIBR: sibr::ParseData Class Reference
sibr::ParseData Class Reference
sibr_scene
Class used to store the data required for defining an IBR Scene.
#include <ParseData.hpp>
Public Types
typedef std::shared_ptr< ParseData > Ptr
Pointer to the instance of class sibr::ParseData.
Public Types inherited from sibr::IParseData
enum Type {
Type::EMPTY, Type::SIBR, Type::COLMAP_CAPREAL, Type::COLMAP,
Type::NVM, Type::MESHROOM, Type::EXTERNAL
}
Denotes the type of dataset represented by a IParseData object.
typedef std::shared_ptr< IParseData > Ptr
Pointer to the instance of class sibr::IParseData.
Public Member Functions
void getParsedBundlerData (const std::string &dataset_path, const std::string &customPath, const std::string &scene_metadata_filename)
Function to parse data from a template dataset path.
void getParsedMeshroomData (const std::string &dataset_path, const std::string &customPath="")
Function to parse data from a template dataset path.
void getParsedColmapData (const std::string &dataset_path, const int fovXfovY_flag, const bool capreal_flag=true)
Function to parse data from a colmap dataset path.
void getParsedNVMData (const std::string &dataset_path, const std::string &customPath, const std::string &nvm_path)
Function to parse data from a template dataset path.
void getParsedData (const BasicIBRAppArgs &myArgs, const std::string &customPath="") override
Function to parse data from a dataset path.
const std::vector< sibr::ImageListFile::Infos > & imgInfos (void) const override
Getter for the information regarding the input images.
void imgInfos (std::vector< sibr::ImageListFile::Infos > &infos) override
Setter for the information regarding the input images.
const int numCameras (void) const override
Getter to the number of cameras defined in the bundle file.
void numCameras (int numCams) override
Setter to the number of cameras defined in the bundle file.
const std::vector< bool > & activeImages (void) const override
Getter for the list of active cameras/images.
void activeImages (std::vector< bool > &activeCams) override
Setter for the list of active cameras/images.
const std::string & basePathName (void) const override
Getter for the base path name where the dataset is located.
void basePathName (std::string &path) override
Setter for the base path name where the dataset is located.
const std::string & meshPath (void) const override
Getter for the mesh path where the dataset is located.
void meshPath (std::string &path) override
Setter for the mesh path where the dataset is located.
const IParseData::Type & datasetType (void) const override
Getter for the dataset type.
void datasetType (IParseData::Type dataType) override
Setter for the dataset type.
const std::vector< InputCamera::Ptr > cameras (void) const override
Getter for the camera infos.
void cameras (std::vector< InputCamera::Ptr > &cams) override
Setter for the camera infos.
const std::string imgPath (void) const override
Getter for the image path.
void imgPath (std::string &imPath) override
Setter for the image path.
virtual bool parseSceneMetadata (const std::string &scene_metadata_path)
Function to parse the scene metadata file to read image data.
Protected Member Functions
bool parseBundlerFile (const std::string &bundler_file_path)
Function to parse the camera calibration files to read camera properties (camera matrix etc.).
void populateFromCamInfos ()
Function to populate scene info from camera infos to appropriate location.
Protected Attributes
std::vector< InputCamera::Ptr > _camInfos
std::string _basePathName
std::string _meshPath
std::vector< sibr::ImageListFile::Infos > _imgInfos
std::string _imgPath = ""
std::vector< bool > _activeImages
int _numCameras
Type _datasetType = Type::EMPTY
Detailed Description
Class used to store the data required for defining an IBR Scene.
Members:
_basePathName: Base dataset directory path.
_camInfos: Vector of sibr::InputCamera holding all data attached with the scene cameras.
_meshPath: Filepath of the mesh associated to the scene.
_imgInfos: Vector of sibr::ImageListFile::Infos holding filename, width, height, and id of the input images.
_imgPath: Path to the calibrated images directory.
_activeImages: Vector of bools storing active state of the camera.
_numCameras: Number of cameras associated with the dataset
_datasetType: Type if dataset being used. Currently supported: COLMAP, SIBR_BUNDLER, NVM, MESHROOM
Definition at line 25 of file ParseData.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<ParseData> sibr::ParseData::Ptr
Pointer to the instance of class sibr::ParseData.
Definition at line 32 of file ParseData.hpp.
Member Function Documentation
activeImages() [1/2]
void sibr::ParseData::activeImages (std::vector< bool > & activeCams) inline override virtual
Setter for the list of active cameras/images.
Implements sibr::IParseData.
Definition at line 234 of file ParseData.hpp.
References _activeImages.
activeImages() [2/2]
const std::vector< bool > & sibr::ParseData::activeImages (void) const inline override virtual
Getter for the list of active cameras/images.
Implements sibr::IParseData.
Definition at line 230 of file ParseData.hpp.
References _activeImages.
basePathName() [1/2]
void sibr::ParseData::basePathName (std::string & path) inline override virtual
Setter for the base path name where the dataset is located.
Implements sibr::IParseData.
Definition at line 244 of file ParseData.hpp.
References _basePathName.
basePathName() [2/2]
const std::string & sibr::ParseData::basePathName (void) const inline override virtual
Getter for the base path name where the dataset is located.
Implements sibr::IParseData.
Definition at line 239 of file ParseData.hpp.
References _basePathName.
cameras() [1/2]
void sibr::ParseData::cameras (std::vector< InputCamera::Ptr > & cams) inline override virtual
Setter for the camera infos.
Implements sibr::IParseData.
Definition at line 268 of file ParseData.hpp.
References _camInfos.
cameras() [2/2]
const std::vector< InputCamera::Ptr > sibr::ParseData::cameras (void) const inline override virtual
Getter for the camera infos.
Implements sibr::IParseData.
Definition at line 263 of file ParseData.hpp.
References _camInfos.
datasetType() [1/2]
void sibr::ParseData::datasetType (IParseData::Type dataType) inline override virtual
Setter for the dataset type.
Implements sibr::IParseData.
Definition at line 259 of file ParseData.hpp.
References _datasetType.
datasetType() [2/2]
const ParseData::Type & sibr::ParseData::datasetType (void) const inline override virtual
Getter for the dataset type.
Implements sibr::IParseData.
Definition at line 283 of file ParseData.hpp.
References _datasetType.
getParsedBundlerData()
void sibr::ParseData::getParsedBundlerData (const std::string & dataset_path, const std::string & customPath, const std::string & scene_metadata_filename)
Function to parse data from a template dataset path.
Parameters
dataset_path Path to the folder containing data
customPath Path to algorithm specific data
scene_metadata_filename Specify the filename of the Scene Metadata file to load specific scene
Definition at line 185 of file ParseData.cpp.
References sibr::fileExists(), and SIBR_ERR.
getParsedColmapData()
void sibr::ParseData::getParsedColmapData (const std::string & dataset_path, const int fovXfovY_flag, const bool capreal_flag = true)
Function to parse data from a colmap dataset path.
The function takes in a colmap dataset folder path and populates ParseData members with data. This function can be used for direct compatibility with colmap data in SIBR. The function automatically computes the intrinsic and extrinsic parameters of the camera, input images filename, widht and height etc. Colmap uses LHS coordinate system while SIBR uses RHS coordinate system. The function applies appropriate transformation to handle this case.
For further compatibility with FrIBR, which enforces a Y-up RHS coordinate system, we need to apply an extra conversion to the rotation matrix, to 'flip back' from y-down to y-up.
Note
Note: when applying the above mentioned conversion, the mesh needs to be converted by the same converter matrix
Parameters
dataset_path Path to the folder containing data
fovXfovY_flag activate two dimensional fov parameters
capreal_flag use capreal data
Definition at line 227 of file ParseData.cpp.
References sibr::fileExists(), sibr::find_any(), ibr_convert_old_to_new::line, sibr::InputCamera::loadColmap(), SIBR_ERR, and sibr::split().
getParsedData()
void sibr::ParseData::getParsedData (const BasicIBRAppArgs & myArgs, const std::string & customPath = "") override virtual
Function to parse data from a dataset path.
Will automatically determine the type of dataset based on the files present.
Parameters
myArgs Arguments containing the dataset path and other infos
customPath additional data path
Implements sibr::IParseData.
Definition at line 292 of file ParseData.cpp.
References sibr::RenderingArgs::colmap_fovXfovY_flag, sibr::BasicDatasetArgs::dataset_path, sibr::BasicDatasetArgs::dataset_type, sibr::directoryExists(), sibr::fileExists(), sibr::ArgBase< T >::get(), sibr::RequiredArgBase< T >::get(), sibr::RenderingArgs::scene_metadata_filename, SIBR_ERR, and sibr::to_lower().
getParsedMeshroomData()
void sibr::ParseData::getParsedMeshroomData (const std::string & dataset_path, const std::string & customPath = "")
Function to parse data from a template dataset path.
Parameters
dataset_path Path to the folder containing data
customPath Path to algorithm specific data
Definition at line 207 of file ParseData.cpp.
References sibr::listSubdirectories(), sibr::InputCamera::loadMeshroom(), and SIBR_ERR.
getParsedNVMData()
void sibr::ParseData::getParsedNVMData (const std::string & dataset_path, const std::string & customPath, const std::string & nvm_path)
Function to parse data from a template dataset path.
Parameters
dataset_path Path to the folder containing data
customPath Path to algorithm specific data
nvm_path Specify the filename of the NVM path.
Definition at line 275 of file ParseData.cpp.
References sibr::fileExists(), sibr::InputCamera::loadNVM(), and SIBR_ERR.
imgInfos() [1/2]
void sibr::ParseData::imgInfos (std::vector< sibr::ImageListFile::Infos > & infos) inline override virtual
Setter for the information regarding the input images.
Implements sibr::IParseData.
Definition at line 216 of file ParseData.hpp.
References _imgInfos.
imgInfos() [2/2]
const std::vector< sibr::ImageListFile::Infos > & sibr::ParseData::imgInfos (void) const inline override virtual
Getter for the information regarding the input images.
Implements sibr::IParseData.
Definition at line 212 of file ParseData.hpp.
References _imgInfos.
imgPath() [1/2]
void sibr::ParseData::imgPath (std::string & imPath) inline override virtual
Setter for the image path.
Implements sibr::IParseData.
Definition at line 278 of file ParseData.hpp.
References _imgPath.
imgPath() [2/2]
const std::string sibr::ParseData::imgPath (void) const inline override virtual
Getter for the image path.
Implements sibr::IParseData.
Definition at line 273 of file ParseData.hpp.
References _imgPath.
meshPath() [1/2]
void sibr::ParseData::meshPath (std::string & path) inline override virtual
Setter for the mesh path where the dataset is located.
Implements sibr::IParseData.
Definition at line 254 of file ParseData.hpp.
References _meshPath.
meshPath() [2/2]
const std::string & sibr::ParseData::meshPath (void) const inline override virtual
Getter for the mesh path where the dataset is located.
Implements sibr::IParseData.
Definition at line 249 of file ParseData.hpp.
References _meshPath.
numCameras() [1/2]
void sibr::ParseData::numCameras (int numCams) inline override virtual
Setter to the number of cameras defined in the bundle file.
Implements sibr::IParseData.
Definition at line 225 of file ParseData.hpp.
References _numCameras.
numCameras() [2/2]
const int sibr::ParseData::numCameras (void) const inline override virtual
Getter to the number of cameras defined in the bundle file.
Implements sibr::IParseData.
Definition at line 221 of file ParseData.hpp.
References _numCameras.
parseBundlerFile()
bool sibr::ParseData::parseBundlerFile (const std::string & bundler_file_path) protected
Function to parse the camera calibration files to read camera properties (camera matrix etc.).
Definition at line 19 of file ParseData.cpp.
References sibr::ImageListFile::Infos::camId, sibr::ImageListFile::Infos::filename, sibr::ImageListFile::Infos::height, ibr_convert_old_to_new::line, SIBR_ERR, and sibr::ImageListFile::Infos::width.
parseSceneMetadata()
bool sibr::ParseData::parseSceneMetadata (const std::string & scene_metadata_path) virtual
Function to parse the scene metadata file to read image data.
Definition at line 69 of file ParseData.cpp.
References sibr::ImageListFile::Infos::camId, sibr::InputCamera::Z::far, sibr::ImageListFile::Infos::filename, sibr::ImageListFile::Infos::height, ibr_convert_old_to_new::line, sibr::InputCamera::Z::near, ibr_convert_old_to_new::scene_metadata, sibr::split(), and sibr::ImageListFile::Infos::width.
populateFromCamInfos()
void sibr::ParseData::populateFromCamInfos () protected
Function to populate scene info from camera infos to appropriate location.
Definition at line 54 of file ParseData.cpp.
Member Data Documentation
_activeImages
std::vector<bool> sibr::ParseData::_activeImages protected
Definition at line 203 of file ParseData.hpp.
Referenced by activeImages().
_basePathName
std::string sibr::ParseData::_basePathName protected
Definition at line 199 of file ParseData.hpp.
Referenced by basePathName().
_camInfos
std::vector<InputCamera::Ptr> sibr::ParseData::_camInfos protected
Definition at line 198 of file ParseData.hpp.
Referenced by cameras().
_datasetType
Type sibr::ParseData::_datasetType = Type::EMPTY protected
Definition at line 205 of file ParseData.hpp.
Referenced by datasetType().
_imgInfos
std::vector<sibr::ImageListFile::Infos> sibr::ParseData::_imgInfos protected
Definition at line 201 of file ParseData.hpp.
Referenced by imgInfos().
_imgPath
std::string sibr::ParseData::_imgPath = "" protected
Definition at line 202 of file ParseData.hpp.
Referenced by imgPath().
_meshPath
std::string sibr::ParseData::_meshPath protected
Definition at line 200 of file ParseData.hpp.
Referenced by meshPath().
_numCameras
int sibr::ParseData::_numCameras protected
Definition at line 204 of file ParseData.hpp.
Referenced by numCameras().
The documentation for this class was generated from the following files:
src/core/scene/ParseData.hpp
src/core/scene/ParseData.cpp