SIBR: sibr::DatasetView Class Reference
sibr::DatasetView Class Reference
sibr_view
Visualize and explore a MVS dataset.
#include <DatasetView.hpp>
Classes
struct ReprojectionData
Contain data related to the reprojection of a point in input images.
Public Types
enum ReprojectionMode { NONE, IMAGE_TO_IMAGE, MESH_TO_IMAGE }
Reprojection mode.
Public Types inherited from sibr::MultiViewBase
typedef std::function< void(sibr::ViewBase::Ptr &, sibr::Input &, const sibr::Viewport &, const float)> ViewUpdateFunc
Update callback for a standard view. Passes the view pointer, the correct input state, and the correct viewport.
typedef std::function< sibr::InputCamera(sibr::ViewBase::Ptr &, sibr::Input &, const sibr::Viewport &, const float)> IBRViewUpdateFunc
Update callback for an IBR view, see main description for the return value.
typedef std::function< void(sibr::ViewBase::Ptr &, const sibr::Viewport &, const IRenderTarget::Ptr &)> AdditionalRenderFunc
Additional render callback for a subview.
Public Member Functions
DatasetView (const BasicIBRScene &scene, const Vector2u &defaultRenderingRes={ 0, 0 }, const Vector2i &defaultViewRes={ 800, 600 })
Constructor.
virtual void onGui (Window &win) override
Update the GUI.
virtual void onUpdate (Input &input) override
Update state based on user input.
virtual void onRender (Window &win) override
Perform rendering.
Public Member Functions inherited from sibr::MultiViewBase
MultiViewBase (const Vector2i &defaultViewRes={ 800, 600 })
void addSubView (const std::string &title, ViewBase::Ptr view, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register a standard subview (for instance a SceneDebugView).
void addSubView (const std::string &title, ViewBase::Ptr view, const ViewUpdateFunc updateFunc, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register a standard subview (for instance a SceneDebugView).
void addIBRSubView (const std::string &title, ViewBase::Ptr view, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register an IBR subview (for instance an ULRView).
void addIBRSubView (const std::string &title, ViewBase::Ptr view, const IBRViewUpdateFunc updateFunc, const Vector2u &res=Vector2u(0, 0), const ImGuiWindowFlags flags=0)
Register an IBR subview (for instance an ULRView).
void addSubMultiView (const std::string &title, MultiViewBase::Ptr multiview)
Add another multi-view system as a subsystem of this one.
ViewBase::Ptr & getIBRSubView (const std::string &title)
Viewport & getIBRSubViewport (const std::string &title)
ViewBase::Ptr removeSubView (const std::string &title)
Unregister a subview.
void renderingMode (const IRenderingMode::Ptr &mode)
Change the rendering mode.
void setDefaultViewResolution (const Vector2i &size)
Define the default rendering and display size for new subviews.
const Viewport getViewport (void) const
Returns the default viewport used for subviews rendering.
const float & deltaTime () const
Returns the last frame time.
void addCameraForView (const std::string &name, ICameraHandler::Ptr cameraHandler)
Add a camera handler that will automatically be updated and used by the MultiViewManager for the given subview.
void addAdditionalRenderingForView (const std::string &name, const AdditionalRenderFunc renderFunc)
Register a function performing additional rendering for a given subview, called by the MultiViewManager after calling onRender() on the subview.
int numSubViews () const
Count NOT recursively the number of subviews.
void mosaicLayout (const Viewport &vp)
Place all subviews on a regular grid in the given viewport.
void toggleSubViewsGUI ()
Toggle the display of sub-managers GUIs.
void setExportPath (const std::string &path)
Set the export path.
void captureView (const std::string &subviewName, const std::string &path="./screenshots", const std::string &filename="")
captures a View content into an image file.
Protected Member Functions
void repro (ReprojectionData &data)
populate reprojection information.
void displayRepro (const ReprojectionData &data)
Visualize the reprojection information.
BasicSubView & getMeshView ()
BasicSubView & getGridView ()
MultiMeshManager::Ptr getMMM ()
ImagesGrid::Ptr getGrid ()
MeshData & proxyData ()
Protected Member Functions inherited from sibr::MultiViewBase
void addIBRSubView (const std::string &title, ViewBase::Ptr view, const IBRViewUpdateFunc updateFunc, const Vector2u &res, const ImGuiWindowFlags flags, const bool defaultFuncUsed)
Helper to add an IBR subview.
void renderSubView (SubView &subview)
Perform rendering for a given subview.
Protected Attributes
std::vector< RaycastingCamera > cams
Input cameras.
ReprojectionData currentRepro
Current selected reprojection.
ReprojectionMode reproMode = MESH_TO_IMAGE
Current reprojection mode.
const std::string meshSubViewStr = "dataset view - mesh"
const std::string gridSubViewStr = "grid"
Protected Attributes inherited from sibr::MultiViewBase
IRenderingMode::Ptr _renderingMode = nullptr
Rendering mode.
std::map< std::string, BasicSubView > _subViews
Regular subviews.
std::map< std::string, IBRSubView > _ibrSubViews
IBR subviews.
std::map< std::string, std::shared_ptr< MultiViewBase > > _subMultiViews
Nested multi-views.
Vector2i _defaultViewResolution
Default view resolution.
std::string _exportPath
Capture output path.
std::vector< cv::Mat > _videoFrames
Video frames.
std::chrono::time_point< std::chrono::steady_clock > _timeLastFrame
Last frame time point.
float _deltaTime
Elapsed time.
bool _showSubViewsGui = true
Show the GUI of the subviews.
bool _onPause = false
Paused interaction and update.
Private Member Functions
SIBR_CLASS_PTR (DatasetView)
Additional Inherited Members
Static Protected Member Functions inherited from sibr::MultiViewBase
static void captureView (const SubView &view, const std::string &path="./screenshots/", const std::string &filename="")
Capture a view as an image on disk.
Detailed Description
Visualize and explore a MVS dataset.
Allow reprojections between one of the input images, scene geometry and other images.
Definition at line 14 of file DatasetView.hpp.
Member Enumeration Documentation
ReprojectionMode
enum sibr::DatasetView::ReprojectionMode
Reprojection mode.
Enumerator
NONE
IMAGE_TO_IMAGE
MESH_TO_IMAGE
Definition at line 29 of file DatasetView.hpp.
Constructor & Destructor Documentation
DatasetView()
sibr::DatasetView::DatasetView (const BasicIBRScene & scene, const Vector2u & defaultRenderingRes = { 0,0 }, const Vector2i & defaultViewRes = { 800, 600 })
Constructor.
Parameters
scene the IBR scene
defaultRenderingRes the mesh view rendering resolution
defaultViewRes the window/view resolution
Definition at line 5 of file DatasetView.cpp.
References sibr::MultiViewBase::addSubView(), sibr::BasicIBRScene::cameras(), cams, gridSubViewStr, sibr::BasicIBRScene::images(), meshSubViewStr, sibr::BasicIBRScene::proxies(), and SIBR_ERR.
Member Function Documentation
displayRepro()
void sibr::DatasetView::displayRepro (const ReprojectionData & data) protected
Visualize the reprojection information.
Parameters
data the reprojection to display
Definition at line 106 of file DatasetView.cpp.
References cams, getGrid(), getMMM(), sibr::DatasetView::ReprojectionData::point3D, sibr::DatasetView::ReprojectionData::repros, sibr::Mesh::triangles(), and sibr::Mesh::vertices().
Referenced by onRender().
getGrid()
ImagesGrid::Ptr sibr::DatasetView::getGrid () protected
Returns
the image grid manager.
Definition at line 142 of file DatasetView.cpp.
Referenced by displayRepro(), and onUpdate().
getGridView()
MultiViewBase::BasicSubView & sibr::DatasetView::getGridView () protected
Returns
the images subview.
Definition at line 132 of file DatasetView.cpp.
References sibr::MultiViewBase::_subViews, and gridSubViewStr.
Referenced by onUpdate().
getMeshView()
MultiViewBase::BasicSubView & sibr::DatasetView::getMeshView () protected
Returns
the mesh subview.
Definition at line 127 of file DatasetView.cpp.
References sibr::MultiViewBase::_subViews, and meshSubViewStr.
Referenced by getMMM(), and onUpdate().
getMMM()
MultiMeshManager::Ptr sibr::DatasetView::getMMM () protected
Returns
the mesh display manager.
Definition at line 137 of file DatasetView.cpp.
References getMeshView().
Referenced by displayRepro(), onUpdate(), and proxyData().
onGui()
void sibr::DatasetView::onGui (Window & win) override virtual
Update the GUI.
Reimplemented from sibr::MultiViewBase.
Definition at line 31 of file DatasetView.cpp.
onRender()
void sibr::DatasetView::onRender (Window & win) override virtual
Perform rendering.
Parameters
win the destination window
Reimplemented from sibr::MultiViewBase.
Definition at line 74 of file DatasetView.cpp.
References currentRepro, displayRepro(), and sibr::MultiViewBase::onRender().
onUpdate()
void sibr::DatasetView::onUpdate (Input & input) override virtual
Update state based on user input.
Parameters
input the view input
Reimplemented from sibr::MultiViewBase.
Definition at line 35 of file DatasetView.cpp.
References sibr::DatasetView::ReprojectionData::active, sibr::Ray::at(), cams, currentRepro, getGrid(), getGridView(), getMeshView(), getMMM(), sibr::RaycastingCamera::getRay(), sibr::InputState< TNbState, TEnum >::isActivated(), sibr::Input::key(), sibr::Key::LeftControl, sibr::Input::mouseButton(), sibr::Input::mousePosition(), sibr::MultiViewBase::onUpdate(), sibr::DatasetView::ReprojectionData::point3D, proxyData(), sibr::MeshData::raycaster, repro(), sibr::DatasetView::ReprojectionData::repros, sibr::Mouse::Right, and sibr::Input::subInput().
proxyData()
MeshData & sibr::DatasetView::proxyData () protected
Returns
the mesh display data.
Definition at line 147 of file DatasetView.cpp.
References getMMM().
Referenced by onUpdate(), and repro().
repro()
void sibr::DatasetView::repro (ReprojectionData & data) protected
populate reprojection information.
Parameters
data the info to populate
Definition at line 83 of file DatasetView.cpp.
References cams, sibr::DatasetView::ReprojectionData::occlusionTest, sibr::DatasetView::ReprojectionData::point3D, proxyData(), sibr::MeshData::raycaster, and sibr::DatasetView::ReprojectionData::repros.
Referenced by onUpdate().
SIBR_CLASS_PTR()
sibr::DatasetView::SIBR_CLASS_PTR (DatasetView) private
Member Data Documentation
cams
std::vector<RaycastingCamera> sibr::DatasetView::cams protected
Input cameras.
Definition at line 85 of file DatasetView.hpp.
Referenced by DatasetView(), displayRepro(), onUpdate(), and repro().
currentRepro
ReprojectionData sibr::DatasetView::currentRepro protected
Current selected reprojection.
Definition at line 86 of file DatasetView.hpp.
Referenced by onRender(), and onUpdate().
gridSubViewStr
const std::string sibr::DatasetView::gridSubViewStr = "grid" protected
Definition at line 90 of file DatasetView.hpp.
Referenced by DatasetView(), and getGridView().
meshSubViewStr
const std::string sibr::DatasetView::meshSubViewStr = "dataset view - mesh" protected
Definition at line 89 of file DatasetView.hpp.
Referenced by DatasetView(), and getMeshView().
reproMode
ReprojectionMode sibr::DatasetView::reproMode = MESH_TO_IMAGE protected
Current reprojection mode.
Definition at line 87 of file DatasetView.hpp.
The documentation for this class was generated from the following files:
src/core/view/DatasetView.hpp
src/core/view/DatasetView.cpp