SIBR: sibr::Camera Class Reference
sibr::Camera Class Reference
sibr_graphics
Represent a basic camera.
#include <Camera.hpp>
Public Types
typedef Transform3< float > Transform3f
Public Member Functions
SIBR_CLASS_PTR (Camera)
Camera (void)
Default constructor.
void set (const Vector3f &translation, const Quaternionf &rotation)
Set the camera pose.
void setLookAt (const Vector3f &eye, const Vector3f &center, const Vector3f &up)
Set the camera pose based on two points and a up vector.
void translate (const Vector3f &v)
Translate the camera.
void translate (const Vector3f &v, const Transform3f &ref)
Translate the camera with respect to a reference frame.
void position (const Vector3f &v)
Set the camera position.
const Vector3f & position (void) const
void rotate (const Quaternionf &rotation)
Rotate the camera.
void rotate (const Vector3f &v)
Rotate the camera.
void rotate (const Vector3f &v, const Transform3f &ref)
Rotate the camera with respect to a reference frame.
void rotation (const Vector3f &v)
Set the camera rotation.
void rotation (const Quaternionf &q)
Set the camera rotation.
const Quaternionf & rotation (void) const
void transform (const Transform3f &t)
Set the camera transform.
const Transform3f & transform (void) const
void fovy (float value)
Set the vertical field of view (in radians).
float fovy (void) const
void aspect (float value)
Set the aspect ratio.
float aspect (void) const
void znear (float value)
Set the near plane.
float znear (void) const
void zfar (float value)
Set the far plane.
float zfar (void) const
void orthoRight (float value)
Set the right frustum extent.
float orthoRight (void) const
void orthoTop (float value)
Set the top frustum extent.
float orthoTop (void) const
bool ortho (void) const
Vector3f dir (void) const
Vector3f up (void) const
Vector3f right (void) const
Vector3f project (const Vector3f &point3d) const
Project 3D point using perspective projection.
Vector3f unproject (const Vector3f &pixel2d) const
Back-project pixel coordinates and depth.
void perspective (float fovRad, float ratio, float znear, float zfar)
Update the projection parameters of the camera.
bool frustumTest (const Vector3f &position3d) const
Check if a point falls inside the camera frustum.
bool frustumTest (const Vector3f &position3d, const Vector2f &pixel2d) const
Check if a point falls inside the camera frustum.
Matrix4f model (void) const
Matrix4f view (void) const
virtual Matrix4f proj (void) const
const Matrix4f & viewproj (void) const
const Matrix4f & invViewproj (void) const
void principalPoint (const sibr::Vector2f &p)
Set the camera principal point.
void setStereoCam (bool isLeft, float focal, float iod)
Set stereo camera projection parameters.
void setOrthoCam (float right, float top)
Set orthographic camera projection parameters.
bool needSave () const
bool needVideoSave () const
std::string savePath () const
void setSavePath (std::string savePath)
Set the save destination path for renderings.
void setDebugVideo (const bool debug)
Toggle video saving.
Static Public Member Functions
static Camera interpolate (const Camera &from, const Camera &to, float dist01)
Interpolate between two cameras.
Protected Member Functions
void forceUpdateViewProj (void) const
Trigger a viewproj matrix udpate.
Protected Attributes
std::string _savePath
Save destination path when reocrding images.
bool _debugVideoFrames
Is video saving enabled or not.
Matrix4f _matViewProj
View projection matrix.
Matrix4f _invMatViewProj
Inverse projection matrix.
bool _dirtyViewProj
Does the camera matrix need an update.
Transform3f _transform
The camera pose.
float _fov
The vertical field of view (radians)
float _aspect
Aspect ratio.
float _znear
Near plane.
float _zfar
Far plane.
float _right
Frustum half width.
float _top
Frustum half height.
sibr::Vector2f _p = {0.5f, 0.5}
Principal point.
bool _isOrtho
Is the camera orthographic.
Detailed Description
Represent a basic camera.
Note
In practice, InputCamera is used most of the time
Definition at line 13 of file Camera.hpp.
Member Typedef Documentation
Transform3f
typedef Transform3<float> sibr::Camera::Transform3f
Definition at line 17 of file Camera.hpp.
Constructor & Destructor Documentation
Camera()
sibr::Camera::Camera (void) inline
Default constructor.
Definition at line 22 of file Camera.hpp.
Member Function Documentation
aspect() [1/2]
void sibr::Camera::aspect (float value) inline
Set the aspect ratio.
Parameters
value the new value
Definition at line 357 of file Camera.hpp.
References _aspect, and _dirtyViewProj.
Referenced by sibr::CameraRaycaster::computePixelDerivatives(), sibr::InteractiveCameraHandler::fromCamera(), sibr::Frustum::Frustum(), sibr::InteractiveCameraHandler::interpolate(), interpolate(), sibr::Orbit::interpolateOrbit(), sibr::InteractiveCameraHandler::onGUI(), sibr::operator<<(), sibr::operator>>(), rot90CC(), sibr::TrackBall::setCameraAttributes(), sibr::InteractiveCameraHandler::update(), and sibr::TrackBall::updateAspectWithViewport().
aspect() [2/2]
float sibr::Camera::aspect (void) const inline
Returns
the aspect ratio.
Definition at line 360 of file Camera.hpp.
References _aspect.
Referenced by sibr::InputCamera::InputCamera(), sibr::InputCamera::loadFromBinary(), sibr::InputCamera::loadNVM(), and sibr::InputCamera::saveToBinary().
dir()
Vector3f sibr::Camera::dir (void) const
Returns
the camera direction vector.
Definition at line 83 of file Camera.cpp.
References sibr::quatRotateVec(), and rotation().
Referenced by sibr::ULRV2View::chosen_cameras(), sibr::ULRView::chosen_cameras(), sibr::ULRV2View::chosen_cameras_angdist(), sibr::CameraRaycaster::computeClippingPlanes(), sibr::CameraRaycaster::computePixelDerivatives(), sibr::TrackBall::fromCamera(), sibr::InteractiveCameraHandler::fromCamera(), sibr::Frustum::Frustum(), frustumTest(), sibr::InputCamera::lookatString(), sibr::TrackBall::mapTo3Dplane(), sibr::ULRRenderer::process(), sibr::RaycastingCamera::projectImg_outside_frustum_correction(), rot90CC(), sibr::IBRBasicUtils::selectCamerasAngleWeight(), sibr::IBRBasicUtils::selectCamerasSimpleDist(), sibr::ShadowMapRenderer::ShadowMapRenderer(), sibr::TrackBall::updateBallCenter(), sibr::TrackBall::updateFromKeyboard(), sibr::Orbit::updateOrbitParametersCentered(), sibr::TrackBall::updateRadius(), sibr::TrackBall::updateRotationRoll(), sibr::TrackBall::updateRotationSphere(), sibr::TrackBall::updateTranslationPlane(), and sibr::TrackBall::updateTranslationZ().
forceUpdateViewProj()
void sibr::Camera::forceUpdateViewProj (void) const protected
Trigger a viewproj matrix udpate.
Definition at line 75 of file Camera.cpp.
References _dirtyViewProj, _invMatViewProj, _matViewProj, proj(), and view().
Referenced by invViewproj(), setLookAt(), and viewproj().
fovy() [1/2]
void sibr::Camera::fovy (float value) inline
Set the vertical field of view (in radians).
Parameters
value the new value
Definition at line 350 of file Camera.hpp.
References _dirtyViewProj, and _fov.
Referenced by sibr::CameraRaycaster::computePixelDerivatives(), sibr::InteractiveCameraHandler::fromCamera(), sibr::Frustum::Frustum(), interpolate(), sibr::TrackBall::load(), sibr::InteractiveCameraHandler::onGUI(), sibr::operator<<(), sibr::operator>>(), rot90CC(), sibr::TrackBall::save(), sibr::CameraRecorder::saveAsBundle(), and sibr::CameraRecorder::saveAsFRIBRBundle().
fovy() [2/2]
float sibr::Camera::fovy (void) const inline
Returns
the vertical field of view (in radians).
Definition at line 353 of file Camera.hpp.
References _fov.
Referenced by sibr::InputCamera::InputCamera(), sibr::InputCamera::loadFromBinary(), sibr::InputCamera::lookatString(), and sibr::InputCamera::toBundleString().
frustumTest() [1/2]
bool sibr::Camera::frustumTest (const Vector3f & position3d) const
Check if a point falls inside the camera frustum.
Parameters
position3d the point location in 3D
Returns
true if the point falls inside
Definition at line 70 of file Camera.cpp.
References project(), and xy().
Referenced by sibr::LabelsManager::renderLabels().
frustumTest() [2/2]
bool sibr::Camera::frustumTest (const Vector3f & position3d, const Vector2f & pixel2d) const
Check if a point falls inside the camera frustum.
Use this version if you already have the projected point.
Parameters
position3d the point location in 3D
pixel2d the projection location of the point in image space ([-1,1])
Returns
true if the point falls inside
Definition at line 65 of file Camera.cpp.
References dir(), and position().
interpolate()
Camera sibr::Camera::interpolate (const Camera & from, const Camera & to, float dist01) static
Interpolate between two cameras.
Parameters
from start camera
to end camera
dist01 the interpolation factor
Returns
a camera with interpolated parameters
Definition at line 107 of file Camera.cpp.
References _transform, aspect(), fovy(), sibr::Transform3< float >::interpolate(), ortho(), orthoRight(), orthoTop(), zfar(), and znear().
Referenced by sibr::InteractiveCameraHandler::interpolate(), sibr::InteractiveCameraHandler::update(), and sibr::CameraRecorder::use().
invViewproj()
const Matrix4f & sibr::Camera::invViewproj (void) const inline
Returns
the camera inverse view-proj matrix (cached).
Definition at line 407 of file Camera.hpp.
References _dirtyViewProj, _invMatViewProj, and forceUpdateViewProj().
Referenced by sibr::AddShadowRenderer::process(), sibr::ShadowMapRenderer::ShadowMapRenderer(), and unproject().
model()
Matrix4f sibr::Camera::model (void) const inline
Returns
the camera model matrix (for camera stub rendering for instance).
Definition at line 194 of file Camera.hpp.
needSave()
bool sibr::Camera::needSave () const inline
Returns
true if the rendering generated with the camera be saved.
Definition at line 235 of file Camera.hpp.
needVideoSave()
bool sibr::Camera::needVideoSave () const inline
Returns
true if the rendering generated with the camera be saved as a frame.
Definition at line 238 of file Camera.hpp.
ortho()
bool sibr::Camera::ortho (void) const inline
Returns
true if the camera is orthographic.
Definition at line 395 of file Camera.hpp.
References _isOrtho.
Referenced by interpolate(), sibr::TrackBall::mapTo3Dplane(), sibr::FPSCamera::moveUsingWASD(), proj(), sibr::TrackBall::updateBallCenter(), sibr::TrackBall::updateRadius(), and sibr::TrackBall::updateTranslationPlane().
orthoRight() [1/2]
void sibr::Camera::orthoRight (float value) inline
Set the right frustum extent.
Parameters
value the new value
Definition at line 382 of file Camera.hpp.
References _dirtyViewProj, and _right.
Referenced by interpolate(), sibr::TrackBall::mapTo3Dplane(), sibr::FPSCamera::moveUsingWASD(), sibr::ShadowMapRenderer::ShadowMapRenderer(), sibr::TrackBall::updateBallCenter(), sibr::TrackBall::updateRadius(), and sibr::TrackBall::updateTranslationPlane().
orthoRight() [2/2]
float sibr::Camera::orthoRight (void) const inline
Returns
the right frustum distance
Definition at line 385 of file Camera.hpp.
References _right.
orthoTop() [1/2]
void sibr::Camera::orthoTop (float value) inline
Set the top frustum extent.
Parameters
value the new value
Definition at line 389 of file Camera.hpp.
References _dirtyViewProj, and _top.
Referenced by interpolate(), sibr::TrackBall::mapTo3Dplane(), sibr::FPSCamera::moveUsingWASD(), sibr::TrackBall::updateBallCenter(), sibr::TrackBall::updateRadius(), and sibr::TrackBall::updateTranslationPlane().
orthoTop() [2/2]
float sibr::Camera::orthoTop (void) const inline
Returns
the top frustum distance
Definition at line 392 of file Camera.hpp.
References _top.
perspective()
void sibr::Camera::perspective (float fovRad, float ratio, float znear, float zfar)
Update the projection parameters of the camera.
Parameters
fovRad the vertical field ov view in radians
ratio the aspect ratio
znear the near plane distance
zfar the far plane distance
Definition at line 34 of file Camera.cpp.
References _aspect, _dirtyViewProj, _fov, _zfar, _znear, zfar(), and znear().
position() [1/2]
void sibr::Camera::position (const Vector3f & v) inline
Set the camera position.
Parameters
v the new position
Definition at line 320 of file Camera.hpp.
References _dirtyViewProj, _transform, and sibr::Transform3< T >::position().
Referenced by sibr::CameraRaycaster::castForEachPixel(), sibr::ULRV2View::chosen_cameras(), sibr::ULRView::chosen_cameras(), sibr::ULRV2View::chosen_cameras_angdist(), sibr::ULRV2View::chosen_camerasNew(), sibr::CameraRaycaster::computeClippingPlanes(), sibr::CameraRaycaster::computePixelDerivatives(), sibr::CameraRaycaster::computeRayDir(), sibr::TrackBall::fromCamera(), sibr::InteractiveCameraHandler::fromCamera(), sibr::Frustum::Frustum(), sibr::generateCamFrustum(), sibr::generateCamQuadWithUvs(), legacyV2main(), sibr::TrackBall::mapTo3Dplane(), sibr::ULRV2Renderer::process(), sibr::ULRRenderer::process(), sibr::MeshRenderer::render(), sibr::StereoAnaglyphRdrMode::render(), sibr::ULRV3Renderer::renderBlending(), sibr::InputCamera::resizedH(), sibr::InputCamera::resizedW(), rot90CC(), sibr::TrackBall::save(), sibr::CameraRecorder::saveAsBundle(), sibr::CameraRecorder::saveAsFRIBRBundle(), sibr::IBRBasicUtils::selectCamerasAngleWeight(), sibr::IBRBasicUtils::selectCamerasSimpleDist(), sibr::MeshShadingShader::setUniforms(), sibr::FPSCamera::snap(), sibr::TrackBall::updateBallCenter(), sibr::TrackBall::updateFromKeyboard(), sibr::Orbit::updateOrbitParameters(), sibr::Orbit::updateOrbitParametersCentered(), sibr::TrackBall::updateRadius(), sibr::TrackBall::updateRotationRoll(), sibr::TrackBall::updateRotationSphere(), sibr::TrackBall::updateTranslationPlane(), and sibr::TrackBall::updateTranslationZ().
position() [2/2]
const Vector3f & sibr::Camera::position (void) const inline
Returns
the camer position.
Definition at line 323 of file Camera.hpp.
References _transform, and sibr::Transform3< T >::position().
Referenced by frustumTest(), sibr::RaycastingCamera::getRay(), sibr::InputCamera::InputCamera(), sibr::InputCamera::loadBundleFRIBR(), sibr::InputCamera::loadColmap(), sibr::InputCamera::loadFromBinary(), sibr::InputCamera::loadMeshroom(), sibr::InputCamera::lookatString(), sibr::RaycastingCamera::projectImg_outside_frustum_correction(), sibr::RaycastingCamera::RaycastingCamera(), sibr::InputCamera::resizedH(), sibr::InputCamera::resizedW(), sibr::InputCamera::saveToBinary(), and sibr::InputCamera::toBundleString().
principalPoint()
void sibr::Camera::principalPoint (const sibr::Vector2f & p) inline
Set the camera principal point.
Parameters
p the principal point, expressed in [0,1]
Definition at line 378 of file Camera.hpp.
References _dirtyViewProj, and _p.
Referenced by sibr::InputCamera::InputCamera().
proj()
Matrix4f sibr::Camera::proj (void) const virtual
Returns
the camera projection matrix.
Definition at line 98 of file Camera.cpp.
References _aspect, _fov, _p, _right, _top, _zfar, _znear, ortho(), sibr::orthographic(), and sibr::perspective().
Referenced by forceUpdateViewProj().
project()
Vector3f sibr::Camera::project (const Vector3f & point3d) const
Project 3D point using perspective projection.
Parameters
point3d 3D point
Returns
pixel coordinates in [-1,1] and depth in [-1,1]
Definition at line 43 of file Camera.cpp.
References viewproj().
Referenced by frustumTest(), sibr::RaycastingCamera::projectImg_outside_frustum_correction(), sibr::InputCamera::projectImgSpaceInvertY(), sibr::InputCamera::projectScreen(), and sibr::LabelsManager::renderLabels().
right()
Vector3f sibr::Camera::right (void) const
Returns
the camera right vector.
Definition at line 93 of file Camera.cpp.
References sibr::quatRotateVec(), and rotation().
Referenced by sibr::TrackBall::mapTo3Dplane(), sibr::StereoAnaglyphRdrMode::render(), rot90CC(), setOrthoCam(), sibr::TrackBall::updateBallCenter(), sibr::TrackBall::updateFromKeyboard(), sibr::Orbit::updateOrbitParametersCentered(), and sibr::TrackBall::updateTranslationPlane().
rotate() [1/3]
void sibr::Camera::rotate (const Quaternionf & rotation) inline
Rotate the camera.
Parameters
rotation the quaternion rotation to apply
Definition at line 327 of file Camera.hpp.
References _dirtyViewProj, _transform, sibr::Transform3< T >::rotate(), and rotation().
Referenced by sibr::FPSCamera::moveUsingWASD().
rotate() [2/3]
void sibr::Camera::rotate (const Vector3f & v) inline
Rotate the camera.
Parameters
v the euler angles to apply
Definition at line 330 of file Camera.hpp.
References _dirtyViewProj, _transform, and sibr::Transform3< T >::rotate().
rotate() [3/3]
void sibr::Camera::rotate (const Vector3f & v, const Transform3f & ref) inline
Rotate the camera with respect to a reference frame.
Parameters
v the rotation euler angles
ref the reference frame
Definition at line 333 of file Camera.hpp.
References _dirtyViewProj, _transform, and sibr::Transform3< T >::rotate().
rotation() [1/3]
void sibr::Camera::rotation (const Quaternionf & q) inline
Set the camera rotation.
Parameters
q the new rotation
Definition at line 340 of file Camera.hpp.
References _dirtyViewProj, _transform, and sibr::Transform3< T >::rotation().
rotation() [2/3]
void sibr::Camera::rotation (const Vector3f & v) inline
Set the camera rotation.
Parameters
v the new rotation euler angles
Definition at line 337 of file Camera.hpp.
References _dirtyViewProj, _transform, and sibr::Transform3< T >::rotation().
Referenced by sibr::InputCamera::resizedH(), sibr::InputCamera::resizedW(), sibr::CameraRecorder::saveAsBundle(), sibr::CameraRecorder::saveAsFRIBRBundle(), sibr::IBRBasicUtils::selectCamerasAngleWeight(), and sibr::FPSCamera::snap().
rotation() [3/3]
const Quaternionf & sibr::Camera::rotation (void) const inline
Returns
the camera rotation.
Definition at line 344 of file Camera.hpp.
References _transform, and sibr::Transform3< T >::rotation().
Referenced by dir(), sibr::InputCamera::InputCamera(), sibr::InputCamera::loadBundleFRIBR(), sibr::InputCamera::loadFromBinary(), sibr::InputCamera::loadLookat(), sibr::InputCamera::loadMeshroom(), sibr::InputCamera::resizedH(), sibr::InputCamera::resizedW(), right(), rotate(), sibr::InputCamera::saveToBinary(), set(), setLookAt(), and up().
savePath()
std::string sibr::Camera::savePath () const inline
Returns
the save destination path for renderings
Definition at line 241 of file Camera.hpp.
set()
void sibr::Camera::set (const Vector3f & translation, const Quaternionf & rotation) inline
Set the camera pose.
Parameters
translation the camera translation
rotation the camera rotation
Definition at line 297 of file Camera.hpp.
References _dirtyViewProj, _transform, rotation(), and sibr::Transform3< T >::set().
Referenced by sibr::InputCamera::readFromFile().
setDebugVideo()
void sibr::Camera::setDebugVideo (const bool debug) inline
Toggle video saving.
Todo:
Cleanup naming.
Parameters
debug if true, saving frames
Definition at line 252 of file Camera.hpp.
Referenced by sibr::CameraRecorder::use().
setLookAt()
void sibr::Camera::setLookAt (const Vector3f & eye, const Vector3f & center, const Vector3f & up) inline
Set the camera pose based on two points and a up vector.
Parameters
eye the camera position
center the camera target point
up the camera up vector
Definition at line 301 of file Camera.hpp.
References _transform, forceUpdateViewProj(), rotation(), sibr::Transform3< T >::set(), and up().
Referenced by sibr::TrackBall::fromBoundingBox(), sibr::Orbit::interpolateOrbit(), sibr::MultiMeshManager::list_mesh_onGUI(), sibr::TrackBall::load(), rot90CC(), sibr::TrackBall::updateBallCenter(), sibr::TrackBall::updateFromKeyboard(), sibr::TrackBall::updateRadius(), sibr::TrackBall::updateRotationRoll(), sibr::TrackBall::updateRotationSphere(), sibr::TrackBall::updateTranslationPlane(), and sibr::TrackBall::updateTranslationZ().
setOrthoCam()
void sibr::Camera::setOrthoCam (float right, float top)
Set orthographic camera projection parameters.
Parameters
right the right frustum extent
top the top frustum extent
Definition at line 130 of file Camera.cpp.
References _dirtyViewProj, _invMatViewProj, _isOrtho, _matViewProj, _right, _top, _zfar, _znear, sibr::orthographic(), right(), and view().
setSavePath()
void sibr::Camera::setSavePath (std::string savePath) inline
Set the save destination path for renderings.
Parameters
savePath the new path
Definition at line 246 of file Camera.hpp.
Referenced by sibr::CameraRecorder::use().
setStereoCam()
void sibr::Camera::setStereoCam (bool isLeft, float focal, float iod)
Set stereo camera projection parameters.
Parameters
isLeft is the camera for the left eye (else right)
focal the focal distance
iod the inter ocular distance
Definition at line 124 of file Camera.cpp.
References _aspect, _fov, _invMatViewProj, _matViewProj, _zfar, _znear, sibr::perspectiveStereo(), and view().
Referenced by sibr::StereoAnaglyphRdrMode::render().
SIBR_CLASS_PTR()
sibr::Camera::SIBR_CLASS_PTR (Camera)
transform() [1/2]
void sibr::Camera::transform (const Transform3f & t)
Set the camera transform.
Parameters
t the new transform
Definition at line 140 of file Camera.cpp.
References _dirtyViewProj, and _transform.
Referenced by sibr::InteractiveCameraHandler::fromTransform(), sibr::FPSCamera::moveUsingMousePan(), sibr::FPSCamera::moveUsingWASD(), sibr::operator<<(), sibr::operator>>(), sibr::MultiMeshManager::setIntialView(), and sibr::SceneDebugView::setup().
transform() [2/2]
const Transform3f & sibr::Camera::transform (void) const inline
Returns
the camera transform.
Definition at line 293 of file Camera.hpp.
References _transform.
Referenced by sibr::InputCamera::toBundleString(), and sibr::InputCamera::writeToFile().
translate() [1/2]
void sibr::Camera::translate (const Vector3f & v) inline
Translate the camera.
Parameters
v the translation
Definition at line 314 of file Camera.hpp.
References _dirtyViewProj, _transform, and sibr::Transform3< T >::translate().
Referenced by sibr::FPSCamera::moveUsingMousePan(), and sibr::FPSCamera::moveUsingWASD().
translate() [2/2]
void sibr::Camera::translate (const Vector3f & v, const Transform3f & ref) inline
Translate the camera with respect to a reference frame.
Parameters
v the translation
ref the reference frame
Definition at line 317 of file Camera.hpp.
References _dirtyViewProj, _transform, and sibr::Transform3< T >::translate().
unproject()
Vector3f sibr::Camera::unproject (const Vector3f & pixel2d) const
Back-project pixel coordinates and depth.
Parameters
pixel2d pixel coordinates p[0],p[1] in [-1,1] and depth p[2] in [-1,1]
Returns
3D point
Definition at line 56 of file Camera.cpp.
References invViewproj().
Referenced by sibr::RaycastingCamera::RaycastingCamera(), and sibr::InputCamera::unprojectImgSpaceInvertY().
up()
Vector3f sibr::Camera::up (void) const
Returns
the camera up vector.
Definition at line 88 of file Camera.cpp.
References sibr::quatRotateVec(), and rotation().
Referenced by sibr::CameraRaycaster::computePixelDerivatives(), sibr::Frustum::Frustum(), sibr::InputCamera::lookatString(), sibr::TrackBall::mapTo3Dplane(), sibr::TrackBall::save(), sibr::InputCamera::saveAsLookat(), setLookAt(), sibr::TrackBall::updateBallCenter(), sibr::TrackBall::updateFromKeyboard(), sibr::Orbit::updateOrbitParameters(), sibr::Orbit::updateOrbitParametersCentered(), sibr::TrackBall::updateRadius(), sibr::TrackBall::updateRotationRoll(), sibr::TrackBall::updateRotationSphere(), sibr::TrackBall::updateTranslationPlane(), and sibr::TrackBall::updateTranslationZ().
view()
Matrix4f sibr::Camera::view (void) const inline
Returns
the camera view matrix.
Definition at line 197 of file Camera.hpp.
Referenced by forceUpdateViewProj(), sibr::Skybox::render(), sibr::NormalRenderer::render(), setOrthoCam(), setStereoCam(), and sibr::TrackBall::updateRotationSphere().
viewproj()
const Matrix4f & sibr::Camera::viewproj (void) const inline
Returns
the camera view-proj matrix (cached).
Definition at line 400 of file Camera.hpp.
References _dirtyViewProj, _matViewProj, and forceUpdateViewProj().
Referenced by sibr::Intersector2D::frustrumQuadsIntersect(), sibr::BinaryMeshRenderer::process(), sibr::ColoredMeshRenderer::process(), sibr::TexturedMeshRenderer::process(), sibr::ULRV2Renderer::process(), sibr::ULRRenderer::process(), project(), sibr::PositionRenderer::render(), sibr::MeshRenderer::render(), sibr::DepthRenderer::render(), sibr::NormalRenderer::render(), sibr::ShadowMapRenderer::render(), sibr::ImageCamViewer::renderImage(), sibr::ULRV3Renderer::renderProxyDepth(), sibr::ShaderAlphaMVP::setUniforms(), and sibr::ShadowMapRenderer::ShadowMapRenderer().
zfar() [1/2]
void sibr::Camera::zfar (float value) inline
Set the far plane.
Parameters
value the new value
Definition at line 371 of file Camera.hpp.
References _dirtyViewProj, and _zfar.
Referenced by sibr::MultiMeshManager::addMeshData(), sibr::CameraRaycaster::computeClippingPlanes(), sibr::TrackBall::fromBoundingBox(), sibr::TrackBall::fromCamera(), sibr::InteractiveCameraHandler::fromCamera(), sibr::Frustum::Frustum(), sibr::generateCamFrustum(), interpolate(), sibr::TrackBall::load(), main(), sibr::InteractiveCameraHandler::onGUI(), sibr::operator<<(), sibr::operator>>(), sibr::InputCamera::resizedH(), sibr::InputCamera::resizedW(), sibr::TrackBall::save(), sibr::InteractiveCameraHandler::setClippingPlanes(), sibr::InteractiveCameraHandler::setup(), sibr::InteractiveCameraHandler::update(), sibr::TrackBall::updateZnearZFar(), and sibr::CameraRecorder::use().
zfar() [2/2]
float sibr::Camera::zfar (void) const inline
Returns
the far plane distance
Definition at line 374 of file Camera.hpp.
References _zfar.
Referenced by sibr::InputCamera::loadFromBinary(), sibr::InputCamera::loadLookat(), sibr::InputCamera::lookatString(), perspective(), sibr::InputCamera::resizedH(), sibr::InputCamera::resizedW(), and sibr::InputCamera::saveToBinary().
znear() [1/2]
void sibr::Camera::znear (float value) inline
Set the near plane.
Parameters
value the new value
Definition at line 364 of file Camera.hpp.
References _dirtyViewProj, and _znear.
Referenced by sibr::CameraRaycaster::computeClippingPlanes(), sibr::TrackBall::fromCamera(), sibr::InteractiveCameraHandler::fromCamera(), sibr::Frustum::Frustum(), sibr::generateCamFrustum(), interpolate(), sibr::TrackBall::load(), main(), sibr::InteractiveCameraHandler::onGUI(), sibr::operator<<(), sibr::operator>>(), sibr::ULRRenderer::process(), sibr::InputCamera::resizedH(), sibr::InputCamera::resizedW(), sibr::TrackBall::save(), sibr::InteractiveCameraHandler::setClippingPlanes(), sibr::InteractiveCameraHandler::setup(), sibr::InteractiveCameraHandler::update(), sibr::TrackBall::updateZnearZFar(), and sibr::CameraRecorder::use().
znear() [2/2]
float sibr::Camera::znear (void) const inline
Returns
the near plane distance
Definition at line 367 of file Camera.hpp.
References _znear.
Referenced by sibr::InputCamera::loadFromBinary(), sibr::InputCamera::loadLookat(), sibr::InputCamera::lookatString(), perspective(), sibr::InputCamera::resizedH(), sibr::InputCamera::resizedW(), and sibr::InputCamera::saveToBinary().
Member Data Documentation
_aspect
float sibr::Camera::_aspect protected
Aspect ratio.
Definition at line 267 of file Camera.hpp.
Referenced by aspect(), perspective(), proj(), sibr::InputCamera::resizedH(), sibr::InputCamera::resizedW(), sibr::InputCamera::saveToBinary(), and setStereoCam().
_debugVideoFrames
bool sibr::Camera::_debugVideoFrames protected
Is video saving enabled or not.
Todo:
Cleanup.
Definition at line 260 of file Camera.hpp.
_dirtyViewProj
bool sibr::Camera::_dirtyViewProj mutable protected
Does the camera matrix need an update.
Definition at line 263 of file Camera.hpp.
Referenced by aspect(), forceUpdateViewProj(), fovy(), invViewproj(), orthoRight(), orthoTop(), perspective(), position(), principalPoint(), rotate(), rotation(), set(), setOrthoCam(), transform(), translate(), viewproj(), zfar(), and znear().
_fov
float sibr::Camera::_fov protected
The vertical field of view (radians)
Definition at line 266 of file Camera.hpp.
Referenced by fovy(), perspective(), proj(), sibr::InputCamera::saveToBinary(), and setStereoCam().
_invMatViewProj
Matrix4f sibr::Camera::_invMatViewProj mutable protected
Inverse projection matrix.
Definition at line 262 of file Camera.hpp.
Referenced by forceUpdateViewProj(), invViewproj(), setOrthoCam(), and setStereoCam().
_isOrtho
bool sibr::Camera::_isOrtho protected
Is the camera orthographic.
Definition at line 273 of file Camera.hpp.
Referenced by ortho(), and setOrthoCam().
_matViewProj
Matrix4f sibr::Camera::_matViewProj mutable protected
View projection matrix.
Definition at line 261 of file Camera.hpp.
Referenced by forceUpdateViewProj(), setOrthoCam(), setStereoCam(), and viewproj().
_p
sibr::Vector2f sibr::Camera::_p = {0.5f, 0.5} protected
Principal point.
Definition at line 272 of file Camera.hpp.
Referenced by principalPoint(), and proj().
_right
float sibr::Camera::_right protected
Frustum half width.
Definition at line 270 of file Camera.hpp.
Referenced by orthoRight(), proj(), and setOrthoCam().
_savePath
std::string sibr::Camera::_savePath protected
Save destination path when reocrding images.
Definition at line 259 of file Camera.hpp.
_top
float sibr::Camera::_top protected
Frustum half height.
Definition at line 271 of file Camera.hpp.
Referenced by orthoTop(), proj(), and setOrthoCam().
_transform
Transform3f sibr::Camera::_transform protected
The camera pose.
Definition at line 265 of file Camera.hpp.
Referenced by interpolate(), position(), rotate(), rotation(), set(), setLookAt(), transform(), and translate().
_zfar
float sibr::Camera::_zfar protected
Far plane.
Definition at line 269 of file Camera.hpp.
Referenced by perspective(), proj(), sibr::InputCamera::saveToBinary(), setOrthoCam(), setStereoCam(), and zfar().
_znear
float sibr::Camera::_znear protected
Near plane.
Definition at line 268 of file Camera.hpp.
Referenced by perspective(), proj(), sibr::InputCamera::saveToBinary(), setOrthoCam(), setStereoCam(), and znear().
The documentation for this class was generated from the following files:
src/core/graphics/Camera.hpp
src/core/graphics/Camera.cpp