SIBR: sibr::Resources Class Reference
sibr::Resources Class Reference
sibr_assets
Singleton used to store a list of plausible path to look for (based on the ibr_resources.ini)
#include <Resources.hpp>
Public Member Functions
std::string getResourceFilePathName (std::string const &filename, bool &success)
Look for the filename into plausible resource paths.
std::string getResourceFilePathName (std::string const &filename)
Look for the filename into plausible resource paths.
Static Public Member Functions
static Resources * Instance ()
Our singleton.
Protected Member Functions
Resources ()
Constructor.
virtual ~Resources ()
Destructor.
Protected Attributes
std::vector< std::string > _rscPaths
List of directories to check into.
Static Protected Attributes
static Resources * _instance = NULL
Singleton.
Detailed Description
Singleton used to store a list of plausible path to look for (based on the ibr_resources.ini)
Definition at line 14 of file Resources.hpp.
Constructor & Destructor Documentation
Resources()
sibr::Resources::Resources () protected
Constructor.
Definition at line 24 of file Resources.cpp.
References _rscPaths, sibr::getInstallDirectory(), ibr_convert_old_to_new::line, and ibr_preprocess_rc_to_sibr::replace().
Referenced by Instance().
~Resources()
sibr::Resources::~Resources () protected virtual
Destructor.
Definition at line 69 of file Resources.cpp.
Member Function Documentation
getResourceFilePathName() [1/2]
std::string sibr::Resources::getResourceFilePathName (std::string const & filename)
Look for the filename into plausible resource paths.
Parameters
filename file name
Returns
the full file path
Definition at line 87 of file Resources.cpp.
References getResourceFilePathName().
getResourceFilePathName() [2/2]
std::string sibr::Resources::getResourceFilePathName (std::string const & filename, bool & success)
Look for the filename into plausible resource paths.
Parameters
filename file name
success was the file found in the registered locations
Returns
the full file path
Definition at line 73 of file Resources.cpp.
References _rscPaths, and sibr::getInstallDirectory().
Referenced by getResourceFilePathName(), and sibr::DepthInputTextureArray::initDepthTextureArrays().
Instance()
Resources * sibr::Resources::Instance () static
Our singleton.
Definition at line 17 of file Resources.cpp.
References _instance, and Resources().
Referenced by sibr::DepthRenderer::DepthRenderer(), sibr::DepthInputTextureArray::initDepthTextureArrays(), sibr::RGBDInputTextures::initializeDepthRenderTargets(), sibr::RGBDInputTextures::initializeImageRenderTargets(), sibr::ImageCamViewer::initImageCamShaders(), sibr::Skybox::load(), sibr::MonoRdrMode::MonoRdrMode(), sibr::NormalRenderer::NormalRenderer(), sibr::PositionRenderer::PositionRenderer(), sibr::LabelsManager::setupLabelsManagerShader(), sibr::ShadowMapRenderer::ShadowMapRenderer(), sibr::StereoAnaglyphRdrMode::StereoAnaglyphRdrMode(), and sibr::RenderMaskHolder::uploadMaskGPU().
Member Data Documentation
_instance
Resources * sibr::Resources::_instance = NULL static protected
Singleton.
Definition at line 43 of file Resources.hpp.
Referenced by Instance().
_rscPaths
std::vector<std::string> sibr::Resources::_rscPaths protected
List of directories to check into.
Definition at line 42 of file Resources.hpp.
Referenced by getResourceFilePathName(), and Resources().
The documentation for this class was generated from the following files:
src/core/assets/Resources.hpp
src/core/assets/Resources.cpp