SIBR: sibr::Orbit Class Reference
sibr::Orbit Class Reference
sibr_view
Interactive camera that allow the user to roate around an object using the keypad.
#include <Orbit.hpp>
Classes
struct OrbitParameters
Internal orbit parameters.
Public Member Functions
Orbit (void)
Create an orbit centered at (0,0,0) with basic initial parameters.
void fromCamera (const sibr::InputCamera &cam, const std::shared_ptr< sibr::Raycaster > raycaster)
Setup the orbit so that its camera has the same pose as the argument camera.
void update (const sibr::Input &input, const std::shared_ptr< sibr::Raycaster > raycaster=std::shared_ptr< sibr::Raycaster >())
virtual void update (const sibr::Input &input, const float deltaTime, const Viewport &viewport) override
Update the camera handler state.
virtual const sibr::InputCamera & getCamera (void) const override
Public Member Functions inherited from sibr::ICameraHandler
virtual void onRender (const sibr::Viewport &viewport)
Render on top of the associated view(s).
virtual void onGUI (const std::string &windowName)
Display GUI options and infos.
Private Member Functions
void interpolateOrbit ()
Compute new camera pose from current orbit parameters.
void updateOrbitParameters (const sibr::Input &input, const std::shared_ptr< sibr::Raycaster > raycaster)
Updates the orbit's center and camera pose, by casting a ray from the clicked point (in Input) to the mesh.
void updateOrbitParametersCentered (const std::shared_ptr< sibr::Raycaster > raycaster)
Updates the orbit's center and camera pose, by casting a ray from the center of the screen to the mesh.
Static Private Member Functions
static sibr::Vector4f computeFittingPlaneCameras (sibr::Vector3f &clickedPoint, const std::vector< InputCamera::Ptr > &cams)
Compute the best fitting plane of the clicked points plus the input cams positions.
Private Attributes
bool _hasBeenInitialized
Has the orbit been initialized.
bool _orbitPointClicked
Has the user clicked on a point in the scene.
sibr::InputCamera _currentCamera
Current camera.
OrbitParameters _orbit
Parameters.
Detailed Description
Interactive camera that allow the user to roate around an object using the keypad.
Commands:
to enable/disable the orbit (note that using at least once (atl + click) to retrieve a 3D point on the proxy is mandatory before enabling the orbit) : b in static mode (default mode) : 5 to flip the orbit (might be the first thing to do if all commands seem broken/reversed, it is needed because there is an ambiguity when using the normal of the plan containing the input cameras and the clicked point) 4 or 6 to rotate towards current camera x-axis 2 or 8 to rotate towards current camera y-axis 7 or 9 to rotate towards current camera z-axis 1 or 3 to zoom in or out in dynamic mode (rotates without interruption around an axis) : alt + (4 or 6) to rotate towards current camera x-axis alt + (2 or 8) to rotate towards current camera y-axis alt + (7 or 9) to rotate towards current camera z-axis 5 to inverse the direction (same axis) 0 to switch back to static mode with initial camera . to switch back to static mode with current camera
Definition at line 40 of file Orbit.hpp.
Constructor & Destructor Documentation
Orbit()
sibr::Orbit::Orbit (void)
Create an orbit centered at (0,0,0) with basic initial parameters.
It is recommended to call fromCamera after that to setup the orbit with a valid set of parameters.
Definition at line 14 of file Orbit.cpp.
References sibr::UIShortcuts::add(), and sibr::UIShortcuts::global().
Member Function Documentation
computeFittingPlaneCameras()
sibr::Vector4f sibr::Orbit::computeFittingPlaneCameras (sibr::Vector3f & clickedPoint, const std::vector< InputCamera::Ptr > & cams) static private
Compute the best fitting plane of the clicked points plus the input cams positions.
Parameters
clickedPoint point clicked by the user
cams reference cameras
Definition at line 275 of file Orbit.cpp.
fromCamera()
void sibr::Orbit::fromCamera (const sibr::InputCamera & cam, const std::shared_ptr< sibr::Raycaster > raycaster)
Setup the orbit so that its camera has the same pose as the argument camera.
A raycaster is required to find the center of the orbit.
Parameters
cam the reference camera
raycaster raycaster to use for centering intersection tests.
Definition at line 243 of file Orbit.cpp.
References _currentCamera, _hasBeenInitialized, _orbit, _orbitPointClicked, sibr::Orbit::OrbitParameters::initialCamera, and updateOrbitParametersCentered().
Referenced by sibr::InteractiveCameraHandler::fromCamera().
getCamera()
const sibr::InputCamera & sibr::Orbit::getCamera (void) const override virtual
Returns
the current camera.
Implements sibr::ICameraHandler.
Definition at line 233 of file Orbit.cpp.
References _currentCamera, _hasBeenInitialized, and SIBR_ERR.
Referenced by sibr::InteractiveCameraHandler::update().
interpolateOrbit()
void sibr::Orbit::interpolateOrbit () private
Compute new camera pose from current orbit parameters.
Definition at line 137 of file Orbit.cpp.
References _currentCamera, _orbit, sibr::Camera::aspect(), sibr::Orbit::OrbitParameters::center, sibr::Orbit::OrbitParameters::direction, sibr::Orbit::OrbitParameters::factor, sibr::Orbit::OrbitParameters::FORWARD_X, sibr::Orbit::OrbitParameters::FORWARD_Y, sibr::Orbit::OrbitParameters::FORWARD_Z, sibr::InputCamera::h(), sibr::Orbit::OrbitParameters::initialCamera, sibr::Orbit::OrbitParameters::keepCamera, sibr::Orbit::OrbitParameters::phi, sibr::Orbit::OrbitParameters::radius, sibr::Orbit::OrbitParameters::roll, sibr::Camera::setLookAt(), SIBR_2PI, SIBR_ORBIT_INTERPOLATE_FRAMES, sibr::Orbit::OrbitParameters::STATIC, sibr::Orbit::OrbitParameters::status, sibr::Orbit::OrbitParameters::theta, sibr::InputCamera::w(), sibr::Orbit::OrbitParameters::xAxis, sibr::Orbit::OrbitParameters::yAxis, and sibr::Orbit::OrbitParameters::zAxis.
Referenced by update().
update() [1/2]
void sibr::Orbit::update (const sibr::Input & input, const float deltaTime, const Viewport & viewport) override virtual
Update the camera handler state.
Parameters
input user input
deltaTime time elapsed since last udpate
viewport view viewport
Implements sibr::ICameraHandler.
Definition at line 228 of file Orbit.cpp.
References update().
update() [2/2]
void sibr::Orbit::update (const sibr::Input & input, const std::shared_ptr< sibr::Raycaster > raycaster = std::shared_ptr<sibr::Raycaster>())
Update the orbit camera based on the user input (keyboard). Can require a raycaster if the user is alt-clicking to select a new orbit center.
Parameters
input user input
raycaster optional raycaster
Definition at line 30 of file Orbit.cpp.
References _hasBeenInitialized, _orbit, sibr::Orbit::OrbitParameters::ACW, sibr::Orbit::OrbitParameters::CW, sibr::Orbit::OrbitParameters::direction, sibr::Key::F, sibr::Orbit::OrbitParameters::flip(), sibr::Orbit::OrbitParameters::FORWARD_X, sibr::Orbit::OrbitParameters::FORWARD_Y, sibr::Orbit::OrbitParameters::FORWARD_Z, interpolateOrbit(), sibr::InputState< TNbState, TEnum >::isActivated(), sibr::InputState< TNbState, TEnum >::isReleased(), sibr::Orbit::OrbitParameters::keepCamera, sibr::Input::key(), sibr::Key::KPDecimal, sibr::Key::KPNum0, sibr::Key::KPNum1, sibr::Key::KPNum2, sibr::Key::KPNum3, sibr::Key::KPNum4, sibr::Key::KPNum5, sibr::Key::KPNum6, sibr::Key::KPNum7, sibr::Key::KPNum8, sibr::Key::KPNum9, sibr::Mouse::Left, sibr::Key::LeftAlt, sibr::Input::mouseButton(), sibr::Key::Num0, sibr::Key::Num1, sibr::Key::Num2, sibr::Key::Num3, sibr::Key::Num4, sibr::Key::Num5, sibr::Key::Num6, sibr::Key::Num7, sibr::Key::Num8, sibr::Key::Num9, sibr::Orbit::OrbitParameters::phi, sibr::Orbit::OrbitParameters::radius, sibr::Orbit::OrbitParameters::roll, sibr::Orbit::OrbitParameters::STATIC, sibr::Orbit::OrbitParameters::status, sibr::Orbit::OrbitParameters::theta, and updateOrbitParameters().
Referenced by update(), and sibr::InteractiveCameraHandler::update().
updateOrbitParameters()
void sibr::Orbit::updateOrbitParameters (const sibr::Input & input, const std::shared_ptr< sibr::Raycaster > raycaster) private
Updates the orbit's center and camera pose, by casting a ray from the clicked point (in Input) to the mesh.
Parameters
input user input
raycaster scene raycaster
Definition at line 183 of file Orbit.cpp.
References _currentCamera, _orbit, _orbitPointClicked, sibr::Orbit::OrbitParameters::center, sibr::CameraRaycaster::computePixelDerivatives(), sibr::RayHit::dist(), sibr::RayHit::hitSomething(), sibr::Orbit::OrbitParameters::initialCamera, sibr::Raycaster::intersect(), sibr::Input::mousePosition(), sibr::Camera::position(), sibr::Orbit::OrbitParameters::radius, sibr::Camera::up(), sibr::Orbit::OrbitParameters::xAxis, sibr::Orbit::OrbitParameters::yAxis, and sibr::Orbit::OrbitParameters::zAxis.
Referenced by update().
updateOrbitParametersCentered()
void sibr::Orbit::updateOrbitParametersCentered (const std::shared_ptr< sibr::Raycaster > raycaster) private
Updates the orbit's center and camera pose, by casting a ray from the center of the screen to the mesh.
Parameters
raycaster scene raycaster
Definition at line 256 of file Orbit.cpp.
References _currentCamera, _orbit, sibr::Orbit::OrbitParameters::center, sibr::Camera::dir(), sibr::RayHit::dist(), sibr::RayHit::hitSomething(), sibr::Orbit::OrbitParameters::initialCamera, sibr::Raycaster::intersect(), sibr::Camera::position(), sibr::Orbit::OrbitParameters::radius, sibr::Camera::right(), sibr::Camera::up(), sibr::Orbit::OrbitParameters::xAxis, sibr::Orbit::OrbitParameters::yAxis, and sibr::Orbit::OrbitParameters::zAxis.
Referenced by fromCamera().
Member Data Documentation
_currentCamera
sibr::InputCamera sibr::Orbit::_currentCamera private
Current camera.
Definition at line 142 of file Orbit.hpp.
Referenced by fromCamera(), getCamera(), interpolateOrbit(), updateOrbitParameters(), and updateOrbitParametersCentered().
_hasBeenInitialized
bool sibr::Orbit::_hasBeenInitialized private
Has the orbit been initialized.
Definition at line 140 of file Orbit.hpp.
Referenced by fromCamera(), getCamera(), and update().
_orbit
OrbitParameters sibr::Orbit::_orbit private
Parameters.
Definition at line 143 of file Orbit.hpp.
Referenced by fromCamera(), interpolateOrbit(), update(), updateOrbitParameters(), and updateOrbitParametersCentered().
_orbitPointClicked
bool sibr::Orbit::_orbitPointClicked private
Has the user clicked on a point in the scene.
Definition at line 141 of file Orbit.hpp.
Referenced by fromCamera(), and updateOrbitParameters().
The documentation for this class was generated from the following files:
src/core/view/Orbit.hpp
src/core/view/Orbit.cpp