SIBR: sibr::MeshTexturing Class Reference
sibr::MeshTexturing Class Reference
sibr_imgproc
Reproject images onto a mesh using the associated camera poses, and accumulate colors in UV-space to generate a texture map.
#include <MeshTexturing.hpp>
Public Types
enum Options : uint { NONE = 0, FLIP_VERTICAL = 1, FLOOD_FILL = 2, POISSON_FILL = 4 }
Export options.
Public Member Functions
MeshTexturing (unsigned int sideSize)
Constructor.
void setMesh (const sibr::Mesh::Ptr mesh)
Set the current mesh to texture.
void reproject (const std::vector< InputCamera::Ptr > &cameras, const std::vector< sibr::ImageRGB::Ptr > &images)
Reproject a set of images into the texture map, using the associated cameras.
sibr::ImageRGB::Ptr getTexture (uint options=NONE) const
Get the final result.
Static Public Member Functions
template<typename T_Type , unsigned int T_NumComp>
static Image< T_Type, T_NumComp >::Ptr floodFill (const Image< T_Type, T_NumComp > &image, const sibr::ImageL8 &mask)
Performs flood fill of an image, following a mask.
static sibr::ImageRGB32F::Ptr poissonFill (const sibr::ImageRGB32F &image, const sibr::ImageL8 &mask)
Performs poisson fill of an image, following a mask.
Private Member Functions
bool hitTest (int px, int py, RayHit &finalHit)
Test if the UV-space mesh covers a pixel of the texture map.
bool sampleNeighborhood (int px, int py, RayHit &hit)
Test if the UV-space mesh approximately covers a pixel of the texture map, by sampling a neighborhood in uv-space.
void interpolate (const sibr::RayHit &hit, sibr::Vector3f &vertex, sibr::Vector3f &normal) const
Compute the interpolated position and normal at the intersection point on the initial mesh.
Private Attributes
sibr::ImageRGB32F _accum
Color accumulator.
sibr::ImageL8 _mask
Mask indicating which regions of the texture map have been covered.
sibr::Mesh::Ptr _mesh
The original world-space mesh.
sibr::Raycaster _worldRaycaster
The world-space mesh raycaster.
sibr::Raycaster _uvsRaycaster
The uv-space mesh raycaster.
Detailed Description
Reproject images onto a mesh using the associated camera poses, and accumulate colors in UV-space to generate a texture map.
Definition at line 16 of file MeshTexturing.hpp.
Member Enumeration Documentation
Options
enum sibr::MeshTexturing::Options : uint
Export options.
Enumerator
NONE
FLIP_VERTICAL
Flip the final result.
FLOOD_FILL
Perform flood filling.
POISSON_FILL
Perform poisson filling (slow).
Definition at line 22 of file MeshTexturing.hpp.
Constructor & Destructor Documentation
MeshTexturing()
sibr::MeshTexturing::MeshTexturing (unsigned int sideSize)
Constructor.
Parameters
sideSize dimension of the texture
Definition at line 7 of file MeshTexturing.cpp.
Member Function Documentation
floodFill()
template<typename T_Type , unsigned int T_NumComp> static Image< T_Type, T_NumComp>::Ptr sibr::MeshTexturing::floodFill (const Image< T_Type, T_NumComp > & image, const sibr::ImageL8 & mask) inline static
Performs flood fill of an image, following a mask.
Parameters
image the image to fill
mask mask where the zeros regions will be filled
Returns
the filled image.
Definition at line 58 of file MeshTexturing.hpp.
References sibr::Image< T_Type, T_NumComp >::h(), SIBR_LOG, sibr::Image< T_Type, T_NumComp >::toOpenCV(), and sibr::Image< T_Type, T_NumComp >::w().
Referenced by getTexture().
getTexture()
sibr::ImageRGB::Ptr sibr::MeshTexturing::getTexture (uint options = NONE) const
Get the final result.
Parameters
options the options to apply to the generated texture map.
Definition at line 164 of file MeshTexturing.cpp.
References _accum, _mask, sibr::Image< T_Type, T_NumComp >::clone(), floodFill(), poissonFill(), and sibr::Image< T_Type, T_NumComp >::toOpenCV().
Referenced by main().
hitTest()
bool sibr::MeshTexturing::hitTest (int px, int py, RayHit & finalHit) private
Test if the UV-space mesh covers a pixel of the texture map.
Parameters
px pixel x coordinate
py pixel y coordinate
finalHit the hit information if there is coverage
Returns
true if there is coverage.
Definition at line 211 of file MeshTexturing.cpp.
References _accum, _uvsRaycaster, sibr::Image< T_Type, T_NumComp >::h(), sibr::RayHit::hitSomething(), sibr::Raycaster::intersect(), and sibr::Image< T_Type, T_NumComp >::w().
Referenced by sampleNeighborhood().
interpolate()
void sibr::MeshTexturing::interpolate (const sibr::RayHit & hit, sibr::Vector3f & vertex, sibr::Vector3f & normal) const private
Compute the interpolated position and normal at the intersection point on the initial mesh.
Parameters
hit the intersection information
vertex will contain the interpolated position
normal will contain the interpolated normal
Definition at line 51 of file MeshTexturing.cpp.
References _mesh, sibr::RayHit::barycentricCoord(), sibr::clamp(), sibr::RayHit::primitive(), sibr::RayHit::Primitive::triID, sibr::RayHit::BCCoord::u, and sibr::RayHit::BCCoord::v.
Referenced by reproject().
poissonFill()
sibr::ImageRGB32F::Ptr sibr::MeshTexturing::poissonFill (const sibr::ImageRGB32F & image, const sibr::ImageL8 & mask) static
Performs poisson fill of an image, following a mask.
Parameters
image the image to fill
mask mask where the zeros regions will be filled
Returns
the filled image.
Warning
This is slow for large images (>8k).
Definition at line 191 of file MeshTexturing.cpp.
References sibr::PoissonReconstruction::result(), SIBR_LOG, sibr::PoissonReconstruction::solve(), and sibr::Image< T_Type, T_NumComp >::toOpenCV().
Referenced by getTexture().
reproject()
void sibr::MeshTexturing::reproject (const std::vector< InputCamera::Ptr > & cameras, const std::vector< sibr::ImageRGB::Ptr > & images)
Reproject a set of images into the texture map, using the associated cameras.
Parameters
cameras the cameras poses
images the images to reproject
Definition at line 66 of file MeshTexturing.cpp.
References _accum, _mask, _mesh, _worldRaycaster, sibr::RayHit::dist(), sibr::Image< T_Type, T_NumComp >::h(), sibr::RayHit::hitSomething(), interpolate(), sibr::Raycaster::intersect(), sampleNeighborhood(), SIBR_WRG, sibr::Image< T_Type, T_NumComp >::w(), sibr::LoadingProgress::walk(), weight(), and xyz().
Referenced by main().
sampleNeighborhood()
bool sibr::MeshTexturing::sampleNeighborhood (int px, int py, RayHit & hit) private
Test if the UV-space mesh approximately covers a pixel of the texture map, by sampling a neighborhood in uv-space.
Parameters
px pixel x coordinate
py pixel y coordinate
hit the hit information if there is coverage
Returns
true if there is coverage.
Definition at line 231 of file MeshTexturing.cpp.
References hitTest().
Referenced by reproject().
setMesh()
void sibr::MeshTexturing::setMesh (const sibr::Mesh::Ptr mesh)
Set the current mesh to texture.
Parameters
mesh the mesh to use.
Warning
The mesh MUST have texcoords.
Note
If the mesh has no normals, they will be computed.
Definition at line 14 of file MeshTexturing.cpp.
References _mesh, _uvsRaycaster, _worldRaycaster, sibr::Raycaster::addMesh(), SIBR_ERR, SIBR_LOG, sibr::Mesh::triangles(), and sibr::Mesh::vertices().
Referenced by main().
Member Data Documentation
_accum
sibr::ImageRGB32F sibr::MeshTexturing::_accum private
Color accumulator.
Definition at line 136 of file MeshTexturing.hpp.
Referenced by getTexture(), hitTest(), and reproject().
_mask
sibr::ImageL8 sibr::MeshTexturing::_mask private
Mask indicating which regions of the texture map have been covered.
Definition at line 137 of file MeshTexturing.hpp.
Referenced by getTexture(), and reproject().
_mesh
sibr::Mesh::Ptr sibr::MeshTexturing::_mesh private
The original world-space mesh.
Definition at line 139 of file MeshTexturing.hpp.
Referenced by interpolate(), reproject(), and setMesh().
_uvsRaycaster
sibr::Raycaster sibr::MeshTexturing::_uvsRaycaster private
The uv-space mesh raycaster.
Definition at line 141 of file MeshTexturing.hpp.
Referenced by hitTest(), and setMesh().
_worldRaycaster
sibr::Raycaster sibr::MeshTexturing::_worldRaycaster private
The world-space mesh raycaster.
Definition at line 140 of file MeshTexturing.hpp.
Referenced by reproject(), and setMesh().
The documentation for this class was generated from the following files:
src/core/imgproc/MeshTexturing.hpp
src/core/imgproc/MeshTexturing.cpp