SIBR: sibr::ViewBase Class Reference
sibr::ViewBase Class Reference
sibr_view
Basic view representation.
#include <ViewBase.hpp>
Public Types
typedef std::shared_ptr< ViewBase > Ptr
Public Member Functions
ViewBase (const unsigned int w=720, const unsigned int h=480)
Constructor.
virtual ~ViewBase ()=default
Destructor.
virtual void onUpdate (Input &input)
virtual void onRender (Window &win)
Render content in a window.
virtual void onRenderIBR (IRenderTarget &dst, const Camera &eye)
Render content in a given rendertarget.
virtual void onGUI ()
Display GUI.
virtual void onRender (const Viewport &vpRender)
Render content in the currently bound RT, using a specific viewport.
virtual void onUpdate (Input &input, const Viewport &vp)
Update state based on user input.
virtual void preRender (RenderTargetRGB &prev)
Legacy: Used to mix with previous pass.
virtual void whichRT (uint i)
Legacy: Set the internal RT to use.
virtual uint whichRT (void)
Legacy:
void setResolution (const Vector2i &size)
Set the view resolution.
const Vector2i & getResolution (void) const
void active (bool act)
Toggle view status.
bool active ()
void setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
bool isFocused (void) const
void setName (const std::string &name)
Define the name of the view (used for disambiguation of GUI, etc.).
const std::string & name () const
Protected Attributes
uint _whichRT
Selected RT id.
std::vector< RenderTargetLum::Ptr > _masks
Rendering masks that can beused by some views/renderers.
bool _active = true
Is the view active.
Vector2i _resolution
View resolution.
bool _focus = false
Is the view focused.
std::string _name = ""
View name.
Detailed Description
Basic view representation.
All views should inherit from it. Can be added as a subview in a multi-window system.
See also
MultiViewBase
Definition at line 20 of file ViewBase.hpp.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<ViewBase> sibr::ViewBase::Ptr
Definition at line 24 of file ViewBase.hpp.
Constructor & Destructor Documentation
ViewBase()
sibr::ViewBase::ViewBase (const unsigned int w = 720, const unsigned int h = 480)
Constructor.
Parameters
w view width
h view height
Definition at line 6 of file ViewBase.cpp.
References _resolution, and _whichRT.
~ViewBase()
virtual sibr::ViewBase::~ViewBase () virtual default
Destructor.
Member Function Documentation
active() [1/2]
bool sibr::ViewBase::active () inline
Returns
true if the view is currently active.
Definition at line 91 of file ViewBase.hpp.
active() [2/2]
void sibr::ViewBase::active (bool act) inline
Toggle view status.
Parameters
act if true, the view is active.
Definition at line 89 of file ViewBase.hpp.
getResolution()
const Vector2i & sibr::ViewBase::getResolution (void) const
Returns
the current resolution.
Definition at line 21 of file ViewBase.cpp.
References _resolution.
isFocused()
bool sibr::ViewBase::isFocused (void) const
Returns
true if the view is currently focused (ie the user is interacting with it).
Definition at line 31 of file ViewBase.cpp.
References _focus.
name()
const std::string & sibr::ViewBase::name (void) const
Returns
the name of the view.
Definition at line 40 of file ViewBase.cpp.
References _name.
Referenced by sibr::ImagesGrid::addImagesToHighlight(), sibr::ImagesGrid::addPixelsToHighlight(), sibr::ImagesGrid::name_collision(), sibr::ImageView::onGUI(), sibr::ULRV2View::onGUI(), and setName().
onGUI()
virtual void sibr::ViewBase::onGUI () inline virtual
Display GUI.
Reimplemented in sibr::ULRV3View, sibr::ULRV2View, sibr::TexturedMeshView, sibr::SceneDebugView, sibr::MultiMeshManager, sibr::ImageView, and sibr::ImagesGrid.
Definition at line 53 of file ViewBase.hpp.
onRender() [1/2]
virtual void sibr::ViewBase::onRender (const Viewport & vpRender) inline virtual
Render content in the currently bound RT, using a specific viewport.
Parameters
vpRender destination viewport
Note
Used when the view is in a multi-view system.
Reimplemented in sibr::ImageView, sibr::SceneDebugView, sibr::MultiMeshManager, sibr::ImagesGrid, and sibr::MultiViewInterfaceView.
Definition at line 59 of file ViewBase.hpp.
onRender() [2/2]
virtual void sibr::ViewBase::onRender (Window & win) inline virtual
Render content in a window.
Parameters
win destination window
Reimplemented in sibr::SceneDebugView.
Definition at line 43 of file ViewBase.hpp.
onRenderIBR()
virtual void sibr::ViewBase::onRenderIBR (IRenderTarget & dst, const Camera & eye) inline virtual
Render content in a given rendertarget.
Parameters
dst destination RT
eye current viewpoint
See also
IRenderingMode
Reimplemented in sibr::ULRV3View, sibr::TexturedMeshView, sibr::ULRView, sibr::ULRV2View, and sibr::MultiViewInterfaceView.
Definition at line 50 of file ViewBase.hpp.
Referenced by sibr::MonoRdrMode::render(), and sibr::StereoAnaglyphRdrMode::render().
onUpdate() [1/2]
virtual void sibr::ViewBase::onUpdate (Input & input) inline virtual
Reimplemented in sibr::ULRV3View, sibr::TexturedMeshView, sibr::SceneDebugView, and sibr::ULRV2View.
Definition at line 38 of file ViewBase.hpp.
Referenced by onUpdate().
onUpdate() [2/2]
void sibr::ViewBase::onUpdate (Input & input, const Viewport & vp) virtual
Update state based on user input.
Parameters
input user input
vp input viewport
Note
Used when the view is in a multi-view system.
Reimplemented in sibr::MultiMeshManager, sibr::ImageView, sibr::ImagesGrid, sibr::SceneDebugView, and sibr::MultiViewInterfaceView.
Definition at line 12 of file ViewBase.cpp.
References onUpdate().
preRender()
virtual void sibr::ViewBase::preRender (RenderTargetRGB & prev) inline virtual
Legacy: Used to mix with previous pass.
Parameters
prev the previous step RT
Definition at line 71 of file ViewBase.hpp.
Referenced by sibr::MonoRdrMode::render(), and sibr::StereoAnaglyphRdrMode::render().
setFocus()
void sibr::ViewBase::setFocus (bool focus)
Toggle view focus (ie the user is interacting with it).
Parameters
focus if true, the view is currently focused
Definition at line 26 of file ViewBase.cpp.
References _focus.
setName()
void sibr::ViewBase::setName (const std::string & name)
Define the name of the view (used for disambiguation of GUI, etc.).
Parameters
name the new name
Definition at line 36 of file ViewBase.cpp.
References _name, and name().
setResolution()
void sibr::ViewBase::setResolution (const Vector2i & size)
Set the view resolution.
Parameters
size the new resolution, in pixels.
Definition at line 16 of file ViewBase.cpp.
References _resolution.
whichRT() [1/2]
virtual void sibr::ViewBase::whichRT (uint i) inline virtual
Legacy: Set the internal RT to use.
Parameters
i RT index
Definition at line 75 of file ViewBase.hpp.
whichRT() [2/2]
virtual uint sibr::ViewBase::whichRT (void) inline virtual
Legacy:
Returns
the current selected RT ID.
Definition at line 77 of file ViewBase.hpp.
Member Data Documentation
_active
bool sibr::ViewBase::_active = true protected
Is the view active.
Definition at line 113 of file ViewBase.hpp.
_focus
bool sibr::ViewBase::_focus = false protected
Is the view focused.
Definition at line 115 of file ViewBase.hpp.
Referenced by isFocused(), and setFocus().
_masks
std::vector<RenderTargetLum::Ptr> sibr::ViewBase::_masks protected
Rendering masks that can beused by some views/renderers.
Definition at line 111 of file ViewBase.hpp.
_name
std::string sibr::ViewBase::_name = "" protected
View name.
Definition at line 116 of file ViewBase.hpp.
Referenced by name(), and setName().
_resolution
Vector2i sibr::ViewBase::_resolution protected
View resolution.
Definition at line 114 of file ViewBase.hpp.
Referenced by getResolution(), setResolution(), and ViewBase().
_whichRT
uint sibr::ViewBase::_whichRT protected
Selected RT id.
Definition at line 110 of file ViewBase.hpp.
Referenced by ViewBase().
The documentation for this class was generated from the following files:
src/core/view/ViewBase.hpp
src/core/view/ViewBase.cpp