SIBR: sibr::Rect< T > Class Template Reference
sibr::Rect< T > Class Template Reference
sibr_system
Represents a simple aligned axis rectangle.
#include <Rect.hpp>
Public Types
typedef Eigen::Matrix< T, 2, 1, Eigen::DontAlign > Vec
Public Member Functions
Rect (void)
Default constructor (null everything)
Rect (T left, T top, T right, T bottom)
Constructor.
T left (void) const
T right (void) const
T top (void) const
T bottom (void) const
T width (void) const
T height (void) const
Eigen::Matrix< T, 2, 1, Eigen::DontAlign > cornerLeftTop (void) const
Eigen::Matrix< T, 2, 1, Eigen::DontAlign > cornerLeftBottom (void) const
Eigen::Matrix< T, 2, 1, Eigen::DontAlign > cornerRightBottom (void) const
Eigen::Matrix< T, 2, 1, Eigen::DontAlign > cornerRightTop (void) const
Private Attributes
T _left
x-coordinate of the left border
T _top
y-coordinate of the top border
T _right
x-coordinate of the right border
T _bottom
y-coordinate of the bottom border
Detailed Description
template<typename T>
class sibr::Rect< T >
Represents a simple aligned axis rectangle.
I use left, top, right, bottom and not x1, x2, y1, y2 or x, y, w, h for being free of coordinate systems. (so you can use this class with an origin starting in the top left corner or the bottom right corner; this should be the same).
Note this class is currently what I call a constclass: once built you cannot modify it.
Definition at line 21 of file Rect.hpp.
Member Typedef Documentation
Vec
template<typename T > typedef Eigen::Matrix<T, 2, 1,Eigen::DontAlign> sibr::Rect< T >::Vec
Definition at line 24 of file Rect.hpp.
Constructor & Destructor Documentation
Rect() [1/2]
template<typename T > sibr::Rect< T >::Rect (void)
Default constructor (null everything)
Definition at line 77 of file Rect.hpp.
Rect() [2/2]
template<typename T > sibr::Rect< T >::Rect (T left, T top, T right, T bottom)
Constructor.
Parameters
left x-coordinate of the left border
top y-coordinate of the top border
right x-coordinate of the right border
bottom y-coordinate of the bottom border
Definition at line 81 of file Rect.hpp.
Member Function Documentation
bottom()
template<typename T > T sibr::Rect< T >::bottom (void) const inline
Returns
the position of the bottom side
Definition at line 98 of file Rect.hpp.
cornerLeftBottom()
template<typename T > Eigen::Matrix< T, 2, 1, Eigen::DontAlign > sibr::Rect< T >::cornerLeftBottom (void) const inline
Returns
the bottom left rectangle corner location.
Definition at line 118 of file Rect.hpp.
cornerLeftTop()
template<typename T > Eigen::Matrix< T, 2, 1, Eigen::DontAlign > sibr::Rect< T >::cornerLeftTop (void) const inline
Returns
the top left rectangle corner location.
Definition at line 114 of file Rect.hpp.
cornerRightBottom()
template<typename T > Eigen::Matrix< T, 2, 1, Eigen::DontAlign > sibr::Rect< T >::cornerRightBottom (void) const inline
Returns
the bottom right rectangle corner location.
Definition at line 122 of file Rect.hpp.
cornerRightTop()
template<typename T > Eigen::Matrix< T, 2, 1, Eigen::DontAlign > sibr::Rect< T >::cornerRightTop (void) const inline
Returns
the top right rectangle corner location.
Definition at line 126 of file Rect.hpp.
height()
template<typename T > T sibr::Rect< T >::height (void) const inline
Returns
the height
Definition at line 108 of file Rect.hpp.
References sibr::Key::T.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
left()
template<typename T > T sibr::Rect< T >::left (void) const inline
Returns
the position of the left side
Definition at line 86 of file Rect.hpp.
right()
template<typename T > T sibr::Rect< T >::right (void) const inline
Returns
the position of the right side
Definition at line 90 of file Rect.hpp.
top()
template<typename T > T sibr::Rect< T >::top (void) const inline
Returns
the position of the top side
Definition at line 94 of file Rect.hpp.
width()
template<typename T > T sibr::Rect< T >::width (void) const inline
Returns
the width
Definition at line 103 of file Rect.hpp.
References sibr::Key::T.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
Member Data Documentation
_bottom
template<typename T > T sibr::Rect< T >::_bottom private
y-coordinate of the bottom border
Definition at line 66 of file Rect.hpp.
_left
template<typename T > T sibr::Rect< T >::_left private
x-coordinate of the left border
Definition at line 63 of file Rect.hpp.
_right
template<typename T > T sibr::Rect< T >::_right private
x-coordinate of the right border
Definition at line 65 of file Rect.hpp.
_top
template<typename T > T sibr::Rect< T >::_top private
y-coordinate of the top border
Definition at line 64 of file Rect.hpp.
The documentation for this class was generated from the following file:
src/core/system/Rect.hpp