SIBR: sibr::CameraRaycaster Class Reference
sibr::CameraRaycaster Class Reference
sibr_raycaster
Used for casting each pixel of an image into a raycaster scene.
#include <CameraRaycaster.hpp>
Public Member Functions
CameraRaycaster (void)
Constructor.
bool init (void)
Initialize (will be done when adding a mesh).
void addMesh (const sibr::Mesh &mesh)
Add a mesh to the raycaster.
void castForEachPixel (const sibr::InputCamera &cam, ICameraRaycasterProcessor *processors[], uint nbProcessors, const std::string &optLogMessage="Executing camera raycasting")
For each image pixel, send a ray and compute data using the provided processors.
Raycaster & raycaster (void)
const Raycaster & raycaster (void) const
Static Public Member Functions
static void computePixelDerivatives (const sibr::InputCamera &cam, sibr::Vector3f &dx, sibr::Vector3f &dy, sibr::Vector3f &upLeftOffset)
This function returns the step (in both x- and y-coordinates) between each pixel in the world space.
static sibr::Vector3f computeRayDir (const sibr::InputCamera &cam, const sibr::Vector2f &pixel)
Compute the ray direction from the camera position to a given pixel.
static void computeClippingPlanes (const sibr::Mesh &mesh, std::vector< InputCamera::Ptr > &cams, std::vector< sibr::Vector2f > &nearsFars)
Estimate the clipping planes for a set of cameras so that the mesh is entirely visible in each camera.
Private Attributes
Raycaster _raycaster
Internal raycaster.
Detailed Description
Used for casting each pixel of an image into a raycaster scene.
Definition at line 36 of file CameraRaycaster.hpp.
Constructor & Destructor Documentation
CameraRaycaster()
sibr::CameraRaycaster::CameraRaycaster (void) inline
Constructor.
Definition at line 41 of file CameraRaycaster.hpp.
Member Function Documentation
addMesh()
void sibr::CameraRaycaster::addMesh (const sibr::Mesh & mesh)
Add a mesh to the raycaster.
Parameters
mesh the mesh
Definition at line 113 of file CameraRaycaster.cpp.
References _raycaster, and sibr::Raycaster::addMesh().
castForEachPixel()
void sibr::CameraRaycaster::castForEachPixel (const sibr::InputCamera & cam, ICameraRaycasterProcessor * processors[], uint nbProcessors, const std::string & optLogMessage = "Executing camera raycasting")
For each image pixel, send a ray and compute data using the provided processors.
Parameters
cam the source camera
processors a list of processors to call for each cast ray
nbProcessors the number of processors in the list
optLogMessage log message
Definition at line 118 of file CameraRaycaster.cpp.
References _raycaster, computePixelDerivatives(), sibr::InputCamera::h(), sibr::Raycaster::intersect(), sibr::Camera::position(), SIBR_ERR, and sibr::InputCamera::w().
computeClippingPlanes()
void sibr::CameraRaycaster::computeClippingPlanes (const sibr::Mesh & mesh, std::vector< InputCamera::Ptr > & cams, std::vector< sibr::Vector2f > & nearsFars) static
Estimate the clipping planes for a set of cameras so that the mesh is entirely visible in each camera.
Parameters
mesh the mesh to visualize
cams the list of cameras
nearsFars will contain the near and far plane of each camera
Definition at line 36 of file CameraRaycaster.cpp.
References sibr::Raycaster::addMesh(), computePixelDerivatives(), sibr::Camera::dir(), sibr::RayHit::dist(), sibr::InputCamera::h(), sibr::RayHit::hitSomething(), sibr::Raycaster::init(), sibr::Raycaster::intersect(), sibr::Mesh::invertedFacesMesh2(), sibr::Camera::position(), raycaster(), SIBR_LOG, sibr::InputCamera::w(), sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::BasicIBRScene::createFromData(), and main().
computePixelDerivatives()
void sibr::CameraRaycaster::computePixelDerivatives (const sibr::InputCamera & cam, sibr::Vector3f & dx, sibr::Vector3f & dy, sibr::Vector3f & upLeftOffset) static
This function returns the step (in both x- and y-coordinates) between each pixel in the world space.
Thus, if go through each pixel of an can image but you need their 3d world position, using this function you can get it using: pixel3d = dx*pixel2d.x + dy*pixel2d.y + upLeftOffset where dx is the step between each horizontal pixel, dy is the step between each vertical pixel,
Parameters
cam the source camera
dx will contain the horizontal step
dy will contain the vertical step
upLeftOffset will contain the 3D coordinates of the top-left pixel
Definition at line 9 of file CameraRaycaster.cpp.
References sibr::Camera::aspect(), sibr::cross(), sibr::Camera::dir(), sibr::Camera::fovy(), sibr::InputCamera::h(), sibr::Camera::position(), sibr::Camera::up(), and sibr::InputCamera::w().
Referenced by castForEachPixel(), computeClippingPlanes(), computeRayDir(), sibr::RaycastingCamera::RaycastingCamera(), and sibr::Orbit::updateOrbitParameters().
computeRayDir()
sibr::Vector3f sibr::CameraRaycaster::computeRayDir (const sibr::InputCamera & cam, const sibr::Vector2f & pixel) static
Compute the ray direction from the camera position to a given pixel.
Parameters
cam the source camera
pixel the pixel in [0,w-1]x[0,h-1]
Returns
the ray direction from the camera position to the center of the input pixel.
Definition at line 99 of file CameraRaycaster.cpp.
References computePixelDerivatives(), and sibr::Camera::position().
Referenced by sibr::generateCamFrustum(), sibr::generateCamQuadWithUvs(), sibr::TrackBall::mapTo3Dplane(), sibr::TrackBall::updateBallCenter(), and sibr::TrackBall::updateTranslationPlane().
init()
bool sibr::CameraRaycaster::init (void)
Initialize (will be done when adding a mesh).
Definition at line 108 of file CameraRaycaster.cpp.
References _raycaster, and sibr::Raycaster::init().
raycaster() [1/2]
Raycaster& sibr::CameraRaycaster::raycaster (void) inline
Returns
the internal raycaster
Definition at line 88 of file CameraRaycaster.hpp.
Referenced by computeClippingPlanes().
raycaster() [2/2]
const Raycaster& sibr::CameraRaycaster::raycaster (void) const inline
Returns
the internal raycaster
Definition at line 90 of file CameraRaycaster.hpp.
Member Data Documentation
_raycaster
Raycaster sibr::CameraRaycaster::_raycaster private
Internal raycaster.
Definition at line 94 of file CameraRaycaster.hpp.
Referenced by addMesh(), castForEachPixel(), and init().
The documentation for this class was generated from the following files:
src/core/raycaster/CameraRaycaster.hpp
src/core/raycaster/CameraRaycaster.cpp