SIBR: sibr::GLuniform< T > Class Template Reference
sibr::GLuniform< T > Class Template Reference
sibr_graphics
OpenGL shader uniform wrapper with additional update/storage functions.
#include <Shader.hpp>
Public Member Functions
GLuniform (const T &t)
Constructor.
operator T& ()
T & get ()
T & operator= (const T &t)
Copy operator.
GLuniform & operator= (const GLuniform &other)
Copy operator.
bool operator!= (const T &t)
not-equal-to operator.
GLuniform (const GLuniform &other)
Copy constructor.
GLuniform ()=default
Default constructor.
void init (sibr::GLShader &shader, std::string name)
Link the uniform to a shader.
void send ()
Send the value to the shader if it was initialized.
void set (const T &t)
Set the value and send it to the shader if it was initialized.
void setArray (const T &t, int size)
Set a list of values and send it to the shader if it was initialized.
Protected Attributes
T value = T()
The underlying value.
sibr::GLParameter parameter
The underlying uniform.
Detailed Description
template<typename T>
class sibr::GLuniform< T >
OpenGL shader uniform wrapper with additional update/storage functions.
It will behave as an element of the type it wraps, but can also be set/sent to the GPU. This limits duplication, as you can replace a float+GLParameter by a GLuniform<float> When you need a reference to the value (for instance in imGui), use uniform.get().
See also
GLParameter
Definition at line 291 of file Shader.hpp.
Constructor & Destructor Documentation
GLuniform() [1/3]
template<typename T > sibr::GLuniform< T >::GLuniform (const T & t) inline
Constructor.
Parameters
t initial value to use
Definition at line 297 of file Shader.hpp.
GLuniform() [2/3]
template<typename T > sibr::GLuniform< T >::GLuniform (const GLuniform< T > & other) inline explicit
Copy constructor.
Update the stored value using the one of the other uniform.
Parameters
other uniform to get the new value from
Definition at line 327 of file Shader.hpp.
GLuniform() [3/3]
template<typename T > sibr::GLuniform< T >::GLuniform () default
Default constructor.
Member Function Documentation
get()
template<typename T > T& sibr::GLuniform< T >::get () inline
Returns
a reference to the value.
Definition at line 303 of file Shader.hpp.
Referenced by sibr::ImageView::onGUI(), sibr::ImageView::onRender(), sibr::ImageView::onUpdate(), sibr::ImageView::setRenderTarget(), and sibr::ImageView::setTexture().
init()
template<typename T > void sibr::GLuniform< T >::init (sibr::GLShader & shader, std::string name) inline
Link the uniform to a shader.
Parameters
shader the shader to link to
name the name of the uniform in the shader
Definition at line 336 of file Shader.hpp.
Referenced by sibr::BinaryMeshRenderer::BinaryMeshRenderer(), sibr::CopyRenderer::CopyRenderer(), sibr::ImageView::ImageView(), sibr::DrawUtilities::initBaseShader(), sibr::DrawUtilities::initGridShader(), sibr::ShaderAlphaMVP::initShader(), sibr::ColorMeshShader::initShader(), sibr::PointShader::initShader(), sibr::MeshShadingShader::initShader(), sibr::NormalRenderingShader::initShader(), sibr::PositionRenderer::PositionRenderer(), sibr::LabelsManager::setupLabelsManagerShader(), and sibr::ULRV2Renderer::setupULRshader().
operator T&()
template<typename T > sibr::GLuniform< T >::operator T& () inline
Returns
a reference to the value.
Definition at line 300 of file Shader.hpp.
operator!=()
template<typename T > bool sibr::GLuniform< T >::operator!= (const T & t) inline
not-equal-to operator.
Compares the stored values with the argument and returns the not-equal-to operator.
Parameters
t value to compare to.
Returns
the boolean result of the operation.
Definition at line 322 of file Shader.hpp.
operator=() [1/2]
template<typename T > GLuniform& sibr::GLuniform< T >::operator= (const GLuniform< T > & other) inline
Copy operator.
Update the stored value using the one of the other uniform.
Parameters
other uniform to get the new value from
Returns
a reference to itself
Definition at line 315 of file Shader.hpp.
operator=() [2/2]
template<typename T > T& sibr::GLuniform< T >::operator= (const T & t) inline
Copy operator.
Update the stored value.
Parameters
t the new value
Returns
a reference to the value.
Definition at line 309 of file Shader.hpp.
send()
template<typename T > void sibr::GLuniform< T >::send () inline
Send the value to the shader if it was initialized.
Note
the shader has to be active
Definition at line 343 of file Shader.hpp.
Referenced by sibr::ImageView::onRender(), sibr::BinaryMeshRenderer::process(), sibr::ULRV2Renderer::process(), sibr::CopyRenderer::process(), and sibr::GLuniform< sibr::Vector4f >::set().
set()
template<typename T > void sibr::GLuniform< T >::set (const T & t) inline
Set the value and send it to the shader if it was initialized.
Parameters
t the new value
Note
the shader has to be active
Definition at line 353 of file Shader.hpp.
Referenced by sibr::DrawUtilities::baseRendering(), sibr::DrawUtilities::image_grid(), sibr::BinaryMeshRenderer::process(), sibr::ULRV2Renderer::process(), sibr::PositionRenderer::render(), sibr::LabelsManager::renderLabels(), sibr::ShaderAlphaMVP::setUniforms(), sibr::ColorMeshShader::setUniforms(), sibr::PointShader::setUniforms(), sibr::MeshShadingShader::setUniforms(), and sibr::NormalRenderingShader::setUniforms().
setArray()
template<typename T > void sibr::GLuniform< T >::setArray (const T & t, int size) inline
Set a list of values and send it to the shader if it was initialized.
Parameters
t the new values
size the number of values
Note
the shader has to be active
Definition at line 363 of file Shader.hpp.
Member Data Documentation
parameter
template<typename T > sibr::GLParameter sibr::GLuniform< T >::parameter protected
The underlying uniform.
Definition at line 372 of file Shader.hpp.
Referenced by sibr::GLuniform< sibr::Vector4f >::init(), sibr::GLuniform< sibr::Vector4f >::send(), and sibr::GLuniform< sibr::Vector4f >::setArray().
value
template<typename T > T sibr::GLuniform< T >::value = T() protected
The underlying value.
Definition at line 371 of file Shader.hpp.
Referenced by sibr::GLuniform< sibr::Vector4f >::get(), sibr::GLuniform< Vector3f >::operator Vector3f &(), sibr::GLuniform< sibr::Vector4f >::operator!=(), sibr::GLuniform< sibr::Vector4f >::operator=(), sibr::GLuniform< sibr::Vector4f >::send(), sibr::GLuniform< sibr::Vector4f >::set(), and sibr::GLuniform< sibr::Vector4f >::setArray().
The documentation for this class was generated from the following file:
src/core/graphics/Shader.hpp