SIBR: sibr::ShaderAlphaMVP Class Reference
sibr::ShaderAlphaMVP Class Reference
sibr_view
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
#include <MultiMeshManager.hpp>
Public Member Functions
virtual void initShader (const std::string &name, const std::string &vert, const std::string &frag, const std::string &geom="")
Initialize the shader.
virtual void setUniforms (const Camera &eye, const MeshData &data)
virtual void render (const Camera &eye, const MeshData &data)
Render using the passed information.
Protected Attributes
GLShader shader
Base shader object.
GLuniform< Matrix4f > mvp
MVP matrix.
GLuniform< float > alpha = 1.0
Opacity.
Private Member Functions
SIBR_CLASS_PTR (ShaderAlphaMVP)
Detailed Description
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
Contains an MVP matrix and an opacity value.
Definition at line 22 of file MultiMeshManager.hpp.
Member Function Documentation
initShader()
void sibr::ShaderAlphaMVP::initShader (const std::string & name, const std::string & vert, const std::string & frag, const std::string & geom = "") virtual
Initialize the shader.
Parameters
name the shader name
vert the vertex shader content
frag the fragment shader ocntent
geom the geometry shader content
Reimplemented in sibr::NormalRenderingShader, sibr::MeshShadingShader, sibr::PointShader, and sibr::ColorMeshShader.
Definition at line 214 of file MultiMeshManager.cpp.
References alpha, sibr::GLuniform< T >::init(), sibr::GLShader::init(), mvp, and shader.
Referenced by sibr::ColorMeshShader::initShader().
render()
void sibr::ShaderAlphaMVP::render (const Camera & eye, const MeshData & data) virtual
Render using the passed information.
Parameters
eye the current viewpoint
data the mesh display options
Reimplemented in sibr::PointShader.
Definition at line 227 of file MultiMeshManager.cpp.
References sibr::GLShader::begin(), sibr::GLShader::end(), sibr::MeshData::renderGeometry(), setUniforms(), and shader.
Referenced by sibr::PointShader::render(), and sibr::MultiMeshManager::renderMeshes().
setUniforms()
void sibr::ShaderAlphaMVP::setUniforms (const Camera & eye, const MeshData & data) virtual
Reimplemented in sibr::NormalRenderingShader, sibr::MeshShadingShader, sibr::PointShader, and sibr::ColorMeshShader.
Definition at line 221 of file MultiMeshManager.cpp.
References alpha, sibr::MeshData::alpha, mvp, sibr::GLuniform< T >::set(), sibr::MeshData::transformation, and sibr::Camera::viewproj().
Referenced by render(), and sibr::ColorMeshShader::setUniforms().
SIBR_CLASS_PTR()
sibr::ShaderAlphaMVP::SIBR_CLASS_PTR (ShaderAlphaMVP) private
Member Data Documentation
alpha
GLuniform<float> sibr::ShaderAlphaMVP::alpha = 1.0 protected
Opacity.
Definition at line 48 of file MultiMeshManager.hpp.
Referenced by initShader(), and setUniforms().
mvp
GLuniform<Matrix4f> sibr::ShaderAlphaMVP::mvp protected
MVP matrix.
Definition at line 47 of file MultiMeshManager.hpp.
Referenced by initShader(), and setUniforms().
shader
GLShader sibr::ShaderAlphaMVP::shader protected
Base shader object.
Definition at line 46 of file MultiMeshManager.hpp.
Referenced by initShader(), sibr::ColorMeshShader::initShader(), sibr::PointShader::initShader(), sibr::MeshShadingShader::initShader(), sibr::NormalRenderingShader::initShader(), and render().
The documentation for this class was generated from the following files:
src/core/view/MultiMeshManager.hpp
src/core/view/MultiMeshManager.cpp