SIBR: sibr::UVUnwrapper Class Reference
sibr::UVUnwrapper Class Reference
sibr_assets
Unwraps a mesh onto a plane, generating texture coordinates for each vertex.
#include <UVUnwrapper.hpp>
Public Member Functions
UVUnwrapper (const sibr::Mesh &mesh, unsigned int res)
Constructor.
sibr::Mesh::Ptr unwrap ()
Unwrap the mesh, return a copy with UV coordinates.
const std::vector< uint > & mapping () const
For each vertex of the unwrapped mesh, the mapping give the index of the corresponding vertex in the input mesh.
std::vector< ImageRGB::Ptr > atlasVisualization () const
Generate debug visualization by rasterizing the meshes in texture space.
~UVUnwrapper ()
Destructor.
Private Attributes
const sibr::Mesh & _mesh
Unwrapped mesh.
unsigned int _size
Width of the atlas, detemrine the accuracy of the estimated UVs.
xatlas::Atlas * _atlas
Atlas object.
std::vector< uint > _mapping
Mapping from the new vertices to the old (some might be duplicated with different UV values).
Detailed Description
Unwraps a mesh onto a plane, generating texture coordinates for each vertex.
Internaly relies on xatlas for unwrapping.
Definition at line 16 of file UVUnwrapper.hpp.
Constructor & Destructor Documentation
UVUnwrapper()
UVUnwrapper::UVUnwrapper (const sibr::Mesh & mesh, unsigned int res)
Constructor.
Parameters
mesh the mesh to unwrap, if UVs are already present they will be used as a guide
res the target texture width, will determine UV accuracy
Definition at line 89 of file UVUnwrapper.cpp.
References _atlas, _size, sibr::Mesh::hasNormals(), sibr::Mesh::hasTexCoords(), sibr::Mesh::normalArray(), printCallback(), progressCallback(), SIBR_ERR, SIBR_LOG, sibr::Mesh::texCoordArray(), sibr::Mesh::triangleArray(), sibr::Mesh::triangles(), sibr::Mesh::vertexArray(), and sibr::Mesh::vertices().
~UVUnwrapper()
UVUnwrapper::~UVUnwrapper ()
Destructor.
Definition at line 261 of file UVUnwrapper.cpp.
References _atlas.
Member Function Documentation
atlasVisualization()
std::vector< ImageRGB::Ptr > UVUnwrapper::atlasVisualization () const
Generate debug visualization by rasterizing the meshes in texture space.
Returns
a set of images, one per atlas
Definition at line 206 of file UVUnwrapper.cpp.
References _atlas, rasterizeLine(), rasterizeTriangle(), SIBR_LOG, and SIBR_WRG.
Referenced by main().
mapping()
const std::vector< uint > & UVUnwrapper::mapping () const
For each vertex of the unwrapped mesh, the mapping give the index of the corresponding vertex in the input mesh.
Returns
a reference to the mapping vector
Definition at line 200 of file UVUnwrapper.cpp.
References _mapping.
unwrap()
sibr::Mesh::Ptr UVUnwrapper::unwrap ()
Unwrap the mesh, return a copy with UV coordinates.
Note that some vertices might be duplicated if they are assigned different UVs in two faces.
Returns
the unwrapped mesh
Definition at line 125 of file UVUnwrapper.cpp.
References _atlas, _mapping, _mesh, _size, sibr::Mesh::colors(), sibr::Timer::deltaTimeFromLastTic(), sibr::Mesh::hasColors(), sibr::Mesh::hasNormals(), sibr::Mesh::normals(), SIBR_LOG, sibr::Timer::tic(), and sibr::Mesh::vertices().
Referenced by main().
Member Data Documentation
_atlas
xatlas::Atlas* sibr::UVUnwrapper::_atlas private
Atlas object.
Definition at line 47 of file UVUnwrapper.hpp.
Referenced by atlasVisualization(), unwrap(), UVUnwrapper(), and ~UVUnwrapper().
_mapping
std::vector<uint> sibr::UVUnwrapper::_mapping private
Mapping from the new vertices to the old (some might be duplicated with different UV values).
Definition at line 48 of file UVUnwrapper.hpp.
Referenced by mapping(), and unwrap().
_mesh
const sibr::Mesh& sibr::UVUnwrapper::_mesh private
Unwrapped mesh.
Definition at line 45 of file UVUnwrapper.hpp.
Referenced by unwrap().
_size
unsigned int sibr::UVUnwrapper::_size private
Width of the atlas, detemrine the accuracy of the estimated UVs.
Definition at line 46 of file UVUnwrapper.hpp.
Referenced by unwrap(), and UVUnwrapper().
The documentation for this class was generated from the following files:
src/core/assets/UVUnwrapper.hpp
src/core/assets/UVUnwrapper.cpp