SIBR: sibr::VideoPlayer Class Reference
sibr::VideoPlayer Class Reference
sibr_video
Load and display a video in a view, with playback options.
#include <Video.hpp>
Public Types
enum Mode { PAUSE, PLAY, SHOULD_CLOSE }
Replay mode.
using Transformation = std::function< cv::Mat(cv::Mat)>
Image processing function.
Public Member Functions
VideoPlayer (const std::string &filepath="", const std::function< cv::Mat(cv::Mat)> &f=[](cv::Mat m) { return m;})
Constructor.
bool load (const std::string &path) override
Load a video from disk.
void setTransformation (const Transformation &f)
Set a transformation function to apply to each frame.
void setMode (Mode _mode)
Set the playback mode.
const std::shared_ptr< sibr::Texture2DRGB > & getDisplayTex () const
void update ()
Load the next frame, call once per rendering frame.
void onGui (float ratio_display)
Display playback GUI.
bool updateCPU ()
Load the next frame to the CPU.
void updateGPU ()
Load the next frame to the GPU.
const cv::Mat & getCurrentFrame () const
Public Member Functions inherited from sibr::Video
Video (const std::string &path="")
Constructor.
const sibr::Vector2i & getResolution ()
cv::Size getResolutionCV ()
int getCurrentFrameNumber ()
void setCurrentFrame (int i)
Seek a specific frame.
int getNumFrames ()
double getFrameRate ()
const Path & getFilepath () const
bool isLoaded ()
int getCodec ()
virtual void release ()
Stop reading from the file.
cv::Mat getVolume (float time_skiped_begin=0, float time_skiped_end=0)
Read a section of the video and store it in a cv::Mat, where each row contains a frame, stored as RGBRGBRGB...
cv::Mat getVolume (int starting_frame, int ending_frame)
Read a section of the video and store otin a cv::Mat, where each row contains a frame, stored as RGBRGBRGB...
cv::Mat next ()
cv::VideoCapture & getCVvideo ()
bool exists () const
Public Member Functions inherited from sibr::ZoomInterraction
void updateZoom (const sibr::Vector2f &canvasSize)
Update zoom information.
Protected Member Functions
std::shared_ptr< sibr::Texture2DRGB > & getLoadingTex ()
void loadNext ()
Load the next frame, on the CPU then the GPU.
Protected Member Functions inherited from sibr::Video
virtual void checkLoad ()
Check if the video is loaded.
Protected Attributes
Mode mode = PAUSE
Play mode.
bool first = true
Are we at the first frame.
bool repeat_when_end = true
Loop when reaching the end.
int displayTex = 1
Index of the display texture.
int loadingTex = 1
Index of the loading texture.
std::shared_ptr< sibr::Texture2DRGB > ping
std::shared_ptr< sibr::Texture2DRGB > pong
Double buffer textures.
cv::Mat tmpFrame
Scratch frame.
Transformation transformation
Transformation to apply to each frame.
int current_frame_slider
Slider position.
Protected Attributes inherited from sibr::Video
cv::VideoCapture cap
Internal capture object.
Path filepath
The path to the video.
sibr::Vector2i resolution
Video resolution.
int nFrames = 0
Number of frames in the video.
double frameRate = 0.0
Video frame rate.
int codec = 0
Codec used to read the video.
bool loaded = false
Video loading status.
Private Member Functions
SIBR_CLASS_PTR (VideoPlayer)
Additional Inherited Members
Public Attributes inherited from sibr::ZoomInterraction
CallBackData callBackData
Interaction data.
ZoomData zoomData
Zoom data.
Detailed Description
Load and display a video in a view, with playback options.
Definition at line 113 of file Video.hpp.
Member Typedef Documentation
Transformation
using sibr::VideoPlayer::Transformation = std::function<cv::Mat(cv::Mat)>
Image processing function.
Definition at line 123 of file Video.hpp.
Member Enumeration Documentation
Mode
enum sibr::VideoPlayer::Mode
Replay mode.
Enumerator
PAUSE
PLAY
SHOULD_CLOSE
Definition at line 121 of file Video.hpp.
Constructor & Destructor Documentation
VideoPlayer()
sibr::VideoPlayer::VideoPlayer (const std::string & filepath = "", const std::function< cv::Mat(cv::Mat)> & f = [](cv::Mat m) { return m; })
Constructor.
Parameters
filepath the path to the video file
f a function to apply to each frame
Note
No loading will be performed at construction. Call load.
Definition at line 131 of file Video.cpp.
Member Function Documentation
getCurrentFrame()
const cv::Mat& sibr::VideoPlayer::getCurrentFrame () const inline
Returns
a reference to the current frame on the CPU.
Definition at line 172 of file Video.hpp.
getDisplayTex()
const std::shared_ptr< sibr::Texture2DRGB > & sibr::VideoPlayer::getDisplayTex () const
Returns
the current display texture on the GPU.
Definition at line 145 of file Video.cpp.
References displayTex, ping, and pong.
Referenced by onGui().
getLoadingTex()
std::shared_ptr<sibr::Texture2DRGB>& sibr::VideoPlayer::getLoadingTex () inline protected
Returns
the current loading texture on the GPU.
Definition at line 177 of file Video.hpp.
Referenced by updateGPU().
load()
bool sibr::VideoPlayer::load (const std::string & path) override virtual
Load a video from disk.
Parameters
path the path to the video on disk
Returns
a success flag
Reimplemented from sibr::Video.
Definition at line 136 of file Video.cpp.
loadNext()
void sibr::VideoPlayer::loadNext () protected
Load the next frame, on the CPU then the GPU.
Definition at line 246 of file Video.cpp.
References updateCPU(), and updateGPU().
Referenced by update().
onGui()
void sibr::VideoPlayer::onGui (float ratio_display)
Display playback GUI.
Parameters
ratio_display a scaling factor that determine the size of the video on screen based on the video intrinsic size.
Definition at line 171 of file Video.cpp.
References sibr::ZoomData::bottomRight(), sibr::ZoomInterraction::callBackData, sibr::Video::checkLoad(), current_frame_slider, displayTex, first, sibr::Video::getCurrentFrameNumber(), getDisplayTex(), sibr::Video::getFrameRate(), sibr::Video::getNumFrames(), sibr::ImageWithCallback(), loadingTex, mode, PAUSE, PLAY, ImGui::PushScaledItemWidth(), repeat_when_end, sibr::Video::setCurrentFrame(), sibr::ZoomData::topLeft(), sibr::ZoomInterraction::updateZoom(), and sibr::ZoomInterraction::zoomData.
setMode()
void sibr::VideoPlayer::setMode (Mode _mode) inline
Set the playback mode.
Parameters
_mode the new mode
Definition at line 146 of file Video.hpp.
setTransformation()
void sibr::VideoPlayer::setTransformation (const Transformation & f) inline
Set a transformation function to apply to each frame.
Parameters
f the new transformation
Definition at line 141 of file Video.hpp.
SIBR_CLASS_PTR()
sibr::VideoPlayer::SIBR_CLASS_PTR (VideoPlayer) private
update()
void sibr::VideoPlayer::update ()
Load the next frame, call once per rendering frame.
Note
Internally calls updateCPU and updateGPU.
Definition at line 150 of file Video.cpp.
References sibr::Video::checkLoad(), displayTex, first, loadingTex, loadNext(), mode, and PLAY.
updateCPU()
bool sibr::VideoPlayer::updateCPU ()
Load the next frame to the CPU.
Returns
a success flag
Definition at line 212 of file Video.cpp.
References sibr::Video::checkLoad(), mode, sibr::Video::next(), PAUSE, repeat_when_end, sibr::Video::setCurrentFrame(), SIBR_WRG, tmpFrame, and transformation.
Referenced by loadNext().
updateGPU()
void sibr::VideoPlayer::updateGPU ()
Load the next frame to the GPU.
Note
You should call updateCPU first.
Definition at line 237 of file Video.cpp.
References getLoadingTex(), and tmpFrame.
Referenced by loadNext().
Member Data Documentation
current_frame_slider
int sibr::VideoPlayer::current_frame_slider protected
Slider position.
Definition at line 190 of file Video.hpp.
Referenced by onGui().
displayTex
int sibr::VideoPlayer::displayTex = 1 protected
Index of the display texture.
Definition at line 185 of file Video.hpp.
Referenced by getDisplayTex(), onGui(), and update().
first
bool sibr::VideoPlayer::first = true protected
Are we at the first frame.
Definition at line 183 of file Video.hpp.
Referenced by onGui(), and update().
loadingTex
int sibr::VideoPlayer::loadingTex = 1 protected
Index of the loading texture.
Definition at line 186 of file Video.hpp.
Referenced by onGui(), and update().
mode
Mode sibr::VideoPlayer::mode = PAUSE protected
Play mode.
Definition at line 182 of file Video.hpp.
Referenced by onGui(), update(), and updateCPU().
ping
std::shared_ptr<sibr::Texture2DRGB> sibr::VideoPlayer::ping protected
Definition at line 187 of file Video.hpp.
Referenced by getDisplayTex().
pong
std::shared_ptr<sibr::Texture2DRGB> sibr::VideoPlayer::pong protected
Double buffer textures.
Definition at line 187 of file Video.hpp.
Referenced by getDisplayTex().
repeat_when_end
bool sibr::VideoPlayer::repeat_when_end = true protected
Loop when reaching the end.
Definition at line 184 of file Video.hpp.
Referenced by onGui(), and updateCPU().
tmpFrame
cv::Mat sibr::VideoPlayer::tmpFrame protected
Scratch frame.
Definition at line 188 of file Video.hpp.
Referenced by updateCPU(), and updateGPU().
transformation
Transformation sibr::VideoPlayer::transformation protected
Transformation to apply to each frame.
Definition at line 189 of file Video.hpp.
Referenced by updateCPU().
The documentation for this class was generated from the following files:
src/core/video/Video.hpp
src/core/video/Video.cpp