SIBR: sibr::CameraRecorder Class Reference
sibr::CameraRecorder Class Reference
sibr_assets
This class handles the recording and replay of a stream of cameras.
#include <CameraRecorder.hpp>
Public Member Functions
CameraRecorder (void)
Default constructor.
~CameraRecorder (void)
Default destructor.
void use (Camera &cam)
This method supports two modes: if the recorder is currently recording, the camera argument will be saved into the recording; else if the recorder is playing, the camera argument will be set to the current replaid camera.
void playback (void)
Start playing the recorded camera stream from the beginning, at a rate of one step for each "use" call.
void record (void)
Start recording a new camera stream, at a rate of one camera saved for each "use" call.
void saving (std::string savePath)
Start asking the renderer to save the frames, at a rate of one image saved for each "use" call.
void savingVideo (bool saveVideo)
Toggle the save flag for video frames when replaying.
void stopSaving (void)
Stop saving.
void stop (void)
Stop playing/recording.
void reset (void)
Clear the current recording.
void playNoInterpolation (bool val)
Set value of play no interpolation.
bool load (const std::string &filename=SIBR_CAMERARECORDER_DEFAULTFILE)
Load a recorded camera stream from a given file.
void save (const std::string &filename=SIBR_CAMERARECORDER_DEFAULTFILE)
Save the current recording stream to a given file.
bool safeLoad (const std::string &filename, int w=1920, int h=1080)
Load recorded path based on file extension.
void loadBundle (const std::string &filePath, int w=1920, int h=1080)
Load a recording stream saved as a bundle file (useful for path from FRIBR).
void loadLookat (const std::string &filePath, int w=1920, int h=1080)
Load a camera path generated by the camera editor / bledner plugin.
void loadColmap (const std::string &filePath, int w=1920, int h=1080)
Load a camera path generated by colmap requires filename images.txt for now TODO GD; fix this.
void saveAsBundle (const std::string &filePath, const int height, const int step=1)
Save the current recording stream as a bundle file.
void saveAsFRIBRBundle (const std::string &dirPath, const int width, const int height)
Save the current recording stream as a bundle file and a series of empty images for FRIBR compatibility.
void saveAsLookAt (const std::string &filePath) const
Save the current recording stream as a lookat file.
bool isPlaying () const
bool isRecording () const
bool isSaving () const
std::vector< Camera > & cams ()
void cams (std::vector< Camera > &cams)
Updates the cameras from a vector, usefull to play already loaded path.
bool loadPath (const std::string &pathFileName, int w, int h)
Load a path, based on file extension name.
void recordOfflinePath (const std::string &outPathDir, ViewBase::Ptr view, const std::string &prefix)
Play path for offline rendering using abstract View interface.
float & speed ()
Private Attributes
uint _pos
Current camera ID for replay.
std::vector< Camera > _cameras
List of recorded cameras.
bool _recording
Are we currently recording.
bool _playing
Are we currently playing.
bool _saving
Are we saving the path as images.
std::string _savingPath
Destination base path for saved images.
bool _savingVideo
Are we saving the path as video.
std::string _savingVideoPath
Destination base path for saved video.
float _speed
Playback speed.
float _interp
Current interpoaltion factor.
bool _playNoInterp
Just play the cameras, make sure focal is preserved.
int _ow
int _oh
offline output path resolution
Detailed Description
This class handles the recording and replay of a stream of cameras.
Definition at line 15 of file CameraRecorder.hpp.
Constructor & Destructor Documentation
CameraRecorder()
sibr::CameraRecorder::CameraRecorder (void) inline
Default constructor.
Definition at line 22 of file CameraRecorder.hpp.
~CameraRecorder()
sibr::CameraRecorder::~CameraRecorder (void) inline
Default destructor.
Definition at line 29 of file CameraRecorder.hpp.
Member Function Documentation
cams() [1/2]
std::vector<Camera>& sibr::CameraRecorder::cams () inline
Returns
A reference to the current stream of recorded cameras.
Definition at line 171 of file CameraRecorder.hpp.
cams() [2/2]
void sibr::CameraRecorder::cams (std::vector< Camera > & cams) inline
Updates the cameras from a vector, usefull to play already loaded path.
Definition at line 176 of file CameraRecorder.hpp.
References cams().
Referenced by cams().
isPlaying()
bool sibr::CameraRecorder::isPlaying () const inline
Returns
a boolean denoting if the recorder is currently playing.
Definition at line 155 of file CameraRecorder.hpp.
Referenced by sibr::InteractiveCameraHandler::update().
isRecording()
bool sibr::CameraRecorder::isRecording () const inline
Returns
a boolean denoting if the recorder is currently recording.
Definition at line 160 of file CameraRecorder.hpp.
isSaving()
bool sibr::CameraRecorder::isSaving () const inline
Returns
a boolean denoting if the recorder is currently asking frames to be saved.
Definition at line 165 of file CameraRecorder.hpp.
load()
bool sibr::CameraRecorder::load (const std::string & filename = SIBR_CAMERARECORDER_DEFAULTFILE)
Load a recorded camera stream from a given file.
Parameters
filename Optional path to the file to load from. By default will try to load SIBR_CAMERARECORDER_DEFAULTFILE from the current directory.
Returns
a boolean denoting the loading success/failure.
Definition at line 114 of file CameraRecorder.cpp.
References _cameras, sibr::ByteStream::load(), reset(), and SIBR_LOG.
Referenced by loadPath(), sibr::InteractiveCameraHandler::onGUI(), safeLoad(), and sibr::InteractiveCameraHandler::update().
loadBundle()
void sibr::CameraRecorder::loadBundle (const std::string & filePath, int w = 1920, int h = 1080)
Load a recording stream saved as a bundle file (useful for path from FRIBR).
Parameters
filePath Path to the bundle file to write to.
w the image width to use for Fov computation
h the image height
Definition at line 165 of file CameraRecorder.cpp.
References _cameras, ibr_convert_old_to_new::line, SIBR_ASSERT, and SIBR_LOG.
Referenced by loadPath(), sibr::InteractiveCameraHandler::onGUI(), safeLoad(), and sibr::InteractiveCameraHandler::update().
loadColmap()
void sibr::CameraRecorder::loadColmap (const std::string & filePath, int w = 1920, int h = 1080)
Load a camera path generated by colmap requires filename images.txt for now TODO GD; fix this.
Parameters
filePath Path to the images.txt file; assumes that a cameras.txt is "next to" it;
w Width of the cameras to create.
h Height of the cameras to create.
Definition at line 203 of file CameraRecorder.cpp.
References _cameras, sibr::InputCamera::loadColmap(), and SIBR_LOG.
Referenced by loadPath(), and sibr::InteractiveCameraHandler::onGUI().
loadLookat()
void sibr::CameraRecorder::loadLookat (const std::string & filePath, int w = 1920, int h = 1080)
Load a camera path generated by the camera editor / bledner plugin.
Parameters
filePath Path to the .lookat file.
w Width of the cameras to create.
h Height of the cameras to create.
Definition at line 217 of file CameraRecorder.cpp.
References _cameras, sibr::InputCamera::loadLookat(), and SIBR_LOG.
Referenced by loadPath(), and sibr::InteractiveCameraHandler::onGUI().
loadPath()
bool sibr::CameraRecorder::loadPath (const std::string & pathFileName, int w, int h)
Load a path, based on file extension name.
Cameras loaded into _cameras
Definition at line 338 of file CameraRecorder.cpp.
References _oh, _ow, _savingPath, sibr::fileExists(), load(), loadBundle(), loadColmap(), loadLookat(), sibr::parentDirectory(), and SIBR_WRG.
playback()
void sibr::CameraRecorder::playback (void)
Start playing the recorded camera stream from the beginning, at a rate of one step for each "use" call.
Definition at line 69 of file CameraRecorder.cpp.
References _playing, SIBR_LOG, and stop().
Referenced by sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::update().
playNoInterpolation()
void sibr::CameraRecorder::playNoInterpolation (bool val) inline
Set value of play no interpolation.
Definition at line 79 of file CameraRecorder.hpp.
Referenced by sibr::InteractiveCameraHandler::onGUI().
record()
void sibr::CameraRecorder::record (void)
Start recording a new camera stream, at a rate of one camera saved for each "use" call.
Definition at line 76 of file CameraRecorder.cpp.
References _recording, SIBR_LOG, and stop().
Referenced by sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::update().
recordOfflinePath()
void sibr::CameraRecorder::recordOfflinePath (const std::string & outPathDir, ViewBase::Ptr view, const std::string & prefix)
Play path for offline rendering using abstract View interface.
Definition at line 356 of file CameraRecorder.cpp.
References _cameras, _oh, _ow, _savingPath, sibr::directoryExists(), sibr::ImagePtr< T_Type, T_NumComp >::reset(), and SIBR_ERR.
reset()
void sibr::CameraRecorder::reset (void)
Clear the current recording.
Definition at line 108 of file CameraRecorder.cpp.
References _cameras, and stop().
Referenced by load(), sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::update().
safeLoad()
bool sibr::CameraRecorder::safeLoad (const std::string & filename, int w = 1920, int h = 1080)
Load recorded path based on file extension.
Parameters
filename the file to load
w resoltuion width
h resolution height
Returns
a success boolean
Note
w and h are needed when loading a Bundle.
Definition at line 151 of file CameraRecorder.cpp.
References load(), loadBundle(), and SIBR_WRG.
save()
void sibr::CameraRecorder::save (const std::string & filename = SIBR_CAMERARECORDER_DEFAULTFILE)
Save the current recording stream to a given file.
Parameters
filename Optional path to the file to write to. By default will try to write to SIBR_CAMERARECORDER_DEFAULTFILE in the current directory.
Definition at line 139 of file CameraRecorder.cpp.
References _cameras, sibr::ByteStream::saveToFile(), and SIBR_LOG.
Referenced by sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::update().
saveAsBundle()
void sibr::CameraRecorder::saveAsBundle (const std::string & filePath, const int height, const int step = 1)
Save the current recording stream as a bundle file.
Parameters
filePath Path to the bundle file to write to.
height the height in pixels of the camera. Used to compute focal length in mm as expected by bundle.
step set to a value greater than 1 to save every "step" camera in the recording stream.
Definition at line 227 of file CameraRecorder.cpp.
References _cameras, sibr::Camera::fovy(), sibr::Camera::position(), sibr::Camera::rotation(), and SIBR_LOG.
Referenced by sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::update().
saveAsFRIBRBundle()
void sibr::CameraRecorder::saveAsFRIBRBundle (const std::string & dirPath, const int width, const int height)
Save the current recording stream as a bundle file and a series of empty images for FRIBR compatibility.
Parameters
dirPath Path to the directory to export to.
width the width in pixels of the camera.
height the height in pixels of the camera.
Definition at line 272 of file CameraRecorder.cpp.
References _cameras, sibr::Camera::fovy(), sibr::makeDirectory(), sibr::Camera::position(), sibr::Camera::rotation(), and SIBR_LOG.
Referenced by sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::update().
saveAsLookAt()
void sibr::CameraRecorder::saveAsLookAt (const std::string & filePath) const
Save the current recording stream as a lookat file.
Parameters
filePath Path to the lookat file to write to.
Definition at line 332 of file CameraRecorder.cpp.
References _cameras, and sibr::InputCamera::saveAsLookat().
Referenced by sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::update().
saving()
void sibr::CameraRecorder::saving (std::string savePath)
Start asking the renderer to save the frames, at a rate of one image saved for each "use" call.
Definition at line 83 of file CameraRecorder.cpp.
References SIBR_LOG.
Referenced by sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::update().
savingVideo()
void sibr::CameraRecorder::savingVideo (bool saveVideo)
Toggle the save flag for video frames when replaying.
Parameters
saveVideo the new flag status
Definition at line 90 of file CameraRecorder.cpp.
References _savingVideo.
Referenced by sibr::InteractiveCameraHandler::onGUI().
speed()
float& sibr::CameraRecorder::speed () inline
Returns
the interpolation speed
Definition at line 192 of file CameraRecorder.hpp.
Referenced by sibr::InteractiveCameraHandler::onGUI().
stop()
void sibr::CameraRecorder::stop (void)
Stop playing/recording.
Definition at line 101 of file CameraRecorder.cpp.
References _interp, _playing, _pos, and _recording.
Referenced by sibr::InteractiveCameraHandler::onGUI(), playback(), record(), reset(), sibr::InteractiveCameraHandler::update(), and use().
stopSaving()
void sibr::CameraRecorder::stopSaving (void)
Stop saving.
Definition at line 95 of file CameraRecorder.cpp.
Referenced by sibr::InteractiveCameraHandler::onGUI(), and sibr::InteractiveCameraHandler::update().
use()
void sibr::CameraRecorder::use (Camera & cam)
This method supports two modes: if the recorder is currently recording, the camera argument will be saved into the recording; else if the recorder is playing, the camera argument will be set to the current replaid camera.
Parameters
cam A reference to the camera to record/update.
Definition at line 8 of file CameraRecorder.cpp.
References _cameras, _interp, _playing, _playNoInterp, _pos, _recording, _saving, _savingPath, _savingVideo, _speed, sibr::Camera::interpolate(), sibr::Camera::setDebugVideo(), sibr::Camera::setSavePath(), SIBR_LOG, stop(), sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::InteractiveCameraHandler::update().
Member Data Documentation
_cameras
std::vector<Camera> sibr::CameraRecorder::_cameras private
List of recorded cameras.
Definition at line 196 of file CameraRecorder.hpp.
Referenced by load(), loadBundle(), loadColmap(), loadLookat(), recordOfflinePath(), reset(), save(), saveAsBundle(), saveAsFRIBRBundle(), saveAsLookAt(), and use().
_interp
float sibr::CameraRecorder::_interp private
Current interpoaltion factor.
Definition at line 204 of file CameraRecorder.hpp.
Referenced by stop(), and use().
_oh
int sibr::CameraRecorder::_oh private
offline output path resolution
Definition at line 206 of file CameraRecorder.hpp.
Referenced by loadPath(), and recordOfflinePath().
_ow
int sibr::CameraRecorder::_ow private
Definition at line 206 of file CameraRecorder.hpp.
Referenced by loadPath(), and recordOfflinePath().
_playing
bool sibr::CameraRecorder::_playing private
Are we currently playing.
Definition at line 198 of file CameraRecorder.hpp.
Referenced by playback(), stop(), and use().
_playNoInterp
bool sibr::CameraRecorder::_playNoInterp private
Just play the cameras, make sure focal is preserved.
Definition at line 205 of file CameraRecorder.hpp.
Referenced by use().
_pos
uint sibr::CameraRecorder::_pos private
Current camera ID for replay.
Definition at line 195 of file CameraRecorder.hpp.
Referenced by stop(), and use().
_recording
bool sibr::CameraRecorder::_recording private
Are we currently recording.
Definition at line 197 of file CameraRecorder.hpp.
Referenced by record(), stop(), and use().
_saving
bool sibr::CameraRecorder::_saving private
Are we saving the path as images.
Definition at line 199 of file CameraRecorder.hpp.
Referenced by use().
_savingPath
std::string sibr::CameraRecorder::_savingPath private
Destination base path for saved images.
Definition at line 200 of file CameraRecorder.hpp.
Referenced by loadPath(), recordOfflinePath(), and use().
_savingVideo
bool sibr::CameraRecorder::_savingVideo private
Are we saving the path as video.
Definition at line 201 of file CameraRecorder.hpp.
Referenced by savingVideo(), and use().
_savingVideoPath
std::string sibr::CameraRecorder::_savingVideoPath private
Destination base path for saved video.
Definition at line 202 of file CameraRecorder.hpp.
_speed
float sibr::CameraRecorder::_speed private
Playback speed.
Definition at line 203 of file CameraRecorder.hpp.
Referenced by use().
The documentation for this class was generated from the following files:
src/core/assets/CameraRecorder.hpp
src/core/assets/CameraRecorder.cpp