SIBR: sibr::RenderTargetTextures Class Reference
sibr::RenderTargetTextures Class Reference
sibr_scene
#include <RenderTargetTextures.hpp>
Public Member Functions
RenderTargetTextures (uint w=0)
virtual void initRGBandDepthTextureArrays (ICalibratedCameras::Ptr cams, IInputImages::Ptr imgs, IProxyMesh::Ptr proxies, int textureFlags, int texture_width, bool faceCull=true)
virtual void initRGBandDepthTextureArrays (ICalibratedCameras::Ptr cams, IInputImages::Ptr imgs, IProxyMesh::Ptr proxies, int textureFlags, bool faceCull=true)
virtual void initializeDefaultRenderTargets (ICalibratedCameras::Ptr cams, IInputImages::Ptr imgs, IProxyMesh::Ptr proxies)
Public Member Functions inherited from sibr::RGBDInputTextures
const std::vector< RenderTargetRGBA32F::Ptr > & inputImagesRT () const
virtual void initializeImageRenderTargets (ICalibratedCameras::Ptr cams, IInputImages::Ptr imgs)
virtual void initializeDepthRenderTargets (ICalibratedCameras::Ptr cams, IProxyMesh::Ptr proxies, bool facecull)
Public Member Functions inherited from sibr::RTTextureSize
RTTextureSize (uint w=0)
void initSize (uint w, uint h)
bool isInit () const
Public Member Functions inherited from sibr::DepthInputTextureArray
virtual void initDepthTextureArrays (ICalibratedCameras::Ptr cams, IProxyMesh::Ptr proxies, bool facecull, int flags=SIBR_GPU_LINEAR_SAMPLING)
const Texture2DArrayLum32F::Ptr & getInputDepthMapArrayPtr () const
Public Member Functions inherited from sibr::RGBInputTextureArray
virtual void initRGBTextureArrays (IInputImages::Ptr imgs, int flags=0)
const Texture2DArrayRGB::Ptr & getInputRGBTextureArrayPtr () const
Protected Member Functions
void initRenderTargetRes (ICalibratedCameras::Ptr cams)
Additional Inherited Members
Protected Attributes inherited from sibr::RGBDInputTextures
std::vector< RenderTargetRGBA32F::Ptr > _inputRGBARenderTextures
Protected Attributes inherited from sibr::RTTextureSize
uint _width = 0
uint _height = 0
bool _isInit = false
int _initActiveCam = 0
Protected Attributes inherited from sibr::DepthInputTextureArray
Texture2DArrayLum32F::Ptr _inputDepthMapArrayPtr
Protected Attributes inherited from sibr::RGBInputTextureArray
Texture2DArrayRGB::Ptr _inputRGBArrayPtr
Detailed Description
Definition at line 86 of file RenderTargetTextures.hpp.
Constructor & Destructor Documentation
RenderTargetTextures()
sibr::RenderTargetTextures::RenderTargetTextures (uint w = 0) inline
Definition at line 95 of file RenderTargetTextures.hpp.
Member Function Documentation
initializeDefaultRenderTargets()
void sibr::RenderTargetTextures::initializeDefaultRenderTargets (ICalibratedCameras::Ptr cams, IInputImages::Ptr imgs, IProxyMesh::Ptr proxies) virtual
Definition at line 196 of file RenderTargetTextures.cpp.
References sibr::RGBDInputTextures::initializeDepthRenderTargets(), sibr::RGBDInputTextures::initializeImageRenderTargets(), initRenderTargetRes(), and sibr::RTTextureSize::isInit().
initRenderTargetRes()
void sibr::RenderTargetTextures::initRenderTargetRes (ICalibratedCameras::Ptr cams) protected
Definition at line 206 of file RenderTargetTextures.cpp.
References sibr::RTTextureSize::_initActiveCam, and SIBR_ERR.
Referenced by initializeDefaultRenderTargets(), and initRGBandDepthTextureArrays().
initRGBandDepthTextureArrays() [1/2]
void sibr::RenderTargetTextures::initRGBandDepthTextureArrays (ICalibratedCameras::Ptr cams, IInputImages::Ptr imgs, IProxyMesh::Ptr proxies, int textureFlags, bool faceCull = true) virtual
Definition at line 224 of file RenderTargetTextures.cpp.
References sibr::DepthInputTextureArray::initDepthTextureArrays(), initRenderTargetRes(), sibr::RGBInputTextureArray::initRGBTextureArrays(), and sibr::RTTextureSize::isInit().
initRGBandDepthTextureArrays() [2/2]
void sibr::RenderTargetTextures::initRGBandDepthTextureArrays (ICalibratedCameras::Ptr cams, IInputImages::Ptr imgs, IProxyMesh::Ptr proxies, int textureFlags, int texture_width, bool faceCull = true) virtual
Definition at line 218 of file RenderTargetTextures.cpp.
References sibr::RTTextureSize::_width.
The documentation for this class was generated from the following files:
src/core/scene/RenderTargetTextures.hpp
src/core/scene/RenderTargetTextures.cpp