SIBR: src/projects/dataset_tools/preprocess/alignMeshes/main.cpp File Reference
main.cpp File Reference
#include <fstream>
#include <boost/filesystem.hpp>
#include <core/system/Utils.hpp>
#include <opencv2/features2d/features2d.hpp>
#include <opencv2/flann/flann.hpp>
#include <core/renderer/DepthRenderer.hpp>
#include <core/graphics/Window.hpp>
#include <core/scene/BasicIBRScene.hpp>
#include <core/scene/ParseData.hpp>
Classes
struct AlignMeshesArgs
Macros
#define PROGRAM_NAME "sibr_chunk2sibr"
#define MAX_ITERS 100
#define TUNING_CONSTANT 4.685
Functions
double distPatch (sibr::ImageRGB &im1, sibr::Vector2i &tpos, sibr::ImageRGB &im2, sibr::Vector2i &spos, int size)
float findMAD (const Eigen::VectorXf &vec)
Eigen::VectorXf weight (Eigen::VectorXf v)
void irls (Eigen::MatrixX4f mX, Eigen::VectorXf vY, Eigen::Vector4f &mCoeffs, float tune)
static bool isRawRC (std::string pathRC)
static void loadRawRC (std::string pathRC, std::vector< sibr::InputCamera::Ptr > &cams2Align, std::vector< sibr::ImageRGB::Ptr > &imgs2Align, sibr::Mesh &mesh2Align)
int assignImages (std::vector< sibr::ImageRGB::Ptr > &imgs2Align, std::vector< sibr::ImageRGB > &imgs2AlignSmall, std::vector< sibr::ImageRGB::Ptr > &imgsRef, std::vector< sibr::ImageRGB > &imgsRefSmall, std::map< int, int > &alignCamToRef, std::vector< sibr::InputCamera::Ptr > &camsRef, std::vector< sibr::InputCamera::Ptr > cams2Align, int resizeW, std::set< int > &assignedCam, float threshold)
InputCamera rot90CC (InputCamera::Ptr &in)
int main (int ac, char **av)
template<typename T >
std::vector< size_t > sort_indexes (const std::vector< T > &v)
void computeRT (std::vector< sibr::Vector3f > A, std::vector< sibr::Vector3f >B, Matrix3f S, Matrix3f &R, sibr::Vector3f &T)
float computeS (std::vector< sibr::Vector3f > A, std::vector< sibr::Vector3f >B, float &minScale, float &maxScale)
Variables
const char * usage
Macro Definition Documentation
MAX_ITERS
#define MAX_ITERS 100
Definition at line 60 of file main.cpp.
PROGRAM_NAME
#define PROGRAM_NAME "sibr_chunk2sibr"
Definition at line 12 of file main.cpp.
TUNING_CONSTANT
#define TUNING_CONSTANT 4.685
Function Documentation
assignImages()
int assignImages (std::vector< sibr::ImageRGB::Ptr > & imgs2Align, std::vector< sibr::ImageRGB > & imgs2AlignSmall, std::vector< sibr::ImageRGB::Ptr > & imgsRef, std::vector< sibr::ImageRGB > & imgsRefSmall, std::map< int, int > & alignCamToRef, std::vector< sibr::InputCamera::Ptr > & camsRef, std::vector< sibr::InputCamera::Ptr > cams2Align, int resizeW, std::set< int > & assignedCam, float threshold)
Definition at line 155 of file main.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), sibr::Image< T_Type, T_NumComp >::toOpenCV(), and sibr::Image< T_Type, T_NumComp >::w().
Referenced by main().
computeRT()
void computeRT (std::vector< sibr::Vector3f > A, std::vector< sibr::Vector3f > B, Matrix3f S, Matrix3f & R, sibr::Vector3f & T)
Definition at line 749 of file main.cpp.
References sibr::Key::A, sibr::Key::B, H, sibr::Key::R, sibr::Key::S, and sibr::Key::T.
computeS()
float computeS (std::vector< sibr::Vector3f > A, std::vector< sibr::Vector3f > B, float & minScale, float & maxScale)
Definition at line 793 of file main.cpp.
References sibr::Key::A, and sibr::Key::B.
distPatch()
double distPatch (sibr::ImageRGB & im1, sibr::Vector2i & tpos, sibr::ImageRGB & im2, sibr::Vector2i & spos, int size)
Definition at line 19 of file main.cpp.
References sibr::Image< T_Type, T_NumComp >::cast(), and sibr::Image< T_Type, T_NumComp >::isInRange().
Referenced by main().
findMAD()
float findMAD (const Eigen::VectorXf & vec)
Definition at line 38 of file main.cpp.
Referenced by irls().
irls()
void irls (Eigen::MatrixX4f mX, Eigen::VectorXf vY, Eigen::Vector4f & mCoeffs, float tune)
Definition at line 62 of file main.cpp.
References findMAD(), MAX_ITERS, and weight().
Referenced by main().
isRawRC()
static bool isRawRC (std::string pathRC) static
Definition at line 115 of file main.cpp.
References sibr::fileExists(), sibr::Mesh::load(), and SIBR_WRG.
Referenced by main().
loadRawRC()
static void loadRawRC (std::string pathRC, std::vector< sibr::InputCamera::Ptr > & cams2Align, std::vector< sibr::ImageRGB::Ptr > & imgs2Align, sibr::Mesh & mesh2Align) static
Definition at line 134 of file main.cpp.
References sibr::Image< T_Type, T_NumComp >::clonePtr(), sibr::Mesh::load(), sibr::Image< T_Type, T_NumComp >::load(), sibr::InputCamera::loadBundle(), and SIBR_ERR.
Referenced by main().
main()
int main (int ac, char ** av)
Definition at line 253 of file main.cpp.
References sibr::DepthRenderer::_depth_RT, assignImages(), sibr::Image< T_Type, T_NumComp >::clone(), sibr::BasicDatasetArgs::dataset_path, distPatch(), sibr::IParseData::EMPTY, AlignMeshesArgs::forceLandscape, sibr::RequiredArgBase< T >::get(), sibr::Image< T_Type, T_NumComp >::h(), irls(), sibr::Image< T_Type, T_NumComp >::isInRange(), isRawRC(), loadRawRC(), sibr::makeDirectory(), AlignMeshesArgs::outPath, sibr::CommandLineArgs::parseMainArgs(), AlignMeshesArgs::pathRef, AlignMeshesArgs::pathToAlign, PROGRAM_NAME, sibr::DepthRenderer::render(), rot90CC(), sibr::Mesh::save(), sibr::InputCamera::saveAsBundle(), AlignMeshesArgs::saveScene, SIBR_ERR, sibr::toOpenCV(), TUNING_CONSTANT, sibr::Mesh::vertices(), sibr::Image< T_Type, T_NumComp >::w(), and xyz().
Referenced by sibr::BinaryMeshRenderer::BinaryMeshRenderer().
rot90CC()
InputCamera rot90CC (InputCamera::Ptr & in)
Definition at line 232 of file main.cpp.
References sibr::Camera::aspect(), sibr::Camera::dir(), sibr::InputCamera::focal(), sibr::Camera::fovy(), sibr::InputCamera::h(), sibr::Camera::position(), sibr::Camera::right(), sibr::Camera::setLookAt(), sibr::InputCamera::size(), and sibr::InputCamera::w().
Referenced by main().
sort_indexes()
template<typename T > std::vector<size_t> sort_indexes (const std::vector< T > & v)
Definition at line 734 of file main.cpp.
weight()
Eigen::VectorXf weight (Eigen::VectorXf v)
Definition at line 49 of file main.cpp.
Referenced by sibr::MRFSolver::buildGraphBinaryLabels(), sibr::InteractiveCameraHandler::findNearestCamera(), irls(), and sibr::MeshTexturing::reproject().
Variable Documentation
usage
const char* usage
Initial value:
= ""
"Usage: " PROGRAM_NAME " -path <reference scene path> -path2 <scene to align path> -outPath <mesh output path>" "\n"
Definition at line 15 of file main.cpp.