SIBR: src/projects/dataset_tools/preprocess/cropFromCenter/main.cpp File Reference
main.cpp File Reference
#include <core/imgproc/CropScaleImageUtility.hpp>
#include <core/system/CommandLineArgs.hpp>
Classes
struct CropAppArgs
Functions
void printUsage ()
bool getParamas (int argc, const char **argv, std::string &inputFile, boost::filesystem::path &outputPath, sibr::Vector2i &avgResolution, sibr::Vector2i &cropResolution, float &scaleDownFactor, sibr::Vector2i &targetResolution)
int main (const int argc, const char **argv)
Variables
const char * USAGE = "Usage: cropFromCenter --inputFile <path_to_input_file> --outputPath <path_to_output_folder> --avgResolution <width x height> --cropResolution <width x height> [--scaleDownFactor <alpha> --targetResolution <width x height>] \n"
const char * TAG = "[cropFromCenter]"
const unsigned PROCESSING_BATCH_SIZE = 150
const char * LOG_FILE_NAME = "cropFromCenter.log"
const char * SCALED_DOWN_SUBFOLDER = "scaled"
const char * SCALED_DOWN_FILENAME = "scale_factor.txt"
Function Documentation
getParamas()
bool getParamas (int argc, const char ** argv, std::string & inputFile, boost::filesystem::path & outputPath, sibr::Vector2i & avgResolution, sibr::Vector2i & cropResolution, float & scaleDownFactor, sibr::Vector2i & targetResolution)
Definition at line 34 of file main.cpp.
References CropAppArgs::avgResolutionArg, CropAppArgs::cropResolutionArg, sibr::ArgBase< T >::get(), CropAppArgs::inputFileArg, CropAppArgs::outputFolderArg, sibr::CommandLineArgs::parseMainArgs(), CropAppArgs::scaleDownFactorArg, and CropAppArgs::targetResolutionArg.
Referenced by main().
main()
int main (const int argc, const char ** argv)
Definition at line 69 of file main.cpp.
References getParamas(), sibr::CropScaleImageUtility::getPathToImgs(), LOG_FILE_NAME, sibr::CropScaleImageUtility::logExecution(), printUsage(), PROCESSING_BATCH_SIZE, SCALED_DOWN_FILENAME, SCALED_DOWN_SUBFOLDER, TAG, sibr::CropScaleImageUtility::writeListImages(), sibr::CropScaleImageUtility::writeScaleFactor(), and sibr::CropScaleImageUtility::writeTargetResolution().
printUsage()
void printUsage ()
Definition at line 28 of file main.cpp.
References USAGE.
Referenced by main().
Variable Documentation
LOG_FILE_NAME
const char* LOG_FILE_NAME = "cropFromCenter.log"
Definition at line 14 of file main.cpp.
Referenced by main().
PROCESSING_BATCH_SIZE
const unsigned PROCESSING_BATCH_SIZE = 150
Definition at line 13 of file main.cpp.
Referenced by main().
SCALED_DOWN_FILENAME
const char* SCALED_DOWN_FILENAME = "scale_factor.txt"
Definition at line 16 of file main.cpp.
Referenced by main().
SCALED_DOWN_SUBFOLDER
const char* SCALED_DOWN_SUBFOLDER = "scaled"
Definition at line 15 of file main.cpp.
Referenced by main().
TAG
const char* TAG = "[cropFromCenter]"
Definition at line 12 of file main.cpp.
USAGE
const char* USAGE = "Usage: cropFromCenter --inputFile <path_to_input_file> --outputPath <path_to_output_folder> --avgResolution <width x height> --cropResolution <width x height> [--scaleDownFactor <alpha> --targetResolution <width x height>] \n"
Definition at line 10 of file main.cpp.