SIBR: src/projects/dataset_tools/preprocess/tonemapper/main.cpp File Reference
main.cpp File Reference
#include "core/system/CommandLineArgs.hpp"
#include "core/assets/InputCamera.hpp"
#include "core/graphics/Image.hpp"
#include "core/graphics/Mesh.hpp"
#include "core/imgproc/MeshTexturing.hpp"
#include "core/scene/BasicIBRScene.hpp"
Classes
struct TonemapperAppArgs
Functions
void tonemap (const sibr::ImageRGB32F &hdrImg, sibr::ImageRGB &ldrImg, float exposure, float gamma)
int main (int ac, char **av)
Function Documentation
main()
int main (int ac, char ** av)
Definition at line 33 of file main.cpp.
References ibr_preprocess_rc_to_sibr::dst, TonemapperAppArgs::exposure, TonemapperAppArgs::gamma, sibr::listFiles(), sibr::Image< T_Type, T_NumComp >::load(), sibr::makeDirectory(), TonemapperAppArgs::output, TonemapperAppArgs::outputExtension, sibr::CommandLineArgs::parseMainArgs(), TonemapperAppArgs::path, sibr::removeExtension(), sibr::Image< T_Type, T_NumComp >::save(), ibr_preprocess_rc_to_sibr::src, and tonemap().
tonemap()
void tonemap (const sibr::ImageRGB32F & hdrImg, sibr::ImageRGB & ldrImg, float exposure, float gamma)
Definition at line 19 of file main.cpp.
References sibr::Image< T_Type, T_NumComp >::fromOpenCV(), and sibr::Image< T_Type, T_NumComp >::toOpenCV().
Referenced by main().