SIBR: src/projects/dataset_tools/preprocess/distordCrop/main.cpp File Reference
main.cpp File Reference
#include <core/imgproc/DistordCropUtility.hpp>
#include <core/system/CommandLineArgs.hpp>
Classes
struct DistordCropAppArgs
Typedefs
typedef boost::filesystem::path Path
Functions
int main (const int argc, const char *const *argv)
Variables
int threshold_black_color = 10
int thinest_bounding_box_size = 5
int threshold_bounding_box_size = 500
float threshold_ratio_bounding_box_size = 0.2f
const int PROCESSING_BATCH_SIZE = 150
sibr::Vector3i backgroundColor = sibr::Vector3i(0, 0, 0)
float resolutionThreshold = 0.15f
float toleranceFactor = 0.0f
bool debug_viz = false
Typedef Documentation
Path
typedef boost::filesystem::path Path
Definition at line 4 of file main.cpp.
Function Documentation
main()
int main (const int argc, const char *const * argv)
Definition at line 61 of file main.cpp.
References DistordCropAppArgs::avgHeightArg, DistordCropAppArgs::avgWidthArg, backgroundColor, DistordCropAppArgs::backgroundColor, DistordCropAppArgs::black_threshold, sibr::BasicDatasetArgs::dataset_path, debug_viz, sibr::DistordCropUtility::findBiggestImageCenteredBox(), sibr::DistordCropUtility::findMinImageSize(), sibr::ArgBase< T >::get(), sibr::DistordCropUtility::is_number(), ibr_convert_old_to_new::line, DistordCropAppArgs::minRatioThresholdArg, DistordCropAppArgs::minSizeThresholdArg, DistordCropAppArgs::modeArg, sibr::CommandLineArgs::parseMainArgs(), PROCESSING_BATCH_SIZE, resolutionThreshold, DistordCropAppArgs::resThreshold, thinest_bounding_box_size, threshold_black_color, threshold_bounding_box_size, threshold_ratio_bounding_box_size, DistordCropAppArgs::toleranceArg, toleranceFactor, and DistordCropAppArgs::vizArg.
Variable Documentation
backgroundColor
sibr::Vector3i backgroundColor = sibr::Vector3i(0, 0, 0)
Definition at line 14 of file main.cpp.
Referenced by sibr::DistordCropUtility::addPixelToQueue(), sibr::DistordCropUtility::findBiggestImageCenteredBox(), sibr::DistordCropUtility::getBounds(), sibr::DistordCropUtility::isBlack(), and main().
debug_viz
bool debug_viz = false
Definition at line 28 of file main.cpp.
Referenced by main().
PROCESSING_BATCH_SIZE
const int PROCESSING_BATCH_SIZE = 150
Definition at line 12 of file main.cpp.
resolutionThreshold
float resolutionThreshold = 0.15f
Definition at line 19 of file main.cpp.
Referenced by sibr::DistordCropUtility::findBiggestImageCenteredBox(), and main().
thinest_bounding_box_size
int thinest_bounding_box_size = 5
Definition at line 8 of file main.cpp.
Referenced by sibr::DistordCropUtility::findBiggestImageCenteredBox(), sibr::DistordCropUtility::findBounds(), sibr::DistordCropUtility::getBounds(), and main().
threshold_black_color
int threshold_black_color = 10
Definition at line 7 of file main.cpp.
Referenced by sibr::DistordCropUtility::addPixelToQueue(), sibr::DistordCropUtility::findBiggestImageCenteredBox(), sibr::DistordCropUtility::getBounds(), sibr::DistordCropUtility::isBlack(), and main().
threshold_bounding_box_size
int threshold_bounding_box_size = 500
Definition at line 9 of file main.cpp.
Referenced by main().
threshold_ratio_bounding_box_size
float threshold_ratio_bounding_box_size = 0.2f
Definition at line 10 of file main.cpp.
Referenced by sibr::DistordCropUtility::findBiggestImageCenteredBox(), and main().
toleranceFactor
float toleranceFactor = 0.0f
Definition at line 26 of file main.cpp.
Referenced by sibr::DistordCropUtility::findBiggestImageCenteredBox(), sibr::DistordCropUtility::getBounds(), and main().