SIBR: src/projects/dataset_tools/preprocess/nvmToSIBR/main.cpp File Reference
main.cpp File Reference
#include <fstream>
#include <iostream>
#include <core/system/CommandLineArgs.hpp>
#include <core/scene/BasicIBRScene.hpp>
#include <core/raycaster/CameraRaycaster.hpp>
#include <core/assets/ImageListFile.hpp>
#include <core/system/Utils.hpp>
Classes
struct ColmapPreprocessArgs
Macros
#define PROGRAM_NAME "sibr_nvm_to_sibr"
Functions
int main (const int argc, const char **argv)
Variables
const char * usage
Macro Definition Documentation
PROGRAM_NAME
#define PROGRAM_NAME "sibr_nvm_to_sibr"
Definition at line 10 of file main.cpp.
Function Documentation
main()
int main (const int argc, const char ** argv)
Definition at line 21 of file main.cpp.
References sibr::BasicIBRScene::cameras(), sibr::copyFile(), sibr::BasicIBRScene::data(), sibr::BasicDatasetArgs::dataset_path, sibr::directoryExists(), sibr::InputCamera::h(), sibr::InputCamera::id(), sibr::makeDirectory(), sibr::InputCamera::name(), sibr::CommandLineArgs::parseMainArgs(), sibr::InputCamera::toBundleString(), sibr::InputCamera::w(), sibr::Camera::zfar(), and sibr::Camera::znear().
Variable Documentation
usage
const char* usage
Initial value:
= ""
"Usage: " PROGRAM_NAME " -path " "\n"
Definition at line 13 of file main.cpp.