SIBR: src/projects/dataset_tools/preprocess/cameraConverter/main.cpp File Reference
main.cpp File Reference
#include "core/system/CommandLineArgs.hpp"
#include "core/assets/InputCamera.hpp"
Classes
struct CameraConverterArgs
Functions
bool load (const std::string &filename, std::vector< InputCamera::Ptr > &cams, const sibr::Vector2u &res)
void save (const std::string &filename, const std::vector< InputCamera::Ptr > &cams)
SIBR binary path saver helper.
void colmapSave (const std::string &filename, const std::vector< InputCamera::Ptr > &xformPath)
int main (int ac, char **av)
The camera converter is a utility to convert a camera path from a file format to another, with additional options.
Function Documentation
colmapSave()
void colmapSave (const std::string & filename, const std::vector< InputCamera::Ptr > & xformPath)
Definition at line 58 of file main.cpp.
References sibr::parentDirectory(), sibr::quatFromMatrix(), and SIBR_ERR.
Referenced by main().
load()
bool load (const std::string & filename, std::vector< InputCamera::Ptr > & cams, const sibr::Vector2u & res)
Definition at line 25 of file main.cpp.
References sibr::ByteStream::load().
Referenced by sibr::InputImages::loadFromPath(), sibr::Mesh::loadMtsXML(), and main().
main()
int main (int ac, char ** av)
The camera converter is a utility to convert a camera path from a file format to another, with additional options.
You can specify a 4x4 transformation matrix to apply, stored in a txt file (values separated by spaces/newlines, f.i. the output of CloudCompare alignment). If you want to apply the inverse transformation, use the –inverse flag. Supported inputs: path (*), lookat (*), bundle, nvm (*), colmap Supported outputs: path, bundle(*), lookat, colmap (images.txt) (*): requires an input/output resolution (often only for the aspect ratio).
Definition at line 112 of file main.cpp.
References CameraConverterArgs::bundleImageFiles, CameraConverterArgs::bundleImageList, colmapSave(), sibr::directoryExists(), sibr::ArgBase< T >::get(), sibr::RequiredArgBase< T >::get(), sibr::getExtension(), sibr::getFileName(), CameraConverterArgs::inImageFilePath, CameraConverterArgs::input, CameraConverterArgs::inputRes, CameraConverterArgs::inverse, load(), sibr::InputCamera::loadBundle(), sibr::InputCamera::loadColmap(), sibr::InputCamera::loadLookat(), sibr::InputCamera::loadNVM(), CameraConverterArgs::output, CameraConverterArgs::outputRes, sibr::CommandLineArgs::parseMainArgs(), sibr::round(), save(), sibr::InputCamera::saveAsBundle(), sibr::InputCamera::saveAsLookat(), SIBR_ERR, SIBR_LOG, CameraConverterArgs::transfo, and xyz().
save()
void save (const std::string & filename, const std::vector< InputCamera::Ptr > & cams)
SIBR binary path saver helper.
Parameters
filename the .path output file
cams the cameras to save
Definition at line 45 of file main.cpp.
References sibr::ByteStream::saveToFile().
Referenced by main().