SIBR: sibr_video
sibr_video
Video loading, processing and display.
Classes
class sibr::FFVideoEncoder
Video encoder using ffmpeg.
struct sibr::PingPongTexture< N >
Double-buffered texture, used to load/display video frames for instance.
struct sibr::MultipleVideoDecoder< T, N >
Batch decoding of multiple videos at the same time, stored in a texture array.
struct sibr::MultipleVideoDecoderArray< T, N >
Batch decoding of multiple videos at the same time, stored in a texture array.
class sibr::Video
Video loaded from a file using OpenCV VideoCapture and FFMPEG.
class sibr::VideoPlayer
Load and display a video in a view, with playback options.
class sibr::VideoVolume< T, N >
struct sibr::PyramidLayer
struct sibr::PyramidParameters
class sibr::VideoGaussianPyramid
class sibr::VideoLaplacianPyramid
struct sibr::ContribData
struct sibr::FullContribData
class sibr::Histogram< T, N >
class sibr::Histogram< T, 1 >
struct sibr::TimeHistogram
class sibr::VideoUtils
Typedefs
using sibr::VideoVolume< T, N >::CVpixel = std::conditional_t< N==1, T, cv::Vec< T, N > >
using sibr::Histogram< T, N >::Value = Vector< T, N >
using sibr::Histogram< T, N >::Indice = Vector< uint, N >
using sibr::Histogram< T, N >::Range = Vector< double, N >
using sibr::Histo1f = Histogram< float, 1 >
using sibr::ColorHistogram = Histogram< uchar, 3 >
Functions
static void sibr::CV_Assign< T, N >::assignValue (uint c, const T &val, cv::Vec< T, N > &vec)
static void sibr::CV_Assign< T, 1 >::assignValue (uint c, const T &val, T &vec)
sibr::VideoVolume< T, N >::VideoVolume ()
sibr::VideoVolume< T, N >::VideoVolume (int _l, int _w, int _h)
sibr::VideoVolume< T, N >::VideoVolume (int _l, int _w, int _h, double value)
sibr::VideoVolume< T, N >::VideoVolume (cv::Mat other_volume, int _w, int _h)
sibr::VideoVolume< T, N >::VideoVolume (const VideoVolume &other)
template<typename U , uint M>
void sibr::VideoVolume< T, N >::setupFrom (const VideoVolume< U, M > &other)
VideoVolume sibr::VideoVolume< T, N >::clone () const
template<typename U , uint M = N>
VideoVolume< U, M > sibr::VideoVolume< T, N >::convertTo () const
void sibr::VideoVolume< T, N >::toggle (double d=255)
void sibr::VideoVolume< T, N >::shift (double d)
void sibr::VideoVolume< T, N >::scale (double d)
template<typename T >
void sibr::VideoVolume< T, N >::add (const VideoVolume< T, N > &other)
template<typename U >
void sibr::VideoVolume< T, N >::substract (const VideoVolume< U, N > &other)
template<typename U , uint M>
void sibr::VideoVolume< T, N >::multiply (const VideoVolume< U, M > &other)
VideoVolume sibr::VideoVolume< T, N >::concat (const VideoVolume &other) const
VideoVolume sibr::VideoVolume< T, N >::concatH (const VideoVolume &other) const
VideoVolume sibr::VideoVolume< T, N >::applyMaskBinary (const Volume1u &mask)
VideoVolume sibr::VideoVolume< T, N >::swapRBchannels () const
template<uint M>
VideoVolume sibr::VideoVolume< T, N >::applyMask (const VideoVolume< uchar, M > &mask)
template<typename T , uint M>
void sibr::VideoVolume< T, N >::applyMaskInPlace (const VideoVolume< T, M > &mask)
VideoVolume sibr::VideoVolume< T, N >::cutFrames (int numBefore, int numAfter)
VideoVolume< uchar, 3 > sibr::VideoVolume< T, N >::colorMapped (int colormap, double scaling=1.0)
void sibr::VideoVolume< T, N >::temporalBlur (float scaling=1.0f)
void sibr::VideoVolume< T, N >::temporalBlurBoundaryConditions (float scaling, double left, double right)
void sibr::VideoVolume< T, N >::extendedTemporalBlur ()
VideoVolume sibr::VideoVolume< T, N >::pyrDownSpacial () const
VideoVolume sibr::VideoVolume< T, N >::pyrDownTemporalModif ()
VideoVolume sibr::VideoVolume< T, N >::pyrDownTemporal () const
VideoVolume sibr::VideoVolume< T, N >::pyrDownTemporalBox () const
VideoVolume sibr::VideoVolume< T, N >::extendedDownScaleTemporal () const
VideoVolume sibr::VideoVolume< T, N >::pyrDown () const
VideoVolume sibr::VideoVolume< T, N >::pyrUpSpacial (int _w, int _h) const
VideoVolume sibr::VideoVolume< T, N >::pyrUpTemporal (int _l) const
VideoVolume sibr::VideoVolume< T, N >::pyrUpTemporalBoundaryConditions (int _l, double left, double right) const
VideoVolume sibr::VideoVolume< T, N >::pyrDownBoundaryConditions (double left, double right) const
VideoVolume sibr::VideoVolume< T, N >::pyrUp (int _l, int _w, int _h) const
void sibr::VideoVolume< T, N >::play (int delay=30, const sibr::Vector2i &res={ -1,-1 }, double scale=1.0) const
void sibr::VideoVolume< T, N >::playStd (double scale=1.0) const
void sibr::VideoVolume< T, N >::saveToVideoFile (const std::string &filepath, double framerate=30.0) const
cv::Mat_< CVpixel > sibr::VideoVolume< T, N >::frame (int t)
const cv::Mat_< CVpixel > sibr::VideoVolume< T, N >::frame (int t) const
cv::Mat_< T > sibr::VideoVolume< T, N >::time_sequence (int i, int j, int c=0) const
cv::Mat_< CVpixel > sibr::VideoVolume< T, N >::time_sequence_pixels (int i, int j) const
VideoVolume sibr::VideoVolume< T, N >::time_sequence_volume (int i, int j) const
cv::Mat sibr::VideoVolume< T, N >::video_line (int i) const
VideoVolume sibr::VideoVolume< T, N >::subVolumeRef (int t_start, int t_end)
VideoVolume sibr::VideoVolume< T, N >::subVolume (int t_start, int t_end) const
VideoVolume sibr::VideoVolume< T, N >::subVolumeSpatial (int x, int y, int w, int h) const
VideoVolume sibr::VideoVolume< T, N >::subVolume_i (int i_start, int i_end) const
VideoVolume sibr::VideoVolume< T, N >::subVolume_i_copy (int i_start, int i_end) const
VideoVolume sibr::VideoVolume< T, N >::duplicateTime (int num) const
cv::Mat_< CVpixel > sibr::VideoVolume< T, N >::spatialSlice (int i_start, int j_start, int i_end, int j_end)
cv::Mat_< CVpixel > sibr::VideoVolume< T, N >::median_frame () const
T & sibr::VideoVolume< T, N >::valueAt (int t, int i, int j, int c=0)
const T & sibr::VideoVolume< T, N >::valueAt (int t, int i, int j, int c=0) const
CVpixel & sibr::VideoVolume< T, N >::pixelAt (int t, int i, int j)
const CVpixel & sibr::VideoVolume< T, N >::pixelAt (int t, int i, int j) const
bool sibr::VideoVolume< T, N >::isValid () const
void sibr::VideoVolume< T, N >::cout () const
VideoVolume sibr::VideoVolume< T, N >::spatialRescale (float f) const
Volume3u sibr::loadVideoVolume (const std::string &filepath)
Volume3u sibr::loadVideoVolume (sibr::Video &video)
template<typename T , uint N, uint M>
VideoVolume< T, N+M > sibr::concatVolumesChannels (const sibr::VideoVolume< T, N > &A, const sibr::VideoVolume< T, M > &B)
SIBR_VIDEO_EXPORT uint sibr::optimal_num_levels (uint length)
template<uint M>
std::vector< sibr::VideoVolume< uchar, M > > sibr::extendedBlurPyramid (const sibr::VideoVolume< uchar, M > &vid, uint num_levels=0)
template<uint M>
std::vector< sibr::VideoVolume< uchar, M > > sibr::gaussianPyramid (const sibr::VideoVolume< uchar, M > &vid, uint num_levels=0)
template<typename T , uint M>
std::vector< sibr::VideoVolume< T, M > > sibr::gaussianPyramidTemporal (const sibr::VideoVolume< T, M > &vid, uint num_levels=0)
template<typename T , uint M>
std::vector< sibr::VideoVolume< T, M > > sibr::gaussianPyramidTemporalBox (const sibr::VideoVolume< T, M > &vid, uint num_levels=0)
std::vector< sibr::Volume3u > sibr::laplacianPyramid (const sibr::Volume3u &vid, uint num_levels)
std::vector< sibr::Volume3u > sibr::laplacianPyramidTemporalDouble (const sibr::Volume3u &vid, uint num_levels)
template<typename U , typename T = U>
std::vector< VideoVolume< T, 3 > > sibr::laplacianPyramidTemporal (const VideoVolume< U, 3 > &vid, uint num_levels=0)
SIBR_VIDEO_EXPORT sibr::Volume3u sibr::collapseLaplacianPyramid (const std::vector< sibr::Volume3u > &pyr, double shift)
template<typename T >
sibr::VideoVolume< T, 3 > sibr::collapseLaplacianPyramidTemporal (const std::vector< sibr::VideoVolume< T, 3 >> &pyr, double shift, bool debug=false)
SIBR_VIDEO_EXPORT sibr::Volume3u sibr::laplacianBlending (const sibr::Volume3u &vA, const sibr::Volume3u &vB, std::vector< sibr::Volume1u > &pyrM)
template<typename T_V , typename T_M >
sibr::VideoVolume< T_V, 3 > sibr::laplacianBlendingTemporal (const sibr::VideoVolume< T_V, 3 > &vA, const sibr::VideoVolume< T_V, 3 > &vB, std::vector< sibr::VideoVolume< T_M, 1 >> &pyrM)
template<typename T , uint N, typename Pix = typename VideoVolume<float, N>::CVpixel>
cv::Mat_< Pix > sibr::totalVariation (const VideoVolume< T, N > &v)
sibr::PyramidLayer::PyramidLayer ()
sibr::PyramidLayer::PyramidLayer (int _w, int _h, int _l, int cv_type=CV_32FC1)
sibr::PyramidLayer::PyramidLayer (const cv::Mat &_volume, int _w, int _h)
PyramidLayer sibr::PyramidLayer::operator+ (const PyramidLayer &other)
PyramidLayer sibr::PyramidLayer::operator- (const PyramidLayer &other)
PyramidLayer sibr::PyramidLayer::clone () const
cv::Mat sibr::PyramidLayer::getRGB (int frame, bool centered=false)
void sibr::PyramidLayer::saveToVideoFile (const std::string &filename, double framerate)
void sibr::PyramidLayer::copySizeFrom (const PyramidLayer &other)
void sibr::PyramidLayer::cout () const
void sibr::PyramidLayer::show (int s=50) const
static void sibr::PyramidLayer::show (PyramidLayer A, PyramidLayer B, int s=50)
static void sibr::PyramidLayer::show (PyramidLayer A, PyramidLayer B, PyramidLayer C, int s=50)
static void sibr::PyramidLayer::show (PyramidLayer A, PyramidLayer B, PyramidLayer C, PyramidLayer D, int s=50, bool centered=false)
static void sibr::PyramidLayer::showDiff (PyramidLayer A, PyramidLayer B, int s=50)
sibr::PyramidParameters::PyramidParameters (int nlevels=5, int temporal=3, int spatial=2, bool spatial_ds=true)
PyramidLayer sibr::blur (const PyramidLayer &layer, const PyramidParameters &params)
PyramidLayer sibr::temporalBlur (const PyramidLayer &layer, const PyramidParameters &params, float scaling)
void sibr::temporalBlurInPlace (PyramidLayer &layer, const PyramidParameters &params, float scaling)
PyramidLayer sibr::decimate (const PyramidLayer &layer, const PyramidParameters &params)
PyramidLayer sibr::upscale (const PyramidLayer &layerUp, const PyramidLayer &layerDown, const PyramidParameters &params)
PyramidLayer sibr::downscale (const PyramidLayer &layer, const PyramidParameters &params)
SIBR_VIDEO_EXPORT cv::Mat sibr::slice (const PyramidLayer &layer, int i, int j, bool vertical, bool center)
sibr::VideoLaplacianPyramid::VideoLaplacianPyramid ()
PyramidLayer sibr::VideoLaplacianPyramid::collapse () const
VideoGaussianPyramid sibr::buildVideoGaussianPyramid (sibr::Video &vid, int nLevels, const PyramidParameters &params, bool show)
VideoGaussianPyramid sibr::buildVideoGaussianPyramid (const cv::Mat &volume, int w, int h, int nLevels, const PyramidParameters &params, bool show)
SIBR_VIDEO_EXPORT VideoLaplacianPyramid sibr::buildVideoLaplacianPyramid (PyramidLayer vid, int nLevels, const PyramidParameters &params, bool show)
VideoLaplacianPyramid sibr::buildVideoLaplacianPyramid (sibr::Video &vid, int nLevels, const PyramidParameters &params, bool show)
VideoLaplacianPyramid sibr::buildVideoLaplacianPyramidFullyReduced (PyramidLayer vid, int nLevels, const PyramidParameters &params, bool show)
SIBR_VIDEO_EXPORT void sibr::convertReducedVideoPyramidTo128 (VideoLaplacianPyramid &vid)
PyramidLayer sibr::videoLaplacianBlending (sibr::Video &vidA, sibr::Video &vidB, PyramidLayer mask_volume)
PyramidLayer sibr::videoLaplacianBlending (PyramidLayer vidA, PyramidLayer vidB, PyramidLayer mask_volume, PyramidParameters params, bool show)
std::vector< FullContribData > sibr::videoLaplacianBlendingContrib (PyramidLayer vidA, PyramidLayer vidB, PyramidLayer mask_volume, PyramidParameters params)
void sibr::videoLaplacianBlendingDebug (PyramidLayer vidA, PyramidLayer vidB, PyramidLayer mask_volume, PyramidParameters params)
sibr::Histogram< T, N >::Histogram (const Value &_min, const Value &_max, uint _numBins=100)
Indice sibr::Histogram< T, N >::whatBin (const Value &value)
void sibr::Histogram< T, N >::addValue (const Value &value)
void sibr::Histogram< T, N >::addValues (const std::vector< Value > &values)
Indice sibr::Histogram< T, N >::getModeIndice () const
Value sibr::Histogram< T, N >::getBinMiddle (const Indice &bin) const
sibr::Histogram< T, 1 >::SIBR_CLASS_PTR (Histogram)
sibr::Histogram< T, 1 >::Histogram (double _min, double _max, int _numBins=100)
bool sibr::Histogram< T, 1 >::whatBin (T value, uint &bin)
void sibr::Histogram< T, 1 >::addValue (T value)
void sibr::Histogram< T, 1 >::addValues (const std::vector< T > &values)
uint sibr::Histogram< T, 1 >::getModeIndice () const
T sibr::Histogram< T, 1 >::getBinMiddle (uint bin) const
std::vector< float > sibr::Histogram< T, 1 >::normalized_values () const
sibr::TimeHistogram::TimeHistogram (double _min, double _max, int _numBins)
void sibr::TimeHistogram::addValues (const std::vector< sibr::Vector3ub > &values)
sibr::Vector3ub sibr::TimeHistogram::getBinMiddle (const sibr::Vector3ub &bin) const
sibr::Vector3ub sibr::TimeHistogram::getHMode () const
void sibr::TimeHistogram::addValue (const sibr::Vector3ub &value)
sibr::Vector3ub sibr::TimeHistogram::whatBin (const sibr::Vector3ub &value)
void sibr::TimeHistogram::computeSortedBins ()
static void sibr::VideoUtils::simpleFlowViz (cv::VideoCapture &cap, float ratio)
static void sibr::VideoUtils::simpleFlowSave (cv::VideoCapture &cap, float ratio, std::function< std::string(int flow_id)> naming_f)
template<typename FunType , typename... OtherArgsTypes>
static void sibr::VideoUtils::loopAndDisplay (cv::VideoCapture &cap, float ratio, FunType f, const OtherArgsTypes &... args)
static void sibr::VideoUtils::deepFlowViz (cv::VideoCapture &cap, float ratio)
static cv::Mat sibr::VideoUtils::getGrey (const cv::Mat &mat)
static cv::Mat sibr::VideoUtils::getFlowViz (const cv::Mat &flow)
static cv::Mat sibr::VideoUtils::cropFromSize (const cv::Mat &mat, const sibr::Vector2i &size)
static void sibr::VideoUtils::getMeanVariance (cv::VideoCapture &cap, cv::Mat &outMean, cv::Mat &outVariance, const sibr::Vector2i &finalSize)
static void sibr::VideoUtils::getMeanVariance2 (cv::VideoCapture &cap, cv::Mat &outMean, cv::Mat &outVariance, const sibr::Vector2i &finalSize, float starting_point_s=0)
static cv::Mat sibr::VideoUtils::getMedian (sibr::Video &vid, float time_skiped_begin=0, float time_skiped_end=0)
static cv::Mat3b sibr::VideoUtils::getMedian (const std::string &path, float time_percentage_crop=0)
static cv::Mat sibr::VideoUtils::getBackgroundImage (sibr::Video &vid, int numBins=50, float time_skip_begin=0, float time_skip_end=0)
static cv::Mat sibr::VideoUtils::getBackgroundImage (const cv::Mat volume, int w, int h, int numBins=50)
static void sibr::VideoUtils::getBackGroundVideo (sibr::Video &vid, PyramidLayer &out_mask, PyramidLayer &out_video, cv::Mat &mask, const sibr::ImageRGB &mean={}, int threshold=75, int numBins=50, float time_skip_begin=0, float time_skip_end=0)
static sibr::Volume1u sibr::VideoUtils::getBackgroundVolume (const sibr::Volume3u &volume, int threshold=75, int numBins=150)
static sibr::Volume1f sibr::VideoUtils::getBackgroundVolumeF (const sibr::Volume3u &volume, int numBins=150)
static void sibr::VideoUtils::computeSaveSimpleFlow (sibr::Video &vid, bool viz=false)
static cv::Mat sibr::VideoUtils::getTemporalSpatialRatio (sibr::Video &vid, PyramidLayer &out_ratio, const sibr::ImageRGB &spatial_ratio, int numBins=50, float time_skip_begin=0, float time_skip_end=0)
static cv::Mat sibr::VideoUtils::getLaplacian (cv::Mat mat, int size=3, bool smooth=false, bool absolute=false)
static cv::Mat sibr::VideoUtils::getCanny (cv::Mat mat)
static void sibr::VideoUtils::computeSaveVideoMaskF (Video &vid, int threshold, bool viz=false)
static void sibr::VideoUtils::computeSaveVideoMaskBlur (Video &vid, int time_window)
static int sibr::VideoUtils::rotationAngleFromMetadata (const std::string &videoPath)
static void sibr::VideoUtils::ECCtransform (cv::Mat matA, cv::Mat matB, cv::Mat &correctedB, cv::Mat &diff, int cvMotion)
static void sibr::VideoUtils::smallAlignmentVideo (sibr::Video &vid, const std::string &outputVidPath, bool viz=false)
static void sibr::VideoUtils::smallAlignmentVideo2 (sibr::Video &vid, const std::string &outputVidPath, bool viz=false)
static cv::Mat sibr::VideoUtils::applyFlow (const cv::Mat &prev, const cv::Mat &flow)
static void sibr::VideoUtils::simpleFlow (cv::VideoCapture &cap, float ratio, std::function< bool(cv::Mat prev, cv::Mat next, cv::Mat flow, int flow_id)> f, std::function< void(void)> end_function=[]() {})
static void sibr::VideoUtils::deepFlow (cv::VideoCapture &cap, float ratio, std::function< bool(cv::Mat prev, cv::Mat next, cv::Mat flow, int flow_id)> f, std::function< void(void)> end_function=[]() {})
Variables
static const uint sibr::VideoVolume< T, N >::cv_type = getOpenCVtype<T, N>
int sibr::VideoVolume< T, N >::w = 0
int sibr::VideoVolume< T, N >::h = 0
int sibr::VideoVolume< T, N >::l = 0
cv::Mat_< T > sibr::VideoVolume< T, N >::mat
cv::Mat sibr::PyramidLayer::volume
int sibr::PyramidLayer::w
int sibr::PyramidLayer::h
int sibr::PyramidLayer::l
int sibr::PyramidParameters::num_levels
int sibr::PyramidParameters::temporal_radius
int sibr::PyramidParameters::spatial_radius
bool sibr::PyramidParameters::splacialDS = true
PyramidParameters sibr::VideoGaussianPyramid::params
std::vector< PyramidLayer > sibr::VideoGaussianPyramid::layers
PyramidParameters sibr::VideoLaplacianPyramid::params
std::vector< PyramidLayer > sibr::VideoLaplacianPyramid::layers
PyramidLayer sibr::ContribData::contrib
PyramidLayer sibr::ContribData::mask
PyramidLayer sibr::ContribData::partA
PyramidLayer sibr::ContribData::partB
ContribData sibr::FullContribData::scaled
ContribData sibr::FullContribData::notScaled
PyramidLayer sibr::FullContribData::result
PyramidLayer sibr::FullContribData::inputA
PyramidLayer sibr::FullContribData::inputB
std::map< Indice, uint > sibr::Histogram< T, N >::bins
Range sibr::Histogram< T, N >::max
Range sibr::Histogram< T, N >::min
Range sibr::Histogram< T, N >::scaling
Range sibr::Histogram< T, N >::bin_range
uint sibr::Histogram< T, N >::numBins = 50
std::vector< uint > sibr::Histogram< T, 1 >::bins
double sibr::Histogram< T, 1 >::max
double sibr::Histogram< T, 1 >::min
double sibr::Histogram< T, 1 >::scaling
double sibr::Histogram< T, 1 >::bin_range
uint sibr::Histogram< T, 1 >::numBins = 50
std::map< sibr::Vector3ub, int > sibr::TimeHistogram::bins
std::map< sibr::Vector3ub, float > sibr::TimeHistogram::sorted_bins
double sibr::TimeHistogram::max
double sibr::TimeHistogram::min
double sibr::TimeHistogram::scaling
double sibr::TimeHistogram::bin_range
int sibr::TimeHistogram::numBins = 50
static int sibr::VideoUtils::codec_ffdshow = cv::VideoWriter::fourcc('F', 'F', 'D', 'S')
static int sibr::VideoUtils::codec_OpenH264 = cv::VideoWriter::fourcc('H', '2', '6', '4')
static int sibr::VideoUtils::codec_OpenH264_fallback = 0x31637661
Detailed Description
Video loading, processing and display.
Typedef Documentation
ColorHistogram
using sibr::ColorHistogram = typedef Histogram<uchar, 3>
Definition at line 961 of file VideoUtils.hpp.
CVpixel
template<typename T , uint N> using sibr::VideoVolume< T, N >::CVpixel = std::conditional_t<N == 1, T, cv::Vec<T, N> >
Definition at line 63 of file VideoUtils.hpp.
Histo1f
using sibr::Histo1f = typedef Histogram<float, 1>
Definition at line 960 of file VideoUtils.hpp.
Indice
template<typename T , uint N> using sibr::Histogram< T, N >::Indice = Vector<uint, N> private
Definition at line 841 of file VideoUtils.hpp.
Range
template<typename T , uint N> using sibr::Histogram< T, N >::Range = Vector<double, N> private
Definition at line 842 of file VideoUtils.hpp.
Value
template<typename T , uint N> using sibr::Histogram< T, N >::Value = Vector<T, N> private
Definition at line 840 of file VideoUtils.hpp.
Function Documentation
add()
template<typename T , uint N> template<typename T > void sibr::VideoVolume< T, N >::add (const VideoVolume< T, N > & other) inline
Definition at line 121 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::cv_type, and sibr::VideoVolume< T, N >::mat.
Referenced by sibr::collapseLaplacianPyramid(), and sibr::collapseLaplacianPyramidTemporal().
addValue() [1/3]
void sibr::TimeHistogram::addValue (const sibr::Vector3ub & value) inline
Definition at line 997 of file VideoUtils.hpp.
References sibr::TimeHistogram::bins, and sibr::TimeHistogram::whatBin().
Referenced by sibr::TimeHistogram::addValues().
addValue() [2/3]
template<typename T , uint N> void sibr::Histogram< T, N >::addValue (const Value & value) inline
Definition at line 860 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::bins, and sibr::Histogram< T, N >::whatBin().
Referenced by sibr::Histogram< T, 1 >::addValues(), and sibr::Histogram< T, N >::addValues().
addValue() [3/3]
template<typename T > void sibr::Histogram< T, 1 >::addValue (T value) inline
Definition at line 914 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::bins, and sibr::Histogram< T, N >::whatBin().
addValues() [1/3]
void sibr::TimeHistogram::addValues (const std::vector< sibr::Vector3ub > & values) inline
Definition at line 971 of file VideoUtils.hpp.
References sibr::TimeHistogram::addValue().
Referenced by sibr::VideoUtils::getBackgroundImage(), sibr::VideoUtils::getBackGroundVideo(), sibr::VideoUtils::getBackgroundVolume(), sibr::VideoUtils::getBackgroundVolumeF(), and sibr::VideoUtils::getTemporalSpatialRatio().
addValues() [2/3]
template<typename T > void sibr::Histogram< T, 1 >::addValues (const std::vector< T > & values) inline
Definition at line 921 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::addValue(), and sibr::Key::T.
addValues() [3/3]
template<typename T , uint N> void sibr::Histogram< T, N >::addValues (const std::vector< Value > & values) inline
Definition at line 863 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::addValue().
applyFlow()
cv::Mat sibr::VideoUtils::applyFlow (const cv::Mat & prev, const cv::Mat & flow) static protected
Definition at line 1009 of file VideoUtils.cpp.
Referenced by sibr::VideoUtils::deepFlowViz(), and sibr::VideoUtils::simpleFlowViz().
applyMask()
template<typename T , uint N> template<uint M> VideoVolume sibr::VideoVolume< T, N >::applyMask (const VideoVolume< uchar, M > & mask) inline
Definition at line 173 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::VideoVolume(), and sibr::VideoVolume< T, N >::w.
applyMaskBinary()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::applyMaskBinary (const Volume1u & mask) inline
Definition at line 153 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::VideoVolume(), and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoUtils::computeSaveVideoMaskF().
applyMaskInPlace()
template<typename T , uint N> template<typename T , uint M> void sibr::VideoVolume< T, N >::applyMaskInPlace (const VideoVolume< T, M > & mask) inline
Definition at line 182 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), and sibr::VideoVolume< T, N >::l.
assignValue() [1/2]
template<typename T , uint N> static void sibr::CV_Assign< T, N >::assignValue (uint c, const T & val, cv::Vec< T, N > & vec) inline static
Definition at line 14 of file VideoUtils.hpp.
Referenced by sibr::VideoVolume< T, N >::median_frame(), and sibr::totalVariation().
assignValue() [2/2]
template<typename T > static void sibr::CV_Assign< T, 1 >::assignValue (uint c, const T & val, T & vec) inline static
Definition at line 20 of file VideoUtils.hpp.
blur()
SIBR_VIDEO_EXPORT PyramidLayer sibr::blur (const PyramidLayer & layer, const PyramidParameters & params)
Definition at line 1377 of file VideoUtils.cpp.
References sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::PyramidParameters::spatial_radius, sibr::PyramidParameters::splacialDS, sibr::temporalBlur(), sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
buildVideoGaussianPyramid() [1/2]
SIBR_VIDEO_EXPORT VideoGaussianPyramid sibr::buildVideoGaussianPyramid (const cv::Mat & volume, int w, int h, int nLevels, const PyramidParameters & params, bool show)
Definition at line 1591 of file VideoUtils.cpp.
References sibr::downscale(), sibr::VideoGaussianPyramid::layers, sibr::VideoGaussianPyramid::params, sibr::show(), and sibr::PyramidLayer::show().
Referenced by sibr::buildVideoGaussianPyramid(), sibr::videoLaplacianBlending(), sibr::videoLaplacianBlendingContrib(), and sibr::videoLaplacianBlendingDebug().
buildVideoGaussianPyramid() [2/2]
SIBR_VIDEO_EXPORT VideoGaussianPyramid sibr::buildVideoGaussianPyramid (sibr::Video & vid, int nLevels, const PyramidParameters & params, bool show)
Definition at line 1610 of file VideoUtils.cpp.
References sibr::buildVideoGaussianPyramid(), sibr::Video::getResolution(), sibr::Video::getVolume(), and sibr::show().
buildVideoLaplacianPyramid() [1/2]
SIBR_VIDEO_EXPORT VideoLaplacianPyramid sibr::buildVideoLaplacianPyramid (PyramidLayer vid, int nLevels, const PyramidParameters & params, bool show)
Definition at line 1615 of file VideoUtils.cpp.
References sibr::downscale(), sibr::VideoLaplacianPyramid::layers, sibr::VideoLaplacianPyramid::params, sibr::show(), sibr::PyramidLayer::show(), sibr::upscale(), and sibr::PyramidLayer::volume.
Referenced by sibr::buildVideoLaplacianPyramid(), sibr::buildVideoLaplacianPyramidFullyReduced(), sibr::videoLaplacianBlending(), sibr::videoLaplacianBlendingContrib(), and sibr::videoLaplacianBlendingDebug().
buildVideoLaplacianPyramid() [2/2]
SIBR_VIDEO_EXPORT VideoLaplacianPyramid sibr::buildVideoLaplacianPyramid (sibr::Video & vid, int nLevels, const PyramidParameters & params, bool show)
Definition at line 1638 of file VideoUtils.cpp.
References sibr::buildVideoLaplacianPyramid(), sibr::Video::getResolution(), sibr::Video::getVolume(), and sibr::show().
buildVideoLaplacianPyramidFullyReduced()
SIBR_VIDEO_EXPORT VideoLaplacianPyramid sibr::buildVideoLaplacianPyramidFullyReduced (PyramidLayer vid, int nLevels, const PyramidParameters & params, bool show)
Definition at line 1643 of file VideoUtils.cpp.
References sibr::buildVideoLaplacianPyramid(), sibr::PyramidLayer::cout(), sibr::VideoLaplacianPyramid::layers, sibr::VideoLaplacianPyramid::params, sibr::show(), and sibr::upscale().
clone() [1/2]
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::clone (void) const inline
Definition at line 98 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::mat, sibr::VideoVolume< T, N >::VideoVolume(), and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoVolume< T, N >::pyrDownBoundaryConditions(), and sibr::VideoVolume< T, N >::time_sequence_volume().
clone() [2/2]
PyramidLayer sibr::PyramidLayer::clone (void) const inline
Definition at line 737 of file VideoUtils.hpp.
References sibr::PyramidLayer::volume.
collapse()
PyramidLayer sibr::VideoLaplacianPyramid::collapse () const
Definition at line 1581 of file VideoUtils.cpp.
References sibr::VideoLaplacianPyramid::layers, sibr::VideoLaplacianPyramid::params, and sibr::upscale().
Referenced by sibr::videoLaplacianBlending(), sibr::videoLaplacianBlendingContrib(), and sibr::videoLaplacianBlendingDebug().
collapseLaplacianPyramid()
SIBR_VIDEO_EXPORT sibr::Volume3u sibr::collapseLaplacianPyramid (const std::vector< sibr::Volume3u > & pyr, double shift)
Definition at line 127 of file VideoUtils.cpp.
References sibr::VideoVolume< T, N >::add(), sibr::VideoVolume< T, N >::convertTo(), sibr::VideoVolume< T, N >::pyrUp(), and sibr::VideoVolume< T, N >::shift().
Referenced by sibr::laplacianBlending().
collapseLaplacianPyramidTemporal()
template<typename T > sibr::VideoVolume<T,3> sibr::collapseLaplacianPyramidTemporal (const std::vector< sibr::VideoVolume< T, 3 >> & pyr, double shift, bool debug = false)
Definition at line 641 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::add(), sibr::VideoVolume< T, N >::convertTo(), sibr::VideoVolume< T, N >::play(), sibr::VideoVolume< T, N >::pyrUpTemporal(), sibr::VideoVolume< T, N >::shift(), and sibr::Key::T.
Referenced by sibr::laplacianBlendingTemporal().
colorMapped()
template<typename T , uint N> VideoVolume<uchar, 3> sibr::VideoVolume< T, N >::colorMapped (int colormap, double scaling = 1.0) inline
Definition at line 197 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, and sibr::VideoVolume< T, N >::w.
computeSaveSimpleFlow()
void sibr::VideoUtils::computeSaveSimpleFlow (sibr::Video & vid, bool viz = false) static
Definition at line 554 of file VideoUtils.cpp.
References sibr::VideoVolume< T, N >::frame(), sibr::Video::getFilepath(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, ibr_convert_old_to_new::line, sibr::loadVideoVolume(), sibr::makeDirectory(), sibr::show(), and sibr::VideoVolume< T, N >::w.
computeSaveVideoMaskBlur()
void sibr::VideoUtils::computeSaveVideoMaskBlur (Video & vid, int time_window) static
Definition at line 645 of file VideoUtils.cpp.
References sibr::Video::getFilepath(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::loadVideoVolume(), sibr::makeDirectory(), sibr::VideoVolume< T, N >::mat, sibr::VideoVolume< T, N >::pixelAt(), sibr::VideoVolume< T, N >::saveToVideoFile(), sibr::VideoVolume< T, N >::valueAt(), and sibr::VideoVolume< T, N >::w.
computeSaveVideoMaskF()
void sibr::VideoUtils::computeSaveVideoMaskF (Video & vid, int threshold, bool viz = false) static
Definition at line 603 of file VideoUtils.cpp.
References sibr::VideoVolume< T, N >::applyMaskBinary(), sibr::VideoVolume< T, N >::frame(), sibr::VideoUtils::getBackgroundVolumeF(), sibr::Video::getFilepath(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::loadVideoVolume(), sibr::makeDirectory(), sibr::VideoVolume< T, N >::play(), sibr::VideoVolume< T, N >::saveToVideoFile(), and sibr::VideoVolume< T, N >::w.
computeSortedBins()
void sibr::TimeHistogram::computeSortedBins () inline
Definition at line 1009 of file VideoUtils.hpp.
References sibr::TimeHistogram::bins, and sibr::TimeHistogram::sorted_bins.
concat()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::concat (const VideoVolume< T, N > & other) const inline
Definition at line 137 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, and sibr::VideoVolume< T, N >::w.
concatH()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::concatH (const VideoVolume< T, N > & other) const inline
Definition at line 144 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, and sibr::VideoVolume< T, N >::w.
concatVolumesChannels()
template<typename T , uint N, uint M> VideoVolume<T, N + M> sibr::concatVolumesChannels (const sibr::VideoVolume< T, N > & A, const sibr::VideoVolume< T, M > & B)
Definition at line 538 of file VideoUtils.hpp.
References sibr::Key::A, sibr::Key::B, sibr::VideoVolume< T, N >::frame(), and sibr::split().
convertReducedVideoPyramidTo128()
SIBR_VIDEO_EXPORT void sibr::convertReducedVideoPyramidTo128 (VideoLaplacianPyramid & vid)
Definition at line 1666 of file VideoUtils.cpp.
References sibr::VideoLaplacianPyramid::layers.
convertTo()
template<typename T , uint N> template<typename U , uint M = N> VideoVolume<U, M> sibr::VideoVolume< T, N >::convertTo () const inline
Definition at line 102 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, and sibr::VideoVolume< T, N >::w.
Referenced by sibr::collapseLaplacianPyramid(), sibr::collapseLaplacianPyramidTemporal(), sibr::laplacianPyramid(), sibr::laplacianPyramidTemporal(), and sibr::laplacianPyramidTemporalDouble().
copySizeFrom()
void sibr::PyramidLayer::copySizeFrom (const PyramidLayer & other) inline
Definition at line 747 of file VideoUtils.hpp.
References sibr::PyramidLayer::h, sibr::PyramidLayer::l, and sibr::PyramidLayer::w.
cout() [1/2]
template<typename T , uint N> void sibr::VideoVolume< T, N >::cout () const inline
Definition at line 517 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, and sibr::VideoVolume< T, N >::w.
cout() [2/2]
void sibr::PyramidLayer::cout () const inline
Definition at line 753 of file VideoUtils.hpp.
Referenced by sibr::buildVideoLaplacianPyramidFullyReduced().
cropFromSize()
cv::Mat sibr::VideoUtils::cropFromSize (const cv::Mat & mat, const sibr::Vector2i & size) static
Definition at line 189 of file VideoUtils.cpp.
cutFrames()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::cutFrames (int numBefore, int numAfter) inline
Definition at line 188 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, sibr::Key::N, and sibr::VideoVolume< T, N >::w.
decimate()
SIBR_VIDEO_EXPORT PyramidLayer sibr::decimate (const PyramidLayer & layer, const PyramidParameters & params)
Definition at line 1449 of file VideoUtils.cpp.
References sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
deepFlow()
void sibr::VideoUtils::deepFlow (cv::VideoCapture & cap, float ratio, std::function< bool(cv::Mat prev, cv::Mat next, cv::Mat flow, int flow_id)> f, std::function< void(void)> end_function = []() {}) static protected
Definition at line 1086 of file VideoUtils.cpp.
References sibr::VideoUtils::getGrey().
Referenced by sibr::VideoUtils::deepFlowViz().
deepFlowViz()
void sibr::VideoUtils::deepFlowViz (cv::VideoCapture & cap, float ratio) static
Definition at line 1121 of file VideoUtils.cpp.
References sibr::VideoUtils::applyFlow(), sibr::VideoUtils::deepFlow(), and sibr::VideoUtils::getFlowViz().
downscale()
SIBR_VIDEO_EXPORT PyramidLayer sibr::downscale (const PyramidLayer & layer, const PyramidParameters & params)
Definition at line 1498 of file VideoUtils.cpp.
References sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::PyramidParameters::splacialDS, sibr::temporalBlur(), sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
Referenced by sibr::buildVideoGaussianPyramid(), and sibr::buildVideoLaplacianPyramid().
duplicateTime()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::duplicateTime (int num) const inline
Definition at line 457 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, and sibr::VideoVolume< T, N >::w.
ECCtransform()
void sibr::VideoUtils::ECCtransform (cv::Mat matA, cv::Mat matB, cv::Mat & correctedB, cv::Mat & diff, int cvMotion) static
Definition at line 793 of file VideoUtils.cpp.
extendedBlurPyramid()
template<uint M> std::vector<sibr::VideoVolume<uchar, M> > sibr::extendedBlurPyramid (const sibr::VideoVolume< uchar, M > & vid, uint num_levels = 0)
Definition at line 555 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::l, and sibr::optimal_num_levels().
extendedDownScaleTemporal()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::extendedDownScaleTemporal () const inline
Definition at line 310 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::extendedTemporalBlur(), sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, and sibr::VideoVolume< T, N >::w.
extendedTemporalBlur()
template<typename T , uint N> void sibr::VideoVolume< T, N >::extendedTemporalBlur () inline
Definition at line 272 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat.
Referenced by sibr::VideoVolume< T, N >::extendedDownScaleTemporal().
frame() [1/2]
template<typename T , uint N> cv::Mat_<CVpixel> sibr::VideoVolume< T, N >::frame (int t) inline
Definition at line 409 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::mat, and sibr::Key::N.
Referenced by sibr::VideoVolume< T, N >::applyMask(), sibr::VideoVolume< T, N >::applyMaskBinary(), sibr::VideoVolume< T, N >::applyMaskInPlace(), sibr::VideoVolume< T, N >::colorMapped(), sibr::VideoUtils::computeSaveSimpleFlow(), sibr::VideoUtils::computeSaveVideoMaskF(), sibr::VideoVolume< T, N >::concatH(), sibr::concatVolumesChannels(), sibr::VideoVolume< T, N >::convertTo(), sibr::VideoVolume< T, N >::extendedDownScaleTemporal(), sibr::loadVideoVolume(), sibr::VideoVolume< T, N >::multiply(), sibr::VideoVolume< T, N >::pixelAt(), sibr::VideoVolume< T, N >::pyrDownSpacial(), sibr::VideoVolume< T, N >::pyrDownTemporalModif(), sibr::VideoVolume< T, N >::pyrUpSpacial(), sibr::VideoVolume< T, N >::saveToVideoFile(), sibr::VideoVolume< T, N >::spatialRescale(), sibr::VideoVolume< T, N >::subVolumeSpatial(), and sibr::VideoVolume< T, N >::swapRBchannels().
frame() [2/2]
template<typename T , uint N> const cv::Mat_<CVpixel> sibr::VideoVolume< T, N >::frame (int t) const inline
Definition at line 412 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::mat, and sibr::Key::N.
gaussianPyramid()
template<uint M> std::vector<sibr::VideoVolume<uchar, M> > sibr::gaussianPyramid (const sibr::VideoVolume< uchar, M > & vid, uint num_levels = 0)
Definition at line 568 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::l, and sibr::optimal_num_levels().
gaussianPyramidTemporal()
template<typename T , uint M> std::vector<sibr::VideoVolume<T, M> > sibr::gaussianPyramidTemporal (const sibr::VideoVolume< T, M > & vid, uint num_levels = 0)
Definition at line 581 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::l, and sibr::optimal_num_levels().
gaussianPyramidTemporalBox()
template<typename T , uint M> std::vector<sibr::VideoVolume<T, M> > sibr::gaussianPyramidTemporalBox (const sibr::VideoVolume< T, M > & vid, uint num_levels = 0)
Definition at line 594 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::l, and sibr::optimal_num_levels().
getBackgroundImage() [1/2]
cv::Mat sibr::VideoUtils::getBackgroundImage (const cv::Mat volume, int w, int h, int numBins = 50) static
Definition at line 373 of file VideoUtils.cpp.
References sibr::TimeHistogram::addValues(), sibr::TimeHistogram::getBinMiddle(), sibr::TimeHistogram::getHMode(), and sibr::Key::L.
getBackgroundImage() [2/2]
cv::Mat sibr::VideoUtils::getBackgroundImage (sibr::Video & vid, int numBins = 50, float time_skip_begin = 0, float time_skip_end = 0) static
Definition at line 367 of file VideoUtils.cpp.
References sibr::Video::getResolution(), and sibr::Video::getVolume().
getBackGroundVideo()
void sibr::VideoUtils::getBackGroundVideo (sibr::Video & vid, PyramidLayer & out_mask, PyramidLayer & out_video, cv::Mat & mask, const sibr::ImageRGB & mean = {}, int threshold = 75, int numBins = 50, float time_skip_begin = 0, float time_skip_end = 0) static
Definition at line 402 of file VideoUtils.cpp.
References sibr::TimeHistogram::addValues(), sibr::Image< T_Type, T_NumComp >::cast(), sibr::clamp(), sibr::TimeHistogram::getBinMiddle(), sibr::TimeHistogram::getHMode(), sibr::Video::getResolution(), sibr::Video::getVolume(), sibr::PyramidLayer::h, sibr::Key::L, sibr::PyramidLayer::l, sibr::Image< T_Type, T_NumComp >::size(), sibr::PyramidLayer::volume, sibr::PyramidLayer::w, and sibr::TimeHistogram::whatBin().
getBackgroundVolume()
sibr::Volume1u sibr::VideoUtils::getBackgroundVolume (const sibr::Volume3u & volume, int threshold = 75, int numBins = 150) static
Definition at line 489 of file VideoUtils.cpp.
References sibr::TimeHistogram::addValues(), sibr::TimeHistogram::getBinMiddle(), sibr::TimeHistogram::getHMode(), sibr::VideoVolume< T, N >::h, sibr::Key::L, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::pixelAt(), sibr::VideoVolume< T, N >::valueAt(), and sibr::VideoVolume< T, N >::w.
getBackgroundVolumeF()
sibr::Volume1f sibr::VideoUtils::getBackgroundVolumeF (const sibr::Volume3u & volume, int numBins = 150) static
Definition at line 523 of file VideoUtils.cpp.
References sibr::TimeHistogram::addValues(), sibr::TimeHistogram::getBinMiddle(), sibr::TimeHistogram::getHMode(), sibr::VideoVolume< T, N >::h, sibr::Key::L, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::pixelAt(), sibr::VideoVolume< T, N >::valueAt(), and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoUtils::computeSaveVideoMaskF().
getBinMiddle() [1/3]
template<typename T , uint N> Value sibr::Histogram< T, N >::getBinMiddle (const Indice & bin) const inline
Definition at line 881 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::bin_range, sibr::Histogram< T, N >::min, and sibr::Key::T.
getBinMiddle() [2/3]
sibr::Vector3ub sibr::TimeHistogram::getBinMiddle (const sibr::Vector3ub & bin) const inline
Definition at line 977 of file VideoUtils.hpp.
References sibr::TimeHistogram::bin_range, sibr::clamp(), and sibr::TimeHistogram::min.
Referenced by sibr::VideoUtils::getBackgroundImage(), sibr::VideoUtils::getBackGroundVideo(), sibr::VideoUtils::getBackgroundVolume(), sibr::VideoUtils::getBackgroundVolumeF(), and sibr::VideoUtils::getTemporalSpatialRatio().
getBinMiddle() [3/3]
template<typename T > T sibr::Histogram< T, 1 >::getBinMiddle (uint bin) const inline
Definition at line 938 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::bin_range, sibr::Histogram< T, N >::min, and sibr::Key::T.
getCanny()
cv::Mat sibr::VideoUtils::getCanny (cv::Mat mat) static
Definition at line 745 of file VideoUtils.cpp.
References sibr::VideoUtils::getGrey().
getFlowViz()
cv::Mat sibr::VideoUtils::getFlowViz (const cv::Mat & flow) static
Definition at line 161 of file VideoUtils.cpp.
References sibr::split(), and xy().
Referenced by sibr::VideoUtils::deepFlowViz(), sibr::VideoUtils::simpleFlowSave(), and sibr::VideoUtils::simpleFlowViz().
getGrey()
cv::Mat sibr::VideoUtils::getGrey (const cv::Mat & mat) static
Definition at line 1140 of file VideoUtils.cpp.
Referenced by sibr::VideoUtils::deepFlow(), sibr::VideoUtils::getCanny(), sibr::VideoUtils::getLaplacian(), sibr::VideoUtils::smallAlignmentVideo(), and sibr::VideoUtils::smallAlignmentVideo2().
getHMode()
sibr::Vector3ub sibr::TimeHistogram::getHMode () const inline
Definition at line 985 of file VideoUtils.hpp.
References sibr::TimeHistogram::bins.
Referenced by sibr::VideoUtils::getBackgroundImage(), sibr::VideoUtils::getBackGroundVideo(), sibr::VideoUtils::getBackgroundVolume(), sibr::VideoUtils::getBackgroundVolumeF(), and sibr::VideoUtils::getTemporalSpatialRatio().
getLaplacian()
cv::Mat sibr::VideoUtils::getLaplacian (cv::Mat mat, int size = 3, bool smooth = false, bool absolute = false) static
Definition at line 730 of file VideoUtils.cpp.
References sibr::VideoUtils::getGrey().
getMeanVariance()
void sibr::VideoUtils::getMeanVariance (cv::VideoCapture & cap, cv::Mat & outMean, cv::Mat & outVariance, const sibr::Vector2i & finalSize) static
Definition at line 205 of file VideoUtils.cpp.
References sibr::sum(), and sibr::var().
getMeanVariance2()
void sibr::VideoUtils::getMeanVariance2 (cv::VideoCapture & cap, cv::Mat & outMean, cv::Mat & outVariance, const sibr::Vector2i & finalSize, float starting_point_s = 0) static
Definition at line 250 of file VideoUtils.cpp.
References sibr::sum(), and sibr::var().
getMedian() [1/2]
cv::Mat3b sibr::VideoUtils::getMedian (const std::string & path, float time_percentage_crop = 0) static
Definition at line 340 of file VideoUtils.cpp.
References sibr::Video::getResolutionCV(), sibr::VideoVolume< T, N >::l, ibr_convert_old_to_new::line, sibr::loadVideoVolume(), and sibr::VideoVolume< T, N >::video_line().
getMedian() [2/2]
cv::Mat sibr::VideoUtils::getMedian (sibr::Video & vid, float time_skiped_begin = 0, float time_skiped_end = 0) static
Definition at line 298 of file VideoUtils.cpp.
References sibr::Video::getResolutionCV(), sibr::Video::getVolume(), and sibr::Key::L.
getModeIndice() [1/2]
template<typename T , uint N> Indice sibr::Histogram< T, N >::getModeIndice () const inline
Definition at line 869 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::bins.
getModeIndice() [2/2]
template<typename T > uint sibr::Histogram< T, 1 >::getModeIndice () const inline
Definition at line 927 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::bins.
getRGB()
cv::Mat sibr::PyramidLayer::getRGB (int frame, bool centered = false)
Definition at line 1183 of file VideoUtils.cpp.
References sibr::PyramidLayer::h, and sibr::PyramidLayer::volume.
getTemporalSpatialRatio()
cv::Mat sibr::VideoUtils::getTemporalSpatialRatio (sibr::Video & vid, PyramidLayer & out_ratio, const sibr::ImageRGB & spatial_ratio, int numBins = 50, float time_skip_begin = 0, float time_skip_end = 0) static
Definition at line 675 of file VideoUtils.cpp.
References sibr::TimeHistogram::addValues(), sibr::Image< T_Type, T_NumComp >::cast(), sibr::TimeHistogram::getBinMiddle(), sibr::TimeHistogram::getHMode(), sibr::Video::getResolution(), sibr::Video::getVolume(), sibr::PyramidLayer::h, sibr::Key::L, sibr::PyramidLayer::l, sibr::PyramidLayer::volume, sibr::PyramidLayer::w, and sibr::TimeHistogram::whatBin().
Histogram() [1/2]
template<typename T , uint N> sibr::Histogram< T, N >::Histogram (const Value & _min, const Value & _max, uint _numBins = 100) inline
Definition at line 845 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::bin_range, sibr::Histogram< T, N >::max, sibr::Histogram< T, N >::min, sibr::Histogram< T, N >::numBins, and sibr::Histogram< T, N >::scaling.
Histogram() [2/2]
template<typename T > sibr::Histogram< T, 1 >::Histogram (double _min, double _max, int _numBins = 100) inline
Definition at line 900 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::bin_range, sibr::Histogram< T, N >::max, sibr::Histogram< T, N >::min, sibr::Histogram< T, N >::numBins, and sibr::Histogram< T, N >::scaling.
isValid()
template<typename T , uint N> bool sibr::VideoVolume< T, N >::isValid () const inline
Definition at line 513 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat.
laplacianBlending()
SIBR_VIDEO_EXPORT sibr::Volume3u sibr::laplacianBlending (const sibr::Volume3u & vA, const sibr::Volume3u & vB, std::vector< sibr::Volume1u > & pyrM)
Definition at line 140 of file VideoUtils.cpp.
References sibr::collapseLaplacianPyramid(), and sibr::laplacianPyramid().
laplacianBlendingTemporal()
template<typename T_V , typename T_M > sibr::VideoVolume<T_V, 3> sibr::laplacianBlendingTemporal (const sibr::VideoVolume< T_V, 3 > & vA, const sibr::VideoVolume< T_V, 3 > & vB, std::vector< sibr::VideoVolume< T_M, 1 >> & pyrM)
Definition at line 670 of file VideoUtils.hpp.
References sibr::collapseLaplacianPyramidTemporal(), and sibr::laplacianPyramidTemporal().
laplacianPyramid()
SIBR_VIDEO_EXPORT std::vector< sibr::Volume3u > sibr::laplacianPyramid (const sibr::Volume3u & vid, uint num_levels)
Definition at line 75 of file VideoUtils.cpp.
References sibr::VideoVolume< T, N >::convertTo(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::optimal_num_levels(), sibr::VideoVolume< T, N >::pyrDown(), sibr::VideoVolume< T, N >::pyrUp(), sibr::VideoVolume< T, N >::shift(), sibr::VideoVolume< T, N >::substract(), and sibr::VideoVolume< T, N >::w.
Referenced by sibr::laplacianBlending().
laplacianPyramidTemporal()
template<typename U , typename T = U> std::vector<VideoVolume<T,3> > sibr::laplacianPyramidTemporal (const VideoVolume< U, 3 > & vid, uint num_levels = 0)
Definition at line 612 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::convertTo(), sibr::VideoVolume< T, N >::l, sibr::optimal_num_levels(), sibr::VideoVolume< T, N >::pyrDownTemporal(), sibr::VideoVolume< T, N >::pyrUpTemporal(), sibr::VideoVolume< T, N >::shift(), sibr::VideoVolume< T, N >::substract(), and sibr::Key::T.
Referenced by sibr::laplacianBlendingTemporal().
laplacianPyramidTemporalDouble()
SIBR_VIDEO_EXPORT std::vector< sibr::Volume3u > sibr::laplacianPyramidTemporalDouble (const sibr::Volume3u & vid, uint num_levels)
Definition at line 98 of file VideoUtils.cpp.
References sibr::VideoVolume< T, N >::convertTo(), sibr::VideoVolume< T, N >::l, sibr::length(), sibr::VideoVolume< T, N >::pyrDownTemporal(), sibr::VideoVolume< T, N >::pyrUpTemporal(), sibr::VideoVolume< T, N >::shift(), and sibr::VideoVolume< T, N >::substract().
loadVideoVolume() [1/2]
SIBR_VIDEO_EXPORT Volume3u sibr::loadVideoVolume (const std::string & filepath)
Definition at line 17 of file VideoUtils.cpp.
References sibr::Video::exists(), and SIBR_WRG.
Referenced by sibr::VideoUtils::computeSaveSimpleFlow(), sibr::VideoUtils::computeSaveVideoMaskBlur(), sibr::VideoUtils::computeSaveVideoMaskF(), and sibr::VideoUtils::getMedian().
loadVideoVolume() [2/2]
SIBR_VIDEO_EXPORT Volume3u sibr::loadVideoVolume (sibr::Video & video)
Definition at line 27 of file VideoUtils.cpp.
References sibr::VideoVolume< T, N >::frame(), sibr::Video::getCurrentFrameNumber(), sibr::Video::getCVvideo(), sibr::Video::getNumFrames(), sibr::Video::getResolution(), and sibr::Video::setCurrentFrame().
loopAndDisplay()
template<typename FunType , typename... OtherArgsTypes> static void sibr::VideoUtils::loopAndDisplay (cv::VideoCapture & cap, float ratio, FunType f, const OtherArgsTypes &... args) static
median_frame()
template<typename T , uint N> cv::Mat_<CVpixel> sibr::VideoVolume< T, N >::median_frame () const inline
Definition at line 482 of file VideoUtils.hpp.
References sibr::CV_Assign< T, N >::assignValue(), sibr::VideoVolume< T, N >::h, sibr::Key::N, sibr::VideoVolume< T, N >::time_sequence(), and sibr::VideoVolume< T, N >::w.
multiply()
template<typename T , uint N> template<typename U , uint M> void sibr::VideoVolume< T, N >::multiply (const VideoVolume< U, M > & other) inline
Definition at line 131 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), and sibr::VideoVolume< T, N >::l.
normalized_values()
template<typename T > std::vector<float> sibr::Histogram< T, 1 >::normalized_values () const inline
Definition at line 942 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::bins, sibr::Histogram< T, N >::numBins, and sibr::sum().
operator+()
PyramidLayer sibr::PyramidLayer::operator+ (const PyramidLayer & other)
Definition at line 1353 of file VideoUtils.cpp.
References sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
operator-()
PyramidLayer sibr::PyramidLayer::operator- (const PyramidLayer & other)
Definition at line 1365 of file VideoUtils.cpp.
References sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
optimal_num_levels()
SIBR_VIDEO_EXPORT uint sibr::optimal_num_levels (uint length)
Definition at line 39 of file VideoUtils.cpp.
References sibr::length().
Referenced by sibr::extendedBlurPyramid(), sibr::gaussianPyramid(), sibr::gaussianPyramidTemporal(), sibr::gaussianPyramidTemporalBox(), sibr::laplacianPyramid(), and sibr::laplacianPyramidTemporal().
pixelAt() [1/2]
template<typename T , uint N> CVpixel& sibr::VideoVolume< T, N >::pixelAt (int t, int i, int j) inline
Definition at line 506 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame().
Referenced by sibr::VideoUtils::computeSaveVideoMaskBlur(), sibr::VideoUtils::getBackgroundVolume(), and sibr::VideoUtils::getBackgroundVolumeF().
pixelAt() [2/2]
template<typename T , uint N> const CVpixel& sibr::VideoVolume< T, N >::pixelAt (int t, int i, int j) const inline
Definition at line 509 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame().
play()
template<typename T , uint N> void sibr::VideoVolume< T, N >::play (int delay = 30, const sibr::Vector2i & res = { -1,-1 }, double scale = 1.0) const inline
Definition at line 363 of file VideoUtils.hpp.
Referenced by sibr::collapseLaplacianPyramidTemporal(), sibr::VideoUtils::computeSaveVideoMaskF(), and sibr::VideoVolume< T, N >::playStd().
playStd()
template<typename T , uint N> void sibr::VideoVolume< T, N >::playStd (double scale = 1.0) const inline
Definition at line 394 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::play(), and sibr::VideoVolume< T, N >::scale().
PyramidLayer() [1/3]
sibr::PyramidLayer::PyramidLayer () inline
Definition at line 726 of file VideoUtils.hpp.
PyramidLayer() [2/3]
sibr::PyramidLayer::PyramidLayer (const cv::Mat & _volume, int _w, int _h) inline
Definition at line 730 of file VideoUtils.hpp.
PyramidLayer() [3/3]
sibr::PyramidLayer::PyramidLayer (int _w, int _h, int _l, int cv_type = CV_32FC1) inline
Definition at line 727 of file VideoUtils.hpp.
PyramidParameters()
sibr::PyramidParameters::PyramidParameters (int nlevels = 5, int temporal = 3, int spatial = 2, bool spatial_ds = true) inline
Definition at line 769 of file VideoUtils.hpp.
pyrDown()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrDown () const inline
Definition at line 320 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::pyrDownSpacial(), and sibr::VideoVolume< T, N >::pyrDownTemporalModif().
Referenced by sibr::laplacianPyramid().
pyrDownBoundaryConditions()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrDownBoundaryConditions (double left, double right) const inline
Definition at line 351 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::clone(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, sibr::VideoVolume< T, N >::temporalBlurBoundaryConditions(), and sibr::VideoVolume< T, N >::w.
pyrDownSpacial()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrDownSpacial () const inline
Definition at line 278 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoVolume< T, N >::pyrDown().
pyrDownTemporal()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrDownTemporal () const inline
Definition at line 295 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::mat, sibr::VideoVolume< T, N >::pyrDownTemporalModif(), and sibr::VideoVolume< T, N >::w.
Referenced by sibr::laplacianPyramidTemporal(), and sibr::laplacianPyramidTemporalDouble().
pyrDownTemporalBox()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrDownTemporalBox () const inline
Definition at line 300 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, and sibr::VideoVolume< T, N >::w.
pyrDownTemporalModif()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrDownTemporalModif () inline
Definition at line 286 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::temporalBlur(), and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoVolume< T, N >::pyrDown(), and sibr::VideoVolume< T, N >::pyrDownTemporal().
pyrUp()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrUp (int _l, int _w, int _h) const inline
Definition at line 359 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::pyrUpSpacial(), and sibr::VideoVolume< T, N >::pyrUpTemporal().
Referenced by sibr::collapseLaplacianPyramid(), and sibr::laplacianPyramid().
pyrUpSpacial()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrUpSpacial (int _w, int _h) const inline
Definition at line 324 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), and sibr::VideoVolume< T, N >::l.
Referenced by sibr::VideoVolume< T, N >::pyrUp().
pyrUpTemporal()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrUpTemporal (int _l) const inline
Definition at line 332 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::mat, sibr::VideoVolume< T, N >::temporalBlur(), and sibr::VideoVolume< T, N >::w.
Referenced by sibr::collapseLaplacianPyramidTemporal(), sibr::laplacianPyramidTemporal(), sibr::laplacianPyramidTemporalDouble(), and sibr::VideoVolume< T, N >::pyrUp().
pyrUpTemporalBoundaryConditions()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::pyrUpTemporalBoundaryConditions (int _l, double left, double right) const inline
Definition at line 343 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::mat, sibr::VideoVolume< T, N >::temporalBlurBoundaryConditions(), and sibr::VideoVolume< T, N >::w.
rotationAngleFromMetadata()
int sibr::VideoUtils::rotationAngleFromMetadata (const std::string & videoPath) static
Definition at line 753 of file VideoUtils.cpp.
References ibr_convert_old_to_new::line, and SIBR_WRG.
saveToVideoFile() [1/2]
void sibr::PyramidLayer::saveToVideoFile (const std::string & filename, double framerate)
Definition at line 1195 of file VideoUtils.cpp.
References sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
saveToVideoFile() [2/2]
template<typename T , uint N> void sibr::VideoVolume< T, N >::saveToVideoFile (const std::string & filepath, double framerate = 30.0) const inline
Definition at line 398 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::makeDirectory(), and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoUtils::computeSaveVideoMaskBlur(), and sibr::VideoUtils::computeSaveVideoMaskF().
scale()
template<typename T , uint N> void sibr::VideoVolume< T, N >::scale (double d) inline
Definition at line 117 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat.
Referenced by sibr::VideoVolume< T, N >::playStd().
setupFrom()
template<typename T , uint N> template<typename U , uint M> void sibr::VideoVolume< T, N >::setupFrom (const VideoVolume< U, M > & other) inline
Definition at line 94 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::VideoVolume(), and sibr::VideoVolume< T, N >::w.
shift()
template<typename T , uint N> void sibr::VideoVolume< T, N >::shift (double d) inline
Definition at line 114 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat.
Referenced by sibr::collapseLaplacianPyramid(), sibr::collapseLaplacianPyramidTemporal(), sibr::laplacianPyramid(), sibr::laplacianPyramidTemporal(), and sibr::laplacianPyramidTemporalDouble().
show() [1/4]
void sibr::PyramidLayer::show (int s = 50) const
Definition at line 1147 of file VideoUtils.cpp.
References sibr::Key::A, sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::slice(), sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
Referenced by sibr::buildVideoGaussianPyramid(), and sibr::buildVideoLaplacianPyramid().
show() [2/4]
void sibr::PyramidLayer::show (PyramidLayer A, PyramidLayer B, int s = 50) static
Definition at line 1207 of file VideoUtils.cpp.
References sibr::Key::A, and sibr::Key::B.
show() [3/4]
void sibr::PyramidLayer::show (PyramidLayer A, PyramidLayer B, PyramidLayer C, int s = 50) static
Definition at line 1226 of file VideoUtils.cpp.
References sibr::Key::A, sibr::Key::B, sibr::Key::C, and sibr::slice().
show() [4/4]
void sibr::PyramidLayer::show (PyramidLayer A, PyramidLayer B, PyramidLayer C, PyramidLayer D, int s = 50, bool centered = false) static
Definition at line 1272 of file VideoUtils.cpp.
References sibr::Key::A, sibr::Key::B, sibr::Key::C, sibr::Key::D, and sibr::slice().
showDiff()
void sibr::PyramidLayer::showDiff (PyramidLayer A, PyramidLayer B, int s = 50) static
Definition at line 1323 of file VideoUtils.cpp.
References sibr::Key::A, and sibr::Key::B.
SIBR_CLASS_PTR()
template<typename T > sibr::Histogram< T, 1 >::SIBR_CLASS_PTR (Histogram< T, 1 >) private
simpleFlow()
void sibr::VideoUtils::simpleFlow (cv::VideoCapture & cap, float ratio, std::function< bool(cv::Mat prev, cv::Mat next, cv::Mat flow, int flow_id)> f, std::function< void(void)> end_function = []() {}) static protected
Definition at line 1020 of file VideoUtils.cpp.
Referenced by sibr::VideoUtils::simpleFlowSave(), and sibr::VideoUtils::simpleFlowViz().
simpleFlowSave()
void sibr::VideoUtils::simpleFlowSave (cv::VideoCapture & cap, float ratio, std::function< std::string(int flow_id)> naming_f) static
Definition at line 1074 of file VideoUtils.cpp.
References sibr::VideoUtils::getFlowViz(), and sibr::VideoUtils::simpleFlow().
simpleFlowViz()
void sibr::VideoUtils::simpleFlowViz (cv::VideoCapture & cap, float ratio) static
Definition at line 1052 of file VideoUtils.cpp.
References sibr::VideoUtils::applyFlow(), sibr::VideoUtils::getFlowViz(), and sibr::VideoUtils::simpleFlow().
slice()
SIBR_VIDEO_EXPORT cv::Mat sibr::slice (const PyramidLayer & layer, int i, int j, bool vertical, bool center)
Definition at line 1561 of file VideoUtils.cpp.
References sibr::clamp(), sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
Referenced by sibr::show(), and sibr::PyramidLayer::show().
smallAlignmentVideo()
void sibr::VideoUtils::smallAlignmentVideo (sibr::Video & vid, const std::string & outputVidPath, bool viz = false) static
Definition at line 812 of file VideoUtils.cpp.
References sibr::FFVideoEncoder::close(), sibr::Video::getFrameRate(), sibr::VideoUtils::getGrey(), sibr::Video::getResolution(), sibr::FFVideoEncoder::isFine(), sibr::Video::next(), sibr::Video::setCurrentFrame(), and SIBR_WRG.
smallAlignmentVideo2()
void sibr::VideoUtils::smallAlignmentVideo2 (sibr::Video & vid, const std::string & outputVidPath, bool viz = false) static
Definition at line 906 of file VideoUtils.cpp.
References sibr::FFVideoEncoder::close(), sibr::Video::getFrameRate(), sibr::VideoUtils::getGrey(), sibr::Video::getResolution(), sibr::FFVideoEncoder::isFine(), sibr::Video::next(), sibr::Video::setCurrentFrame(), and SIBR_WRG.
spatialRescale()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::spatialRescale (float f) const inline
Definition at line 521 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, and sibr::VideoVolume< T, N >::w.
spatialSlice()
template<typename T , uint N> cv::Mat_<CVpixel> sibr::VideoVolume< T, N >::spatialSlice (int i_start, int j_start, int i_end, int j_end) inline
Definition at line 465 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::l, and sibr::VideoVolume< T, N >::time_sequence_pixels().
substract()
template<typename T , uint N> template<typename U > void sibr::VideoVolume< T, N >::substract (const VideoVolume< U, N > & other) inline
Definition at line 126 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::cv_type, and sibr::VideoVolume< T, N >::mat.
Referenced by sibr::laplacianPyramid(), sibr::laplacianPyramidTemporal(), and sibr::laplacianPyramidTemporalDouble().
subVolume()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::subVolume (int t_start, int t_end) const inline
Definition at line 435 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::mat, sibr::VideoVolume< T, N >::VideoVolume(), and sibr::VideoVolume< T, N >::w.
subVolume_i()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::subVolume_i (int i_start, int i_end) const inline
Definition at line 449 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat, sibr::Key::N, sibr::VideoVolume< T, N >::VideoVolume(), and sibr::VideoVolume< T, N >::w.
subVolume_i_copy()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::subVolume_i_copy (int i_start, int i_end) const inline
Definition at line 453 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat, sibr::Key::N, sibr::VideoVolume< T, N >::VideoVolume(), and sibr::VideoVolume< T, N >::w.
subVolumeRef()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::subVolumeRef (int t_start, int t_end) inline
Definition at line 431 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::mat, sibr::VideoVolume< T, N >::VideoVolume(), and sibr::VideoVolume< T, N >::w.
subVolumeSpatial()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::subVolumeSpatial (int x, int y, int w, int h) const inline
Definition at line 439 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, and sibr::VideoVolume< T, N >::w.
swapRBchannels()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::swapRBchannels () const inline
Definition at line 161 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::Key::N, sibr::VideoVolume< T, N >::VideoVolume(), and sibr::VideoVolume< T, N >::w.
temporalBlur() [1/2]
SIBR_VIDEO_EXPORT PyramidLayer sibr::temporalBlur (const PyramidLayer & layer, const PyramidParameters & params, float scaling)
Definition at line 1435 of file VideoUtils.cpp.
References sibr::PyramidLayer::h, sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
Referenced by sibr::blur(), and sibr::downscale().
temporalBlur() [2/2]
template<typename T , uint N> void sibr::VideoVolume< T, N >::temporalBlur (float scaling = 1.0f) inline
Definition at line 238 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat.
Referenced by sibr::VideoVolume< T, N >::pyrDownTemporalModif(), and sibr::VideoVolume< T, N >::pyrUpTemporal().
temporalBlurBoundaryConditions()
template<typename T , uint N> void sibr::VideoVolume< T, N >::temporalBlurBoundaryConditions (float scaling, double left, double right) inline
Definition at line 243 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, sibr::Key::N, sibr::VideoVolume< T, N >::valueAt(), and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoVolume< T, N >::pyrDownBoundaryConditions(), and sibr::VideoVolume< T, N >::pyrUpTemporalBoundaryConditions().
temporalBlurInPlace()
SIBR_VIDEO_EXPORT void sibr::temporalBlurInPlace (PyramidLayer & layer, const PyramidParameters & params, float scaling)
Definition at line 1443 of file VideoUtils.cpp.
References sibr::PyramidLayer::volume.
Referenced by sibr::upscale().
time_sequence()
template<typename T , uint N> cv::Mat_<T> sibr::VideoVolume< T, N >::time_sequence (int i, int j, int c = 0) const inline
Definition at line 416 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat, sibr::Key::N, and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoVolume< T, N >::median_frame(), and sibr::totalVariation().
time_sequence_pixels()
template<typename T , uint N> cv::Mat_<CVpixel> sibr::VideoVolume< T, N >::time_sequence_pixels (int i, int j) const inline
Definition at line 419 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat, sibr::Key::N, and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoVolume< T, N >::spatialSlice(), and sibr::VideoVolume< T, N >::time_sequence_volume().
time_sequence_volume()
template<typename T , uint N> VideoVolume sibr::VideoVolume< T, N >::time_sequence_volume (int i, int j) const inline
Definition at line 423 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::clone(), sibr::VideoVolume< T, N >::time_sequence_pixels(), and sibr::VideoVolume< T, N >::VideoVolume().
TimeHistogram()
sibr::TimeHistogram::TimeHistogram (double _min, double _max, int _numBins) inline
Definition at line 965 of file VideoUtils.hpp.
References sibr::TimeHistogram::bin_range, sibr::TimeHistogram::max, sibr::TimeHistogram::min, sibr::TimeHistogram::numBins, and sibr::TimeHistogram::scaling.
toggle()
template<typename T , uint N> void sibr::VideoVolume< T, N >::toggle (double d = 255) inline
Definition at line 110 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat.
totalVariation()
template<typename T , uint N, typename Pix = typename VideoVolume<float, N>::CVpixel> cv::Mat_<Pix> sibr::totalVariation (const VideoVolume< T, N > & v)
Definition at line 705 of file VideoUtils.hpp.
References sibr::CV_Assign< T, N >::assignValue(), sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::Key::N, sibr::VideoVolume< T, N >::time_sequence(), and sibr::VideoVolume< T, N >::w.
upscale()
SIBR_VIDEO_EXPORT PyramidLayer sibr::upscale (const PyramidLayer & layerUp, const PyramidLayer & layerDown, const PyramidParameters & params)
Definition at line 1468 of file VideoUtils.cpp.
References sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::PyramidParameters::splacialDS, sibr::temporalBlurInPlace(), sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
Referenced by sibr::buildVideoLaplacianPyramid(), sibr::buildVideoLaplacianPyramidFullyReduced(), sibr::VideoLaplacianPyramid::collapse(), and sibr::videoLaplacianBlendingContrib().
valueAt() [1/2]
template<typename T , uint N> T& sibr::VideoVolume< T, N >::valueAt (int t, int i, int j, int c = 0) inline
Definition at line 499 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat, sibr::Key::N, and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoUtils::computeSaveVideoMaskBlur(), sibr::VideoUtils::getBackgroundVolume(), sibr::VideoUtils::getBackgroundVolumeF(), and sibr::VideoVolume< T, N >::temporalBlurBoundaryConditions().
valueAt() [2/2]
template<typename T , uint N> const T& sibr::VideoVolume< T, N >::valueAt (int t, int i, int j, int c = 0) const inline
Definition at line 502 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat, sibr::Key::N, and sibr::VideoVolume< T, N >::w.
video_line()
template<typename T , uint N> cv::Mat sibr::VideoVolume< T, N >::video_line (int i) const inline
Definition at line 427 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat, sibr::Key::N, and sibr::VideoVolume< T, N >::w.
Referenced by sibr::VideoUtils::getMedian().
videoLaplacianBlending() [1/2]
SIBR_VIDEO_EXPORT PyramidLayer sibr::videoLaplacianBlending (PyramidLayer vidA, PyramidLayer vidB, PyramidLayer mask_volume, PyramidParameters params, bool show)
Definition at line 1699 of file VideoUtils.cpp.
References sibr::buildVideoGaussianPyramid(), sibr::buildVideoLaplacianPyramid(), sibr::VideoLaplacianPyramid::collapse(), sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::VideoLaplacianPyramid::layers, sibr::PyramidParameters::num_levels, sibr::VideoLaplacianPyramid::params, sibr::show(), sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
videoLaplacianBlending() [2/2]
SIBR_VIDEO_EXPORT PyramidLayer sibr::videoLaplacianBlending (sibr::Video & vidA, sibr::Video & vidB, PyramidLayer mask_volume)
Definition at line 1674 of file VideoUtils.cpp.
References sibr::buildVideoGaussianPyramid(), sibr::buildVideoLaplacianPyramid(), sibr::VideoLaplacianPyramid::collapse(), sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::VideoLaplacianPyramid::layers, sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
videoLaplacianBlendingContrib()
SIBR_VIDEO_EXPORT std::vector< FullContribData > sibr::videoLaplacianBlendingContrib (PyramidLayer vidA, PyramidLayer vidB, PyramidLayer mask_volume, PyramidParameters params)
Definition at line 1744 of file VideoUtils.cpp.
References sibr::buildVideoGaussianPyramid(), sibr::buildVideoLaplacianPyramid(), sibr::VideoLaplacianPyramid::collapse(), sibr::ContribData::contrib, sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::VideoLaplacianPyramid::layers, sibr::ContribData::mask, sibr::FullContribData::notScaled, sibr::PyramidParameters::num_levels, sibr::VideoLaplacianPyramid::params, sibr::ContribData::partA, sibr::ContribData::partB, sibr::FullContribData::scaled, sibr::upscale(), sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
videoLaplacianBlendingDebug()
SIBR_VIDEO_EXPORT void sibr::videoLaplacianBlendingDebug (PyramidLayer vidA, PyramidLayer vidB, PyramidLayer mask_volume, PyramidParameters params)
Definition at line 1813 of file VideoUtils.cpp.
References sibr::buildVideoGaussianPyramid(), sibr::buildVideoLaplacianPyramid(), sibr::VideoLaplacianPyramid::collapse(), sibr::PyramidLayer::h, sibr::PyramidLayer::l, sibr::VideoLaplacianPyramid::layers, sibr::PyramidParameters::num_levels, sibr::PyramidLayer::volume, and sibr::PyramidLayer::w.
VideoLaplacianPyramid()
sibr::VideoLaplacianPyramid::VideoLaplacianPyramid () inline
Definition at line 799 of file VideoUtils.hpp.
VideoVolume() [1/5]
template<typename T , uint N> sibr::VideoVolume< T, N >::VideoVolume () inline
Definition at line 71 of file VideoUtils.hpp.
Referenced by sibr::VideoVolume< T, N >::applyMask(), sibr::VideoVolume< T, N >::applyMaskBinary(), sibr::VideoVolume< T, N >::clone(), sibr::VideoVolume< T, N >::setupFrom(), sibr::VideoVolume< T, N >::subVolume(), sibr::VideoVolume< T, N >::subVolume_i(), sibr::VideoVolume< T, N >::subVolume_i_copy(), sibr::VideoVolume< T, N >::subVolumeRef(), sibr::VideoVolume< T, N >::swapRBchannels(), and sibr::VideoVolume< T, N >::time_sequence_volume().
VideoVolume() [2/5]
template<typename T , uint N> sibr::VideoVolume< T, N >::VideoVolume (const VideoVolume< T, N > & other) inline
Definition at line 89 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::mat.
VideoVolume() [3/5]
template<typename T , uint N> sibr::VideoVolume< T, N >::VideoVolume (cv::Mat other_volume, int _w, int _h) inline
Definition at line 81 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, sibr::Key::N, SIBR_ERR, and sibr::VideoVolume< T, N >::w.
VideoVolume() [4/5]
template<typename T , uint N> sibr::VideoVolume< T, N >::VideoVolume (int _l, int _w, int _h) inline
Definition at line 73 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, sibr::Key::N, and sibr::VideoVolume< T, N >::w.
VideoVolume() [5/5]
template<typename T , uint N> sibr::VideoVolume< T, N >::VideoVolume (int _l, int _w, int _h, double value) inline
Definition at line 77 of file VideoUtils.hpp.
References sibr::VideoVolume< T, N >::h, sibr::VideoVolume< T, N >::l, sibr::VideoVolume< T, N >::mat, sibr::Key::N, sibr::Key::T, and sibr::VideoVolume< T, N >::w.
whatBin() [1/3]
sibr::Vector3ub sibr::TimeHistogram::whatBin (const sibr::Vector3ub & value) inline
Definition at line 1001 of file VideoUtils.hpp.
References sibr::clamp(), sibr::TimeHistogram::min, sibr::TimeHistogram::numBins, and sibr::TimeHistogram::scaling.
Referenced by sibr::TimeHistogram::addValue(), sibr::VideoUtils::getBackGroundVideo(), and sibr::VideoUtils::getTemporalSpatialRatio().
whatBin() [2/3]
template<typename T , uint N> Indice sibr::Histogram< T, N >::whatBin (const Value & value) inline
Definition at line 852 of file VideoUtils.hpp.
References sibr::clamp(), sibr::Histogram< T, N >::min, sibr::Key::N, sibr::Histogram< T, N >::numBins, and sibr::Histogram< T, N >::scaling.
Referenced by sibr::Histogram< T, N >::addValue(), and sibr::Histogram< T, 1 >::addValue().
whatBin() [3/3]
template<typename T > bool sibr::Histogram< T, 1 >::whatBin (T value, uint & bin) inline
Definition at line 905 of file VideoUtils.hpp.
References sibr::Histogram< T, N >::min, sibr::Histogram< T, N >::numBins, and sibr::Histogram< T, N >::scaling.
Variable Documentation
bin_range [1/3]
template<typename T , uint N> Range sibr::Histogram< T, N >::bin_range protected
Definition at line 891 of file VideoUtils.hpp.
Referenced by sibr::Histogram< T, N >::getBinMiddle(), sibr::Histogram< T, 1 >::getBinMiddle(), sibr::Histogram< T, N >::Histogram(), and sibr::Histogram< T, 1 >::Histogram().
bin_range [2/3]
template<typename T > double sibr::Histogram< T, 1 >::bin_range protected
Definition at line 956 of file VideoUtils.hpp.
bin_range [3/3]
double sibr::TimeHistogram::bin_range
Definition at line 1029 of file VideoUtils.hpp.
Referenced by sibr::TimeHistogram::getBinMiddle(), and sibr::TimeHistogram::TimeHistogram().
bins [1/3]
template<typename T , uint N> std::map<Indice, uint> sibr::Histogram< T, N >::bins protected
Definition at line 890 of file VideoUtils.hpp.
Referenced by sibr::Histogram< T, N >::addValue(), sibr::Histogram< T, 1 >::addValue(), sibr::Histogram< T, N >::getModeIndice(), sibr::Histogram< T, 1 >::getModeIndice(), and sibr::Histogram< T, 1 >::normalized_values().
bins [2/3]
template<typename T > std::vector<uint> sibr::Histogram< T, 1 >::bins protected
Definition at line 955 of file VideoUtils.hpp.
bins [3/3]
std::map<sibr::Vector3ub, int> sibr::TimeHistogram::bins
Definition at line 1027 of file VideoUtils.hpp.
Referenced by sibr::TimeHistogram::addValue(), sibr::TimeHistogram::computeSortedBins(), and sibr::TimeHistogram::getHMode().
codec_ffdshow
int sibr::VideoUtils::codec_ffdshow = cv::VideoWriter::fourcc('F', 'F', 'D', 'S') static
Definition at line 1084 of file VideoUtils.hpp.
codec_OpenH264
int sibr::VideoUtils::codec_OpenH264 = cv::VideoWriter::fourcc('H', '2', '6', '4') static
Definition at line 1085 of file VideoUtils.hpp.
codec_OpenH264_fallback
int sibr::VideoUtils::codec_OpenH264_fallback = 0x31637661 static
Definition at line 1086 of file VideoUtils.hpp.
contrib
PyramidLayer sibr::ContribData::contrib
Definition at line 825 of file VideoUtils.hpp.
Referenced by sibr::videoLaplacianBlendingContrib().
cv_type
template<typename T , uint N> const uint sibr::VideoVolume< T, N >::cv_type = getOpenCVtype<T, N> static
Definition at line 64 of file VideoUtils.hpp.
Referenced by sibr::VideoVolume< T, N >::add(), and sibr::VideoVolume< T, N >::substract().
h [1/2]
template<typename T , uint N> int sibr::VideoVolume< T, N >::h = 0
Definition at line 67 of file VideoUtils.hpp.
Referenced by sibr::VideoVolume< T, N >::applyMask(), sibr::VideoVolume< T, N >::applyMaskBinary(), sibr::VideoVolume< T, N >::clone(), sibr::VideoVolume< T, N >::colorMapped(), sibr::VideoUtils::computeSaveSimpleFlow(), sibr::VideoUtils::computeSaveVideoMaskBlur(), sibr::VideoUtils::computeSaveVideoMaskF(), sibr::VideoVolume< T, N >::concat(), sibr::VideoVolume< T, N >::concatH(), sibr::VideoVolume< T, N >::convertTo(), sibr::VideoVolume< T, N >::cout(), sibr::VideoVolume< T, N >::cutFrames(), sibr::VideoVolume< T, N >::duplicateTime(), sibr::VideoVolume< T, N >::extendedDownScaleTemporal(), sibr::VideoVolume< T, N >::frame(), sibr::VideoUtils::getBackgroundVolume(), sibr::VideoUtils::getBackgroundVolumeF(), sibr::laplacianPyramid(), sibr::VideoVolume< T, N >::median_frame(), sibr::VideoVolume< T, N >::pyrDownBoundaryConditions(), sibr::VideoVolume< T, N >::pyrDownSpacial(), sibr::VideoVolume< T, N >::pyrDownTemporal(), sibr::VideoVolume< T, N >::pyrDownTemporalBox(), sibr::VideoVolume< T, N >::pyrDownTemporalModif(), sibr::VideoVolume< T, N >::pyrUpTemporal(), sibr::VideoVolume< T, N >::pyrUpTemporalBoundaryConditions(), sibr::VideoVolume< T, N >::saveToVideoFile(), sibr::VideoVolume< T, N >::setupFrom(), sibr::VideoVolume< T, N >::spatialRescale(), sibr::VideoVolume< T, N >::subVolume(), sibr::VideoVolume< T, N >::subVolumeRef(), sibr::VideoVolume< T, N >::subVolumeSpatial(), sibr::VideoVolume< T, N >::swapRBchannels(), sibr::VideoVolume< T, N >::temporalBlurBoundaryConditions(), sibr::totalVariation(), and sibr::VideoVolume< T, N >::VideoVolume().
h [2/2]
int sibr::PyramidLayer::h
Definition at line 764 of file VideoUtils.hpp.
Referenced by sibr::blur(), sibr::PyramidLayer::copySizeFrom(), sibr::decimate(), sibr::downscale(), sibr::VideoUtils::getBackGroundVideo(), sibr::PyramidLayer::getRGB(), sibr::VideoUtils::getTemporalSpatialRatio(), sibr::PyramidLayer::operator+(), sibr::PyramidLayer::operator-(), sibr::PyramidLayer::saveToVideoFile(), sibr::PyramidLayer::show(), sibr::slice(), sibr::temporalBlur(), sibr::upscale(), sibr::videoLaplacianBlending(), sibr::videoLaplacianBlendingContrib(), and sibr::videoLaplacianBlendingDebug().
inputA
PyramidLayer sibr::FullContribData::inputA
Definition at line 831 of file VideoUtils.hpp.
inputB
PyramidLayer sibr::FullContribData::inputB
Definition at line 831 of file VideoUtils.hpp.
l [1/2]
template<typename T , uint N> int sibr::VideoVolume< T, N >::l = 0
Definition at line 67 of file VideoUtils.hpp.
Referenced by sibr::VideoVolume< T, N >::applyMask(), sibr::VideoVolume< T, N >::applyMaskBinary(), sibr::VideoVolume< T, N >::applyMaskInPlace(), sibr::VideoVolume< T, N >::colorMapped(), sibr::VideoUtils::computeSaveSimpleFlow(), sibr::VideoUtils::computeSaveVideoMaskBlur(), sibr::VideoUtils::computeSaveVideoMaskF(), sibr::VideoVolume< T, N >::concat(), sibr::VideoVolume< T, N >::concatH(), sibr::VideoVolume< T, N >::convertTo(), sibr::VideoVolume< T, N >::cout(), sibr::VideoVolume< T, N >::cutFrames(), sibr::VideoVolume< T, N >::duplicateTime(), sibr::extendedBlurPyramid(), sibr::VideoVolume< T, N >::extendedDownScaleTemporal(), sibr::gaussianPyramid(), sibr::gaussianPyramidTemporal(), sibr::gaussianPyramidTemporalBox(), sibr::VideoUtils::getBackgroundVolume(), sibr::VideoUtils::getBackgroundVolumeF(), sibr::VideoUtils::getMedian(), sibr::laplacianPyramid(), sibr::laplacianPyramidTemporal(), sibr::laplacianPyramidTemporalDouble(), sibr::VideoVolume< T, N >::multiply(), sibr::VideoVolume< T, N >::pyrDownBoundaryConditions(), sibr::VideoVolume< T, N >::pyrDownSpacial(), sibr::VideoVolume< T, N >::pyrDownTemporalBox(), sibr::VideoVolume< T, N >::pyrDownTemporalModif(), sibr::VideoVolume< T, N >::pyrUpSpacial(), sibr::VideoVolume< T, N >::saveToVideoFile(), sibr::VideoVolume< T, N >::setupFrom(), sibr::VideoVolume< T, N >::spatialRescale(), sibr::VideoVolume< T, N >::spatialSlice(), sibr::VideoVolume< T, N >::subVolumeSpatial(), sibr::VideoVolume< T, N >::swapRBchannels(), sibr::VideoVolume< T, N >::temporalBlurBoundaryConditions(), sibr::totalVariation(), and sibr::VideoVolume< T, N >::VideoVolume().
l [2/2]
int sibr::PyramidLayer::l
Definition at line 764 of file VideoUtils.hpp.
Referenced by sibr::blur(), sibr::PyramidLayer::copySizeFrom(), sibr::decimate(), sibr::downscale(), sibr::VideoUtils::getBackGroundVideo(), sibr::VideoUtils::getTemporalSpatialRatio(), sibr::PyramidLayer::operator+(), sibr::PyramidLayer::operator-(), sibr::PyramidLayer::saveToVideoFile(), sibr::PyramidLayer::show(), sibr::slice(), sibr::upscale(), sibr::videoLaplacianBlending(), sibr::videoLaplacianBlendingContrib(), and sibr::videoLaplacianBlendingDebug().
layers [1/2]
std::vector<PyramidLayer> sibr::VideoGaussianPyramid::layers
Definition at line 791 of file VideoUtils.hpp.
Referenced by sibr::buildVideoGaussianPyramid().
layers [2/2]
std::vector<PyramidLayer> sibr::VideoLaplacianPyramid::layers
Definition at line 807 of file VideoUtils.hpp.
Referenced by sibr::buildVideoLaplacianPyramid(), sibr::buildVideoLaplacianPyramidFullyReduced(), sibr::VideoLaplacianPyramid::collapse(), sibr::convertReducedVideoPyramidTo128(), sibr::videoLaplacianBlending(), sibr::videoLaplacianBlendingContrib(), and sibr::videoLaplacianBlendingDebug().
mask
PyramidLayer sibr::ContribData::mask
Definition at line 825 of file VideoUtils.hpp.
Referenced by sibr::videoLaplacianBlendingContrib().
mat
template<typename T , uint N> cv::Mat_<T> sibr::VideoVolume< T, N >::mat
Definition at line 68 of file VideoUtils.hpp.
Referenced by sibr::VideoVolume< T, N >::add(), sibr::VideoVolume< T, N >::clone(), sibr::VideoUtils::computeSaveVideoMaskBlur(), sibr::VideoVolume< T, N >::concat(), sibr::VideoVolume< T, N >::cutFrames(), sibr::VideoVolume< T, N >::duplicateTime(), sibr::VideoVolume< T, N >::extendedDownScaleTemporal(), sibr::VideoVolume< T, N >::extendedTemporalBlur(), sibr::VideoVolume< T, N >::frame(), sibr::VideoVolume< T, N >::isValid(), sibr::VideoVolume< T, N >::pyrDownBoundaryConditions(), sibr::VideoVolume< T, N >::pyrDownTemporal(), sibr::VideoVolume< T, N >::pyrDownTemporalBox(), sibr::VideoVolume< T, N >::pyrUpTemporal(), sibr::VideoVolume< T, N >::pyrUpTemporalBoundaryConditions(), sibr::VideoVolume< T, N >::scale(), sibr::VideoVolume< T, N >::shift(), sibr::VideoVolume< T, N >::substract(), sibr::VideoVolume< T, N >::subVolume(), sibr::VideoVolume< T, N >::subVolume_i(), sibr::VideoVolume< T, N >::subVolume_i_copy(), sibr::VideoVolume< T, N >::subVolumeRef(), sibr::VideoVolume< T, N >::temporalBlur(), sibr::VideoVolume< T, N >::temporalBlurBoundaryConditions(), sibr::VideoVolume< T, N >::time_sequence(), sibr::VideoVolume< T, N >::time_sequence_pixels(), sibr::VideoVolume< T, N >::toggle(), sibr::VideoVolume< T, N >::valueAt(), sibr::VideoVolume< T, N >::video_line(), and sibr::VideoVolume< T, N >::VideoVolume().
max [1/3]
template<typename T , uint N> Range sibr::Histogram< T, N >::max protected
Definition at line 891 of file VideoUtils.hpp.
Referenced by sibr::Histogram< T, N >::Histogram(), and sibr::Histogram< T, 1 >::Histogram().
max [2/3]
template<typename T > double sibr::Histogram< T, 1 >::max protected
Definition at line 956 of file VideoUtils.hpp.
max [3/3]
double sibr::TimeHistogram::max
Definition at line 1029 of file VideoUtils.hpp.
Referenced by sibr::TimeHistogram::TimeHistogram().
min [1/3]
template<typename T , uint N> Range sibr::Histogram< T, N >::min protected
Definition at line 891 of file VideoUtils.hpp.
Referenced by sibr::Histogram< T, N >::getBinMiddle(), sibr::Histogram< T, 1 >::getBinMiddle(), sibr::Histogram< T, N >::Histogram(), sibr::Histogram< T, 1 >::Histogram(), sibr::Histogram< T, N >::whatBin(), and sibr::Histogram< T, 1 >::whatBin().
min [2/3]
template<typename T > double sibr::Histogram< T, 1 >::min protected
Definition at line 956 of file VideoUtils.hpp.
min [3/3]
double sibr::TimeHistogram::min
Definition at line 1029 of file VideoUtils.hpp.
Referenced by sibr::TimeHistogram::getBinMiddle(), sibr::TimeHistogram::TimeHistogram(), and sibr::TimeHistogram::whatBin().
notScaled
ContribData sibr::FullContribData::notScaled
Definition at line 830 of file VideoUtils.hpp.
Referenced by sibr::videoLaplacianBlendingContrib().
num_levels
int sibr::PyramidParameters::num_levels
Definition at line 771 of file VideoUtils.hpp.
Referenced by sibr::videoLaplacianBlending(), sibr::videoLaplacianBlendingContrib(), and sibr::videoLaplacianBlendingDebug().
numBins [1/3]
template<typename T , uint N> uint sibr::Histogram< T, N >::numBins = 50 protected
Definition at line 892 of file VideoUtils.hpp.
Referenced by sibr::Histogram< T, N >::Histogram(), sibr::Histogram< T, 1 >::Histogram(), sibr::Histogram< T, 1 >::normalized_values(), sibr::Histogram< T, N >::whatBin(), and sibr::Histogram< T, 1 >::whatBin().
numBins [2/3]
template<typename T > uint sibr::Histogram< T, 1 >::numBins = 50 protected
Definition at line 957 of file VideoUtils.hpp.
numBins [3/3]
int sibr::TimeHistogram::numBins = 50
Definition at line 1030 of file VideoUtils.hpp.
Referenced by sibr::TimeHistogram::TimeHistogram(), and sibr::TimeHistogram::whatBin().
params [1/2]
PyramidParameters sibr::VideoGaussianPyramid::params
Definition at line 790 of file VideoUtils.hpp.
Referenced by sibr::buildVideoGaussianPyramid().
params [2/2]
PyramidParameters sibr::VideoLaplacianPyramid::params
Definition at line 803 of file VideoUtils.hpp.
Referenced by sibr::buildVideoLaplacianPyramid(), sibr::buildVideoLaplacianPyramidFullyReduced(), sibr::VideoLaplacianPyramid::collapse(), sibr::videoLaplacianBlending(), and sibr::videoLaplacianBlendingContrib().
partA
PyramidLayer sibr::ContribData::partA
Definition at line 825 of file VideoUtils.hpp.
Referenced by sibr::videoLaplacianBlendingContrib().
partB
PyramidLayer sibr::ContribData::partB
Definition at line 825 of file VideoUtils.hpp.
Referenced by sibr::videoLaplacianBlendingContrib().
result
PyramidLayer sibr::FullContribData::result
Definition at line 831 of file VideoUtils.hpp.
scaled
ContribData sibr::FullContribData::scaled
Definition at line 829 of file VideoUtils.hpp.
Referenced by sibr::videoLaplacianBlendingContrib().
scaling [1/3]
template<typename T , uint N> Range sibr::Histogram< T, N >::scaling protected
Definition at line 891 of file VideoUtils.hpp.
Referenced by sibr::Histogram< T, N >::Histogram(), sibr::Histogram< T, 1 >::Histogram(), sibr::Histogram< T, N >::whatBin(), and sibr::Histogram< T, 1 >::whatBin().
scaling [2/3]
template<typename T > double sibr::Histogram< T, 1 >::scaling protected
Definition at line 956 of file VideoUtils.hpp.
scaling [3/3]
double sibr::TimeHistogram::scaling
Definition at line 1029 of file VideoUtils.hpp.
Referenced by sibr::TimeHistogram::TimeHistogram(), and sibr::TimeHistogram::whatBin().
sorted_bins
std::map<sibr::Vector3ub, float> sibr::TimeHistogram::sorted_bins
Definition at line 1028 of file VideoUtils.hpp.
Referenced by sibr::TimeHistogram::computeSortedBins().
spatial_radius
int sibr::PyramidParameters::spatial_radius
Definition at line 773 of file VideoUtils.hpp.
Referenced by sibr::blur().
splacialDS
bool sibr::PyramidParameters::splacialDS = true
Definition at line 774 of file VideoUtils.hpp.
Referenced by sibr::blur(), sibr::downscale(), and sibr::upscale().
temporal_radius
int sibr::PyramidParameters::temporal_radius
Definition at line 772 of file VideoUtils.hpp.
volume
cv::Mat sibr::PyramidLayer::volume
Definition at line 763 of file VideoUtils.hpp.
Referenced by sibr::blur(), sibr::buildVideoLaplacianPyramid(), sibr::PyramidLayer::clone(), sibr::decimate(), sibr::downscale(), sibr::VideoUtils::getBackGroundVideo(), sibr::PyramidLayer::getRGB(), sibr::VideoUtils::getTemporalSpatialRatio(), sibr::PyramidLayer::operator+(), sibr::PyramidLayer::operator-(), sibr::PyramidLayer::saveToVideoFile(), sibr::PyramidLayer::show(), sibr::slice(), sibr::temporalBlur(), sibr::temporalBlurInPlace(), sibr::upscale(), sibr::videoLaplacianBlending(), sibr::videoLaplacianBlendingContrib(), and sibr::videoLaplacianBlendingDebug().
w [1/2]
template<typename T , uint N> int sibr::VideoVolume< T, N >::w = 0
Definition at line 67 of file VideoUtils.hpp.
Referenced by sibr::VideoVolume< T, N >::applyMask(), sibr::VideoVolume< T, N >::applyMaskBinary(), sibr::VideoVolume< T, N >::clone(), sibr::VideoVolume< T, N >::colorMapped(), sibr::VideoUtils::computeSaveSimpleFlow(), sibr::VideoUtils::computeSaveVideoMaskBlur(), sibr::VideoUtils::computeSaveVideoMaskF(), sibr::VideoVolume< T, N >::concat(), sibr::VideoVolume< T, N >::concatH(), sibr::VideoVolume< T, N >::convertTo(), sibr::VideoVolume< T, N >::cout(), sibr::VideoVolume< T, N >::cutFrames(), sibr::VideoVolume< T, N >::duplicateTime(), sibr::VideoVolume< T, N >::extendedDownScaleTemporal(), sibr::VideoUtils::getBackgroundVolume(), sibr::VideoUtils::getBackgroundVolumeF(), sibr::laplacianPyramid(), sibr::VideoVolume< T, N >::median_frame(), sibr::VideoVolume< T, N >::pyrDownBoundaryConditions(), sibr::VideoVolume< T, N >::pyrDownSpacial(), sibr::VideoVolume< T, N >::pyrDownTemporal(), sibr::VideoVolume< T, N >::pyrDownTemporalBox(), sibr::VideoVolume< T, N >::pyrDownTemporalModif(), sibr::VideoVolume< T, N >::pyrUpTemporal(), sibr::VideoVolume< T, N >::pyrUpTemporalBoundaryConditions(), sibr::VideoVolume< T, N >::saveToVideoFile(), sibr::VideoVolume< T, N >::setupFrom(), sibr::VideoVolume< T, N >::spatialRescale(), sibr::VideoVolume< T, N >::subVolume(), sibr::VideoVolume< T, N >::subVolume_i(), sibr::VideoVolume< T, N >::subVolume_i_copy(), sibr::VideoVolume< T, N >::subVolumeRef(), sibr::VideoVolume< T, N >::subVolumeSpatial(), sibr::VideoVolume< T, N >::swapRBchannels(), sibr::VideoVolume< T, N >::temporalBlurBoundaryConditions(), sibr::VideoVolume< T, N >::time_sequence(), sibr::VideoVolume< T, N >::time_sequence_pixels(), sibr::totalVariation(), sibr::VideoVolume< T, N >::valueAt(), sibr::VideoVolume< T, N >::video_line(), and sibr::VideoVolume< T, N >::VideoVolume().
w [2/2]
int sibr::PyramidLayer::w
Definition at line 764 of file VideoUtils.hpp.
Referenced by sibr::blur(), sibr::PyramidLayer::copySizeFrom(), sibr::decimate(), sibr::downscale(), sibr::VideoUtils::getBackGroundVideo(), sibr::VideoUtils::getTemporalSpatialRatio(), sibr::PyramidLayer::operator+(), sibr::PyramidLayer::operator-(), sibr::PyramidLayer::saveToVideoFile(), sibr::PyramidLayer::show(), sibr::slice(), sibr::temporalBlur(), sibr::upscale(), sibr::videoLaplacianBlending(), sibr::videoLaplacianBlendingContrib(), and sibr::videoLaplacianBlendingDebug().