SIBR: sibr_raycaster
sibr_raycaster
Raycasting utilities.
Classes
class sibr::ICameraRaycasterProcessor
Used to process casted rays from image pixels.
class sibr::CameraRaycaster
Used for casting each pixel of an image into a raycaster scene.
class sibr::RaycastingCamera
A raycasting camera is an input camera augmented with additional casting and frustum helpers.
struct quad
Struct representing a 3D quad, along with load/save utilities.
class sibr::Intersector2D
This class provides utilities to compute point/line/triangle/quad intersections.
class PlaneEstimator
Fit a plane to a point cloud using an improved RANSAC approach.
class sibr::Ray
Represents a simple ray.
class sibr::RayHit
Contains information about a ray hit.
class sibr::Raycaster
This class can be used to cast rays against a scene containing triangular meshes.
struct sibr::BasicVoxelType
Default voxel type, storing binary occupancy.
class sibr::VoxelGridBase
Basic voxel grid interface provinding cell manipulation and query helpers.
class sibr::VoxelGrid< CellType >
Voxel grid with custom data storage.
class sibr::KdTree< num_t, Distance >
Represent a 3D hierachical query structure baked by a nanoflann KdTree.
Typedefs
typedef Eigen::AlignedBox< float, 3 > sibr::VoxelGridBase::Box
using sibr::VoxelGrid< CellType >::VoxelType = CellType
Functions
sibr::Vector3f sibr::orthoVector (const sibr::Vector3f &v)
Generate a vector orthogonal to the input one.
sibr::BasicVoxelType::operator bool () const
sibr::VoxelGridBase::SIBR_CLASS_PTR (VoxelGridBase)
sibr::VoxelGridBase::VoxelGridBase (const Box &boundingBox, int numPerDim, bool forceCube=true)
Constructor.
sibr::VoxelGridBase::VoxelGridBase (const Box &boundingBox, const sibr::Vector3i &numsPerDim, bool forceCube=true)
Constructor.
bool sibr::VoxelGridBase::isInside (const sibr::Vector3f &worldPos) const
Check if a position is in the voxel grid.
bool sibr::VoxelGridBase::outOfBounds (const sibr::Vector3i &cell) const
Check if a set of indices correspond to a reachable voxel.
size_t sibr::VoxelGridBase::getNumCells () const
const sibr::Vector3i & sibr::VoxelGridBase::getDims () const
sibr::Vector3i sibr::VoxelGridBase::getCell (size_t cellId) const
Convert a linear cell ID to a set of 3D indices.
size_t sibr::VoxelGridBase::getCellId (const sibr::Vector3i &cell) const
Convert a voxel 3D indices to a linear ID.
size_t sibr::VoxelGridBase::getCellId (const sibr::Vector3f &world_pos) const
Convert a 3D position to the linear ID of the voxel containing it.
sibr::Vector3f sibr::VoxelGridBase::getCellCenter (const sibr::Vector3i &cell) const
Get the position of a voxel center in world space.
sibr::Vector3f sibr::VoxelGridBase::getCellCenter (size_t cellId) const
Get the position of a voxel center in world space.
std::vector< size_t > sibr::VoxelGridBase::rayMarch (const Ray &ray) const
Intersect a ray with the voxel grid, listing all intersected voxels.
sibr::Mesh::Ptr sibr::VoxelGridBase::getCellMesh (const sibr::Vector3i &cell) const
Generate a wireframe mesh representing a voxel.
sibr::Mesh::Ptr sibr::VoxelGridBase::getAllCellMesh () const
Generate a wireframe mesh representing all voxels.
sibr::Mesh::Ptr sibr::VoxelGridBase::getCellMeshFilled (const sibr::Vector3i &cell) const
Generate a triangle mesh representing a voxel.
sibr::Mesh::Ptr sibr::VoxelGridBase::getAllCellMeshFilled () const
Generate a triangle mesh representing all voxels.
Eigen::AlignedBox3f sibr::VoxelGridBase::getCellBox (size_t cellId) const
Get a voxel bounding box.
std::vector< size_t > sibr::VoxelGridBase::getNeighbors (size_t cellId) const
Get a voxel neighbors linear IDs.
VoxelGridBase sibr::VoxelGridBase::extend (int numCells) const
Extend the voxel grid along all dimensions.
const Box & sibr::VoxelGridBase::getBBox () const
static int sibr::VoxelGridBase::getMinIndex (const sibr::Vector3f &v)
Return the index of the smallest coefficient of the input vector.
sibr::Vector3i sibr::VoxelGridBase::getCell (const sibr::Vector3f &worldPos) const
Get the integer coordinates of the cell containing a position.
sibr::Vector3i sibr::VoxelGridBase::getCellInclusive (const sibr::Vector3f &worldPos) const
Get the integer coordinates of the cell containing a position.
bool sibr::VoxelGridBase::intersectionWithBox (const Ray &ray, sibr::Vector3f &intersection) const
Check if a ray intersect the voxel grid.
const sibr::Vector3f & sibr::VoxelGridBase::getCellSize () const
float sibr::VoxelGridBase::getCellSizeNorm () const
sibr::Vector3f sibr::VoxelGridBase::sampleCell (size_t cellId)
Sample a random position in a given voxel.
sibr::Mesh::Ptr sibr::VoxelGridBase::getCellMeshInternal (const sibr::Vector3i &cell, bool filled) const
Helper to generate a voxel mesh.
sibr::Mesh::Ptr sibr::VoxelGridBase::getAllCellMeshInternal (bool filled) const
Helper to generate the voxel grid mesh.
sibr::VoxelGrid< CellType >::SIBR_CLASS_PTR (VoxelGrid)
sibr::VoxelGrid< CellType >::VoxelGrid (const Box &boundingBox, int numPerDim, bool forceCube=true)
Constructor.
sibr::VoxelGrid< CellType >::VoxelGrid (const Box &boundingBox, const sibr::Vector3i &numsPerDim, bool forceCube=true)
Constructor.
CellType & sibr::VoxelGrid< CellType >::operator[] (size_t cell_id)
Get voxel at a given linear index.
const CellType & sibr::VoxelGrid< CellType >::operator[] (size_t cell_id) const
Get voxel at a given linear index.
CellType & sibr::VoxelGrid< CellType >::operator() (int x, int y, int z)
Get voxel at given integer 3D coordinates.
const CellType & sibr::VoxelGrid< CellType >::operator() (int x, int y, int z) const
Get voxel at given integer 3D coordinates.
CellType & sibr::VoxelGrid< CellType >::operator[] (const sibr::Vector3i &v)
Get voxel at given integer 3D coordinates.
const CellType & sibr::VoxelGrid< CellType >::operator[] (const sibr::Vector3i &v) const
Get voxel at given integer 3D coordinates.
template<typename FuncType >
sibr::Mesh::Ptr sibr::VoxelGrid< CellType >::getAllCellMeshWithCond (bool filled, const FuncType &func) const
Generate a mesh from all voxels satisfying a condition.
sibr::Mesh::Ptr sibr::VoxelGrid< CellType >::getAllCellMeshWithIds (bool filled, std::vector< std::size_t > cell_ids) const
Get cell meshes from their ids.
template<typename FuncType >
std::vector< std::size_t > sibr::VoxelGrid< CellType >::detect_non_empty_cells (const FuncType &func) const
List the voxels that statisfy a condition (for instance fullness)
const std::vector< CellType > & sibr::VoxelGrid< CellType >::getData () const
Variables
bool sibr::BasicVoxelType::used = true
The voxel status.
sibr::Vector3i sibr::VoxelGridBase::dims
Integer grid dimensions.
sibr::Vector3f sibr::VoxelGridBase::cellSize
World space voxel size.
float sibr::VoxelGridBase::cellSizeNorm
World space voxel diagonal length.
Box sibr::VoxelGridBase::box
Grid bounding box.
sibr::Mesh::Ptr sibr::VoxelGridBase::baseCellMesh
sibr::Mesh::Ptr sibr::VoxelGridBase::baseCellMeshFilled
Base meshes for visualisation.
std::mt19937 sibr::VoxelGridBase::_generator
Generator for sampling, seeded at 0.
std::uniform_real_distribution< double > sibr::VoxelGridBase::_distribution
(-1,1) distribution.
std::vector< CellType > sibr::VoxelGrid< CellType >::data
Voxels storage.
Detailed Description
Raycasting utilities.
This module provides functionalities related to raycasting on 2D and 3D geometry. It contains basic 2D intersection tests, a wrapper around the embree raycasting library (http://embree.github.io/), and helpers to perform raycasting over all pixels of an image.
Typedef Documentation
Box
typedef Eigen::AlignedBox<float, 3> sibr::VoxelGridBase::Box
Definition at line 42 of file VoxelGrid.hpp.
VoxelType
template<typename CellType = BasicVoxelType> using sibr::VoxelGrid< CellType >::VoxelType = CellType
Definition at line 229 of file VoxelGrid.hpp.
Function Documentation
detect_non_empty_cells()
template<typename CellType > template<typename FuncType > std::vector< std::size_t > sibr::VoxelGrid< CellType >::detect_non_empty_cells (const FuncType & func) const inline
List the voxels that statisfy a condition (for instance fullness)
Parameters
func the predicate to evaluate, will receive as unique argument a voxel (CellType).
Returns
a list of linear indices of all voxels such that func(voxel) is true.
Definition at line 340 of file VoxelGrid.hpp.
extend()
VoxelGridBase sibr::VoxelGridBase::extend (int numCells) const
Extend the voxel grid along all dimensions.
This means that if the initial count along a given axis was N, the new is N+2*numCells.
Parameters
numCells the number of cells to add
Returns
the extended voxel grid
Definition at line 255 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::box, sibr::VoxelGridBase::dims, sibr::VoxelGridBase::getCellSize(), and sibr::VoxelGridBase::VoxelGridBase().
getAllCellMesh()
sibr::Mesh::Ptr sibr::VoxelGridBase::getAllCellMesh () const
Generate a wireframe mesh representing all voxels.
Returns
the generated wireframe cube mesh
Definition at line 208 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::getAllCellMeshInternal().
getAllCellMeshFilled()
sibr::Mesh::Ptr sibr::VoxelGridBase::getAllCellMeshFilled () const
Generate a triangle mesh representing all voxels.
Returns
the generated filled cube mesh
Definition at line 218 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::getAllCellMeshInternal().
getAllCellMeshInternal()
sibr::Mesh::Ptr sibr::VoxelGridBase::getAllCellMeshInternal (bool filled) const protected
Helper to generate the voxel grid mesh.
Parameters
filled should the mesh be wireframe (false) or faceted (true)
Returns
the generated mesh
Definition at line 323 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::baseCellMesh, sibr::VoxelGridBase::baseCellMeshFilled, sibr::VoxelGridBase::getCell(), sibr::VoxelGridBase::getCellSize(), and sibr::VoxelGridBase::getNumCells().
Referenced by sibr::VoxelGridBase::getAllCellMesh(), and sibr::VoxelGridBase::getAllCellMeshFilled().
getAllCellMeshWithCond()
template<typename CellType > template<typename FuncType > sibr::Mesh::Ptr sibr::VoxelGrid< CellType >::getAllCellMeshWithCond (bool filled, const FuncType & func) const inline
Generate a mesh from all voxels satisfying a condition.
Parameters
filled should the mesh be wireframe (false) or faceted (true)
func the predicate to evaluate, will receive as unique argument a voxel (CellType).
Returns
the generated mesh
Definition at line 351 of file VoxelGrid.hpp.
getAllCellMeshWithIds()
template<typename CellType > sibr::Mesh::Ptr sibr::VoxelGrid< CellType >::getAllCellMeshWithIds (bool filled, std::vector< std::size_t > cell_ids) const inline
Get cell meshes from their ids.
}@
Parameters
filled should the mesh be wireframe (false) or faceted (true)
cell_ids ids of cell meshes.
Returns
the generated mesh
Definition at line 360 of file VoxelGrid.hpp.
getBBox()
const Box& sibr::VoxelGridBase::getBBox () const inline
Returns
the voxel grid bounding box.
Definition at line 155 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGridBase::getNeighbors().
getCell() [1/2]
sibr::Vector3i sibr::VoxelGridBase::getCell (const sibr::Vector3f & worldPos) const
Get the integer coordinates of the cell containing a position.
Parameters
worldPos the position
Returns
the cell integer coordinates
Definition at line 126 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::box, sibr::VoxelGridBase::dims, and SIBR_ERR.
getCell() [2/2]
sibr::Vector3i sibr::VoxelGridBase::getCell (size_t cellId) const
Convert a linear cell ID to a set of 3D indices.
Parameters
cellId linear ID
Returns
the indices of the voxel along each axis
Definition at line 99 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::dims, sibr::VoxelGridBase::getNumCells(), sibr::VoxelGridBase::outOfBounds(), and SIBR_ERR.
Referenced by sibr::VoxelGridBase::getAllCellMeshInternal(), sibr::VoxelGridBase::getCellBox(), sibr::VoxelGridBase::getCellCenter(), sibr::VoxelGridBase::getCellId(), sibr::VoxelGridBase::rayMarch(), and sibr::VoxelGridBase::sampleCell().
getCellBox()
Eigen::AlignedBox3f sibr::VoxelGridBase::getCellBox (size_t cellId) const
Get a voxel bounding box.
Parameters
cellId the voxel linear index
Returns
the bounding box.
Definition at line 223 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::getCell(), sibr::VoxelGridBase::getCellCenter(), and sibr::VoxelGridBase::getCellSize().
getCellCenter() [1/2]
sibr::Vector3f sibr::VoxelGridBase::getCellCenter (const sibr::Vector3i & cell) const
Get the position of a voxel center in world space.
Parameters
cell the voxel integer coordinates
Returns
the center 3D position
Definition at line 367 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::box, and sibr::VoxelGridBase::getCellSize().
Referenced by sibr::VoxelGridBase::getCellBox(), sibr::VoxelGridBase::getCellCenter(), sibr::VoxelGridBase::getNeighbors(), and sibr::VoxelGridBase::sampleCell().
getCellCenter() [2/2]
sibr::Vector3f sibr::VoxelGridBase::getCellCenter (size_t cellId) const
Get the position of a voxel center in world space.
Parameters
cellId linear voxel ID
Returns
the center 3D position
Definition at line 372 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::getCell(), and sibr::VoxelGridBase::getCellCenter().
getCellId() [1/2]
size_t sibr::VoxelGridBase::getCellId (const sibr::Vector3f & world_pos) const
Convert a 3D position to the linear ID of the voxel containing it.
Parameters
world_pos the position
Returns
the linear ID of the voxel
Definition at line 362 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::getCell(), and sibr::VoxelGridBase::getCellId().
getCellId() [2/2]
size_t sibr::VoxelGridBase::getCellId (const sibr::Vector3i & cell) const
Convert a voxel 3D indices to a linear ID.
Parameters
cell the voxel integer coordinates
Returns
the linear ID
Definition at line 354 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::dims, sibr::VoxelGridBase::outOfBounds(), and SIBR_ERR.
Referenced by sibr::VoxelGridBase::getCellId(), sibr::VoxelGridBase::getNeighbors(), sibr::VoxelGrid< CellType >::operator()(), sibr::VoxelGrid< CellType >::operator[](), and sibr::VoxelGridBase::rayMarch().
getCellInclusive()
sibr::Vector3i sibr::VoxelGridBase::getCellInclusive (const sibr::Vector3f & worldPos) const
Get the integer coordinates of the cell containing a position.
Positions along the boundaries of the voxel grid are considered as belonging to the closest cell.
Parameters
worldPos the position
Returns
the cell integer coordinates
Definition at line 138 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::box, sibr::VoxelGridBase::dims, and SIBR_ERR.
getCellMesh()
sibr::Mesh::Ptr sibr::VoxelGridBase::getCellMesh (const sibr::Vector3i & cell) const
Generate a wireframe mesh representing a voxel.
Parameters
cell the voxel integer coordinates
Returns
the generated wireframe cube mesh
Definition at line 203 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::getCellMeshInternal().
getCellMeshFilled()
sibr::Mesh::Ptr sibr::VoxelGridBase::getCellMeshFilled (const sibr::Vector3i & cell) const
Generate a triangle mesh representing a voxel.
Parameters
cell the voxel integer coordinates
Returns
the generated filled cube mesh
Definition at line 213 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::getCellMeshInternal().
getCellMeshInternal()
sibr::Mesh::Ptr sibr::VoxelGridBase::getCellMeshInternal (const sibr::Vector3i & cell, bool filled) const protected
Helper to generate a voxel mesh.
Parameters
cell the coordinates of the voxel to generate
filled should the mesh be wireframe (false) or faceted (true)
Returns
the generated mesh
Definition at line 307 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::baseCellMesh, sibr::VoxelGridBase::baseCellMeshFilled, and sibr::VoxelGridBase::getCellSize().
Referenced by sibr::VoxelGridBase::getCellMesh(), and sibr::VoxelGridBase::getCellMeshFilled().
getCellSize()
const sibr::Vector3f & sibr::VoxelGridBase::getCellSize () const
Returns
the size of a voxel.
Definition at line 288 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::cellSize.
Referenced by sibr::VoxelGridBase::extend(), sibr::VoxelGridBase::getAllCellMeshInternal(), sibr::VoxelGridBase::getCellBox(), sibr::VoxelGridBase::getCellCenter(), sibr::VoxelGridBase::getCellMeshInternal(), sibr::VoxelGridBase::getNeighbors(), sibr::VoxelGridBase::rayMarch(), sibr::VoxelGridBase::sampleCell(), and sibr::VoxelGridBase::VoxelGridBase().
getCellSizeNorm()
float sibr::VoxelGridBase::getCellSizeNorm () const
Returns
the length of a voxel diagonal.
Definition at line 293 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::cellSizeNorm.
getData()
template<typename CellType = BasicVoxelType> const std::vector<CellType>& sibr::VoxelGrid< CellType >::getData () const inline
Returns
the voxel grid data.
Definition at line 328 of file VoxelGrid.hpp.
References sibr::VoxelGrid< CellType >::data.
getDims()
const sibr::Vector3i & sibr::VoxelGridBase::getDims () const
Returns
the number of voxels along each axis.
Definition at line 94 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::dims.
getMinIndex()
int sibr::VoxelGridBase::getMinIndex (const sibr::Vector3f & v) static
Return the index of the smallest coefficient of the input vector.
Parameters
v the vector
Returns
the location of the minimum
Definition at line 377 of file VoxelGrid.cpp.
Referenced by sibr::VoxelGridBase::rayMarch().
getNeighbors()
std::vector< size_t > sibr::VoxelGridBase::getNeighbors (size_t cellId) const
Get a voxel neighbors linear IDs.
Parameters
cellId linear voxel ID
Returns
the linear IDs of the neigbors.
Definition at line 235 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::getBBox(), sibr::VoxelGridBase::getCellCenter(), sibr::VoxelGridBase::getCellId(), and sibr::VoxelGridBase::getCellSize().
getNumCells()
size_t sibr::VoxelGridBase::getNumCells () const
Returns
the number of voxels.
Definition at line 89 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::dims.
Referenced by sibr::VoxelGridBase::getAllCellMeshInternal(), sibr::VoxelGridBase::getCell(), and sibr::VoxelGrid< CellType >::VoxelGrid().
intersectionWithBox()
bool sibr::VoxelGridBase::intersectionWithBox (const Ray & ray, sibr::Vector3f & intersection) const
Check if a ray intersect the voxel grid.
Parameters
ray the ray to cast
intersection will contain the intersection position if it exists
Returns
true if there is an intersection
Definition at line 271 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::box, sibr::Ray::dir(), and sibr::Ray::orig().
Referenced by sibr::VoxelGridBase::rayMarch().
isInside()
bool sibr::VoxelGridBase::isInside (const sibr::Vector3f & worldPos) const
Check if a position is in the voxel grid.
Parameters
worldPos the world 3D position
Returns
true if the position is in the grid bounding box
Definition at line 78 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::box.
Referenced by sibr::VoxelGridBase::rayMarch().
operator bool()
sibr::BasicVoxelType::operator bool () const inline
Returns
true if filled.
Definition at line 30 of file VoxelGrid.hpp.
References sibr::BasicVoxelType::used.
operator()() [1/2]
template<typename CellType = BasicVoxelType> CellType& sibr::VoxelGrid< CellType >::operator() (int x, int y, int z) inline
Get voxel at given integer 3D coordinates.
Parameters
x x integer coordinate
y y integer coordinate
z z integer coordinate
Returns
a reference to the voxel
Definition at line 275 of file VoxelGrid.hpp.
References sibr::VoxelGrid< CellType >::data, and sibr::VoxelGridBase::getCellId().
operator()() [2/2]
template<typename CellType = BasicVoxelType> const CellType& sibr::VoxelGrid< CellType >::operator() (int x, int y, int z) const inline
Get voxel at given integer 3D coordinates.
Parameters
x x integer coordinate
y y integer coordinate
z z integer coordinate
Returns
a reference to the voxel
Definition at line 285 of file VoxelGrid.hpp.
References sibr::VoxelGrid< CellType >::data, and sibr::VoxelGridBase::getCellId().
operator[]() [1/4]
template<typename CellType = BasicVoxelType> CellType& sibr::VoxelGrid< CellType >::operator[] (const sibr::Vector3i & v) inline
Get voxel at given integer 3D coordinates.
Parameters
v integer coordinates
Returns
a reference to the voxel
Definition at line 293 of file VoxelGrid.hpp.
References sibr::VoxelGrid< CellType >::data, and sibr::VoxelGridBase::getCellId().
operator[]() [2/4]
template<typename CellType = BasicVoxelType> const CellType& sibr::VoxelGrid< CellType >::operator[] (const sibr::Vector3i & v) const inline
Get voxel at given integer 3D coordinates.
Parameters
v integer coordinates
Returns
a reference to the voxel
Definition at line 301 of file VoxelGrid.hpp.
References sibr::VoxelGrid< CellType >::data, and sibr::VoxelGridBase::getCellId().
operator[]() [3/4]
template<typename CellType = BasicVoxelType> CellType& sibr::VoxelGrid< CellType >::operator[] (size_t cell_id) inline
Get voxel at a given linear index.
Parameters
cell_id the linear index
Returns
a reference to the voxel
Definition at line 257 of file VoxelGrid.hpp.
References sibr::VoxelGrid< CellType >::data.
operator[]() [4/4]
template<typename CellType = BasicVoxelType> const CellType& sibr::VoxelGrid< CellType >::operator[] (size_t cell_id) const inline
Get voxel at a given linear index.
Parameters
cell_id the linear index
Returns
a reference to the voxel
Definition at line 265 of file VoxelGrid.hpp.
References sibr::VoxelGrid< CellType >::data.
orthoVector()
sibr::Vector3f sibr::orthoVector (const sibr::Vector3f & v)
Generate a vector orthogonal to the input one.
Parameters
v the input vector
Returns
the ortogonal vector
Warning
The output vector is not necessarily of unit length.
Definition at line 386 of file VoxelGrid.cpp.
outOfBounds()
bool sibr::VoxelGridBase::outOfBounds (const sibr::Vector3i & cell) const
Check if a set of indices correspond to a reachable voxel.
Parameters
cell the voxel integer coordinates
Returns
true if the voxel exists in the grid
Definition at line 83 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::dims.
Referenced by sibr::VoxelGridBase::getCell(), and sibr::VoxelGridBase::getCellId().
rayMarch()
std::vector< size_t > sibr::VoxelGridBase::rayMarch (const Ray & ray) const
Intersect a ray with the voxel grid, listing all intersected voxels.
Parameters
ray the ray to cast
Returns
linear IDs of the intersected voxels
Definition at line 160 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::box, sibr::VoxelGridBase::dims, sibr::Ray::dir(), sibr::frac(), sibr::VoxelGridBase::getCell(), sibr::VoxelGridBase::getCellId(), sibr::VoxelGridBase::getCellSize(), sibr::VoxelGridBase::getMinIndex(), sibr::VoxelGridBase::intersectionWithBox(), sibr::VoxelGridBase::isInside(), and sibr::Ray::orig().
sampleCell()
sibr::Vector3f sibr::VoxelGridBase::sampleCell (size_t cellId)
Sample a random position in a given voxel.
Parameters
cellId the voxel to sample from
Returns
the sampled position
Note
The random generator is seeded at 0 when creating the grid.
Warning
The current implementation is sampling in center+(random(-1,1)^3)*cellSize.
Definition at line 298 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::_distribution, sibr::VoxelGridBase::_generator, sibr::VoxelGridBase::getCell(), sibr::VoxelGridBase::getCellCenter(), and sibr::VoxelGridBase::getCellSize().
SIBR_CLASS_PTR() [1/2]
template<typename CellType = BasicVoxelType> sibr::VoxelGrid< CellType >::SIBR_CLASS_PTR (VoxelGrid< CellType >) private
SIBR_CLASS_PTR() [2/2]
sibr::VoxelGridBase::SIBR_CLASS_PTR (VoxelGridBase) private
VoxelGrid() [1/2]
template<typename CellType = BasicVoxelType> sibr::VoxelGrid< CellType >::VoxelGrid (const Box & boundingBox, const sibr::Vector3i & numsPerDim, bool forceCube = true) inline
Constructor.
Parameters
boundingBox bounding box delimiting the voxellized region
numsPerDim number of voxels along each dimension
forceCube if true, the largest dimension will be split in numPerDim voxels and the other such that the voxels are cubes in world space
Definition at line 248 of file VoxelGrid.hpp.
References sibr::VoxelGrid< CellType >::data, and sibr::VoxelGridBase::getNumCells().
VoxelGrid() [2/2]
template<typename CellType = BasicVoxelType> sibr::VoxelGrid< CellType >::VoxelGrid (const Box & boundingBox, int numPerDim, bool forceCube = true) inline
Constructor.
Parameters
boundingBox bounding box delimiting the voxellized region
numPerDim number of voxels along each dimension
forceCube if true, the largest dimension will be split in numPerDim voxels and the other such that the voxels are cubes in world space
Definition at line 238 of file VoxelGrid.hpp.
VoxelGridBase() [1/2]
sibr::VoxelGridBase::VoxelGridBase (const Box & boundingBox, const sibr::Vector3i & numsPerDim, bool forceCube = true)
Constructor.
Parameters
boundingBox bounding box delimiting the voxellized region
numsPerDim number of voxels along each dimension
forceCube if true, the largest dimension will be split in numPerDims voxels and the other such that the voxels are cubes in world space
Definition at line 10 of file VoxelGrid.cpp.
References sibr::VoxelGridBase::baseCellMesh, sibr::VoxelGridBase::baseCellMeshFilled, sibr::VoxelGridBase::box, sibr::VoxelGridBase::cellSize, sibr::VoxelGridBase::cellSizeNorm, sibr::VoxelGridBase::dims, sibr::VoxelGridBase::getCellSize(), and sibr::round().
VoxelGridBase() [2/2]
sibr::VoxelGridBase::VoxelGridBase (const Box & boundingBox, int numPerDim, bool forceCube = true)
Constructor.
Parameters
boundingBox bounding box delimiting the voxellized region
numPerDim number of voxels along each dimension
forceCube if true, the largest dimension will be split in numPerDim voxels and the other such that the voxels are cubes in world space
Definition at line 5 of file VoxelGrid.cpp.
Referenced by sibr::VoxelGridBase::extend().
Variable Documentation
_distribution
std::uniform_real_distribution<double> sibr::VoxelGridBase::_distribution protected
(-1,1) distribution.
Definition at line 219 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGridBase::sampleCell().
_generator
std::mt19937 sibr::VoxelGridBase::_generator protected
Generator for sampling, seeded at 0.
Definition at line 218 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGridBase::sampleCell().
baseCellMesh
sibr::Mesh::Ptr sibr::VoxelGridBase::baseCellMesh protected
Definition at line 216 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGridBase::getAllCellMeshInternal(), sibr::VoxelGridBase::getCellMeshInternal(), and sibr::VoxelGridBase::VoxelGridBase().
baseCellMeshFilled
sibr::Mesh::Ptr sibr::VoxelGridBase::baseCellMeshFilled protected
Base meshes for visualisation.
Definition at line 216 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGridBase::getAllCellMeshInternal(), sibr::VoxelGridBase::getCellMeshInternal(), and sibr::VoxelGridBase::VoxelGridBase().
box
Box sibr::VoxelGridBase::box protected
Grid bounding box.
Definition at line 215 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGridBase::extend(), sibr::VoxelGridBase::getCell(), sibr::VoxelGridBase::getCellCenter(), sibr::VoxelGridBase::getCellInclusive(), sibr::VoxelGridBase::intersectionWithBox(), sibr::VoxelGridBase::isInside(), sibr::VoxelGridBase::rayMarch(), and sibr::VoxelGridBase::VoxelGridBase().
cellSize
sibr::Vector3f sibr::VoxelGridBase::cellSize protected
World space voxel size.
Definition at line 213 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGridBase::getCellSize(), and sibr::VoxelGridBase::VoxelGridBase().
cellSizeNorm
float sibr::VoxelGridBase::cellSizeNorm protected
World space voxel diagonal length.
Definition at line 214 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGridBase::getCellSizeNorm(), and sibr::VoxelGridBase::VoxelGridBase().
data
template<typename CellType = BasicVoxelType> std::vector<CellType> sibr::VoxelGrid< CellType >::data protected
Voxels storage.
Definition at line 334 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGrid< CellType >::getData(), sibr::VoxelGrid< CellType >::operator()(), sibr::VoxelGrid< CellType >::operator[](), get_image_size.Test_get_image_size::test_get_image_size(), and sibr::VoxelGrid< CellType >::VoxelGrid().
dims
sibr::Vector3i sibr::VoxelGridBase::dims protected
Integer grid dimensions.
Definition at line 212 of file VoxelGrid.hpp.
Referenced by sibr::VoxelGridBase::extend(), sibr::VoxelGridBase::getCell(), sibr::VoxelGridBase::getCellId(), sibr::VoxelGridBase::getCellInclusive(), sibr::VoxelGridBase::getDims(), sibr::VoxelGridBase::getNumCells(), sibr::VoxelGridBase::outOfBounds(), sibr::VoxelGridBase::rayMarch(), and sibr::VoxelGridBase::VoxelGridBase().
used
bool sibr::BasicVoxelType::used = true
The voxel status.
Definition at line 32 of file VoxelGrid.hpp.
Referenced by sibr::BasicVoxelType::operator bool().