SIBR: sibr_system
sibr_system
System utilities.
Classes
class sibr::Array2d< T >
Used to store custom data on a map using pixel position (2d unsigned pos).
class sibr::ByteStream
Be sure to use STL objects from client's dll version by exporting this declaration (see warning C4251)
struct sibr::Switch
Used to wrap a toggle argument in the command line.
struct sibr::ValueGetter< T >
Helper to extract values from a vector of strings.
class sibr::ArgBase< T >
Internal argument based interface.
class sibr::Arg< T >
Template Arg class, will init itself in the defaut ctor using the command line args (ie.
class sibr::Arg< Switch >
Specialization of Arg for Switch, default value get flipped if arg is present.
class sibr::Arg< bool >
Specialization of Arg for bool, value is true if key is present and false otherwise.
class sibr::RequiredArgBase< T >
Represent a mandatory argument.
class sibr::RequiredArg< T >
Similar to Arg, except this one will crash if attempt to use the value while not initialized initialization can be done using the command line or manually.
class sibr::RequiredArg< std::string >
Specialization required for std::string as const string & key constructor and const T & constructor are ambiguous.
struct sibr::AppArgs
Hierarchy of Args classes that can be seens as modules, and can be combined using virtual inheritance, with no duplication of code so derived Args has no extra work to do Assuming CommandLineArgs::parseMainArgs() was called once, Args arguments will be automatically initialized with the value from the command line by the constructor Existing Args structs should cover most of the existing IBR apps To add a new argument like –my-arg 5 on top of existing arguments and to add a new required argument like –important-param "on" on top of existing arguments, do the following:
struct sibr::WindowArgs
Arguments related to a window.
struct sibr::WindowAppArgs
Combination of window and application arguments.
struct sibr::RenderingArgs
Common rendering settings.
struct sibr::BasicDatasetArgs
Dataset related arguments.
struct sibr::BasicIBRAppArgs
"Default" set of arguments.
struct sibr::ValueGetter< std::string >
Specialization of value getter for strings.
struct sibr::ValueGetter< bool >
Specialization of value getter for booleans.
struct sibr::ValueGetter< double >
Specialization of value getter for doubles.
struct sibr::ValueGetter< float >
Specialization of value getter for floats.
struct sibr::ValueGetter< int >
Specialization of value getter for integers.
struct sibr::ValueGetter< char >
Specialization of value getter for chars.
struct sibr::ValueGetter< uint >
Specialization of value getter for unsigned integers.
struct sibr::ValueGetter< std::array< T, N > >
Specialization of value getter for arrays.
struct sibr::ValueGetter< sibr::Vector< T, N > >
Specialization of value getter for sibr::Vectors.
struct sibr::LogExit
Ensure that all logs are output before exiting when an error or exception is raised.
struct sibr::DebugScopeProfiler
Used for quickly measuring time for completing a scope.
class sibr::LoadingProgress
Simple utility class for reporting on the standard output a loading progess.
class sibr::Rect< T >
Represents a simple aligned axis rectangle.
class sibr::Timer
Timer to monitor performance of a section of code.
class sibr::ThreadIdWorker
Class used to work concurrently on multiple tasks/instructions.
class sibr::Transform3< T >
Represent a 3D transformation composed of a rotation and translation.
class sibr::MultiVector< T, N >
Multi dimensional vector.
class sibr::MultiVector< T, 1 >
Base multi-dimensional vector class (a 1D vector).
class sibr::XMLTree
Wrapper of rapidxml xml_document<> class so that the string associated to the xml file stays in memory.
Typedefs
typedef Eigen::Matrix< unsigned, 4, 4, Eigen::DontAlign, 4, 4 > sibr::Matrix4u
typedef Eigen::Matrix< int, 4, 4, Eigen::DontAlign, 4, 4 > sibr::Matrix4i
typedef Eigen::Matrix< float, 4, 4, Eigen::DontAlign, 4, 4 > sibr::Matrix4f
typedef Eigen::Matrix< double, 4, 4, Eigen::DontAlign, 4, 4 > sibr::Matrix4d
typedef Eigen::Matrix< unsigned, 3, 3, Eigen::DontAlign, 3, 3 > sibr::Matrix3u
typedef Eigen::Matrix< int, 3, 3, Eigen::DontAlign, 3, 3 > sibr::Matrix3i
typedef Eigen::Matrix< float, 3, 3, Eigen::DontAlign, 3, 3 > sibr::Matrix3f
typedef Eigen::Matrix< double, 3, 3, Eigen::DontAlign, 3, 3 > sibr::Matrix3d
typedef Eigen::Quaternion< unsigned > sibr::Quaternionu
typedef Eigen::Quaternion< int > sibr::Quaternioni
typedef Eigen::Quaternion< float > sibr::Quaternionf
typedef Eigen::Quaternion< double > sibr::Quaterniond
template<typename T , int N>
using sibr::Vector = Eigen::Matrix< T, N, 1, Eigen::DontAlign >
typedef Eigen::Matrix< float, 1, 1, Eigen::DontAlign > sibr::Vector1f
typedef Eigen::Matrix< int, 1, 1, Eigen::DontAlign > sibr::Vector1i
typedef Eigen::Matrix< unsigned, 2, 1, Eigen::DontAlign > sibr::Vector2u
typedef Eigen::Matrix< unsigned char, 2, 1, Eigen::DontAlign > sibr::Vector2ub
typedef Eigen::Matrix< int, 2, 1, Eigen::DontAlign > sibr::Vector2i
typedef Eigen::Matrix< float, 2, 1, Eigen::DontAlign > sibr::Vector2f
typedef Eigen::Matrix< double, 2, 1, Eigen::DontAlign > sibr::Vector2d
typedef Eigen::Matrix< unsigned, 3, 1, Eigen::DontAlign > sibr::Vector3u
typedef Eigen::Matrix< unsigned char, 3, 1, Eigen::DontAlign > sibr::Vector3ub
typedef Eigen::Matrix< unsigned short int, 3, 1, Eigen::DontAlign > sibr::Vector3s
typedef Eigen::Matrix< int, 3, 1, Eigen::DontAlign > sibr::Vector3i
typedef Eigen::Matrix< float, 3, 1, Eigen::DontAlign > sibr::Vector3f
typedef Eigen::Matrix< double, 3, 1, Eigen::DontAlign > sibr::Vector3d
typedef Eigen::Matrix< unsigned, 4, 1, Eigen::DontAlign > sibr::Vector4u
typedef Eigen::Matrix< unsigned char, 4, 1, Eigen::DontAlign > sibr::Vector4ub
typedef Eigen::Matrix< int, 4, 1, Eigen::DontAlign > sibr::Vector4i
typedef Eigen::Matrix< float, 4, 1, Eigen::DontAlign > sibr::Vector4f
typedef Eigen::Matrix< double, 4, 1, Eigen::DontAlign > sibr::Vector4d
typedef MultiVector< T, N - 1 > sibr::MultiVector< T, N >::SubVector
Enumerations
enum sibr::RenderingModes { sibr::RENDERMODE_MONO, sibr::RENDERMODE_STEREO_ANAGLYPH, sibr::RENDERMODE_STEREO_QUADBUFFER }
Available rendering modes for IBR views.
enum sibr::FilePickerMode { sibr::Default, sibr::Save, sibr::Directory }
Selection mode for the file picker.
Functions
const CommandLineArgs & sibr::getCommandLineArgs ()
Getter for the command line args manager singleton.
float sibr::round (float x)
Rounding operation.
template<typename T >
Eigen::Matrix< T, 4, 4, 0, 4, 4 > sibr::matFromQuat (const Eigen::Quaternion< T, 0 > &q)
Convert a quaternion to a rotation matrix.
template<typename T , int Options>
Eigen::Matrix< T, 4, 4, 0, 4, 4 > sibr::matFromTranslation (const Eigen::Matrix< T, 3, 1, Options > &vec)
Convert a translation to a rotation matrix.
Matrix4f SIBR_SYSTEM_EXPORT sibr::perspective (float fovRadian, float ratio, float zn, float zf, const ::sibr::Vector2f &p={0.5f, 0.5f})
Generate a perspective matrix.
Matrix4f sibr::perspectiveOffCenter (float left, float right, float bottom, float top, float mynear, float myfar)
Generate an off-center perspective matrix.
Matrix4f sibr::perspectiveStereo (float fovRadian, float aspect, float zn, float zf, float focalDistance, float eyeDistance, bool isLeftEye)
Generate a perspective matrix for stereo rendering.
Matrix4f sibr::orthographic (float right, float top, float mynear, float myfar)
Generate an orthographic matrix.
Matrix4f sibr::lookAt (const Vector3f &eye, const Vector3f &center, const Vector3f &up)
Generate a view matrix using the look at parameters.
void sibr::operator<< (std::ofstream &outfile, const Matrix4f &m)
Output a Matrix4f to a file stream.
void sibr::operator>> (std::ifstream &infile, Matrix4f &out)
Read a Matrix4f from a file stream.
template<typename T , int Options>
Eigen::Quaternion< T, 0 > sibr::quatFromMatrix (const Eigen::Matrix< T, 3, 3, Options, 3, 3 > &m)
Build a quaternion from a rotation matrix.
template<typename T , int Options>
Eigen::Quaternion< T, 0 > sibr::quatFromMatrix (const Eigen::Matrix< T, 4, 4, Options, 4, 4 > &m)
Build a quaternion from a rotation matrix.
template<typename T , int Options>
Eigen::Quaternion< T, 0 > sibr::quatFromEulerAngles (const Eigen::Matrix< T, 3, 1, Options > &deg)
Build a quaternion from rotation euler angles.
template<typename T , int Options>
Eigen::Matrix< T, 3, 1, Options > sibr::quatRotateVec (const Eigen::Quaternion< T, 0 > &rotation, const Eigen::Matrix< T, 3, 1, Options > &vec)
Rotate a vector using a quaternion.
template<typename T >
static Eigen::Quaternion< T > sibr::dot (const Eigen::Quaternion< T > &q1, const Eigen::Quaternion< T > &q2)
Quaternion product.
template<typename T >
static float sibr::angleRadian (const Eigen::Quaternion< T > &q1, const Eigen::Quaternion< T > &q2)
Compute the delta angle between two quaternions.
template<typename T >
static Eigen::Quaternion< T > sibr::lerp (const Eigen::Quaternion< T > &q1, const Eigen::Quaternion< T > &q2, float t)
Linear quaternion interpolation.
template<typename T >
static Eigen::Quaternion< T > sibr::slerp (const Eigen::Quaternion< T > &q1, const Eigen::Quaternion< T > &q2, float t)
Spherical quaternion interpolation.
std::string sibr::strSearchAndReplace (const std::string &src, const std::string &search, const std::string &replaceby)
Replaces all occurences of a substring with another substring.
std::string sibr::removeExtension (const std::string &str)
Process a string (a filename or path) to remove any extension if it exists.
std::string sibr::getExtension (const std::string &str)
Process a string (a filename or path) to extract the file extension if it exists.
std::string sibr::parentDirectory (const std::string &str)
Process a string (a path) to return the parent directory.
SIBR_SYSTEM_EXPORT std::string sibr::getFileName (const std::string &str)
Process a string (a path) to return the file name.
bool sibr::strContainsOnlyDigits (const std::string &str)
Check if a string only contains digits.
std::vector< std::string > sibr::split (const std::string &str, char delim='\n')
Split string into sub-strings delimited by a given character.
std::string sibr::sprint (const char *msg,...)
Wrapper around sibr::sprintf that returns a string.
int sibr::sprintf (char *buffer, size_t size, const char *format,...)
Write a formatted string with inserted values to a buffer.
SIBR_SYSTEM_EXPORT std::string sibr::to_lower (const std::string &str)
Convert the input string to lowert case.
SIBR_SYSTEM_EXPORT bool sibr::find_any (const std::vector< std::string > &needles, const std::string &haystack)
Find if a list of substring is present in a given string.
std::string sibr::timestamp (const std::string &format="%Y_%m_%d_%H_%M_%S")
Write the current timestamp to a string.
template<typename T >
ByteStream & sibr::operator<< (ByteStream &stream, const Transform3< T > &t)
Write transformation to a byte stream.
template<typename T >
ByteStream & sibr::operator>> (ByteStream &stream, Transform3< T > &t)
Read transformation from a byte stream.
std::string sibr::loadFile (const std::string &filename)
Load the whole file into a std::string.
void sibr::makeDirectory (const std::string &path)
Create directory (if it doesn't exist already)
std::vector< std::string > sibr::listFiles (const std::string &path, const bool listHidden=false, const bool includeSubdirectories=false, const std::vector< std::string > &allowedExtensions={})
List content of directory, sorted alphabetically.
std::vector< std::string > sibr::listSubdirectories (const std::string &path, const bool listHidden=false)
List content of directory, sorted alphabetically, including subdirectories.
bool sibr::copyDirectory (const std::string &src, const std::string &dst)
Copy directory.
bool sibr::copyFile (const std::string &src, const std::string &dst, const bool overwrite=false)
Copy file.
void sibr::emptyDirectory (const std::string &path)
Empty a directory (if it exist already)
bool sibr::fileExists (const std::string &path)
Test if a file exists.
bool sibr::directoryExists (const std::string &path)
Test if a directory exists.
size_t sibr::getAvailableMem ()
SIBR_SYSTEM_EXPORT std::string sibr::getInstallDirectory ()
SIBR_SYSTEM_EXPORT std::string sibr::getBinDirectory ()
SIBR_SYSTEM_EXPORT std::string sibr::getShadersDirectory (const std::string &subfolder)
SIBR_SYSTEM_EXPORT std::string sibr::getScriptsDirectory ()
SIBR_SYSTEM_EXPORT std::string sibr::getResourcesDirectory ()
SIBR_SYSTEM_EXPORT std::string sibr::getAppDataDirectory ()
SIBR_SYSTEM_EXPORT std::string sibr::getInstallSubDirectory (const std::string &subfolder)
bool sibr::showFilePicker (std::string &selectedElement, const FilePickerMode mode, const std::string &directoryPath="", const std::string &extensionsAllowed="")
Present a native OS file picker.
template<typename FunType , typename ... ArgsType>
void sibr::taskTiming (const std::string &s, FunType &&f, ArgsType &&... args)
Measure and print the timing of a task.
template<typename T , int N, int Options>
bool Eigen::operator< (const Eigen::Matrix< T, N, 1, Options > &left, const Eigen::Matrix< T, N, 1, Options > &right)
Lexicographic comparison (from left to right).
template<typename T , int N, int Options>
std::ostream & Eigen::operator<< (std::ostream &s, const Eigen::Matrix< T, N, 1, Options > &t)
Output matrix to a stream.
template<typename T , int N, int Options>
std::istream & Eigen::operator>> (std::istream &s, Eigen::Matrix< T, N, 1, Options > &t)
Read matrix from a stream.
template<typename T , int N, int Options>
Eigen::Matrix< T, N, 1, Options > sibr::frac (const Eigen::Matrix< T, N, 1, Options > &A)
Fractional part of each component.
template<typename T , int N, int Options>
T sibr::distance (const Eigen::Matrix< T, N, 1, Options > &A, const Eigen::Matrix< T, N, 1, Options > &B)
Distance between two vectors.
template<typename T , int N, int Options>
T sibr::length (const Eigen::Matrix< T, N, 1, Options > &A)
Return the length of a vector.
template<typename T , int N, int Options>
T sibr::sqLength (const Eigen::Matrix< T, N, 1, Options > &A)
Return the squared length of a vector.
template<typename T , int N, int Options>
T sibr::dot (const Eigen::Matrix< T, N, 1, Options > &A, const Eigen::Matrix< T, N, 1, Options > &B)
Compute the dot product of two vectors.
template<typename T , int N, int Options>
Eigen::Matrix< T, N, 1, Options > sibr::cross (const Eigen::Matrix< T, N, 1, Options > &A, const Eigen::Matrix< T, N, 1, Options > &B)
Compute the cross product of two vectors.
template<typename T , int N>
Vector< T, N > sibr::clamp (const Vector< T, N > &A, const Vector< T, N > &min, const Vector< T, N > &max)
Clamp each component of a vector between two values.
template<typename T , int N, int Options>
T sibr::cotan (const Eigen::Matrix< T, N, 1, Options > &A, const Eigen::Matrix< T, N, 1, Options > &B)
Compute the cotangent of the angle between two vectors.
SIBR_SYSTEM_EXPORT Eigen::Matrix< float, 3, 1, Eigen::DontAlign > sibr::toColorFloat (Vector< unsigned char, 3 > &colorUB)
Convert an unsigned char color in [0,255] to a float color in [0,1].
SIBR_SYSTEM_EXPORT Eigen::Matrix< unsigned char, 3, 1, Eigen::DontAlign > sibr::toColorUB (Vector< float, 3 > &colorFloat)
Convert a float color in [0,1] to an unsigned char color in [0,255].
Eigen::Matrix< float, 4, 4, Eigen::DontAlign > sibr::alignRotationMatrix (const sibr::Vector3f &from, const sibr::Vector3f &to)
Return a 4x4 3D rotation matrix that aligns the first vector onto the second one.
template<typename T_in , typename T_out = T_in>
T_out sibr::sum (const std::vector< T_in > &vec, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Sum elements from a vector.
template<typename T_in , typename T_out = T_in>
std::vector< T_out > sibr::weighted_normalization (const std::vector< T_in > &vec, const std::vector< T_in > &weights, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Weighted sum of elements in a vector.
template<typename T_in , typename T_out = T_in>
std::vector< T_out > sibr::applyLambda (const std::vector< T_in > &vec, const std::function< T_out(T_in)> &f)
Apply a function to each element of a vector (not in place)
template<typename T_in , typename T_out >
std::vector< T_out > sibr::applyLambda (const std::vector< T_in > &vec1, const std::vector< T_in > &vec2, const std::function< T_out(T_in, T_in)> &f)
Apply a function to each pair of elements from two vectors of same size (not in place).
template<typename T_in , typename T_out = T_in>
T_out sibr::var (const std::vector< T_in > &vec, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Compute the variance of elements in a vector.
template<typename T_in , typename T_out = T_in>
std::vector< T_out > sibr::normalizedMinMax (const std::vector< T_in > &vec, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Normalize all elements in a vector based on the min and max values in it (not in place).
template<typename T_in , typename T_out = T_in, unsigned int Power = 2>
std::vector< T_out > sibr::normalizedZeroOne (const std::vector< T_in > &vec, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Apply a power-sum normalization.
sibr::MultiVector< T, N >::MultiVector ()
Constructor.
sibr::MultiVector< T, N >::MultiVector (int n, const T &t=T())
Constructor.
sibr::MultiVector< T, N >::MultiVector (const std::vector< int > &dims, const T &t=T())
Constructor.
T & sibr::MultiVector< T, N >::multiAt (const std::vector< int > &ids)
Getter.
const T & sibr::MultiVector< T, N >::multiAt (const std::vector< int > &ids) const
Getter.
std::vector< int > sibr::MultiVector< T, N >::dims () const
Get the size along each dimension.
void sibr::MultiVector< T, N >::dimsDisplay () const
Print the size along each dimension.
void sibr::MultiVector< T, N >::dimsRecur (std::vector< int > &v) const
Helper to get the dimensions.
sibr::MultiVector< T, 1 >::MultiVector ()
Constructor.
sibr::MultiVector< T, 1 >::MultiVector (int n, const T &t=T())
Constructor.
sibr::MultiVector< T, 1 >::MultiVector (const std::vector< int > &dims, const T &t=T())
Constructor.
T & sibr::MultiVector< T, 1 >::multiAt (const std::vector< int > &ids)
Getter.
const T & sibr::MultiVector< T, 1 >::multiAt (const std::vector< int > &ids) const
Getter.
void sibr::MultiVector< T, 1 >::dimsDisplay () const
Print the size along each dimension.
void sibr::MultiVector< T, 1 >::dimsRecur (std::vector< int > &v) const
Helper to get the dimensions.
Variables
template<typename T >
constexpr uint sibr::NumberOfArg = 1
uint contexpr helper, defining the number of command line tokens required to init T
template<>
constexpr uint sibr::NumberOfArg< bool > = 0
uint contexpr helper, defining the number of command line tokens required to init T
template<>
constexpr uint sibr::NumberOfArg< Switch > = 0
uint contexpr helper, defining the number of command line tokens required to init T
Friends
class sibr::MultiVector< T, N >::MultiVector< T, N+1 >
class sibr::MultiVector< T, 1 >::MultiVector< T, 2 >
Detailed Description
System utilities.
Typedef Documentation
Matrix3d
typedef Eigen::Matrix<double, 3, 3, Eigen::DontAlign, 3, 3> sibr::Matrix3d
Definition at line 54 of file Matrix.hpp.
Matrix3f
typedef Eigen::Matrix<float, 3, 3, Eigen::DontAlign, 3, 3> sibr::Matrix3f
Definition at line 53 of file Matrix.hpp.
Matrix3i
typedef Eigen::Matrix<int, 3, 3, Eigen::DontAlign, 3, 3> sibr::Matrix3i
Definition at line 52 of file Matrix.hpp.
Matrix3u
typedef Eigen::Matrix<unsigned, 3, 3, Eigen::DontAlign, 3, 3> sibr::Matrix3u
Definition at line 51 of file Matrix.hpp.
Matrix4d
typedef Eigen::Matrix<double, 4, 4, Eigen::DontAlign, 4, 4> sibr::Matrix4d
Definition at line 50 of file Matrix.hpp.
Matrix4f
typedef Eigen::Matrix<float, 4, 4, Eigen::DontAlign, 4, 4> sibr::Matrix4f
Definition at line 49 of file Matrix.hpp.
Matrix4i
typedef Eigen::Matrix<int, 4, 4, Eigen::DontAlign, 4, 4> sibr::Matrix4i
Definition at line 48 of file Matrix.hpp.
Matrix4u
typedef Eigen::Matrix<unsigned, 4, 4, Eigen::DontAlign, 4, 4> sibr::Matrix4u
Definition at line 47 of file Matrix.hpp.
Quaterniond
typedef Eigen::Quaternion<double> sibr::Quaterniond
Definition at line 213 of file Quaternion.hpp.
Quaternionf
typedef Eigen::Quaternion<float> sibr::Quaternionf
Definition at line 212 of file Quaternion.hpp.
Quaternioni
typedef Eigen::Quaternion<int> sibr::Quaternioni
Definition at line 211 of file Quaternion.hpp.
Quaternionu
typedef Eigen::Quaternion<unsigned> sibr::Quaternionu
Definition at line 210 of file Quaternion.hpp.
SubVector
template<typename T , unsigned int N> typedef MultiVector<T, N - 1> sibr::MultiVector< T, N >::SubVector private
Definition at line 206 of file VectorUtils.hpp.
Vector
template<typename T , int N> using sibr::Vector = typedef Eigen::Matrix<T, N, 1, Eigen::DontAlign>
Definition at line 80 of file Vector.hpp.
Vector1f
typedef Eigen::Matrix<float, 1, 1,Eigen::DontAlign> sibr::Vector1f
Definition at line 177 of file Vector.hpp.
Vector1i
typedef Eigen::Matrix<int, 1, 1,Eigen::DontAlign> sibr::Vector1i
Definition at line 178 of file Vector.hpp.
Vector2d
typedef Eigen::Matrix<double, 2, 1,Eigen::DontAlign> sibr::Vector2d
Definition at line 184 of file Vector.hpp.
Vector2f
typedef Eigen::Matrix<float, 2, 1,Eigen::DontAlign> sibr::Vector2f
Definition at line 183 of file Vector.hpp.
Vector2i
typedef Eigen::Matrix<int, 2, 1,Eigen::DontAlign> sibr::Vector2i
Definition at line 182 of file Vector.hpp.
Vector2u
typedef Eigen::Matrix<unsigned, 2, 1,Eigen::DontAlign> sibr::Vector2u
Definition at line 180 of file Vector.hpp.
Vector2ub
typedef Eigen::Matrix<unsigned char, 2, 1,Eigen::DontAlign> sibr::Vector2ub
Definition at line 181 of file Vector.hpp.
Vector3d
typedef Eigen::Matrix<double, 3, 1,Eigen::DontAlign> sibr::Vector3d
Definition at line 191 of file Vector.hpp.
Vector3f
typedef Eigen::Matrix<float, 3, 1,Eigen::DontAlign> sibr::Vector3f
Definition at line 190 of file Vector.hpp.
Vector3i
typedef Eigen::Matrix<int, 3, 1,Eigen::DontAlign> sibr::Vector3i
Definition at line 189 of file Vector.hpp.
Vector3s
typedef Eigen::Matrix<unsigned short int, 3, 1,Eigen::DontAlign> sibr::Vector3s
Definition at line 188 of file Vector.hpp.
Vector3u
typedef Eigen::Matrix<unsigned, 3, 1,Eigen::DontAlign> sibr::Vector3u
Definition at line 186 of file Vector.hpp.
Vector3ub
typedef Eigen::Matrix<unsigned char, 3, 1,Eigen::DontAlign> sibr::Vector3ub
Definition at line 187 of file Vector.hpp.
Vector4d
typedef Eigen::Matrix<double, 4, 1,Eigen::DontAlign> sibr::Vector4d
Definition at line 197 of file Vector.hpp.
Vector4f
typedef Eigen::Matrix<float, 4, 1,Eigen::DontAlign> sibr::Vector4f
Definition at line 196 of file Vector.hpp.
Vector4i
typedef Eigen::Matrix<int, 4, 1,Eigen::DontAlign> sibr::Vector4i
Definition at line 195 of file Vector.hpp.
Vector4u
typedef Eigen::Matrix<unsigned, 4, 1,Eigen::DontAlign> sibr::Vector4u
Definition at line 193 of file Vector.hpp.
Vector4ub
typedef Eigen::Matrix<unsigned char, 4, 1,Eigen::DontAlign> sibr::Vector4ub
Definition at line 194 of file Vector.hpp.
Enumeration Type Documentation
FilePickerMode
enum sibr::FilePickerMode
Selection mode for the file picker.
Enumerator
Default
Save
Directory
Definition at line 115 of file Utils.hpp.
RenderingModes
enum sibr::RenderingModes
Available rendering modes for IBR views.
Enumerator
RENDERMODE_MONO
RENDERMODE_STEREO_ANAGLYPH
RENDERMODE_STEREO_QUADBUFFER
Definition at line 51 of file CommandLineArgs.hpp.
Function Documentation
alignRotationMatrix()
SIBR_SYSTEM_EXPORT Eigen::Matrix< float, 4, 4, Eigen::DontAlign > sibr::alignRotationMatrix (const sibr::Vector3f & from, const sibr::Vector3f & to)
Return a 4x4 3D rotation matrix that aligns the first vector onto the second one.
Parameters
from source vector, current direction
to destination vector, target direction
Returns
the rotation matrix
Definition at line 16 of file Vector.cpp.
References sibr::Key::R.
angleRadian()
template<typename T > static float sibr::angleRadian (const Eigen::Quaternion< T > & q1, const Eigen::Quaternion< T > & q2) inline static
Compute the delta angle between two quaternions.
Parameters
q1 first quaternion
q2 second quaternion
Returns
the angle in radians
Note
Will return the smallest angle possible
Definition at line 167 of file Quaternion.hpp.
Referenced by sibr::IBRBasicUtils::selectCamerasAngleWeight().
applyLambda() [1/2]
template<typename T_in , typename T_out = T_in> std::vector<T_out> sibr::applyLambda (const std::vector< T_in > & vec, const std::function< T_out(T_in)> & f)
Apply a function to each element of a vector (not in place)
Parameters
vec vector
f function to apply
Returns
vector containing the processed results
Definition at line 69 of file VectorUtils.hpp.
applyLambda() [2/2]
template<typename T_in , typename T_out > std::vector<T_out> sibr::applyLambda (const std::vector< T_in > & vec1, const std::vector< T_in > & vec2, const std::function< T_out(T_in, T_in)> & f)
Apply a function to each pair of elements from two vectors of same size (not in place).
Parameters
vec1 first vector
vec2 second vector
f function to apply
Returns
vector containing the processed results
Definition at line 86 of file VectorUtils.hpp.
clamp()
template<typename T , int N> Vector<T,N> sibr::clamp (const Vector< T, N > & A, const Vector< T, N > & min, const Vector< T, N > & max) inline
Clamp each component of a vector between two values.
Parameters
A vector
min min values vector
max max values vector
Returns
min(max(A, min), max)
Definition at line 149 of file Vector.hpp.
References sibr::Key::A.
copyDirectory()
SIBR_SYSTEM_EXPORT bool sibr::copyDirectory (const std::string & src, const std::string & dst)
Copy directory.
Parameters
src source path
dst destination path
Returns
success boolean
Definition at line 165 of file Utils.cpp.
References ibr_preprocess_rc_to_sibr::dst, and ibr_preprocess_rc_to_sibr::src.
copyFile()
SIBR_SYSTEM_EXPORT bool sibr::copyFile (const std::string & src, const std::string & dst, const bool overwrite = false)
Copy file.
Parameters
src source path
dst destination path
overwrite if the file already exists, should it be overwritten
Returns
success boolean
Definition at line 232 of file Utils.cpp.
References ibr_preprocess_rc_to_sibr::dst, and ibr_preprocess_rc_to_sibr::src.
Referenced by main().
cotan()
template<typename T , int N, int Options> T sibr::cotan (const Eigen::Matrix< T, N, 1, Options > & A, const Eigen::Matrix< T, N, 1, Options > & B) inline
Compute the cotangent of the angle between two vectors.
Parameters
A first vector
B second vector
Returns
the cotangent
Definition at line 159 of file Vector.hpp.
References sibr::Key::A, and sibr::Key::B.
cross()
template<typename T , int N, int Options> Eigen::Matrix<T, N, 1, Options> sibr::cross (const Eigen::Matrix< T, N, 1, Options > & A, const Eigen::Matrix< T, N, 1, Options > & B) inline
Compute the cross product of two vectors.
Parameters
A first vector
B second vector
Returns
AxB
Definition at line 138 of file Vector.hpp.
References sibr::Key::A, and sibr::Key::B.
Referenced by sibr::CameraRaycaster::computePixelDerivatives(), sibr::Mesh::getBoundingSphere(), and PlaneEstimator::plane3Pts().
dims()
template<typename T , unsigned int N> std::vector<int> sibr::MultiVector< T, N >::dims () const inline
Get the size along each dimension.
Returns
the N-d size
Definition at line 246 of file VectorUtils.hpp.
Referenced by sibr::MultiVector< T, N - 1 >::dimsDisplay().
dimsDisplay() [1/2]
template<typename T , unsigned int N> void sibr::MultiVector< T, N >::dimsDisplay () const inline
Print the size along each dimension.
Definition at line 255 of file VectorUtils.hpp.
dimsDisplay() [2/2]
template<typename T > void sibr::MultiVector< T, 1 >::dimsDisplay () const inline
Print the size along each dimension.
Definition at line 321 of file VectorUtils.hpp.
dimsRecur() [1/2]
template<typename T , unsigned int N> void sibr::MultiVector< T, N >::dimsRecur (std::vector< int > & v) const inline protected
Helper to get the dimensions.
Parameters
v will contain the size along each axis
Definition at line 269 of file VectorUtils.hpp.
Referenced by sibr::MultiVector< T, N - 1 >::dims().
dimsRecur() [2/2]
template<typename T > void sibr::MultiVector< T, 1 >::dimsRecur (std::vector< int > & v) const inline protected
Helper to get the dimensions.
Parameters
v will contain the size along each axis
Definition at line 330 of file VectorUtils.hpp.
directoryExists()
SIBR_SYSTEM_EXPORT bool sibr::directoryExists (const std::string & path)
Test if a directory exists.
Parameters
path the directory path
Returns
true if directory exists
Definition at line 288 of file Utils.cpp.
Referenced by sibr::getInstallDirectory(), sibr::getInstallSubDirectory(), sibr::ParseData::getParsedData(), sibr::listFiles(), sibr::listSubdirectories(), sibr::Skybox::load(), main(), sibr::CameraRecorder::recordOfflinePath(), and sibr::SceneDebugView::SceneDebugView().
distance()
template<typename T , int N, int Options> T sibr::distance (const Eigen::Matrix< T, N, 1, Options > & A, const Eigen::Matrix< T, N, 1, Options > & B) inline
Distance between two vectors.
Parameters
A first vector
B second vector
Returns
norm(A-B)
Definition at line 100 of file Vector.hpp.
References sibr::Key::A, and sibr::Key::B.
Referenced by sibr::MaterialMesh::ambientOcclusion(), sibr::ULRV2View::chosen_cameras(), sibr::ULRView::chosen_cameras(), sibr::ULRV2View::computeVisibilityMap(), sibr::Mesh::getBoundingSphere(), sibr::IBRBasicUtils::selectCamerasSimpleDist(), sibr::FPSCamera::snap(), sibr::MaterialMesh::subdivideMesh(), sibr::MaterialMesh::subdivideMesh2(), and sibr::Frustum::testSphere().
dot() [1/2]
template<typename T , int N, int Options> T sibr::dot (const Eigen::Matrix< T, N, 1, Options > & A, const Eigen::Matrix< T, N, 1, Options > & B) inline
Compute the dot product of two vectors.
Parameters
A first vector
B second vector
Returns
A.B
Definition at line 128 of file Vector.hpp.
References sibr::Key::A, and sibr::Key::B.
dot() [2/2]
template<typename T > static Eigen::Quaternion<T> sibr::dot (const Eigen::Quaternion< T > & q1, const Eigen::Quaternion< T > & q2) inline static
Quaternion product.
Parameters
q1 first quaternion
q2 second quaternion
Returns
the result quaternion
Definition at line 156 of file Quaternion.hpp.
Referenced by sibr::Mesh::adaptativeTaubinSmoothing(), sibr::ULRV2View::chosen_cameras(), sibr::ULRView::chosen_cameras(), sibr::ULRV2View::chosen_cameras_angdist(), PlaneEstimator::estimateGroundPlane(), PlaneEstimator::getMeshPlane(), sibr::RaycastingCamera::isInsideFrustum(), sibr::RaycastingCamera::projectImg_outside_frustum_correction(), sibr::IBRBasicUtils::selectCamerasAngleWeight(), sibr::IBRBasicUtils::selectCamerasSimpleDist(), and sibr::slerp().
emptyDirectory()
SIBR_SYSTEM_EXPORT void sibr::emptyDirectory (const std::string & path)
Empty a directory (if it exist already)
Parameters
path the directory path
Definition at line 275 of file Utils.cpp.
fileExists()
SIBR_SYSTEM_EXPORT bool sibr::fileExists (const std::string & path)
Test if a file exists.
Parameters
path the file path
Returns
true if file exists
Definition at line 282 of file Utils.cpp.
Referenced by sibr::BasicIBRScene::createFromData(), sibr::Video::exists(), sibr::ParseData::getParsedBundlerData(), sibr::ParseData::getParsedColmapData(), sibr::ParseData::getParsedData(), sibr::ParseData::getParsedNVMData(), isRawRC(), sibr::Mesh::load(), sibr::CameraRecorder::loadPath(), sibr::CropScaleImageUtility::logExecution(), main(), and sibr::Window::setup().
find_any()
SIBR_SYSTEM_EXPORT bool sibr::find_any (const std::vector< std::string > & needles, const std::string & haystack)
Find if a list of substring is present in a given string.
Parameters
needles the list of substring
haystack the search string
Returns
true if any substring is present in the search string, else false
Definition at line 125 of file String.cpp.
Referenced by sibr::ParseData::getParsedColmapData().
frac()
template<typename T , int N, int Options> Eigen::Matrix<T, N, 1, Options> sibr::frac (const Eigen::Matrix< T, N, 1, Options > & A)
Fractional part of each component.
Parameters
A vector
Returns
the fractional matrix
Definition at line 87 of file Vector.hpp.
References sibr::Key::A, and sibr::Key::N.
Referenced by sibr::MultiViewInterface::pixFromScreenPos(), sibr::GridMapping::pixFromScreenPos(), and sibr::VoxelGridBase::rayMarch().
getAppDataDirectory()
SIBR_SYSTEM_EXPORT std::string sibr::getAppDataDirectory ()
Returns
the user specific application directory
Definition at line 344 of file Utils.cpp.
References sibr::makeDirectory(), and SIBR_ERR.
Referenced by sibr::Window::setup().
getAvailableMem()
SIBR_SYSTEM_EXPORT size_t sibr::getAvailableMem ()
Returns
the available memory on windows system in Ko
Definition at line 294 of file Utils.cpp.
References DIV.
getBinDirectory()
SIBR_SYSTEM_EXPORT std::string sibr::getBinDirectory ()
Returns
the binary directory on windows system
Definition at line 324 of file Utils.cpp.
References sibr::getInstallSubDirectory().
getCommandLineArgs()
SIBR_SYSTEM_EXPORT const CommandLineArgs & sibr::getCommandLineArgs ()
Getter for the command line args manager singleton.
Definition at line 10 of file CommandLineArgs.cpp.
References sibr::CommandLineArgs::getGlobal().
Referenced by sibr::AppArgs::displayHelpIfRequired().
getExtension()
SIBR_SYSTEM_EXPORT std::string sibr::getExtension (const std::string & str)
Process a string (a filename or path) to extract the file extension if it exists.
Parameters
str the string to get the extension from
Returns
the extension string (without the leading dot)
Definition at line 26 of file String.cpp.
Referenced by sibr::IImage::imageResolution(), main(), and sibr::Mesh::save().
getFileName()
SIBR_SYSTEM_EXPORT std::string sibr::getFileName (const std::string & str)
Process a string (a path) to return the file name.
Parameters
str the string to process
Returns
the string with all but the last component removed
Note
Will return the full string if no separator was found.
Definition at line 51 of file String.cpp.
Referenced by main().
getInstallDirectory()
SIBR_SYSTEM_EXPORT std::string sibr::getInstallDirectory ()
Returns
the binary directory on windows system
Definition at line 309 of file Utils.cpp.
References sibr::directoryExists(), sibr::parentDirectory(), and SIBR_ERR.
Referenced by sibr::getInstallSubDirectory(), sibr::Resources::getResourceFilePathName(), and sibr::Resources::Resources().
getInstallSubDirectory()
SIBR_SYSTEM_EXPORT std::string sibr::getInstallSubDirectory (const std::string & subfolder)
Parameters
subfolder the subfolder to get
Returns
the provided subfolder path on windows system
Definition at line 378 of file Utils.cpp.
References sibr::directoryExists(), sibr::getInstallDirectory(), and SIBR_ERR.
Referenced by sibr::getBinDirectory(), sibr::getResourcesDirectory(), sibr::getScriptsDirectory(), and sibr::getShadersDirectory().
getResourcesDirectory()
SIBR_SYSTEM_EXPORT std::string sibr::getResourcesDirectory ()
Returns
the resources directory on windows system
Definition at line 339 of file Utils.cpp.
References sibr::getInstallSubDirectory().
Referenced by main(), and sibr::Window::setup().
getScriptsDirectory()
SIBR_SYSTEM_EXPORT std::string sibr::getScriptsDirectory ()
Returns
the scripts directory on windows system
Definition at line 334 of file Utils.cpp.
References sibr::getInstallSubDirectory().
getShadersDirectory()
SIBR_SYSTEM_EXPORT std::string sibr::getShadersDirectory (const std::string & subfolder = "")
Parameters
subfolder optional subfolder for subproject
Returns
the binary directory on windows system
Definition at line 329 of file Utils.cpp.
References sibr::getInstallSubDirectory().
Referenced by sibr::AddShadowRenderer::AddShadowRenderer(), sibr::BlurRenderer::BlurRenderer(), sibr::ColoredMeshRenderer::ColoredMeshRenderer(), sibr::ImageView::ImageView(), sibr::MultiMeshManager::initShaders(), sibr::PoissonRenderer::PoissonRenderer(), sibr::ULRV3Renderer::setupShaders(), sibr::ULRV2Renderer::setupULRshader(), sibr::TexturedMeshRenderer::TexturedMeshRenderer(), sibr::ULRRenderer::ULRRenderer(), and sibr::RenderMaskHolder::uploadMaskGPU().
length()
template<typename T , int N, int Options> T sibr::length (const Eigen::Matrix< T, N, 1, Options > & A) inline
Return the length of a vector.
Parameters
A vector
Returns
norm(A)
Definition at line 109 of file Vector.hpp.
References sibr::Key::A.
Referenced by sibr::GLShader::getBinary(), sibr::laplacianPyramidTemporalDouble(), sibr::loadFile(), sibr::optimal_num_levels(), sibr::RayHit::RayHit(), and sibr::Mesh::subDivide().
lerp()
template<typename T > static Eigen::Quaternion<T> sibr::lerp (const Eigen::Quaternion< T > & q1, const Eigen::Quaternion< T > & q2, float t) inline static
Linear quaternion interpolation.
Parameters
q1 first quaternion
q2 second quaternion
t interpolation factor
Returns
the interpolated quaternion
Definition at line 180 of file Quaternion.hpp.
listFiles()
SIBR_SYSTEM_EXPORT std::vector< std::string > sibr::listFiles (const std::string & path, const bool listHidden = false, const bool includeSubdirectories = false, const std::vector< std::string > & allowedExtensions = {})
List content of directory, sorted alphabetically.
Parameters
path directory path
listHidden should hidden files be listed
includeSubdirectories should subdirectories be explored
allowedExtensions a list of allowed extensions to filter the list with (for instance {"png", "bmp"})
Returns
a list of file names/subpaths
Note
To get each element full path, use path + "/" + itemPath
Definition at line 89 of file Utils.cpp.
References sibr::directoryExists().
Referenced by main().
listSubdirectories()
SIBR_SYSTEM_EXPORT std::vector< std::string > sibr::listSubdirectories (const std::string & path, const bool listHidden = false)
List content of directory, sorted alphabetically, including subdirectories.
Parameters
path directory path
listHidden should hidden directories be listed
Returns
a list of directory names/subpaths
Note
To get each element full path, use path + "/" + itemPath
Definition at line 134 of file Utils.cpp.
References sibr::directoryExists().
Referenced by sibr::ParseData::getParsedMeshroomData().
loadFile()
SIBR_SYSTEM_EXPORT std::string sibr::loadFile (const std::string & filename)
Load the whole file into a std::string.
Parameters
filename the file path
Returns
the loaded content
Definition at line 63 of file Utils.cpp.
References sibr::length(), and SIBR_ERR.
lookAt()
Matrix4f SIBR_SYSTEM_EXPORT sibr::lookAt (const Vector3f & eye, const Vector3f & center, const Vector3f & up)
Generate a view matrix using the look at parameters.
Parameters
eye camera position
center point the camera is looking at
up up vector
Returns
the projection matrix
Definition at line 82 of file Matrix.cpp.
Referenced by sibr::MaterialMesh::loadMtsXML(), and sibr::FPSCamera::snap().
makeDirectory()
SIBR_SYSTEM_EXPORT void sibr::makeDirectory (const std::string & path)
Create directory (if it doesn't exist already)
Parameters
path the directory path
Definition at line 82 of file Utils.cpp.
Referenced by sibr::MultiViewBase::captureView(), sibr::VideoUtils::computeSaveSimpleFlow(), sibr::VideoUtils::computeSaveVideoMaskBlur(), sibr::VideoUtils::computeSaveVideoMaskF(), sibr::getAppDataDirectory(), main(), sibr::InputCamera::saveAsBundle(), sibr::CameraRecorder::saveAsFRIBRBundle(), sibr::VideoVolume< T, N >::saveToVideoFile(), sibr::SceneDebugView::SceneDebugView(), and sibr::MultiViewBase::setExportPath().
matFromQuat()
template<typename T > Eigen::Matrix<T, 4, 4, 0, 4, 4> sibr::matFromQuat (const Eigen::Quaternion< T, 0 > & q)
Convert a quaternion to a rotation matrix.
Parameters
q the quaternion to convert
Returns
the corresponding matrix
Definition at line 61 of file Matrix.hpp.
Referenced by sibr::Transform3< T >::matrix().
matFromTranslation()
template<typename T , int Options> Eigen::Matrix<T, 4, 4, 0, 4, 4> sibr::matFromTranslation (const Eigen::Matrix< T, 3, 1, Options > & vec)
Convert a translation to a rotation matrix.
Parameters
vec the translation to convert
Returns
the corresponding matrix
Definition at line 78 of file Matrix.hpp.
Referenced by sibr::Transform3< T >::matrix().
multiAt() [1/4]
template<typename T , unsigned int N> T& sibr::MultiVector< T, N >::multiAt (const std::vector< int > & ids) inline
Getter.
Parameters
ids N-d coordinates
Returns
a reference to the corresponding value.
Definition at line 231 of file VectorUtils.hpp.
multiAt() [2/4]
template<typename T > T& sibr::MultiVector< T, 1 >::multiAt (const std::vector< int > & ids) inline
Getter.
Parameters
ids N-d coordinates
Returns
a reference to the corresponding value.
Definition at line 307 of file VectorUtils.hpp.
multiAt() [3/4]
template<typename T , unsigned int N> const T& sibr::MultiVector< T, N >::multiAt (const std::vector< int > & ids) const inline
Getter.
Parameters
ids N-d coordinates
Returns
a const reference to the corresponding value.
Definition at line 239 of file VectorUtils.hpp.
multiAt() [4/4]
template<typename T > const T& sibr::MultiVector< T, 1 >::multiAt (const std::vector< int > & ids) const inline
Getter.
Parameters
ids N-d coordinates
Returns
a const reference to the corresponding value.
Definition at line 315 of file VectorUtils.hpp.
MultiVector() [1/6]
template<typename T , unsigned int N> sibr::MultiVector< T, N >::MultiVector () inline
Constructor.
Definition at line 211 of file VectorUtils.hpp.
MultiVector() [2/6]
template<typename T > sibr::MultiVector< T, 1 >::MultiVector () inline
Constructor.
Definition at line 287 of file VectorUtils.hpp.
MultiVector() [3/6]
template<typename T , unsigned int N> sibr::MultiVector< T, N >::MultiVector (const std::vector< int > & dims, const T & t = T()) inline
Constructor.
Parameters
dims number of elements on each axis
t default value
Definition at line 224 of file VectorUtils.hpp.
MultiVector() [4/6]
template<typename T > sibr::MultiVector< T, 1 >::MultiVector (const std::vector< int > & dims, const T & t = T()) inline
Constructor.
Parameters
dims number of elements on each axis (only the last one will be considered here).
t default value
Definition at line 300 of file VectorUtils.hpp.
MultiVector() [5/6]
template<typename T , unsigned int N> sibr::MultiVector< T, N >::MultiVector (int n, const T & t = T()) inline
Constructor.
Parameters
n number of elements on each axis
t default value
Definition at line 217 of file VectorUtils.hpp.
MultiVector() [6/6]
template<typename T > sibr::MultiVector< T, 1 >::MultiVector (int n, const T & t = T()) inline
Constructor.
Parameters
n number of elements
t default value
Definition at line 293 of file VectorUtils.hpp.
normalizedMinMax()
template<typename T_in , typename T_out = T_in> std::vector<T_out> sibr::normalizedMinMax (const std::vector< T_in > & vec, const std::function< bool(T_in)> & f = [](T_in val) { return true; })
Normalize all elements in a vector based on the min and max values in it (not in place).
Parameters
vec vector
f validity function (f(i) == true if the i-th element should be taken into account.
Returns
a vector containing the normalized values
Definition at line 134 of file VectorUtils.hpp.
normalizedZeroOne()
template<typename T_in , typename T_out = T_in, unsigned int Power = 2> std::vector<T_out> sibr::normalizedZeroOne (const std::vector< T_in > & vec, const std::function< bool(T_in)> & f = [](T_in val) { return true; })
Apply a power-sum normalization.
Parameters
vec vector
f validity function (f(i) == true if the i-th element should be taken into account.
Returns
a vector containing the normalized values
Definition at line 168 of file VectorUtils.hpp.
operator<()
template<typename T , int N, int Options> bool Eigen::operator< (const Eigen::Matrix< T, N, 1, Options > & left, const Eigen::Matrix< T, N, 1, Options > & right)
Lexicographic comparison (from left to right).
Parameters
left first element
right second element
Returns
true if left is lexicographically smaller than right.
Definition at line 25 of file Vector.hpp.
References sibr::Key::N.
operator<<() [1/3]
template<typename T > ByteStream& sibr::operator<< (ByteStream & stream, const Transform3< T > & t)
Write transformation to a byte stream.
Parameters
stream the byte stream
t the transform
Returns
the stream for compositing
Definition at line 229 of file Transform3.hpp.
References sibr::Transform3< T >::position(), and sibr::Transform3< T >::rotation().
operator<<() [2/3]
void SIBR_SYSTEM_EXPORT sibr::operator<< (std::ofstream & outfile, const Matrix4f & m)
Output a Matrix4f to a file stream.
Parameters
outfile the output file
m the matrix
Definition at line 101 of file Matrix.cpp.
operator<<() [3/3]
template<typename T , int N, int Options> std::ostream& Eigen::operator<< (std::ostream & s, const Eigen::Matrix< T, N, 1, Options > & t)
Output matrix to a stream.
Parameters
s stream
t matrix
Returns
the stream for chaining
Definition at line 43 of file Vector.hpp.
References sibr::Key::N.
operator>>() [1/3]
template<typename T > ByteStream& sibr::operator>> (ByteStream & stream, Transform3< T > & t)
Read transformation from a byte stream.
Parameters
stream the byte stream
t the transform
Returns
the stream for compositing
Definition at line 244 of file Transform3.hpp.
References sibr::Transform3< T >::position(), and sibr::Transform3< T >::rotation().
operator>>() [2/3]
void SIBR_SYSTEM_EXPORT sibr::operator>> (std::ifstream & infile, Matrix4f & out)
Read a Matrix4f from a file stream.
Parameters
infile the input file
out the matrix
Definition at line 110 of file Matrix.cpp.
operator>>() [3/3]
template<typename T , int N, int Options> std::istream& Eigen::operator>> (std::istream & s, Eigen::Matrix< T, N, 1, Options > & t)
Read matrix from a stream.
Parameters
s stream
t matrix
Returns
the stream for chaining
Definition at line 56 of file Vector.hpp.
References sibr::Key::N.
orthographic()
Matrix4f SIBR_SYSTEM_EXPORT sibr::orthographic (float right, float top, float mynear, float myfar)
Generate an orthographic matrix.
Defined by giving the top/right extent in world units.
Parameters
right right extent
top top extent
mynear near plane
myfar dar plane
Returns
the projection matrix
Definition at line 68 of file Matrix.cpp.
Referenced by sibr::Camera::proj(), and sibr::Camera::setOrthoCam().
parentDirectory()
SIBR_SYSTEM_EXPORT std::string sibr::parentDirectory (const std::string & str)
Process a string (a path) to return the parent directory.
Parameters
str the string to process
Returns
the string with the last component removed
Note
Will return the empty string if no separator was found.
Definition at line 35 of file String.cpp.
Referenced by colmapSave(), sibr::BasicIBRScene::createFromData(), sibr::getInstallDirectory(), sibr::InputCamera::loadBundleFRIBR(), sibr::InputCamera::loadNVM(), sibr::CameraRecorder::loadPath(), main(), and sibr::SceneDebugView::SceneDebugView().
perspective()
Matrix4f SIBR_SYSTEM_EXPORT sibr::perspective (float fovRadian, float ratio, float zn, float zf, const ::sibr::Vector2f & p = {0.5f, 0.5f})
Generate a perspective matrix.
Parameters
fovRadian vertical field of view in radians
ratio aspect ratio
zn near plane
zf far plane
p the principal point, expressed in [0,1]
Returns
the projection matrix
perspectiveOffCenter()
Matrix4f SIBR_SYSTEM_EXPORT sibr::perspectiveOffCenter (float left, float right, float bottom, float top, float mynear, float myfar)
Generate an off-center perspective matrix.
Defined by giving the top/left/right/bottom extent in world units.
Parameters
left left extent
right right extent
bottom bottom extent
top top extent
mynear near plane
myfar dar plane
Returns
the projection matrix
Definition at line 23 of file Matrix.cpp.
Referenced by sibr::perspectiveStereo().
perspectiveStereo()
Matrix4f SIBR_SYSTEM_EXPORT sibr::perspectiveStereo (float fovRadian, float aspect, float zn, float zf, float focalDistance, float eyeDistance, bool isLeftEye)
Generate a perspective matrix for stereo rendering.
Parameters
fovRadian vertical field of view in radians
aspect aspect ratio
zn near plane
zf far plane
focalDistance the focal distance
eyeDistance the inter-eye distance
isLeftEye if true computes the left eye matrix, else the right eye
Returns
the projection matrix
Definition at line 46 of file Matrix.cpp.
References sibr::perspectiveOffCenter().
Referenced by sibr::Camera::setStereoCam().
quatFromEulerAngles()
template<typename T , int Options> Eigen::Quaternion<T, 0> sibr::quatFromEulerAngles (const Eigen::Matrix< T, 3, 1, Options > & deg)
Build a quaternion from rotation euler angles.
Parameters
deg the rotation angles
Returns
the quaternion
Todo:
Explicit the angles order (yaw, pitch, roll?)
Definition at line 115 of file Quaternion.hpp.
References ibr_preprocess_rc_to_sibr::dst, and SIBR_DEGTORAD.
Referenced by sibr::Transform3< T >::rotate(), and sibr::Transform3< T >::rotation().
quatFromMatrix() [1/2]
template<typename T , int Options> Eigen::Quaternion<T, 0> sibr::quatFromMatrix (const Eigen::Matrix< T, 3, 3, Options, 3, 3 > & m)
Build a quaternion from a rotation matrix.
Parameters
m the rotation matrix
Returns
the quaternion
Todo:
Seems to be different from sibr::Quaternion(rotationmatrix)
Definition at line 22 of file Quaternion.hpp.
Referenced by colmapSave(), and sibr::FPSCamera::snap().
quatFromMatrix() [2/2]
template<typename T , int Options> Eigen::Quaternion<T, 0> sibr::quatFromMatrix (const Eigen::Matrix< T, 4, 4, Options, 4, 4 > & m)
Build a quaternion from a rotation matrix.
Parameters
m the rotation matrix
Returns
the quaternion
Definition at line 68 of file Quaternion.hpp.
quatRotateVec()
template<typename T , int Options> Eigen::Matrix<T, 3, 1, Options> sibr::quatRotateVec (const Eigen::Quaternion< T, 0 > & rotation, const Eigen::Matrix< T, 3, 1, Options > & vec)
Rotate a vector using a quaternion.
Parameters
rotation the quaternion
vec the vector
Returns
the rotated vector.
Definition at line 145 of file Quaternion.hpp.
Referenced by sibr::Camera::dir(), sibr::Camera::right(), and sibr::Camera::up().
removeExtension()
SIBR_SYSTEM_EXPORT std::string sibr::removeExtension (const std::string & str)
Process a string (a filename or path) to remove any extension if it exists.
Parameters
str the string to remove the extension from
Returns
the string without extension
Definition at line 21 of file String.cpp.
Referenced by sibr::ProxyMesh::loadFromData(), and main().
round()
float sibr::round (float x) inline
Rounding operation.
Parameters
x the value to round
Returns
the rounded value
Todo:
Compare behaviour with std::round
Definition at line 288 of file Config.hpp.
Referenced by sibr::FFVideoEncoder::init(), main(), sibr::MultiViewManager::onGui(), sibr::FFVideoEncoder::operator<<(), sibr::Window::setup(), and sibr::VoxelGridBase::VoxelGridBase().
showFilePicker()
SIBR_SYSTEM_EXPORT bool sibr::showFilePicker (std::string & selectedElement, const FilePickerMode mode, const std::string & directoryPath = "", const std::string & extensionsAllowed = "")
Present a native OS file picker.
Parameters
selectedElement will contain the path to the element selected by the user if any.
mode the mode to use, pick from Save, Directory, Default.
directoryPath the initial directory to present to the user.
extensionsAllowed a list of file extensions to allow: "obj,ply" for instance.
Returns
true if an element was selected, else false.
Warning
'.' relative path is unsupported for directoryPath.
Definition at line 391 of file Utils.cpp.
References sibr::Directory, sibr::Save, and SIBR_WRG.
Referenced by sibr::MultiMeshManager::list_mesh_onGUI(), sibr::InteractiveCameraHandler::onGUI(), and sibr::MultiViewManager::onGui().
slerp()
template<typename T > static Eigen::Quaternion<T> sibr::slerp (const Eigen::Quaternion< T > & q1, const Eigen::Quaternion< T > & q2, float t) static
Spherical quaternion interpolation.
Parameters
q1 first quaternion
q2 second quaternion
t interpolation factor
Returns
the interpolated quaternion
Definition at line 191 of file Quaternion.hpp.
References sibr::dot(), and sibr::lerp().
split()
SIBR_SYSTEM_EXPORT std::vector< std::string > sibr::split (const std::string & str, char delim = '\n')
Split string into sub-strings delimited by a given character.
Parameters
str the input string
delim the delimiting characters
Returns
a list of split substrings
Definition at line 68 of file String.cpp.
Referenced by sibr::concatVolumesChannels(), sibr::cvSplitChannels(), sibr::VideoUtils::getFlowViz(), sibr::ParseData::getParsedColmapData(), sibr::InputCamera::loadColmap(), sibr::loadFile(), sibr::InputCamera::loadLookat(), sibr::RenderMaskHolder::loadMasks(), sibr::RenderMaskHolderArray::loadMasks(), sibr::MaterialMesh::loadMtsXML(), sibr::ParseData::parseSceneMetadata(), sibr::MultipleVideoDecoder< T, N >::updateGPU(), and sibr::MultipleVideoDecoderArray< T, N >::updateGPU().
sprint()
SIBR_SYSTEM_EXPORT std::string sibr::sprint (const char * msg, ...)
Wrapper around sibr::sprintf that returns a string.
Parameters
msg the string with C placeholders
... the values for each placeholder
Returns
the string with the formatted values inserted
Definition at line 83 of file String.cpp.
References TEMP_STR_SIZE.
Referenced by sibr::ULRV2Renderer::setupULRshader().
sprintf()
SIBR_SYSTEM_EXPORT int sibr::sprintf (char * buffer, size_t size, const char * format, ...)
Write a formatted string with inserted values to a buffer.
Parameters
buffer the destination string
size the size of the format string
format the string with C placeholders
... the values for each placeholder
Returns
a status code similar to sprintf
Definition at line 99 of file String.cpp.
sqLength()
template<typename T , int N, int Options> T sibr::sqLength (const Eigen::Matrix< T, N, 1, Options > & A) inline
Return the squared length of a vector.
Parameters
A vector
Returns
norm(A)^2
Definition at line 118 of file Vector.hpp.
References sibr::Key::A.
strContainsOnlyDigits()
SIBR_SYSTEM_EXPORT bool sibr::strContainsOnlyDigits (const std::string & str)
Check if a string only contains digits.
Parameters
str the string to check
Returns
true if it only contains digits
Definition at line 60 of file String.cpp.
strSearchAndReplace()
SIBR_SYSTEM_EXPORT std::string sibr::strSearchAndReplace (const std::string & src, const std::string & search, const std::string & replaceby)
Replaces all occurences of a substring with another substring.
Parameters
src the string to perform replacements in
search the substring to replace
replaceby the new substring to substitute
Returns
the string with the substitutions performed.
Definition at line 9 of file String.cpp.
References ibr_preprocess_rc_to_sibr::src.
sum()
template<typename T_in , typename T_out = T_in> T_out sibr::sum (const std::vector< T_in > & vec, const std::function< bool(T_in)> & f = [](T_in val) { return true; })
Sum elements from a vector.
Parameters
vec vector
f validity function (f(i) == true if the i-th element should be taken into account.
Returns
the accumulated sum
Definition at line 19 of file VectorUtils.hpp.
Referenced by sibr::VideoUtils::getMeanVariance(), sibr::VideoUtils::getMeanVariance2(), and sibr::Histogram< T, 1 >::normalized_values().
taskTiming()
template<typename FunType , typename ... ArgsType> void sibr::taskTiming (const std::string & s, FunType && f, ArgsType &&... args)
Measure and print the timing of a task.
Parameters
s description
f function to run
args arguments for the function
Definition at line 137 of file Utils.hpp.
timestamp()
SIBR_SYSTEM_EXPORT std::string sibr::timestamp (const std::string & format = "%Y_%m_%d_%H_%M_%S")
Write the current timestamp to a string.
Parameters
format the formatting to use for the timestamp (see default value for an example)
Returns
a string containing the timestamp
Definition at line 136 of file String.cpp.
Referenced by sibr::MultiViewBase::captureView().
to_lower()
SIBR_SYSTEM_EXPORT std::string sibr::to_lower (const std::string & str)
Convert the input string to lowert case.
Parameters
str the input string
Returns
the input string in lower case
Definition at line 113 of file String.cpp.
Referenced by sibr::ParseData::getParsedData(), and sibr::IImage::imageResolution().
toColorFloat()
SIBR_SYSTEM_EXPORT Eigen::Matrix<float, 3, 1, Eigen::DontAlign> sibr::toColorFloat (Vector< unsigned char, 3 > & colorUB)
Convert an unsigned char color in [0,255] to a float color in [0,1].
Parameters
colorUB the color vector
Returns
the [0,1] float vector
toColorUB()
SIBR_SYSTEM_EXPORT Eigen::Matrix<unsigned char, 3,1,Eigen::DontAlign> sibr::toColorUB (Vector< float, 3 > & colorFloat)
Convert a float color in [0,1] to an unsigned char color in [0,255].
Parameters
colorFloat the color vector
Returns
the [0,255] float vector
var()
template<typename T_in , typename T_out = T_in> T_out sibr::var (const std::vector< T_in > & vec, const std::function< bool(T_in)> & f = [](T_in val) { return true; })
Compute the variance of elements in a vector.
Parameters
vec vector
f validity function (f(i) == true if the i-th element should be taken into account.
Returns
the variance
Definition at line 104 of file VectorUtils.hpp.
Referenced by sibr::VideoUtils::getMeanVariance(), and sibr::VideoUtils::getMeanVariance2().
weighted_normalization()
template<typename T_in , typename T_out = T_in> std::vector<T_out> sibr::weighted_normalization (const std::vector< T_in > & vec, const std::vector< T_in > & weights, const std::function< bool(T_in)> & f = [](T_in val) { return true; })
Weighted sum of elements in a vector.
Parameters
vec vector
weights per-element weight
f validity function (f(i) == true if the i-th element should be taken into account.
Returns
the weighted sum
Definition at line 38 of file VectorUtils.hpp.
Variable Documentation
NumberOfArg
template<typename T > constexpr uint sibr::NumberOfArg = 1 constexpr
uint contexpr helper, defining the number of command line tokens required to init T
Definition at line 22 of file CommandLineArgs.hpp.
NumberOfArg< bool >
template<> constexpr uint sibr::NumberOfArg< bool > = 0 constexpr
uint contexpr helper, defining the number of command line tokens required to init T
Definition at line 25 of file CommandLineArgs.hpp.
NumberOfArg< Switch >
template<> constexpr uint sibr::NumberOfArg< Switch > = 0 constexpr
uint contexpr helper, defining the number of command line tokens required to init T
Definition at line 28 of file CommandLineArgs.hpp.
Friends
MultiVector< T, 2 >
template<typename T > friend class MultiVector< T, 2 > friend
Definition at line 269 of file VectorUtils.hpp.
MultiVector< T, N+1 >
template<typename T , unsigned int N> friend class MultiVector< T, N+1 > friend
Definition at line 202 of file VectorUtils.hpp.