SIBR: sibr_assets
sibr_assets
Assets and files utilities.
Namespaces
sibr::LoadingStatus
Loading status for streaming.
Classes
class sibr::ActiveImageFile
Represent a active_images.txt file use to select a subset of a scene images.
class sibr::CameraRecorder
This class handles the recording and replay of a stream of cameras.
class sibr::IFileLoader
General file loading interface.
class sibr::ImageListFile
Represents a list of input images.
class sibr::InputCamera
Input camera parameters.
class sibr::Resources
Singleton used to store a list of plausible path to look for (based on the ibr_resources.ini)
class sibr::UVUnwrapper
Unwraps a mesh onto a plane, generating texture coordinates for each vertex.
Functions
std::string sibr::imageIdToString (int id)
Utility that converts an integer id to a string using the "most used" format.
template<unsigned int N>
std::string sibr::intToString (int id)
Generate a string representation of an integer, padded with zeros.
std::string sibr::getProxyFilename (const std::string &datasetPath)
Get the default path and filename used for the proxy mesh.
Detailed Description
Assets and files utilities.
Function Documentation
getProxyFilename()
std::string sibr::getProxyFilename (const std::string & datasetPath) inline
Get the default path and filename used for the proxy mesh.
Parameters
datasetPath the base path
Returns
the mesh path
Definition at line 64 of file Config.hpp.
imageIdToString()
std::string sibr::imageIdToString (int id) inline
Utility that converts an integer id to a string using the "most used" format.
Parameters
id the id to convert (fi 7)
Returns
the corresponding string (fi "0000007")
Definition at line 39 of file Config.hpp.
Referenced by sibr::InputImages::loadFromPath(), sibr::RenderMaskHolder::loadMasks(), and sibr::RenderMaskHolderArray::loadMasks().
intToString()
template<unsigned int N> std::string sibr::intToString (int id)
Generate a string representation of an integer, padded with zeros.
Parameters
id the integer
Returns
the padded string
Note
The template int value determines the padding count.
Definition at line 51 of file Config.hpp.
References sibr::Key::N.