SIBR: sibr_view
sibr_view
View, camera, high-level rendering utilities.
Classes
class sibr::DatasetView
Visualize and explore a MVS dataset.
class sibr::FPSCamera
Interactive camera that can be moved using WASD keys.
class sibr::FPSCounter
Provde a small GUI panel to display the current framerate, smoothed over multiple frames.
class sibr::IBRBasicUtils
Provide basic IBR utilities.
class sibr::ICameraHandler
Represent an interaction mode (FPS, trackball,...) for a camera controlled by the user, or a combination of multiple modes.
class sibr::InteractiveCameraHandler
The InteractiveCameraHandler gathers various types of camera interactions and allows the user to switch between them, keeping them in sync.
class sibr::MultiViewInterface
This class provides basic rendering utilities for a list of images + a mesh.
struct sibr::UV< space >
class sibr::InterfaceUtilities
class sibr::MeshRenderer
class sibr::MeshViewer
class sibr::ShaderAlphaMVP
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class sibr::ColorMeshShader
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class sibr::PointShader
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class sibr::MeshShadingShader
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class sibr::NormalRenderingShader
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class sibr::MeshData
Helper class containing all information relative to how to render a mesh for debugging purpose in a MultiMeshManager.
class sibr::MultiMeshManager
Provide a view to render and interact with several meshes, useful for debugging purposes for instance.
class sibr::MultiViewBase
MultiViewBase is designed to provide more flexibility and with a multi-windows system in mind.
class sibr::MultiViewManager
A multiview manager is a multi-view system that displays its subviews in an OS window.
class sibr::Orbit
Interactive camera that allow the user to roate around an object using the keypad.
class sibr::IRenderingMode
Rendering mode manages the rendertarget and camera fed to an IBR view.
class sibr::MonoRdrMode
Default rendering mode: monoview, passthrough.
class sibr::StereoAnaglyphRdrMode
Stereo rendering mode: two slightly shifted views are rendered and composited as anaglyphs.
struct sibr::LabelsManager
Helper used to display camera labels on screen.
struct sibr::ImageCamViewer
Helper used to render image planes in front of the camera, for both scenes storing 2D separate images or a texture array.
class sibr::SceneDebugView
Scene viewer for IBR scenes with a proxy, cameras and input images.
class sibr::Skybox
A skybox object for rendering a cubemap texture.
class sibr::TrackBall
Provide a handler to interact using a trackball (based on mouse motions).
class sibr::UIShortcuts
Register and display keyboard shortcuts.
class sibr::ViewBase
Basic view representation.
Enumerations
enum sibr::UVspace { sibr::ZERO_ONE, sibr::MINUS_ONE_ONE, sibr::ONE_ZERO }
Functions
Mesh::Ptr sibr::generateCamFrustum (const InputCamera &cam, float znear=-1, float zfar=-1)
Generate an accurate camera frustum.
Mesh::Ptr sibr::generateCamFrustumColored (const InputCamera &cam, const Vector3f &col, float znear=-1, float zfar=-1)
Generate an accurate camera frustum with a custom color.
Mesh::Ptr sibr::generateCamQuadWithUvs (const InputCamera &cam, float dist)
Generate a quad representing a camera image plane.
Detailed Description
View, camera, high-level rendering utilities.
Enumeration Type Documentation
UVspace
enum sibr::UVspace
Enumerator
ZERO_ONE
MINUS_ONE_ONE
ONE_ZERO
Definition at line 16 of file InterfaceUtils.h.
Function Documentation
generateCamFrustum()
Mesh::Ptr SIBR_VIEW_EXPORT sibr::generateCamFrustum (const InputCamera & cam, float znear = -1, float zfar = -1)
Generate an accurate camera frustum.
Parameters
cam camera to visualize as a stub
znear near value to use for the frustum (if < 0, cam.near() will be used)
zfar far value to use for the frustum (if < 0, cam.far() will be used)
Definition at line 12 of file SceneDebugView.cpp.
References sibr::CameraRaycaster::computeRayDir(), sibr::InputCamera::getImageCorners(), sibr::Camera::position(), sibr::Camera::zfar(), and sibr::Camera::znear().
Referenced by sibr::generateCamFrustumColored(), and sibr::SceneDebugView::onRender().
generateCamFrustumColored()
Mesh::Ptr SIBR_VIEW_EXPORT sibr::generateCamFrustumColored (const InputCamera & cam, const Vector3f & col, float znear = -1, float zfar = -1)
Generate an accurate camera frustum with a custom color.
Parameters
cam camera to visualize as a stub
col the mesh line color
znear near value to use for the frustum (if < 0, cam.near() will be used)
zfar far value to use for the frustum (if < 0, cam.far() will be used)
Definition at line 40 of file SceneDebugView.cpp.
References sibr::generateCamFrustum().
generateCamQuadWithUvs()
Mesh::Ptr SIBR_VIEW_EXPORT sibr::generateCamQuadWithUvs (const InputCamera & cam, float dist)
Generate a quad representing a camera image plane.
Parameters
cam the camera
dist the distance in world space from the camera position to the image plane
Definition at line 48 of file SceneDebugView.cpp.
References sibr::CameraRaycaster::computeRayDir(), sibr::InputCamera::getImageCorners(), and sibr::Camera::position().
Referenced by sibr::ImageCamViewer::renderImage().