SIBR: sibr_graphics
sibr_graphics
OpenGL and graphics utilities.
Namespaces
sibr::opencv
Classes
class sibr::Camera
Represent a basic camera.
class sibr::Frustum
Represent a 3D frustum defined by 6 planes.
class sibr::GPUQuery
Provide a buffered wrapper around an OpenGL query object, avoiding manual synchronization.
class sibr::IImage
Interface virtual class for all the templated image classes.
class sibr::ImagePtr< T_Type, T_NumComp >
Wrapper around an image pointer.
class sibr::Image< T_Type, T_NumComp >
This class is used to store images.
class sibr::Input
Maintain the complete state of user interactions (mouse, keyboard) for a given view or window.
class sibr::MaterialMesh
Store both CPU and GPU data for a geometric mesh.
class sibr::Mesh
Store both CPU and GPU data for a geometric mesh.
class sibr::MeshBufferGL
This class is used to render mesh.
class sibr::IRenderTarget
Rendertarget interface.
class sibr::RenderTarget< T_Type, T_NumComp >
A render target wraps an OpenGL framebuffer, that can have one depth buffer, one stencil buffer, and one or more color attachments.
class sibr::RenderUtility
Helpers for rendering basic debug objects (cameras, simple meshes,...)
class sibr::GLShader
OpenGL shader wrapper.
class sibr::GLParameter
OpenGL shader uniform wrapper.
class sibr::GLuniform< T >
OpenGL shader uniform wrapper with additional update/storage functions.
class sibr::ITexture2D
Interface for a generic GPU 2D texture.
class sibr::Texture2D< T_Type, T_NumComp >
Represent a 2D texture on the GPU, with custom format and type.
class sibr::ITexture2DArray
Interface for a generic GPU 2D array texture.
class sibr::Texture2DArray< T_Type, T_NumComp >
Represent an array of 2D textures on the GPU, with custom format, type and slice count.
class sibr::ITextureCubeMap
Interface for a generic GPU cubemap texture.
class sibr::TextureCubeMap< T_Type, T_NumComp >
Represent a cubemap composed of 6 2D faces on the GPU, with custom format and type.
class sibr::GLType< T >
Helper building the correspondence between a GL type and a C type.
class sibr::GLType< unsigned char >
Helper building the correspondence between a GL type and a C type.
class sibr::GLType< unsigned short >
Helper building the correspondence between a GL type and a C type.
class sibr::GLType< short >
Helper building the correspondence between a GL type and a C type.
class sibr::GLType< float >
Helper building the correspondence between a GL type and a C type.
class sibr::GLType< int >
Helper building the correspondence between a GL type and a C type.
class sibr::GLFormat< T_Type, T_Num >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< unsigned char, 1 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< unsigned char, 2 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< unsigned char, 3 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< unsigned char, 4 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< unsigned short, 1 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< unsigned short, 2 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< unsigned short, 3 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< unsigned short, 4 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< int, 1 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< int, 2 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< int, 3 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< int, 4 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< float, 1 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< float, 2 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< float, 3 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormat< float, 4 >
Helper building the correspondence between a GL format and a C type and number of components.
class sibr::GLFormatCVmat< T_Type, T_Num >
Helper building the correspondence between a GL format and a cv::Mat.
class sibr::GLFormatCVmat< unsigned char, 1 >
Helper building the correspondence between a GL format and a cv::Mat.
class sibr::GLFormatCVmat< unsigned char, 3 >
Helper building the correspondence between a GL format and a cv::Mat.
class sibr::GLFormatCVmat< unsigned char, 4 >
Helper building the correspondence between a GL format and a cv::Mat.
struct sibr::OpenCVdepth< T >
Helper building the correspondence between a GL type and a cv::Mat depth.
struct sibr::OpenCVdepth< uchar >
Helper building the correspondence between a GL type and a cv::Mat depth.
struct sibr::OpenCVdepth< float >
Helper building the correspondence between a GL type and a cv::Mat depth.
struct sibr::OpenCVdepth< double >
Helper building the correspondence between a GL type and a cv::Mat depth.
struct sibr::ValidGLTexFormat< ImageType >
Helper class to specify for which image type we can find a valid texture format.
struct sibr::ValidGLTexFormat< sibr::Image< ScalarType, N > >
Helper class to specify for which image type we can find a valid texture format.
struct sibr::ValidGLTexFormat< cv::Mat >
Helper class to specify for which image type we can find a valid texture format.
struct sibr::GLTexFormat< ImageType, ScalarType, N >
Helper class to provide, from a generic image type, all the information needed for OpenGL textures Right now it can work with all sibr::Image and with cv::Mat (3U8 only) You can add more using explicit template instanciation to specify both ValidGLTexFormat and the following GLTexFormat properties.
struct sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >
Helper class to provide, for an sibr::Image, all the information needed for OpenGL textures.
struct sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >
Helper class to provide, for an sibr::Image::Ptr, all the information needed for OpenGL textures.
struct sibr::GLTexFormat< cv::Mat, ScalarType, N >
Helper class to provide, for a cv::Mat, all the information needed for OpenGL textures.
struct sibr::GLTexFormat< cv::Mat_< cv::Vec< ScalarType, N > >, ScalarType, N >
Helper class to provide, for a cv::Mat, all the information needed for OpenGL textures.
class sibr::Viewport
Represent an on-screen viewport using normalized coordinates, which can be nested into another viewport.
class sibr::Window
System window backed by an internal framebuffer.
Typedefs
typedef Vector4f sibr::ColorRGBA
typedef T_Type sibr::Image< T_Type, T_NumComp >::Type
typedef ImagePtr< T_Type, T_NumComp > sibr::Image< T_Type, T_NumComp >::Ptr
typedef Eigen::Matrix< T_Type, T_NumComp, 1, Eigen::DontAlign > sibr::Image< T_Type, T_NumComp >::Pixel
using sibr::ImagePtr< T_Type, T_NumComp >::ImageType = Image< T_Type, T_NumComp >
Underlying image type.
typedef Image< unsigned char, 3 > sibr::ImageRGB
Standard image types.
typedef Image< unsigned char, 4 > sibr::ImageRGBA
typedef Image< unsigned char, 1 > sibr::ImageL8
typedef Image< unsigned char, 2 > sibr::ImageUV8
typedef Image< unsigned short int, 3 > sibr::ImageRGB16
typedef Image< unsigned short int, 1 > sibr::ImageL16
typedef Image< float, 3 > sibr::ImageRGB32F
typedef Image< float, 3 > sibr::ImageFloat3
typedef Image< float, 4 > sibr::ImageRGBA32F
typedef Image< float, 4 > sibr::ImageFloat4
typedef Image< float, 1 > sibr::ImageL32F
typedef Image< float, 1 > sibr::ImageFloat1
typedef Image< float, 2 > sibr::ImageFloat2
typedef Image< float, 2 > sibr::ImageUV32F
typedef Image< bool, 1 > sibr::ImageBool1
typedef Image< double, 1 > sibr::ImageDouble1
typedef Image< double, 2 > sibr::ImageDouble2
typedef Image< double, 3 > sibr::ImageDouble3
typedef Image< double, 4 > sibr::ImageDouble4
typedef Image< int, 1 > sibr::ImageInt1
typedef Image< int, 2 > sibr::ImageInt2
typedef Image< int, 3 > sibr::ImageInt3
typedef Image< int, 4 > sibr::ImageInt4
using sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::ImageType = sibr::Image< ScalarType, N >
using sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::ImageType = ImagePtr< ScalarType, N >
Enumerations
enum { sibr::Image< T_Type, T_NumComp >::e_NumComp = T_NumComp }
enum { sibr::GLType< unsigned char >::type = GL_UNSIGNED_BYTE }
enum { sibr::GLType< unsigned short >::type = GL_UNSIGNED_SHORT }
enum { sibr::GLType< short >::type = GL_SHORT }
enum { sibr::GLType< float >::type = GL_FLOAT }
enum { sibr::GLType< int >::type = GL_INT }
enum {
sibr::GLFormat< unsigned char, 1 >::internal_format = GL_R8, sibr::GLFormat< unsigned char, 1 >::format = GL_RED, sibr::GLFormat< unsigned char, 1 >::int_internal_format = GL_R8UI, sibr::GLFormat< unsigned char, 1 >::int_format = GL_RED_INTEGER,
sibr::GLFormat< unsigned char, 1 >::isdepth = 0
}
enum {
sibr::GLFormat< unsigned char, 2 >::internal_format = GL_RG8, sibr::GLFormat< unsigned char, 2 >::format = GL_RG, sibr::GLFormat< unsigned char, 2 >::int_internal_format = GL_RG8UI, sibr::GLFormat< unsigned char, 2 >::int_format = GL_RG_INTEGER,
sibr::GLFormat< unsigned char, 2 >::isdepth = 0
}
enum {
sibr::GLFormat< unsigned char, 3 >::internal_format = GL_RGB8, sibr::GLFormat< unsigned char, 3 >::format = GL_RGB, sibr::GLFormat< unsigned char, 3 >::int_internal_format = GL_RGB8UI, sibr::GLFormat< unsigned char, 3 >::int_format = GL_RGB_INTEGER,
sibr::GLFormat< unsigned char, 3 >::isdepth = 0
}
enum {
sibr::GLFormat< unsigned char, 4 >::internal_format = GL_RGBA8, sibr::GLFormat< unsigned char, 4 >::format = GL_RGBA, sibr::GLFormat< unsigned char, 4 >::int_internal_format = GL_RGBA8UI, sibr::GLFormat< unsigned char, 4 >::int_format = GL_RGBA_INTEGER,
sibr::GLFormat< unsigned char, 4 >::isdepth = 0
}
enum {
sibr::GLFormat< unsigned short, 1 >::internal_format = GL_R16, sibr::GLFormat< unsigned short, 1 >::format = GL_R, sibr::GLFormat< unsigned short, 1 >::int_internal_format = GL_R16UI, sibr::GLFormat< unsigned short, 1 >::int_format = GL_RED_INTEGER,
sibr::GLFormat< unsigned short, 1 >::isdepth = 0
}
enum {
sibr::GLFormat< unsigned short, 2 >::internal_format = GL_RG16, sibr::GLFormat< unsigned short, 2 >::format = GL_RG, sibr::GLFormat< unsigned short, 2 >::int_internal_format = GL_RG16UI, sibr::GLFormat< unsigned short, 2 >::int_format = GL_RG_INTEGER,
sibr::GLFormat< unsigned short, 2 >::isdepth = 0
}
enum {
sibr::GLFormat< unsigned short, 3 >::internal_format = GL_RGB16, sibr::GLFormat< unsigned short, 3 >::format = GL_RGB, sibr::GLFormat< unsigned short, 3 >::int_internal_format = GL_RGB16UI, sibr::GLFormat< unsigned short, 3 >::int_format = GL_RGB_INTEGER,
sibr::GLFormat< unsigned short, 3 >::isdepth = 0
}
enum {
sibr::GLFormat< unsigned short, 4 >::internal_format = GL_RGBA16, sibr::GLFormat< unsigned short, 4 >::format = GL_RGBA, sibr::GLFormat< unsigned short, 4 >::int_internal_format = GL_RGBA16UI, sibr::GLFormat< unsigned short, 4 >::int_format = GL_RGBA_INTEGER,
sibr::GLFormat< unsigned short, 4 >::isdepth = 0
}
enum {
sibr::GLFormat< int, 1 >::internal_format = GL_R32I, sibr::GLFormat< int, 1 >::format = GL_RED_INTEGER, sibr::GLFormat< int, 1 >::int_internal_format = GL_R32I, sibr::GLFormat< int, 1 >::int_format = GL_RED_INTEGER,
sibr::GLFormat< int, 1 >::isdepth = 0
}
enum {
sibr::GLFormat< int, 2 >::internal_format = GL_RG32I, sibr::GLFormat< int, 2 >::format = GL_RG_INTEGER, sibr::GLFormat< int, 2 >::int_internal_format = GL_RG32I, sibr::GLFormat< int, 2 >::int_format = GL_RG_INTEGER,
sibr::GLFormat< int, 2 >::isdepth = 0
}
enum {
sibr::GLFormat< int, 3 >::internal_format = GL_RGB32I, sibr::GLFormat< int, 3 >::format = GL_RGB_INTEGER, sibr::GLFormat< int, 3 >::int_internal_format = GL_RGB32I, sibr::GLFormat< int, 3 >::int_format = GL_RGB_INTEGER,
sibr::GLFormat< int, 3 >::isdepth = 0
}
enum {
sibr::GLFormat< int, 4 >::internal_format = GL_RGBA32I, sibr::GLFormat< int, 4 >::format = GL_RGBA_INTEGER, sibr::GLFormat< int, 4 >::int_internal_format = GL_RGBA32I, sibr::GLFormat< int, 4 >::int_format = GL_RGBA_INTEGER,
sibr::GLFormat< int, 4 >::isdepth = 0
}
enum {
sibr::GLFormat< float, 1 >::internal_format = GL_R32F, sibr::GLFormat< float, 1 >::format = GL_RED, sibr::GLFormat< float, 1 >::int_internal_format = -1, sibr::GLFormat< float, 1 >::int_format = -1,
sibr::GLFormat< float, 1 >::isdepth = 0
}
enum {
sibr::GLFormat< float, 2 >::internal_format = GL_RG32F, sibr::GLFormat< float, 2 >::format = GL_RG, sibr::GLFormat< float, 2 >::int_internal_format = -1, sibr::GLFormat< float, 2 >::int_format = -1,
sibr::GLFormat< float, 2 >::isdepth = 0
}
enum {
sibr::GLFormat< float, 3 >::internal_format = GL_RGB32F, sibr::GLFormat< float, 3 >::format = GL_RGB, sibr::GLFormat< float, 3 >::int_internal_format = -1, sibr::GLFormat< float, 3 >::int_format = -1,
sibr::GLFormat< float, 3 >::isdepth = 0
}
enum {
sibr::GLFormat< float, 4 >::internal_format = GL_RGBA32F, sibr::GLFormat< float, 4 >::format = GL_RGBA, sibr::GLFormat< float, 4 >::int_internal_format = -1, sibr::GLFormat< float, 4 >::int_format = -1,
sibr::GLFormat< float, 4 >::isdepth = 0
}
enum {
sibr::GLFormatCVmat< unsigned char, 1 >::internal_format = GLFormat<uchar, 1>::internal_format, sibr::GLFormatCVmat< unsigned char, 1 >::format = GLFormat<uchar, 1>::format, sibr::GLFormatCVmat< unsigned char, 1 >::int_internal_format = GLFormat<uchar, 1>::int_internal_format, sibr::GLFormatCVmat< unsigned char, 1 >::int_format = GLFormat<uchar, 1>::int_format,
sibr::GLFormatCVmat< unsigned char, 1 >::isdepth = GLFormat<uchar, 1>::isdepth
}
enum {
sibr::GLFormatCVmat< unsigned char, 3 >::internal_format = GLFormat<uchar,3>::internal_format, sibr::GLFormatCVmat< unsigned char, 3 >::format = GL_BGR, sibr::GLFormatCVmat< unsigned char, 3 >::int_internal_format = GLFormat<uchar, 3>::int_internal_format, sibr::GLFormatCVmat< unsigned char, 3 >::int_format = GLFormat<uchar, 3>::int_format,
sibr::GLFormatCVmat< unsigned char, 3 >::isdepth = GLFormat<uchar, 3>::isdepth
}
enum {
sibr::GLFormatCVmat< unsigned char, 4 >::internal_format = GLFormat<uchar, 4>::internal_format, sibr::GLFormatCVmat< unsigned char, 4 >::format = GL_BGRA, sibr::GLFormatCVmat< unsigned char, 4 >::int_internal_format = GLFormat<uchar, 4>::int_internal_format, sibr::GLFormatCVmat< unsigned char, 4 >::int_format = GLFormat<uchar, 4>::int_format,
sibr::GLFormatCVmat< unsigned char, 4 >::isdepth = GLFormat<uchar, 4>::isdepth
}
Functions
template<typename T >
T sibr::clamp (T value, T min, T max)
Clamp a value.
bool sibr::showImGuiWindow (const std::string &windowTitle, const IRenderTarget &rt, ImGuiWindowFlags flags, Viewport &viewport, bool invalidTexture, bool updateLayout, int handle=0)
Show the content of a rendertarget in an ImGui window.
void sibr::fitImageToDisplayRegion (const Vector2f &imgSize, const Vector2i &regionSize, Vector2f &offset, Vector2f &size)
Helper that compute the location and extent to display an image in a given region without cropping or distorting it.
Mesh::Ptr sibr::generateMeshForText (const std::string &text, unsigned int &separationIndex)
Generate a mesh for a given label, using ImGui internally.
const float ImGui::GetTitleBarHeight ()
void ImGui::PushScaledItemWidth (float item_width)
Push a width for item which is HiDPI aware.
bool ImGui::TabButton (const char *label, bool highlight, const ImVec2 &size=ImVec2(0, 0))
Helper to create a tab button item.
template<typename T_Type >
SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType (void)
template<>
SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< uint8 > (void)
template<>
SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< int8 > (void)
template<>
SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< uint16 > (void)
template<>
SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< int16 > (void)
template<>
SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< int32 > (void)
template<>
SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< float > (void)
template<>
SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< double > (void)
template<typename T_Type >
float sibr::opencv::imageTypeRange (void)
template<>
SIBR_GRAPHICS_EXPORT float sibr::opencv::imageTypeRange< float > (void)
template<>
SIBR_GRAPHICS_EXPORT float sibr::opencv::imageTypeRange< double > (void)
float sibr::opencv::imageTypeCVRange (int cvDepth)
Get the size of the range of values an OpenCV type can take.
void sibr::opencv::convertBGR2RGB (cv::Mat &dst)
Convert a BGR cv::Mat into a RGB cv::Mat, in-place.
void sibr::opencv::convertRGB2BGR (cv::Mat &dst)
Convert a BGR cv::Mat into a RGB cv::Mat, in-place.
sibr::IImage::SIBR_CLASS_PTR (IImage)
virtual bool sibr::IImage::load (const std::string &filename, bool verbose=true, bool warning_if_not_found=true)=0
Load an image from the disk (png, jpeg, exr, etc., see OpenCV cv::imread documentation for more details).
virtual bool sibr::IImage::loadByteStream (const std::string &filename, bool verbose=true)=0
Load an image from the disk (stored as a raw binary blob).
virtual void sibr::IImage::save (const std::string &filename, bool verbose=true) const =0
Save an image to the disk (png, jpeg, see OpenCV cv::imwrite documentation for more details).
virtual void sibr::IImage::saveByteStream (const std::string &filename, bool verbose=true) const =0
Save an image to the disk (as a raw binary blob).
virtual void sibr::IImage::saveHDR (const std::string &filename, bool verbose=true) const =0
Save an HDR image to the disk (exr, hdr, see OpenCV cv::imwrite documentation for more details).
virtual uint sibr::IImage::w (void) const =0
virtual uint sibr::IImage::h (void) const =0
virtual sibr::Vector2u sibr::IImage::size (void) const =0
virtual bool sibr::IImage::isInRange (const ::sibr::Vector2i &xy) const =0
Check if a pixel (x,y) is inside the image boundaries.
virtual std::string sibr::IImage::pixelStr (const ::sibr::Vector2i &xy) const =0
Get the value stored at a pixel and convert it to a string representation.
virtual uint sibr::IImage::numComp (void) const =0
virtual uint sibr::IImage::sizeOfComp (void) const =0
virtual void sibr::IImage::flipH (void)=0
Flip the image along the horizontal axis.
virtual void sibr::IImage::flipV (void)=0
Flip the image along the vertical axis.
virtual int sibr::IImage::opencvType (void) const =0
virtual const cv::Mat & sibr::IImage::toOpenCV (void) const =0
virtual cv::Mat & sibr::IImage::toOpenCVnonConst (void)=0
virtual cv::Mat sibr::IImage::toOpenCVBGR (void) const =0
virtual void sibr::IImage::fromOpenCV (const cv::Mat &img)=0
Replace the content of the image with the content of another matrix.
virtual void sibr::IImage::fromOpenCVBGR (const cv::Mat &img)=0
Replace the content of the image with the content of another matrix, flipping channels.
static sibr::Vector2i sibr::IImage::get_jpeg_size (std::ifstream &file)
Get the size of jpeg image file by reading its header.
static sibr::Vector2i sibr::IImage::imageResolution (const std::string &file_path)
Get the size of an image file from its header.
sibr::Image< T_Type, T_NumComp >::Image (void)
Default constructor.
sibr::Image< T_Type, T_NumComp >::Image (uint width, uint height)
Constructor.
sibr::Image< T_Type, T_NumComp >::Image (uint width, uint height, const T_Type &init)
Constructor.
sibr::Image< T_Type, T_NumComp >::Image (uint width, uint height, const Pixel &init)
Constructor.
sibr::Image< T_Type, T_NumComp >::Image (Image &&other)
Move constructor.
Image & sibr::Image< T_Type, T_NumComp >::operator= (Image &&other) noexcept
Move operator.
bool sibr::Image< T_Type, T_NumComp >::load (const std::string &filename, bool verbose=true, bool warning_if_not_found=true)
Load an image from the disk (png, jpeg, exr, etc., see OpenCV cv::imread documentation for more details).
bool sibr::Image< T_Type, T_NumComp >::loadByteStream (const std::string &filename, bool verbose=true)
Load an image from the disk (stored as a raw binary blob).
void sibr::Image< T_Type, T_NumComp >::save (const std::string &filename, bool verbose=true) const
Save an image to the disk (png, jpeg, see OpenCV cv::imwrite documentation for more details).
void sibr::Image< T_Type, T_NumComp >::saveByteStream (const std::string &filename, bool verbose=true) const
Save an image to the disk (as a raw binary blob).
void sibr::Image< T_Type, T_NumComp >::saveHDR (const std::string &filename, bool verbose=true) const
Save an HDR image to the disk (exr, hdr, see OpenCV cv::imwrite documentation for more details).
const Pixel & sibr::Image< T_Type, T_NumComp >::operator() (uint x, uint y) const
Pixel accessor.
Pixel & sibr::Image< T_Type, T_NumComp >::operator() (uint x, uint y)
Pixel accessor.
const Pixel & sibr::Image< T_Type, T_NumComp >::operator() (const sibr::Vector2i &xy) const
Pixel accessor.
Pixel & sibr::Image< T_Type, T_NumComp >::operator() (const sibr::Vector2i &xy)
Pixel accessor.
const Pixel & sibr::Image< T_Type, T_NumComp >::operator() (const ::sibr::Vector2f &xy) const
Pixel accessor.
Pixel & sibr::Image< T_Type, T_NumComp >::operator() (const ::sibr::Vector2f &xy)
Pixel accessor.
virtual std::string sibr::Image< T_Type, T_NumComp >::pixelStr (const ::sibr::Vector2i &xy) const
Get the value stored at a pixel and convert it to a string representation.
const void * sibr::Image< T_Type, T_NumComp >::data (void) const
void * sibr::Image< T_Type, T_NumComp >::data (void)
ColorRGBA sibr::Image< T_Type, T_NumComp >::color (uint x, uint y) const
Convert a pixel value to a 4 components float vector (in 0,1).
void sibr::Image< T_Type, T_NumComp >::color (uint x, uint y, const ColorRGBA &c)
Set a pixel value from 4 components float vector (in 0,1).
static Pixel sibr::Image< T_Type, T_NumComp >::color (const ColorRGBA &rgba)
Helper to convert a 4 components float vector (in 0,1) to the proper pixel format.
Image sibr::Image< T_Type, T_NumComp >::resized (int width, int height, int cv_interpolation_method=cv::INTER_LINEAR) const
Generate a resized version of the current image.
Image sibr::Image< T_Type, T_NumComp >::resizedMax (int maxlen) const
Generate a resized version of the current image so that the maximum dimension (either width or height) is now equal to maxlen.
Image sibr::Image< T_Type, T_NumComp >::clone (void) const
ImagePtr< T_Type, T_NumComp > sibr::Image< T_Type, T_NumComp >::clonePtr (void) const
uint sibr::Image< T_Type, T_NumComp >::w (void) const
uint sibr::Image< T_Type, T_NumComp >::h (void) const
sibr::Vector2u sibr::Image< T_Type, T_NumComp >::size (void) const
template<typename T >
bool sibr::Image< T_Type, T_NumComp >::isInRange (T x, T y) const
Check if a pixel (x,y) is inside the image boundaries.
template<typename T >
bool sibr::Image< T_Type, T_NumComp >::inRange (T x, T y) const
Check if a pixel (x,y) is inside the image boundaries.
bool sibr::Image< T_Type, T_NumComp >::isInRange (const sibr::Vector2i &xy) const
Check if a pixel (x,y) is inside the image boundaries.
bool sibr::Image< T_Type, T_NumComp >::isInRange (const sibr::Vector2f &xy) const
Check if a pixel (x,y) is inside the image boundaries.
uint sibr::Image< T_Type, T_NumComp >::numComp (void) const
uint sibr::Image< T_Type, T_NumComp >::sizeOfComp (void) const
void sibr::Image< T_Type, T_NumComp >::flipH (void)
Flip the image along the horizontal axis.
void sibr::Image< T_Type, T_NumComp >::flipV (void)
Flip the image along the vertical axis.
int sibr::Image< T_Type, T_NumComp >::opencvType (void) const
const cv::Mat & sibr::Image< T_Type, T_NumComp >::toOpenCV (void) const
cv::Mat & sibr::Image< T_Type, T_NumComp >::toOpenCVnonConst (void)
cv::Mat sibr::Image< T_Type, T_NumComp >::toOpenCVBGR (void) const
void sibr::Image< T_Type, T_NumComp >::fromOpenCV (const cv::Mat &img)
Replace the content of the image with the content of another matrix.
void sibr::Image< T_Type, T_NumComp >::fromOpenCVBGR (const cv::Mat &img)
Replace the content of the image with the content of another matrix, flipping channels.
void sibr::Image< T_Type, T_NumComp >::findMinMax (Pixel &minImage, Pixel &maxImage)
Find the component-wise minimum and maximum values contained in the image.
void sibr::Image< T_Type, T_NumComp >::remap (const Pixel &minValue, const Pixel &maxValue)
Rescale an image content in a defined range.
template<class T_Image >
T_Image sibr::Image< T_Type, T_NumComp >::cast () const
Cast into another image type.
Pixel sibr::Image< T_Type, T_NumComp >::bilinear (const sibr::Vector2f &pixel) const
Fetch bilinear interpolated value from floating point pixel coordinates.
Pixel sibr::Image< T_Type, T_NumComp >::bicubic (const sibr::Vector2f &pixelPosition) const
Fetch bicubic interpolated value from floating point pixel coordinates.
sibr::Image< T_Type, T_NumComp >::Image (const Image &other)=delete
Disallow copy constructor.
Image & sibr::Image< T_Type, T_NumComp >::operator= (const Image &other)=delete
Disallow copy operator.
static Eigen::Matrix< float, T_NumComp, 1, Eigen::DontAlign > sibr::Image< T_Type, T_NumComp >::monoCubic (float t, const Eigen::Matrix< float, T_NumComp, 4, Eigen::DontAlign > &colors)
Helper for bicubic interpolation.
sibr::ImagePtr< T_Type, T_NumComp >::ImagePtr ()
Default constructor.
sibr::ImagePtr< T_Type, T_NumComp >::ImagePtr (Image< T_Type, T_NumComp > *imgPtr)
Constructor from a raw pointer.
sibr::ImagePtr< T_Type, T_NumComp >::ImagePtr (const std::shared_ptr< Image< T_Type, T_NumComp >> &imgPtr)
Constructor from a shared pointer.
static ImagePtr sibr::ImagePtr< T_Type, T_NumComp >::fromImg (const ImageType &img)
Generate a pointer by cloning an image.
void sibr::ImagePtr< T_Type, T_NumComp >::reset (ImageType *ptr)
Set a new pointee.
Image< T_Type, T_NumComp > * sibr::ImagePtr< T_Type, T_NumComp >::get ()
const Image< T_Type, T_NumComp >::Pixel & sibr::ImagePtr< T_Type, T_NumComp >::operator() (uint x, uint y) const
Pixel accessor.
Image< T_Type, T_NumComp >::Pixel & sibr::ImagePtr< T_Type, T_NumComp >::operator() (uint x, uint y)
Pixel accessor.
const Image< T_Type, T_NumComp >::Pixel & sibr::ImagePtr< T_Type, T_NumComp >::operator() (const sibr::Vector2i &xy) const
Pixel accessor.
Image< T_Type, T_NumComp >::Pixel & sibr::ImagePtr< T_Type, T_NumComp >::operator() (const sibr::Vector2i &xy)
Pixel accessor.
Image< T_Type, T_NumComp > & sibr::ImagePtr< T_Type, T_NumComp >::operator* ()
const Image< T_Type, T_NumComp > & sibr::ImagePtr< T_Type, T_NumComp >::operator* () const
Image< T_Type, T_NumComp > * sibr::ImagePtr< T_Type, T_NumComp >::operator-> ()
const Image< T_Type, T_NumComp > * sibr::ImagePtr< T_Type, T_NumComp >::operator-> () const
std::shared_ptr< Image< T_Type, T_NumComp > > & sibr::ImagePtr< T_Type, T_NumComp >::operator= (std::shared_ptr< Image< T_Type, T_NumComp >> &imgShPtr)
Assign a shared ptr.
sibr::ImagePtr< T_Type, T_NumComp >::operator bool ()
sibr::ImagePtr< T_Type, T_NumComp >::operator bool () const
Image< unsigned char, 3 > sibr::coloredClass (const Image< unsigned char, 1 >::Ptr imClass)
Convert an integer ID map to a colored image using a different random color for each ID.
Image< unsigned char, 3 > sibr::coloredClass (const Image< int, 1 >::Ptr imClass)
Convert an integer ID map to a colored image using a different random color for each ID.
void sibr::showFloat (const Image< float, 1 > &im, bool logScale=false, double min=-DBL_MAX, double max=DBL_MAX)
Display a 32F image in a debug window, using the Parula colormap after normalizing the values.
sibr::ImageRGBA sibr::convertL32FtoRGBA (const sibr::ImageL32F &imgF)
Convert a L32F into a RGBA image while preserving bit-level representation.
sibr::ImageL32F sibr::convertRGBAtoL32F (const sibr::ImageRGBA &imgRGBA)
Convert a RGBA into a L32F image while preserving bit-level representation.
sibr::ImageRGBA sibr::convertRGB32FtoRGBA (const sibr::ImageRGB32F &imgF)
Convert a RGB32F into a RGBA image (3 times wider) while preserving bit-level representation.
sibr::ImageRGB32F sibr::convertRGBAtoRGB32F (const sibr::ImageRGBA &imgRGBA)
Convert a RGBA into a RGB32F image while preserving bit-level representation.
sibr::ImageRGBA sibr::convertNormalMapToSphericalHalf (const sibr::ImageRGB32F &imgF)
Convert a RGB32 normal map into a UV16 map storing theta and phi as half floats, packed into a RGBA8.
sibr::ImageRGB32F sibr::convertSphericalHalfToNormalMap (const sibr::ImageRGBA &imgF)
Convert a RGBA map, packing theta and phi as half floats, into a RGB32 normal map.
cv::Mat sibr::duplicate3 (cv::Mat c)
Create a three channels cv::Mat by repeating a single channel cv::Mat.
template<typename T_Type , unsigned T_NumComp>
static void sibr::show (const Image< T_Type, T_NumComp > &img, const std::string &windowTitle="sibr::show()", bool closeWindow=true)
Display an image into a popup OpenCV window.
template<typename sibr_T , typename openCV_T , int N>
Vector< sibr_T, N > sibr::fromOpenCV (const cv::Vec< openCV_T, N > &vec)
template<typename openCV_T , typename sibr_T , int N>
cv::Vec< openCV_T, N > sibr::toOpenCV (const Vector< sibr_T, N > &vec)
void sibr::blit (const IRenderTarget &src, const IRenderTarget &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a render target to another render target, resizing if needed.
void sibr::blit_and_flip (const IRenderTarget &src, const IRenderTarget &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a render target to another render target, resizing if needed and flipping the result.
template<typename T_Type , unsigned T_NumComp>
static void sibr::show (const RenderTarget< T_Type, T_NumComp > &rt, uint layer=0, const std::string &windowTitle="sibr::show()", bool closeWindow=true)
Display a rendertarget color content in a popup window (backed by OpenCV).
template<typename T_Type , unsigned T_NumComp>
static void sibr::showDepth (const RenderTarget< T_Type, T_NumComp > &rt, const std::string &windowTitle="sibr::show()", bool closeWindow=true)
Display a rendertarget depth content in a popup window (backed by OpenCV).
template<typename T_Type , unsigned T_NumComp>
static void sibr::showDepthFromAlpha (const RenderTarget< T_Type, T_NumComp > &rt, const std::string &windowTitle="sibr::show()", bool closeWindow=true)
Display a rendertarget alpha content as a grey map in a popup window (backed by OpenCV).
std::string sibr::loadFile (const std::string &filename, const GLShader::Define::List &defines)
Load a file from disk and apply macro-like substitutions.
void sibr::blit (const ITexture2D &src, const ITexture2D &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a texture to another texture, resizing if needed.
void sibr::blit (const ITexture2D &src, const IRenderTarget &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR, bool flip=false)
Copy the content of a texture to a render target, resizing if needed.
void sibr::blit_and_flip (const ITexture2D &src, const IRenderTarget &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a texture to a render target, resizing if needed and flipping the result.
void sibr::blitToColorAttachment (const ITexture2D &src, IRenderTarget &dst, int location, GLenum filter=GL_LINEAR, bool flip=false)
Copy the content of a texture to a specific color attachment of the destination render target, resizing if needed.
void sibr::blit (const IRenderTarget &src, const ITexture2D &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a rendertarget first color attachment to a texture, resizing if needed.
template<typename T_Type , unsigned T_NumComp>
static void sibr::show (const RenderTarget< T_Type, T_NumComp > &rt, const std::string &winTitle="sibr::show()")
Display a RenderTarget into a popup OpenCV window.
template<typename T_Type , unsigned T_NumComp>
static void sibr::show (const Texture2D< T_Type, T_NumComp > &texture, const std::string &winTitle="sibr::show()")
Display a texture into a popup OpenCV window.
static ImageType sibr::GLTexFormat< ImageType, ScalarType, N >::flip (const ImageType &img)
Flip an image.
static ImageType sibr::GLTexFormat< ImageType, ScalarType, N >::resize (const ImageType &img, uint w, uint h)
Resize an image.
static uint sibr::GLTexFormat< ImageType, ScalarType, N >::width (const ImageType &img)
Get an image width.
static uint sibr::GLTexFormat< ImageType, ScalarType, N >::height (const ImageType &img)
Get an image height.
static const void * sibr::GLTexFormat< ImageType, ScalarType, N >::data (const ImageType &img)
Get an image data.
static ImageType sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::flip (const ImageType &img)
Flip an image.
static ImageType sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::resize (const ImageType &img, uint w, uint h)
Resize an image.
static uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::width (const ImageType &img)
Get an image width.
static uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::height (const ImageType &img)
Get an image height.
static const void * sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::data (const ImageType &img)
Get an image data.
static ImageType sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::flip (const ImageType &img)
Flip an image.
static ImageType sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::resize (const ImageType &img, uint w, uint h)
Resize an image.
static uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::width (const ImageType &img)
Get an image width.
static uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::height (const ImageType &img)
Get an image height.
static const void * sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::data (const ImageType &img)
Get an image data.
static cv::Mat sibr::GLTexFormat< cv::Mat, ScalarType, N >::flip (const cv::Mat &img)
Flip an image.
static cv::Mat sibr::GLTexFormat< cv::Mat, ScalarType, N >::resize (const cv::Mat &img, uint w, uint h)
Resize an image.
static uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::width (const cv::Mat &img)
Get an image width.
static uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::height (const cv::Mat &img)
Get an image height.
static const void * sibr::GLTexFormat< cv::Mat, ScalarType, N >::data (const cv::Mat &img)
Get an image data.
static void * sibr::GLTexFormat< cv::Mat, ScalarType, N >::data (cv::Mat &img)
Get an image data.
static uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::cv_type ()
template<typename T_Type >
static Eigen::Matrix< T_Type, 3, 1, Eigen::DontAlign > sibr::randomColor ()
Generate a random color.
cv::Scalar sibr::jetColor (float gray)
Generate a color for a given scalar score, using the jet color map.
sibr::Vector3ub sibr::getLinearColorFromProbaV (double proba)
Generate a color for a given scalar score, using a reversible mapping.
double sibr::getProbaFromLinearColor (const sibr::Vector3ub &color)
Convert a color to the associated scalar score, using a reversible mapping.
sibr::Vector2d sibr::cartesianToSpherical (const sibr::Vector3d &dir)
Convert a direction from cartesian to spherical coordinates.
sibr::Vector2d sibr::cartesianToSphericalUVs (const sibr::Vector3d &dir)
Convert a direction from cartesian to spherical UVs.
void sibr::sRGB2Lin (sibr::ImageRGB32F &img)
Inplace conversion of float image from sRGB space to linear.
void sibr::lin2sRGB (sibr::ImageRGB32F &img)
Inplace conversion of a float image from linear space to sRGB.
template<typename FunType , typename ... ArgsType>
void sibr::renderTask (const std::string &s, FunType &&f, ArgsType &&... args)
Debug helper: wrap a rendering task in an openGL debug group (visible in Renderdoc).
float sibr::lerp (float A, float B, float fac)
Interpolate between two values.
float sibr::inverseLerp (float from, float to, float current)
Express a value as the linear combination of two other values.
Variables
cv::Mat sibr::Image< T_Type, T_NumComp >::_pixels
Pixels stored in RGB format.
std::shared_ptr< Image< T_Type, T_NumComp > > sibr::ImagePtr< T_Type, T_NumComp >::imPtr
Pointer type.
static const uint sibr::OpenCVdepth< uchar >::value = CV_8U
static const uint sibr::OpenCVdepth< float >::value = CV_32F
static const uint sibr::OpenCVdepth< double >::value = CV_64F
template<typename T , uint N>
constexpr uint sibr::getOpenCVtype = CV_MAKE_TYPE(OpenCVdepth<T>::value, N)
Helper to create a cv::Mat type from its depth and number of components.
template<typename T >
constexpr uint sibr::getOpenCVtypeSingleChannel = getOpenCVtype<T, 1>
Helper to create a one-channel cv::Mat from its depth.
static const bool sibr::ValidGLTexFormat< ImageType >::value = false
static const bool sibr::ValidGLTexFormat< sibr::Image< ScalarType, N > >::value = true
static const bool sibr::ValidGLTexFormat< cv::Mat >::value = true
static const uint sibr::GLTexFormat< ImageType, ScalarType, N >::internal_format
Internal GL format.
static const uint sibr::GLTexFormat< ImageType, ScalarType, N >::format
Generic GL format.
static const uint sibr::GLTexFormat< ImageType, ScalarType, N >::int_internal_format
Internal GL format for integer textures.
static const uint sibr::GLTexFormat< ImageType, ScalarType, N >::int_format
Generic GL format for integer textures.
static const uint sibr::GLTexFormat< ImageType, ScalarType, N >::isdepth
Is it a depth format.
static const uint sibr::GLTexFormat< ImageType, ScalarType, N >::type
The component GL type.
static const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::internal_format = GLFormat<ScalarType, N>::internal_format
Internal GL format.
static const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::format = GLFormat<ScalarType, N>::format
Generic GL format.
static const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::int_internal_format = GLFormat<ScalarType, N>::int_internal_format
Internal GL format for integer textures.
static const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::int_format = GLFormat<ScalarType, N>::int_format
Generic GL format for integer textures.
static const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::isdepth = GLFormat<ScalarType, N>::isdepth
Is it a depth format.
static const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::type = GLType<ScalarType>::type
The component GL type.
static const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::internal_format = GLFormat<ScalarType, N>::internal_format
Internal GL format.
static const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::format = GLFormat<ScalarType, N>::format
Generic GL format.
static const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::int_internal_format = GLFormat<ScalarType, N>::int_internal_format
Internal GL format for integer textures.
static const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::int_format = GLFormat<ScalarType, N>::int_format
Generic GL format for integer textures.
static const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::isdepth = GLFormat<ScalarType, N>::isdepth
Is it a depth format.
static const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::type = GLType<ScalarType>::type
The component GL type.
static const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::internal_format = GLFormatCVmat<ScalarType, N>::internal_format
Internal GL format.
static const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::format = GLFormatCVmat<ScalarType, N>::format
Generic GL format.
static const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::int_internal_format = GLFormatCVmat<ScalarType, N>::int_internal_format
Internal GL format for integer textures.
static const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::int_format = GLFormatCVmat<ScalarType, N>::int_format
Generic GL format for integer textures.
static const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::isdepth = GLFormatCVmat<ScalarType, N>::isdepth
Is it a depth format.
static const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::type = GLType<ScalarType>::type
The component GL type.
Detailed Description
OpenGL and graphics utilities.
Contain type utilities to match C, cv and sibr types to OpenGL formats.
Typedef Documentation
ColorRGBA
typedef Vector4f sibr::ColorRGBA
Definition at line 86 of file Image.hpp.
ImageBool1
typedef Image<bool, 1> sibr::ImageBool1
Definition at line 616 of file Image.hpp.
ImageDouble1
typedef Image<double, 1> sibr::ImageDouble1
Definition at line 617 of file Image.hpp.
ImageDouble2
typedef Image<double, 2> sibr::ImageDouble2
Definition at line 618 of file Image.hpp.
ImageDouble3
typedef Image<double, 3> sibr::ImageDouble3
Definition at line 619 of file Image.hpp.
ImageDouble4
typedef Image<double, 4> sibr::ImageDouble4
Definition at line 620 of file Image.hpp.
ImageFloat1
typedef Image<float, 1> sibr::ImageFloat1
Definition at line 613 of file Image.hpp.
ImageFloat2
typedef Image<float, 2> sibr::ImageFloat2
Definition at line 614 of file Image.hpp.
ImageFloat3
typedef Image<float, 3> sibr::ImageFloat3
Definition at line 609 of file Image.hpp.
ImageFloat4
typedef Image<float, 4> sibr::ImageFloat4
Definition at line 611 of file Image.hpp.
ImageInt1
typedef Image<int, 1> sibr::ImageInt1
Definition at line 621 of file Image.hpp.
ImageInt2
typedef Image<int, 2> sibr::ImageInt2
Definition at line 622 of file Image.hpp.
ImageInt3
typedef Image<int, 3> sibr::ImageInt3
Definition at line 623 of file Image.hpp.
ImageInt4
typedef Image<int, 4> sibr::ImageInt4
Definition at line 624 of file Image.hpp.
ImageL16
typedef Image<unsigned short int, 1> sibr::ImageL16
Definition at line 607 of file Image.hpp.
ImageL32F
typedef Image<float, 1> sibr::ImageL32F
Definition at line 612 of file Image.hpp.
ImageL8
typedef Image<unsigned char, 1> sibr::ImageL8
Definition at line 604 of file Image.hpp.
ImageRGB
typedef Image<unsigned char, 3> sibr::ImageRGB
Standard image types.
Definition at line 602 of file Image.hpp.
ImageRGB16
typedef Image<unsigned short int, 3> sibr::ImageRGB16
Definition at line 606 of file Image.hpp.
ImageRGB32F
typedef Image<float, 3> sibr::ImageRGB32F
Definition at line 608 of file Image.hpp.
ImageRGBA
typedef Image<unsigned char, 4> sibr::ImageRGBA
Definition at line 603 of file Image.hpp.
ImageRGBA32F
typedef Image<float, 4> sibr::ImageRGBA32F
Definition at line 610 of file Image.hpp.
ImageType [1/3]
template<typename T_Type , unsigned int T_NumComp> using sibr::ImagePtr< T_Type, T_NumComp >::ImageType = Image<T_Type, T_NumComp>
Underlying image type.
Definition at line 513 of file Image.hpp.
ImageType [2/3]
template<typename ScalarType , uint N> using sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::ImageType = sibr::Image<ScalarType, N>
Definition at line 408 of file Types.hpp.
ImageType [3/3]
template<typename ScalarType , uint N> using sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::ImageType = ImagePtr<ScalarType, N>
Definition at line 447 of file Types.hpp.
ImageUV32F
typedef Image<float, 2> sibr::ImageUV32F
Definition at line 615 of file Image.hpp.
ImageUV8
typedef Image<unsigned char, 2> sibr::ImageUV8
Definition at line 605 of file Image.hpp.
Pixel
template<typename T_Type , unsigned int T_NumComp> typedef Eigen::Matrix<T_Type, T_NumComp, 1, Eigen::DontAlign> sibr::Image< T_Type, T_NumComp >::Pixel
Definition at line 232 of file Image.hpp.
Ptr
template<typename T_Type , unsigned int T_NumComp> typedef ImagePtr<T_Type, T_NumComp> sibr::Image< T_Type, T_NumComp >::Ptr
Definition at line 230 of file Image.hpp.
Type
template<typename T_Type , unsigned int T_NumComp> typedef T_Type sibr::Image< T_Type, T_NumComp >::Type
Definition at line 229 of file Image.hpp.
Enumeration Type Documentation
anonymous enum [1/2]
template<typename T_Type , unsigned int T_NumComp> anonymous enum
Enumerator
e_NumComp
Definition at line 233 of file Image.hpp.
anonymous enum [2/2]
anonymous enum
Enumerator
type
Definition at line 42 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
type
Definition at line 48 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 137 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 149 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 161 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 173 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 185 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 197 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 209 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 221 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 233 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 245 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
type
Definition at line 54 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 257 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 286 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 298 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 310 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
type
Definition at line 60 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
type
Definition at line 66 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 77 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 89 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 101 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 113 of file Types.hpp.
anonymous enum
anonymous enum
Enumerator
internal_format
format
int_internal_format
int_format
isdepth
Definition at line 125 of file Types.hpp.
Function Documentation
bicubic()
template<typename T_Type , unsigned int T_NumComp> Eigen::Matrix< T_Type, T_NumComp, 1, Eigen::DontAlign > sibr::Image< T_Type, T_NumComp >::bicubic (const sibr::Vector2f & pixelPosition) const
Fetch bicubic interpolated value from floating point pixel coordinates.
Parameters
pixelPosition query position in [0,w[x[0,h[
Returns
the interpolated value
Definition at line 1232 of file Image.hpp.
References sibr::clamp().
bilinear()
template<typename T_Type , unsigned int T_NumComp> Eigen::Matrix< T_Type, T_NumComp, 1, Eigen::DontAlign > sibr::Image< T_Type, T_NumComp >::bilinear (const sibr::Vector2f & pixel) const
Fetch bilinear interpolated value from floating point pixel coordinates.
Parameters
pixel query position in [0,w[x[0,h[
Returns
the interpolated value
Definition at line 1195 of file Image.hpp.
blit() [1/4]
SIBR_GRAPHICS_EXPORT void sibr::blit (const IRenderTarget & src, const IRenderTarget & dst, GLbitfield mask = GL_COLOR_BUFFER_BIT, GLenum filter = GL_LINEAR)
Copy the content of a render target to another render target, resizing if needed.
Parameters
src source rendertarget
dst destination rendertarget
mask which part of the buffer to copy (color, depth, stencil).
filter filtering mode if the two rendertargets have different dimensions (linear or nearest)
Note
The blit can only happen for color attachment 0 in both src and dst.
Warning
If the mask contains the depth or stencil, filter must be GL_NEAREST
Definition at line 6 of file RenderTarget.cpp.
References ibr_preprocess_rc_to_sibr::dst, and ibr_preprocess_rc_to_sibr::src.
Referenced by sibr::blit_and_flip(), sibr::ULRV2View::onRenderIBR(), sibr::TexturedMeshView::onRenderIBR(), and sibr::ULRV3View::onRenderIBR().
blit() [2/4]
SIBR_GRAPHICS_EXPORT void sibr::blit (const IRenderTarget & src, const ITexture2D & dst, GLbitfield mask = GL_COLOR_BUFFER_BIT, GLenum filter = GL_LINEAR)
Copy the content of a rendertarget first color attachment to a texture, resizing if needed.
Parameters
src source rendertarget
dst destination texture
mask which part of the buffer to copy (color, depth, stencil).
filter filtering mode if the two buffers have different dimensions (linear or nearest)
Note
The blit can only happen for color attachment 0 in dst.
Warning
If the mask contains the depth or stencil, filter must be GL_NEAREST
Definition at line 57 of file Texture.cpp.
References ibr_preprocess_rc_to_sibr::dst, SIBR_ASSERT, and ibr_preprocess_rc_to_sibr::src.
blit() [3/4]
SIBR_GRAPHICS_EXPORT void sibr::blit (const ITexture2D & src, const IRenderTarget & dst, GLbitfield mask = GL_COLOR_BUFFER_BIT, GLenum filter = GL_LINEAR, bool flip = false)
Copy the content of a texture to a render target, resizing if needed.
Parameters
src source texture
dst destination rendertarget
mask which part of the buffer to copy (color, depth, stencil).
filter filtering mode if the two buffers have different dimensions (linear or nearest)
flip flip the texture vertically when copying it
Note
The blit can only happen for color attachment 0 in dst.
Warning
If the mask contains the depth or stencil, filter must be GL_NEAREST
Definition at line 6 of file Texture.cpp.
References ibr_preprocess_rc_to_sibr::dst, SIBR_ASSERT, and ibr_preprocess_rc_to_sibr::src.
blit() [4/4]
SIBR_GRAPHICS_EXPORT void sibr::blit (const ITexture2D & src, const ITexture2D & dst, GLbitfield mask = GL_COLOR_BUFFER_BIT, GLenum filter = GL_LINEAR)
Copy the content of a texture to another texture, resizing if needed.
Parameters
src source texture
dst destination texture
mask which part of the buffer to copy (color, depth, stencil).
filter filtering mode if the two buffers have different dimensions (linear or nearest)
Warning
If the mask contains the depth or stencil, filter must be GL_NEAREST
Definition at line 74 of file Texture.cpp.
References ibr_preprocess_rc_to_sibr::dst, SIBR_ASSERT, and ibr_preprocess_rc_to_sibr::src.
blit_and_flip() [1/2]
SIBR_GRAPHICS_EXPORT void sibr::blit_and_flip (const IRenderTarget & src, const IRenderTarget & dst, GLbitfield mask = GL_COLOR_BUFFER_BIT, GLenum filter = GL_LINEAR)
Copy the content of a render target to another render target, resizing if needed and flipping the result.
Parameters
src source rendertarget
dst destination rendertarget
mask which part of the buffer to copy (color, depth, stencil).
filter filtering mode if the two rendertargets have different dimensions (linear or nearest)
Note
The blit can only happen for color attachment 0 in both src and dst.
Warning
If the mask contains the depth or stencil, filter must be GL_NEAREST
Definition at line 15 of file RenderTarget.cpp.
References ibr_preprocess_rc_to_sibr::dst, and ibr_preprocess_rc_to_sibr::src.
blit_and_flip() [2/2]
SIBR_GRAPHICS_EXPORT void sibr::blit_and_flip (const ITexture2D & src, const IRenderTarget & dst, GLbitfield mask = GL_COLOR_BUFFER_BIT, GLenum filter = GL_LINEAR)
Copy the content of a texture to a render target, resizing if needed and flipping the result.
Parameters
src source texture
dst destination rendertarget
mask which part of the buffer to copy (color, depth, stencil).
filter filtering mode if the two buffers have different dimensions (linear or nearest)
Note
The blit can only happen for color attachment 0 in dst.
Warning
If the mask contains the depth or stencil, filter must be GL_NEAREST
Definition at line 24 of file Texture.cpp.
References sibr::blit(), ibr_preprocess_rc_to_sibr::dst, and ibr_preprocess_rc_to_sibr::src.
blitToColorAttachment()
SIBR_GRAPHICS_EXPORT void sibr::blitToColorAttachment (const ITexture2D & src, IRenderTarget & dst, int location, GLenum filter = GL_LINEAR, bool flip = false)
Copy the content of a texture to a specific color attachment of the destination render target, resizing if needed.
Parameters
src source texture
dst destination rendertarget
location the color attachment to blit to
filter filtering mode if the two buffers have different dimensions (linear or nearest)
flip flip the texture vertically when copying it
Note
No mask to specify, as this is assumed to be COLOR.
Definition at line 29 of file Texture.cpp.
References ibr_preprocess_rc_to_sibr::dst, SIBR_ASSERT, and ibr_preprocess_rc_to_sibr::src.
cartesianToSpherical()
SIBR_GRAPHICS_EXPORT sibr::Vector2d sibr::cartesianToSpherical (const sibr::Vector3d & dir)
Convert a direction from cartesian to spherical coordinates.
Parameters
dir a direction in cartesian 3D space
Returns
the spherical coordinates [phi,theta] in [-pi,pi]x[0,pi]
Warning
dir is assumed to be normalized
Definition at line 28 of file Utils.cpp.
Referenced by sibr::cartesianToSphericalUVs().
cartesianToSphericalUVs()
SIBR_GRAPHICS_EXPORT sibr::Vector2d sibr::cartesianToSphericalUVs (const sibr::Vector3d & dir)
Convert a direction from cartesian to spherical UVs.
Parameters
dir a direction in cartesian 3D space
Returns
the spherical UVs [u,v] in [0,1]^2
Warning
dir is assumed to be normalized
Definition at line 40 of file Utils.cpp.
References sibr::cartesianToSpherical().
cast()
template<typename T_Type , unsigned int T_NumComp> template<class T_Image > T_Image sibr::Image< T_Type, T_NumComp >::cast () const inline
Cast into another image type.
Returns
the converted image
Definition at line 466 of file Image.hpp.
Referenced by distPatch(), sibr::VideoUtils::getBackGroundVideo(), and sibr::VideoUtils::getTemporalSpatialRatio().
clamp()
template<typename T > T sibr::clamp (T value, T min, T max) inline
Clamp a value.
Parameters
value value to clamp
min min value
max max value
Returns
min(max(value, min), max)
Definition at line 96 of file Config.hpp.
Referenced by sibr::Image< T_Type, T_NumComp >::bicubic(), sibr::VideoUtils::getBackGroundVideo(), sibr::TimeHistogram::getBinMiddle(), sibr::getLinearColorFromProbaV(), sibr::MeshTexturing::interpolate(), sibr::ULRV2View::onGUI(), sibr::ULRV3View::onGUI(), sibr::InteractiveCameraHandler::onGUI(), sibr::Window::setup(), sibr::slice(), sibr::InteractiveCameraHandler::snapToCamera(), sibr::GridMapping::updateZoomBox(), sibr::TimeHistogram::whatBin(), and sibr::Histogram< T, N >::whatBin().
clone()
template<typename T_Type , unsigned int T_NumComp> Image< T_Type, T_NumComp > sibr::Image< T_Type, T_NumComp >::clone (void) const
Returns
a deep copy of the image.
Definition at line 811 of file Image.hpp.
References sibr::Image< T_Type, T_NumComp >::_pixels.
Referenced by sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::flip(), sibr::ImagePtr< T_Type, T_NumComp >::fromImg(), sibr::MeshTexturing::getTexture(), main(), and sibr::TextureCubeMap< T_Type, T_NumComp >::sendCubeMap().
clonePtr()
template<typename T_Type , unsigned int T_NumComp> ImagePtr< T_Type, T_NumComp > sibr::Image< T_Type, T_NumComp >::clonePtr (void) const
Returns
a pointer to a deep copy of the image.
Definition at line 818 of file Image.hpp.
Referenced by loadRawRC().
color() [1/3]
template<typename T_Type , unsigned int T_NumComp> Image< T_Type, T_NumComp >::Pixel sibr::Image< T_Type, T_NumComp >::color (const ColorRGBA & rgba) static
Helper to convert a 4 components float vector (in 0,1) to the proper pixel format.
Parameters
rgba the value to convert
Returns
the converted value
Definition at line 1107 of file Image.hpp.
color() [2/3]
template<typename T_Type , unsigned int T_NumComp> ColorRGBA sibr::Image< T_Type, T_NumComp >::color (uint x, uint y) const
Convert a pixel value to a 4 components float vector (in 0,1).
Parameters
x x coordinate
y y coordinate
Returns
the normalized expanded value
Definition at line 1070 of file Image.hpp.
References SIBR_ASSERT.
Referenced by sibr::RenderTarget< T_Type, T_NumComp >::readBackDepth(), and sibr::showDepthFromAlpha().
color() [3/3]
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::color (uint x, uint y, const ColorRGBA & c)
Set a pixel value from 4 components float vector (in 0,1).
Parameters
x x coordinate
y y coordinate
c the new value
Definition at line 1079 of file Image.hpp.
References SIBR_ASSERT.
coloredClass() [1/2]
SIBR_GRAPHICS_EXPORT Image< unsigned char, 3 > sibr::coloredClass (const Image< int, 1 >::Ptr imClass)
Convert an integer ID map to a colored image using a different random color for each ID.
Note that 255 is black.
Parameters
imClass the ID map
Returns
a color coded map
Definition at line 202 of file Image.cpp.
coloredClass() [2/2]
SIBR_GRAPHICS_EXPORT Image< unsigned char, 3 > sibr::coloredClass (const Image< unsigned char, 1 >::Ptr imClass)
Convert an integer ID map to a colored image using a different random color for each ID.
Note that 255 is black.
Parameters
imClass the ID map
Returns
a color coded map
Definition at line 178 of file Image.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), and sibr::Image< T_Type, T_NumComp >::w().
convertBGR2RGB()
SIBR_GRAPHICS_EXPORT void sibr::opencv::convertBGR2RGB (cv::Mat & dst)
Convert a BGR cv::Mat into a RGB cv::Mat, in-place.
Parameters
dst the matrix to convert
Definition at line 26 of file Image.cpp.
Referenced by sibr::Image< T_Type, T_NumComp >::fromOpenCVBGR(), and sibr::Image< T_Type, T_NumComp >::load().
convertL32FtoRGBA()
SIBR_GRAPHICS_EXPORT sibr::ImageRGBA sibr::convertL32FtoRGBA (const sibr::ImageL32F & imgF)
Convert a L32F into a RGBA image while preserving bit-level representation.
Useful to save float maps as PNG, and benefit from PNG compression on disk.
Parameters
imgF the image to convert
Returns
the packed RGBA image
Definition at line 58 of file Image.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), and sibr::Image< T_Type, T_NumComp >::w().
Referenced by sibr::ULRV2View::computeVisibilityMap().
convertNormalMapToSphericalHalf()
SIBR_GRAPHICS_EXPORT sibr::ImageRGBA sibr::convertNormalMapToSphericalHalf (const sibr::ImageRGB32F & imgF)
Convert a RGB32 normal map into a UV16 map storing theta and phi as half floats, packed into a RGBA8.
Parameters
imgF the XYZ normal map
Returns
the packed theta,phi normal map
Definition at line 121 of file Image.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), and sibr::Image< T_Type, T_NumComp >::w().
convertRGB2BGR()
SIBR_GRAPHICS_EXPORT void sibr::opencv::convertRGB2BGR (cv::Mat & dst)
Convert a BGR cv::Mat into a RGB cv::Mat, in-place.
Parameters
dst the matrix to convert
Definition at line 41 of file Image.cpp.
Referenced by sibr::Image< T_Type, T_NumComp >::toOpenCVBGR().
convertRGB32FtoRGBA()
SIBR_GRAPHICS_EXPORT sibr::ImageRGBA sibr::convertRGB32FtoRGBA (const sibr::ImageRGB32F & imgF)
Convert a RGB32F into a RGBA image (3 times wider) while preserving bit-level representation.
Useful to save float maps as PNG, and benefit from PNG compression on disk.
Parameters
imgF the image to convert
Returns
the packed RGBA image
Definition at line 87 of file Image.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), and sibr::Image< T_Type, T_NumComp >::w().
convertRGBAtoL32F()
SIBR_GRAPHICS_EXPORT sibr::ImageL32F sibr::convertRGBAtoL32F (const sibr::ImageRGBA & imgRGBA)
Convert a RGBA into a L32F image while preserving bit-level representation.
Useful to decode float maps stored as as PNG.
Parameters
imgRGBA the image to convert
Returns
the unpacked float image
Definition at line 72 of file Image.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), and sibr::Image< T_Type, T_NumComp >::w().
Referenced by legacyV2main().
convertRGBAtoRGB32F()
SIBR_GRAPHICS_EXPORT sibr::ImageRGB32F sibr::convertRGBAtoRGB32F (const sibr::ImageRGBA & imgRGBA)
Convert a RGBA into a RGB32F image while preserving bit-level representation.
Useful to decode float maps stored as as PNG.
Parameters
imgRGBA the image to convert
Returns
the unpacked float image
Definition at line 104 of file Image.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), and sibr::Image< T_Type, T_NumComp >::w().
convertSphericalHalfToNormalMap()
SIBR_GRAPHICS_EXPORT sibr::ImageRGB32F sibr::convertSphericalHalfToNormalMap (const sibr::ImageRGBA & imgF)
Convert a RGBA map, packing theta and phi as half floats, into a RGB32 normal map.
Parameters
imgF packed theta,phi normal map
Returns
the XYZ normal map
Definition at line 148 of file Image.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), and sibr::Image< T_Type, T_NumComp >::w().
cv_type()
template<typename ScalarType , uint N> static uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::cv_type () inline static
Returns
the matrix OpenCV type.
Definition at line 524 of file Types.hpp.
References sibr::Key::N.
data() [1/7]
template<typename ScalarType , uint N> static const void* sibr::GLTexFormat< cv::Mat, ScalarType, N >::data (const cv::Mat & img) inline static
Get an image data.
Parameters
img the image
Returns
pointer to the beginning of the data.
Definition at line 514 of file Types.hpp.
data() [2/7]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> static const void* sibr::GLTexFormat< ImageType, ScalarType, N >::data (const ImageType & img) static
Get an image data.
Parameters
img the image
Returns
pointer to the beginning of the data.
data() [3/7]
template<typename ScalarType , uint N> static const void* sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::data (const ImageType & img) inline static
Get an image data.
Parameters
img the image
Returns
pointer to the beginning of the data.
Definition at line 433 of file Types.hpp.
References sibr::Image< T_Type, T_NumComp >::data().
data() [4/7]
template<typename ScalarType , uint N> static const void* sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::data (const ImageType & img) inline static
Get an image data.
Parameters
img the image
Returns
pointer to the beginning of the data.
Definition at line 472 of file Types.hpp.
data() [5/7]
template<typename ScalarType , uint N> static void* sibr::GLTexFormat< cv::Mat, ScalarType, N >::data (cv::Mat & img) inline static
Get an image data.
Parameters
img the image
Returns
pointer to the beginning of the data.
Definition at line 519 of file Types.hpp.
data() [6/7]
template<typename T_Type , unsigned int T_NumComp> void * sibr::Image< T_Type, T_NumComp >::data (void)
Returns
a pointer to the raw image data.
Definition at line 755 of file Image.hpp.
References SIBR_ASSERT.
data() [7/7]
template<typename T_Type , unsigned int T_NumComp> const void * sibr::Image< T_Type, T_NumComp >::data (void) const
Returns
a pointer to the raw image data.
Definition at line 749 of file Image.hpp.
References SIBR_ASSERT.
Referenced by sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::data(), sibr::RenderTarget< T_Type, T_NumComp >::readBack(), sibr::Texture2D< T_Type, T_NumComp >::readBack(), sibr::RenderTarget< T_Type, T_NumComp >::readBackDepth(), sibr::TextureCubeMap< T_Type, T_NumComp >::sendCubeMap(), and sibr::show().
duplicate3()
SIBR_GRAPHICS_EXPORT cv::Mat sibr::duplicate3 (cv::Mat c)
Create a three channels cv::Mat by repeating a single channel cv::Mat.
Parameters
c the input cv::Mat
Returns
a three channels cv::Mat
Definition at line 268 of file Image.cpp.
findMinMax()
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::findMinMax (Pixel & minImage, Pixel & maxImage)
Find the component-wise minimum and maximum values contained in the image.
Parameters
minImage will contain the minimum value
maxImage will contain the maximum value
Definition at line 1159 of file Image.hpp.
fitImageToDisplayRegion()
SIBR_GRAPHICS_EXPORT void sibr::fitImageToDisplayRegion (const Vector2f & imgSize, const Vector2i & regionSize, Vector2f & offset, Vector2f & size)
Helper that compute the location and extent to display an image in a given region without cropping or distorting it.
Parameters
imgSize the image size
regionSize the region size
offset will containg the top-left corner location
size will contain the size to use
Definition at line 117 of file GUI.cpp.
Referenced by sibr::showImGuiWindow().
flip() [1/4]
template<typename ScalarType , uint N> static cv::Mat sibr::GLTexFormat< cv::Mat, ScalarType, N >::flip (const cv::Mat & img) inline static
Flip an image.
Parameters
img image to flip
Returns
the fliped image.
Definition at line 490 of file Types.hpp.
flip() [2/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> static ImageType sibr::GLTexFormat< ImageType, ScalarType, N >::flip (const ImageType & img) static
Flip an image.
Parameters
img image to flip
Returns
the fliped image.
flip() [3/4]
template<typename ScalarType , uint N> static ImageType sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::flip (const ImageType & img) inline static
Flip an image.
Parameters
img image to flip
Returns
the fliped image.
Definition at line 411 of file Types.hpp.
References sibr::Image< T_Type, T_NumComp >::clone(), and sibr::Image< T_Type, T_NumComp >::flipH().
flip() [4/4]
template<typename ScalarType , uint N> static ImageType sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::flip (const ImageType & img) inline static
Flip an image.
Parameters
img image to flip
Returns
the fliped image.
Definition at line 450 of file Types.hpp.
flipH() [1/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::flipH (void) virtual
Flip the image along the horizontal axis.
Implements sibr::IImage.
Definition at line 1150 of file Image.hpp.
Referenced by sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::flip(), sibr::RGBDInputTextures::initializeImageRenderTargets(), sibr::RenderTarget< T_Type, T_NumComp >::readBack(), sibr::Texture2D< T_Type, T_NumComp >::readBack(), sibr::TextureCubeMap< T_Type, T_NumComp >::sendCubeMap(), and sibr::RenderMaskHolder::uploadMaskGPU().
flipH() [2/2]
virtual void sibr::IImage::flipH (void) pure virtual
Flip the image along the horizontal axis.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
flipV() [1/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::flipV (void) virtual
Flip the image along the vertical axis.
Implements sibr::IImage.
Definition at line 1154 of file Image.hpp.
flipV() [2/2]
virtual void sibr::IImage::flipV (void) pure virtual
Flip the image along the vertical axis.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
fromImg()
template<typename T_Type , unsigned int T_NumComp> static ImagePtr sibr::ImagePtr< T_Type, T_NumComp >::fromImg (const ImageType & img) inline static
Generate a pointer by cloning an image.
Parameters
img the image to clone
Returns
the pointer
Definition at line 534 of file Image.hpp.
References sibr::Image< T_Type, T_NumComp >::clone(), and sibr::ImagePtr< T_Type, T_NumComp >::ImagePtr().
fromOpenCV() [1/3]
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::fromOpenCV (const cv::Mat & img) virtual
Replace the content of the image with the content of another matrix.
Parameters
img the new matrix
Implements sibr::IImage.
Definition at line 775 of file Image.hpp.
References sibr::opencv::imageTypeCVRange().
Referenced by sibr::ULRV2View::computeVisibilityMap(), sibr::RenderMaskHolder::loadMasks(), sibr::RenderTarget< T_Type, T_NumComp >::readBack(), and tonemap().
fromOpenCV() [2/3]
virtual void sibr::IImage::fromOpenCV (const cv::Mat & img) pure virtual
Replace the content of the image with the content of another matrix.
Parameters
img the new matrix
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
fromOpenCV() [3/3]
template<typename sibr_T , typename openCV_T , int N> Vector<sibr_T, N> sibr::fromOpenCV (const cv::Vec< openCV_T, N > & vec) inline
Definition at line 1269 of file Image.hpp.
References sibr::Key::N.
Referenced by sibr::Image< T_Type, T_NumComp >::fromOpenCVBGR(), and sibr::Image< T_Type, T_NumComp >::load().
fromOpenCVBGR() [1/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::fromOpenCVBGR (const cv::Mat & img) virtual
Replace the content of the image with the content of another matrix, flipping channels.
Parameters
img the new matrix
Note
Only applies to 3 and 4 channel images.
Implements sibr::IImage.
Definition at line 768 of file Image.hpp.
References sibr::opencv::convertBGR2RGB(), and sibr::fromOpenCV().
Referenced by sibr::showFloat().
fromOpenCVBGR() [2/2]
virtual void sibr::IImage::fromOpenCVBGR (const cv::Mat & img) pure virtual
Replace the content of the image with the content of another matrix, flipping channels.
Parameters
img the new matrix
Note
Only applies to 3 and 4 channel images.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
generateMeshForText()
SIBR_GRAPHICS_EXPORT Mesh::Ptr sibr::generateMeshForText (const std::string & text, unsigned int & separationIndex)
Generate a mesh for a given label, using ImGui internally.
This will generate a mesh that contain both the background and foreground geometry packed together sequentially.
Parameters
text the text to generate the label of
separationIndex will contain the location of the first triangle of the foreground mesh
Returns
the mesh containing first the background triangles then the foreground triangles
Definition at line 61 of file GUI.cpp.
References sibr::Key::End.
Referenced by sibr::LabelsManager::setupLabelsManagerMeshes().
get()
template<typename T_Type , unsigned int T_NumComp> Image<T_Type, T_NumComp>* sibr::ImagePtr< T_Type, T_NumComp >::get () inline
Returns
the image
Definition at line 542 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
get_jpeg_size()
sibr::Vector2i sibr::IImage::get_jpeg_size (std::ifstream & file) static
Get the size of jpeg image file by reading its header.
Parameters
file the input filestream, already opened.
Returns
The size (width,heighgt) else (-1, -1) if the header cannot be read .
Definition at line 277 of file Image.cpp.
Referenced by sibr::IImage::imageResolution().
getLinearColorFromProbaV()
SIBR_GRAPHICS_EXPORT sibr::Vector3ub sibr::getLinearColorFromProbaV (double proba)
Generate a color for a given scalar score, using a reversible mapping.
Parameters
proba the probability value
Returns
the associated color
Definition at line 13 of file Utils.cpp.
References sibr::clamp().
getProbaFromLinearColor()
SIBR_GRAPHICS_EXPORT double sibr::getProbaFromLinearColor (const sibr::Vector3ub & color)
Convert a color to the associated scalar score, using a reversible mapping.
Parameters
color the color
Returns
the probability value
Definition at line 21 of file Utils.cpp.
GetTitleBarHeight()
SIBR_GRAPHICS_EXPORT const float ImGui::GetTitleBarHeight ()
Returns
the height of the title bar (for layout)
Definition at line 309 of file GUI.cpp.
Referenced by sibr::MultiViewBase::addIBRSubView(), sibr::MultiViewBase::addSubView(), sibr::MultiViewBase::mosaicLayout(), sibr::MultiViewManager::onGui(), sibr::FPSCounter::render(), and sibr::showImGuiWindow().
h() [1/2]
template<typename T_Type , unsigned int T_NumComp> uint sibr::Image< T_Type, T_NumComp >::h (void) const virtual
Returns
the image height.
Implements sibr::IImage.
Definition at line 1130 of file Image.hpp.
Referenced by assignImages(), sibr::DistordCropUtility::Bounds::Bounds(), sibr::coloredClass(), sibr::ULRV2View::computeVisibilityMap(), sibr::convertL32FtoRGBA(), sibr::convertNormalMapToSphericalHalf(), sibr::convertRGB32FtoRGBA(), sibr::convertRGBAtoL32F(), sibr::convertRGBAtoRGB32F(), sibr::convertSphericalHalfToNormalMap(), sibr::TextureCubeMap< T_Type, T_NumComp >::createFromImages(), sibr::MeshTexturing::floodFill(), sibr::DistordCropUtility::getBounds(), sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::height(), sibr::MeshTexturing::hitTest(), sibr::Image< float, 3 >::isInRange(), sibr::lin2sRGB(), main(), sibr::RenderTarget< T_Type, T_NumComp >::readBackDepth(), sibr::MeshTexturing::reproject(), sibr::TextureCubeMap< T_Type, T_NumComp >::sendCubeMap(), sibr::showDepthFromAlpha(), sibr::showFloat(), sibr::sRGB2Lin(), and sibr::RenderMaskHolder::uploadMaskGPU().
h() [2/2]
virtual uint sibr::IImage::h (void) const pure virtual
Returns
the image height.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
height() [1/4]
template<typename ScalarType , uint N> static uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::height (const cv::Mat & img) inline static
Get an image height.
Parameters
img the image
Returns
the height
Definition at line 509 of file Types.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
height() [2/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> static uint sibr::GLTexFormat< ImageType, ScalarType, N >::height (const ImageType & img) static
Get an image height.
Parameters
img the image
Returns
the height
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
height() [3/4]
template<typename ScalarType , uint N> static uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::height (const ImageType & img) inline static
Get an image height.
Parameters
img the image
Returns
the height
Definition at line 428 of file Types.hpp.
References sibr::Image< T_Type, T_NumComp >::h().
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
height() [4/4]
template<typename ScalarType , uint N> static uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::height (const ImageType & img) inline static
Get an image height.
Parameters
img the image
Returns
the height
Definition at line 467 of file Types.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
Image() [1/6]
template<typename T_Type , unsigned int T_NumComp> sibr::Image< T_Type, T_NumComp >::Image (const Image< T_Type, T_NumComp > & other) delete
Disallow copy constructor.
Parameters
other image to copy
Image() [2/6]
template<typename T_Type , unsigned int T_NumComp> sibr::Image< T_Type, T_NumComp >::Image (Image< T_Type, T_NumComp > && other)
Move constructor.
Parameters
other image to move, don't use after move
Definition at line 738 of file Image.hpp.
Image() [3/6]
template<typename T_Type , unsigned int T_NumComp> sibr::Image< T_Type, T_NumComp >::Image (uint width, uint height)
Constructor.
Parameters
width image width
height image height
Warning
The image content will be undefined.
Definition at line 719 of file Image.hpp.
Image() [4/6]
template<typename T_Type , unsigned int T_NumComp> sibr::Image< T_Type, T_NumComp >::Image (uint width, uint height, const Pixel & init)
Constructor.
Parameters
width image width
height image height
init default value to use for all pixels
Definition at line 727 of file Image.hpp.
Image() [5/6]
template<typename T_Type , unsigned int T_NumComp> sibr::Image< T_Type, T_NumComp >::Image (uint width, uint height, const T_Type & init)
Constructor.
Parameters
width image width
height image height
init default value to use for all components of all pixels
Definition at line 723 of file Image.hpp.
Image() [6/6]
template<typename T_Type , unsigned int T_NumComp> sibr::Image< T_Type, T_NumComp >::Image (void)
Default constructor.
Definition at line 715 of file Image.hpp.
ImagePtr() [1/3]
template<typename T_Type , unsigned int T_NumComp> sibr::ImagePtr< T_Type, T_NumComp >::ImagePtr () inline
Default constructor.
Definition at line 518 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
Referenced by sibr::ImagePtr< T_Type, T_NumComp >::fromImg().
ImagePtr() [2/3]
template<typename T_Type , unsigned int T_NumComp> sibr::ImagePtr< T_Type, T_NumComp >::ImagePtr (const std::shared_ptr< Image< T_Type, T_NumComp >> & imgPtr) inline
Constructor from a shared pointer.
Parameters
imgPtr the shared pointer to wrap
Definition at line 528 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
ImagePtr() [3/3]
template<typename T_Type , unsigned int T_NumComp> sibr::ImagePtr< T_Type, T_NumComp >::ImagePtr (Image< T_Type, T_NumComp > * imgPtr) inline
Constructor from a raw pointer.
Parameters
imgPtr the raw pointer to wrap
Definition at line 523 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
imageResolution()
sibr::Vector2i sibr::IImage::imageResolution (const std::string & file_path) static
Get the size of an image file from its header.
Supported file type: {png, jpg, jpeg, bmp, tga}.
Parameters
file_path the input file path
Returns
The size (width,heighgt) else (-1, -1) if the header cannot be read .
Definition at line 313 of file Image.cpp.
References get_image_size::BMP, sibr::IImage::get_jpeg_size(), sibr::getExtension(), get_image_size::JPEG, sibr::ByteStream::ntohl(), get_image_size::PNG, and sibr::to_lower().
Referenced by sibr::InputCamera::loadNVM().
imageType()
template<typename T_Type > SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType (void)
Returns
the OpenCV type corresponding to a C type.
imageType< double >()
template<> SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< double > (void) inline
Returns
the OpenCV type corresponding to a C type.
Definition at line 57 of file Image.hpp.
imageType< float >()
template<> SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< float > (void) inline
Returns
the OpenCV type corresponding to a C type.
Definition at line 55 of file Image.hpp.
imageType< int16 >()
template<> SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< int16 > (void) inline
Returns
the OpenCV type corresponding to a C type.
Definition at line 51 of file Image.hpp.
imageType< int32 >()
template<> SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< int32 > (void) inline
Returns
the OpenCV type corresponding to a C type.
Definition at line 53 of file Image.hpp.
imageType< int8 >()
template<> SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< int8 > (void) inline
Returns
the OpenCV type corresponding to a C type.
Definition at line 47 of file Image.hpp.
imageType< uint16 >()
template<> SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< uint16 > (void) inline
Returns
the OpenCV type corresponding to a C type.
Definition at line 49 of file Image.hpp.
imageType< uint8 >()
template<> SIBR_GRAPHICS_EXPORT int sibr::opencv::imageType< uint8 > (void) inline
Returns
the OpenCV type corresponding to a C type.
Definition at line 45 of file Image.hpp.
imageTypeCVRange()
SIBR_GRAPHICS_EXPORT float sibr::opencv::imageTypeCVRange (int cvDepth)
Get the size of the range of values an OpenCV type can take.
Parameters
cvDepth the OpenCV type depth
Returns
the size of the range
Definition at line 10 of file Image.cpp.
References sibr::opencv::imageTypeRange< double >(), and sibr::opencv::imageTypeRange< float >().
Referenced by sibr::Image< T_Type, T_NumComp >::fromOpenCV().
imageTypeRange()
template<typename T_Type > float sibr::opencv::imageTypeRange (void) inline
Returns
the size of the range of values a type can take when used in OpenCV.
Definition at line 61 of file Image.hpp.
imageTypeRange< double >()
template<> SIBR_GRAPHICS_EXPORT float sibr::opencv::imageTypeRange< double > (void) inline
Returns
the size of the range of values a type can take when used in OpenCV.
Definition at line 67 of file Image.hpp.
Referenced by sibr::opencv::imageTypeCVRange().
imageTypeRange< float >()
template<> SIBR_GRAPHICS_EXPORT float sibr::opencv::imageTypeRange< float > (void) inline
Returns
the size of the range of values a type can take when used in OpenCV.
Definition at line 65 of file Image.hpp.
Referenced by sibr::opencv::imageTypeCVRange().
inRange()
template<typename T_Type , unsigned int T_NumComp> template<typename T > bool sibr::Image< T_Type, T_NumComp >::inRange (T x, T y) const inline
Check if a pixel (x,y) is inside the image boundaries.
Parameters
x x coordinate
y y coordinate
Returns
true if 0<=x<w and 0<=y=<h
Todo:
Duplicate call used in inpainting, remove.
Definition at line 409 of file Image.hpp.
inverseLerp()
float sibr::inverseLerp (float from, float to, float current) inline
Express a value as the linear combination of two other values.
Parameters
from first value
to second value
current value to express as a combination
Returns
the interpolation factor
Definition at line 126 of file Utils.hpp.
Referenced by sibr::IBRBasicUtils::selectCamerasAngleWeight().
isInRange() [1/4]
virtual bool sibr::IImage::isInRange (const ::sibr::Vector2i & xy) const pure virtual
Check if a pixel (x,y) is inside the image boundaries.
Parameters
xy the pixel coordinates
Returns
true if 0<=x<w and 0<=y=<h
isInRange() [2/4]
template<typename T_Type , unsigned int T_NumComp> bool sibr::Image< T_Type, T_NumComp >::isInRange (const sibr::Vector2f & xy) const inline
Check if a pixel (x,y) is inside the image boundaries.
Parameters
xy the pixel coordinates
Returns
true if 0<=x<w and 0<=y=<h
Definition at line 419 of file Image.hpp.
isInRange() [3/4]
template<typename T_Type , unsigned int T_NumComp> bool sibr::Image< T_Type, T_NumComp >::isInRange (const sibr::Vector2i & xy) const inline
Check if a pixel (x,y) is inside the image boundaries.
Parameters
xy the pixel coordinates
Returns
true if 0<=x<w and 0<=y=<h
Definition at line 414 of file Image.hpp.
isInRange() [4/4]
template<typename T_Type , unsigned int T_NumComp> template<typename T > bool sibr::Image< T_Type, T_NumComp >::isInRange (T x, T y) const inline
Check if a pixel (x,y) is inside the image boundaries.
Parameters
x x coordinate
y y coordinate
Returns
true if 0<=x<w and 0<=y=<h
Definition at line 400 of file Image.hpp.
Referenced by sibr::ULRV2View::computeVisibilityMap(), distPatch(), sibr::DistordCropUtility::getBounds(), sibr::Image< float, 3 >::inRange(), and main().
jetColor()
SIBR_GRAPHICS_EXPORT cv::Scalar sibr::jetColor (float gray)
Generate a color for a given scalar score, using the jet color map.
Generate a jet color associated to the input probability, as a 3-channels cv::Scalar.
Parameters
gray the probability value
Returns
the associated jet color.
Definition at line 8 of file Utils.cpp.
lerp()
float sibr::lerp (float A, float B, float fac) inline
Interpolate between two values.
Parameters
A first value
B second value
fac interpolation factor
Returns
A+fac*(B-A)
Definition at line 116 of file Utils.hpp.
References sibr::Key::A, and sibr::Key::B.
Referenced by sibr::slerp().
lin2sRGB()
SIBR_GRAPHICS_EXPORT void sibr::lin2sRGB (sibr::ImageRGB32F & img)
Inplace conversion of a float image from linear space to sRGB.
Parameters
img the image to convert
Definition at line 80 of file Utils.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), sibr::lin2sRGBF(), and sibr::Image< T_Type, T_NumComp >::w().
load() [1/2]
template<typename T_Type , unsigned int T_NumComp> bool sibr::Image< T_Type, T_NumComp >::load (const std::string & filename, bool verbose = true, bool warning_if_not_found = true) virtual
Load an image from the disk (png, jpeg, exr, etc., see OpenCV cv::imread documentation for more details).
Parameters
filename the path to the file
verbose display additional informations
warning_if_not_found log if the file doesn't exist, even if verbose is set to false
Returns
a success flag
Implements sibr::IImage.
Definition at line 825 of file Image.hpp.
References sibr::opencv::convertBGR2RGB(), sibr::fromOpenCV(), SIBR_LOG, and SIBR_WRG.
Referenced by sibr::BasicIBRScene::createFromData(), sibr::InputCamera::loadBundleFRIBR(), sibr::RenderMaskHolder::loadMasks(), loadRawRC(), and main().
load() [2/2]
virtual bool sibr::IImage::load (const std::string & filename, bool verbose = true, bool warning_if_not_found = true) pure virtual
Load an image from the disk (png, jpeg, exr, etc., see OpenCV cv::imread documentation for more details).
Parameters
filename the path to the file
verbose display additional informations
warning_if_not_found log if the file doesn't exist, even if verbose is set to false
Returns
a success flag
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
loadByteStream() [1/2]
template<typename T_Type , unsigned int T_NumComp> bool sibr::Image< T_Type, T_NumComp >::loadByteStream (const std::string & filename, bool verbose = true) virtual
Load an image from the disk (stored as a raw binary blob).
Parameters
filename the path to the file
verbose display additional informations
Returns
a success flag
Implements sibr::IImage.
Definition at line 847 of file Image.hpp.
References sibr::ByteStream::load(), SIBR_LOG, and SIBR_WRG.
loadByteStream() [2/2]
virtual bool sibr::IImage::loadByteStream (const std::string & filename, bool verbose = true) pure virtual
Load an image from the disk (stored as a raw binary blob).
Parameters
filename the path to the file
verbose display additional informations
Returns
a success flag
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
loadFile()
SIBR_GRAPHICS_EXPORT std::string sibr::loadFile (const std::string & filename, const GLShader::Define::List & defines)
Load a file from disk and apply macro-like substitutions.
Parameters
filename the file path
defines a list of substitutions to apply
Returns
the loaded string
Definition at line 264 of file Shader.cpp.
References ibr_convert_old_to_new::line, sibr::split(), and sibr::strRemoveSpaces().
Referenced by sibr::AddShadowRenderer::AddShadowRenderer(), sibr::BlurRenderer::BlurRenderer(), sibr::ColoredMeshRenderer::ColoredMeshRenderer(), sibr::CopyRenderer::CopyRenderer(), sibr::DepthRenderer::DepthRenderer(), sibr::ImageView::ImageView(), sibr::DepthInputTextureArray::initDepthTextureArrays(), sibr::RGBDInputTextures::initializeDepthRenderTargets(), sibr::RGBDInputTextures::initializeImageRenderTargets(), sibr::ImageCamViewer::initImageCamShaders(), sibr::MultiMeshManager::initShaders(), sibr::Skybox::load(), sibr::MonoRdrMode::MonoRdrMode(), sibr::NormalRenderer::NormalRenderer(), sibr::PoissonRenderer::PoissonRenderer(), sibr::PositionRenderer::PositionRenderer(), sibr::LabelsManager::setupLabelsManagerShader(), sibr::ULRV3Renderer::setupShaders(), sibr::ULRV2Renderer::setupULRshader(), sibr::ShadowMapRenderer::ShadowMapRenderer(), sibr::StereoAnaglyphRdrMode::StereoAnaglyphRdrMode(), sibr::TexturedMeshRenderer::TexturedMeshRenderer(), sibr::ULRRenderer::ULRRenderer(), and sibr::RenderMaskHolder::uploadMaskGPU().
monoCubic()
template<typename T_Type , unsigned int T_NumComp> Eigen::Matrix< float, T_NumComp, 1, Eigen::DontAlign > sibr::Image< T_Type, T_NumComp >::monoCubic (float t, const Eigen::Matrix< float, T_NumComp, 4, Eigen::DontAlign > & colors) static protected
Helper for bicubic interpolation.
Parameters
t blend factor
colors colors at the four corners
Returns
interpolated value
Definition at line 1219 of file Image.hpp.
References sibr::Key::M.
numComp() [1/2]
template<typename T_Type , unsigned int T_NumComp> uint sibr::Image< T_Type, T_NumComp >::numComp (void) const virtual
Returns
the number of components of the image.
Implements sibr::IImage.
Definition at line 1140 of file Image.hpp.
numComp() [2/2]
virtual uint sibr::IImage::numComp (void) const pure virtual
Returns
the number of components of the image.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
opencvType() [1/2]
template<typename T_Type , unsigned int T_NumComp> int sibr::Image< T_Type, T_NumComp >::opencvType (void) const inline virtual
Returns
the image OpenCV type.
Implements sibr::IImage.
Definition at line 434 of file Image.hpp.
opencvType() [2/2]
virtual int sibr::IImage::opencvType (void) const pure virtual
Returns
the image OpenCV type.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
operator bool() [1/2]
template<typename T_Type , unsigned int T_NumComp> sibr::ImagePtr< T_Type, T_NumComp >::operator bool () inline
Returns
true if the image pointer is initialized.
Definition at line 589 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
operator bool() [2/2]
template<typename T_Type , unsigned int T_NumComp> sibr::ImagePtr< T_Type, T_NumComp >::operator bool () const inline
Returns
true if the image pointer is initialized.
Definition at line 592 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
operator()() [1/10]
template<typename T_Type , unsigned int T_NumComp> Pixel& sibr::Image< T_Type, T_NumComp >::operator() (const ::sibr::Vector2f & xy)
Pixel accessor.
Parameters
xy pixel coordinates
Returns
a reference to the pixel value.
operator()() [2/10]
template<typename T_Type , unsigned int T_NumComp> const Pixel& sibr::Image< T_Type, T_NumComp >::operator() (const ::sibr::Vector2f & xy) const
Pixel accessor.
Parameters
xy pixel coordinates
Returns
a reference to the pixel value.
operator()() [3/10]
template<typename T_Type , unsigned int T_NumComp> Image< T_Type, T_NumComp >::Pixel & sibr::Image< T_Type, T_NumComp >::operator() (const sibr::Vector2i & xy) inline
Pixel accessor.
Parameters
xy pixel coordinates
Returns
a reference to the pixel value.
Definition at line 1051 of file Image.hpp.
References xy().
operator()() [4/10]
template<typename T_Type , unsigned int T_NumComp> Image< T_Type, T_NumComp >::Pixel & sibr::ImagePtr< T_Type, T_NumComp >::operator() (const sibr::Vector2i & xy) inline
Pixel accessor.
Parameters
xy pixel coordinates
Returns
a reference to the pixel value.
Definition at line 1055 of file Image.hpp.
References xy().
operator()() [5/10]
template<typename T_Type , unsigned int T_NumComp> const Image< T_Type, T_NumComp >::Pixel & sibr::Image< T_Type, T_NumComp >::operator() (const sibr::Vector2i & xy) const inline
Pixel accessor.
Parameters
xy pixel coordinates
Returns
a reference to the pixel value.
Definition at line 1041 of file Image.hpp.
References xy().
operator()() [6/10]
template<typename T_Type , unsigned int T_NumComp> const Image< T_Type, T_NumComp >::Pixel & sibr::ImagePtr< T_Type, T_NumComp >::operator() (const sibr::Vector2i & xy) const inline
Pixel accessor.
Parameters
xy pixel coordinates
Returns
a reference to the pixel value.
Definition at line 1045 of file Image.hpp.
References xy().
operator()() [7/10]
template<typename T_Type , unsigned int T_NumComp> Image< T_Type, T_NumComp >::Pixel & sibr::Image< T_Type, T_NumComp >::operator() (uint x, uint y) inline
Pixel accessor.
Parameters
x x coordinate
y y coordinate
Returns
a reference to the pixel value.
Definition at line 1023 of file Image.hpp.
References SIBR_ASSERT.
operator()() [8/10]
template<typename T_Type , unsigned int T_NumComp> Image< T_Type, T_NumComp >::Pixel & sibr::ImagePtr< T_Type, T_NumComp >::operator() (uint x, uint y) inline
Pixel accessor.
Parameters
x x coordinate
y y coordinate
Returns
a reference to the pixel value.
Definition at line 1034 of file Image.hpp.
operator()() [9/10]
template<typename T_Type , unsigned int T_NumComp> const Image< T_Type, T_NumComp >::Pixel & sibr::Image< T_Type, T_NumComp >::operator() (uint x, uint y) const inline
Pixel accessor.
Parameters
x x coordinate
y y coordinate
Returns
a reference to the pixel value.
Definition at line 1006 of file Image.hpp.
References SIBR_ASSERT.
operator()() [10/10]
template<typename T_Type , unsigned int T_NumComp> const Image< T_Type, T_NumComp >::Pixel & sibr::ImagePtr< T_Type, T_NumComp >::operator() (uint x, uint y) const inline
Pixel accessor.
Parameters
x x coordinate
y y coordinate
Returns
a reference to the pixel value.
Definition at line 1017 of file Image.hpp.
operator*() [1/2]
template<typename T_Type , unsigned int T_NumComp> Image<T_Type, T_NumComp>& sibr::ImagePtr< T_Type, T_NumComp >::operator* () inline
Returns
the dereferenced image
Definition at line 571 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
operator*() [2/2]
template<typename T_Type , unsigned int T_NumComp> const Image<T_Type, T_NumComp>& sibr::ImagePtr< T_Type, T_NumComp >::operator* () const inline
Returns
the dereferenced image
Definition at line 574 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
operator->() [1/2]
template<typename T_Type , unsigned int T_NumComp> Image<T_Type, T_NumComp>* sibr::ImagePtr< T_Type, T_NumComp >::operator-> () inline
Returns
raw pointer to the image
Definition at line 577 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
operator->() [2/2]
template<typename T_Type , unsigned int T_NumComp> const Image<T_Type, T_NumComp>* sibr::ImagePtr< T_Type, T_NumComp >::operator-> () const inline
Returns
raw pointer to the image
Definition at line 580 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
operator=() [1/3]
template<typename T_Type , unsigned int T_NumComp> Image& sibr::Image< T_Type, T_NumComp >::operator= (const Image< T_Type, T_NumComp > & other) delete
Disallow copy operator.
Parameters
other image to copy
operator=() [2/3]
template<typename T_Type , unsigned int T_NumComp> Image< T_Type, T_NumComp > & sibr::Image< T_Type, T_NumComp >::operator= (Image< T_Type, T_NumComp > && other) noexcept
Move operator.
Parameters
other image to move, don't use after move
Definition at line 743 of file Image.hpp.
operator=() [3/3]
template<typename T_Type , unsigned int T_NumComp> std::shared_ptr<Image<T_Type, T_NumComp> >& sibr::ImagePtr< T_Type, T_NumComp >::operator= (std::shared_ptr< Image< T_Type, T_NumComp >> & imgShPtr) inline
Assign a shared ptr.
Parameters
imgShPtr the shared pointer
Returns
a reference to the updated pointer
Definition at line 586 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
pixelStr() [1/2]
template<typename T_Type , unsigned int T_NumComp> std::string sibr::Image< T_Type, T_NumComp >::pixelStr (const ::sibr::Vector2i & xy) const virtual
Get the value stored at a pixel and convert it to a string representation.
Parameters
xy the pixel coordinates
Returns
a string representation of the pixel value.
Implements sibr::IImage.
Definition at line 1115 of file Image.hpp.
References xy().
pixelStr() [2/2]
virtual std::string sibr::IImage::pixelStr (const ::sibr::Vector2i & xy) const pure virtual
Get the value stored at a pixel and convert it to a string representation.
Parameters
xy the pixel coordinates
Returns
a string representation of the pixel value.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
PushScaledItemWidth()
SIBR_GRAPHICS_EXPORT void ImGui::PushScaledItemWidth (float item_width)
Push a width for item which is HiDPI aware.
Parameters
item_width The with to push, in regular pixels.
Definition at line 311 of file GUI.cpp.
Referenced by sibr::SceneDebugView::gui_options(), sibr::ULRV2View::onGUI(), sibr::ULRV3View::onGUI(), sibr::FPSCamera::onGUI(), sibr::InteractiveCameraHandler::onGUI(), and sibr::VideoPlayer::onGui().
randomColor()
template<typename T_Type > static Eigen::Matrix<T_Type, 3, 1, Eigen::DontAlign> sibr::randomColor () static
Generate a random color.
Returns
a random RGB triplet
Definition at line 19 of file Utils.hpp.
remap()
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::remap (const Pixel & minValue, const Pixel & maxValue)
Rescale an image content in a defined range.
Parameters
minValue the lower value of the range
maxValue the upper value of the range
Definition at line 1178 of file Image.hpp.
renderTask()
template<typename FunType , typename ... ArgsType> void sibr::renderTask (const std::string & s, FunType && f, ArgsType &&... args)
Debug helper: wrap a rendering task in an openGL debug group (visible in Renderdoc).
Parameters
s debug group name
f the task to wrap
args the task arguments
Definition at line 104 of file Utils.hpp.
reset()
template<typename T_Type , unsigned int T_NumComp> void sibr::ImagePtr< T_Type, T_NumComp >::reset (ImageType * ptr) inline
Set a new pointee.
Parameters
ptr the new image pointer
Definition at line 539 of file Image.hpp.
References sibr::ImagePtr< T_Type, T_NumComp >::imPtr.
Referenced by sibr::CameraRecorder::recordOfflinePath().
resize() [1/4]
template<typename ScalarType , uint N> static cv::Mat sibr::GLTexFormat< cv::Mat, ScalarType, N >::resize (const cv::Mat & img, uint w, uint h) inline static
Resize an image.
Parameters
img image to resize
w new width
h new height
Returns
the resize image.
Definition at line 497 of file Types.hpp.
resize() [2/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> static ImageType sibr::GLTexFormat< ImageType, ScalarType, N >::resize (const ImageType & img, uint w, uint h) static
Resize an image.
Parameters
img image to resize
w new width
h new height
Returns
the resize image.
resize() [3/4]
template<typename ScalarType , uint N> static ImageType sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::resize (const ImageType & img, uint w, uint h) inline static
Resize an image.
Parameters
img image to resize
w new width
h new height
Returns
the resize image.
Definition at line 418 of file Types.hpp.
References sibr::Image< T_Type, T_NumComp >::resized().
resize() [4/4]
template<typename ScalarType , uint N> static ImageType sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::resize (const ImageType & img, uint w, uint h) inline static
Resize an image.
Parameters
img image to resize
w new width
h new height
Returns
the resize image.
Definition at line 457 of file Types.hpp.
resized()
template<typename T_Type , unsigned int T_NumComp> Image< T_Type, T_NumComp > sibr::Image< T_Type, T_NumComp >::resized (int width, int height, int cv_interpolation_method = cv::INTER_LINEAR) const
Generate a resized version of the current image.
Parameters
width the target width
height the target height
cv_interpolation_method the up/down scaling method
Returns
the resized image
Definition at line 1088 of file Image.hpp.
References ibr_preprocess_rc_to_sibr::dst, and sibr::toOpenCV().
Referenced by sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::resize().
resizedMax()
template<typename T_Type , unsigned int T_NumComp> Image< T_Type, T_NumComp > sibr::Image< T_Type, T_NumComp >::resizedMax (int maxlen) const
Generate a resized version of the current image so that the maximum dimension (either width or height) is now equal to maxlen.
Preserve the original ratio. Example: src is 2048x1024, resizedMax(1024) -> dst is 1024x512
Parameters
maxlen the target maximum dimension value
Returns
the resized image
Definition at line 1098 of file Image.hpp.
save() [1/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::save (const std::string & filename, bool verbose = true) const virtual
Save an image to the disk (png, jpeg, see OpenCV cv::imwrite documentation for more details).
Parameters
filename the path to the file
verbose display additional informations
Warning
HDR images will be converted to LDR,
See also
saveHDR .
Warning
Some image formats can't be stored in some file formats.
Implements sibr::IImage.
Definition at line 881 of file Image.hpp.
References SIBR_ERR, SIBR_LOG, and SIBR_WRG.
Referenced by sibr::MultiViewBase::captureView(), main(), and sibr::MultiViewBase::renderSubView().
save() [2/2]
virtual void sibr::IImage::save (const std::string & filename, bool verbose = true) const pure virtual
Save an image to the disk (png, jpeg, see OpenCV cv::imwrite documentation for more details).
Parameters
filename the path to the file
verbose display additional informations
Warning
HDR images will be converted to LDR,
See also
saveHDR .
Warning
Some image formats can't be stored in some file formats.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
saveByteStream() [1/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::saveByteStream (const std::string & filename, bool verbose = true) const virtual
Save an image to the disk (as a raw binary blob).
Parameters
filename the path to the file
verbose display additional informations
Implements sibr::IImage.
Definition at line 976 of file Image.hpp.
References sibr::ByteStream::saveToFile(), SIBR_LOG, and SIBR_WRG.
saveByteStream() [2/2]
virtual void sibr::IImage::saveByteStream (const std::string & filename, bool verbose = true) const pure virtual
Save an image to the disk (as a raw binary blob).
Parameters
filename the path to the file
verbose display additional informations
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
saveHDR() [1/2]
template<typename T_Type , unsigned int T_NumComp> void sibr::Image< T_Type, T_NumComp >::saveHDR (const std::string & filename, bool verbose = true) const virtual
Save an HDR image to the disk (exr, hdr, see OpenCV cv::imwrite documentation for more details).
Parameters
filename the path to the file
verbose display additional informations
Implements sibr::IImage.
Definition at line 932 of file Image.hpp.
References SIBR_ERR, SIBR_LOG, and SIBR_WRG.
saveHDR() [2/2]
virtual void sibr::IImage::saveHDR (const std::string & filename, bool verbose = true) const pure virtual
Save an HDR image to the disk (exr, hdr, see OpenCV cv::imwrite documentation for more details).
Parameters
filename the path to the file
verbose display additional informations
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
show() [1/4]
template<typename T_Type , unsigned T_NumComp> static void sibr::show (const Image< T_Type, T_NumComp > & img, const std::string & windowTitle = "sibr::show()", bool closeWindow = true) static
Display an image into a popup OpenCV window.
Parameters
img the image to display
windowTitle the window title
closeWindow close the window after key presses
Definition at line 699 of file Image.hpp.
References sibr::Image< T_Type, T_NumComp >::toOpenCVBGR().
Referenced by sibr::buildVideoGaussianPyramid(), sibr::buildVideoLaplacianPyramid(), sibr::buildVideoLaplacianPyramidFullyReduced(), sibr::VideoUtils::computeSaveSimpleFlow(), sibr::ULRRenderer::process(), sibr::MonoRdrMode::render(), sibr::show(), sibr::showDepth(), sibr::showDepthFromAlpha(), sibr::showFloat(), and sibr::videoLaplacianBlending().
show() [2/4]
template<typename T_Type , unsigned T_NumComp> static void sibr::show (const RenderTarget< T_Type, T_NumComp > & rt, const std::string & winTitle = "sibr::show()") static
Display a RenderTarget into a popup OpenCV window.
Parameters
rt the rendertarget to display
winTitle the window title
Definition at line 587 of file Texture.hpp.
References sibr::RenderTarget< T_Type, T_NumComp >::readBack(), and sibr::show().
show() [3/4]
template<typename T_Type , unsigned T_NumComp> static void sibr::show (const RenderTarget< T_Type, T_NumComp > & rt, uint layer = 0, const std::string & windowTitle = "sibr::show()", bool closeWindow = true) static
Display a rendertarget color content in a popup window (backed by OpenCV).
Parameters
rt the rendertarget to display
layer the color attachment to display
windowTitle name of the window
closeWindow should the window be closed when pressing a key
Definition at line 221 of file RenderTarget.hpp.
References sibr::RenderTarget< T_Type, T_NumComp >::h(), sibr::RenderTarget< T_Type, T_NumComp >::readBack(), sibr::show(), and sibr::RenderTarget< T_Type, T_NumComp >::w().
show() [4/4]
template<typename T_Type , unsigned T_NumComp> static void sibr::show (const Texture2D< T_Type, T_NumComp > & texture, const std::string & winTitle = "sibr::show()") static
Display a texture into a popup OpenCV window.
Parameters
texture the texture to display
winTitle the window title
Definition at line 599 of file Texture.hpp.
References sibr::Image< T_Type, T_NumComp >::data(), sibr::Texture2D< T_Type, T_NumComp >::h(), sibr::Texture2D< T_Type, T_NumComp >::handle(), sibr::show(), and sibr::Texture2D< T_Type, T_NumComp >::w().
showDepth()
template<typename T_Type , unsigned T_NumComp> static void sibr::showDepth (const RenderTarget< T_Type, T_NumComp > & rt, const std::string & windowTitle = "sibr::show()", bool closeWindow = true) static
Display a rendertarget depth content in a popup window (backed by OpenCV).
Parameters
rt the rendertarget to display
windowTitle name of the window
closeWindow should the window be closed when pressing a key
Definition at line 234 of file RenderTarget.hpp.
References sibr::RenderTarget< T_Type, T_NumComp >::h(), sibr::RenderTarget< T_Type, T_NumComp >::readBackDepth(), sibr::show(), and sibr::RenderTarget< T_Type, T_NumComp >::w().
showDepthFromAlpha()
template<typename T_Type , unsigned T_NumComp> static void sibr::showDepthFromAlpha (const RenderTarget< T_Type, T_NumComp > & rt, const std::string & windowTitle = "sibr::show()", bool closeWindow = true) static
Display a rendertarget alpha content as a grey map in a popup window (backed by OpenCV).
Parameters
rt the rendertarget to display
windowTitle name of the window
closeWindow should the window be closed when pressing a key
Definition at line 247 of file RenderTarget.hpp.
References sibr::Image< T_Type, T_NumComp >::color(), sibr::Image< T_Type, T_NumComp >::h(), sibr::RenderTarget< T_Type, T_NumComp >::h(), sibr::RenderTarget< T_Type, T_NumComp >::readBack(), sibr::show(), sibr::Image< T_Type, T_NumComp >::w(), and sibr::RenderTarget< T_Type, T_NumComp >::w().
showFloat()
SIBR_GRAPHICS_EXPORT void sibr::showFloat (const Image< float, 1 > & im, bool logScale = false, double min = -DBL_MAX, double max = DBL_MAX)
Display a 32F image in a debug window, using the Parula colormap after normalizing the values.
Parameters
im the float image to display
logScale display log(img)
min optional lower bound for the normalization
max optional upper bound for the normalization
Definition at line 233 of file Image.cpp.
References sibr::Image< T_Type, T_NumComp >::fromOpenCVBGR(), sibr::Image< T_Type, T_NumComp >::h(), sibr::show(), sibr::Image< T_Type, T_NumComp >::toOpenCV(), and sibr::Image< T_Type, T_NumComp >::w().
showImGuiWindow()
SIBR_GRAPHICS_EXPORT bool sibr::showImGuiWindow (const std::string & windowTitle, const IRenderTarget & rt, ImGuiWindowFlags flags, Viewport & viewport, bool invalidTexture, bool updateLayout, int handle = 0)
Show the content of a rendertarget in an ImGui window.
Parameters
windowTitle the window name (unique)
rt the rendrtarget to display
flags ImGui flags
viewport will contain the window extent on screen
invalidTexture ignore the RT
updateLayout force update the camera location on screen
handle the texture index to display from the input RT
Returns
true if window is focused (useful for managing interactions).
Definition at line 13 of file GUI.cpp.
References sibr::Key::End, sibr::Viewport::finalHeight(), sibr::Viewport::finalLeft(), sibr::Viewport::finalSize(), sibr::Viewport::finalTop(), sibr::Viewport::finalWidth(), sibr::fitImageToDisplayRegion(), ImGui::GetTitleBarHeight(), and sibr::IRenderTarget::handle().
Referenced by sibr::MultiViewBase::renderSubView().
SIBR_CLASS_PTR()
sibr::IImage::SIBR_CLASS_PTR (IImage)
size() [1/2]
template<typename T_Type , unsigned int T_NumComp> sibr::Vector2u sibr::Image< T_Type, T_NumComp >::size (void) const virtual
Returns
the image size.
Implements sibr::IImage.
Definition at line 1135 of file Image.hpp.
Referenced by sibr::VideoUtils::getBackGroundVideo(), and sibr::InputCamera::loadBundleFRIBR().
size() [2/2]
virtual sibr::Vector2u sibr::IImage::size (void) const pure virtual
Returns
the image size.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
sizeOfComp() [1/2]
template<typename T_Type , unsigned int T_NumComp> uint sibr::Image< T_Type, T_NumComp >::sizeOfComp (void) const virtual
Returns
the size of a pixel value in bytes.
Implements sibr::IImage.
Definition at line 1145 of file Image.hpp.
sizeOfComp() [2/2]
virtual uint sibr::IImage::sizeOfComp (void) const pure virtual
Returns
the size of a pixel value in bytes.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
sRGB2Lin()
SIBR_GRAPHICS_EXPORT void sibr::sRGB2Lin (sibr::ImageRGB32F & img)
Inplace conversion of float image from sRGB space to linear.
Parameters
img the image to convert
Definition at line 69 of file Utils.cpp.
References sibr::Image< T_Type, T_NumComp >::h(), sibr::sRGB2LinF(), and sibr::Image< T_Type, T_NumComp >::w().
TabButton()
SIBR_GRAPHICS_EXPORT bool ImGui::TabButton (const char * label, bool highlight, const ImVec2 & size = ImVec2(0, 0))
Helper to create a tab button item.
Parameters
label the button text
highlight should the button be highlit
size the size of the button (0,0 will autosize).
Returns
true if the tab is active
Definition at line 316 of file GUI.cpp.
toOpenCV() [1/3]
template<typename openCV_T , typename sibr_T , int N> cv::Vec<openCV_T, N> sibr::toOpenCV (const Vector< sibr_T, N > & vec) inline
Definition at line 1278 of file Image.hpp.
References sibr::Key::N.
Referenced by legacyV2main(), main(), sibr::Image< T_Type, T_NumComp >::resized(), and sibr::Image< T_Type, T_NumComp >::toOpenCVBGR().
toOpenCV() [2/3]
template<typename T_Type , unsigned int T_NumComp> const cv::Mat& sibr::Image< T_Type, T_NumComp >::toOpenCV (void) const inline virtual
Returns
a reference to the underlying OpenCV matrix.
Implements sibr::IImage.
Definition at line 437 of file Image.hpp.
Referenced by assignImages(), sibr::Image< float, 3 >::cast(), sibr::MeshTexturing::floodFill(), sibr::MeshTexturing::getTexture(), sibr::RenderMaskHolder::loadMasks(), sibr::MeshTexturing::poissonFill(), sibr::RenderTarget< T_Type, T_NumComp >::readBack(), sibr::showFloat(), and tonemap().
toOpenCV() [3/3]
virtual const cv::Mat& sibr::IImage::toOpenCV (void) const pure virtual
Returns
a reference to the underlying OpenCV matrix.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
toOpenCVBGR() [1/2]
template<typename T_Type , unsigned int T_NumComp> cv::Mat sibr::Image< T_Type, T_NumComp >::toOpenCVBGR (void) const virtual
Returns
a copy of the matrix with channels flipped.
Note
Only applies to 3 and 4 channel images.
Implements sibr::IImage.
Definition at line 761 of file Image.hpp.
References sibr::opencv::convertRGB2BGR(), and sibr::toOpenCV().
Referenced by sibr::FFVideoEncoder::operator<<(), sibr::MultiViewBase::renderSubView(), and sibr::show().
toOpenCVBGR() [2/2]
virtual cv::Mat sibr::IImage::toOpenCVBGR (void) const pure virtual
Returns
a copy of the matrix with channels flipped.
Note
Only applies to 3 and 4 channel images.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
toOpenCVnonConst() [1/2]
template<typename T_Type , unsigned int T_NumComp> cv::Mat& sibr::Image< T_Type, T_NumComp >::toOpenCVnonConst (void) inline virtual
Returns
a reference to the underlying OpenCV matrix.
Implements sibr::IImage.
Definition at line 440 of file Image.hpp.
Referenced by sibr::ULRV2View::computeVisibilityMap().
toOpenCVnonConst() [2/2]
virtual cv::Mat& sibr::IImage::toOpenCVnonConst (void) pure virtual
Returns
a reference to the underlying OpenCV matrix.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
w() [1/2]
template<typename T_Type , unsigned int T_NumComp> uint sibr::Image< T_Type, T_NumComp >::w (void) const virtual
Returns
the image width.
Implements sibr::IImage.
Definition at line 1125 of file Image.hpp.
Referenced by assignImages(), sibr::DistordCropUtility::Bounds::Bounds(), sibr::coloredClass(), sibr::ULRV2View::computeVisibilityMap(), sibr::convertL32FtoRGBA(), sibr::convertNormalMapToSphericalHalf(), sibr::convertRGB32FtoRGBA(), sibr::convertRGBAtoL32F(), sibr::convertRGBAtoRGB32F(), sibr::convertSphericalHalfToNormalMap(), sibr::TextureCubeMap< T_Type, T_NumComp >::createFromImages(), sibr::MeshTexturing::floodFill(), sibr::DistordCropUtility::getBounds(), sibr::MeshTexturing::hitTest(), sibr::Image< float, 3 >::isInRange(), sibr::lin2sRGB(), main(), sibr::RenderTarget< T_Type, T_NumComp >::readBackDepth(), sibr::MeshTexturing::reproject(), sibr::TextureCubeMap< T_Type, T_NumComp >::sendCubeMap(), sibr::showDepthFromAlpha(), sibr::showFloat(), sibr::sRGB2Lin(), sibr::RenderMaskHolder::uploadMaskGPU(), and sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::width().
w() [2/2]
virtual uint sibr::IImage::w (void) const pure virtual
Returns
the image width.
Implemented in sibr::Image< T_Type, T_NumComp >, sibr::Image< unsigned char, 1 >, and sibr::Image< float, 3 >.
width() [1/4]
template<typename ScalarType , uint N> static uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::width (const cv::Mat & img) inline static
Get an image width.
Parameters
img the image
Returns
the width
Definition at line 504 of file Types.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
width() [2/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> static uint sibr::GLTexFormat< ImageType, ScalarType, N >::width (const ImageType & img) static
Get an image width.
Parameters
img the image
Returns
the width
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
width() [3/4]
template<typename ScalarType , uint N> static uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::width (const ImageType & img) inline static
Get an image width.
Parameters
img the image
Returns
the width
Definition at line 423 of file Types.hpp.
References sibr::Image< T_Type, T_NumComp >::w().
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
width() [4/4]
template<typename ScalarType , uint N> static uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::width (const ImageType & img) inline static
Get an image width.
Parameters
img the image
Returns
the width
Definition at line 462 of file Types.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
Variable Documentation
_pixels
template<typename T_Type , unsigned int T_NumComp> cv::Mat sibr::Image< T_Type, T_NumComp >::_pixels protected
Pixels stored in RGB format.
Definition at line 503 of file Image.hpp.
Referenced by sibr::Image< T_Type, T_NumComp >::clone(), sibr::Image< float, 3 >::toOpenCV(), and sibr::Image< float, 3 >::toOpenCVnonConst().
format [1/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> const uint sibr::GLTexFormat< ImageType, ScalarType, N >::format static
Generic GL format.
Definition at line 399 of file Types.hpp.
format [2/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::format = GLFormat<ScalarType, N>::format static
Generic GL format.
Definition at line 438 of file Types.hpp.
format [3/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::format = GLFormat<ScalarType, N>::format static
Generic GL format.
Definition at line 477 of file Types.hpp.
format [4/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::format = GLFormatCVmat<ScalarType, N>::format static
Generic GL format.
Definition at line 529 of file Types.hpp.
getOpenCVtype
template<typename T , uint N> constexpr uint sibr::getOpenCVtype = CV_MAKE_TYPE(OpenCVdepth<T>::value, N) constexpr
Helper to create a cv::Mat type from its depth and number of components.
Definition at line 338 of file Types.hpp.
getOpenCVtypeSingleChannel
template<typename T > constexpr uint sibr::getOpenCVtypeSingleChannel = getOpenCVtype<T, 1> constexpr
Helper to create a one-channel cv::Mat from its depth.
Definition at line 341 of file Types.hpp.
imPtr
template<typename T_Type , unsigned int T_NumComp> std::shared_ptr<Image<T_Type, T_NumComp> > sibr::ImagePtr< T_Type, T_NumComp >::imPtr
Pointer type.
Definition at line 515 of file Image.hpp.
Referenced by sibr::ImagePtr< T_Type, T_NumComp >::get(), sibr::ImagePtr< T_Type, T_NumComp >::ImagePtr(), sibr::ImagePtr< T_Type, T_NumComp >::operator bool(), sibr::ImagePtr< T_Type, T_NumComp >::operator*(), sibr::ImagePtr< T_Type, T_NumComp >::operator->(), sibr::ImagePtr< T_Type, T_NumComp >::operator=(), and sibr::ImagePtr< T_Type, T_NumComp >::reset().
int_format [1/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> const uint sibr::GLTexFormat< ImageType, ScalarType, N >::int_format static
Generic GL format for integer textures.
Definition at line 401 of file Types.hpp.
int_format [2/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::int_format = GLFormat<ScalarType, N>::int_format static
Generic GL format for integer textures.
Definition at line 440 of file Types.hpp.
int_format [3/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::int_format = GLFormat<ScalarType, N>::int_format static
Generic GL format for integer textures.
Definition at line 479 of file Types.hpp.
int_format [4/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::int_format = GLFormatCVmat<ScalarType, N>::int_format static
Generic GL format for integer textures.
Definition at line 531 of file Types.hpp.
int_internal_format [1/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> const uint sibr::GLTexFormat< ImageType, ScalarType, N >::int_internal_format static
Internal GL format for integer textures.
Definition at line 400 of file Types.hpp.
int_internal_format [2/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::int_internal_format = GLFormat<ScalarType, N>::int_internal_format static
Internal GL format for integer textures.
Definition at line 439 of file Types.hpp.
int_internal_format [3/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::int_internal_format = GLFormat<ScalarType, N>::int_internal_format static
Internal GL format for integer textures.
Definition at line 478 of file Types.hpp.
int_internal_format [4/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::int_internal_format = GLFormatCVmat<ScalarType, N>::int_internal_format static
Internal GL format for integer textures.
Definition at line 530 of file Types.hpp.
internal_format [1/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> const uint sibr::GLTexFormat< ImageType, ScalarType, N >::internal_format static
Internal GL format.
Definition at line 398 of file Types.hpp.
internal_format [2/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::internal_format = GLFormat<ScalarType, N>::internal_format static
Internal GL format.
Definition at line 437 of file Types.hpp.
internal_format [3/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::internal_format = GLFormat<ScalarType, N>::internal_format static
Internal GL format.
Definition at line 476 of file Types.hpp.
internal_format [4/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::internal_format = GLFormatCVmat<ScalarType, N>::internal_format static
Internal GL format.
Definition at line 528 of file Types.hpp.
isdepth [1/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> const uint sibr::GLTexFormat< ImageType, ScalarType, N >::isdepth static
Is it a depth format.
Definition at line 402 of file Types.hpp.
isdepth [2/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::isdepth = GLFormat<ScalarType, N>::isdepth static
Is it a depth format.
Definition at line 441 of file Types.hpp.
isdepth [3/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::isdepth = GLFormat<ScalarType, N>::isdepth static
Is it a depth format.
Definition at line 480 of file Types.hpp.
isdepth [4/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::isdepth = GLFormatCVmat<ScalarType, N>::isdepth static
Is it a depth format.
Definition at line 532 of file Types.hpp.
type [1/4]
template<typename ImageType , typename ScalarType = typename ImageType::Type, uint N = ImageType::e_NumComp> const uint sibr::GLTexFormat< ImageType, ScalarType, N >::type static
The component GL type.
Definition at line 403 of file Types.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
type [2/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >::type = GLType<ScalarType>::type static
The component GL type.
Definition at line 442 of file Types.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
type [3/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >::type = GLType<ScalarType>::type static
The component GL type.
Definition at line 481 of file Types.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
type [4/4]
template<typename ScalarType , uint N> const uint sibr::GLTexFormat< cv::Mat, ScalarType, N >::type = GLType<ScalarType>::type static
The component GL type.
Definition at line 533 of file Types.hpp.
Referenced by get_image_size.Image::to_str_row(), and get_image_size.Image::to_str_row_verbose().
value [1/6]
const uint sibr::OpenCVdepth< uchar >::value = CV_8U static
Definition at line 324 of file Types.hpp.
value [2/6]
const uint sibr::OpenCVdepth< float >::value = CV_32F static
Definition at line 329 of file Types.hpp.
value [3/6]
const uint sibr::OpenCVdepth< double >::value = CV_64F static
Definition at line 334 of file Types.hpp.
value [4/6]
template<typename ImageType > const bool sibr::ValidGLTexFormat< ImageType >::value = false static
Definition at line 345 of file Types.hpp.
value [5/6]
template<typename ScalarType , uint N> const bool sibr::ValidGLTexFormat< sibr::Image< ScalarType, N > >::value = true static
Definition at line 350 of file Types.hpp.
value [6/6]
const bool sibr::ValidGLTexFormat< cv::Mat >::value = true static
Definition at line 355 of file Types.hpp.