SIBR: src/core/system/MatrixBasePlugin.hpp File Reference
MatrixBasePlugin.hpp File Reference
Typedefs
typedef Scalar Type
Functions
MatrixBase transposed (void)
Helper to evaluate a transposed matrix without overwriting risks.
Matrix< Scalar, 2, 1, Eigen::DontAlign > xy (float fill=0.f) const
Get the first two components, filling with a default value if some are missing.
Matrix< Scalar, 2, 1, Eigen::DontAlign > yx (float fill=0.f) const
Get the first two components swapped, filling with a default value if some are missing.
Matrix< Scalar, 2, 1, Eigen::DontAlign > wz (float fill=0.f) const
Get the last two components swapped, filling with a default value if some are missing.
Matrix< Scalar, 3, 1, Eigen::DontAlign > xyz (float fill=0.f) const
Get the first three components, filling with a default value if some are missing.
Matrix< Scalar, 4, 1, Eigen::DontAlign > xyzw (float fill=0.f) const
Get the first four components, filling with a default value if some are missing.
Matrix< Scalar, 3, 1, Eigen::DontAlign > yxz (float fill=0.f) const
Get the first three components swapped (YXZ), filling with a default value if some are missing.
Matrix< Scalar, 3, 1, Eigen::DontAlign > yzx (float fill=0.f) const
Get the first three components swapped (YZX), filling with a default value if some are missing.
bool isNull (void) const
Check if a vector is exactly zero for all components.
Typedef Documentation
Type
typedef Scalar Type
Definition at line 76 of file MatrixBasePlugin.hpp.
Function Documentation
isNull()
bool isNull (void) const
Check if a vector is exactly zero for all components.
Returns
true if all components are exactly zero.
Definition at line 72 of file MatrixBasePlugin.hpp.
transposed()
MatrixBase transposed (void) inline
Helper to evaluate a transposed matrix without overwriting risks.
Returns
a copy of the matrix, transposed
Definition at line 11 of file MatrixBasePlugin.hpp.
wz()
Matrix<Scalar, 2, 1, Eigen::DontAlign> wz (float fill = 0.f) const
Get the last two components swapped, filling with a default value if some are missing.
Parameters
fill the default value to use
Returns
the selected components.
Definition at line 33 of file MatrixBasePlugin.hpp.
xy()
Matrix<Scalar, 2, 1,Eigen::DontAlign> xy (float fill = 0.f) const
Get the first two components, filling with a default value if some are missing.
Parameters
fill the default value to use
Returns
the selected components.
Definition at line 17 of file MatrixBasePlugin.hpp.
Referenced by sibr::Viewport::contains(), sibr::Camera::frustumTest(), sibr::VideoUtils::getFlowViz(), sibr::Image< float, 3 >::isInRange(), sibr::Image< T_Type, T_NumComp >::operator()(), sibr::ImagePtr< T_Type, T_NumComp >::operator()(), and sibr::Image< T_Type, T_NumComp >::pixelStr().
xyz()
Matrix<Scalar, 3, 1,Eigen::DontAlign> xyz (float fill = 0.f) const
Get the first three components, filling with a default value if some are missing.
Parameters
fill the default value to use
Returns
the selected components.
Definition at line 41 of file MatrixBasePlugin.hpp.
Referenced by PlaneEstimator::estimateGroundPlane(), sibr::Mesh::loadMtsXML(), sibr::MaterialMesh::loadMtsXML(), main(), sibr::MeshTexturing::reproject(), and sibr::Raycaster::xformRtcMeshOnly().
xyzw()
Matrix<Scalar, 4, 1,Eigen::DontAlign> xyzw (float fill = 0.f) const
Get the first four components, filling with a default value if some are missing.
Parameters
fill the default value to use
Returns
the selected components.
Definition at line 49 of file MatrixBasePlugin.hpp.
yx()
Matrix<Scalar, 2, 1, Eigen::DontAlign> yx (float fill = 0.f) const
Get the first two components swapped, filling with a default value if some are missing.
Parameters
fill the default value to use
Returns
the selected components.
Definition at line 25 of file MatrixBasePlugin.hpp.
yxz()
Matrix<Scalar, 3, 1, Eigen::DontAlign> yxz (float fill = 0.f) const
Get the first three components swapped (YXZ), filling with a default value if some are missing.
Parameters
fill the default value to use
Returns
the selected components.
Definition at line 57 of file MatrixBasePlugin.hpp.
yzx()
Matrix<Scalar, 3, 1, Eigen::DontAlign> yzx (float fill = 0.f) const
Get the first three components swapped (YZX), filling with a default value if some are missing.
Parameters
fill the default value to use
Returns
the selected components.
Definition at line 65 of file MatrixBasePlugin.hpp.