SIBR: src/core/system/MD5.h File Reference
MD5.h File Reference
#include <stddef.h>
Classes
struct MD5_CTX
Macros
#define F(x, y, z) (((x) & (y)) | ((~x) & (z)))
#define G(x, y, z) (((x) & (z)) | ((y) & (~z)))
#define H(x, y, z) ((x) ^ (y) ^ (z))
#define I(x, y, z) ((y) ^ ((x) | (~z)))
#define ROTATE_LEFT(x, n) (((x) << (n)) | ((x) >> (32-(n))))
#define FF(a, b, c, d, x, s, ac)
#define GG(a, b, c, d, x, s, ac)
#define HH(a, b, c, d, x, s, ac)
#define II(a, b, c, d, x, s, ac)
#define S11 7
#define S12 12
#define S13 17
#define S14 22
#define S21 5
#define S22 9
#define S23 14
#define S24 20
#define S31 4
#define S32 11
#define S33 16
#define S34 23
#define S41 6
#define S42 10
#define S43 15
#define S44 21
Typedefs
typedef unsigned long int UINT4
Functions
void MD5Init (MD5_CTX *mdContext)
void MD5Update (MD5_CTX *mdContext, unsigned char *inBuf, size_t inLen)
void MD5Final (MD5_CTX *mdContext)
void MD5Buffer (void *buffer, size_t bufLen, unsigned int *pDigest)
static void Transform (UINT4 *buf, UINT4 *in)
Variables
static unsigned char PADDING [64]
Macro Definition Documentation
F
#define F (x, y, z) (((x) & (y)) | ((~x) & (z)))
Definition at line 128 of file MD5.h.
FF
#define FF (a, b, c, d, x, s, ac)
Value:
  {(a) += F ((b), (c), (d)) + (x) + (UINT4)(ac); \
   (a) = ROTATE_LEFT ((a), (s)); \
   (a) += (b); \
  }
Definition at line 138 of file MD5.h.
G
#define G (x, y, z) (((x) & (z)) | ((y) & (~z)))
Definition at line 129 of file MD5.h.
GG
#define GG (a, b, c, d, x, s, ac)
Value:
  {(a) += G ((b), (c), (d)) + (x) + (UINT4)(ac); \
   (a) = ROTATE_LEFT ((a), (s)); \
   (a) += (b); \
  }
Definition at line 143 of file MD5.h.
H
#define H (x, y, z) ((x) ^ (y) ^ (z))
Definition at line 130 of file MD5.h.
HH
#define HH (a, b, c, d, x, s, ac)
Value:
  {(a) += H ((b), (c), (d)) + (x) + (UINT4)(ac); \
   (a) = ROTATE_LEFT ((a), (s)); \
   (a) += (b); \
  }
Definition at line 148 of file MD5.h.
I
#define I (x, y, z) ((y) ^ ((x) | (~z)))
Definition at line 131 of file MD5.h.
II
#define II (a, b, c, d, x, s, ac)
Value:
  {(a) += I ((b), (c), (d)) + (x) + (UINT4)(ac); \
   (a) = ROTATE_LEFT ((a), (s)); \
   (a) += (b); \
  }
Definition at line 153 of file MD5.h.
ROTATE_LEFT
#define ROTATE_LEFT (x, n) (((x) << (n)) | ((x) >> (32-(n))))
Definition at line 134 of file MD5.h.
S11
#define S11 7
S12
#define S12 12
S13
#define S13 17
S14
#define S14 22
S21
#define S21 5
S22
#define S22 9
S23
#define S23 14
S24
#define S24 20
S31
#define S31 4
S32
#define S32 11
S33
#define S33 16
S34
#define S34 23
S41
#define S41 6
S42
#define S42 10
S43
#define S43 15
S44
#define S44 21
Typedef Documentation
UINT4
typedef unsigned long int UINT4
Definition at line 46 of file MD5.h.
Function Documentation
MD5Buffer()
void MD5Buffer (void * buffer, size_t bufLen, unsigned int * pDigest)
Definition at line 65 of file MD5.h.
References MD5_CTX::digest, MD5Final(), MD5Init(), and MD5Update().
MD5Final()
void MD5Final (MD5_CTX * mdContext)
Definition at line 203 of file MD5.h.
References MD5_CTX::buf, MD5_CTX::digest, MD5_CTX::i, MD5_CTX::in, MD5Update(), PADDING, and Transform().
Referenced by MD5Buffer().
MD5Init()
void MD5Init (MD5_CTX * mdContext)
Definition at line 159 of file MD5.h.
References MD5_CTX::buf, and MD5_CTX::i.
Referenced by MD5Buffer().
MD5Update()
void MD5Update (MD5_CTX * mdContext, unsigned char * inBuf, size_t inLen)
Definition at line 171 of file MD5.h.
References MD5_CTX::buf, MD5_CTX::i, MD5_CTX::in, and Transform().
Referenced by MD5Buffer(), and MD5Final().
Transform()
static void Transform (UINT4 * buf, UINT4 * in) static
Definition at line 243 of file MD5.h.
References FF, GG, HH, II, S11, S12, S13, S14, S21, S22, S23, S24, S31, S32, S33, S34, S41, S42, S43, and S44.
Referenced by MD5Final(), and MD5Update().
Variable Documentation
PADDING
unsigned char PADDING[64] static
Initial value:
= {
  0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
Definition at line 116 of file MD5.h.
Referenced by MD5Final().