SIBR: sibr Namespace Reference
sibr Namespace Reference
Namespaces
Key
LoadingStatus
Loading status for streaming.
Mouse
opencv
Classes
class ActiveImageFile
Represent a active_images.txt file use to select a subset of a scene images.
class AddShadowRenderer
Composite two rendered scenes while generating local cast shadows from the top one to the bottom one.
struct AppArgs
Hierarchy of Args classes that can be seens as modules, and can be combined using virtual inheritance, with no duplication of code so derived Args has no extra work to do Assuming CommandLineArgs::parseMainArgs() was called once, Args arguments will be automatically initialized with the value from the command line by the constructor Existing Args structs should cover most of the existing IBR apps To add a new argument like –my-arg 5 on top of existing arguments and to add a new required argument like –important-param "on" on top of existing arguments, do the following:
class Arg
Template Arg class, will init itself in the defaut ctor using the command line args (ie.
class Arg< bool >
Specialization of Arg for bool, value is true if key is present and false otherwise.
class Arg< Switch >
Specialization of Arg for Switch, default value get flipped if arg is present.
class ArgBase
Internal argument based interface.
class Array2d
Used to store custom data on a map using pixel position (2d unsigned pos).
struct BasicDatasetArgs
Dataset related arguments.
struct BasicIBRAppArgs
"Default" set of arguments.
class BasicIBRScene
Class used to define a basic IBR Scene containing multiple components required to define a scene.
struct BasicVoxelType
Default voxel type, storing binary occupancy.
class BinaryMeshRenderer
Render a binary mask of a mesh, with options to limit Z-fighting.
class BlurRenderer
Blur on color edges present in a texture.
class ByteStream
Be sure to use STL objects from client's dll version by exporting this declaration (see warning C4251)
class CalibratedCameras
struct CallBackData
Store user interaction information to be returned when displaying an image.
class Camera
Represent a basic camera.
class CameraRaycaster
Used for casting each pixel of an image into a raycaster scene.
class CameraRecorder
This class handles the recording and replay of a stream of cameras.
class ColoredMeshRenderer
Render a mesh colored using the per-vertex color attribute.
class ColorMeshShader
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class CommandLineArgs
struct ContribData
class CopyRenderer
Copy the content of an input texture to another rendertarget or to the window.
class CropScaleImageUtility
Utility class to crop and rescale images, especially for uniformizing IBR datasets.
struct CV_Assign
struct CV_Assign< T, 1 >
class DatasetView
Visualize and explore a MVS dataset.
struct DebugScopeProfiler
Used for quickly measuring time for completing a scope.
class DepthInputTextureArray
class DepthRenderer
Render a mesh to a depth rendertarget.
class DistordCropUtility
Helpers for cropping undistorted dataset images so that margins are removed, while keeping the dataset consistent.
struct DoubleClick
struct DragClickData
struct DragData
class DrawUtilities
class FFVideoEncoder
Video encoder using ffmpeg.
class FPSCamera
Interactive camera that can be moved using WASD keys.
class FPSCounter
Provde a small GUI panel to display the current framerate, smoothed over multiple frames.
class Frustum
Represent a 3D frustum defined by 6 planes.
struct FullContribData
class GLFormat
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< float, 1 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< float, 2 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< float, 3 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< float, 4 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< int, 1 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< int, 2 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< int, 3 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< int, 4 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< unsigned char, 1 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< unsigned char, 2 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< unsigned char, 3 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< unsigned char, 4 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< unsigned short, 1 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< unsigned short, 2 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< unsigned short, 3 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormat< unsigned short, 4 >
Helper building the correspondence between a GL format and a C type and number of components.
class GLFormatCVmat
Helper building the correspondence between a GL format and a cv::Mat.
class GLFormatCVmat< unsigned char, 1 >
Helper building the correspondence between a GL format and a cv::Mat.
class GLFormatCVmat< unsigned char, 3 >
Helper building the correspondence between a GL format and a cv::Mat.
class GLFormatCVmat< unsigned char, 4 >
Helper building the correspondence between a GL format and a cv::Mat.
class GLParameter
OpenGL shader uniform wrapper.
class GLShader
OpenGL shader wrapper.
struct GLTexFormat
Helper class to provide, from a generic image type, all the information needed for OpenGL textures Right now it can work with all sibr::Image and with cv::Mat (3U8 only) You can add more using explicit template instanciation to specify both ValidGLTexFormat and the following GLTexFormat properties.
struct GLTexFormat< cv::Mat, ScalarType, N >
Helper class to provide, for a cv::Mat, all the information needed for OpenGL textures.
struct GLTexFormat< cv::Mat_< cv::Vec< ScalarType, N > >, ScalarType, N >
Helper class to provide, for a cv::Mat, all the information needed for OpenGL textures.
struct GLTexFormat< ImagePtr< ScalarType, N >, ScalarType, N >
Helper class to provide, for an sibr::Image::Ptr, all the information needed for OpenGL textures.
struct GLTexFormat< sibr::Image< ScalarType, N >, ScalarType, N >
Helper class to provide, for an sibr::Image, all the information needed for OpenGL textures.
class GLType
Helper building the correspondence between a GL type and a C type.
class GLType< float >
Helper building the correspondence between a GL type and a C type.
class GLType< int >
Helper building the correspondence between a GL type and a C type.
class GLType< short >
Helper building the correspondence between a GL type and a C type.
class GLType< unsigned char >
Helper building the correspondence between a GL type and a C type.
class GLType< unsigned short >
Helper building the correspondence between a GL type and a C type.
class GLuniform
OpenGL shader uniform wrapper with additional update/storage functions.
class GPUQuery
Provide a buffered wrapper around an OpenGL query object, avoiding manual synchronization.
class GridMapping
struct HighlightData
class Histogram
class Histogram< T, 1 >
class IBRBasicUtils
Provide basic IBR utilities.
class ICalibratedCameras
class ICameraHandler
Represent an interaction mode (FPS, trackball,...) for a camera controlled by the user, or a combination of multiple modes.
class ICameraRaycasterProcessor
Used to process casted rays from image pixels.
class IFileLoader
General file loading interface.
class IIBRScene
Interface used to define how an IBR Scene is shaped containing multiple components required to define a scene.
class IImage
Interface virtual class for all the templated image classes.
class IInputImages
class Image
This class is used to store images.
struct ImageCamViewer
Helper used to render image planes in front of the camera, for both scenes storing 2D separate images or a texture array.
struct ImageGridLayer
class ImageListFile
Represents a list of input images.
class ImagePtr
Wrapper around an image pointer.
class ImagesGrid
class ImageView
Basic view to display an image and inspect it.
class Input
Maintain the complete state of user interactions (mouse, keyboard) for a given view or window.
class InputCamera
Input camera parameters.
class InputImages
class InputState
Keep track of the pressed/active/released state of a set of keys/buttons.
class InteractiveCameraHandler
The InteractiveCameraHandler gathers various types of camera interactions and allows the user to switch between them, keeping them in sync.
class InterfaceUtilities
class Intersector2D
This class provides utilities to compute point/line/triangle/quad intersections.
class IParseData
Interface used to store the data required for defining an IBR Scene.
class IProxyMesh
class IRenderingMode
Rendering mode manages the rendertarget and camera fed to an IBR view.
class IRenderTarget
Rendertarget interface.
class ITexture2D
Interface for a generic GPU 2D texture.
class ITexture2DArray
Interface for a generic GPU 2D array texture.
class ITextureCubeMap
Interface for a generic GPU cubemap texture.
class KdTree
Represent a 3D hierachical query structure baked by a nanoflann KdTree.
struct KeyCombination
Helper keeping track of the number of keys currently pressed.
struct LabelsManager
Helper used to display camera labels on screen.
struct LayerData
class LoadingProgress
Simple utility class for reporting on the standard output a loading progess.
struct LogExit
Ensure that all logs are output before exiting when an error or exception is raised.
class MaterialMesh
Store both CPU and GPU data for a geometric mesh.
class Mesh
Store both CPU and GPU data for a geometric mesh.
class MeshBufferGL
This class is used to render mesh.
class MeshData
Helper class containing all information relative to how to render a mesh for debugging purpose in a MultiMeshManager.
class MeshRenderer
class MeshShadingShader
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class MeshTexturing
Reproject images onto a mesh using the associated camera poses, and accumulate colors in UV-space to generate a texture map.
class MeshViewer
class MonoRdrMode
Default rendering mode: monoview, passthrough.
class MRFSolver
Object wrapper around Kolmogorov & Boykov MRF solver.
class MultiMeshManager
Provide a view to render and interact with several meshes, useful for debugging purposes for instance.
struct MultipleVideoDecoder
Batch decoding of multiple videos at the same time, stored in a texture array.
struct MultipleVideoDecoderArray
Batch decoding of multiple videos at the same time, stored in a texture array.
class MultiVector
Multi dimensional vector.
class MultiVector< T, 1 >
Base multi-dimensional vector class (a 1D vector).
class MultiViewBase
MultiViewBase is designed to provide more flexibility and with a multi-windows system in mind.
class MultiViewInterface
This class provides basic rendering utilities for a list of images + a mesh.
class MultiViewInterfaceView
class MultiViewManager
A multiview manager is a multi-view system that displays its subviews in an OS window.
struct MVpixel
class NormalRenderer
Render the world or view space normals of a mesh.
class NormalRenderingShader
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class ObjectSelection
struct OpenCVdepth
Helper building the correspondence between a GL type and a cv::Mat depth.
struct OpenCVdepth< double >
Helper building the correspondence between a GL type and a cv::Mat depth.
struct OpenCVdepth< float >
Helper building the correspondence between a GL type and a cv::Mat depth.
struct OpenCVdepth< uchar >
Helper building the correspondence between a GL type and a cv::Mat depth.
class Orbit
Interactive camera that allow the user to roate around an object using the keypad.
class ParseData
Class used to store the data required for defining an IBR Scene.
struct PingPongTexture
Double-buffered texture, used to load/display video frames for instance.
struct PixPos
class PointShader
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class PoissonReconstruction
Performs gradient integration for tasks such as Poisson-based inpainting, smooth filling, ...
class PoissonRenderer
Hole filling by poisson synthesis on an input texture; contains all shaders, render targets and render passes.
class PositionRenderer
Render the world space positions of a mesh surface.
class ProxyMesh
struct PyramidLayer
struct PyramidParameters
struct QuadData
struct QuadSelectionData
class Ray
Represents a simple ray.
class Raycaster
This class can be used to cast rays against a scene containing triangular meshes.
class RaycastingCamera
A raycasting camera is an input camera augmented with additional casting and frustum helpers.
class RayHit
Contains information about a ray hit.
class Rect
Represents a simple aligned axis rectangle.
struct RectangleData
struct RenderingArgs
Common rendering settings.
class RenderMaskHolder
Store a set of masks associated to a set of images (dataset input images for instance), on the GPU.
class RenderMaskHolderArray
Store a set of masks associated to a set of images (dataset input images for instance), on the GPU.
class RenderTarget
A render target wraps an OpenGL framebuffer, that can have one depth buffer, one stencil buffer, and one or more color attachments.
class RenderTargetTextures
class RenderUtility
Helpers for rendering basic debug objects (cameras, simple meshes,...)
class RequiredArg
Similar to Arg, except this one will crash if attempt to use the value while not initialized initialization can be done using the command line or manually.
class RequiredArg< std::string >
Specialization required for std::string as const string & key constructor and const T & constructor are ambiguous.
class RequiredArgBase
Represent a mandatory argument.
class Resources
Singleton used to store a list of plausible path to look for (based on the ibr_resources.ini)
class RGBDInputTextures
class RGBInputTextureArray
class RTTextureSize
struct ScaleData
struct ScalingOptions
class SceneDebugView
Scene viewer for IBR scenes with a proxy, cameras and input images.
struct SegmentSelection
Represent a segment defined by the user by clicking on screen.
struct SelectionData
class ShaderAlphaMVP
Shader wrapper for sending mesh display options to the GPU (while avoiding duplicated uniforms) .
class ShadowMapRenderer
Render high quality soft shadows, designed to mimick the sun shadowing.
class Skybox
A skybox object for rendering a cubemap texture.
class StereoAnaglyphRdrMode
Stereo rendering mode: two slightly shifted views are rendered and composited as anaglyphs.
struct SubView
struct Switch
Used to wrap a toggle argument in the command line.
class Texture2D
Represent a 2D texture on the GPU, with custom format and type.
class Texture2DArray
Represent an array of 2D textures on the GPU, with custom format, type and slice count.
class TextureCubeMap
Represent a cubemap composed of 6 2D faces on the GPU, with custom format and type.
class TexturedMeshRenderer
Render a textured mesh, using per-vertex texture coordinates.
class TexturedMeshView
Wrap a Textured Mesh renderer with additional parameters and information.
class ThreadIdWorker
Class used to work concurrently on multiple tasks/instructions.
struct TimeHistogram
class Timer
Timer to monitor performance of a section of code.
class TrackBall
Provide a handler to interact using a trackball (based on mouse motions).
class Transform3
Represent a 3D transformation composed of a rotation and translation.
class UIShortcuts
Register and display keyboard shortcuts.
struct ULRAppArgs
Arguments for all ULR applications.
class ULRRenderer
Legacy ULR renderer.
class ULRV2Renderer
Second version of the ULR render.
class ULRV2View
View associated to ULRRenderer v2, providing interface and options.
class ULRV3Renderer
Perform per-pixel Unstructured Lumigraph Rendering (Buehler et al., 2001).
class ULRV3View
Wrap a ULR renderer with additional parameters and information.
class ULRView
View associated to ULRRenderer v1, providing interface and options.
struct UV
class UVUnwrapper
Unwraps a mesh onto a plane, generating texture coordinates for each vertex.
struct ValidGLTexFormat
Helper class to specify for which image type we can find a valid texture format.
struct ValidGLTexFormat< cv::Mat >
Helper class to specify for which image type we can find a valid texture format.
struct ValidGLTexFormat< sibr::Image< ScalarType, N > >
Helper class to specify for which image type we can find a valid texture format.
struct ValueGetter
Helper to extract values from a vector of strings.
struct ValueGetter< bool >
Specialization of value getter for booleans.
struct ValueGetter< char >
Specialization of value getter for chars.
struct ValueGetter< double >
Specialization of value getter for doubles.
struct ValueGetter< float >
Specialization of value getter for floats.
struct ValueGetter< int >
Specialization of value getter for integers.
struct ValueGetter< sibr::Vector< T, N > >
Specialization of value getter for sibr::Vectors.
struct ValueGetter< std::array< T, N > >
Specialization of value getter for arrays.
struct ValueGetter< std::string >
Specialization of value getter for strings.
struct ValueGetter< uint >
Specialization of value getter for unsigned integers.
class Video
Video loaded from a file using OpenCV VideoCapture and FFMPEG.
class VideoGaussianPyramid
class VideoLaplacianPyramid
class VideoPlayer
Load and display a video in a view, with playback options.
class VideoUtils
class VideoVolume
class ViewBase
Basic view representation.
class Viewport
Represent an on-screen viewport using normalized coordinates, which can be nested into another viewport.
class VoxelGrid
Voxel grid with custom data storage.
class VoxelGridBase
Basic voxel grid interface provinding cell manipulation and query helpers.
class Window
System window backed by an internal framebuffer.
struct WindowAppArgs
Combination of window and application arguments.
struct WindowArgs
Arguments related to a window.
class XMLTree
Wrapper of rapidxml xml_document<> class so that the string associated to the xml file stays in memory.
struct ZoomData
Store additional user zoom information to be returned when displaying an image.
struct ZoomInterraction
Store user interaction and zooming information to be returned when displaying an image.
Typedefs
typedef Vector4f ColorRGBA
typedef Image< unsigned char, 3 > ImageRGB
Standard image types.
typedef Image< unsigned char, 4 > ImageRGBA
typedef Image< unsigned char, 1 > ImageL8
typedef Image< unsigned char, 2 > ImageUV8
typedef Image< unsigned short int, 3 > ImageRGB16
typedef Image< unsigned short int, 1 > ImageL16
typedef Image< float, 3 > ImageRGB32F
typedef Image< float, 3 > ImageFloat3
typedef Image< float, 4 > ImageRGBA32F
typedef Image< float, 4 > ImageFloat4
typedef Image< float, 1 > ImageL32F
typedef Image< float, 1 > ImageFloat1
typedef Image< float, 2 > ImageFloat2
typedef Image< float, 2 > ImageUV32F
typedef Image< bool, 1 > ImageBool1
typedef Image< double, 1 > ImageDouble1
typedef Image< double, 2 > ImageDouble2
typedef Image< double, 3 > ImageDouble3
typedef Image< double, 4 > ImageDouble4
typedef Image< int, 1 > ImageInt1
typedef Image< int, 2 > ImageInt2
typedef Image< int, 3 > ImageInt3
typedef Image< int, 4 > ImageInt4
typedef RenderTarget< unsigned char, 3 > RenderTargetRGB
typedef RenderTarget< unsigned char, 4 > RenderTargetRGBA
typedef RenderTarget< unsigned char, 1 > RenderTargetLum
typedef RenderTarget< unsigned short, 1 > RenderTargetLum16
typedef RenderTarget< unsigned short, 2 > RenderTargetUV16
typedef RenderTarget< unsigned short, 3 > RenderTargetRGB16
typedef RenderTarget< unsigned short, 4 > RenderTargetRGBA16
typedef RenderTarget< int, 1 > RenderTargetInt1
typedef RenderTarget< float, 3 > RenderTargetRGB32F
typedef RenderTarget< float, 4 > RenderTargetRGBA32F
typedef RenderTarget< float, 1 > RenderTargetLum32F
typedef RenderTarget< float, 2 > RenderTargetUV32F
typedef Texture2D< unsigned char, 3 > Texture2DRGB
typedef Texture2D< unsigned char, 4 > Texture2DRGBA
typedef Texture2D< unsigned char, 1 > Texture2DLum
typedef Texture2D< unsigned short, 4 > Texture2DRGBA16
typedef Texture2D< unsigned short, 1 > Texture2DLum16
typedef Texture2D< unsigned short, 2 > Texture2DUV16
typedef Texture2D< short, 2 > Texture2DUV16s
typedef Texture2D< float, 3 > Texture2DRGB32F
typedef Texture2D< float, 4 > Texture2DRGBA32F
typedef Texture2D< float, 2 > Texture2DUV32F
typedef Texture2D< float, 1 > Texture2DLum32F
typedef Texture2DArray< unsigned char, 1 > Texture2DArrayLum
typedef Texture2DArray< unsigned char, 2 > Texture2DArrayUV
typedef Texture2DArray< unsigned char, 3 > Texture2DArrayRGB
typedef Texture2DArray< unsigned char, 4 > Texture2DArrayRGBA
typedef Texture2DArray< unsigned short, 1 > Texture2DArrayLum16
typedef Texture2DArray< unsigned short, 2 > Texture2DArrayUV16
typedef Texture2DArray< unsigned short, 3 > Texture2DArrayRGB16
typedef Texture2DArray< unsigned short, 4 > Texture2DArrayRGBA16
typedef Texture2DArray< short, 1 > Texture2DArrayLum16s
typedef Texture2DArray< short, 2 > Texture2DArrayUV16s
typedef Texture2DArray< short, 3 > Texture2DArrayRGB16s
typedef Texture2DArray< short, 4 > Texture2DArrayRGBA16s
typedef Texture2DArray< int, 1 > Texture2DArrayInt1
typedef Texture2DArray< int, 2 > Texture2DArrayInt2
typedef Texture2DArray< int, 3 > Texture2DArrayInt3
typedef Texture2DArray< int, 4 > Texture2DArrayInt4
typedef Texture2DArray< float, 1 > Texture2DArrayLum32F
typedef Texture2DArray< float, 2 > Texture2DArrayUV32F
typedef Texture2DArray< float, 3 > Texture2DArrayRGB32F
typedef Texture2DArray< float, 4 > Texture2DArrayRGBA32F
typedef TextureCubeMap< unsigned char, 1 > TextureCubeMapLum
typedef TextureCubeMap< unsigned char, 3 > TextureCubeMapRGB
typedef TextureCubeMap< unsigned char, 4 > TextureCubeMapRGBA
typedef TextureCubeMap< unsigned short, 1 > TextureCubeMapLum16
typedef TextureCubeMap< unsigned short, 2 > TextureCubeMapUV16
typedef TextureCubeMap< unsigned short, 4 > TextureCubeMapRGBA16
typedef TextureCubeMap< short, 2 > TextureCubeMapUV16s
typedef TextureCubeMap< float, 1 > TextureCubeMapLum32F
typedef TextureCubeMap< float, 3 > TextureCubeMapRGB32F
typedef TextureCubeMap< float, 4 > TextureCubeMapRGBA32F
using ArgSwitch = Arg< Switch >
typedef Eigen::Matrix< unsigned, 4, 4, Eigen::DontAlign, 4, 4 > Matrix4u
typedef Eigen::Matrix< int, 4, 4, Eigen::DontAlign, 4, 4 > Matrix4i
typedef Eigen::Matrix< float, 4, 4, Eigen::DontAlign, 4, 4 > Matrix4f
typedef Eigen::Matrix< double, 4, 4, Eigen::DontAlign, 4, 4 > Matrix4d
typedef Eigen::Matrix< unsigned, 3, 3, Eigen::DontAlign, 3, 3 > Matrix3u
typedef Eigen::Matrix< int, 3, 3, Eigen::DontAlign, 3, 3 > Matrix3i
typedef Eigen::Matrix< float, 3, 3, Eigen::DontAlign, 3, 3 > Matrix3f
typedef Eigen::Matrix< double, 3, 3, Eigen::DontAlign, 3, 3 > Matrix3d
typedef Eigen::Quaternion< unsigned > Quaternionu
typedef Eigen::Quaternion< int > Quaternioni
typedef Eigen::Quaternion< float > Quaternionf
typedef Eigen::Quaternion< double > Quaterniond
typedef Rect< float > Rectf
typedef Rect< int > Recti
typedef Transform3< float > Transform3f
Helper def.
template<typename T , int N>
using Vector = Eigen::Matrix< T, N, 1, Eigen::DontAlign >
typedef Eigen::Matrix< float, 1, 1, Eigen::DontAlign > Vector1f
typedef Eigen::Matrix< int, 1, 1, Eigen::DontAlign > Vector1i
typedef Eigen::Matrix< unsigned, 2, 1, Eigen::DontAlign > Vector2u
typedef Eigen::Matrix< unsigned char, 2, 1, Eigen::DontAlign > Vector2ub
typedef Eigen::Matrix< int, 2, 1, Eigen::DontAlign > Vector2i
typedef Eigen::Matrix< float, 2, 1, Eigen::DontAlign > Vector2f
typedef Eigen::Matrix< double, 2, 1, Eigen::DontAlign > Vector2d
typedef Eigen::Matrix< unsigned, 3, 1, Eigen::DontAlign > Vector3u
typedef Eigen::Matrix< unsigned char, 3, 1, Eigen::DontAlign > Vector3ub
typedef Eigen::Matrix< unsigned short int, 3, 1, Eigen::DontAlign > Vector3s
typedef Eigen::Matrix< int, 3, 1, Eigen::DontAlign > Vector3i
typedef Eigen::Matrix< float, 3, 1, Eigen::DontAlign > Vector3f
typedef Eigen::Matrix< double, 3, 1, Eigen::DontAlign > Vector3d
typedef Eigen::Matrix< unsigned, 4, 1, Eigen::DontAlign > Vector4u
typedef Eigen::Matrix< unsigned char, 4, 1, Eigen::DontAlign > Vector4ub
typedef Eigen::Matrix< int, 4, 1, Eigen::DontAlign > Vector4i
typedef Eigen::Matrix< float, 4, 1, Eigen::DontAlign > Vector4f
typedef Eigen::Matrix< double, 4, 1, Eigen::DontAlign > Vector4d
using PingPong4u = PingPongTexture< 4 >
using PingPong3u = PingPongTexture< 3 >
using PingPong1u = PingPongTexture< 1 >
using MultipleVideoDecoder1u = MultipleVideoDecoder< uchar, 1 >
using MultipleVideoDecoder3u = MultipleVideoDecoder< uchar, 3 >
using MultipleVideoDecoderArray1u = MultipleVideoDecoderArray< uchar, 1 >
using MultipleVideoDecoderArray3u = MultipleVideoDecoderArray< uchar, 3 >
using Volume3f = VideoVolume< float, 3 >
using Volume1f = VideoVolume< float, 1 >
using Volume4u = VideoVolume< uchar, 4 >
using Volume3u = VideoVolume< uchar, 3 >
using Volume1u = VideoVolume< uchar, 1 >
using Histo1f = Histogram< float, 1 >
using ColorHistogram = Histogram< uchar, 3 >
typedef UV< sibr::MINUS_ONE_ONE > UV11
typedef UV< sibr::ZERO_ONE > UV01
typedef UV< sibr::ONE_ZERO > UV10
Enumerations
enum RenderingModes { RENDERMODE_MONO, RENDERMODE_STEREO_ANAGLYPH, RENDERMODE_STEREO_QUADBUFFER }
Available rendering modes for IBR views.
enum FilePickerMode { Default, Save, Directory }
Selection mode for the file picker.
enum UVspace { ZERO_ONE, MINUS_ONE_ONE, ONE_ZERO }
Functions
std::string imageIdToString (int id)
Utility that converts an integer id to a string using the "most used" format.
template<unsigned int N>
std::string intToString (int id)
Generate a string representation of an integer, padded with zeros.
std::string getProxyFilename (const std::string &datasetPath)
Get the default path and filename used for the proxy mesh.
ByteStream & operator<< (ByteStream &stream, const Camera &c)
Write a camera to a byte stream.
ByteStream & operator>> (ByteStream &stream, Camera &c)
Read a camera from a byte stream.
template<typename T >
T clamp (T value, T min, T max)
Clamp a value.
bool showImGuiWindow (const std::string &windowTitle, const IRenderTarget &rt, ImGuiWindowFlags flags, Viewport &viewport, bool invalidTexture, bool updateLayout, int handle=0)
Show the content of a rendertarget in an ImGui window.
Mesh::Ptr generateMeshForText (const std::string &text, unsigned int &separationIndex)
Generate a mesh for a given label, using ImGui internally.
void fitImageToDisplayRegion (const Vector2f &imgSize, const Vector2i &regionSize, Vector2f &offset, Vector2f &size)
Helper that compute the location and extent to display an image in a given region without cropping or distorting it.
void DisplayImageGui (GLuint texture, const sibr::Vector2i &displaySize, const sibr::Vector2f &uv0={ 0, 0 }, const sibr::Vector2f &uv1={ 1, 1 })
Display an image using ImGui::image, with additional options.
void ImageWithCallback (GLuint texture, const sibr::Vector2i &displaySize, CallBackData &callbackDataOut, const sibr::Vector2f &uv0={ 0, 0 }, const sibr::Vector2f &uv1={ 1, 1 })
Display an image using ImGui::image with support for returning interaction information (did the user click the image, etc.).
void ImageWithZoom (GLuint texture, const sibr::Vector2i &displaySize, ZoomInterraction &zoom)
Display an image using ImGui::image with support for returning user zoom information.
sibr::ImageRGBA convertL32FtoRGBA (const sibr::ImageL32F &imgF)
Convert a L32F into a RGBA image while preserving bit-level representation.
sibr::ImageL32F convertRGBAtoL32F (const sibr::ImageRGBA &imgRGBA)
Convert a RGBA into a L32F image while preserving bit-level representation.
sibr::ImageRGBA convertRGB32FtoRGBA (const sibr::ImageRGB32F &imgF)
Convert a RGB32F into a RGBA image (3 times wider) while preserving bit-level representation.
sibr::ImageRGB32F convertRGBAtoRGB32F (const sibr::ImageRGBA &imgRGBA)
Convert a RGBA into a RGB32F image while preserving bit-level representation.
sibr::ImageRGBA convertNormalMapToSphericalHalf (const sibr::ImageRGB32F &imgF)
Convert a RGB32 normal map into a UV16 map storing theta and phi as half floats, packed into a RGBA8.
sibr::ImageRGB32F convertSphericalHalfToNormalMap (const sibr::ImageRGBA &imgF)
Convert a RGBA map, packing theta and phi as half floats, into a RGB32 normal map.
Image< unsigned char, 3 > coloredClass (const Image< unsigned char, 1 >::Ptr imClass)
Convert an integer ID map to a colored image using a different random color for each ID.
Image< unsigned char, 3 > coloredClass (const Image< int, 1 >::Ptr imClass)
Convert an integer ID map to a colored image using a different random color for each ID.
void showFloat (const Image< float, 1 > &im, bool logScale=false, double min=-DBL_MAX, double max=DBL_MAX)
Display a 32F image in a debug window, using the Parula colormap after normalizing the values.
cv::Mat duplicate3 (cv::Mat c)
Create a three channels cv::Mat by repeating a single channel cv::Mat.
template<typename T_Type , unsigned T_NumComp>
static void show (const Image< T_Type, T_NumComp > &img, const std::string &windowTitle="sibr::show()", bool closeWindow=true)
Display an image into a popup OpenCV window.
template<typename sibr_T , typename openCV_T , int N>
Vector< sibr_T, N > fromOpenCV (const cv::Vec< openCV_T, N > &vec)
template<typename openCV_T , typename sibr_T , int N>
cv::Vec< openCV_T, N > toOpenCV (const Vector< sibr_T, N > &vec)
KeyCombination operator&& (const KeyCombination &combA, const KeyCombination &combB)
Merge two set of pressed keys.
template<typename TTo , typename TFrom >
static std::vector< TTo > prepareVertexData (const std::vector< TFrom > &fromData, uint numVertices)
template<typename TTo , typename TFrom >
static void appendVertexData (std::vector< TTo > &toData, const std::vector< TFrom > &fromData)
template<typename T >
static uint getVectorDataSize (const std::vector< T > &v)
template<typename TTo , typename TFrom >
static std::vector< TTo > prepareVertexData (const std::vector< TFrom > &fromData, uint numVertices)
template<typename TTo , typename TFrom >
static void appendVertexData (std::vector< TTo > &toData, const std::vector< TFrom > &fromData)
template<typename T >
static uint getVectorDataSize (const std::vector< T > &v)
void blit (const IRenderTarget &src, const IRenderTarget &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a render target to another render target, resizing if needed.
void blit_and_flip (const IRenderTarget &src, const IRenderTarget &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a render target to another render target, resizing if needed and flipping the result.
template<typename T_Type , unsigned T_NumComp>
static void show (const RenderTarget< T_Type, T_NumComp > &rt, uint layer=0, const std::string &windowTitle="sibr::show()", bool closeWindow=true)
Display a rendertarget color content in a popup window (backed by OpenCV).
template<typename T_Type , unsigned T_NumComp>
static void showDepth (const RenderTarget< T_Type, T_NumComp > &rt, const std::string &windowTitle="sibr::show()", bool closeWindow=true)
Display a rendertarget depth content in a popup window (backed by OpenCV).
template<typename T_Type , unsigned T_NumComp>
static void showDepthFromAlpha (const RenderTarget< T_Type, T_NumComp > &rt, const std::string &windowTitle="sibr::show()", bool closeWindow=true)
Display a rendertarget alpha content as a grey map in a popup window (backed by OpenCV).
static const std::vector< float > & getCameraStubVertices (float camStubSize=0.1f)
static const std::vector< uint > & getCameraStubIndices (void)
static std::string strRemoveSpaces (const std::string &str)
std::string loadFile (const std::string &filename, const GLShader::Define::List &defines)
Load a file from disk and apply macro-like substitutions.
void blit (const ITexture2D &src, const IRenderTarget &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR, bool flip=false)
Copy the content of a texture to a render target, resizing if needed.
void blit_and_flip (const ITexture2D &src, const IRenderTarget &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a texture to a render target, resizing if needed and flipping the result.
void blitToColorAttachment (const ITexture2D &src, IRenderTarget &dst, int location, GLenum filter=GL_LINEAR, bool flip=false)
Copy the content of a texture to a specific color attachment of the destination render target, resizing if needed.
void blit (const IRenderTarget &src, const ITexture2D &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a rendertarget first color attachment to a texture, resizing if needed.
void blit (const ITexture2D &src, const ITexture2D &dst, GLbitfield mask=GL_COLOR_BUFFER_BIT, GLenum filter=GL_LINEAR)
Copy the content of a texture to another texture, resizing if needed.
template<typename T_Type , unsigned T_NumComp>
static void show (const RenderTarget< T_Type, T_NumComp > &rt, const std::string &winTitle="sibr::show()")
Display a RenderTarget into a popup OpenCV window.
template<typename T_Type , unsigned T_NumComp>
static void show (const Texture2D< T_Type, T_NumComp > &texture, const std::string &winTitle="sibr::show()")
Display a texture into a popup OpenCV window.
cv::Scalar jetColor (float gray)
Generate a color for a given scalar score, using the jet color map.
sibr::Vector3ub getLinearColorFromProbaV (double proba)
Generate a color for a given scalar score, using a reversible mapping.
double getProbaFromLinearColor (const sibr::Vector3ub &color)
Convert a color to the associated scalar score, using a reversible mapping.
sibr::Vector2d cartesianToSpherical (const sibr::Vector3d &dir)
Convert a direction from cartesian to spherical coordinates.
sibr::Vector2d cartesianToSphericalUVs (const sibr::Vector3d &dir)
Convert a direction from cartesian to spherical UVs.
float sRGB2LinF (float inF)
float lin2sRGBF (float inF)
void sRGB2Lin (sibr::ImageRGB32F &img)
Inplace conversion of float image from sRGB space to linear.
void lin2sRGB (sibr::ImageRGB32F &img)
Inplace conversion of a float image from linear space to sRGB.
template<typename T_Type >
static Eigen::Matrix< T_Type, 3, 1, Eigen::DontAlign > randomColor ()
Generate a random color.
template<typename FunType , typename ... ArgsType>
void renderTask (const std::string &s, FunType &&f, ArgsType &&... args)
Debug helper: wrap a rendering task in an openGL debug group (visible in Renderdoc).
float lerp (float A, float B, float fac)
Interpolate between two values.
float inverseLerp (float from, float to, float current)
Express a value as the linear combination of two other values.
static void glfwErrorCallback (int error, const char *description)
static void glErrorCallback (GLenum src, GLenum type, GLuint id, GLenum severity, GLsizei size, const GLchar *str, const void *user)
static void glfwKeyboardCallback (GLFWwindow *window, int key, int scancode, int action, int mods)
static void glfwResizeCallback (GLFWwindow *window, int w, int h)
static void glfwCursorPosCallback (GLFWwindow *, double x, double y)
static void glfwMouseButtonCallback (GLFWwindow *window, int button, int action, int mods)
static void glfwMouseScrollCallback (GLFWwindow *window, double x, double y)
sibr::Vector3f orthoVector (const sibr::Vector3f &v)
Generate a vector orthogonal to the input one.
const CommandLineArgs & getCommandLineArgs ()
Getter for the command line args manager singleton.
float round (float x)
Rounding operation.
Matrix4f perspective (float fovRadian, float ratio, float zn, float zf, const sibr::Vector2f &p)
Matrix4f perspectiveOffCenter (float left, float right, float bottom, float top, float mynear, float myfar)
Generate an off-center perspective matrix.
Matrix4f perspectiveStereo (float fovRadian, float aspect, float zn, float zf, float focalDistance, float eyeDistance, bool isLeftEye)
Generate a perspective matrix for stereo rendering.
Matrix4f orthographic (float right, float top, float mynear, float myfar)
Generate an orthographic matrix.
Matrix4f lookAt (const Vector3f &eye, const Vector3f &center, const Vector3f &up)
Generate a view matrix using the look at parameters.
void operator<< (std::ofstream &outfile, const Matrix4f &m)
Output a Matrix4f to a file stream.
void operator>> (std::ifstream &infile, Matrix4f &out)
Read a Matrix4f from a file stream.
template<typename T >
Eigen::Matrix< T, 4, 4, 0, 4, 4 > matFromQuat (const Eigen::Quaternion< T, 0 > &q)
Convert a quaternion to a rotation matrix.
template<typename T , int Options>
Eigen::Matrix< T, 4, 4, 0, 4, 4 > matFromTranslation (const Eigen::Matrix< T, 3, 1, Options > &vec)
Convert a translation to a rotation matrix.
Matrix4f SIBR_SYSTEM_EXPORT perspective (float fovRadian, float ratio, float zn, float zf, const ::sibr::Vector2f &p={0.5f, 0.5f})
Generate a perspective matrix.
template<typename T , int Options>
Eigen::Quaternion< T, 0 > quatFromMatrix (const Eigen::Matrix< T, 3, 3, Options, 3, 3 > &m)
Build a quaternion from a rotation matrix.
template<typename T , int Options>
Eigen::Quaternion< T, 0 > quatFromMatrix (const Eigen::Matrix< T, 4, 4, Options, 4, 4 > &m)
Build a quaternion from a rotation matrix.
template<typename T , int Options>
Eigen::Quaternion< T, 0 > quatFromEulerAngles (const Eigen::Matrix< T, 3, 1, Options > &deg)
Build a quaternion from rotation euler angles.
template<typename T , int Options>
Eigen::Matrix< T, 3, 1, Options > quatRotateVec (const Eigen::Quaternion< T, 0 > &rotation, const Eigen::Matrix< T, 3, 1, Options > &vec)
Rotate a vector using a quaternion.
template<typename T >
static Eigen::Quaternion< T > dot (const Eigen::Quaternion< T > &q1, const Eigen::Quaternion< T > &q2)
Quaternion product.
template<typename T >
static float angleRadian (const Eigen::Quaternion< T > &q1, const Eigen::Quaternion< T > &q2)
Compute the delta angle between two quaternions.
template<typename T >
static Eigen::Quaternion< T > lerp (const Eigen::Quaternion< T > &q1, const Eigen::Quaternion< T > &q2, float t)
Linear quaternion interpolation.
template<typename T >
static Eigen::Quaternion< T > slerp (const Eigen::Quaternion< T > &q1, const Eigen::Quaternion< T > &q2, float t)
Spherical quaternion interpolation.
std::string strSearchAndReplace (const std::string &src, const std::string &search, const std::string &replaceby)
Replaces all occurences of a substring with another substring.
std::string removeExtension (const std::string &str)
Process a string (a filename or path) to remove any extension if it exists.
std::string getExtension (const std::string &str)
Process a string (a filename or path) to extract the file extension if it exists.
std::string parentDirectory (const std::string &str)
Process a string (a path) to return the parent directory.
SIBR_SYSTEM_EXPORT std::string getFileName (const std::string &str)
Process a string (a path) to return the file name.
bool strContainsOnlyDigits (const std::string &str)
Check if a string only contains digits.
std::vector< std::string > split (const std::string &str, char delim='\n')
Split string into sub-strings delimited by a given character.
std::string sprint (const char *msg,...)
Wrapper around sibr::sprintf that returns a string.
int sprintf (char *buffer, size_t size, const char *format,...)
Write a formatted string with inserted values to a buffer.
SIBR_SYSTEM_EXPORT std::string to_lower (const std::string &str)
Convert the input string to lowert case.
SIBR_SYSTEM_EXPORT bool find_any (const std::vector< std::string > &needles, const std::string &haystack)
Find if a list of substring is present in a given string.
std::string timestamp (const std::string &format="%Y_%m_%d_%H_%M_%S")
Write the current timestamp to a string.
template<typename T >
ByteStream & operator<< (ByteStream &stream, const Transform3< T > &t)
Write transformation to a byte stream.
template<typename T >
ByteStream & operator>> (ByteStream &stream, Transform3< T > &t)
Read transformation from a byte stream.
std::string loadFile (const std::string &filename)
Load the whole file into a std::string.
void makeDirectory (const std::string &path)
Create directory (if it doesn't exist already)
std::vector< std::string > listFiles (const std::string &path, const bool listHidden=false, const bool includeSubdirectories=false, const std::vector< std::string > &allowedExtensions={})
List content of directory, sorted alphabetically.
std::vector< std::string > listSubdirectories (const std::string &path, const bool listHidden=false)
List content of directory, sorted alphabetically, including subdirectories.
bool copyDirectory (const std::string &src, const std::string &dst)
Copy directory.
bool copyFile (const std::string &src, const std::string &dst, const bool overwrite=false)
Copy file.
void emptyDirectory (const std::string &path)
Empty a directory (if it exist already)
bool fileExists (const std::string &path)
Test if a file exists.
bool directoryExists (const std::string &path)
Test if a directory exists.
size_t getAvailableMem ()
SIBR_SYSTEM_EXPORT std::string getInstallDirectory ()
SIBR_SYSTEM_EXPORT std::string getBinDirectory ()
SIBR_SYSTEM_EXPORT std::string getShadersDirectory (const std::string &subfolder)
SIBR_SYSTEM_EXPORT std::string getScriptsDirectory ()
SIBR_SYSTEM_EXPORT std::string getResourcesDirectory ()
SIBR_SYSTEM_EXPORT std::string getAppDataDirectory ()
SIBR_SYSTEM_EXPORT std::string getInstallSubDirectory (const std::string &subfolder)
bool showFilePicker (std::string &selectedElement, const FilePickerMode mode, const std::string &directoryPath="", const std::string &extensionsAllowed="")
Present a native OS file picker.
template<typename FunType , typename ... ArgsType>
void taskTiming (const std::string &s, FunType &&f, ArgsType &&... args)
Measure and print the timing of a task.
Vector3f toColorFloat (Vector3ub &colorUB)
Vector3ub toColorUB (Vector3f &colorFloat)
Eigen::Matrix< float, 4, 4, Eigen::DontAlign > alignRotationMatrix (const sibr::Vector3f &from, const sibr::Vector3f &to)
Return a 4x4 3D rotation matrix that aligns the first vector onto the second one.
template<typename T , int N, int Options>
Eigen::Matrix< T, N, 1, Options > frac (const Eigen::Matrix< T, N, 1, Options > &A)
Fractional part of each component.
template<typename T , int N, int Options>
T distance (const Eigen::Matrix< T, N, 1, Options > &A, const Eigen::Matrix< T, N, 1, Options > &B)
Distance between two vectors.
template<typename T , int N, int Options>
T length (const Eigen::Matrix< T, N, 1, Options > &A)
Return the length of a vector.
template<typename T , int N, int Options>
T sqLength (const Eigen::Matrix< T, N, 1, Options > &A)
Return the squared length of a vector.
template<typename T , int N, int Options>
T dot (const Eigen::Matrix< T, N, 1, Options > &A, const Eigen::Matrix< T, N, 1, Options > &B)
Compute the dot product of two vectors.
template<typename T , int N, int Options>
Eigen::Matrix< T, N, 1, Options > cross (const Eigen::Matrix< T, N, 1, Options > &A, const Eigen::Matrix< T, N, 1, Options > &B)
Compute the cross product of two vectors.
template<typename T , int N>
Vector< T, N > clamp (const Vector< T, N > &A, const Vector< T, N > &min, const Vector< T, N > &max)
Clamp each component of a vector between two values.
template<typename T , int N, int Options>
T cotan (const Eigen::Matrix< T, N, 1, Options > &A, const Eigen::Matrix< T, N, 1, Options > &B)
Compute the cotangent of the angle between two vectors.
SIBR_SYSTEM_EXPORT Eigen::Matrix< float, 3, 1, Eigen::DontAlign > toColorFloat (Vector< unsigned char, 3 > &colorUB)
Convert an unsigned char color in [0,255] to a float color in [0,1].
SIBR_SYSTEM_EXPORT Eigen::Matrix< unsigned char, 3, 1, Eigen::DontAlign > toColorUB (Vector< float, 3 > &colorFloat)
Convert a float color in [0,1] to an unsigned char color in [0,255].
template<typename T_in , typename T_out = T_in>
T_out sum (const std::vector< T_in > &vec, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Sum elements from a vector.
template<typename T_in , typename T_out = T_in>
std::vector< T_out > weighted_normalization (const std::vector< T_in > &vec, const std::vector< T_in > &weights, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Weighted sum of elements in a vector.
template<typename T_in , typename T_out = T_in>
std::vector< T_out > applyLambda (const std::vector< T_in > &vec, const std::function< T_out(T_in)> &f)
Apply a function to each element of a vector (not in place)
template<typename T_in , typename T_out >
std::vector< T_out > applyLambda (const std::vector< T_in > &vec1, const std::vector< T_in > &vec2, const std::function< T_out(T_in, T_in)> &f)
Apply a function to each pair of elements from two vectors of same size (not in place).
template<typename T_in , typename T_out = T_in>
T_out var (const std::vector< T_in > &vec, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Compute the variance of elements in a vector.
template<typename T_in , typename T_out = T_in>
std::vector< T_out > normalizedMinMax (const std::vector< T_in > &vec, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Normalize all elements in a vector based on the min and max values in it (not in place).
template<typename T_in , typename T_out = T_in, unsigned int Power = 2>
std::vector< T_out > normalizedZeroOne (const std::vector< T_in > &vec, const std::function< bool(T_in)> &f=[](T_in val) { return true;})
Apply a power-sum normalization.
std::vector< cv::Mat > cvSplitChannels (cv::Mat mat)
Volume3u loadVideoVolume (const std::string &filepath)
Volume3u loadVideoVolume (sibr::Video &video)
SIBR_VIDEO_EXPORT uint optimal_num_levels (uint length)
SIBR_VIDEO_EXPORT std::vector< sibr::Volume3u > gaussianPyramid (const sibr::Volume3u &vid, uint num_levels)
SIBR_VIDEO_EXPORT std::vector< sibr::Volume3u > gaussianPyramidTemporal (const sibr::Volume3u &vid, uint num_levels)
std::vector< sibr::Volume3u > laplacianPyramid (const sibr::Volume3u &vid, uint num_levels)
std::vector< sibr::Volume3u > laplacianPyramidTemporalDouble (const sibr::Volume3u &vid, uint num_levels)
SIBR_VIDEO_EXPORT sibr::Volume3u collapseLaplacianPyramid (const std::vector< sibr::Volume3u > &pyr, double shift)
SIBR_VIDEO_EXPORT sibr::Volume3u laplacianBlending (const sibr::Volume3u &vA, const sibr::Volume3u &vB, std::vector< sibr::Volume1u > &pyrM)
PyramidLayer blur (const PyramidLayer &layer, const PyramidParameters &params)
PyramidLayer temporalBlur (const PyramidLayer &layer, const PyramidParameters &params, float scaling)
void temporalBlurInPlace (PyramidLayer &layer, const PyramidParameters &params, float scaling)
PyramidLayer decimate (const PyramidLayer &layer, const PyramidParameters &params)
PyramidLayer upscale (const PyramidLayer &layerUp, const PyramidLayer &layerDown, const PyramidParameters &params)
PyramidLayer downscale (const PyramidLayer &layer, const PyramidParameters &params)
SIBR_VIDEO_EXPORT cv::Mat slice (const PyramidLayer &layer, int i, int j, bool vertical, bool center)
VideoGaussianPyramid buildVideoGaussianPyramid (const cv::Mat &volume, int w, int h, int nLevels, const PyramidParameters &params, bool show)
VideoGaussianPyramid buildVideoGaussianPyramid (sibr::Video &vid, int nLevels, const PyramidParameters &params, bool show)
SIBR_VIDEO_EXPORT VideoLaplacianPyramid buildVideoLaplacianPyramid (PyramidLayer vid, int nLevels, const PyramidParameters &params, bool show)
VideoLaplacianPyramid buildVideoLaplacianPyramid (sibr::Video &vid, int nLevels, const PyramidParameters &params, bool show)
VideoLaplacianPyramid buildVideoLaplacianPyramidFullyReduced (PyramidLayer vid, int nLevels, const PyramidParameters &params, bool show)
SIBR_VIDEO_EXPORT void convertReducedVideoPyramidTo128 (VideoLaplacianPyramid &vid)
PyramidLayer videoLaplacianBlending (sibr::Video &vidA, sibr::Video &vidB, PyramidLayer mask_volume)
PyramidLayer videoLaplacianBlending (PyramidLayer vidA, PyramidLayer vidB, PyramidLayer mask_volume, PyramidParameters params, bool show)
std::vector< FullContribData > videoLaplacianBlendingContrib (PyramidLayer vidA, PyramidLayer vidB, PyramidLayer mask_volume, PyramidParameters params)
void videoLaplacianBlendingDebug (PyramidLayer vidA, PyramidLayer vidB, PyramidLayer mask_volume, PyramidParameters params)
template<typename T , uint N>
cv::Mat cvConvertMatTo (cv::Mat mat, double scale=1.0)
template<typename T , uint N, uint M>
VideoVolume< T, N+M > concatVolumesChannels (const sibr::VideoVolume< T, N > &A, const sibr::VideoVolume< T, M > &B)
template<uint M>
std::vector< sibr::VideoVolume< uchar, M > > extendedBlurPyramid (const sibr::VideoVolume< uchar, M > &vid, uint num_levels=0)
template<uint M>
std::vector< sibr::VideoVolume< uchar, M > > gaussianPyramid (const sibr::VideoVolume< uchar, M > &vid, uint num_levels=0)
template<typename T , uint M>
std::vector< sibr::VideoVolume< T, M > > gaussianPyramidTemporal (const sibr::VideoVolume< T, M > &vid, uint num_levels=0)
template<typename T , uint M>
std::vector< sibr::VideoVolume< T, M > > gaussianPyramidTemporalBox (const sibr::VideoVolume< T, M > &vid, uint num_levels=0)
template<typename U , typename T = U>
std::vector< VideoVolume< T, 3 > > laplacianPyramidTemporal (const VideoVolume< U, 3 > &vid, uint num_levels=0)
template<typename T >
sibr::VideoVolume< T, 3 > collapseLaplacianPyramidTemporal (const std::vector< sibr::VideoVolume< T, 3 >> &pyr, double shift, bool debug=false)
template<typename T_V , typename T_M >
sibr::VideoVolume< T_V, 3 > laplacianBlendingTemporal (const sibr::VideoVolume< T_V, 3 > &vA, const sibr::VideoVolume< T_V, 3 > &vB, std::vector< sibr::VideoVolume< T_M, 1 >> &pyrM)
template<typename T , uint N, typename Pix = typename VideoVolume<float, N>::CVpixel>
cv::Mat_< Pix > totalVariation (const VideoVolume< T, N > &v)
template<typename T_Type , unsigned int T_NumComp>
static void show (const sibr::Texture2DArray< T_Type, T_NumComp > &texArray, sibr::Window *inputWin=nullptr, int w=-1, int h=-1)
Mesh::Ptr generateCamFrustum (const InputCamera &cam, float znear=-1, float zfar=-1)
Generate an accurate camera frustum.
Mesh::Ptr generateCamFrustumColored (const InputCamera &cam, const Vector3f &col, float znear=-1, float zfar=-1)
Generate an accurate camera frustum with a custom color.
Mesh::Ptr generateCamQuadWithUvs (const InputCamera &cam, float dist)
Generate a quad representing a camera image plane.
Variables
template<typename T , uint N>
constexpr uint getOpenCVtype = CV_MAKE_TYPE(OpenCVdepth<T>::value, N)
Helper to create a cv::Mat type from its depth and number of components.
template<typename T >
constexpr uint getOpenCVtypeSingleChannel = getOpenCVtype<T, 1>
Helper to create a one-channel cv::Mat from its depth.
static int windowCounter = 0
template<typename T >
constexpr uint NumberOfArg = 1
uint contexpr helper, defining the number of command line tokens required to init T
template<>
constexpr uint NumberOfArg< bool > = 0
uint contexpr helper, defining the number of command line tokens required to init T
template<>
constexpr uint NumberOfArg< Switch > = 0
uint contexpr helper, defining the number of command line tokens required to init T
Detailed Description
Todo:
TODO: If you care about security (did someone want to hack/use your app to hide a virus/retrieve informations from this compiled code), comment the following line and resolve warnings by finding new safe-functions.
Todo:
TODO: make shorter
Todo:
TODO: make shorter
Typedef Documentation
ArgSwitch
using sibr::ArgSwitch = typedef Arg<Switch>
Definition at line 231 of file CommandLineArgs.hpp.
MultipleVideoDecoder1u
using sibr::MultipleVideoDecoder1u = typedef MultipleVideoDecoder<uchar, 1>
Definition at line 186 of file MultipleVideoDecoder.hpp.
MultipleVideoDecoder3u
using sibr::MultipleVideoDecoder3u = typedef MultipleVideoDecoder<uchar, 3>
Definition at line 187 of file MultipleVideoDecoder.hpp.
MultipleVideoDecoderArray1u
using sibr::MultipleVideoDecoderArray1u = typedef MultipleVideoDecoderArray<uchar, 1>
Definition at line 188 of file MultipleVideoDecoder.hpp.
MultipleVideoDecoderArray3u
using sibr::MultipleVideoDecoderArray3u = typedef MultipleVideoDecoderArray<uchar, 3>
Definition at line 189 of file MultipleVideoDecoder.hpp.
PingPong1u
using sibr::PingPong1u = typedef PingPongTexture<1>
Definition at line 185 of file MultipleVideoDecoder.hpp.
PingPong3u
using sibr::PingPong3u = typedef PingPongTexture<3>
Definition at line 184 of file MultipleVideoDecoder.hpp.
PingPong4u
using sibr::PingPong4u = typedef PingPongTexture<4>
Definition at line 183 of file MultipleVideoDecoder.hpp.
Rectf
typedef Rect<float> sibr::Rectf
Definition at line 71 of file Rect.hpp.
Recti
typedef Rect<int> sibr::Recti
Definition at line 72 of file Rect.hpp.
RenderTargetInt1
typedef RenderTarget<int, 1> sibr::RenderTargetInt1
Definition at line 277 of file RenderTarget.hpp.
RenderTargetLum
typedef RenderTarget<unsigned char, 1> sibr::RenderTargetLum
Definition at line 270 of file RenderTarget.hpp.
RenderTargetLum16
typedef RenderTarget<unsigned short, 1> sibr::RenderTargetLum16
Definition at line 272 of file RenderTarget.hpp.
RenderTargetLum32F
typedef RenderTarget<float, 1> sibr::RenderTargetLum32F
Definition at line 281 of file RenderTarget.hpp.
RenderTargetRGB
typedef RenderTarget<unsigned char, 3> sibr::RenderTargetRGB
Definition at line 268 of file RenderTarget.hpp.
RenderTargetRGB16
typedef RenderTarget<unsigned short, 3> sibr::RenderTargetRGB16
Definition at line 274 of file RenderTarget.hpp.
RenderTargetRGB32F
typedef RenderTarget<float, 3> sibr::RenderTargetRGB32F
Definition at line 279 of file RenderTarget.hpp.
RenderTargetRGBA
typedef RenderTarget<unsigned char, 4> sibr::RenderTargetRGBA
Definition at line 269 of file RenderTarget.hpp.
RenderTargetRGBA16
typedef RenderTarget<unsigned short, 4> sibr::RenderTargetRGBA16
Definition at line 275 of file RenderTarget.hpp.
RenderTargetRGBA32F
typedef RenderTarget<float, 4> sibr::RenderTargetRGBA32F
Definition at line 280 of file RenderTarget.hpp.
RenderTargetUV16
typedef RenderTarget<unsigned short, 2> sibr::RenderTargetUV16
Definition at line 273 of file RenderTarget.hpp.
RenderTargetUV32F
typedef RenderTarget<float, 2> sibr::RenderTargetUV32F
Definition at line 282 of file RenderTarget.hpp.
Texture2DArrayInt1
typedef Texture2DArray<int, 1> sibr::Texture2DArrayInt1
Definition at line 642 of file Texture.hpp.
Texture2DArrayInt2
typedef Texture2DArray<int, 2> sibr::Texture2DArrayInt2
Definition at line 643 of file Texture.hpp.
Texture2DArrayInt3
typedef Texture2DArray<int, 3> sibr::Texture2DArrayInt3
Definition at line 644 of file Texture.hpp.
Texture2DArrayInt4
typedef Texture2DArray<int, 4> sibr::Texture2DArrayInt4
Definition at line 645 of file Texture.hpp.
Texture2DArrayLum
typedef Texture2DArray<unsigned char, 1> sibr::Texture2DArrayLum
Definition at line 627 of file Texture.hpp.
Texture2DArrayLum16
typedef Texture2DArray<unsigned short, 1> sibr::Texture2DArrayLum16
Definition at line 632 of file Texture.hpp.
Texture2DArrayLum16s
typedef Texture2DArray<short, 1> sibr::Texture2DArrayLum16s
Definition at line 637 of file Texture.hpp.
Texture2DArrayLum32F
typedef Texture2DArray<float, 1> sibr::Texture2DArrayLum32F
Definition at line 647 of file Texture.hpp.
Texture2DArrayRGB
typedef Texture2DArray<unsigned char, 3> sibr::Texture2DArrayRGB
Definition at line 629 of file Texture.hpp.
Texture2DArrayRGB16
typedef Texture2DArray<unsigned short, 3> sibr::Texture2DArrayRGB16
Definition at line 634 of file Texture.hpp.
Texture2DArrayRGB16s
typedef Texture2DArray<short, 3> sibr::Texture2DArrayRGB16s
Definition at line 639 of file Texture.hpp.
Texture2DArrayRGB32F
typedef Texture2DArray<float, 3> sibr::Texture2DArrayRGB32F
Definition at line 649 of file Texture.hpp.
Texture2DArrayRGBA
typedef Texture2DArray<unsigned char, 4> sibr::Texture2DArrayRGBA
Definition at line 630 of file Texture.hpp.
Texture2DArrayRGBA16
typedef Texture2DArray<unsigned short, 4> sibr::Texture2DArrayRGBA16
Definition at line 635 of file Texture.hpp.
Texture2DArrayRGBA16s
typedef Texture2DArray<short, 4> sibr::Texture2DArrayRGBA16s
Definition at line 640 of file Texture.hpp.
Texture2DArrayRGBA32F
typedef Texture2DArray<float, 4> sibr::Texture2DArrayRGBA32F
Definition at line 650 of file Texture.hpp.
Texture2DArrayUV
typedef Texture2DArray<unsigned char, 2> sibr::Texture2DArrayUV
Definition at line 628 of file Texture.hpp.
Texture2DArrayUV16
typedef Texture2DArray<unsigned short, 2> sibr::Texture2DArrayUV16
Definition at line 633 of file Texture.hpp.
Texture2DArrayUV16s
typedef Texture2DArray<short, 2> sibr::Texture2DArrayUV16s
Definition at line 638 of file Texture.hpp.
Texture2DArrayUV32F
typedef Texture2DArray<float, 2> sibr::Texture2DArrayUV32F
Definition at line 648 of file Texture.hpp.
Texture2DLum
typedef Texture2D<unsigned char, 1> sibr::Texture2DLum
Definition at line 613 of file Texture.hpp.
Texture2DLum16
typedef Texture2D<unsigned short, 1> sibr::Texture2DLum16
Definition at line 616 of file Texture.hpp.
Texture2DLum32F
typedef Texture2D<float, 1> sibr::Texture2DLum32F
Definition at line 624 of file Texture.hpp.
Texture2DRGB
typedef Texture2D<unsigned char, 3> sibr::Texture2DRGB
Definition at line 611 of file Texture.hpp.
Texture2DRGB32F
typedef Texture2D<float, 3> sibr::Texture2DRGB32F
Definition at line 621 of file Texture.hpp.
Texture2DRGBA
typedef Texture2D<unsigned char, 4> sibr::Texture2DRGBA
Definition at line 612 of file Texture.hpp.
Texture2DRGBA16
typedef Texture2D<unsigned short, 4> sibr::Texture2DRGBA16
Definition at line 615 of file Texture.hpp.
Texture2DRGBA32F
typedef Texture2D<float, 4> sibr::Texture2DRGBA32F
Definition at line 622 of file Texture.hpp.
Texture2DUV16
typedef Texture2D<unsigned short, 2> sibr::Texture2DUV16
Definition at line 617 of file Texture.hpp.
Texture2DUV16s
typedef Texture2D<short, 2> sibr::Texture2DUV16s
Definition at line 619 of file Texture.hpp.
Texture2DUV32F
typedef Texture2D<float, 2> sibr::Texture2DUV32F
Definition at line 623 of file Texture.hpp.
TextureCubeMapLum
typedef TextureCubeMap<unsigned char, 1> sibr::TextureCubeMapLum
Definition at line 653 of file Texture.hpp.
TextureCubeMapLum16
typedef TextureCubeMap<unsigned short, 1> sibr::TextureCubeMapLum16
Definition at line 657 of file Texture.hpp.
TextureCubeMapLum32F
typedef TextureCubeMap<float, 1> sibr::TextureCubeMapLum32F
Definition at line 663 of file Texture.hpp.
TextureCubeMapRGB
typedef TextureCubeMap<unsigned char, 3> sibr::TextureCubeMapRGB
Definition at line 654 of file Texture.hpp.
TextureCubeMapRGB32F
typedef TextureCubeMap<float, 3> sibr::TextureCubeMapRGB32F
Definition at line 664 of file Texture.hpp.
TextureCubeMapRGBA
typedef TextureCubeMap<unsigned char, 4> sibr::TextureCubeMapRGBA
Definition at line 655 of file Texture.hpp.
TextureCubeMapRGBA16
typedef TextureCubeMap<unsigned short, 4> sibr::TextureCubeMapRGBA16
Definition at line 659 of file Texture.hpp.
TextureCubeMapRGBA32F
typedef TextureCubeMap<float, 4> sibr::TextureCubeMapRGBA32F
Definition at line 665 of file Texture.hpp.
TextureCubeMapUV16
typedef TextureCubeMap<unsigned short, 2> sibr::TextureCubeMapUV16
Definition at line 658 of file Texture.hpp.
TextureCubeMapUV16s
typedef TextureCubeMap<short, 2> sibr::TextureCubeMapUV16s
Definition at line 661 of file Texture.hpp.
Transform3f
typedef Transform3<float> sibr::Transform3f
Helper def.
Definition at line 220 of file Transform3.hpp.
UV01
typedef UV<sibr::ZERO_ONE> sibr::UV01
Definition at line 33 of file InterfaceUtils.h.
UV10
typedef UV<sibr::ONE_ZERO> sibr::UV10
Definition at line 34 of file InterfaceUtils.h.
UV11
typedef UV<sibr::MINUS_ONE_ONE> sibr::UV11
Definition at line 32 of file InterfaceUtils.h.
Volume1f
using sibr::Volume1f = typedef VideoVolume<float, 1>
Definition at line 51 of file VideoUtils.hpp.
Volume1u
using sibr::Volume1u = typedef VideoVolume<uchar, 1>
Definition at line 54 of file VideoUtils.hpp.
Volume3f
using sibr::Volume3f = typedef VideoVolume<float, 3>
Definition at line 50 of file VideoUtils.hpp.
Volume3u
using sibr::Volume3u = typedef VideoVolume<uchar, 3>
Definition at line 53 of file VideoUtils.hpp.
Volume4u
using sibr::Volume4u = typedef VideoVolume<uchar, 4>
Definition at line 52 of file VideoUtils.hpp.
Function Documentation
appendVertexData() [1/2]
template<typename TTo , typename TFrom > static void sibr::appendVertexData (std::vector< TTo > & toData, const std::vector< TFrom > & fromData) static
Definition at line 34 of file MeshBufferGL.cpp.
Referenced by sibr::MeshBufferGL::build().
appendVertexData() [2/2]
template<typename TTo , typename TFrom > static void sibr::appendVertexData (std::vector< TTo > & toData, const std::vector< TFrom > & fromData) static
cvConvertMatTo()
template<typename T , uint N> cv::Mat sibr::cvConvertMatTo (cv::Mat mat, double scale = 1.0)
Definition at line 26 of file VideoUtils.hpp.
References cvSplitChannels(), and sibr::Key::N.
cvSplitChannels()
SIBR_VIDEO_EXPORT std::vector< cv::Mat > sibr::cvSplitChannels (cv::Mat mat)
Definition at line 11 of file VideoUtils.cpp.
References split().
Referenced by cvConvertMatTo().
DisplayImageGui()
void sibr::DisplayImageGui (GLuint texture, const sibr::Vector2i & displaySize, const sibr::Vector2f & uv0 = { 0, 0 }, const sibr::Vector2f & uv1 = { 1, 1 })
Display an image using ImGui::image, with additional options.
Parameters
texture the ID of the texture to display
displaySize the target size
uv0 bottom-left corner of the image to display
uv1 top-right corner of the image to display
Definition at line 262 of file GUI.cpp.
Referenced by ImageWithCallback().
gaussianPyramid()
SIBR_VIDEO_EXPORT std::vector<sibr::Volume3u> sibr::gaussianPyramid (const sibr::Volume3u & vid, uint num_levels)
Definition at line 49 of file VideoUtils.cpp.
References sibr::VideoVolume< T, N >::l, and optimal_num_levels().
gaussianPyramidTemporal()
SIBR_VIDEO_EXPORT std::vector<sibr::Volume3u> sibr::gaussianPyramidTemporal (const sibr::Volume3u & vid, uint num_levels)
Definition at line 62 of file VideoUtils.cpp.
References sibr::VideoVolume< T, N >::l, and optimal_num_levels().
getCameraStubIndices()
static const std::vector<uint>& sibr::getCameraStubIndices (void) static
Definition at line 28 of file RenderUtility.cpp.
Referenced by sibr::RenderUtility::createCameraStub().
getCameraStubVertices()
static const std::vector<float>& sibr::getCameraStubVertices (float camStubSize = 0.1f) static
Definition at line 17 of file RenderUtility.cpp.
Referenced by sibr::RenderUtility::createCameraStub().
getVectorDataSize() [1/2]
template<typename T > static uint sibr::getVectorDataSize (const std::vector< T > & v) inline static
Definition at line 51 of file MeshBufferGL.cpp.
References sibr::Key::T.
Referenced by sibr::MeshBufferGL::build().
getVectorDataSize() [2/2]
template<typename T > static uint sibr::getVectorDataSize (const std::vector< T > & v) static
glErrorCallback()
static void sibr::glErrorCallback (GLenum src, GLenum type, GLuint id, GLenum severity, GLsizei size, const GLchar * str, const void * user) static
Definition at line 21 of file Window.cpp.
References SIBR_ERR, and ibr_preprocess_rc_to_sibr::src.
Referenced by sibr::Window::setup().
glfwCursorPosCallback()
static void sibr::glfwCursorPosCallback (GLFWwindow * , double x, double y) static
Definition at line 80 of file Window.cpp.
References sibr::Input::global(), and sibr::Input::mousePosition().
Referenced by sibr::Window::setup().
glfwErrorCallback()
static void sibr::glfwErrorCallback (int error, const char * description) static
Definition at line 16 of file Window.cpp.
References SIBR_ERR.
Referenced by sibr::Window::AutoInitializer::AutoInitializer().
glfwKeyboardCallback()
static void sibr::glfwKeyboardCallback (GLFWwindow * window, int key, int scancode, int action, int mods) static
Definition at line 54 of file Window.cpp.
References sibr::Input::global(), sibr::Input::key(), sibr::InputState< TNbState, TEnum >::press(), and sibr::InputState< TNbState, TEnum >::release().
Referenced by sibr::Window::setup().
glfwMouseButtonCallback()
static void sibr::glfwMouseButtonCallback (GLFWwindow * window, int button, int action, int mods) static
Definition at line 91 of file Window.cpp.
References sibr::Input::global(), sibr::Input::mouseButton(), sibr::InputState< TNbState, TEnum >::press(), and sibr::InputState< TNbState, TEnum >::release().
Referenced by sibr::Window::setup().
glfwMouseScrollCallback()
static void sibr::glfwMouseScrollCallback (GLFWwindow * window, double x, double y) static
Definition at line 110 of file Window.cpp.
References sibr::Input::global(), and sibr::Input::mouseScroll().
Referenced by sibr::Window::setup().
glfwResizeCallback()
static void sibr::glfwResizeCallback (GLFWwindow * window, int w, int h) static
Definition at line 71 of file Window.cpp.
References sibr::Window::viewport().
Referenced by sibr::Window::setup().
ImageWithCallback()
void sibr::ImageWithCallback (GLuint texture, const sibr::Vector2i & displaySize, CallBackData & callbackDataOut, const sibr::Vector2f & uv0 = { 0, 0 }, const sibr::Vector2f & uv1 = { 1, 1 })
Display an image using ImGui::image with support for returning interaction information (did the user click the image, etc.).
Parameters
texture the ID of the texture to display
displaySize the target size
callbackDataOut will contain interaction information for the current frame
uv0 bottom-left corner of the image to display
uv1 top-right corner of the image to display
Definition at line 271 of file GUI.cpp.
References sibr::CallBackData::ctrlPressed, DisplayImageGui(), sibr::CallBackData::isClickedLeft, sibr::CallBackData::isClickedRight, sibr::CallBackData::isHoovered, sibr::CallBackData::isReleasedLeft, sibr::CallBackData::isReleasedRight, sibr::CallBackData::itemPos, sibr::CallBackData::itemSize, sibr::CallBackData::mousePos, sibr::CallBackData::positionRatio, and sibr::CallBackData::scroll.
Referenced by ImageWithZoom(), and sibr::VideoPlayer::onGui().
ImageWithZoom()
SIBR_GRAPHICS_EXPORT void sibr::ImageWithZoom (GLuint texture, const sibr::Vector2i & displaySize, ZoomInterraction & zoom)
Display an image using ImGui::image with support for returning user zoom information.
Parameters
texture the ID of the texture to display
displaySize the target size
zoom will contain zoom information for the current frame
Definition at line 298 of file GUI.cpp.
References sibr::ZoomData::bottomRight(), sibr::ZoomInterraction::callBackData, ImageWithCallback(), sibr::ZoomData::topLeft(), sibr::ZoomInterraction::updateZoom(), and sibr::ZoomInterraction::zoomData.
lin2sRGBF()
float sibr::lin2sRGBF (float inF)
Definition at line 58 of file Utils.cpp.
Referenced by lin2sRGB().
operator&&()
KeyCombination SIBR_GRAPHICS_EXPORT sibr::operator&& (const KeyCombination & combA, const KeyCombination & combB)
Merge two set of pressed keys.
Parameters
combA first set
combB second set
Returns
the union set
Definition at line 57 of file Input.cpp.
References sibr::KeyCombination::isTrue, and sibr::KeyCombination::numKeys.
operator<<()
SIBR_GRAPHICS_EXPORT ByteStream & sibr::operator<< (ByteStream & stream, const Camera & c)
Write a camera to a byte stream.
Parameters
stream the stream to write to
c the camera
Returns
the stream (for chaining).
Definition at line 6 of file Camera.cpp.
References sibr::Camera::aspect(), sibr::Camera::fovy(), sibr::Camera::transform(), sibr::Camera::zfar(), and sibr::Camera::znear().
operator>>()
SIBR_GRAPHICS_EXPORT ByteStream & sibr::operator>> (ByteStream & stream, Camera & c)
Read a camera from a byte stream.
Parameters
stream the stream to read from
c the camera
Returns
the stream (for chaining).
Definition at line 17 of file Camera.cpp.
References sibr::Camera::aspect(), sibr::Camera::fovy(), sibr::Camera::transform(), sibr::Camera::zfar(), and sibr::Camera::znear().
perspective()
Matrix4f sibr::perspective (float fovRadian, float ratio, float zn, float zf, const sibr::Vector2f & p)
Definition at line 6 of file Matrix.cpp.
Referenced by sibr::Camera::proj().
prepareVertexData() [1/2]
template<typename TTo , typename TFrom > static std::vector<TTo> sibr::prepareVertexData (const std::vector< TFrom > & fromData, uint numVertices) static
Definition at line 10 of file MeshBufferGL.cpp.
References SIBR_ASSERT.
prepareVertexData() [2/2]
template<typename TTo , typename TFrom > static std::vector<TTo> sibr::prepareVertexData (const std::vector< TFrom > & fromData, uint numVertices) static
show()
template<typename T_Type , unsigned int T_NumComp> static void sibr::show (const sibr::Texture2DArray< T_Type, T_NumComp > & texArray, sibr::Window * inputWin = nullptr, int w = -1, int h = -1) static
Definition at line 173 of file InterfaceUtils.h.
References sibr::GLShader::begin(), sibr::Viewport::bind(), sibr::Window::close(), sibr::Texture2DArray< T_Type, T_NumComp >::depth(), sibr::Key::End, sibr::GLShader::end(), sibr::Key::Escape, sibr::Input::global(), sibr::InterfaceUtilities::gridGL, sibr::Texture2DArray< T_Type, T_NumComp >::handle(), sibr::InterfaceUtilities::initAllShaders(), sibr::InputState< TNbState, TEnum >::isPressed(), sibr::Input::key(), sibr::Window::makeContextCurrent(), sibr::InterfaceUtilities::multiViewBottomRightGL, sibr::InterfaceUtilities::multiViewShader, sibr::InterfaceUtilities::multiViewTopLeftGL, sibr::InterfaceUtilities::numImgsGL, sibr::Input::poll(), sibr::RenderUtility::renderScreenQuad(), sibr::GLParameter::set(), sibr::Window::size(), slice(), sibr::Window::swapBuffer(), and sibr::Window::viewport().
sRGB2LinF()
float sibr::sRGB2LinF (float inF)
Definition at line 49 of file Utils.cpp.
Referenced by sRGB2Lin().
strRemoveSpaces()
static std::string sibr::strRemoveSpaces (const std::string & str) static
Definition at line 255 of file Shader.cpp.
Referenced by loadFile().
toColorFloat()
Vector3f sibr::toColorFloat (Vector3ub & colorUB)
Definition at line 8 of file Vector.cpp.
toColorUB()
Vector3ub sibr::toColorUB (Vector3f & colorFloat)
Definition at line 12 of file Vector.cpp.
Variable Documentation
windowCounter
int sibr::windowCounter = 0 static
Definition at line 117 of file Window.cpp.
Referenced by sibr::Window::AutoInitializer::AutoInitializer(), sibr::Window::contextIsRunning(), and sibr::Window::AutoInitializer::~AutoInitializer().