SIBR: convert Namespace Reference
convert Namespace Reference
Functions
def updateStringFromDict (string, map, format='${%s}', fix_paths=True)
def fixMeshEol (meshPath, newMeshPath)
Function Documentation
fixMeshEol()
def convert.fixMeshEol (meshPath, newMeshPath)
Definition at line 18 of file convert.py.
References ibr_preprocess_rc_to_sibr.replace().
updateStringFromDict()
def convert.updateStringFromDict (string, map, format = '${%s}', fix_paths = True)
Definition at line 7 of file convert.py.
Referenced by TaskPipeline.TaskPipeline.isExpressionValid(), and TaskPipeline.TaskPipeline.runProcessSteps().