SIBR: get_image_size Namespace Reference
get_image_size Namespace Reference
Classes
class Image
class Test_get_image_size
class UnknownImageFormat
Functions
def get_image_size (file_path)
def get_image_metadata (file_path)
def main (argv=None)
Variables
string FILE_UNKNOWN = "Sorry, don't know how to get size for this file."
types = collections.OrderedDict()
string BMP = 'BMP'
string GIF = 'GIF'
string ICO = 'ICO'
string JPEG = 'JPEG'
string PNG = 'PNG'
string TIFF = 'TIFF'
list image_fields = ['path', 'type', 'file_size', 'width', 'height']
Function Documentation
get_image_metadata()
def get_image_size.get_image_metadata (file_path)
Return an `Image` object for a given img file content - no external
dependencies except the os and struct builtin modules
Args:
    file_path (str): path to an image file
Returns:
    Image: (path, type, file_size, width, height)
Definition at line 75 of file get_image_size.py.
Referenced by get_image_size(), get_image_size.Test_get_image_size.test_get_image_metadata__ENOENT_OSError(), and get_image_size.Test_get_image_size.test_get_image_metadata__not_an_image_UnknownImageFormat().
get_image_size()
def get_image_size.get_image_size (file_path)
Return (width, height) for a given img file content - no external
dependencies except the os and struct builtin modules
Definition at line 66 of file get_image_size.py.
References get_image_metadata().
main()
def get_image_size.main (argv = None)
Print image metadata fields for the given file path.
Keyword Arguments:
    argv (list): commandline arguments (e.g. sys.argv[1:])
Returns:
    int: zero for OK
Definition at line 293 of file get_image_size.py.
Variable Documentation
BMP
string get_image_size.BMP = 'BMP'
Definition at line 32 of file get_image_size.py.
Referenced by sibr::IImage.imageResolution().
FILE_UNKNOWN
string get_image_size.FILE_UNKNOWN = "Sorry, don't know how to get size for this file."
Definition at line 24 of file get_image_size.py.
GIF
string get_image_size.GIF = 'GIF'
Definition at line 33 of file get_image_size.py.
ICO
string get_image_size.ICO = 'ICO'
Definition at line 34 of file get_image_size.py.
image_fields
list get_image_size.image_fields = ['path', 'type', 'file_size', 'width', 'height']
Definition at line 39 of file get_image_size.py.
JPEG
string get_image_size.JPEG = 'JPEG'
Definition at line 35 of file get_image_size.py.
Referenced by sibr::IImage.imageResolution().
PNG
string get_image_size.PNG = 'PNG'
Definition at line 36 of file get_image_size.py.
Referenced by sibr::IImage.imageResolution().
TIFF
string get_image_size.TIFF = 'TIFF'
Definition at line 37 of file get_image_size.py.
types
get_image_size.types = collections.OrderedDict()
Definition at line 31 of file get_image_size.py.