SIBR: commands Namespace Reference
commands Namespace Reference
Functions
def getProcess (programName, binaryPath=getBinariesPath())
def runCommand (binary, command_args)
def getColmap (colmapPath=getColmapPath())
Function Documentation
getColmap()
def commands.getColmap (colmapPath = getColmapPath())
Definition at line 32 of file commands.py.
Referenced by fullColmapProcess.main().
getProcess()
def commands.getProcess (programName, binaryPath = getBinariesPath())
Definition at line 8 of file commands.py.
Referenced by colmap2sibr.main(), fullColmapProcess.main(), and textureOnly.main().
runCommand()
def commands.runCommand (binary, command_args)
Definition at line 18 of file commands.py.
Referenced by wedge_to_vertex_uvs.convertUVs(), TaskPipeline.TaskPipeline.runProcessSteps(), and simplify_mesh.simplifyMesh().