SIBR: ibr_convert_old_to_new Namespace Reference
ibr_convert_old_to_new Namespace Reference
Functions
def get_image_size (fname)
def checkOutput (output, force_continue)
def main (argv, path_dest)
Variables
string path_dest = ""
path_data = os.path.abspath(os.path.join(os.path.dirname(__file__), "../datasets"))
executables_suffix
executables_folder
path_in_imgs = path_data
string file_nameList = path_data + "images/list_images.txt";
string scene_metadata = "Scene Metadata File\n\n"
path_list_images = os.path.join(path_in_imgs, "list_images.txt")
list list_images = []
list_image_file = open(path_list_images, "r")
path_clipping_planes = os.path.join(path_data, "clipping_planes.txt")
list clipping_planes = []
clipping_planes_file = open(path_clipping_planes, "r")
line = line.strip('\n')
list folder_to_create = ["images","cameras","meshes","textures"]
path_scene_metadata = os.path.join(path_dest, "scene_metadata.txt")
scene_metadata_file = open(path_scene_metadata, "w")
Function Documentation
checkOutput()
def ibr_convert_old_to_new.checkOutput (output, force_continue)
Definition at line 68 of file ibr_convert_old_to_new.py.
get_image_size()
def ibr_convert_old_to_new.get_image_size (fname)
Determine the image type of fhandle and return its size.
from draco
Definition at line 33 of file ibr_convert_old_to_new.py.
main()
def ibr_convert_old_to_new.main (argv, path_dest)
Definition at line 83 of file ibr_convert_old_to_new.py.
References paths.getBinariesPath().
Variable Documentation
clipping_planes
list ibr_convert_old_to_new.clipping_planes = []
Definition at line 146 of file ibr_convert_old_to_new.py.
clipping_planes_file
ibr_convert_old_to_new.clipping_planes_file = open(path_clipping_planes, "r")
Definition at line 149 of file ibr_convert_old_to_new.py.
executables_folder
ibr_convert_old_to_new.executables_folder
Definition at line 105 of file ibr_convert_old_to_new.py.
executables_suffix
ibr_convert_old_to_new.executables_suffix
Definition at line 105 of file ibr_convert_old_to_new.py.
file_nameList
string ibr_convert_old_to_new.file_nameList = path_data + "images/list_images.txt";
Definition at line 123 of file ibr_convert_old_to_new.py.
folder_to_create
list ibr_convert_old_to_new.folder_to_create = ["images","cameras","meshes","textures"]
Definition at line 161 of file ibr_convert_old_to_new.py.
line
ibr_convert_old_to_new.line = line.strip('\n')
Definition at line 152 of file ibr_convert_old_to_new.py.
Referenced by sibr::VideoUtils.computeSaveSimpleFlow(), sibr::Mesh.fromOffStream(), sibr::VideoUtils.getMedian(), sibr::ParseData.getParsedColmapData(), sibr::CropScaleImageUtility.getPathToImgs(), sibr::InterfaceUtilities.linePixels(), sibr::DrawUtilities.linePixels(), sibr::InputCamera.loadBundle(), sibr::CameraRecorder.loadBundle(), sibr::InputCamera.loadBundleFRIBR(), sibr::InputCamera.loadColmap(), sibr.loadFile(), sibr::InputCamera.loadLookat(), main(), sibr::TrackBall.mapTo3Dplane(), sibr::ParseData.parseBundlerFile(), sibr::ParseData.parseSceneMetadata(), sibr::RaycastingCamera.rayProjection(), sibr::Resources.Resources(), and sibr::VideoUtils.rotationAngleFromMetadata().
list_image_file
ibr_convert_old_to_new.list_image_file = open(path_list_images, "r")
Definition at line 137 of file ibr_convert_old_to_new.py.
list_images
list ibr_convert_old_to_new.list_images = []
Definition at line 133 of file ibr_convert_old_to_new.py.
Referenced by sibr::InputCamera.loadBundle().
path_clipping_planes
ibr_convert_old_to_new.path_clipping_planes = os.path.join(path_data, "clipping_planes.txt")
Definition at line 145 of file ibr_convert_old_to_new.py.
path_data
string ibr_convert_old_to_new.path_data = os.path.abspath(os.path.join(os.path.dirname(__file__), "../datasets"))
Definition at line 105 of file ibr_convert_old_to_new.py.
path_dest
string ibr_convert_old_to_new.path_dest = ""
Definition at line 104 of file ibr_convert_old_to_new.py.
path_in_imgs
ibr_convert_old_to_new.path_in_imgs = path_data
Definition at line 116 of file ibr_convert_old_to_new.py.
path_list_images
ibr_convert_old_to_new.path_list_images = os.path.join(path_in_imgs, "list_images.txt")
Definition at line 132 of file ibr_convert_old_to_new.py.
path_scene_metadata
ibr_convert_old_to_new.path_scene_metadata = os.path.join(path_dest, "scene_metadata.txt")
Definition at line 198 of file ibr_convert_old_to_new.py.
scene_metadata
string ibr_convert_old_to_new.scene_metadata = "Scene Metadata File\n\n"
Definition at line 129 of file ibr_convert_old_to_new.py.
Referenced by sibr::ParseData.parseSceneMetadata().
scene_metadata_file
ibr_convert_old_to_new.scene_metadata_file = open(path_scene_metadata, "w")
Definition at line 200 of file ibr_convert_old_to_new.py.