SIBR: ibr_preprocess_rc_to_sibr Namespace Reference
ibr_preprocess_rc_to_sibr Namespace Reference
Functions
def get_image_size (fname)
def replace (file_path, pattern, subst)
def checkOutput (output, force_continue)
def get_textured_mesh_base_name (source_folder)
def get_scale_factor (current_res, target_res)
def main (argv, path_dest)
Variables
string path_dest = ""
path_data = os.path.abspath(os.path.join(os.path.dirname(__file__), "../datasets"))
executables_suffix
executables_folder = os.path.abspath(executables_folder + "/") + "/"
path_in_imgs = path_data
string path_out_imgs = path_dest + "images/"
string raw_data = "raw/"
string cameras_dir = "cameras/"
string images_dir = "images/"
string pmvs_model_dir = "meshes/"
list dirs_to_create = [ raw_data, cameras_dir, images_dir, pmvs_model_dir]
path_to_dir = os.path.join(path_dest, dir_to_create)
int width_limit = 2500
GLOBALS ######################################.
bool create_temp_folders = False
input_bundle = bundle.Bundle(path_data + "bundle.out")
crop_app = getProcess("distordCrop" + executables_suffix, executables_folder)
RUN DISTORDCROP ################################## by calling distordCrop (preprocess/distordCrop), input images that have a resolution completely different from the average or that have too much black border added by RealityCapture will be listed in a exclude_images.txt file.
avg_resolution = input_bundle.get_avg_resolution()
resolutions_txt_path = os.path.join(path_data, "resolutions.txt")
p_exit = subprocess.call([crop_app, "--path", path_data, "--ratio", "0.3", "--avg_width", str(avg_resolution[0]), "--avg_height", str(avg_resolution[1]) ])
list exclude = []
path_to_exclude_images_txt = os.path.join(path_data, "exclude_images.txt")
exclusion_file = open(path_to_exclude_images_txt, "r")
line = exclusion_file.readline()
tokens = line.split()
path_to_crop_new_size_txt = os.path.join(path_data, "cropNewSize.txt")
new_width = int(tokens[0])
new_height = int(tokens[1])
list proposed_res = [new_width, new_height]
target_res = None
TRANSFORM IMAGES TO TARGET RESOLUTION #################### we need to crop images to the previous proposed resolution (crop applied from the center).
tuple half_width = (int)(proposed_res[0] * 0.5)
tuple half_height = (int)(proposed_res[0] * 0.5)
crop_from_center_app = getProcess("cropFromCenter" + executables_suffix, executables_folder)
path_to_transform_list_txt = os.path.join (path_data, "toTransform.txt")
list crop_from_center_args
def scale_factor = get_scale_factor(proposed_res, target_res)
path_to_output_bundle = os.path.join (path_dest, cameras_dir, "bundle.out")
path_to_scaled_down_output_bundle = os.path.join (os.path.join (path_dest, "images/scaled"), "bundle.out")
def textured_mesh_base_name = get_textured_mesh_base_name(path_data)
MOVE REST OF ASSETS ###############################.
list files_to_move
source_file = os.path.join (path_data, filename)
destination_file = os.path.join (os.path.join (path_dest, directory_name), filename)
clipping_planes_app = getProcess("clippingPlanes" + executables_suffix, executables_folder)
CALCULATE CLIPPING PLANES ############################# clippingPlanes executable.
list clipping_planes_args = [clipping_planes_app, path_dest]
path_images = os.path.join(path_dest, images_dir)
CREATE LIST IMAGES ##################################.
path_list_images = os.path.join(path_images, "list_images.txt")
list list_images = []
CREATE SCENE METADATA #################################.
list_image_file = open(path_list_images, "r")
path_clipping_planes = os.path.join(path_dest, "clipping_planes.txt")
list clipping_planes = []
clipping_planes_file = open(path_clipping_planes, "r")
string scene_metadata = "Scene Metadata File\n\n"
list new_list = [a[:-1] + " " + b for a, b in zip(list_images, clipping_planes)]
path_scene_metadata = os.path.join(path_dest, "scene_metadata.txt")
scene_metadata_file = open(path_scene_metadata, "w")
src = os.path.join(path_data, filename)
dst = os.path.join(path_dest, raw_data)
Function Documentation
checkOutput()
def ibr_preprocess_rc_to_sibr.checkOutput (output, force_continue)
Check if an external process succeeded and if we should abort if something went wrong
Args:
    output          (int): output of some external launched process (0=fine, 1 or greater=error)
    force_continue  (bool): should we continue anyway?
Returns:
    bool: True if last process succeeded
Definition at line 95 of file ibr_preprocess_rc_to_sibr.py.
get_image_size()
def ibr_preprocess_rc_to_sibr.get_image_size (fname)
Determine the image type of fhandle and return its size.
from draco
Definition at line 44 of file ibr_preprocess_rc_to_sibr.py.
get_scale_factor()
def ibr_preprocess_rc_to_sibr.get_scale_factor (current_res, target_res)
Return the scale factor needed to go from current_res to target_res.
The value is calculated based on the idea that we don't want to crop the input dataset anymore
and that we prefer to add black borders in order to reach the target resolution
Args:
    current_res (vec2): current dataset resolution
    target_res  (vec2): target dataset resolution
Returns:
    float: scale factor
Definition at line 129 of file ibr_preprocess_rc_to_sibr.py.
get_textured_mesh_base_name()
def ibr_preprocess_rc_to_sibr.get_textured_mesh_base_name (source_folder)
Return the base name of a textured mesh obtained with RealityCapture
Args:
    source_folder (str): path to dataset (bundle file, textured and images)
Returns:
    str: base name of <base name>.obj, <base name>.mtl and <base name>_u1_v1.png
Definition at line 113 of file ibr_preprocess_rc_to_sibr.py.
main()
def ibr_preprocess_rc_to_sibr.main (argv, path_dest)
Definition at line 177 of file ibr_preprocess_rc_to_sibr.py.
References paths.getBinariesPath().
replace()
def ibr_preprocess_rc_to_sibr.replace (file_path, pattern, subst)
Definition at line 82 of file ibr_preprocess_rc_to_sibr.py.
Referenced by convert.fixMeshEol(), sibr::Resources.Resources(), get_image_size.Image.to_str_row(), and get_image_size.Image.to_str_row_verbose().
Variable Documentation
avg_resolution
ibr_preprocess_rc_to_sibr.avg_resolution = input_bundle.get_avg_resolution()
Definition at line 258 of file ibr_preprocess_rc_to_sibr.py.
cameras_dir
string ibr_preprocess_rc_to_sibr.cameras_dir = "cameras/"
Definition at line 224 of file ibr_preprocess_rc_to_sibr.py.
clipping_planes
list ibr_preprocess_rc_to_sibr.clipping_planes = []
Definition at line 415 of file ibr_preprocess_rc_to_sibr.py.
clipping_planes_app
ibr_preprocess_rc_to_sibr.clipping_planes_app = getProcess("clippingPlanes" + executables_suffix, executables_folder)
CALCULATE CLIPPING PLANES ############################# clippingPlanes executable.
Definition at line 381 of file ibr_preprocess_rc_to_sibr.py.
clipping_planes_args
list ibr_preprocess_rc_to_sibr.clipping_planes_args = [clipping_planes_app, path_dest]
Definition at line 383 of file ibr_preprocess_rc_to_sibr.py.
clipping_planes_file
ibr_preprocess_rc_to_sibr.clipping_planes_file = open(path_clipping_planes, "r")
Definition at line 418 of file ibr_preprocess_rc_to_sibr.py.
create_temp_folders
bool ibr_preprocess_rc_to_sibr.create_temp_folders = False
Definition at line 239 of file ibr_preprocess_rc_to_sibr.py.
crop_app
ibr_preprocess_rc_to_sibr.crop_app = getProcess("distordCrop" + executables_suffix, executables_folder)
RUN DISTORDCROP ################################## by calling distordCrop (preprocess/distordCrop), input images that have a resolution completely different from the average or that have too much black border added by RealityCapture will be listed in a exclude_images.txt file.
A new proposed resolution will be also output in a file called cropNewSize.txt In order to accelerate this process and avoid loading the images multiple times, make sure that average resolution was already calculated and there is file called resolutions.txt in the dataset source folder containing the current resolution of each image.
Definition at line 255 of file ibr_preprocess_rc_to_sibr.py.
crop_from_center_app
ibr_preprocess_rc_to_sibr.crop_from_center_app = getProcess("cropFromCenter" + executables_suffix, executables_folder)
Definition at line 314 of file ibr_preprocess_rc_to_sibr.py.
crop_from_center_args
list ibr_preprocess_rc_to_sibr.crop_from_center_args
Initial value:
 =  [crop_from_center_app,
     "--inputFile", path_to_transform_list_txt,
     "--outputPath", path_out_imgs,
     "--avgResolution", str(avg_resolution[0]), str(avg_resolution[1]),
     "--cropResolution", str(proposed_res[0]), str(proposed_res[1])
 ]
Definition at line 320 of file ibr_preprocess_rc_to_sibr.py.
destination_file
ibr_preprocess_rc_to_sibr.destination_file = os.path.join (os.path.join (path_dest, directory_name), filename)
Definition at line 369 of file ibr_preprocess_rc_to_sibr.py.
dirs_to_create
list ibr_preprocess_rc_to_sibr.dirs_to_create = [ raw_data, cameras_dir, images_dir, pmvs_model_dir]
Definition at line 228 of file ibr_preprocess_rc_to_sibr.py.
dst
ibr_preprocess_rc_to_sibr.dst = os.path.join(path_dest, raw_data)
Definition at line 461 of file ibr_preprocess_rc_to_sibr.py.
Referenced by sibr.blit(), sibr.blit_and_flip(), sibr.blitToColorAttachment(), sibr.copyDirectory(), sibr.copyFile(), main(), sibr::ImagesGrid.onRender(), sibr::MultiMeshManager.onRender(), sibr::ULRV2View.onRenderIBR(), sibr::ULRView.onRenderIBR(), sibr::TexturedMeshView.onRenderIBR(), sibr::ULRV3View.onRenderIBR(), sibr::BinaryMeshRenderer.process(), sibr::TexturedMeshRenderer.process(), sibr::PoissonRenderer.process(), sibr::ULRV3Renderer.process(), sibr::ULRV2Renderer.process(), sibr::ULRRenderer.process(), sibr::AddShadowRenderer.process(), sibr::BlurRenderer.process(), sibr::CopyRenderer.process(), sibr.quatFromEulerAngles(), sibr::ULRV3Renderer.renderBlending(), and sibr::Image< T_Type, T_NumComp >.resized().
exclude
list ibr_preprocess_rc_to_sibr.exclude = []
Definition at line 270 of file ibr_preprocess_rc_to_sibr.py.
exclusion_file
ibr_preprocess_rc_to_sibr.exclusion_file = open(path_to_exclude_images_txt, "r")
Definition at line 274 of file ibr_preprocess_rc_to_sibr.py.
executables_folder
string ibr_preprocess_rc_to_sibr.executables_folder = os.path.abspath(executables_folder + "/") + "/"
Definition at line 202 of file ibr_preprocess_rc_to_sibr.py.
executables_suffix
ibr_preprocess_rc_to_sibr.executables_suffix
Definition at line 202 of file ibr_preprocess_rc_to_sibr.py.
files_to_move
list ibr_preprocess_rc_to_sibr.files_to_move
Initial value:
 =  [   #['pmvs/models/pmvs_recon.ply',''],
                     ['pmvs_recon.ply', pmvs_model_dir],
                     ['mesh.ply', pmvs_model_dir],
                     ['recon.ply', pmvs_model_dir],
                     ['rc_out.csv', path_dest],
                     [textured_mesh_base_name + ".obj", pmvs_model_dir],
                     [textured_mesh_base_name + ".mtl", pmvs_model_dir],
                     [textured_mesh_base_name + "_u1_v1.png", pmvs_model_dir] ]
Definition at line 359 of file ibr_preprocess_rc_to_sibr.py.
half_height
tuple ibr_preprocess_rc_to_sibr.half_height = (int)(proposed_res[0] * 0.5)
Definition at line 310 of file ibr_preprocess_rc_to_sibr.py.
half_width
tuple ibr_preprocess_rc_to_sibr.half_width = (int)(proposed_res[0] * 0.5)
Definition at line 309 of file ibr_preprocess_rc_to_sibr.py.
images_dir
string ibr_preprocess_rc_to_sibr.images_dir = "images/"
Definition at line 225 of file ibr_preprocess_rc_to_sibr.py.
input_bundle
ibr_preprocess_rc_to_sibr.input_bundle = bundle.Bundle(path_data + "bundle.out")
Definition at line 241 of file ibr_preprocess_rc_to_sibr.py.
line
ibr_preprocess_rc_to_sibr.line = exclusion_file.readline()
Definition at line 275 of file ibr_preprocess_rc_to_sibr.py.
list_image_file
ibr_preprocess_rc_to_sibr.list_image_file = open(path_list_images, "r")
Definition at line 406 of file ibr_preprocess_rc_to_sibr.py.
list_images
list ibr_preprocess_rc_to_sibr.list_images = []
CREATE SCENE METADATA #################################.
Definition at line 403 of file ibr_preprocess_rc_to_sibr.py.
new_height
ibr_preprocess_rc_to_sibr.new_height = int(tokens[1])
Definition at line 291 of file ibr_preprocess_rc_to_sibr.py.
new_list
list ibr_preprocess_rc_to_sibr.new_list = [a[:-1] + " " + b for a, b in zip(list_images, clipping_planes)]
Definition at line 431 of file ibr_preprocess_rc_to_sibr.py.
new_width
ibr_preprocess_rc_to_sibr.new_width = int(tokens[0])
Definition at line 290 of file ibr_preprocess_rc_to_sibr.py.
p_exit
ibr_preprocess_rc_to_sibr.p_exit = subprocess.call([crop_app, "--path", path_data, "--ratio", "0.3", "--avg_width", str(avg_resolution[0]), "--avg_height", str(avg_resolution[1]) ])
Definition at line 265 of file ibr_preprocess_rc_to_sibr.py.
path_clipping_planes
ibr_preprocess_rc_to_sibr.path_clipping_planes = os.path.join(path_dest, "clipping_planes.txt")
Definition at line 414 of file ibr_preprocess_rc_to_sibr.py.
path_data
string ibr_preprocess_rc_to_sibr.path_data = os.path.abspath(os.path.join(os.path.dirname(__file__), "../datasets"))
Definition at line 202 of file ibr_preprocess_rc_to_sibr.py.
path_dest
string ibr_preprocess_rc_to_sibr.path_dest = ""
Definition at line 201 of file ibr_preprocess_rc_to_sibr.py.
path_images
ibr_preprocess_rc_to_sibr.path_images = os.path.join(path_dest, images_dir)
CREATE LIST IMAGES ##################################.
Definition at line 394 of file ibr_preprocess_rc_to_sibr.py.
path_in_imgs
ibr_preprocess_rc_to_sibr.path_in_imgs = path_data
Definition at line 214 of file ibr_preprocess_rc_to_sibr.py.
path_list_images
ibr_preprocess_rc_to_sibr.path_list_images = os.path.join(path_images, "list_images.txt")
Definition at line 395 of file ibr_preprocess_rc_to_sibr.py.
path_out_imgs
string ibr_preprocess_rc_to_sibr.path_out_imgs = path_dest + "images/"
Definition at line 215 of file ibr_preprocess_rc_to_sibr.py.
path_scene_metadata
ibr_preprocess_rc_to_sibr.path_scene_metadata = os.path.join(path_dest, "scene_metadata.txt")
Definition at line 451 of file ibr_preprocess_rc_to_sibr.py.
path_to_crop_new_size_txt
ibr_preprocess_rc_to_sibr.path_to_crop_new_size_txt = os.path.join(path_data, "cropNewSize.txt")
Definition at line 286 of file ibr_preprocess_rc_to_sibr.py.
path_to_dir
ibr_preprocess_rc_to_sibr.path_to_dir = os.path.join(path_dest, dir_to_create)
Definition at line 231 of file ibr_preprocess_rc_to_sibr.py.
path_to_exclude_images_txt
ibr_preprocess_rc_to_sibr.path_to_exclude_images_txt = os.path.join(path_data, "exclude_images.txt")
Definition at line 271 of file ibr_preprocess_rc_to_sibr.py.
path_to_output_bundle
ibr_preprocess_rc_to_sibr.path_to_output_bundle = os.path.join (path_dest, cameras_dir, "bundle.out")
Definition at line 342 of file ibr_preprocess_rc_to_sibr.py.
path_to_scaled_down_output_bundle
ibr_preprocess_rc_to_sibr.path_to_scaled_down_output_bundle = os.path.join (os.path.join (path_dest, "images/scaled"), "bundle.out")
Definition at line 349 of file ibr_preprocess_rc_to_sibr.py.
path_to_transform_list_txt
ibr_preprocess_rc_to_sibr.path_to_transform_list_txt = os.path.join (path_data, "toTransform.txt")
Definition at line 317 of file ibr_preprocess_rc_to_sibr.py.
pmvs_model_dir
string ibr_preprocess_rc_to_sibr.pmvs_model_dir = "meshes/"
Definition at line 226 of file ibr_preprocess_rc_to_sibr.py.
proposed_res
list ibr_preprocess_rc_to_sibr.proposed_res = [new_width, new_height]
Definition at line 292 of file ibr_preprocess_rc_to_sibr.py.
raw_data
string ibr_preprocess_rc_to_sibr.raw_data = "raw/"
Definition at line 223 of file ibr_preprocess_rc_to_sibr.py.
resolutions_txt_path
ibr_preprocess_rc_to_sibr.resolutions_txt_path = os.path.join(path_data, "resolutions.txt")
Definition at line 261 of file ibr_preprocess_rc_to_sibr.py.
scale_factor
def ibr_preprocess_rc_to_sibr.scale_factor = get_scale_factor(proposed_res, target_res)
Definition at line 330 of file ibr_preprocess_rc_to_sibr.py.
scene_metadata
string ibr_preprocess_rc_to_sibr.scene_metadata = "Scene Metadata File\n\n"
Definition at line 427 of file ibr_preprocess_rc_to_sibr.py.
scene_metadata_file
ibr_preprocess_rc_to_sibr.scene_metadata_file = open(path_scene_metadata, "w")
Definition at line 453 of file ibr_preprocess_rc_to_sibr.py.
source_file
ibr_preprocess_rc_to_sibr.source_file = os.path.join (path_data, filename)
Definition at line 368 of file ibr_preprocess_rc_to_sibr.py.
src
ibr_preprocess_rc_to_sibr.src = os.path.join(path_data, filename)
Definition at line 460 of file ibr_preprocess_rc_to_sibr.py.
Referenced by sibr.blit(), sibr.blit_and_flip(), sibr.blitToColorAttachment(), sibr::PoissonReconstruction.computeGradients(), sibr.copyDirectory(), sibr.copyFile(), sibr.glErrorCallback(), main(), sibr::PoissonRenderer.process(), and sibr.strSearchAndReplace().
target_res
list ibr_preprocess_rc_to_sibr.target_res = None
TRANSFORM IMAGES TO TARGET RESOLUTION #################### we need to crop images to the previous proposed resolution (crop applied from the center).
if a target resolution was passed as parameter, we also need to scale down the images and pad them with black borders in order to end up with the exact target resolution. Before padding the images, we need to have available the temporary result of the dataset scaled down in order to potentially call harmonize (which doesn't work with images that were padded with black borders). Scaled down dataset will be stored inside <destination_folder>/scaledDown and we will store the scale down factor in a scale_factor.txt file
Definition at line 307 of file ibr_preprocess_rc_to_sibr.py.
textured_mesh_base_name
def ibr_preprocess_rc_to_sibr.textured_mesh_base_name = get_textured_mesh_base_name(path_data)
MOVE REST OF ASSETS ###############################.
Definition at line 356 of file ibr_preprocess_rc_to_sibr.py.
tokens
ibr_preprocess_rc_to_sibr.tokens = line.split()
Definition at line 276 of file ibr_preprocess_rc_to_sibr.py.
Referenced by sibr::InputCamera.loadColmap().
width_limit
int ibr_preprocess_rc_to_sibr.width_limit = 2500
GLOBALS ######################################.
Definition at line 238 of file ibr_preprocess_rc_to_sibr.py.