SIBR: sibr::ZoomInterraction Struct Reference
sibr::ZoomInterraction Struct Reference
Store user interaction and zooming information to be returned when displaying an image.
#include <GUI.hpp>
Public Member Functions
void updateZoom (const sibr::Vector2f &canvasSize)
Update zoom information.
Public Attributes
CallBackData callBackData
Interaction data.
ZoomData zoomData
Zoom data.
Detailed Description
Store user interaction and zooming information to be returned when displaying an image.
Definition at line 149 of file GUI.hpp.
Member Function Documentation
updateZoom()
void sibr::ZoomInterraction::updateZoom (const sibr::Vector2f & canvasSize)
Update zoom information.
Parameters
canvasSize size ot the displayed region of the image
Definition at line 154 of file GUI.cpp.
References sibr::ZoomData::bottomRight(), callBackData, sibr::ZoomData::center, sibr::ZoomData::diagonal, sibr::ZoomData::firstClickPixel, sibr::ZoomData::scaled(), sibr::ZoomData::secondClickPixel, sibr::ZoomData::tmpBottonRight, sibr::ZoomData::tmpTopLeft, sibr::ZoomData::topLeft(), sibr::ZoomData::underMofidication, sibr::ZoomData::uvFromBoxPos(), and zoomData.
Referenced by sibr::ImageWithZoom(), and sibr::VideoPlayer::onGui().
Member Data Documentation
callBackData
CallBackData sibr::ZoomInterraction::callBackData
Interaction data.
Definition at line 155 of file GUI.hpp.
Referenced by sibr::ImageWithZoom(), sibr::VideoPlayer::onGui(), and updateZoom().
zoomData
ZoomData sibr::ZoomInterraction::zoomData
Zoom data.
Definition at line 156 of file GUI.hpp.
Referenced by sibr::ImageWithZoom(), sibr::VideoPlayer::onGui(), and updateZoom().
The documentation for this struct was generated from the following files:
src/core/graphics/GUI.hpp
src/core/graphics/GUI.cpp