SIBR: CameraConverterArgs Struct Reference
CameraConverterArgs Struct Reference
Public Attributes
RequiredArg< std::string > input = { "input", "input camera file" }
RequiredArg< std::string > output = { "output", "output camera file" }
Arg< std::string > transfo = { "transfo", "", "matrix file" }
Arg< sibr::Vector2u > inputRes = {"ires", {1920, 1080}, "input camera resolution (not required for all formats)"}
Arg< sibr::Vector2u > outputRes = { "ores", {1920, 1080}, "output camera resolution (not required for all formats)" }
Arg< bool > inverse = {"inverse", "reverse the transformation"}
Arg< bool > bundleImageList = { "images_list", "for a bundle output, output list_images.txt" }
Arg< bool > bundleImageFiles = { "images_files", "for a bundle output, output empty images in a 'visualize' subdirectory" }
Arg< std::string > inImageFilePath = { "in_images_files", "", "for a bundle input images file directory (for list_images etc)" }
Public Attributes inherited from sibr::AppArgs
std::string appName
std::string appPath
Arg< std::string > custom_app_path = { "appPath", "./", "define a custom app path" }
Arg< bool > showHelp = {"help", "display this help message"}
Arg< bool > noExit = {"noExit", "dont exit after rendering path "}
Arg< std::string > pathFile = { "pathFile", "", "filename of path to render offline; app renders path and exits" }
Arg< std::string > outPath = { "outPath", "pathOutput", "Path of directory to store path output default relative the input path directory " }
Additional Inherited Members
Public Member Functions inherited from sibr::AppArgs
AppArgs ()
Constructor.
void displayHelpIfRequired () const
Helper to print the help message if the help argument was passed.
Detailed Description
Definition at line 7 of file main.cpp.
Member Data Documentation
bundleImageFiles
Arg<bool> CameraConverterArgs::bundleImageFiles = { "images_files", "for a bundle output, output empty images in a 'visualize' subdirectory" }
Definition at line 15 of file main.cpp.
Referenced by main().
bundleImageList
Arg<bool> CameraConverterArgs::bundleImageList = { "images_list", "for a bundle output, output list_images.txt" }
Definition at line 14 of file main.cpp.
Referenced by main().
inImageFilePath
Arg<std::string> CameraConverterArgs::inImageFilePath = { "in_images_files", "", "for a bundle input images file directory (for list_images etc)" }
Definition at line 16 of file main.cpp.
Referenced by main().
input
RequiredArg<std::string> CameraConverterArgs::input = { "input", "input camera file" }
Definition at line 8 of file main.cpp.
Referenced by main().
inputRes
Arg<sibr::Vector2u> CameraConverterArgs::inputRes = {"ires", {1920, 1080}, "input camera resolution (not required for all formats)"}
Definition at line 11 of file main.cpp.
Referenced by main().
inverse
Arg<bool> CameraConverterArgs::inverse = {"inverse", "reverse the transformation"}
Definition at line 13 of file main.cpp.
Referenced by main().
output
RequiredArg<std::string> CameraConverterArgs::output = { "output", "output camera file" }
Definition at line 9 of file main.cpp.
Referenced by main().
outputRes
Arg<sibr::Vector2u> CameraConverterArgs::outputRes = { "ores", {1920, 1080}, "output camera resolution (not required for all formats)" }
Definition at line 12 of file main.cpp.
Referenced by main().
transfo
Arg<std::string> CameraConverterArgs::transfo = { "transfo", "", "matrix file" }
Definition at line 10 of file main.cpp.
Referenced by main().
The documentation for this struct was generated from the following file:
src/projects/dataset_tools/preprocess/cameraConverter/main.cpp