SIBR: sibr::ZoomData Struct Reference
sibr::ZoomData Struct Reference
Store additional user zoom information to be returned when displaying an image.
#include <GUI.hpp>
Public Member Functions
sibr::Vector2f topLeft () const
sibr::Vector2f bottomRight () const
sibr::Vector2f uvFromBoxPos (const sibr::Vector2f &pos) const
Convert pixel coordinates in UV, taking the zoom into account.
ZoomData scaled (const sibr::Vector2f &size) const
Rescale zoom data using a reference region size.
Public Attributes
sibr::Vector2f center = sibr::Vector2f(0.5f, 0.5f)
sibr::Vector2f diagonal = sibr::Vector2f(0.5f, 0.5f)
sibr::Vector2f tmpTopLeft
sibr::Vector2f tmpBottonRight
sibr::Vector2f firstClickPixel
sibr::Vector2f secondClickPixel
Zoomed region corners and location.
bool underMofidication = false
Is the user currently zooming.
Detailed Description
Store additional user zoom information to be returned when displaying an image.
Definition at line 123 of file GUI.hpp.
Member Function Documentation
bottomRight()
sibr::Vector2f sibr::ZoomData::bottomRight () const
Returns
the zoomed region bottom right corner in image space.
Definition at line 139 of file GUI.cpp.
References center, and diagonal.
Referenced by sibr::ImageWithZoom(), sibr::VideoPlayer::onGui(), and sibr::ZoomInterraction::updateZoom().
scaled()
ZoomData sibr::ZoomData::scaled (const sibr::Vector2f & size) const
Rescale zoom data using a reference region size.
Parameters
size the region size
Returns
the resized data
Definition at line 146 of file GUI.cpp.
References center, and diagonal.
Referenced by sibr::SegmentSelection::update(), and sibr::ZoomInterraction::updateZoom().
topLeft()
sibr::Vector2f sibr::ZoomData::topLeft () const
Returns
the zoomed region top left corner in image space.
Definition at line 138 of file GUI.cpp.
References center, and diagonal.
Referenced by sibr::ImageWithZoom(), sibr::VideoPlayer::onGui(), sibr::ZoomInterraction::updateZoom(), and uvFromBoxPos().
uvFromBoxPos()
sibr::Vector2f sibr::ZoomData::uvFromBoxPos (const sibr::Vector2f & pos) const
Convert pixel coordinates in UV, taking the zoom into account.
Parameters
pos the pixel position
Returns
the corresponding UVs
Definition at line 141 of file GUI.cpp.
References diagonal, and topLeft().
Referenced by sibr::SegmentSelection::update(), and sibr::ZoomInterraction::updateZoom().
Member Data Documentation
center
sibr::Vector2f sibr::ZoomData::center = sibr::Vector2f(0.5f, 0.5f)
Definition at line 143 of file GUI.hpp.
Referenced by bottomRight(), scaled(), topLeft(), and sibr::ZoomInterraction::updateZoom().
diagonal
sibr::Vector2f sibr::ZoomData::diagonal = sibr::Vector2f(0.5f, 0.5f)
Definition at line 143 of file GUI.hpp.
Referenced by bottomRight(), scaled(), topLeft(), sibr::ZoomInterraction::updateZoom(), and uvFromBoxPos().
firstClickPixel
sibr::Vector2f sibr::ZoomData::firstClickPixel
Definition at line 144 of file GUI.hpp.
Referenced by sibr::ZoomInterraction::updateZoom().
secondClickPixel
sibr::Vector2f sibr::ZoomData::secondClickPixel
Zoomed region corners and location.
Definition at line 144 of file GUI.hpp.
Referenced by sibr::ZoomInterraction::updateZoom().
tmpBottonRight
sibr::Vector2f sibr::ZoomData::tmpBottonRight
Definition at line 144 of file GUI.hpp.
Referenced by sibr::ZoomInterraction::updateZoom().
tmpTopLeft
sibr::Vector2f sibr::ZoomData::tmpTopLeft
Definition at line 144 of file GUI.hpp.
Referenced by sibr::ZoomInterraction::updateZoom().
underMofidication
bool sibr::ZoomData::underMofidication = false
Is the user currently zooming.
Definition at line 145 of file GUI.hpp.
Referenced by sibr::ZoomInterraction::updateZoom().
The documentation for this struct was generated from the following files:
src/core/graphics/GUI.hpp
src/core/graphics/GUI.cpp