SIBR: sibr::RectangleData Struct Reference
sibr::RectangleData Struct Reference
#include <InterfaceUtils.h>
Public Member Functions
RectangleData ()
sibr::Vector2f br () const
sibr::Vector2f tl () const
Public Attributes
sibr::Vector2f center
sibr::Vector2f diagonal
Detailed Description
Definition at line 124 of file InterfaceUtils.h.
Constructor & Destructor Documentation
RectangleData()
sibr::RectangleData::RectangleData () inline
Definition at line 126 of file InterfaceUtils.h.
Member Function Documentation
br()
sibr::Vector2f sibr::RectangleData::br () const inline
Definition at line 129 of file InterfaceUtils.h.
References center, and diagonal.
Referenced by sibr::MultiViewInterface::displayImages(), sibr::MultiViewInterface::pixFromScreenPos(), sibr::MultiViewInterface::screenPos(), sibr::MultiViewInterface::screenPosPixelCenter(), sibr::MultiViewInterface::updateCenter(), sibr::MultiViewInterface::updateDrag(), and sibr::MultiViewInterface::updateZoomBox().
tl()
sibr::Vector2f sibr::RectangleData::tl () const inline
Definition at line 130 of file InterfaceUtils.h.
References center, and diagonal.
Referenced by sibr::MultiViewInterface::displayImages(), sibr::MultiViewInterface::pixFromScreenPos(), sibr::MultiViewInterface::screenPos(), sibr::MultiViewInterface::screenPosPixelCenter(), sibr::MultiViewInterface::updateCenter(), sibr::MultiViewInterface::updateDrag(), and sibr::MultiViewInterface::updateZoomBox().
Member Data Documentation
center
sibr::Vector2f sibr::RectangleData::center
Definition at line 127 of file InterfaceUtils.h.
Referenced by br(), tl(), sibr::MultiViewInterface::updateCenter(), sibr::MultiViewInterface::updateDrag(), and sibr::MultiViewInterface::updateZoomBox().
diagonal
sibr::Vector2f sibr::RectangleData::diagonal
Definition at line 128 of file InterfaceUtils.h.
Referenced by br(), tl(), sibr::MultiViewInterface::updateZoomBox(), and sibr::MultiViewInterface::updateZoomScroll().
The documentation for this struct was generated from the following file:
src/core/view/interface/InterfaceUtils.h