SIBR: sibr::AppArgs Struct Reference
sibr::AppArgs Struct Reference
sibr_system
Hierarchy of Args classes that can be seens as modules, and can be combined using virtual inheritance, with no duplication of code so derived Args has no extra work to do Assuming CommandLineArgs::parseMainArgs() was called once, Args arguments will be automatically initialized with the value from the command line by the constructor Existing Args structs should cover most of the existing IBR apps To add a new argument like –my-arg 5 on top of existing arguments and to add a new required argument like –important-param "on" on top of existing arguments, do the following:
#include <CommandLineArgs.hpp>
Public Member Functions
AppArgs ()
Constructor.
void displayHelpIfRequired () const
Helper to print the help message if the help argument was passed.
Public Attributes
std::string appName
std::string appPath
Arg< std::string > custom_app_path = { "appPath", "./", "define a custom app path" }
Arg< bool > showHelp = {"help", "display this help message"}
Arg< bool > noExit = {"noExit", "dont exit after rendering path "}
Arg< std::string > pathFile = { "pathFile", "", "filename of path to render offline; app renders path and exits" }
Arg< std::string > outPath = { "outPath", "pathOutput", "Path of directory to store path output default relative the input path directory " }
Detailed Description
Hierarchy of Args classes that can be seens as modules, and can be combined using virtual inheritance, with no duplication of code so derived Args has no extra work to do Assuming CommandLineArgs::parseMainArgs() was called once, Args arguments will be automatically initialized with the value from the command line by the constructor Existing Args structs should cover most of the existing IBR apps To add a new argument like –my-arg 5 on top of existing arguments and to add a new required argument like –important-param "on" on top of existing arguments, do the following:
struct SIBR_SYSTEM_EXPORT MyArgs : virtual ExistingArg1, virtual ExistingArgs2, ... { Arg<int> myParameter = { "my-arg", some_default_value }; RequiredArg<std::string> myRequiredParameter = { "important-param" }; }
Definition at line 331 of file CommandLineArgs.hpp.
Constructor & Destructor Documentation
AppArgs()
sibr::AppArgs::AppArgs ()
Constructor.
Definition at line 124 of file CommandLineArgs.cpp.
References appName, appPath, sibr::CommandLineArgs::getGlobal(), and sibr::CommandLineArgs::getRequired().
Member Function Documentation
displayHelpIfRequired()
void sibr::AppArgs::displayHelpIfRequired () const
Helper to print the help message if the help argument was passed.
Definition at line 131 of file CommandLineArgs.cpp.
References sibr::CommandLineArgs::displayHelp(), sibr::ArgBase< T >::get(), sibr::getCommandLineArgs(), and showHelp.
Referenced by main().
Member Data Documentation
appName
std::string sibr::AppArgs::appName
Definition at line 335 of file CommandLineArgs.hpp.
Referenced by AppArgs().
appPath
std::string sibr::AppArgs::appPath
Definition at line 336 of file CommandLineArgs.hpp.
Referenced by AppArgs().
custom_app_path
Arg<std::string> sibr::AppArgs::custom_app_path = { "appPath", "./", "define a custom app path" }
Definition at line 337 of file CommandLineArgs.hpp.
noExit
Arg<bool> sibr::AppArgs::noExit = {"noExit", "dont exit after rendering path "}
Definition at line 344 of file CommandLineArgs.hpp.
Referenced by legacyV1main(), legacyV2main(), and main().
outPath
Arg<std::string> sibr::AppArgs::outPath = { "outPath", "pathOutput", "Path of directory to store path output default relative the input path directory " }
Definition at line 346 of file CommandLineArgs.hpp.
Referenced by legacyV1main(), legacyV2main(), and main().
pathFile
Arg<std::string> sibr::AppArgs::pathFile = { "pathFile", "", "filename of path to render offline; app renders path and exits" }
Definition at line 345 of file CommandLineArgs.hpp.
Referenced by legacyV1main(), legacyV2main(), and main().
showHelp
Arg<bool> sibr::AppArgs::showHelp = {"help", "display this help message"}
Definition at line 338 of file CommandLineArgs.hpp.
Referenced by displayHelpIfRequired().
The documentation for this struct was generated from the following files:
src/core/system/CommandLineArgs.hpp
src/core/system/CommandLineArgs.cpp