SIBR: sibr::KeyCombination Struct Reference
sibr::KeyCombination Struct Reference
Helper keeping track of the number of keys currently pressed.
#include <Input.hpp>
Public Member Functions
KeyCombination ()
Default constructor.
KeyCombination (int n, bool b)
Constructor.
operator bool () const
Public Attributes
int numKeys
Number of pressed keys.
bool isTrue
Activations status.
Detailed Description
Helper keeping track of the number of keys currently pressed.
Definition at line 173 of file Input.hpp.
Constructor & Destructor Documentation
KeyCombination() [1/2]
sibr::KeyCombination::KeyCombination ()
Default constructor.
Definition at line 49 of file Input.cpp.
KeyCombination() [2/2]
sibr::KeyCombination::KeyCombination (int n, bool b)
Constructor.
Parameters
n number of keys pressed
b are they active or not
Definition at line 50 of file Input.cpp.
Member Function Documentation
operator bool()
sibr::KeyCombination::operator bool () const
Returns
true if they are numKeys pressed keys and their combination is active.
Definition at line 52 of file Input.cpp.
References sibr::InputState< TNbState, TEnum >::getNumActivated(), sibr::Input::global(), and sibr::Input::key().
Member Data Documentation
isTrue
bool sibr::KeyCombination::isTrue
Activations status.
Definition at line 188 of file Input.hpp.
Referenced by sibr::operator&&().
numKeys
int sibr::KeyCombination::numKeys
Number of pressed keys.
Definition at line 187 of file Input.hpp.
Referenced by sibr::operator&&().
The documentation for this struct was generated from the following files:
src/core/graphics/Input.hpp
src/core/graphics/Input.cpp