SIBR: sibr::LabelsManager Struct Reference
sibr::LabelsManager Struct Reference
sibr_view
Helper used to display camera labels on screen.
#include <SceneDebugView.hpp>
Classes
struct CameraInfos
Displayed cameras info.
struct LabelMesh
Label geometry info.
Protected Member Functions
void setupLabelsManagerShader ()
Initialize the shaders.
void setupLabelsManagerMeshes (const std::vector< InputCamera::Ptr > &cams)
Generate labels data based on input camera informations.
void renderLabels (const Camera &eye, const Viewport &vp, const std::vector< CameraInfos > &cams_info)
Render the camera labels.
Protected Attributes
std::map< unsigned int, LabelMesh > _labelMeshes
Generated geometry for each label.
GLShader _labelShader
Shader.
GLuniform< Vector3f > _labelShaderPosition
Uniform for the label position.
GLuniform< float > _labelShaderScale = 1.0f
Uniform for the label scale (used twice per label, with different values derived from _labelScale).
GLuniform< Vector2f > _labelShaderViewport
The viewport of the view, for ratio adjustment.
float _labelScale = 1.0f
The label scale ons creen.
Detailed Description
Helper used to display camera labels on screen.
Internally use ImGui to generate labels data.
Definition at line 49 of file SceneDebugView.hpp.
Member Function Documentation
renderLabels()
void sibr::LabelsManager::renderLabels (const Camera & eye, const Viewport & vp, const std::vector< CameraInfos > & cams_info) protected
Render the camera labels.
Parameters
eye the current viewpoint
vp the view viewport
cams_info the current state of the cameras.
Todo:
Get rid of the viewport if possible.
Definition at line 99 of file SceneDebugView.cpp.
References _labelMeshes, _labelScale, _labelShader, _labelShaderPosition, _labelShaderScale, _labelShaderViewport, sibr::GLShader::begin(), sibr::GLShader::end(), sibr::Viewport::finalHeight(), sibr::Viewport::finalWidth(), sibr::Camera::frustumTest(), sibr::Camera::project(), and sibr::GLuniform< T >::set().
Referenced by sibr::SceneDebugView::onRender().
setupLabelsManagerMeshes()
void sibr::LabelsManager::setupLabelsManagerMeshes (const std::vector< InputCamera::Ptr > & cams) protected
Generate labels data based on input camera informations.
Parameters
cams the cameras
Definition at line 88 of file SceneDebugView.cpp.
References _labelMeshes, and sibr::generateMeshForText().
Referenced by sibr::SceneDebugView::setup().
setupLabelsManagerShader()
void sibr::LabelsManager::setupLabelsManagerShader () protected
Initialize the shaders.
Definition at line 78 of file SceneDebugView.cpp.
References _labelShader, _labelShaderPosition, _labelShaderScale, _labelShaderViewport, sibr::GLuniform< T >::init(), sibr::GLShader::init(), sibr::Resources::Instance(), and sibr::loadFile().
Referenced by sibr::SceneDebugView::SceneDebugView().
Member Data Documentation
_labelMeshes
std::map<unsigned int, LabelMesh> sibr::LabelsManager::_labelMeshes protected
Generated geometry for each label.
Definition at line 92 of file SceneDebugView.hpp.
Referenced by renderLabels(), and setupLabelsManagerMeshes().
_labelScale
float sibr::LabelsManager::_labelScale = 1.0f protected
The label scale ons creen.
Definition at line 97 of file SceneDebugView.hpp.
Referenced by sibr::SceneDebugView::gui_options(), and renderLabels().
_labelShader
GLShader sibr::LabelsManager::_labelShader protected
Shader.
Definition at line 93 of file SceneDebugView.hpp.
Referenced by renderLabels(), and setupLabelsManagerShader().
_labelShaderPosition
GLuniform<Vector3f> sibr::LabelsManager::_labelShaderPosition protected
Uniform for the label position.
Definition at line 94 of file SceneDebugView.hpp.
Referenced by renderLabels(), and setupLabelsManagerShader().
_labelShaderScale
GLuniform<float> sibr::LabelsManager::_labelShaderScale = 1.0f protected
Uniform for the label scale (used twice per label, with different values derived from _labelScale).
Definition at line 95 of file SceneDebugView.hpp.
Referenced by renderLabels(), and setupLabelsManagerShader().
_labelShaderViewport
GLuniform<Vector2f> sibr::LabelsManager::_labelShaderViewport protected
The viewport of the view, for ratio adjustment.
Definition at line 96 of file SceneDebugView.hpp.
Referenced by renderLabels(), and setupLabelsManagerShader().
The documentation for this struct was generated from the following files:
src/core/view/SceneDebugView.hpp
src/core/view/SceneDebugView.cpp