SIBR: sibr::MultipleVideoDecoder< T, N > Struct Template Reference
sibr::MultipleVideoDecoder< T, N > Struct Template Reference
sibr_video
Batch decoding of multiple videos at the same time, stored in a texture array.
#include <MultipleVideoDecoder.hpp>
Public Types
using TexArray = sibr::Texture2DArray< T, N >
using TexArrayPtr = typename TexArray::Ptr
Public Member Functions
void update (const std::vector< sibr::VideoPlayer::Ptr > &videos)
Update a set of video players to the next frame.
void updateCPU (const std::vector< sibr::VideoPlayer::Ptr > &videos)
Load the next frame on the CPU for a set of video players.
void updateGPU (const std::vector< sibr::VideoPlayer::Ptr > &videos)
Upload the next frame to the GPU for a set of video players.
TexArrayPtr & getLoadingTexArray ()
const TexArrayPtr & getDisplayTexArray () const
Public Attributes
bool first = true
First frame.
int loadingTexArray = 1
int displayTexArray = 1
Texture indices.
TexArrayPtr ping
TexArrayPtr pong
Textures.
Detailed Description
template<typename T, uint N>
struct sibr::MultipleVideoDecoder< T, N >
Batch decoding of multiple videos at the same time, stored in a texture array.
Definition at line 45 of file MultipleVideoDecoder.hpp.
Member Typedef Documentation
TexArray
template<typename T , uint N> using sibr::MultipleVideoDecoder< T, N >::TexArray = sibr::Texture2DArray<T,N>
Definition at line 46 of file MultipleVideoDecoder.hpp.
TexArrayPtr
template<typename T , uint N> using sibr::MultipleVideoDecoder< T, N >::TexArrayPtr = typename TexArray::Ptr
Definition at line 47 of file MultipleVideoDecoder.hpp.
Member Function Documentation
getDisplayTexArray()
template<typename T , uint N> const TexArrayPtr& sibr::MultipleVideoDecoder< T, N >::getDisplayTexArray () const inline
Returns
the current display texture array.
Definition at line 105 of file MultipleVideoDecoder.hpp.
References sibr::MultipleVideoDecoder< T, N >::displayTexArray, sibr::MultipleVideoDecoder< T, N >::ping, and sibr::MultipleVideoDecoder< T, N >::pong.
getLoadingTexArray()
template<typename T , uint N> TexArrayPtr& sibr::MultipleVideoDecoder< T, N >::getLoadingTexArray () inline
Returns
the current loading texture array.
Definition at line 102 of file MultipleVideoDecoder.hpp.
References sibr::MultipleVideoDecoder< T, N >::loadingTexArray, sibr::MultipleVideoDecoder< T, N >::ping, and sibr::MultipleVideoDecoder< T, N >::pong.
Referenced by sibr::MultipleVideoDecoder< T, N >::updateGPU(), and sibr::MultipleVideoDecoderArray< T, N >::updateGPU().
update()
template<typename T , uint N> void sibr::MultipleVideoDecoder< T, N >::update (const std::vector< sibr::VideoPlayer::Ptr > & videos) inline
Update a set of video players to the next frame.
Parameters
videos the video players to udpate
Note
Internally calls both updateCPU and updateGPU.
Definition at line 53 of file MultipleVideoDecoder.hpp.
References sibr::MultipleVideoDecoder< T, N >::displayTexArray, sibr::MultipleVideoDecoder< T, N >::first, sibr::MultipleVideoDecoder< T, N >::loadingTexArray, sibr::MultipleVideoDecoder< T, N >::updateCPU(), and sibr::MultipleVideoDecoder< T, N >::updateGPU().
updateCPU()
template<typename T , uint N> void sibr::MultipleVideoDecoder< T, N >::updateCPU (const std::vector< sibr::VideoPlayer::Ptr > & videos) inline
Load the next frame on the CPU for a set of video players.
Parameters
videos the video players to udpate
Definition at line 69 of file MultipleVideoDecoder.hpp.
Referenced by sibr::MultipleVideoDecoder< T, N >::update().
updateGPU()
template<typename T , uint N> void sibr::MultipleVideoDecoder< T, N >::updateGPU (const std::vector< sibr::VideoPlayer::Ptr > & videos) inline
Upload the next frame to the GPU for a set of video players.
Parameters
videos the video players to udpate
Definition at line 81 of file MultipleVideoDecoder.hpp.
References sibr::MultipleVideoDecoder< T, N >::getLoadingTexArray(), sibr::Key::N, and sibr::split().
Referenced by sibr::MultipleVideoDecoder< T, N >::update().
Member Data Documentation
displayTexArray
template<typename T , uint N> int sibr::MultipleVideoDecoder< T, N >::displayTexArray = 1
Texture indices.
Definition at line 108 of file MultipleVideoDecoder.hpp.
Referenced by sibr::MultipleVideoDecoder< T, N >::getDisplayTexArray(), sibr::MultipleVideoDecoder< T, N >::update(), and sibr::MultipleVideoDecoderArray< T, N >::update().
first
template<typename T , uint N> bool sibr::MultipleVideoDecoder< T, N >::first = true
First frame.
Definition at line 107 of file MultipleVideoDecoder.hpp.
Referenced by sibr::MultipleVideoDecoder< T, N >::update(), and sibr::MultipleVideoDecoderArray< T, N >::update().
loadingTexArray
template<typename T , uint N> int sibr::MultipleVideoDecoder< T, N >::loadingTexArray = 1
Definition at line 108 of file MultipleVideoDecoder.hpp.
Referenced by sibr::MultipleVideoDecoder< T, N >::getLoadingTexArray(), sibr::MultipleVideoDecoder< T, N >::update(), and sibr::MultipleVideoDecoderArray< T, N >::update().
ping
template<typename T , uint N> TexArrayPtr sibr::MultipleVideoDecoder< T, N >::ping
Definition at line 109 of file MultipleVideoDecoder.hpp.
Referenced by sibr::MultipleVideoDecoder< T, N >::getDisplayTexArray(), and sibr::MultipleVideoDecoder< T, N >::getLoadingTexArray().
pong
template<typename T , uint N> TexArrayPtr sibr::MultipleVideoDecoder< T, N >::pong
Textures.
Definition at line 109 of file MultipleVideoDecoder.hpp.
Referenced by sibr::MultipleVideoDecoder< T, N >::getDisplayTexArray(), and sibr::MultipleVideoDecoder< T, N >::getLoadingTexArray().
The documentation for this struct was generated from the following file:
src/core/video/MultipleVideoDecoder.hpp