SIBR: sibr::ValueGetter< T > Struct Template Reference
sibr::ValueGetter< T > Struct Template Reference
sibr_system
Helper to extract values from a vector of strings.
#include <CommandLineArgs.hpp>
Static Public Member Functions
static T get (const std::vector< std::string > &values, uint n)
Extract the N-th element from a vector of string representations.
static std::string toString (const T &value)
Convert an element to its string representation.
Detailed Description
template<typename T>
struct sibr::ValueGetter< T >
Helper to extract values from a vector of strings.
Definition at line 34 of file CommandLineArgs.hpp.
Member Function Documentation
get()
template<typename T > static T sibr::ValueGetter< T >::get (const std::vector< std::string > & values, uint n) static
Extract the N-th element from a vector of string representations.
Parameters
values a list of strings representing elements
n the index of the element to query
Returns
the element corresponding to the N-th string.
Referenced by sibr::ValueGetter< std::array< T, N > >::get(), sibr::ValueGetter< sibr::Vector< T, N > >::get(), and sibr::CommandLineArgs::getInternal().
toString()
template<typename T > static std::string sibr::ValueGetter< T >::toString (const T & value) static
Convert an element to its string representation.
Parameters
value the element to convert
Returns
the string representation
The documentation for this struct was generated from the following file:
src/core/system/CommandLineArgs.hpp