SIBR: sibr::ImageCamViewer Struct Reference
sibr::ImageCamViewer Struct Reference
sibr_view
Helper used to render image planes in front of the camera, for both scenes storing 2D separate images or a texture array.
#include <SceneDebugView.hpp>
Protected Member Functions
void initImageCamShaders ()
Initialize the shaders.
void renderImage (const Camera &eye, const InputCamera &cam, const std::vector< RenderTargetRGBA32F::Ptr > &rts, int cam_id)
Render one specific input image on a camera image plane.
void renderImage (const Camera &eye, const InputCamera &cam, uint tex2Darray_handle, int cam_id)
Render one specific input image on a camera image plane.
Protected Attributes
GLShader _shader2D
Shader for the 2D separate case.
GLShader _shaderArray
Shader for the texture array case.
GLuniform< sibr::Matrix4f > _mvp2D
GLuniform< sibr::Matrix4f > _mvpArray
MVP matrix.
GLuniform< float > _alpha2D = 1.0f
Opacity.
GLuniform< float > _alphaArray = 1.0f
Opacity.
GLuniform< int > _sliceArray = 1
Slice location (for the texture array case).
float _alphaImage = 0.5f
Opacity shared value.
float _cameraScaling = 0.8f
Camera scaling.
Detailed Description
Helper used to render image planes in front of the camera, for both scenes storing 2D separate images or a texture array.
Definition at line 105 of file SceneDebugView.hpp.
Member Function Documentation
initImageCamShaders()
void sibr::ImageCamViewer::initImageCamShaders () protected
Initialize the shaders.
Definition at line 138 of file SceneDebugView.cpp.
References sibr::Resources::Instance(), and sibr::loadFile().
renderImage() [1/2]
void sibr::ImageCamViewer::renderImage (const Camera & eye, const InputCamera & cam, const std::vector< RenderTargetRGBA32F::Ptr > & rts, int cam_id) protected
Render one specific input image on a camera image plane.
Parameters
eye the current viewpoint
cam the camera to show the image plane of
rts input 2D textures list
cam_id the list index associated to the camera
Definition at line 152 of file SceneDebugView.cpp.
References sibr::Mesh::FillRenderMode, sibr::generateCamQuadWithUvs(), and sibr::Camera::viewproj().
Referenced by sibr::SceneDebugView::onRender().
renderImage() [2/2]
void sibr::ImageCamViewer::renderImage (const Camera & eye, const InputCamera & cam, uint tex2Darray_handle, int cam_id) protected
Render one specific input image on a camera image plane.
Parameters
eye the current viewpoint
cam the camera to show the image plane of
tex2Darray_handle input images texture array
cam_id the array slice associated to the camera
Definition at line 167 of file SceneDebugView.cpp.
References sibr::Mesh::FillRenderMode, sibr::generateCamQuadWithUvs(), and sibr::Camera::viewproj().
Member Data Documentation
_alpha2D
GLuniform<float> sibr::ImageCamViewer::_alpha2D = 1.0f protected
Opacity.
Definition at line 131 of file SceneDebugView.hpp.
_alphaArray
GLuniform<float> sibr::ImageCamViewer::_alphaArray = 1.0f protected
Opacity.
Definition at line 132 of file SceneDebugView.hpp.
_alphaImage
float sibr::ImageCamViewer::_alphaImage = 0.5f protected
Opacity shared value.
Definition at line 134 of file SceneDebugView.hpp.
Referenced by sibr::SceneDebugView::gui_options().
_cameraScaling
float sibr::ImageCamViewer::_cameraScaling = 0.8f protected
Camera scaling.
Definition at line 135 of file SceneDebugView.hpp.
Referenced by sibr::SceneDebugView::gui_options(), sibr::SceneDebugView::onRender(), and sibr::SceneDebugView::onUpdate().
_mvp2D
GLuniform<sibr::Matrix4f> sibr::ImageCamViewer::_mvp2D protected
Definition at line 130 of file SceneDebugView.hpp.
_mvpArray
GLuniform<sibr::Matrix4f> sibr::ImageCamViewer::_mvpArray protected
MVP matrix.
Definition at line 130 of file SceneDebugView.hpp.
_shader2D
GLShader sibr::ImageCamViewer::_shader2D protected
Shader for the 2D separate case.
Definition at line 128 of file SceneDebugView.hpp.
_shaderArray
GLShader sibr::ImageCamViewer::_shaderArray protected
Shader for the texture array case.
Definition at line 129 of file SceneDebugView.hpp.
_sliceArray
GLuniform<int> sibr::ImageCamViewer::_sliceArray = 1 protected
Slice location (for the texture array case).
Definition at line 133 of file SceneDebugView.hpp.
The documentation for this struct was generated from the following files:
src/core/view/SceneDebugView.hpp
src/core/view/SceneDebugView.cpp