SIBR: sibr::UV< space > Struct Template Reference
sibr::UV< space > Struct Template Reference
sibr_view
#include <InterfaceUtils.h>
Public Member Functions
UV (float u, float v)
template<UVspace otherSpace>
operator UV< otherSpace > () const
Static Public Member Functions
static UV from (const sibr::Vector2f &v)
Detailed Description
template<UVspace space>
struct sibr::UV< space >
Definition at line 21 of file InterfaceUtils.h.
Constructor & Destructor Documentation
UV()
template<UVspace space> sibr::UV< space >::UV (float u, float v) inline
Definition at line 25 of file InterfaceUtils.h.
Referenced by sibr::UV< space >::from().
Member Function Documentation
from()
template<UVspace space> static UV sibr::UV< space >::from (const sibr::Vector2f & v) inline static
Definition at line 23 of file InterfaceUtils.h.
References sibr::UV< space >::UV().
Referenced by sibr::InterfaceUtilities::circlePixels(), sibr::MultiViewInterface::displayZoom(), sibr::InterfaceUtilities::linePixels(), sibr::MultiViewInterface::pixFromScreenPos(), sibr::InterfaceUtilities::rectanglePixels(), sibr::MultiViewInterface::screenPos(), and sibr::MultiViewInterface::screenPosPixelCenter().
operator UV< otherSpace >()
template<UVspace space> template<UVspace otherSpace> sibr::UV< space >::operator UV< otherSpace > () const
The documentation for this struct was generated from the following file:
src/core/view/interface/InterfaceUtils.h