SIBR: src/projects/ulr/apps/texturedMesh/main.cpp File Reference
main.cpp File Reference
#include <fstream>
#include <core/graphics/Window.hpp>
#include <core/view/MultiViewManager.hpp>
#include <projects/ulr/renderer/TexturedMeshView.hpp>
#include <core/scene/BasicIBRScene.hpp>
#include <core/raycaster/Raycaster.hpp>
#include <core/view/SceneDebugView.hpp>
Classes
struct TexturedMeshAppArgs
Macros
#define PROGRAM_NAME "sibr_texturedMesh_app"
Functions
int main (int ac, char **av)
Variables
const char * usage
Macro Definition Documentation
PROGRAM_NAME
#define PROGRAM_NAME "sibr_texturedMesh_app"
Definition at line 9 of file main.cpp.
Function Documentation
main()
int main (int ac, char ** av)
Definition at line 24 of file main.cpp.
References sibr::MultiViewBase::addCameraForView(), sibr::MultiViewBase::addIBRSubView(), sibr::Raycaster::addMesh(), sibr::MultiViewBase::addSubView(), CHECK_GL_ERROR, sibr::Window::close(), sibr::BasicDatasetArgs::dataset_path, sibr::Key::Escape, sibr::fileExists(), sibr::ArgBase< T >::get(), sibr::RequiredArgBase< T >::get(), sibr::Input::global(), sibr::Raycaster::init(), sibr::Window::isOpened(), sibr::Image< T_Type, T_NumComp >::load(), sibr::Window::makeContextCurrent(), TexturedMeshAppArgs::noScene, sibr::MultiViewManager::onRender(), sibr::MultiViewManager::onUpdate(), sibr::CommandLineArgs::parseMainArgs(), sibr::Input::poll(), PROGRAM_NAME, sibr::removeExtension(), sibr::RenderingArgs::rendering_size, SIBR_ERR, SIBR_GPU_LINEAR_SAMPLING, sibr::Window::swapBuffer(), TexturedMeshAppArgs::textureImagePath, sibr::WindowArgs::vsync, sibr::WindowArgs::win_height, and sibr::WindowArgs::win_width.
Variable Documentation
usage
const char* usage
Initial value:
= ""
    "Usage: " PROGRAM_NAME " -path <dataset-path or mesh-path>"                                     "\n"
Definition at line 12 of file main.cpp.