SIBR: src/projects/ulr/apps/ulrv2/main.cpp File Reference
main.cpp File Reference
#include <fstream>
#include <core/graphics/Window.hpp>
#include <core/view/MultiViewManager.hpp>
#include <core/system/String.hpp>
#include "projects/ulr/renderer/ULRView.hpp"
#include <projects/ulr/renderer/ULRV2View.hpp>
#include <projects/ulr/renderer/ULRV3View.hpp>
#include <core/renderer/DepthRenderer.hpp>
#include <core/raycaster/Raycaster.hpp>
#include <core/view/SceneDebugView.hpp>
Macros
#define PROGRAM_NAME "sibr_ulrv2_app"
Functions
int legacyV1main (ULRAppArgs &myArgs)
Use ULRV1 view and renderer.
int legacyV2main (ULRAppArgs &myArgs)
Use ULRV2 view and renderer.
int main (int ac, char **av)
Variables
const char * usage
Macro Definition Documentation
PROGRAM_NAME
#define PROGRAM_NAME "sibr_ulrv2_app"
Definition at line 15 of file main.cpp.
Function Documentation
legacyV1main()
int legacyV1main (ULRAppArgs & myArgs)
Use ULRV1 view and renderer.
Definition at line 321 of file main.cpp.
References sibr::MultiViewBase::addCameraForView(), sibr::MultiViewBase::addIBRSubView(), sibr::Raycaster::addMesh(), sibr::MultiViewBase::addSubView(), CHECK_GL_ERROR, sibr::Window::close(), sibr::Key::Escape, sibr::ArgBase< T >::get(), sibr::MultiViewBase::getIBRSubView(), sibr::Input::global(), sibr::Raycaster::init(), sibr::Window::isOpened(), sibr::Window::makeContextCurrent(), sibr::AppArgs::noExit, sibr::MultiViewManager::onRender(), sibr::MultiViewManager::onUpdate(), sibr::AppArgs::outPath, sibr::AppArgs::pathFile, sibr::Input::poll(), PROGRAM_NAME, sibr::RenderingArgs::rendering_size, sibr::Window::swapBuffer(), sibr::WindowArgs::vsync, sibr::WindowArgs::win_height, and sibr::WindowArgs::win_width.
Referenced by main().
legacyV2main()
int legacyV2main (ULRAppArgs & myArgs)
Use ULRV2 view and renderer.
Definition at line 152 of file main.cpp.
References sibr::DepthRenderer::_depth_RT, sibr::MultiViewBase::addCameraForView(), sibr::MultiViewBase::addIBRSubView(), sibr::Raycaster::addMesh(), sibr::MultiViewBase::addSubView(), sibr::ULRAppArgs::alphas, CHECK_GL_ERROR, sibr::Window::close(), sibr::convertRGBAtoL32F(), sibr::Texture2DArray< T_Type, T_NumComp >::createFromImages(), sibr::Key::Escape, sibr::ArgBase< T >::get(), sibr::MultiViewBase::getIBRSubView(), sibr::Input::global(), sibr::InputCamera::h(), sibr::Raycaster::init(), sibr::ULRAppArgs::invert, sibr::Window::isOpened(), sibr::Window::makeContextCurrent(), sibr::ULRAppArgs::maskParams, sibr::ULRAppArgs::masks, sibr::AppArgs::noExit, sibr::MultiViewManager::onRender(), sibr::MultiViewManager::onUpdate(), sibr::AppArgs::outPath, sibr::AppArgs::pathFile, sibr::ULRAppArgs::poisson, sibr::Input::poll(), sibr::Camera::position(), PROGRAM_NAME, sibr::DepthRenderer::render(), sibr::RenderingArgs::rendering_size, SIBR_FLIP_TEXTURE, SIBR_GPU_LINEAR_SAMPLING, sibr::ULRAppArgs::softVisibility, sibr::Window::swapBuffer(), sibr::toOpenCV(), sibr::InputCamera::unprojectImgSpaceInvertY(), sibr::WindowArgs::vsync, sibr::InputCamera::w(), sibr::WindowArgs::win_height, sibr::WindowArgs::win_width, and sibr::Key::Z.
Referenced by main().
main()
int main (int ac, char ** av)
Definition at line 27 of file main.cpp.
References sibr::MultiViewBase::addCameraForView(), sibr::MultiViewBase::addIBRSubView(), sibr::Raycaster::addMesh(), sibr::MultiViewBase::addSubView(), CHECK_GL_ERROR, sibr::Window::close(), sibr::AppArgs::displayHelpIfRequired(), sibr::Key::Escape, sibr::ArgBase< T >::get(), sibr::MultiViewBase::getIBRSubView(), sibr::getResourcesDirectory(), sibr::Input::global(), sibr::Raycaster::init(), sibr::Window::isOpened(), legacyV1main(), legacyV2main(), sibr::Window::makeContextCurrent(), sibr::ULRAppArgs::maskParams, sibr::ULRAppArgs::maskParamsExtra, sibr::ULRAppArgs::masks, sibr::AppArgs::noExit, sibr::MultiViewManager::onRender(), sibr::MultiViewManager::onUpdate(), sibr::AppArgs::outPath, sibr::CommandLineArgs::parseMainArgs(), sibr::AppArgs::pathFile, sibr::Input::poll(), PROGRAM_NAME, sibr::RenderingArgs::rendering_size, SIBR_FLIP_TEXTURE, SIBR_GPU_LINEAR_SAMPLING, sibr::Window::swapBuffer(), sibr::ULRAppArgs::version, sibr::WindowArgs::vsync, sibr::WindowArgs::win_height, and sibr::WindowArgs::win_width.
Variable Documentation
usage
const char* usage
Initial value:
= ""
"Usage: " PROGRAM_NAME " -path <dataset-path>"                                      "\n"
Definition at line 18 of file main.cpp.