SIBR: src/core/assets/UVUnwrapper.cpp File Reference
UVUnwrapper.cpp File Reference
#include "UVUnwrapper.hpp"
#include <core/system/SimpleTimer.hpp>
#include <core/graphics/Utils.hpp>
#include "xatlas.h"
Functions
int printCallback (const char *format,...)
bool progressCallback (xatlas::ProgressCategory category, int progress, void *userData)
void setPixel (uint8_t *dest, int destWidth, int x, int y, const sibr::Vector3ub &color)
static void rasterizeLine (uint8_t *dest, int destWidth, const int *p1, const int *p2, const sibr::Vector3ub &color)
void rasterizeTriangle (uint8_t *dest, int destWidth, const int *t0, const int *t1, const int *t2, const sibr::Vector3ub &color)
Function Documentation
printCallback()
int printCallback (const char * format, ...)
Definition at line 6 of file UVUnwrapper.cpp.
Referenced by sibr::UVUnwrapper::UVUnwrapper().
progressCallback()
bool progressCallback (xatlas::ProgressCategory category, int progress, void * userData)
Definition at line 15 of file UVUnwrapper.cpp.
Referenced by sibr::UVUnwrapper::UVUnwrapper().
rasterizeLine()
static void rasterizeLine (uint8_t * dest, int destWidth, const int * p1, const int * p2, const sibr::Vector3ub & color) static
Definition at line 35 of file UVUnwrapper.cpp.
References setPixel().
Referenced by sibr::UVUnwrapper::atlasVisualization().
rasterizeTriangle()
void rasterizeTriangle (uint8_t * dest, int destWidth, const int * t0, const int * t1, const int * t2, const sibr::Vector3ub & color)
Definition at line 64 of file UVUnwrapper.cpp.
References sibr::Key::A, sibr::Key::B, and setPixel().
Referenced by sibr::UVUnwrapper::atlasVisualization().
setPixel()
void setPixel (uint8_t * dest, int destWidth, int x, int y, const sibr::Vector3ub & color)
Definition at line 26 of file UVUnwrapper.cpp.
Referenced by rasterizeLine(), and rasterizeTriangle().